- .github/ISSUE_TEMPLATE/config.yml
To have links to the docs and slack directly on GitHub when creating a new issue
#
#
</p>
#
#
> Add issue config.yml

- ingestion/src/metadata/ingestion/source/database/vertica/metadata.py
- ingestion/src/metadata/ingestion/source/database/vertica/queries.py
- ingestion/src/metadata/utils/sqlalchemy_utils.py
Fix #10263: Fetch Vertica Schema Comments
#
#
#
> Fix #10263: Fetch Vertica Schema Comments

- ingestion/src/metadata/ingestion/connections/builders.py
- ingestion/src/metadata/ingestion/source/database/clickhouse/connection.py
- ingestion/src/metadata/ingestion/source/database/deltalake/connection.py
- ingestion/src/metadata/ingestion/source/database/hive/connection.py
- ingestion/src/metadata/ingestion/source/database/mysql/connection.py
- ingestion/src/metadata/ingestion/source/database/postgres/connection.py
- ingestion/src/metadata/ingestion/source/database/redshift/connection.py
- ingestion/src/metadata/ingestion/source/messaging/kafka/connection.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/clickhouseConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/deltaLakeConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/hiveConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/mysqlConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/postgresConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/redshiftConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/messaging/kafkaConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/messaging/redpandaConnection.json
Fix #8981 & fix #7468: Move Connection Options and Connection Args to main properties
#
#
#
> Fix #8981: Move Connection Options and Connection Args to main properties

- openmetadata-docs/content/deployment/security/amazon-cognito-sso/kubernetes.md
- openmetadata-docs/content/deployment/security/auth0/kubernetes.md
- openmetadata-docs/content/deployment/security/azure/kubernetes.md
- openmetadata-docs/content/deployment/security/custom-oidc/kubernetes.md
- openmetadata-docs/content/deployment/security/google/kubernetes.md
- openmetadata-docs/content/deployment/security/keycloak/kubernetes.md
- openmetadata-docs/content/deployment/security/okta/kubernetes.md
- openmetadata-docs/content/deployment/security/one-login/kubernetes.md
Looking at few of the past support requests, it seems people are missing JWT Token Endpoint while configuring SSO with OpenMetadata in k8s. Updated the Configs to include the default url for JWT Token as well.
#
#
</p>
#
#
> fix: docs for k8s publicKeys

- .github/workflows/openmetadata-airflow-apis.yml
- .github/workflows/py-checkstyle.yml
- .github/workflows/py-cli-e2e-tests.yml
- .github/workflows/py-generate.yml
- .github/workflows/py-ingestion-core-publish.yml
- .github/workflows/py-ingestion-publish.yml
- .github/workflows/py-tests.yml
This is a fix for the CI which are failing for python - 
One of the PR is - https://github.com/open-metadata/OpenMetadata/pull/10387
> Updated the command for ubuntu dependencies

- openmetadata-ui/src/main/resources/ui/src/components/BotListV1/BotListV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/EmptyGraphPlaceholder.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Services/Services.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/UserList/UserListV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/error-with-placeholder/ErrorPlaceHolder.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts
- openmetadata-ui/src/main/resources/ui/src/enums/common.enum.ts
- openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesListPage/PoliciesListPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesListPage/RolesListPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TestSuitePage/TestSuitePage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/services/ServicesPage.tsx
- Issue: https://github.com/open-metadata/OpenMetadata/issues/9819#issuecomment-1435167307
- Change Empty Placeholder 
#
#
#
#
> chore(ui) : Change ErrorPlace holder in Data Insight Page

- openmetadata-docs/content/connectors/messaging/kafka/troubleshooting.md
Fix broken image link in the docs.
> Fix: broken image link in Kafka docs

- ingestion/src/metadata/ingestion/source/database/bigquery/lineage.py
- ingestion/src/metadata/ingestion/source/database/bigquery/query_parser.py
- ingestion/src/metadata/ingestion/source/database/bigquery/usage.py
- ingestion/src/metadata/ingestion/source/database/mssql/lineage.py
- ingestion/src/metadata/ingestion/source/database/mssql/usage.py
- ingestion/src/metadata/ingestion/source/database/postgres/lineage.py
- ingestion/src/metadata/ingestion/source/database/postgres/query_parser.py
- ingestion/src/metadata/ingestion/source/database/postgres/usage.py
- ingestion/src/metadata/ingestion/source/database/query_parser_source.py
- ingestion/src/metadata/ingestion/source/database/redshift/lineage.py
- ingestion/src/metadata/ingestion/source/database/redshift/queries.py
- ingestion/src/metadata/ingestion/source/database/redshift/query_parser.py
- ingestion/src/metadata/ingestion/source/database/redshift/usage.py
- ingestion/src/metadata/ingestion/source/database/snowflake/lineage.py
- ingestion/src/metadata/ingestion/source/database/snowflake/query_parser.py
- ingestion/src/metadata/ingestion/source/database/snowflake/usage.py
- ingestion/tests/unit/test_usage_filter.py
Fix #10292: Remove DB & Schema Usage Filters
#
#
#
> Fix #10292: Remove DB & Schema Usage Filters

- .github/teams.yml
Added Karan & Dhruvin to team so that PR checks starts
> chore(workflow): add Karan & Dhruvin to team

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/ActivityThreadList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/AnnouncementThreads.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightDetail.less
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/datasetDetails.style.less
- openmetadata-ui/src/main/resources/ui/src/components/EntityList/EntityList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyAssetStats/MyAssetStats.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/ProfilerDetailsCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/RecentSearchedTerms/RecentSearchedTermsAntd.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Services/Services.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/TableProfilerChart.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/teams.less
- openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/containers/PageLayout.tsx
- openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Feeds.constants.ts
- openmetadata-ui/src/main/resources/ui/src/pages/forgot-password/forgot-password.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/login/index.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- openmetadata-ui/src/main/resources/ui/src/styles/components/card.less
- openmetadata-ui/src/main/resources/ui/src/styles/components/table.less
- openmetadata-ui/src/main/resources/ui/src/styles/layout/page-layout.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
- Issue: https://github.com/open-metadata/OpenMetadata/issues/9819#issuecomment-1410908431
- Set Border-radius to 4px across cards
- Different shadow for left panel and cards
#
#
#
#
> chore(ui): UI improvements for same Border Radius

- openmetadata-docs/content/deployment/security/enable-jwt-tokens.md
> [DOCS] Add key pairs configurations for docker and kubernetes

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseSchemaResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/entity/data/databaseSchema.json
Added tags to Schema Level
#
#
#
> add tags to schema Level

- ingestion/src/metadata/ingestion/processor/pii.py
I worked on fixing import error presidio
#
> fix: scoped import for presidio

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/FeedListBody.less
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/AnnouncementThreads.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/announcement.less
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/datasetDetails.style.less
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/EntitySummaryPanel.style.less
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelFeaturesList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/ProfilerDetailsCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ServiceConnectionDetails/ServiceConnectionDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/TableProfilerChart.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/tableProfiler.less
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardV2.less
- openmetadata-ui/src/main/resources/ui/src/constants/entity.constants.ts
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- openmetadata-ui/src/main/resources/ui/src/styles/components/card.less
- openmetadata-ui/src/main/resources/ui/src/styles/components/glossary.less
- openmetadata-ui/src/main/resources/ui/src/styles/components/size.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
- Issue : https://github.com/open-metadata/OpenMetadata/issues/9819#issuecomment-1410903193
- UI improvements for cards and box shadow
#
#
#
#
> chore(ui): UI improvements for cards and box shadow

- openmetadata-docs/content/sdk/java/index.md
Add a link to the demo repo with more examples of the Java SDK.
> Doc: Add Java SDK examples to the documentation

- openmetadata-ui/src/main/resources/ui/src/components/common/facetfilter/FacetFilter.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/facetfilter/FacetFilter.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
- Issue: https://github.com/open-metadata/OpenMetadata/issues/9819#issuecomment-1427810035
- Sorted tier filters in explore Leftpanel
#
#
#
#
> UI : Sorted tier filters in explore Leftpanel

- ingestion/tests/integration/ometa/test_ometa_objectstore_api.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
- openmetadata-spec/src/main/resources/json/schema/entity/data/container.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/objectstore/azureObjectStoreConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/objectstore/gcsObjectStoreConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/objectstore/s3ObjectStoreConnection.json
- The container was missing the `serviceType` property.
- Added some tests in the OMeta side for the ingestion
- Updated the Title of the service connections to have cleaner class names in Python
Thanks
#
#
</p>
#
#
> Add service type to container & ometa tests

- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/bigquery.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/postgres.spec.js
Fixed biqQuery and postgres cypress test
#
#
</p>
#
#
> fixed bigquery and postgres cypress test

- CONTRIBUTING.md
> Update CONTRIBUTING.md to fix Slack link

- ingestion/tests/cli_e2e/test_cli_mysql.py
> Fix mysql e2e tests after adding new tables

- ingestion/setup.py
Downgraded python confluent-kafka library
#
#
</p>
#
#
> Downgraded python confluent-kafka library

- ingestion/setup.py
- ingestion/src/metadata/ingestion/processor/pii.py
- ingestion/src/metadata/profiler/profiler/core.py
I worked on changing spacy model
#
> fix: spacy model

- ingestion/src/metadata/interfaces/sqalchemy/sqa_profiler_interface.py
- ingestion/src/metadata/orm_profiler/metrics/system/system.py
Merge profiler bugs fix to 0.13.2.
#
> fix: handle overflow in profiler

- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
Fix case when `owner` is None
#
#
> fix: handle None `owner`

- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionRecentRun/IngestionRecentRuns.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/ingestion.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/ingestionPipelineAPI.ts
Closes: #10318 
#
#
https://user-images.githubusercontent.com/12962843/224231282-f8a47917-bbd5-49a5-8384-24a1953c9774.mov
#
#
> fix(ui): update recent runs instead whole page

- ingestion/src/metadata/ingestion/source/database/postgres/queries.py
I worked on adding quotes around alias in queries.
Fix: #10312 
#
> adding quotes around alias

- ingestion/src/metadata/ingestion/source/pipeline/nifi/client.py
- ingestion/src/metadata/ingestion/source/pipeline/nifi/connection.py
- ingestion/tests/unit/topology/pipeline/test_nifi.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/pipeline/nifiConnection.json
Add support for nifi client certificate auth
#
#
> Fixes #10498 - Add support for nifi client certificate auth.

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/EntityDetails.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/ContainerDetail/ContainerDataModel/ContainerDataModel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SummaryList/SummaryListItems/SummaryListItems.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsViewer/tags-viewer.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicSchema/TopicSchema.tsx
- openmetadata-ui/src/main/resources/ui/src/components/VersionTable/VersionTable.component.tsx
Closes #10500 
I worked on issue #10500.
#
#
https://user-images.githubusercontent.com/59080942/224303972-a6eaee17-89be-4205-bf97-83c025bc2fd2.mov
#
#
> fix(#10500): When the tier is removed all tags are also removed.

- ingestion/tests/cli_e2e/test_cli_dbt_redshift.py
Fixed dbt e2e filter test
#
#
#
> Fixed dbt e2e filter test

- ingestion/operators/docker/exit_handler.py
- ingestion/operators/docker/main.py
- ingestion/operators/docker/test_connection.py
Add the exit handler script to be used as an exit call for the Argo Workflows. It will be used to update the status if the workflow init fails or Argo explodes during the execution
#
#
</p>
#
#
> Prepare exit handler & Add missing arg to test connection

- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/ingestion/source/database/database_service.py
- ingestion/tests/unit/profiler/test_profiler.py
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseSchemaResource.java
- openmetadata-spec/src/main/resources/json/schema/api/data/createDatabaseSchema.json
> Add Labels on DatabaseSchema Level

- openmetadata-service/src/main/java/org/openmetadata/service/util/ElasticSearchIndexUtil.java
- openmetadata-spec/src/main/resources/json/schema/api/createEventPublisherJob.json
- Add Language Option in Reindexing for Elastic Search 
#
#
#
> Add Indexing Mapping Language in Reindexing

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js
- Fix cypress for tags
#
#
#
#
> UI : Fix cypress for tags

- ingestion/src/metadata/data_insight/processor/web_analytic_report_data_processor.py
- ingestion/tests/integration/data_insight/test_data_insight_workflow.py
Implements logic to exclude traffic from table owner when reporting page view metrics by entity
#
#
> fix: exclude owner from page view traffic in DI

- openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/explore.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/explore/ExplorePage.component.tsx
- Change Explore Placeholder when ES failed
#
#
#
#
> UI : Change Explore Placeholder when ES failed

- openmetadata-docs/content/overview/releases/latest-release.md
The last release date could confuse users and make them think the project has been unmaintained.
> Fix misleading date in documentation

- ingestion/src/metadata/ingestion/source/dashboard/quicksight/metadata.py
- ingestion/tests/unit/topology/dashboard/test_quicksight.py
- openmetadata-docs/content/deployment/docker/index.md
Fixed quicksight dashboard_url ( change embed url to quicksight's endpoint )
#
#
</p>
#
#
> Fix Quicksight URL

- ingestion/src/metadata/ingestion/models/table_metadata.py
- ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
- ingestion/src/metadata/ingestion/sink/metadata_rest.py
- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/database_service.py
- ingestion/src/metadata/ingestion/source/database/redshift/metadata.py
- ingestion/src/metadata/ingestion/source/database/sql_column_handler.py
- ingestion/src/metadata/utils/fqn.py
- ingestion/tests/unit/topology/database/test_postgres.py
- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
Fix #5153: Add referred columns for foreign key constraint and sort_key, dist_key support
#
#
</p>
#
#
> Fix #5153: Add referred columns for foreign key constraint and sort_key, dist_key support

- ingestion/tests/unit/topology/metadata/test_amundsen.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/deltaLakeConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/druidConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/hiveConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/mariaDBConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/pinotDBConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/prestoConnection.json
Some database connections where missing the dbt support flag. Adding it to the ones I believe should have it (e.g., excluded dynamodb or salesforce)
#
#
</p>
#
#
> Add support dbt in connection

- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ColumnIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ContainerIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchEventPublisher.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchIndexDefinition.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/TableIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/resources/elasticsearch/en/container_index_mapping.json
> Add search api integration for object store

- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/PipelineIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/pipelines/PipelineResourceTest.java
> Fix patching tags for tasks

- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/mocks/TableSummary.mock.ts
- openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryCard.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableQueries/TableQueries.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableQueries/TableQueries.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/elasticsearch.constant.ts
- openmetadata-ui/src/main/resources/ui/src/mocks/TableData.mock.ts
- openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/ElasticSearchReIndexModal.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/tour-page/TourPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/queryAPI.ts
- openmetadata-ui/src/main/resources/ui/src/rest/tableAPI.ts
UI updated as per new query as entity change
#
#
</p>
#
#
> Fix: UI updated as per new query as entity change

- ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py
- ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py
`get_user_by_email` function currently only returns default field and does not allow requesting extract fields. This PR allows passing fields from the User endpoint to the the `get_user_by_email` function.
#
#
> [Fix] Add field argument to `get_user_by_email` function

- openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
Take Pagination length from Lineage config modal.
Expand only visible columns on clicking of Expand All button.
#
#
</p>
#
#
> fix: lineage pagination issues

- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/QueryRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/query/QueryResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/EnumBackwardCompatibilityTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/query/QueryResourceTest.java
- openmetadata-spec/src/main/java/org/openmetadata/schema/EntityInterface.java
- openmetadata-spec/src/main/resources/json/schema/api/voteRequest.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/query.json
- openmetadata-spec/src/main/resources/json/schema/type/entityRelationship.json
- openmetadata-spec/src/main/resources/json/schema/type/votes.json
- openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryCard.test.tsx
Added Voting for queries 
#
#
</p>
#
#
> Added Vote for Queries

- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ContainerIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/DashboardIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/MlModelIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/PipelineIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/TableIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/TopicIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/permissions/PermissionsResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/Authorizer.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/DefaultAuthorizer.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/CompiledRule.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/PolicyCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/PolicyEvaluator.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/ResourceContext.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/RoleCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/RuleEvaluator.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectContext.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/TestCaseResourceContext.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/RuleEvaluatorTest.java
See #10656 for more details
#
#
> Fixes #10656 Fix permissions API bug

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EventSubscriptionRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/CollectionRegistry.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/CompiledRule.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/PolicyCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/PolicyEvaluator.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/RuleEvaluator.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectContext.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/RuleEvaluatorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/SubjectContextTest.java
- openmetadata-spec/src/main/java/org/openmetadata/schema/Function.java
See #10679 for details
#
- [] Bug fix
#
> Fixes #10679 - Add policy functions inAnyTeam and hasAnyRole

- ingestion/tests/cli_e2e/test_cli_mysql.py
A table was dropped. We need to update the count
#
#
</p>
#
#
> Update MySQL e2e counts after #10265

- openmetadata-ui/src/main/resources/ui/src/pages/LogsViewer/LogsViewer.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/LogsViewer/LogsViewer.interfaces.ts
It was missing and the UI was not giving us any results
#
#
</p>
#
#
> UI - Add ES log retrieval

- openmetadata-docs/content/connectors/ingestion/workflows/profiler/index.md
> doc: added best practice section to profiler

- ingestion/src/metadata/ingestion/source/database/glue/metadata.py
I worked on fixing glue ingestion issue for cypress.
#
#
> Fix glue ingestion issue

- openmetadata-docs/content/connectors/database/druid/airflow.md
- openmetadata-docs/content/connectors/database/druid/cli.md
- openmetadata-docs/content/connectors/database/druid/index.md
I worked on updating docs for druid
#
> update druid docs

- openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightSummary.tsx
Fixes #10571 
Fixed issue App Analytics summary not adjusting to the datetime [UI] 
https://user-images.githubusercontent.com/71748675/227214772-102fbc46-37e3-4e2c-ab8c-0a15b27eedfd.mov
#
#
> fixes #10571: App Analytics summary not adjusting to the datetime [UI] #10571

- openmetadata-ui/src/main/resources/ui/src/components/common/SummaryTagsDescription/SummaryTagsDescription.component.tsx
Fixes https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1481220093
I worked on fixing the icon on the lineage summary panel
#
#
> Fixes #10543:  The icon on lineage summary panel

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Service.spec.js
- openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/serviceAPI.ts
Fixes : Closes #10457
I worked on the Remove owner functionality which was breaking due to an unidentified field error from BE.
https://user-images.githubusercontent.com/66266464/227129669-17f88eac-f63b-4c32-8735-b6a4c6de1e51.mov
#
#
> Fixes #10457 : Breaking of remove owner from Services page

- openmetadata-docs/content/connectors/pipeline/airflow/cli.md
- openmetadata-docs/content/connectors/pipeline/airflow/index.md
> Docs - Add Airflow version support

- openmetadata-ui/src/main/resources/ui/src/components/EntityInfoDrawer/EntityInfoDrawer.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainer/tags-container.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/success-screen/SuccessScreen.tsx
- openmetadata-ui/src/main/resources/ui/src/interface/types.d.ts
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.mock.ts
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
Fixes #10662 
I worked on the issue #10662 
https://user-images.githubusercontent.com/59080942/227205177-30c3743c-8a46-4a11-8c01-443757b214d4.mov
#
#
> fix#10662: Update tier functionality is not working as expected on the containers page

- openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/redshiftWithDBT.spec.js
Fixes cypress failure for redshiftWithDBT
#
#
> fix(test): redshiftWithDBT cypress failure for lineage

- ingestion/src/metadata/profiler/orm/functions/datetime.py
- ingestion/src/metadata/utils/sqa_utils.py
Fixes #10775 handle partitionning for bigquery datetime dtype.
#
#
> Fixes #10775 -- BQ partitionning for datetime dtype

- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchEventPublisher.java
Fixes QueryUsedIn data not present in ES
#
#
> Fix Query Used In

- openmetadata-ui/src/main/resources/ui/cypress/constants/tagsAddRemove.constants.js
cypress: skipping tagsAddRemove spec for mlmodel entity
#
#
> cypress: skipping tagsAddRemove spec for  mlmodel entity

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TokenRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BasicAuthenticator.java
Fixes null thrown in case of the missing or invalid Refresh token
Returns a proper message in case of the missing or invalid token.
#
#
> Return proper message in case invalid or missing token

- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- ingestion/src/metadata/orm_profiler/orm/functions/datetime.py
- ingestion/src/metadata/orm_profiler/profiler/handle_partition.py
- openmetadata-airflow-apis/setup.py
-  Implements issue-10780 for 0.13.3. In 1.0 package structure has been changed. We need to open a PR specifically for 0.13.3 (can't cherry pick). PR from `main` https://github.com/open-metadata/OpenMetadata/commit/31d4662abef3c2094ae04260314b4bc290eece1a
- Bumped python package version
#
#
> Issue 10780 for 0.13.3

- ingestion/src/metadata/ingestion/source/database/databricks/connection.py
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/domodashboard.json
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/looker.json
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/metabase.json
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/mode.json
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/powerbi.json
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/quicksight.json
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/redash.json
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/superset.json
- openmetadata-service/src/main/resources/json/data/testConnections/database/databricks.json
- openmetadata-service/src/main/resources/json/data/testConnections/messaging/kafka.json
- openmetadata-service/src/main/resources/json/data/testConnections/messaging/kinesis.json
- openmetadata-service/src/main/resources/json/data/testConnections/messaging/redpanda.json
- openmetadata-service/src/main/resources/json/data/testConnections/metadata/amundsen.json
- openmetadata-service/src/main/resources/json/data/testConnections/metadata/atlas.json
- openmetadata-service/src/main/resources/json/data/testConnections/mlmodel/mlflow.json
- openmetadata-service/src/main/resources/json/data/testConnections/mlmodel/sagemaker.json
- openmetadata-service/src/main/resources/json/data/testConnections/pipeline/airbyte.json
- openmetadata-service/src/main/resources/json/data/testConnections/pipeline/airflow.json
- openmetadata-service/src/main/resources/json/data/testConnections/pipeline/dagster.json
- openmetadata-service/src/main/resources/json/data/testConnections/pipeline/databrickspipeline.json
- openmetadata-service/src/main/resources/json/data/testConnections/pipeline/domopipeline.json
- openmetadata-service/src/main/resources/json/data/testConnections/pipeline/fivetran.json
- openmetadata-service/src/main/resources/json/data/testConnections/pipeline/gluepipeline.json
- openmetadata-service/src/main/resources/json/data/testConnections/pipeline/nifi.json
Fixed the descriptions of test connection definitions and added timeout for databricks 
#
#
> Minor Fixes for test connection

- ingestion/src/metadata/ingestion/ometa/ometa_api.py
- ingestion/src/metadata/ingestion/source/objectstore/objectstore_service.py
- ingestion/src/metadata/ingestion/source/objectstore/s3/metadata.py
- openmetadata-service/src/main/java/org/openmetadata/service/resources/objectstores/ContainerResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/objectstore/ObjectStoreServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/TestServiceConnectionRequestClassConverter.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/services/ObjectStoreServiceResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/entity/automations/testServiceConnection.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/objectstoreService.json
- openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ConnectionConfigForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Services.constant.ts
- openmetadata-ui/src/main/resources/ui/src/enums/entity.enum.ts
- openmetadata-ui/src/main/resources/ui/src/enums/service.enum.ts
- openmetadata-ui/src/main/resources/ui/src/interface/types.d.ts
- openmetadata-ui/src/main/resources/ui/src/pages/service/index.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/ObjectStoreServiceUtils.ts
- openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx
- Handle test connection for S3
- Add new status handling for the S3 ingestion
- Update the endpoint string to `objectStoreService` to ease an issue where the Ingestion Pipeline service type was sent wrongfully as `objectstoreService` instead of `objectStoreService`. This is ok for now as a followup, we'll do a refactor from `objectStoreService` to the final `StorageService`.
- Update list field param name
- Fix testing the connection and deploying object store services from the UI
#
#
> S3 Improvements for test connection and connector status

- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PolicyRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/RoleRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/EntityResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/policies/PolicyResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/RoleResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/ResourceContext.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectContext.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/policies/PolicyResourceTest.java
Fixes #10791 
Add tests for various Policy and Resources Access Control scenarios
#
#
> Fixes #10791 Add tests for various Resource & Policy scenarios

- ingestion/tests/cli_e2e/test_cli_mysql.py
Updated the filters count for mysql e2e test
#
#
> Updated count for mysql e2e filters

- ingestion/src/metadata/profiler/metrics/system/system.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/10812
Worked on fixing region issue
#
#
> Fixes 10812: Fix Region issue in profiler ingestion ( bigquery )

- ingestion/src/metadata/ingestion/source/messaging/kinesis/metadata.py
Fixed the wrong merge conflict resolution for kinesis
#
#
> Fixed the wrong merge conflict resolution for kinesis

- .github/workflows/docker-openmetadata-db.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- .github/workflows/docker-openmetadata-postgres.yml
- .github/workflows/docker-openmetadata-server.yml
- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion-postgres.yml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata-postgres.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
1.0.0-alpha version upgrade
#
#
> 1.0.0-alpha version upgrade

- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/bigquery.spec.js
I worked on fixing the glossary e2e spec because it was failing due to the wrong input id.
#
#
> fix(ui):glossary e2e spec

- openmetadata-service/src/main/resources/elasticsearch/en/topic_index_mapping.json
> Add ngram to topic display name indexing

- docker/docker-compose-quickstart/Dockerfile
> Fix Dockerfile Path 

- openmetadata-docs/content/developers/contribute/build-code-and-run-tests/prerequisites.md
> update node version in prerequisites

- ingestion/src/metadata/ingestion/ometa/provider_registry.py
- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
- openmetadata-ui/src/main/resources/ui/src/components/BotDetails/AuthMechanismForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/CreateUser/CreateUser.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/BotsUtils.ts
Fixes part of #9353
- Added deprecation messages when any bot configuration with SSO is used.
- Remove possibility to change the bot configuration to the SSO one.
#
> Fix: Remove bot configuration with SSO service account

- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionRecentRun/IngestionRecentRuns.component.tsx
Minor text correction found while testing some ingestion flows.
#
> fix(ui): Minor text correction

- ingestion/src/metadata/ingestion/models/es_documents.py
- ingestion/src/metadata/ingestion/sink/elasticsearch.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/container_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/dashboard_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/entity_report_data_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/glossary_term_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/mlmodel_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/pipeline_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/query_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/table_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/tag_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/team_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/topic_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/user_search_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/web_analytic_entity_view_report_data_index_mapping.py
- ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/web_analytic_user_activity_report_data_index_mapping.py
- ingestion/src/metadata/ingestion/source/metadata/metadata.py
- ingestion/src/metadata/utils/elasticsearch.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/metadata/metadataESConnection.json
1. There were many mappings not updates since the last changes in the backend. We're going to tackle this problem completely in https://github.com/open-metadata/OpenMetadata/issues/9185
2. The ES sink was not properly structured and it was quite messy. Now the last cleaning piece pending will be done with the issue above.
3. We also added the missing Container and Query entities indexing capabilities in the framework
In this PR we centralized a ton of the processing to make it easier to follow and evolve.
#
#
> Update ingestion ES mappings & restructure sink

- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
- ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py
Fixes #8852
Reviewed the ES querying logic for lineage and updated some methods docstring. 
We can not simplify the logic since we need the columns field to get the column lineage. So, for now, we have to query ES and the API.
> Fix#8852: Updating comments on sql lineage flow

- ingestion/src/metadata/profiler/metrics/system/system.py
- ingestion/src/metadata/profiler/profiler/core.py
- ingestion/src/metadata/test_suite/api/workflow.py
- ingestion/src/metadata/utils/entity_link.py
- ingestion/tests/integration/ometa/test_ometa_test_suite.py
- ingestion/tests/integration/test_suite/test_workflow.py
- ingestion/tests/unit/metadata/utils/test_entity_link.py
Fixes #10727 
- Handle `UNKNOWN` and `NULL` types 
- Fix CLI test suite logic to cover the below cases
1. Same test name - different FQN - different Test Suite 👉 create test case ✅
2. Same test name - same FQN - different Test Suite 👉 test name already exist for entity, will be filtered out ✅
3. Same test name - same FQN - Same test Suite 👉 test already exist, will be filtered out ✅
4. Same test name - different FQN - Same test suite 👉 create ✅
- Cache system metrics for `Snowflake` and `BigQuery`. This was an opportunity improvements and we'll do additional work in https://github.com/open-metadata/OpenMetadata/issues/10860
#
#
> Fixes #10727 (& other minor improvements)

- ingestion/src/metadata/parsers/avro_parser.py
- ingestion/tests/unit/test_avro_parser.py
- ingestion/tests/unit/topology/database/test_datalake.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
- openmetadata-spec/src/main/resources/json/schema/type/schema.json
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicSchema/TopicSchema.tsx
Fix #10814: Improve parsing logic for union fields in topic
Before 
After 
#
#
> Fix #10814: Improve parsing logic for union fields in topic

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
Fixes #10711
Team with soft deleted user does not apply PATCH correctly.
#
#
> Fixes #10711 Cannot assign a policy to a team with a soft-deleted user

- ingestion/src/metadata/clients/aws_client.py
- ingestion/src/metadata/examples/workflows/athena_lineage.yaml
- ingestion/src/metadata/examples/workflows/athena_usage.yaml
- ingestion/src/metadata/ingestion/source/database/athena/lineage.py
- ingestion/src/metadata/ingestion/source/database/athena/models.py
- ingestion/src/metadata/ingestion/source/database/athena/query_parser.py
- ingestion/src/metadata/ingestion/source/database/athena/usage.py
- ingestion/src/metadata/ingestion/source/database/databricks/client.py
- ingestion/src/metadata/ingestion/source/database/databricks/lineage.py
- ingestion/src/metadata/ingestion/source/database/databricks/usage.py
- ingestion/src/metadata/ingestion/source/database/lineage_source.py
- ingestion/src/metadata/ingestion/source/database/usage_source.py
- ingestion/src/metadata/ingestion/stage/table_usage.py
- ingestion/src/metadata/utils/constants.py
- openmetadata-docs/content/connectors/database/athena/airflow.md
- openmetadata-docs/content/connectors/database/athena/cli.md
- openmetadata-docs/content/connectors/database/athena/index.md
- openmetadata-docs/content/connectors/ingestion/lineage/index.md
- openmetadata-docs/content/connectors/ingestion/workflows/usage/index.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/athenaConnection.json
Fix #10320: Add Athena Usage & Lineage
Athena does not store the query history log in a specific table but it can be fetched via calling the [list_query_executions](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena/client/list_query_executions.html) API which returns only the id of executed queries and [batch_get_query_execution](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena/client/batch_get_query_execution.html) API is used to fetch the details of those queries.
This approach is somewhat similar to what we do for databricks but the APIs does not provide the functionality to filter the queries based of datetime or query text hence the we will be dependent on the [resultLimit](https://github.com/open-metadata/OpenMetadata/b …
> Fix #10320: Add Athena Usage & Lineage

- openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
Fixes lineage page in Tour.
#
#
> fix: broken lineage link on tour page

- ingestion/src/metadata/ingestion/connections/test_connections.py
- ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
- ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin_utils.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/WorkflowRepository.java
Test Connection Improvements: Use patch instead of put as part of #10774
#
#
> Test Connection Improvements: Use patch instead of put

- openmetadata-docs/content/overview/roadmap/index.md
> Fix roadmap dates and features

- ingestion/setup.py
Fix #10896: Fix snappy coded issue
#
#
> Fix #10896: Fix snappy coded issue

- ingestion/src/metadata/ingestion/source/metadata/amundsen/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/dagster/connection.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/pipeline/dagsterConnection.json
Fixes: #10778 
I worked on adding timeout option for Dagster and Amundsen changes
#
#
> adding timeout option for Dagster and Amundsen changes

- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
Fixes #10846
I worked on cypress-integration-tests yml files because the previous changes running workflows on all the path changes.
#
> Fixing the cypress-test path

- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/resources/elasticsearch/en/query_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/team_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/user_index_mapping.json
> Fix #10904, Glossary Search: no Matches info for Synonyms

- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
Run on main branch with all changes except docs.
#
#
> fix(CI): Run Cypress on main branch with all changes except docs

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/RestoreEntity.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/TeamsHierarchy.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Policies.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js
cypress: fix flaky cypress test from main 
#
#
> cypress: fix flaky cypress test from main

- openmetadata-ui/src/main/resources/ui/public/swagger.html
- openmetadata-ui/src/main/resources/ui/src/pages/swagger/index.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/swagger/swagger.less
Fixes #10905 
I worked issue #10905 
#
#
> fix(#10905):API documentation does not show bullets from Markdown

- openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Policies.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js
> cypress: fix failing cypress test

- ingestion/src/metadata/ingestion/source/dashboard/metabase/client.py
- ingestion/src/metadata/ingestion/source/dashboard/metabase/connection.py
- ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/metabase/models.py
This PR is work in progress, I am trying to create a client file for metabase to fix #10721,
@pmbrull , @ulixius9 could you have a look and let me know if I am going in the right direction?
Questions: Is the solution created by splitting the metadata file and creating a new client file? I'm not quite sure. 
Fixes #10721
#
#
> [WIP] Fixes #10721:  created client file for metabase and moved get request to client file

- openmetadata-docs/content/sdk/python/index.md
> Update python sdk client connection details

- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/ReIndexingHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/SearchIndexWorkflow.java
- openmetadata-spec/src/main/resources/json/schema/system/eventPublisherJob.json
- openmetadata-ui/src/main/resources/ui/src/jsons/en.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/ElasticSearchReIndexPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/elasticSearchReIndexAPI.ts
- openmetadata-ui/src/main/resources/ui/src/utils/EventPublisherUtils.tsx
> Add Stop Functionality For Reindex

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/powerbi/client.py
- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/redash/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
- ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
- ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py
- ingestion/src/metadata/ingestion/source/pipeline/airbyte/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/dagster/connection.py
- ingestion/src/metadata/ingestion/source/pipeline/nifi/metadata.py
- ingestion/src/metadata/utils/helpers.py
- ingestion/tests/unit/topology/dashboard/test_looker.py
- ingestion/tests/unit/topology/dashboard/test_superset.py
- ingestion/tests/unit/topology/pipeline/test_airbyte.py
- ingestion/tests/unit/topology/pipeline/test_nifi.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java
Fix #10858: Fix dashbaord & pipeline url
#
#
> Fix #10858: Fix dashbaord & pipeline url

- ingestion/src/metadata/ingestion/sink/metadata_rest.py
- ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
- ingestion/src/metadata/utils/dbt_config.py
- ingestion/tests/unit/test_dbt.py
Moved the logs of dbt from INFO to DEBUG level
Added registering record for data models
#
#
> Fixed dbt logging

- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchEventPublisher.java
> Avoid ES Bulk Calls for not requests

- ingestion/src/metadata/ingestion/source/database/trino/metadata.py
> Fixes 10821: Issue with dash and underscore in trino fixed

- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
- I have downgraded machine as we are suspecting it to be cause of failures, but we found out that to be an issue with ES.
- #10981 this is fixed, So revert back the machine changes to speed up Cypress
#
#
> fix(ui): upgrade cy machine to 3

- openmetadata-docs/content/openmetadata/data-insight/index.md
I worked on updating data-insight doc update.
Provide an example of running data insights with Airflow SDK.
Also, add Elasticsearch Reindex using the Airflow SDK
#
#
> Doc update for Data-insight

- openmetadata-ui/src/main/resources/ui/src/components/ContainerVersion/ContainerVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ContainerVersion/ContainerVersion.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/objectStoreAPI.ts
Fixes #10886 
I worked on adding version page for container data assets
https://user-images.githubusercontent.com/59080942/231138021-6f4d32d9-fde9-456b-a7f8-104da69bd2ee.mov
#
#
> chore(ui) #10886 : Add version page for container

- ingestion/src/metadata/ingestion/ometa/client.py
- ingestion/src/metadata/ingestion/source/dashboard/metabase/client.py
- ingestion/src/metadata/ingestion/source/dashboard/metabase/connection.py
- ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/metabase/models.py
- ingestion/src/metadata/ingestion/source/pipeline/airbyte/client.py
- ingestion/src/metadata/utils/constants.py
We have defined some models but we are not using it these models in metabase client, in this pr I've converted all the expected json reponse and mapped them to their respective models,
note: in the models I've marked most of the fields as optional as we are not using most of then and we do not want to break the processing of dashbord if some fields were not found 
#
#
> Use metabase models in client

- ingestion/tests/unit/test_suite/test_validations_datalake.py
To not kill the github runner
#
#
> Fix test usage resources

- openmetadata-service/src/main/java/org/openmetadata/service/events/ChangeEventHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/ChangeEventParser.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/ChangeEventParserResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/FeedResourceTest.java
> Remove space before : in before update activity feed message

- ingestion/src/metadata/examples/workflows/bigquery.yaml
- openmetadata-docs/content/connectors/database/bigquery/airflow.md
- openmetadata-docs/content/connectors/database/bigquery/cli.md
- openmetadata-docs/content/connectors/database/bigquery/index.md
> Fixes 8264: add docs around adding taxonomy project id

- ingestion/src/metadata/ingestion/source/database/oracle/metadata.py
- ingestion/src/metadata/ingestion/source/database/oracle/queries.py
- ingestion/src/metadata/ingestion/source/database/oracle/utils.py
Fix #10999: Add support for materialised views in oracle
currently the oracle dialect ingests materialised view as a regular table
Since materialised view is not a regular table/view, have handled it separately also since we are picking up the view definition for materialised view in this pr, the issue of lineage is also resolved,
#
#
> Fix #10999: Add support for materialised views in oracle

- ingestion/src/metadata/ingestion/models/delete_entity.py
- ingestion/src/metadata/ingestion/source/database/database_service.py
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/databaseAPI.ts
Fixes https://github.com/open-metadata/OpenMetadata/issues/10514
Added logic to clean up the schemas if deleted from source
#
#
> Added logic for cleaning up schemas

- common/pom.xml
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-service/pom.xml
- pom.xml
Updates the dependencies for release 1.0
#
#
> Update dependencies for 1.0 release

- ingestion/src/metadata/ingestion/source/storage/s3/metadata.py
- ingestion/src/metadata/ingestion/source/storage/s3/models.py
- ingestion/src/metadata/ingestion/source/storage/storage_service.py
- ingestion/tests/unit/topology/storage/test_storage.py
We were ingesting at the same level, the buckets and their children (if we passed some data model files).
Now we properly ingest them as children:
#
#
> Handle container parents

- openmetadata-spec/src/main/resources/json/schema/security/credentials/gcsValues.json
> fix 11021: remove repeating item title

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v009__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v009__create_db_connection_info.sql
Fixes issues in migration, migrate-all was failing in between.
#
#
> Fix Failing migrations

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
> Fix 9399: issue with validating profile sample input for percentage to be between 0 and 100

- ingestion/src/metadata/cli/insight.py
- ingestion/src/metadata/cmd.py
- ingestion/src/metadata/examples/workflows/data_insight.yaml
- ingestion/src/metadata/utils/workflow_output_handler.py
- openmetadata-docs/content/openmetadata/data-insight/index.md
I work on this to run data insights with metadata command-line. (before we don't have command  `metadata insight -c <path-to-yaml> `, but now it's available. and also update doc for that.
fix #10874
#
#
> Data insights with metadata command-line

- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/QueryCount/QueryCount.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/QueryCount/QueryCount.test.tsx
- openmetadata-ui/src/main/resources/ui/src/enums/entity.enum.ts
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
Fixes #8303
UI: Confusing data about query on table details page. #8303
- Added ES count call to query to get query count and show to database details page
#
#
> fix UI: Confusing data about query on table details page. #8303

- ingestion/examples/sample_data/looker/charts.json
- ingestion/examples/sample_data/looker/dashboardDataModels.json
- ingestion/examples/sample_data/looker/dashboards.json
- ingestion/examples/sample_data/looker/service.json
- ingestion/src/metadata/ingestion/source/database/sample_data.py
To help showing and testing the features
#
#
> Add Looker Sample Data

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/ActivityFeedCard.tsx
I worked on the subtask of issue #10543 
#
#
> fix(ui):Popover should be on the right side

- ingestion/src/metadata/ingestion/ometa/client.py
We have a user having the exception:
```
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
At minute 10 during the ingestions. Looks like an issue that might be related to https://github.com/psf/requests/issues/4664, so we are trying to catch the `ConnectionError` here to retry the request.
This is something that I have not been able to reproduce, locally nor on other OM installations that are also using 0.13.3.
#
#
> Python Client - Catch ConnectionError to handle RemoteDisconnected

- ingestion/src/metadata/examples/workflows/kafka.yaml
- openmetadata-docs/content/connectors/messaging/kafka/troubleshooting.md
Update Kafka troubleshooting section with the YAML example.
> Doc: Update Kafka troubleshooting section

- .github/workflows/docker-openmetadata-db.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- .github/workflows/docker-openmetadata-postgres.yml
- .github/workflows/docker-openmetadata-server.yml
- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion-postgres.yml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata-postgres.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
> 1.0.0 beta bump version

- openmetadata-ui/src/main/resources/ui/src/components/BotListV1/BotListV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ContainerDetail/ContainerDataModel/ContainerDataModel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModels/ModelTab/ModelTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/RolesAndPoliciesList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/VersionTable/VersionTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/PoliciesDetailsList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
Fixes [<issue-number>](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1508349722)
- I worked on  changing the Data Model URL to it's respective page
- Fix the nested column expanding issue -  https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1499027881
-  Added dataType with displayName in DataModel -  https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1508100225
https://user-images.githubusercontent.com/66266464/232030218-ac6bab77-a264-4869-ae88-6512be115932.mov
#
> Fixes comments #10543: Change and redirect the DataModel url to it's page from Lineage panel

- ingestion/src/metadata/ingestion/source/database/hive/connection.py
Instead of `auth` for hive, we should use `auth_mechanism`
#
#
> Handle impala auth mechanism

- ingestion/src/metadata/ingestion/sink/elasticsearch.py
- ingestion/src/metadata/ingestion/source/database/datalake/utils.py
Fix Ingestion Top Level Imports
#
#
> Fix Ingestion Top Level Imports

- .github/workflows/py-cli-e2e-tests.yml
Add missing env vars for running Tableau E2E test.
> Fix: Add Tableau E2E test missing env vars

- openmetadata-ui/src/main/resources/ui/cypress.config.ts
- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
> fixed glossary & service failing cypress

- .github/workflows/maven-build-skip.yml
- .github/workflows/maven-build.yml
- bootstrap/sql/org.postgresql.Driver/v009__create_db_connection_info.sql
> Fix postgres migrations & Update maven CI triggers

- ingestion/src/metadata/profiler/processor/handle_partition.py
- ingestion/src/metadata/profiler/processor/sampler.py
> fix: column retrieval for SNOWFLAKE

- openmetadata-docs/content/deployment/kubernetes/eks.md
- openmetadata-docs/content/deployment/kubernetes/gke.md
- openmetadata-docs/content/deployment/kubernetes/on-prem.md
Updated the docs that mention the install command to install openmetadata helm charts 
#
#
> K8 step update

- openmetadata-docs/content/overview/roadmap/index.md
> Update roadmap release date

- .github/workflows/py-cli-e2e-tests.yml
- ingestion/src/metadata/ingestion/source/dashboard/redash/metadata.py
- ingestion/tests/cli_e2e/dashboard/redash/redash.yaml
- ingestion/tests/cli_e2e/test_cli_redash.py
Part of #10805
Add an E2E test since the code is barely tested.
> Fix: Add Redash E2E test

- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx
Fixes #11106
I worked on supporting the Markdown preview in the test case description
#
#
> Fixes #11106 : Supported Markdown preview in the test case description

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
> Fix Query Pagination Issue

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx
I worked on fixing cypress issue 
#
#
> Fix cypress issue

- openmetadata-ui/src/main/resources/ui/src/components/SearchDropdown/SearchDropdown.less
- openmetadata-ui/src/main/resources/ui/src/components/SearchDropdown/SearchDropdown.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchUtils.tsx
Fixes some issues from #10543 
1. https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1490717025
2. https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1490730247
I worked on increasing the maximum width of the quick search dropdown and bringing the common filters i.e.
`Owner` and `Tags` in front of the other filters.
https://user-images.githubusercontent.com/51777795/232797966-5280e39f-0955-4e75-be27-6d730177534a.mov
#
#
> ui: search dropdown improvements

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeader/EntityHeader.component.tsx
Fixes comments : https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1506357945
I worked on supporting Encoded fqn in entity url's
https://user-images.githubusercontent.com/66266464/232783115-9d68dc61-f191-4f27-93bb-71566f2420ac.mov
#
#
> Fixes : Supported Encoded fqn in entity url's

- ingestion/src/metadata/ingestion/source/database/datalake/metadata.py
- ingestion/src/metadata/utils/azure_utils.py
- ingestion/src/metadata/utils/gcs_utils.py
- openmetadata-docs-v1/content/v1.0.0/connectors/database/datalake/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/datalake/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/datalake/index.md
We were filtering out correct files and passing extra options to the read functions
#
#
> Azure datalake metadata ingestion fixes

- .github/workflows/py-cli-e2e-tests.yml
- ingestion/tests/cli_e2e/dashboard/powerbi/powerbi.yaml
- ingestion/tests/cli_e2e/dashboard/powerbi/redshift.yaml
- ingestion/tests/cli_e2e/test_cli_powerbi.py
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Dashboard/PowerBI.md
Added Powerbi E2E and requirement documentation
#
#
> Added Powerbi E2E and requirement documentation

- ingestion/setup.py
- ingestion/src/metadata/interfaces/sqalchemy/mixins/sqa_mixin.py
- ingestion/src/metadata/interfaces/sqalchemy/sqa_profiler_interface.py
- ingestion/src/metadata/interfaces/sqalchemy/sqa_test_suite_interface.py
> Fixes 10729 in 0.13.3

- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/Steps/ConfigureIngestion.tsx
Fixes #11122
- I worked on supporting Enable Debug logs for Services like MlModel, Metadata & Storage Service
#
#
> Fixes #11122 : Supported Debug log for Services

- bootstrap/bootstrap_storage.sh
- bootstrap/sql/com.mysql.cj.jdbc.Driver/v008__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v008__create_db_connection_info.sql
We weren't cleaning up properly all the necessary information from the Sample Data service.
Instead of relying on the migrations, we will update the docs for the 0.13 upgrades to let users know to remove the service directly in the UI before the upgrade.
As we are updating an old migration script, adding `repair` to the `migrate-all` to make upgrades easier and not add extra steps
#
#
> Revert Sample Data migrations

- ingestion/src/metadata/profiler/orm/functions/modulo.py
- ingestion/src/metadata/profiler/orm/functions/sum.py
Fixes #11137 
Worked on fixing Arithmetic Bug and Syntax error on pymssql scheme
#
#
> Fixes #11137: Mssql Syntax Error + Arithemetic Error

- ingestion/src/metadata/ingestion/source/database/databricks/usage.py
Fix the function name. (Because of that databricks usage was not working. this issue was happen #10879 here.)
#
#
> Fix: Databricks usage issue

- ingestion/src/metadata/profiler/processor/core.py
- ingestion/tests/unit/profiler/test_profiler.py
Fixed logic to filter metrics from metrics list when include Column is set in the profilerConfig.
#
#
> Fix metrics filtering

- .github/workflows/py-cli-e2e-tests.yml
- ingestion/src/metadata/ingestion/source/dashboard/metabase/client.py
- ingestion/tests/cli_e2e/dashboard/metabase/metabase.yaml
- ingestion/tests/cli_e2e/dashboard/metabase/redshift.yaml
- ingestion/tests/cli_e2e/test_cli_metabase.py
- openmetadata-docs-v1/content/v0.13.2/connectors/dashboard/metabase/airflow.md
- openmetadata-docs-v1/content/v0.13.2/connectors/dashboard/metabase/cli.md
- openmetadata-docs-v1/content/v0.13.2/connectors/dashboard/metabase/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/metabase/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/metabase/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/metabase/index.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Dashboard/Metabase.md
> Metabase E2E Test & docs

- openmetadata-ui/src/main/resources/ui/src/pages/signup/index.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/signup/index.tsx
> fix: Create button is not working on SignUp form

- ingestion/src/metadata/ingestion/source/database/athena/models.py
- openmetadata-docs-v1/content/v1.0.0/connectors/database/athena/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/athena/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/athena/index.md
- openmetadata-docs-v1/content/v1.0.0/deployment/airflow/index.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/athenaConnection.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Athena.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/lineage.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/usage.md
Add Athena, Lineage and Usage docs & Fix Athena UI Lineage and Usage workflows
Also fixed the athena lineage/usage query model
#
#
> Add Athena, Lineage and Usage docs & Fix Athena UI Lineage and Usage workflows

- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Dashboard/workflows/metadata.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/lineage.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/metadata.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/profiler.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/usage.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Messaging/workflows/metadata.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Metadata/workflows/metadata.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Mlmodel/workflows/metadata.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/workflows/metadata.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Storage/workflows/metadata.md
Ingestion Workflow Markdown Docs
#
#
> Ingestion Workflow Markdown Docs

- openmetadata-docs-v1/content/v0.13.2/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs-v1/content/v0.13.2/connectors/pipeline/airflow/lineage-operator.md
- openmetadata-docs-v1/content/v1.0.0/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs-v1/content/v1.0.0/connectors/pipeline/airflow/lineage-operator.md
I worked on removing the content for new docs that was causing the render conflicts with the MarkDoc tags
#
#
> documentation: content causing render conflicts with markdoc tags removed

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/TotalCountForTeams&Users.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/DashboardSummary/DashboardSummary.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/MlModelSummary/MlModelSummary.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/PipelineSummary/PipelineSummary.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SummaryList/SummaryList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SummaryList/SummaryListItems/SummaryListItems.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/SelectableList/SelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/teams/AddTeamForm.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntitySummaryPanelUtils.tsx
Worked on below issues:
1. Teams getting infinite calls for owner dropdown
2. Teams name validation as per json schema
3. alignment issue for summary panel (Dashboard / Pipeline / ML Model)
https://user-images.githubusercontent.com/12962843/233451887-c8a13a75-272a-4c3a-9bde-102a55326848.mov
https://user-images.githubusercontent.com/12962843/233452035-49fdd71e-c08f-4a7a-83e1-b2b0c9796255.mov
#
#
> fix(ui): alignment on summary panel

- ingestion/src/metadata/profiler/orm/converter.py
- ingestion/tests/cli_e2e/common/test_cli_db.py
- ingestion/tests/cli_e2e/test_cli_mssql.py
Fixes #11043 
Fixes HexByteString issue
#
#
> Fix HexByteString Issue, revert datatype change

- openmetadata-docs-v1/content/v0.13.2/connectors/database/datalake/index.md
- openmetadata-docs-v1/content/v0.13.2/main-concepts/metadata-standard/schemas/entity/services/connections/database/datalakeConnection.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/datalake/index.md
- openmetadata-docs-v1/content/v1.0.0/main-concepts/metadata-standard/schemas/entity/services/connections/database/datalakeConnection.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Datalake.md
Add Datalake docs for ingestion ui
#
#
> Add Datalake Docs

- openmetadata-docs-v1/content/v0.13.2/connectors/database/databricks/troubleshooting.md
- openmetadata-docs-v1/content/v0.13.2/how-to-guides/cli-ingestion-with-basic-auth/index.md
- openmetadata-docs-v1/content/v0.13.2/how-to-guides/feature-configurations/bots.md
- openmetadata-docs-v1/content/v0.13.2/how-to-guides/feature-configurations/index.md
- openmetadata-docs-v1/content/v0.13.2/how-to-guides/teams-and-users/how-to-organise-teams-and-users.md
- openmetadata-docs-v1/content/v0.13.2/how-to-guides/teams-and-users/index.md
- openmetadata-docs-v1/content/v0.13.2/main-concepts/high-level-design.md
- openmetadata-docs-v1/content/v0.13.2/overview/features/index.md
- openmetadata-docs-v1/content/v0.13.2/overview/releases/index.md
- openmetadata-docs-v1/content/v0.13.2/quick-start/local-deployment.md
- openmetadata-docs-v1/content/v0.13.2/quick-start/sandbox.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/databricks/troubleshooting.md
- openmetadata-docs-v1/content/v1.0.0/how-to-guides/cli-ingestion-with-basic-auth/index.md
- openmetadata-docs-v1/content/v1.0.0/how-to-guides/custom-logo/how-to-add-custom-logo.md
- openmetadata-docs-v1/content/v1.0.0/how-to-guides/feature-configurations/bots.md
- openmetadata-docs-v1/content/v1.0.0/how-to-guides/feature-configurations/index.md
- openmetadata-docs-v1/content/v1.0.0/how-to-guides/how-to-add-language-support.md
- openmetadata-docs-v1/content/v1.0.0/how-to-guides/teams-and-users/how-to-organise-teams-and-users.md
- openmetadata-docs-v1/content/v1.0.0/how-to-guides/teams-and-users/index.md
- openmetadata-docs-v1/content/v1.0.0/main-concepts/high-level-design.md
- openmetadata-docs-v1/content/v1.0.0/main-concepts/index.md
- openmetadata-docs-v1/content/v1.0.0/main-concepts/metadata-standard/index.md
- openmetadata-docs-v1/content/v1.0.0/main-concepts/metadata-standard/schemas.md
- openmetadata-docs-v1/content/v1.0.0/overview/features/index.md
- openmetadata-docs-v1/content/v1.0.0/overview/index.md
- openmetadata-docs-v1/content/v1.0.0/overview/releases/index.md
- openmetadata-docs-v1/content/v1.0.0/quick-start/index.md
- openmetadata-docs-v1/content/v1.0.0/quick-start/local-deployment.md
- openmetadata-docs-v1/content/v1.0.0/quick-start/sandbox.md
Doc update for version - 0.13.2 and version - 1.0.0
In this PR:
- Quickstart section Done
- overview section Done (roadmap page will done after  this fix :https://github.com/open-metadata/docs-v1/issues/68)
- connectors (Databricks troubleshooting page)
- how-to-guides section Done
- main-concepts section done
#
#
> Documentation Update

- openmetadata-ui/src/main/resources/ui/src/utils/i18next/i18nextUtil.ts
> chore(ui): support spanish & Portugis languages

- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DbtTab/DbtTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DbtTab/dbt-tab.style.less
- openmetadata-ui/src/main/resources/ui/src/constants/Lineage.constants.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
Fixes #10502
- dbt tab UI improvement
- [updated lineage UI](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1507915691)
#
#
> fix(ui) #10502 dbt tab improvement

- openmetadata-docs-v1/content/v0.13.2/connectors/database/oracle/airflow.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/oracle/cli.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/oracle/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/oracle/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/oracle/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/oracle/index.md
- openmetadata-docs/content/connectors/database/oracle/airflow.md
- openmetadata-docs/content/connectors/database/oracle/cli.md
- openmetadata-docs/content/connectors/database/oracle/index.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Oracle.md
> Add Oracle Docs

- openmetadata-docs-v1/content/v1.0.0/connectors/database/mssql/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/mssql/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/mssql/index.md
- openmetadata-docs-v1/content/v1.0.0/main-concepts/metadata-standard/schemas/entity/services/connections/database/mssqlConnection.md
- openmetadata-docs/content/connectors/database/mssql/cli.md
- openmetadata-docs/content/connectors/database/mssql/index.md
- openmetadata-docs/content/main-concepts/metadata-standard/schemas/entity/services/connections/database/mssqlConnection.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Mssql.md
> Mssql docs

- ingestion/tests/unit/test_sql_lineage.py
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Metadata/workflows/dataInsight.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Metadata/workflows/elasticSearchReindex.md
Part of #10805
Add missing `md` files for Elasticsearch Reindex and Data Insight docs in UI.
Skip a flaky test in python 3.7 for now.
> Doc: Add ElasticsearchReindex and Data Insight docs in UI

- openmetadata-docs-v1/content/v0.13.2/connectors/pipeline/dagster/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/pipeline/dagster/index.md
- openmetadata-docs/content/connectors/pipeline/dagster/airflow.md
- openmetadata-docs/content/connectors/pipeline/dagster/cli.md
- openmetadata-docs/content/connectors/pipeline/dagster/index.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/Dagster.md
> Add dagster docs

- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
when a array is ingested it expects display data type to be in format of `array<int>` but now since we are storing the raw data type from data source in the display data type it is possible that it might not follow the same structure for example postgres displays this information as `integer[]`
#
#
> Remove Validation On Display Datatype

- ingestion/src/metadata/ingestion/source/database/common_db_source.py
Fix Lineage Via Table Entity Error
If api failed to create the table view will still be added into context for parsing lineage, hence we should add view to context only when table creation was successful 
#
#
> Fix Lineage Via Table Entity Error

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v009__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v009__create_db_connection_info.sql
- ingestion/tests/unit/topology/database/test_salesforce.py
- openmetadata-docs-v1/content/v0.13.2/connectors/database/salesforce/airflow.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/salesforce/cli.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/salesforce/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/salesforce/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/salesforce/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/salesforce/index.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/salesforceConnection.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Salesforce.md
Salesforce docs & remove unnecessary fields
#
#
> Salesforce docs & remove unnecessary fields

- openmetadata-docs-v1/content/v1.0.0/connectors/database/azuresql/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/azuresql/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/azuresql/index.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/azureSQLConnection.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/AzureSQL.md
Make Database Required for AzureSQL
#
#
> Make Database Required for AzureSQL

- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/GlossaryTerms/tabs/AssetsTabs.component.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Assets.constants.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
- [Use plural when listing asset types. Instead of Table, Topic, it should be Tables, and Topics. ](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1517841137)
- [Glossaries in explore page has a blue colored icon that is different from gray icon in the glossaries page. The blue color does not look great. Let's have consistent color for the icon. ](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1517904612)
- [Classification does not follow the icon, breadcrumb, name and display name format.](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1517913775)
https://user-images.githubusercontent.com/71748675/233793493-1894f3e0-9b46-438e-b44c-f928a9a6354e.mov
#
#
> ui: feedback 1.0 part 3

- ingestion/src/metadata/ingestion/models/es_documents.py
- ingestion/src/metadata/ingestion/sink/elasticsearch.py
> Fix #11214: Ingestion based elastic search index missing serviceType for MLModel and Container

- ingestion/src/metadata/examples/workflows/kafka.yaml
- ingestion/src/metadata/ingestion/source/messaging/common_broker_source.py
> Fix #10964: update retentionSize based on retention.size in the topic config

- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/tags/index.test.tsx
show full topic config for messaging services
#
#
> fix(ui): show full topic config for messaging service

- ingestion/src/metadata/examples/workflows/dbt.yaml
- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/bare-metal.md
- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/docker.md
- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/versions/013-to-100.md
- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/versions/index.md
- openmetadata-docs-v1/content/v1.0.0/menu.md
> 0.13 to 1.00 docs changes

- openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.tsx
- Fix logo alignment issue
#
#
> fix(ui): OM logo alignment in app bar

- openmetadata-docs-v1/content/v0.13.2/connectors/credentials/index.md
- openmetadata-docs-v1/content/v0.13.2/connectors/dashboard/powerbi/setup-powerbi-account.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/azuresql/troubleshooting.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/bigquery/roles.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/datalake/troubleshooting.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/domo-database/troubleshoot.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/redshift/troubleshooting.md
- openmetadata-docs-v1/content/v1.0.0/connectors/credentials/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/powerbi/setup-powerbi-account.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/azuresql/troubleshooting.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/bigquery/roles.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/datalake/troubleshooting.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/domo-database/troubleshoot.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/redshift/troubleshooting.md
In this PR Fix all connectors' Troubleshoot page and a few required doc changes.
#
#
> Update Troubleshoot page

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
Added extra validation in for dbt upstream nodes
#
#
> Added upstream nodes validation for dbt

- openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
Fixes Column Level Lineage rendering
#
#
> fix: column level lineage rendering

- .github/workflows/docker-openmetadata-db.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- .github/workflows/docker-openmetadata-postgres.yml
- .github/workflows/docker-openmetadata-server.yml
- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion-postgres.yml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata-postgres.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
> 1.0.0 version upgrade

- openmetadata-ui/src/main/resources/ui/src/components/AddService/Steps/SelectServiceType.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
> chore(ui): mark impala service as beta

- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/index.md
- openmetadata-docs-v1/content/v1.0.0/releases/index.md
- openmetadata-docs-v1/content/v1.0.0/releases/releases/index.md
- openmetadata-docs-v1/content/v1.0.0/releases/releases/latest.md
- Add backup and upgrade links at the top of `/deployment/upgrade` to make it easier to find.
- Add upgrade links in the release pages
#
#
> [Docs] - Add upgrade & release docs

- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/index.md
- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/versions/013-to-100.md
> fix(docs): Add a note for jwt public key url change for 1.0.0

- ingestion/examples/airflow/dags/airflow_sample_usage.py
To point to the right path in Airflow
#
#
> Fix sample usage DAG directory

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v009__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v009__create_db_connection_info.sql
We missed the migrations on https://github.com/open-metadata/OpenMetadata/pull/10014
#
#
> Fix dynamodb migration

- ingestion/tests/cli_e2e/test_cli_tableau.py
Tableau E2E tests have wrong expected values.
> Fix: Tableau E2E wrong expected values

- ingestion/src/metadata/ingestion/ometa/mixins/tests_mixin.py
- ingestion/tests/integration/ometa/test_ometa_test_suite.py
in `Create...` objects we removed the entityLink to the entity fqn. This PR fixes a migration we missed. 
#
#
> Fix get or create test case

- openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
Fixes Lineage Expand All issue
https://user-images.githubusercontent.com/33024356/234554230-7f998334-3747-40a1-9fdd-e1a8305220c1.mov
#
#
> fix: lineage expand collapse toggle issue

- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/AddIngestion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/Steps/ScheduleInterval.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/addIngestion.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DatePickerMenu/DatePickerMenu.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TimeUtils.ts
Fixes #11254 
- [UI] Data Insights UI does not show scheduling options and range
- selector not including last day bug
https://user-images.githubusercontent.com/71748675/234528862-3871effd-fadb-4a76-82b2-9e3a5a989664.mov
#
#
> fixed ui: [UI] Data Insights UI does not show scheduling options and range selector not including last day bug

- openmetadata-docs-v1/content/v0.13.2/connectors/database/dynamodb/airflow.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/dynamodb/cli.md
- openmetadata-docs-v1/content/v0.13.2/connectors/database/dynamodb/index.md
- openmetadata-docs-v1/content/v0.13.3/connectors/database/dynamodb/airflow.md
- openmetadata-docs-v1/content/v0.13.3/connectors/database/dynamodb/cli.md
- openmetadata-docs-v1/content/v0.13.3/connectors/database/dynamodb/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/dynamodb/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/dynamodb/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/dynamodb/index.md
> Fix Dynamodb doc

- openmetadata-docs-v1/content/v1.0.0/deployment/airflow/index.md
> [Docs] - 401 Unauthorized - Airflow troubleshooting

- openmetadata-docs-v1/content/v0.13.2/deployment/upgrade/bare-metal.md
- openmetadata-docs-v1/content/v0.13.2/deployment/upgrade/docker.md
- openmetadata-docs-v1/content/v0.13.2/deployment/upgrade/kubernetes.md
- openmetadata-docs-v1/content/v0.13.2/quick-start/local-deployment.md
- openmetadata-docs-v1/content/v0.13.2/sdk/python/ingestion/lineage.md
- openmetadata-docs-v1/content/v0.13.3/deployment/upgrade/bare-metal.md
- openmetadata-docs-v1/content/v0.13.3/deployment/upgrade/docker.md
- openmetadata-docs-v1/content/v0.13.3/deployment/upgrade/kubernetes.md
- openmetadata-docs-v1/content/v0.13.3/quick-start/local-deployment.md
- openmetadata-docs-v1/content/v0.13.3/sdk/python/ingestion/lineage.md
- openmetadata-docs-v1/content/v1.0.0/deployment/security/enable-jwt-tokens.md
- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/bare-metal.md
- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/docker.md
- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/kubernetes.md
- openmetadata-docs-v1/content/v1.0.0/quick-start/local-deployment.md
- openmetadata-docs-v1/content/v1.0.0/sdk/python/ingestion/lineage.md
I worked on updating the docs content to use newly added Warning and Tip styling 
#
#
> documentation: updated the content to use newly added Warning and Tip styling

- openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/error-with-placeholder/ErrorPlaceHolderIngestion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/success-screen/SuccessScreen.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
- openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/utils/IngestionUtils.tsx
- Change the Airflow link and fix the label for No Data Placeholder
#
#
> fix(ui):  airflow link change and label for no data ingestion

- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
> Bump Ingestion Version

- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/domo-dashboard/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/domo-dashboard/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/domo-dashboard/index.md
Add Domo List of features Table 
#
#
> Add Domo Docs for 1.0.0

- openmetadata-docs-v1/content/v0.13.2/deployment/kubernetes/on-prem.md
- openmetadata-docs-v1/content/v0.13.3/deployment/kubernetes/on-prem.md
- openmetadata-docs-v1/content/v1.0.0/deployment/kubernetes/on-prem.md
In new doc <p> tag is not required.
Before:
Now:
#
#
> Remove <P> tag which is not supported in doc-v1

- openmetadata-docs-v1/content/v1.0.0/deployment/kubernetes/values.md
> fix(docs): Update Helm Values

- ingestion/src/metadata/readers/github.py
- openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/common.py
Fixes #11340 
missing headers when sending the GET
#
#
> Fixes  #11340 - Add missing headers

- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/kubernetes.md
Upgrade Kubernetes Docs for pipelineServiceClient Config changes.
#
#
> Fix(docs): Upgrade Kubernetes Docs

- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/domo-dashboard/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/bigquery/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/clickhouse/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/databricks/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/datalake/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/db2/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/deltalake/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/domo-database/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/druid/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/glue/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/hive/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/mariadb/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/mssql/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/mysql/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/oracle/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/pinotdb/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/postgres/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/presto/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/redshift/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/singlestore/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/snowflake/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/sqlite/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/database/trino/index.md
> Fix links pointing to usage, lineage, queries

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/bigquery.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/glue.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/kafka.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/metabase.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/mysql.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/postgres.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/redshiftWithDBT.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/snowflake.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/superset.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/SearchFlow.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.js
I worked on adding an e2e test for the service requirement doc panel
- Test should fetch the selected service markdown doc file
- Test should highlight the field section when the service field is focused
#
#
> e2e: add e2e for service requirement doc panel

- ingestion/src/metadata/ingestion/source/database/athena/models.py
- ingestion/src/metadata/ingestion/source/database/athena/usage.py
Fix #11352: Fix athena usage models
#
#
> Fix #11352: Fix athena usage models

- ingestion/src/metadata/ingestion/lineage/parser.py
- ingestion/src/metadata/utils/helpers.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/11064
#
#
> Fixed clean_query method for \n

- openmetadata-docs-v1/content/v1.0.0/deployment/kubernetes/values.md
I worked on docs-v1 because saml config helm values were to be added.
#
#
> SAML CONFIG Helm values docs update

- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/ChangeEventHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/feeds/FeedResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/PostResourceContext.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/ThreadResourceContext.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/ChangeEventParser.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/FeedResourceTest.java
Cleanup code related FeedRepo and ChangeEventHandler
#
#
> Cleanup FeedRepository and ChangeEventHandler

- openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts
I worked on fixing the doc links.
#
#
> fix: doc links

- .github/workflows/cypress-integration-tests-mysql-skip.yml
- .github/workflows/cypress-integration-tests-postgresql-skip.yml
> Issue-11338 Cypress test skip for docs

- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/resources/elasticsearch/en/container_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/dashboard_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/glossary_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/mlmodel_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/pipeline_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/query_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/table_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/tag_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/topic_index_mapping.json
Add substring matching at description level with ngram indexing
#
- [] Bug fix
#
> Add Description Ngram for search

- ingestion/src/metadata/ingestion/source/database/postgres/metadata.py
- ingestion/src/metadata/ingestion/source/database/postgres/utils.py
Fix geometry type for postgres
Postgres fails for type geometry with error `GEOMETRY() takes no arguments`, which is an error related to library itself when creating table with geometry column like this `geometry(Geometry,4326),` it passed the `Geometry,4326` params in the args of `GEOMETRY` which is unexpected hence the error, with this pr we are overriding the `_get_column_info` method which is responsible for determining the type of column and explicitly setting the args to empty to avoid such errors
slack support thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1682698118936489
#
#
> Fix geometry type for postgres

- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/yarn.lock
Fixes https://github.com/open-metadata/OpenMetadata/security/dependabot/109
bump sync-i18n to v0.0.20
#
#
> bump sync-i18n to v0.0.20

- ingestion/src/metadata/profiler/orm/converter.py
- ingestion/src/metadata/profiler/orm/registry.py
- ingestion/src/metadata/profiler/orm/types/custom_array.py
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Databricks.md
Fix #11332: Fix databricks sample data ingestion for array datatype
Sample data ingestion fails in the case of array datatype for databricks since sqlalchamy returns the `np.ndarray` type of array while fetching sample data for the array column and it fails to convert it into JSON 
hence in this pr, I've created a custom array in which if we get the array of type `np.ndarray` convert it to a python list
#
#
> Fix #11332: Fix databricks sample data ingestion for array datatype

- openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/NodeSuggestions.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/NodeSuggestions.test.tsx
Fixes #11412 
https://user-images.githubusercontent.com/33024356/236158014-b0f0bacd-657d-4455-bee0-47decfd6e6a5.mov
#
#
> fix: use search api instead of suggest on lineage node

- openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AddAndRemoveTierAndOwner.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/EntityDetails.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Service.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/GlossaryDetailsRightPanel/GlossaryDetailsRightPanel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TestSuiteDetails/TestSuiteDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteDetailsPage/TestSuiteDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
Fixes [#11334](https://github.com/open-metadata/OpenMetadata/issues/11334)
Added cypress for Add and remove owner for
- All entity page
- DatabaseSchema details page
- Database details page
- Service page
- teams page
- test suite page
Added Cypress to add owner for
- Glossary
- Glossary term
Add and remove tier
- All entity
- database details page
- replaced put API with patch for updating owner in service page
- fixed edit owner icon not visible issue on test suite details page
#
#
> feat: added cypress flow of add and remove owner and tier

- openmetadata-ui/src/main/resources/ui/src/components/ServiceConnectionDetails/ServiceConnectionDetails.component.tsx
Fixes #11336 
mask Looker & Tableau config for format password
#
#
> fix(ui): mask api token for looker connection

- openmetadata-docs-v1/content/v1.0.0/deployment/docker/security.md
- openmetadata-docs-v1/content/v1.0.0/deployment/security/index.md
> Docs:Fix security doc links

- ingestion/src/metadata/ingestion/source/database/postgres/utils.py
Fix postgres cypress issue
#
#
> Fix postgres cypress issue

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ContainerVersion/ContainerVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardVersion/DashboardVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardVersion/DashboardVersion.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModelVersion/DataModelVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetVersion/DatasetVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelVersion/MlModelVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/SampleDataTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableTags/TableTags.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainer/tags-container.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicVersion/TopicVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/VersionTable/VersionTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/description/Description.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx
- openmetadata-ui/src/main/resources/ui/src/enums/common.enum.ts
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- openmetadata-ui/src/main/resources/ui/src/styles/spacing.less
Fixes:  #11407
- fix the color difference of edit tag.
- fix the version page layout issue, added border in tables and fix the background color issue.
- fix the spacing issue of tags in Entity info.
- fix the icon size of no data filter icon and change the spacing.
- remove the card from  no data placeholder.
#
#
> fixes(ui) : UI improvements

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/EntitySummaryPanel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/AlertsPage/AlertsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/position.less
Fixes comments of #11407
- Fix the overflowing of the title in the Entity summary panel
- Fix the missing icon in case of a long title 
- added placeholder if no description is there is Alert table
#
#
> fix(ui) :  fix overflowing issue on entity summary panel

- openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/cardlist/CardListItem/CardWithListItem.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/TierCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/tier-card.style.less
- openmetadata-ui/src/main/resources/ui/src/enums/service.enum.ts
- openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
#11407
https://user-images.githubusercontent.com/71748675/236447473-4bf0e016-1239-4b44-821d-8120c4db0290.mov
https://user-images.githubusercontent.com/71748675/236447918-97e396e2-a04d-48b4-a3cb-1b950527038a.mov
#
#
> ui: fixed feedback 1.0.1

- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/powerbi/airflow.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/powerbi/cli.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/powerbi/index.md
- openmetadata-docs-v1/content/v1.0.0/connectors/dashboard/powerbi/setup-powerbi-account.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Dashboard/PowerBI.md
Updated PowerBI docs to make non-admin APIs clear
#
#
> Updated PowerBI docs to make non-admin APIs clear

- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/ResourceRegistry.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardDataModelRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
> Fixes #11245 - fix test failures

- openmetadata-service/src/main/java/org/openmetadata/service/resources/tags/TagLabelCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/CompiledRule.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/RoleCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/RuleEvaluator.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectContext.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/policies/PolicyResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/RuleEvaluatorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/SubjectContextTest.java
> Fixes #11397 hasAnyRole and inAnyTeam condition policy error

- ingestion/src/metadata/ingestion/ometa/client.py
Fixes [#4664](https://github.com/psf/requests/issues/4664)
The change allows errors to be handled and retried.
I worked on this issue because I tested the changes in our current deployment and solved the issue.
#
#
> Fixes #4664: Allow requests to be retried

- openmetadata-docs-v1/content/v1.0.0/deployment/kubernetes/index.md
Include minikube start notes for kubernetes.
#
> docs: include minikube start notes for kubernetes

- ingestion/src/metadata/ingestion/source/database/salesforce/metadata.py
- openmetadata-docs-v1/content/v0.13.2/main-concepts/metadata-standard/schemas/entity/services/connections/database/salesforceConnection.md
- openmetadata-docs-v1/content/v0.13.3/main-concepts/metadata-standard/schemas/entity/services/connections/database/salesforceConnection.md
- openmetadata-docs-v1/content/v1.0.0/main-concepts/metadata-standard/schemas/entity/services/connections/database/salesforceConnection.md
- openmetadata-docs/content/main-concepts/metadata-standard/schemas/entity/services/connections/database/salesforceConnection.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/salesforceConnection.json
Fix #11468: Fix salesforce scheme issue
#
#
> Fix #11468: Fix salesforce scheme issue

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeader/EntityHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/EntitySummaryPanel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/EntitySummaryPanel.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardV2.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
Fixes  comments of #11407
- I worked on fixing the squeezing issue in Entity headers
- Shown only Entity name in right panel for every entity
#
#
> fix(ui): fix  the icon squeezing issue in entity headers and only name in right panel header

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightAlert.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/header/PageHeader.component.tsx
I worked on data insight report end-to-end tests.
#
#
> E2e data insight report

- openmetadata-ui/src/main/resources/ui/public/index.html
Fixes favicon and manifest path 404 errors...
#
#
> Fixed favicon and manifest path

- openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationFeedCard.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- openmetadata-ui/src/main/resources/ui/src/styles/tailwind.css
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
- I worked on fixing the underline that was coming on hover in Entity headers
https://user-images.githubusercontent.com/66266464/237040382-4e36f59c-46d8-4032-930b-14a00c039a5e.mov
#
#
> fix(ui): fix  the underline issue on entity cards

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
Added Whatsnew content for 1.0.1
https://user-images.githubusercontent.com/71748675/237060178-a6797d26-0909-49bc-ad36-e831dcb2409d.mov
#
#
> ui: added whats new content for 1.0.1

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardV2.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/components/size.less
- I worked on the ellipses in the tags and glossary page
- fix the misalignment of deleted tag issue in deleted entity 
#
#
> fix(ui): fix the ellipses and icon misplacement of entity headers

- openmetadata-ui/LICENSE
> Add missing license for UI module

- openmetadata-service/src/main/java/org/openmetadata/service/security/saml/SamlAssertionConsumerServlet.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/saml/SamlLoginServlet.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/saml/SamlMetadataServlet.java
- openmetadata-service/src/main/java/org/openmetadata/service/socket/FeedServlet.java
- openmetadata-service/src/main/java/org/openmetadata/service/socket/SocketAddressFilter.java
Log Some messages to Output stream instead of Stack Trace Priniting
#
#
> Servlets Log Error Messages

- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/models.py
Fix tableau models to make fields optional
support thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1683656534523199
#
#
> Fix tableau models to make fields optional

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/ChangeLogs.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> Fix what's new content 1.0.1

- ingestion/src/metadata/ingestion/source/database/vertica/queries.py
- ingestion/tests/cli_e2e/base/test_cli_db.py
Fix E2E Vertica & System Metric
#
#
> Fix E2E Vertica & System Metric

- openmetadata-docs-v1/content/v1.0.0/deployment/upgrade/index.md
With a couple of configs needed in 1.0.1 if people reuse old configs
#
#
> [Docs] - Add 1.0.1 YAML docs

- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/DataInsightsReportJob.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/ReportsHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightDescriptionAndOwnerTemplate.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightTotalAssetTemplate.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
Allows to manually trigger the job from API
#
#
> [InsightReport] DataInsight Manual trigger Job

- openmetadata-docs-v1/content/v0.13.2/deployment/kubernetes/eks.md
- openmetadata-docs-v1/content/v0.13.2/deployment/kubernetes/gke.md
- openmetadata-docs-v1/content/v0.13.2/deployment/kubernetes/on-prem.md
- openmetadata-docs-v1/content/v0.13.3/deployment/kubernetes/eks.md
- openmetadata-docs-v1/content/v0.13.3/deployment/kubernetes/gke.md
- openmetadata-docs-v1/content/v0.13.3/deployment/kubernetes/on-prem.md
- openmetadata-docs-v1/content/v1.0.0/deployment/kubernetes/eks.md
- openmetadata-docs-v1/content/v1.0.0/deployment/kubernetes/gke.md
- openmetadata-docs-v1/content/v1.0.0/deployment/kubernetes/on-prem.md
- openmetadata-docs/content/deployment/kubernetes/eks.md
- openmetadata-docs/content/deployment/kubernetes/gke.md
- openmetadata-docs/content/deployment/kubernetes/on-prem.md
Fixes typos in the documentation related to the words "persistent" and "deploy".
- I changed all occurrences of "presistent" to "persistent" and "delpoy" to "deploy"
- I was reading through the documentation and noticed that the two words were consistently misspelled. It was likely due to a copy paste of the same sentences.
- I did not test my changes. I only made changes in `.md` files.
I worked on these changes because I'm excited about the project and noticed the typos while reading the documentation.
#
#
> Fixes typos: Change presistent to persistent and delpoy to deploy

- ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
> Fix Airflow ingestion: check if downstream task are null

- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
cypress: updated workflow with cypress provided image
#
#
> cypress: updated workflow with cypress provided image

- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
Reverts open-metadata/OpenMetadata#11544
> Revert "cypress: updated workflow with cypress provided image"

- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/DataInsightsReportJob.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EmailUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/PaginatedEntitiesSource.java
Fixes mail to be sent to the team users in case the email is missing
#
#
> Data Insight Report Improvement

- ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
Otherwise upstream errors where the context does not end up being set break the pipeline
#
#
> Validate context in Airflow

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
- ingestion/src/metadata/utils/tag_utils.py
- ingestion/tests/unit/test_dbt.py
- ingestion/tests/unit/topology/pipeline/test_dagster.py
Validate if tags are created before attaching them to CreateRequest
Only attach the tags to create requests if the tag are successfully creating in OM
#
#
> Validate if tags are created before attaching them to CreateRequest

- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
Updating the Python version for inplace release
#
#
> updating python version

- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
Updating py version to 1.0.1.3
#
#
> Py ver update 1.0.1.3

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/settings/SettingsCache.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/settings/settings.json
Add Custom Logo Setting to be Configurable from Database
Mentioned here :- https://github.com/open-metadata/OpenMetadata/issues/11503#issuecomment-1540503503
#
#
> Add settings to Db for Custom Logo

- openmetadata-ui/src/main/resources/ui/src/components/ContainerDetail/ContainerDataModel/ContainerDataModel.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ContainerDetail/ContainerDataModel/ContainerDataModel.tsx
Fixes for Container Entity : https://github.com/open-metadata/OpenMetadata/issues/11281
- I worked on supporting separate tags and glossary column in container entity table
- Including the Version page
#
#
> feat(ui): supported separated tags and glossary column in container entity with version page

- openmetadata-docs-v1/content/v1.0.0/releases/roadmap/index.md
> Fix Roadmap docs alignment

- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/entity/classification/tag.json
- openmetadata-spec/src/main/resources/json/schema/type/basic.json
> 11579 Task - Change schema regex to allow parenthesis in the entity name

- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion-postgres.yml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata-postgres.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
Bump versions in main branch.
#
> fix: versions in main branch

- ingestion/examples/sample_data/datasets/tables.json
Fixes a task from https://github.com/open-metadata/OpenMetadata/issues/11579
Adding a table in the sample data with () and another with russian characters
#
#
> 11579 Task - Add () in sample data

- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityNameModal/EntityNameModal.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityNameModal/EntityNameModal.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/AnnouncementDrawer/AnnouncementDrawer.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/AnnouncementDrawer/AnnouncementDrawer.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/ManageButton/ManageButton.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TopicDetails/TopicDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/tour-page/TourPage.component.tsx
#11399
- Added edit displayName functionality for topic and dashboard entity
- Refactor code for topic and dashboard page
https://github.com/open-metadata/OpenMetadata/assets/71748675/8df082b0-3905-4498-b1de-efcec97c9157
#
#
> Feat(ui): update displayName part 2

- openmetadata-ui/src/main/resources/ui/cypress/constants/tagsAddRemove.constants.js
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardVersion/DashboardVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableTags/TableTags.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx
Fixes for Dashbord Entity : https://github.com/open-metadata/OpenMetadata/issues/11281
- Supporting separate tags and glossary columns in Dashboard entity table
- Included version page too.
#
#
> feat(ui): Supported separate column for Dashboard entity along with  version

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/MlModelPage/MlModelPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/serviceAPI.ts
#11399
Added update displayName functionality for
https://github.com/open-metadata/OpenMetadata/assets/71748675/13d49a7b-b4e8-4b47-b7c1-b352dd30e21a
https://github.com/open-metadata/OpenMetadata/assets/71748675/b34d2cb4-52d4-4baa-8dd5-87140f58cd55
#
#
> Feat(ui): update displayName part 3

- ingestion/tests/cli_e2e/base/test_cli_db.py
- ingestion/tests/cli_e2e/test_cli_snowflake.py
Increase delay for system metric in e2e tests
#
#
> Increase delay for system metric in e2e tests

- ingestion/Dockerfile
- ingestion/Dockerfile.ci
- ingestion/operators/docker/Dockerfile
- ingestion/operators/docker/Dockerfile-dev
> Fix #11610 - Add libsasl deps for kerberos

- openmetadata-service/pom.xml
Removed Docs , descriptor file is pointing to previous location
#
#
> Fix Descriptor File

- ingestion/src/metadata/ingestion/sink/elasticsearch.py
FQN for [tag](https://github.com/open-metadata/OpenMetadata/blob/4df64ef6fee10a608a2ea0d2db596eab5fbf9fdf/openmetadata-spec/src/main/resources/json/schema/entity/classification/tag.json#L31) is a string field
#
#
> Fix elastic-search reindex error from ingestion

- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModel.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelFeaturesList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineVersion/PipelineVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableTags/TableTags.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableTags/TableTags.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Tag/Tags/tags.tsx
- openmetadata-ui/src/main/resources/ui/src/components/VersionTable/VersionTable.component.tsx
Fixes for MlModel Entity : https://github.com/open-metadata/OpenMetadata/issues/11281
- Supporting separate tags and glossary columns in MlModel entity
- added border in tags displaying in version page
- removed the removable tag functionality in tag components.
#
#
> feat(ui): supported separate tags for mlmodel entity

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Teams.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/components/size.less
Closes #11608 
I worked on issue #11608 
#
#
> feat(#11608): show email in teams page

- ingestion/src/metadata/ingestion/source/database/glue/metadata.py
- ingestion/tests/unit/topology/database/test_glue.py
- openmetadata-docs/content/v1.0.0/connectors/database/glue/airflow.md
- openmetadata-docs/content/v1.0.0/connectors/database/glue/cli.md
- openmetadata-docs/content/v1.0.0/connectors/database/glue/index.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/glue/airflow.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/glue/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/glue/index.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/glueConnection.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Glue.md
Fix #11571: Support custom database name for glue
#
#
> Fix #11571: Support custom database name for glue

- openmetadata-ui/src/main/resources/ui/src/components/DashboardVersion/DashboardVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModelVersion/DataModelVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelDetails.interface.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataModelPage/DataModelPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
Fixes #11399
- Added Edit displayName feature for Datamodel entity
- Added displayName in the breadcrumb for version page
https://github.com/open-metadata/OpenMetadata/assets/71748675/cd8d3eb9-c454-498e-8a1c-b2f1a5486248
#
#
> feat(ui): added update displayName functionality for datamodel entity and updated breadcrumb with displayName for version page

- .snyk
- openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/deploy.py
- openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/ip.py
- openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/run_automation.py
- openmetadata-airflow-apis/openmetadata_managed_apis/operations/deploy.py
From the snyk report.
Also filtering false positives from the UI and server side
#
#
> Fix XSS warnings

- ingestion/src/metadata/pii/ner_scanner.py
- ingestion/src/metadata/pii/processor.py
- ingestion/tests/unit/pii/test_ner_scanner.py
Which was forcing the presidio package import out of scope. I broke this when trying to have the `NERScanner` with the `scan` as a classmethod. However, in this case it makes sense to properly handle the class state and initialize the analyzer only once in the init.
#
#
> Clean NER Scanner imports

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/storages/ContainerResourceTest.java
Part of fix #11492
#
- [ x] Bug fix
#
- [x ] I have commented on my code, particularly in hard-to-understand areas.
> Part of fix 11492 -  Add missing fields in Container update

- ingestion/src/metadata/readers/github.py
- openmetadata-docs/content/v1.0.0/connectors/dashboard/looker/airflow.md
- openmetadata-docs/content/v1.0.0/connectors/dashboard/looker/cli.md
- openmetadata-docs/content/v1.0.0/connectors/dashboard/looker/index.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/dashboard/looker/airflow.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/dashboard/looker/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/dashboard/looker/index.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Dashboard/Looker.md
> Fix GitHub reader headers and add docs

- ingestion/src/metadata/ingestion/api/parser.py
- ingestion/tests/unit/airflow/test_lineage_parser.py
This helps us throw a better error when the YAML config is malformed
#
#
> Fix parsing for Storage Services & Quick Airflow test

- .github/workflows/monitor-slack-link.yml
to send an alert to slack if https://slack.open-metadata.org/ stops being available
#
#
> Add slack monitor action

- openmetadata-ui/src/main/resources/ui/src/components/Modals/SchemaModal/SchemaModal.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Modals/SchemaModal/SchemaModal.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/RowData.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/RowData.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/SampleDataTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/SampleDataTable.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/sample.interface.ts
Fixes #11490
- I worked on converting the table to antd for better experience.
https://github.com/open-metadata/OpenMetadata/assets/66266464/2cd71528-7861-4c7d-bdae-f6cf2efaf2ab
#
#
> fixes #11490 : scrolling issue in Sample data

- ingestion/src/metadata/pii/column_name_scanner.py
- ingestion/src/metadata/pii/ner_scanner.py
- ingestion/src/metadata/pii/processor.py
- ingestion/tests/unit/pii/test_ner_scanner.py
to use typed classes and commented logic
#
#
> Restructure NER Scanner internals

- ingestion/src/metadata/ingestion/source/database/oracle/metadata.py
- ingestion/src/metadata/ingestion/source/database/oracle/queries.py
- ingestion/src/metadata/ingestion/source/database/oracle/utils.py
Oracle view lineage was not getting generated for all the views this was because we were executing two separate queries to fetch the view definition of regular views and materialized views. [Here](https://github.com/open-metadata/OpenMetadata/blob/4f953de97ffeca5f50a551c96c07a78fc3ebf98c/ingestion/src/metadata/utils/sqlalchemy_utils.py#L51)  we are maintaining a map of view names against view definition so the materialized views view definition override the result of regular views hence view definition was not found and the lineage was not generated. 
#
#
> Fix view lineage not generated for oracle

- openmetadata-ui/src/main/resources/ui/src/components/ContainerDetail/ContainerDataModel/ContainerDataModel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModels/ModelTab/ModelTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelFeaturesList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicSchema/TopicSchema.tsx
- fix the loading issue when tags select is open and glossary tag is set to open or wise versa.
Issue : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/9203aec8-9c39-4867-8f67-5fa8751a862e
Resolved : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/5a5b9c51-535f-4b2e-a813-42ec8766f879
#
#
> fix(ui): fix  the loading of tag input

- openmetadata-service/src/main/java/org/openmetadata/service/util/UserUtil.java
When We can successfully connect to Email Server , the OM Server should be generating a random PWD.
#
#
> Fix Random Password not generated when Email Config is present

- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
Replace HTML table with ANTD table, and refactor the code in mlModel component
#
#
> refactor(ui): replace html table with antd table and refactor code

- ingestion/setup.py
> Fix typing_extension verson

- ingestion/src/metadata/ingestion/source/messaging/kafka/connection.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/11728
#
#
> Fixes 11728: Kafka connection fails due to CustomSecretStr if basicAuthUserInfo is passed

- openmetadata-service/src/main/java/org/openmetadata/service/secrets/masker/EntityMaskerFactory.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/masker/NoopEntityMasker.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/masker/PasswordEntityMasker.java
- openmetadata-service/src/test/java/org/openmetadata/service/secrets/masker/EntityMaskerFactoryTest.java
> Remove unnecessary singletons

- openmetadata-ui/pom.xml
- openmetadata-ui/src/main/resources/ui/webpack.config.prod.js
> fix: webfont loading issue

- openmetadata-ui/src/main/resources/ui/src/components/authentication/auth-provider/AuthProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/AuthProvider.util.ts
Fixes: Refresh token fails on no expiry found
If no refresh token present will not execute and timer related to refresh
https://github.com/open-metadata/OpenMetadata/assets/12962843/66fd4140-d521-4f52-8fed-451130ab901d
#
#
> fix(ui): null expiry means infinite lifetime for token

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> Fix what's new content 1.0.2

- .github/workflows/docker-openmetadata-db.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- .github/workflows/docker-openmetadata-postgres.yml
- .github/workflows/docker-openmetadata-server.yml
- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion-postgres.yml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata-postgres.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
> Version upgrade

- openmetadata-docs/content/v1.0.0/deployment/upgrade/kubernetes.md
Fixes a typo in the deployment/kubernetes.md docs.
#
#
> Update kubernetes.md typo

- ingestion/src/metadata/ingestion/source/dashboard/looker/connection.py
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/looker.json
> Add new Looker test connection steps

- openmetadata-ui/src/main/resources/ui/src/components/common/error-with-placeholder/ErrorPlaceHolderES.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/error-with-placeholder/ErrorPlaceHolderIngestion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/onboarding/Onboarding.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/tailwind.css
I worked on removing the `tw-card` tailwind class and used the AntD Card component.
#
#
> chore(ui): clean up the `tw-cad` tailwind class

- openmetadata-docs/content/v1.0.0/releases/releases/index.md
- openmetadata-docs/content/v1.0.0/releases/releases/latest.md
- I worked on updated the doc release section along with the latest release section
#
#
> fix : updated the doc release section

- conf/openmetadata.yaml
- docker/openmetadata.yaml
- openmetadata-docs/content/v1.1.0-snapshot/deployment/kubernetes/index.md
- openmetadata-service/src/main/java/org/openmetadata/service/util/ElasticSearchClientUtils.java
- openmetadata-spec/src/main/resources/json/schema/configuration/elasticSearchConfiguration.json
When openmetadata app has been idle for a while, calling any search method of an ElasticsearchRepository (which uses the RestHighLevelClient for the underlying ES connection) results in a java.io.IOException: Connection reset by peer.
Example:
```
**Calling** /api/v1/analytics/dataInsights/charts/aggregate?startTs=1684589207795&endTs=1684848407796&dataInsightChartName=TotalEntitiesByTier&dataReportIndex=entity_report_data_index
**Response** {"responseMessage":"An exception with message [Connection reset by peer] was thrown while processing request."}
```
This pull request expose an new env var `ELASTICSEARCH_KEEP_ALIVE_TIMEOUT_SECS`, and enable TCP keep alive strategy.
#
#
> Add ES RestHighLevelClient TCP keep alive timeout

- conf/openmetadata.yaml
- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplicationConfig.java
- openmetadata-service/src/main/java/org/openmetadata/service/extension/NoOpExtension.java
- openmetadata-service/src/main/java/org/openmetadata/service/extension/OpenMetadataExtension.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/CollectionRegistry.java
- openmetadata-spec/src/main/resources/json/schema/configuration/extensionConfiguration.json
Added Initialisation for Extension in OM
#
#
> Add extension to OpenMetadata

- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
Fixes https://openmetadata.slack.com/archives/C02B6955S4S/p1684849892492659
#
#
> Remove Unnecessary fields from GET and DELETE

- ingestion/operators/docker/run_automation.py
- ingestion/src/metadata/ingestion/connections/test_connections.py
To get some verbosity when running this in a container
#
#
> Improve logging for test connection workflow

- ingestion/Dockerfile
- ingestion/Dockerfile.ci
- ingestion/operators/docker/Dockerfile
- ingestion/operators/docker/Dockerfile-dev
Fixes #9593 by installing `idb-db-sa` for those target platforms that support it. We'll continue to monitor the IBM [discussion](https://ibm-data-and-ai.ideas.ibm.com/ideas/DB2CON-I-92), but having the amd image containing the dependency should solve most of the issues raised by the community, since the default target platform for deployments of the ingestion containers is amd
#
#
> Install ibm-db-sa if not ARM

- openmetadata-docs/content/v1.0.0/connectors/pipeline/airflow/configuring-lineage.md
- openmetadata-docs/content/v1.0.0/menu.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/pipeline/airflow/configuring-lineage.md
- openmetadata-docs/content/v1.1.0-snapshot/menu.md
> [Docs] - Airflow lineage docs

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeader/EntityHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/index.js
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
Fixes text color and font weights
Text color - 292929
#
#
> fix: update text colors to grey

- openmetadata-ui/src/main/resources/ui/src/components/JSONSchemaTemplate/DescriptionFieldTemplate.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/FormBuilder/FormBuilder.tsx
I worked on hiding the json schema fields default description.
#
#
> chore(ui): hide json schema fields default description

- ingestion/tests/cli_e2e/base/test_cli_db.py
- ingestion/tests/cli_e2e/common/test_cli_db.py
- ingestion/tests/cli_e2e/test_cli_snowflake.py
Since it was not reliable on processing the DDLs during the test. We are getting almost daily errors, so until we cannot guarantee stability, better to keep it out
#
#
> Remove e2e system metrics test

- ingestion/src/metadata/ingestion/ometa/auth_provider.py
Fixes #9993 
I worked on fixing line too long
#
#
> Fix LineTooLong

- ingestion/tests/cli_e2e/base/test_cli.py
- ingestion/tests/cli_e2e/base/test_cli_db.py
- ingestion/tests/cli_e2e/common/test_cli_db.py
- ingestion/tests/cli_e2e/test_cli_redshift.py
- ingestion/tests/cli_e2e/test_cli_snowflake.py
Also using ast.literal_eval as a safer version of eval just to pick up the dictionary info from stdout
#
#
> Fix redshift e2e with new lineage info

- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/bigquery.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/common/ServiceDocPanel/ServiceDocPanel.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/regex.constants.ts
I worked on fixing the list field highlighting in service connection form
https://github.com/open-metadata/OpenMetadata/assets/59080942/3cc7a82a-801e-426d-ae5c-08426644e6c6
#
#
> fix(ui): list field highlighting in service connection form

- openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.tsx
- Added tests for MyDataWidget component
- Fix no data placeholder for mydata widget
#
#
> test(ui): unit tests for my data widget

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Teams.spec.js
> cypress: fixed flaky cypress for service specs

- ingestion/src/metadata/ingestion/source/metadata/atlas/metadata.py
- openmetadata-docs/content/v1.0.0/connectors/metadata/amundsen/airflow.md
- openmetadata-docs/content/v1.0.0/connectors/metadata/amundsen/cli.md
- openmetadata-docs/content/v1.0.0/connectors/metadata/amundsen/index.md
- openmetadata-docs/content/v1.0.0/connectors/metadata/atlas/airflow.md
- openmetadata-docs/content/v1.0.0/connectors/metadata/atlas/cli.md
- openmetadata-docs/content/v1.0.0/connectors/metadata/atlas/index.md
Fix #11781: Fix atlas lineage issue
#
#
> Fix #11781: Fix atlas lineage issue

- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/bigquery.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/glue.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/kafka.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/metabase.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/mysql.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/postgres.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/redshiftWithDBT.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/snowflake.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/superset.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/common/FilterPattern/FilterPattern.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/FilterPattern/FilterPattern.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/tsconfig.json
Fixes #11575 
I worked on issue #11575 
https://github.com/open-metadata/OpenMetadata/assets/59080942/d79d2a1b-3e89-4a06-995e-29f25b39c19e
#
#
> fix(#11575): filter pattern does not work if `,` in regex

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
> Fix #11855: Tags can get deleted if the service name matches partially with targetFQN

- .github/workflows/docker-openmetadata-db.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- .github/workflows/docker-openmetadata-postgres.yml
- .github/workflows/docker-openmetadata-server.yml
- docker/docker-compose-ingestion/docker-compose-ingestion-postgres.yml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata-postgres.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
Feature: Prepare versions for 1.0.3 release.
#
#
> feat: Update Versions to prepare for 1.0.3 Release

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/EntityDetails.spec.js
updated cypress as per new changes
#
#
> cypress: updated cypress for entityDetails as per new changes

- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/models.py
Fixed null values in upstreamColumns for tableau data models
ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1685079306628629?thread_ts=1683803765.308049&cid=C02B6955S4S
#
#
> Fixed null values in upstreamColumns for tableau data models

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/ActivityFeedCardV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/FeedCardHeader/feed-card-header-v1.style.less
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/activity-feed-card.style.less
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/Shared/ActivityFeedActions.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/KPIChartV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TotalEntityInsightV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/left-sidebar.less
- openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/RightSidebar.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/Tags/Tags.less
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsViewer/tags-viewer.tsx
- openmetadata-ui/src/main/resources/ui/src/components/recently-viewed/recently-viewed.less
- openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/my-data.less
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
> feat: update style guide

- openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogGenericExceptionMapper.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UsageRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/usage/UsageResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/usage/UsageResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/entity/policies/accessControl/resourceDescriptor.json
> Fixes #11872 - Add authorization for Usage APIs

- ingestion/Dockerfile
- ingestion/Dockerfile.ci
> fix: CI Snyk Reports

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MetadataServiceRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/metadata/MetadataServiceResource.java
Fixes https://openmetadata.slack.com/archives/C02B6955S4S/p1684451331345989
#
#
> Fix Update Issue in MetadataService in case the ES config is updated

- ingestion/examples/sample_data/tests/testSuites.json
- ingestion/src/metadata/data_quality/api/workflow.py
- ingestion/src/metadata/data_quality/validations/base_test_handler.py
- ingestion/src/metadata/ingestion/source/database/sample_data.py
- ingestion/tests/integration/ometa/test_ometa_test_suite.py
- ingestion/tests/integration/test_suite/test_workflow.py
- ingestion/tests/unit/test_suite/test_validations_databases.py
- ingestion/tests/unit/test_suite/test_validations_datalake.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestSuiteResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/api/tests/createTestSuite.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/testSuitePipeline.json
- openmetadata-spec/src/main/resources/json/schema/tests/basic.json
- openmetadata-spec/src/main/resources/json/schema/tests/testSuite.json
Reverts open-metadata/OpenMetadata#11881
> Revert "Fixe Issue #11863 - Add Status logic for test case results"

- openmetadata-docs/content/v1.0.0/releases/releases/index.md
- openmetadata-docs/content/v1.0.0/releases/releases/latest.md
> Docs: Add 1.0.3 Release Notes

- .github/workflows/publish-maven-package.yml
* Create manual.yml
* Maven actions triggering in various scenerios
* Removing the testfile
* Updating the event to push and adding mvn build version
* Reverting the  mvn release build version changes
#
#
> fix(ci): Maven Publish GitHub (#11762)

- ingestion/src/metadata/profiler/metrics/system/system.py
Disabling snowflake system metrics while working on https://github.com/open-metadata/OpenMetadata/issues/11743
#
#
> Temporarily disable sys. metrics for snowflake while working on #11743

- openmetadata-service/src/main/resources/elasticsearch/jp/dashboard_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/glossary_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/mlmodel_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/team_index_mapping.json
> Fix Japanese language indexing

- openmetadata-docs/content/v0.13.3/connectors/ingestion/workflows/profiler/index.md
- openmetadata-docs/content/v0.13.3/developers/apis/api-organization.md
- openmetadata-docs/content/v0.13.3/developers/apis/implementation-notes.md
- openmetadata-docs/content/v0.13.3/developers/apis/index.md
- openmetadata-docs/content/v0.13.3/developers/schemas/index.md
- openmetadata-docs/content/v0.13.3/developers/schemas/schema-language.md
- openmetadata-docs/content/v0.13.3/menu.md
- openmetadata-docs/content/v1.0.0/connectors/ingestion/workflows/profiler/index.md
- openmetadata-docs/content/v1.0.0/developers/apis/api-organization.md
- openmetadata-docs/content/v1.0.0/developers/apis/implementation-notes.md
- openmetadata-docs/content/v1.0.0/developers/apis/index.md
- openmetadata-docs/content/v1.0.0/developers/schemas/index.md
- openmetadata-docs/content/v1.0.0/developers/schemas/schema-language.md
- openmetadata-docs/content/v1.0.0/menu.md
Added profiler, APIs and Schema doc back
#
#
> doc: Added profiler, apis and schemas documentation back

- ingestion/src/metadata/data_insight/processor/entity_report_data_processor.py
Add a check for empty string in the description entity processor. If we have the description attribute for the entity object we'll check to make sure this description is not empty.
#
#
> fix: check for empty description strings

- openmetadata-service/src/main/resources/elasticsearch/en/topic_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/topic_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/topic_index_mapping.json
> Change ES mapping maximumMessageSize & retentionSize to long

- openmetadata-docs/content/v0.13.3/deployment/bare-metal/index.md
- openmetadata-docs/content/v0.13.3/deployment/docker/index.md
- openmetadata-docs/content/v0.13.3/deployment/kubernetes/index.md
- openmetadata-docs/content/v1.0.0/deployment/bare-metal/index.md
- openmetadata-docs/content/v1.0.0/deployment/docker/index.md
- openmetadata-docs/content/v1.0.0/deployment/kubernetes/index.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/bare-metal/index.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/docker/index.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/kubernetes/index.md
doc: updated documentation info for DB requiremenst
](doc: updated documentation info for DB requiremenst)
#
#
> doc: updated documentation info for DB requiremenst

- openmetadata-ui/src/main/resources/ui/src/components/ContainerDetail/ContainerDataModel/ContainerDataModel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModels/ModelTab/ModelTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicSchema/TopicSchema.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/ContainerDetailUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/ContainerDetailUtils.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DataModelsUtils.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TopicSchema.utils.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TopicSchemaUtils.test.ts
- fix the tags assigning issue with the same column name in entities tables.
https://github.com/open-metadata/OpenMetadata/assets/66266464/238ac994-6ced-4a6c-8afd-c68a50fb87b6
#
#
> fix(ui): the tags issue with same column name in entities

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/11875
#
#
> Fix 11875: Add check to see if parent table exists in OM

- .github/workflows/docker-openmetadata-server.yml
> fix(ci): version bump to 1.0.4

- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/oracle/airflow.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/oracle/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/oracle/index.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/oracleConnection.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Oracle.md
Fixes [#11726](https://github.com/open-metadata/OpenMetadata/issues/11726) 
Add database name filed for oracle db
#
#
> Add database name filed for oracle db

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/src/constants/regex.constants.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
Fixes #11589 
I worked on issues #11589 
https://github.com/open-metadata/OpenMetadata/assets/59080942/c353d01d-c097-4d7a-a23f-93fea036b73e
#
#
> fix( #11589):japanese/chinese language support in custom property name

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestConnectionDefinitionRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/connections/TestConnectionDefinitionResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/services/connections/TestConnectionDefinitionResourceTest.java
Instead of deleting and recreating
#
#
> Update test conn definition on initialize

- ingestion/examples/airflow/dags/airflow_lineage_operator.py
- ingestion/src/airflow_provider_openmetadata/lineage/runner.py
- ingestion/tests/integration/lineage/airflow/test_airflow_lineage.py
> Fix #11752 - Multiple inlets in AirflowLineageOperator

- .github/workflows/monitor-slack-link.yml
- scripts/slack-link-monitor.py
Since the current approach with `jq` is giving us some failures which look like false positives. Trying to set a more comprehensive approach with Python which will give us some more control and logging over what is happening.
#
#
> Use python for Slack Link Monitoring

- .github/workflows/monitor-slack-link.yml
Adding a missing checkout step for the new script
#
#
> Fix link monitor GA

- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/ParameterForm.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/ParameterForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/schema-editor/SchemaEditor.tsx
- openmetadata-ui/src/main/resources/ui/src/mocks/TestSuite.mock.ts
- openmetadata-ui/src/main/resources/ui/src/pages/teams/ImportTeamsPage/ImportTeamsPage.test.tsx
Fixes #11848 
Add strategy and threshold to the SQL test #11848
#
#
> fix (ui): Add `strategy` and `threshold` to the SQL test #11848

- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/mssqlConnection.json
Fixes #11813 
I worked on adding lineage support from UI for Mssql
#
#
> Add Lineage support for mssql

- openmetadata-docs/content/v1.0.0/deployment/security/amazon-cognito-sso/bare-metal.md
- openmetadata-docs/content/v1.0.0/deployment/security/amazon-cognito-sso/docker.md
- openmetadata-docs/content/v1.0.0/deployment/security/amazon-cognito-sso/kubernetes.md
- openmetadata-docs/content/v1.0.0/deployment/security/auth0/bare-metal.md
- openmetadata-docs/content/v1.0.0/deployment/security/auth0/docker.md
- openmetadata-docs/content/v1.0.0/deployment/security/auth0/kubernetes.md
- openmetadata-docs/content/v1.0.0/deployment/security/custom-oidc/bare-metal.md
- openmetadata-docs/content/v1.0.0/deployment/security/custom-oidc/docker.md
- openmetadata-docs/content/v1.0.0/deployment/security/custom-oidc/kubernetes.md
- openmetadata-docs/content/v1.0.0/deployment/security/google/bare-metal.md
- openmetadata-docs/content/v1.0.0/deployment/security/google/docker.md
- openmetadata-docs/content/v1.0.0/deployment/security/google/kubernetes.md
- openmetadata-docs/content/v1.0.0/deployment/security/keycloak/bare-metal.md
- openmetadata-docs/content/v1.0.0/deployment/security/keycloak/docker.md
- openmetadata-docs/content/v1.0.0/deployment/security/keycloak/kubernetes.md
- openmetadata-docs/content/v1.0.0/deployment/security/okta/bare-metal.md
- openmetadata-docs/content/v1.0.0/deployment/security/okta/docker.md
- openmetadata-docs/content/v1.0.0/deployment/security/okta/kubernetes.md
- openmetadata-docs/content/v1.0.0/deployment/security/one-login/bare-metal.md
- openmetadata-docs/content/v1.0.0/deployment/security/one-login/docker.md
- openmetadata-docs/content/v1.0.0/deployment/security/one-login/kubernetes.md
Updated the authentication configuration docs to reflect the latest configuration 
#
> Fix authentication configuration docs to reflect to 

- openmetadata-docs/content/v1.0.0/sdk/python/ingestion/lineage.md
Adding import EntityReference to run the instructions row by row fluently.
#
#
> Update sdk/python/ingestion/lineage.md docs

- ingestion/src/metadata/ingestion/source/database/database_service.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/11954
#
#
> Fixed Mark Deleted Tables for multiple DBs

- ingestion/src/airflow_provider_openmetadata/lineage/callback.py
> Fix Airflow callback import

- ingestion/operators/docker/Dockerfile
- ingestion/operators/docker/Dockerfile-dev
- ingestion/setup.py
We observed huge memory spikes when running the redshift ingestion, which came together with slow performance, when running the ingestion from the ingestion-base image.
- Changed a few things on the ingestion-base image, specifically to the postgres system libraries.
- After that, we also needed to fix the version sqlalchemy-redshift==0.8.12. Looks like from 0.8.12 to 0.8.13 something messed things up (we were using 0.8.14). Will look further on this one.
#
#
> Fix Redshift performance and memory issues for ingestion-base

- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchIndexDefinition.java
- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchIndexFactory.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/util/FormatterUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
Resolves #12019 
Resolves #12020 
#
#
> Reindex improvement

- openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/feeds/FeedResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/FeedResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/secrets/ExternalSecretsManagerTest.java
> Fixes #11883 - A user can resolve a task created by him

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/looker/parser.py
- openmetadata-docs/content/v1.1.0-snapshot/connectors/dashboard/looker/airflow.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/dashboard/looker/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/dashboard/looker/index.md
- openmetadata-service/src/main/java/org/openmetadata/service/resources/datamodels/DashboardDataModelResource.java
- openmetadata-spec/src/main/resources/json/schema/api/data/createDashboardDataModel.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/dashboardDataModel.json
Two things are happening here:
- Adding the `project` property to dashboard Data Models, similar to what we did for dashboards
- Implementing the project ingestion for Looker (both dashboards and Data Models)
#
#
> Add `project` to Data Models JSON Schema & Implement in Looker

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/WorkflowRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/AWSSSMSecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/AWSSecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/InMemorySecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/NoopSecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/SecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/SecretsManagerFactory.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/IngestionPipelineBuilder.java
- openmetadata-service/src/test/java/org/openmetadata/service/secrets/SecretsManagerLifecycleTest.java
Fixes #11966.
For the managed SM, we control the full secret lifecycle from OM: we create the secret whenever a new service is created, but we missed deleting it at the end.
This patch implements the capabilities in the server when we have configured the managed AWS SSM and managed AWS KMS
#
#
> Fix #11966 - Add delete secrets options for managed SM

- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightDescriptionAndOwnerTemplate.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightTotalAssetTemplate.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/entity/IngestionPipelineFormatter.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/entity/KpiFormatter.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/entity/QueryFormatter.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/entity/TestCaseFormatter.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- Fixes Exceptions in case of different Fields
- Limit Data Insight Report Double to two digits
- Owner Field invalid in case of Thread for some entities
#
#
> Bug fixes for Activity Feed + Restrict digits to 2' place

- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/Airflow.md
Fixes #11978
The details about backend db connections from Airflow were removed and this is super misleading for users when trying to fill in the gaps.
#
#
> Fix #11978 - Fix Airflow UI docs

- openmetadata-docs/content/v1.0.0/connectors/ingestion/workflows/dbt/dbt-troubleshooting.md
- openmetadata-docs/content/v1.0.0/connectors/ingestion/workflows/dbt/index.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/ingestion/workflows/dbt/dbt-troubleshooting.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/ingestion/workflows/dbt/index.md
> Update dbt docs for S3

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
- ingestion/src/metadata/utils/fqn.py
Fixed dbt test column name
#
#
> Fixed dbt test column name

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
Added dbt test_metadata check
#
#
> Added dbt test_metadata check

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/8946
Added PowerBI projects
#
#
> Added Powerbi Lineage across workspaces and datamodel projects

- ingestion/src/metadata/ingestion/source/pipeline/dagster/client.py
- ingestion/src/metadata/ingestion/source/pipeline/dagster/connection.py
- ingestion/src/metadata/ingestion/source/pipeline/dagster/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/dagster/models.py
- ingestion/src/metadata/ingestion/source/pipeline/pipeline_service.py
- ingestion/tests/unit/topology/pipeline/test_dagster.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/11987
#
#
> Fixed dagster bugs and Added Pydantic Models

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/TagsAddRemove.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV1/TagsContainerV1.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV1/TagsContainerV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV1/TagsTree.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.ts
- Supported separate tags for glossary and tags in entity pages.
#
#
> fix(ui):supported separate tags for glossary and tags

- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/Airflow.spec.js
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/Airflow.md
I worked on fixing the airflow cypress e2e test.
#
#
> fix(ui): airflow cypress test

- ingestion/Dockerfile
- ingestion/Dockerfile.ci
- ingestion/operators/docker/Dockerfile
- ingestion/operators/docker/Dockerfile-dev
> Fixed mysqlclient dep

- openmetadata-docs/content/v1.1.0-snapshot/releases/roadmap/index.md
> [Docs] - Update roadmap date

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticSearch/ElasticSearchClientImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/openSearch/OpenSearchClientImpl.java
added search for test case index
> added search for test case index

- openmetadata-docs/content/v1.0.0/releases/roadmap/index.md
> [Docs] - Update Roadmap 1.0.0 dir

- openmetadata-service/src/main/java/org/openmetadata/service/ChangeEventConfig.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/ReportsHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/ActivityFeedAlertCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatasourceConfig.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/settings/SettingsCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/tags/TagLabelCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/AWSSSMSecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/AWSSecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/InMemorySecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/NoopSecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BotTokenCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/auth/UserTokenCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/PolicyCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/RoleCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/saml/SamlSettingsHolder.java
- openmetadata-service/src/main/java/org/openmetadata/service/socket/WebSocketManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EmailUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/MicrometerBundleSingleton.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/ReIndexingHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/TablesInitializer.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/RuleEvaluatorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/SubjectContextTest.java
Fixing sonar issues for static variables in the code
#
#
> Fix sonar issues for static variable names

- openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/dashboardAPI.ts
> fixed: Dashboard services UI error #12003

- ingestion/src/metadata/examples/workflows/oracle_lineage.yaml
- ingestion/src/metadata/examples/workflows/oracle_usage.yaml
- ingestion/src/metadata/ingestion/source/database/oracle/connection.py
- ingestion/src/metadata/ingestion/source/database/oracle/lineage.py
- ingestion/src/metadata/ingestion/source/database/oracle/queries.py
- ingestion/src/metadata/ingestion/source/database/oracle/query_parser.py
- ingestion/src/metadata/ingestion/source/database/oracle/usage.py
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/oracle/airflow.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/oracle/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/oracle/index.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/ingestion/lineage/index.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/oracleConnection.json
> Fix #10175 - Add Oracle lineage and usage

- ingestion/src/metadata/ingestion/source/database/dbt/constants.py
- ingestion/src/metadata/ingestion/source/database/dbt/dbt_utils.py
- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
- ingestion/tests/unit/test_dbt.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/6874
Moved methods to dbt_utils
#
#
> Fix 6874: Added Support for lineage from dbt ephemeral nodes

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/activity-feed-tab.less
- openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Users/Users.style.less
- openmetadata-ui/src/main/resources/ui/src/pages/UserPage/UserPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/components/drawer.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
Fixes #11983
Show all the entities which are directly owned by the user or are owned by the team which contains this user.
#
#
> feat: show all entities related to user

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelDetails.interface.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataModelPage/DataModelPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/MlModelPage/MlModelPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TopicDetails/TopicDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
> fix(ui): update details on task resolve

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/TeamsHierarchy.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AddRoleAndAssignToUser.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TeamsSelectable/TeamsSelectable.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- fixed failing cypress test of main branch
- added no data placeholder to table entity details
- fixed soft-delete & restore entity bug
#
#
> cypress: fixed failing cypress tests of main

- ingestion/src/metadata/ingestion/source/dashboard/looker/columns.py
- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
- ingestion/tests/unit/topology/dashboard/test_looker.py
> Fix #12106 - Fix looker chart `sourceUrl` & Array datatype handling

- ingestion/operators/docker/main.py
To make sure that regardless of the Workflow being executed, everything is properly sent to Argo's logs.
#
#
> Set logger level for ingestion-base

- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/AddDataQualityTest.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPanel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPanel.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCaseStatusModal/TestCaseStatusModal.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCases/TestCases.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.style.less
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/profilerDashboard.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/QualityTab/QualityTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TestSuite/AddTestSuiteForm/AddTestSuiteForm.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Color.constants.ts
- openmetadata-ui/src/main/resources/ui/src/constants/profiler.constant.ts
- openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
- Worked on data quality feedback
#
#
> ui: worked on DQ feedback part 2

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
> Powerbi loop bug fix

- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestSuiteResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
- Hash testSuite fqn+append `.testSuite`
- handle no test cases passed on creating logical test suite
#
#
> fix: hash name of test suite + append

- openmetadata-docs/content/v1.0.0/deployment/security/enable-ssl/nginx.md
> Docs: add proxy_pass setting for nginx

- ingestion/src/metadata/ingestion/source/metadata/atlas/metadata.py
- ingestion/tests/unit/topology/metadata/test_atlas.py
Fix atlas lineage custom db name issue
#
#
> Fix atlas lineage custom db name issue

- ingestion/src/metadata/ingestion/source/database/databricks/models.py
- ingestion/src/metadata/ingestion/source/database/databricks/unity_catalog/metadata.py
Databricks Support Table Constraints
#
#
> Databricks Support Table Constraints

- ingestion/src/metadata/utils/datalake/csv_tsv_dispatch.py
- ingestion/src/metadata/utils/datalake/parquet_dispatch.py
Move Pandas import to methods instead of toplevel
> Move Top Level Imports

- bootstrap/sql/org.postgresql.Driver/v013__create_db_connection_info.sql
Fix Migrations where the migrations in postgres was appending instead or replacing
> Fix Migrations

- ingestion/examples/sample_data/topics/topics.json
- ingestion/src/metadata/ingestion/source/database/sample_data.py
- openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/query/QueryResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/topics/TopicResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/mask/PIIMasker.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/query/QueryResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/topics/TopicResourceTest.java
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTopic/SampleDataTopic.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTopic/SampleDataTopic.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/topicsAPI.ts
If a query is flagged as `PII.Sensitive`, we won't show it anymore to non-owners/admins/bots on the LIST API.
#
#
> Mask queries, Table sample data and Topic sample data

- ingestion/tests/unit/test_query_parser.py
> Fix SQLLineage Test

- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/operators/docker/Dockerfile-dev
> Remvoed ibm db arch

- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/TestSuiteIngestion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddTestCaseList/AddTestCaseList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddTestCaseList/AddTestCaseList.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPanel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCases/TestCases.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummary.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TestSuite/AddTestSuiteForm/AddTestSuiteForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TestSuite/TestSuiteStepper/TestSuiteStepper.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/elasticsearch.constant.ts
- openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteDetailsPage/TestSuiteDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
Worked on DQ feedback
- integrated permission for test suite and test case
- added test case re-indexing support
- updated dynamic name of test suite ingestion pipeline
- added support to updated displayName of test case
- updated UI of "Add Test Case form" same as add test case modal of logical test suite
- other miner feedbacks
#
#
> ui: worked on DQ feedback part 3

- ingestion/src/metadata/data_quality/validations/mixins/sqa_validator_mixin.py
Fixes undefined bool of clause
#
#
> fix: check on undefined bool value of clause

- openmetadata-docs/content/v1.0.0/connectors/ingestion/workflows/profiler/auto_tagging.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/ingestion/workflows/profiler/auto_tagging.md
> [Docs] - Auto tagging Windows troubleshooting

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/SampleDataTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/tour/Tour.tsx
- openmetadata-ui/src/main/resources/ui/src/components/tour/tour.style.less
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- fixed tour flow and address feedback.
#
#
> fixed(ui): updated tour flow and feedback

- ingestion/src/metadata/mixins/pandas/pandas_mixin.py
Fixes Datalake Profiler bug
This fails for parquet for AWS S3 datalake conn
#
#
> fix connection kwargs bug in profiler

- ingestion/src/metadata/profiler/api/workflow.py
- ingestion/src/metadata/profiler/sink/metadata_rest.py
- ingestion/src/metadata/utils/datalake/json_dispatch.py
Fixes Infinite Loop over any exception on profiler workflow
#
#
> Fix Profiler Workflow infinite loop

- openmetadata-docs/content/v1.0.0/connectors/storage/s3/airflow.md
- openmetadata-docs/content/v1.0.0/connectors/storage/s3/cli.md
- openmetadata-docs/content/v1.0.0/connectors/storage/s3/index.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/storage/s3/airflow.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/storage/s3/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/storage/s3/index.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Storage/S3.md
> [Docs] - Update S3 storage permissions

- openmetadata-ui/src/main/resources/ui/src/components/AddTestCaseList/AddTestCaseList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPanel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPanel.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummary.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/QualityTab/QualityTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/TestSuite.constant.ts
- openmetadata-ui/src/main/resources/ui/src/pages/KPIPage/EditKPIPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/KPIPage/EditKPIPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteDetailsPage/TestSuiteDetailsPage.component.tsx
> ui: worked on feedback part-1

- ingestion/src/metadata/cli/restore.py
- ingestion/src/metadata/cli/utils.py
- Fixes connection instantiation for Postgres and MySQL in backup/restore
- added tqdm to see backup progression
#
#
> fix: updated MySQL and Postres conn in backup/restore

- SECURITY.md
- ingestion/tests/cli_e2e/test_cli_mysql.py
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Mysql.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Postgres.md
Doc modifications - mysql, postgres & Mysql E2E fix
#
#
> Connection Doc modifications - mysql, postgres & Mysql E2E fix

- ingestion/tests/cli_e2e/test_cli_vertica.py
> Fix Vertica e2e test

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/ImportGlossary/ImportGlossary.tsx
- openmetadata-ui/src/main/resources/ui/src/components/GlossaryDetails/GlossaryDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/GlossaryDetailsRightPanel/GlossaryDetailsRightPanel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/GlossaryTerms/GlossaryTermsV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/GlossaryTerms/tabs/AssetsTabs.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/GlossaryTerms/tabs/GlossaryOverviewTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryCard.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- openmetadata-ui/src/main/resources/ui/src/styles/components/glossary.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
- openmetadata-ui/src/main/resources/ui/src/styles/x-master.css
updated glossary ui to sync with new ui
#
#
> ui: updated glossary layout to sync with new layout

- .run/Template JUnit.run.xml
- docker/development/docker-compose-postgres.yml
- docker/development/docker-compose.yml
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- openmetadata-service/pom.xml
- openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
- pom.xml
I worked on ... because ... updated elastic search version from 7.16.0 to 7.16.1
> updated elastic search version from 7.16.0 to 7.16.1

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v013__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v013__create_db_connection_info.sql
- openmetadata-service/src/main/resources/json/data/tests/tableCustomSQLQuery.json
Added missing migration for test definition parameter definition changes
#
#
> fix: test defintion migration for parameter definition changes

- .github/teams.yml
adding @Anuj359, @07Himank and @tutte to the safe to test list for CI + cleaning contributors
#
#
> Update teams list for labeler

- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/AzureSQL.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Clickhouse.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Databricks.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Db2.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Druid.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Hive.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Impala.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/MariaDB.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/MongoDB.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Mssql.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Mysql.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Oracle.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/PinotDB.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Postgres.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Presto.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Redshift.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/SQLite.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/SapHana.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/SingleStore.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Trino.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Vertica.md
Fix https://github.com/open-metadata/OpenMetadata/issues/12055
Fixed database hostport docs
#
#
> Fixed database hostport docs

- openmetadata-docs/content/v1.1.0-snapshot/deployment/airflow/index.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/kubernetes/index.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/kubernetes/values.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/amazon-cognito-sso/kubernetes.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/auth0/kubernetes.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/azure/kubernetes.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/enable-jwt-tokens.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/enable-password-masking.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/enable-ssl/ssl-troubleshooting.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/google/kubernetes.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/keycloak/kubernetes.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/okta/kubernetes.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/security/one-login/kubernetes.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/upgrade/index.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/upgrade/kubernetes.md
- openmetadata-docs/content/v1.1.0-snapshot/deployment/upgrade/versions/100-to-110.md
- openmetadata-docs/content/v1.1.0-snapshot/how-to-guides/feature-configurations/bots.md
Kubernetes Docs update for breaking changes and updates to 1.1.0 Release.
#
#
> fix(docs): kubernetes docs for breaking changes for 1.1.0

- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/models.py
Updated the tableau pydantic models to make `name` fields optional
ref: [slack_thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1687834410911719)
#
#
> Tableau name fields Optional

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedListV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProviderContext.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/login/LoginCarousel.tsx
Fixes:
- Increase delay on Login Carousel
- User profile infinite API calls
- User profile for others do not show proper data
#
#
> fix(ui): user profile page activity feed

- ingestion/Dockerfile.ci
- openmetadata-docs/content/v1.0.0/connectors/database/impala/cli.md
- openmetadata-docs/content/v1.0.0/connectors/database/mysql/airflow.md
- openmetadata-docs/content/v1.0.0/connectors/database/mysql/cli.md
- openmetadata-docs/content/v1.0.0/connectors/database/mysql/index.md
- openmetadata-docs/content/v1.0.0/connectors/database/postgres/cli.md
- openmetadata-docs/content/v1.0.0/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/impala/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/mysql/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/mysql/index.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/postgres/cli.md
- openmetadata-docs/content/v1.1.0-snapshot/connectors/database/postgres/index.md
> Fix Docs - add iam based rds doc

- ingestion/src/metadata/ingestion/source/dashboard/looker/parser.py
- ingestion/src/metadata/readers/base.py
- ingestion/src/metadata/readers/bitbucket.py
- ingestion/src/metadata/readers/github.py
- ingestion/src/metadata/readers/local.py
- ingestion/tests/unit/resources/lkml/cats.explore.lkml
- ingestion/tests/unit/topology/dashboard/test_looker_lkml_parser.py
- ingestion/tests/unit/topology/dashboard/test_lookml_bitbucket_reader.py
- ingestion/tests/unit/topology/dashboard/test_lookml_github_reader.py
> Looker - Fix file extension and blob import

- openmetadata-ui/src/main/resources/ui/src/constants/Login.constants.ts
updated name from Data Insight to Data Insights
#
#
> ui: updated nam from data insight to data insights

- ingestion/src/metadata/utils/entity_link.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/12245
#
#
> Fixed dbt table level test

- openmetadata-service/src/main/java/org/openmetadata/service/migration/MigrationUtil.java
> Fix migrations to handle entities with mal-formed FQN due to . in their name

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v014__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v014__create_db_connection_info.sql
- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DomainRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/EntityResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/domains/DomainResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/glossary/GlossaryTermResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/IndexUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/EnumBackwardCompatibilityTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/domains/DomainResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/api/domains/createDomain.json
- openmetadata-spec/src/main/resources/json/schema/entity/domains/domain.json
- openmetadata-spec/src/main/resources/json/schema/entity/teams/teamHierarchy.json
- openmetadata-spec/src/main/resources/json/schema/type/entityRelationship.json
> 12142.task1 - Add support for Domains

- ingestion/src/metadata/ingestion/source/dashboard/looker/columns.py
- ingestion/tests/unit/resources/lkml/recursive.explore.lkml
- ingestion/tests/unit/resources/lkml/views/recursive.view.lkml
- ingestion/tests/unit/resources/lkml/views/recursive_call.view.lkml
- ingestion/tests/unit/topology/dashboard/test_looker_lkml_parser.py
and add some tests for recursive calls
#
#
> Fix looker view parser

- ingestion/examples/sample_data/users/users.json
> Sample Data - Add users with dot in the name

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
The add_test_case_results API fails if the `timestamp` is passed as `None`. In case of dbt if the test gets aborted due to  
some error, the `timestamp` is passed as `None`
In this case we will default to the `run_results.json` file generation time since that will be when the test execution got completed.
#
#
> Fix None completed_at time for dbt test

- openmetadata-docs/content/partials/v1.1.0/deployment/upgrade/upgrade-prerequisites-110.md
> [Docs] - Upgrade docs: Add log and sort_buffer_size

- openmetadata-ui/src/main/resources/ui/src/utils/ConnectionSchemas/SupersetConnection.json
Fixes superset auth support
#
#
> support(ui): superset with basic and iam auth type

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/dashboard/DashboardServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/database/DatabaseServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/messaging/MessagingServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/metadata/MetadataServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/mlmodel/MlModelServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/pipeline/PipelineServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/storage/StorageServiceResource.java
> Fix #10181: Dot character in service names cause issues when running the ingestion

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
Fix :  #12124
I worked on ... because ... solved table API throws 404 when tags assigned to it got deleted
#
- [ x] Bug fix
> solved table api throw 404 error

- openmetadata-docs/content/partials/v1.1.0/deployment/upgrade/upgrade-prerequisites-110.md
> [Docs] - Add migration time warning

- ingestion/src/metadata/cli/db_dump.py
Added backup for server tables
#
#
> Added Server migration table to utility

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v013__create_db_connection_info.sql
> Fix DL migrations

- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseSchemaResource.java
> Fix db filter name in resource list

- ingestion/tests/cli_e2e/base/test_cli_dbt.py
- ingestion/tests/cli_e2e/dbt/redshift/redshift.yaml
- ingestion/tests/cli_e2e/test_cli_dbt_redshift.py
Added table level test and intermediate models in dbt e2e
#
#
> Added table level test and intermediate models in dbt E2E Test

- ingestion/tests/cli_e2e/test_cli_mysql.py
MySQL e2e filter count changed after 2 tables were added [here](https://github.com/open-metadata/OpenMetadata/blob/main/bootstrap/sql/com.mysql.cj.jdbc.Driver/v014__create_db_connection_info.sql)
Fixed the counts
#
#
> Fixed MySQL e2e count

- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/events/EventSubscriptionResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java
> 11587 Task 1 - Simplify field inheritance from parent to child entities

- common/pom.xml
- openmetadata-service/pom.xml
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/TeamResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/type/basic.json
- pom.xml
Upgrade dependencies for 1.2.0 release
#
#
> Upgrade dependencies for 1.2.0 release

- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/TestCaseIndex.java
> Fix TestCase indexing: exclude change descripiton from indexing

- ingestion/tests/integration/ometa/test_ometa_glossary.py
Required changes after https://github.com/open-metadata/OpenMetadata/commit/a313dc19f321070e1e4027f774848d9fbafea632
#
#
> Fix glossary reviewer pytests

- ingestion/src/metadata/ingestion/source/database/database_service.py
> Fix Filter Pattern

- openmetadata-ui/src/main/resources/ui/src/components/authentication/auth-provider/AuthProvider.tsx
I worked on changing the after-login API call method, to update the user details, from `PUT` to `PATCH`.
https://github.com/open-metadata/OpenMetadata/assets/51777795/f339fe5a-44c3-4684-a398-8fee727771c8
#
#
> fix(UI): login related bug

- openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
> fix(ui): cypress fix for login with email

- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/TestCaseIndex.java
> Fix TestCase index

- ingestion/src/metadata/ingestion/source/database/database_service.py
> Fixes #12270: Filter Pattern Delete issue

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Explore/explore.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
- I worked on revamping the database page ui to the latest one.
-  remove old components
#
#
> feat(ui): supported latest ui for the database page

- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- ingestion/setup.py
downgrade avro version for CI fix
#
#
> Update PIP in cypress and docker workflows

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/MigrationUtil.java
> Fix Test Issues

- .github/workflows/docker-openmetadata-server.yml
- openmetadata-docs/content/v1.1.0/developers/contribute/build-code-and-run-tests/prerequisites.md
- openmetadata-spec/src/main/resources/json/schema/configuration/authenticationConfiguration.json
- openmetadata-spec/src/main/resources/json/schema/settings/settings.json
- openmetadata-ui/src/main/resources/ui/json2ts.sh
- package.json
- yarn.lock
> Fix OpenMetadata  schema to TypeScript generation

- .github/workflows/py-cli-e2e-tests.yml
Fixed cli e2e yml for datalake region value
#
#
> Fixed cli e2e yml for datalake region value

- docker/docker-compose-quickstart/docker-compose.yml
Also updated the release compose to avoid any issues from people running the migration
#
#
> Update sort buffer in quickstart docker

- ingestion/src/metadata/cli/db_dump.py
- ingestion/src/metadata/ingestion/source/dashboard/domodashboard/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/airflow/lineage_parser.py
- ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/airflow/models.py
- ingestion/src/metadata/ingestion/source/pipeline/airflow/utils.py
- ingestion/tests/unit/topology/pipeline/test_airflow.py
- openmetadata-docs/content/v1.1.0/connectors/pipeline/airflow/mwaa.md
> Fix #12313 - Airflow lineage parsing and schedules

- .github/workflows/py-tests-skip.yml
- .github/workflows/py-tests.yml
We need to bring this in to test the 3.10 integration. CI cannot happen on the PR itself
#
#
> [Test] - Run CI for Python 3.10

- common/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
Fixes failure in CI due to version miss match
#
#
> Fix Pom versions

- openmetadata-docs/content/v1.1.0/connectors/database/clickhouse/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/databricks/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/datalake/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/db2/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/deltalake/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/domo-database/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/druid/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/dynamodb/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/glue/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/hive/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/impala/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/mariadb/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/mongodb/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/mssql/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/mysql/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/oracle/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/pinotdb/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/postgres/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/presto/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/redshift/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/salesforce/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/sap-hana/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/singlestore/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/snowflake/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/sqlite/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/trino/yaml.md
- openmetadata-docs/content/v1.1.0/connectors/database/vertica/yaml.md
> [Docs] - Add missing links

- docker/development/docker-compose-postgres.yml
sort buffer is not a correct command here and all CIs are failing for this
```
2023-07-13 05:06:51.384 GMT [44] FATAL:  unrecognized configuration parameter "sort_buffer_size"
```
#
#
> Fix postgres container init

- ingestion/setup.py
- ingestion/src/metadata/ingestion/lineage/parser.py
- openmetadata-airflow-apis/setup.py
Increase sqlfluff parsing timeout and prepare bump dev version 
#
#
> Increase sqlfluff parsing timeout and prepare bump dev version 

- ingestion/examples/sample_data/profiler/tableProfile.json
- ingestion/src/metadata/ingestion/source/database/sample_data.py
> add sample data for table profile

- openmetadata-ui/src/main/resources/ui/src/constants/regex.constants.test.ts
- openmetadata-ui/src/main/resources/ui/src/constants/regex.constants.ts
Fixes #12403 
I worked on issue #12403 
https://github.com/open-metadata/OpenMetadata/assets/59080942/4b937c1f-71b1-4ddd-9311-31f19a6eef3a
#
#
> fix(#12403): áéíóú ÁÉÍÓÚ characters not allowed in glossary, glossary term, classification and tag names

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
> Fix explore cache name

- openmetadata-service/src/main/java/org/openmetadata/csv/EntityCsv.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/ValidatorUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/util/ValidatorUtilTest.java
- openmetadata-spec/src/main/resources/json/schema/api/domains/createDataProduct.json
- openmetadata-spec/src/main/resources/json/schema/api/domains/createDomain.json
- openmetadata-spec/src/main/resources/json/schema/entity/domains/dataProduct.json
- openmetadata-spec/src/main/resources/json/schema/entity/domains/domain.json
- openmetadata-spec/src/main/resources/json/schema/entity/teams/team.json
- openmetadata-spec/src/main/resources/json/schema/entity/teams/user.json
> Fixes #12447 Use JSON schema constraint validation in CSV imports

- openmetadata-spec/src/main/resources/json/schema/type/entityRelationship.json
Fix on Expert Enum missing in Java Enum
#
#
> Add missing Expert Enum name

- docker/validate_compose.py
- ingestion/tests/unit/profiler/pandas/test_profiler.py
> Fix Docker Import

- openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.interface.ts
Fixes unit tests type error
#
#
> fix: type errors for unit tests

- docker/run_local_docker.sh
> install 3rd party for running validate compose docker

- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceProfilerPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storage/containerMetadataConfig.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/testSuitePipeline.json
I worked on fixing json schema $ref and $id path
#
#
> fix: json schema ref and id path

- ingestion/setup.py
pymssql build is failing due to the below issue listed in their repo
https://github.com/pymssql/pymssql/issues/826
The PR disables this dependancy until the above issue is fixed
Opened a issue to track the same https://github.com/open-metadata/OpenMetadata/issues/12480
#
#
> Disabled pymssql dependancy

- ingestion/pipelines/lineage.yaml
- ingestion/setup.py
- ingestion/src/metadata/cli/lineage.py
- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
> Increase lineage parsing timeout

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
Fixes issue in listing tableProfile for deleted tables
#
#
> List Deleted table Profile

- ingestion/src/metadata/ingestion/source/database/databricks/models.py
- ingestion/src/metadata/ingestion/source/database/databricks/unity_catalog/metadata.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/12300
#
#
> Databricks: Support column comments in case of complex columns

- ingestion/setup.py
Rather than disabling it, let's add an exclusion and avoid it
> Fix Dependency issue - mssql

- openmetadata-docs/content/v1.1.0/developers/apis/api-organization.md
- openmetadata-docs/content/v1.1.0/developers/apis/implementation-notes.md
- openmetadata-docs/content/v1.1.0/developers/apis/index.md
> Add API docs for v1.1.0

- openmetadata-ui/src/main/resources/ui/cypress.config.ts
- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/Following.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/RecentlyViewed.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/RightSidebar.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx
> test(ui): e2e tests for recently viewed and following

- openmetadata-docs/content/v1.1.0/menu.md
> Added missing menu items for v1.1.0 documentation

- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
**Fixes broken tour page**
Uploading Screen Recording 2023-07-19 at 9.31.52 PM.mov…
#
#
> fix(ui): tour with permission errors on multiple steps

- ingestion/src/metadata/ingestion/source/database/vertica/metadata.py
Fix #12301: Fix Vertica col comments for projections with the same name
#
#
> Fix #12301: Fix Vertica col comments for projections with the same name

- ingestion/src/metadata/ingestion/source/database/clickhouse/metadata.py
- ingestion/src/metadata/ingestion/source/database/column_type_parser.py
- ingestion/src/metadata/ingestion/source/database/sql_column_handler.py
- ingestion/src/metadata/profiler/metrics/hybrid/histogram.py
- ingestion/src/metadata/profiler/metrics/static/count_in_set.py
- ingestion/src/metadata/profiler/metrics/static/ilike_count.py
- ingestion/src/metadata/profiler/metrics/static/like_count.py
- ingestion/src/metadata/profiler/metrics/static/max.py
- ingestion/src/metadata/profiler/metrics/static/mean.py
- ingestion/src/metadata/profiler/metrics/static/min.py
- ingestion/src/metadata/profiler/metrics/static/not_like_count.py
- ingestion/src/metadata/profiler/metrics/static/not_regexp_match_count.py
- ingestion/src/metadata/profiler/metrics/static/null_count.py
- ingestion/src/metadata/profiler/metrics/static/regexp_match_count.py
- ingestion/src/metadata/profiler/metrics/static/stddev.py
- ingestion/src/metadata/profiler/metrics/static/sum.py
- ingestion/src/metadata/profiler/metrics/window/first_quartile.py
- ingestion/src/metadata/profiler/metrics/window/median.py
- ingestion/src/metadata/profiler/metrics/window/third_quartile.py
- ingestion/src/metadata/profiler/orm/converter/common.py
- ingestion/src/metadata/profiler/orm/functions/length.py
- ingestion/src/metadata/profiler/orm/functions/median.py
- ingestion/src/metadata/profiler/orm/registry.py
- ingestion/src/metadata/profiler/orm/types/custom_ip.py
- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
Fixes Clickhouse profiler issue
IPV4 IPV6 data type issue
Cast Null to Nulltype bigint issue
Add nullable datatype as null
adding `self.col.type` to columnclause helps fetch type for a overriding metric fn
#
#
> Fix: Clickhouse profiler fix - Cast null nulltype issue

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/MigrationUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/versions/mysql/v110/MySQLMigration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/versions/postgres/v110/PostgresMigration.java
Optimize DB Calls for Migration
#
#
> Optimize db calls for entity_extension and field_relationship table

- openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/authentication/auth-provider/AuthProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/authentication/auth-provider/okta-auth-provider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/authentication/authenticators/OktaAuthenticator.tsx
- openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.tsx
> fix(ui): disable auto renew for react-okta

- openmetadata-service/src/test/resources/openmetadata-secure-test.yaml
> Remove file appender from logging for tests

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedEditor/KeyHelp.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.interface.ts
I worked on making changes to stay on the same page when the task is resolved.
https://github.com/open-metadata/OpenMetadata/assets/59080942/29908172-2ae9-4bb2-bff1-6fac566c2be0
#
#
> chore(ui): stay on the same page when the task is resolved

- ingestion/src/metadata/ingestion/source/database/sql_column_handler.py
- ingestion/src/metadata/profiler/orm/functions/sum.py
> Fix Cast and Col checks - Clickhouse

- ingestion/src/metadata/ingestion/source/database/mssql/queries.py
- ingestion/src/metadata/ingestion/source/database/mssql/utils.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/12515
#
#
> Fixed mssql comments

- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceMainTabContent.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/TasksPage.interface.ts
- openmetadata-ui/src/main/resources/ui/src/utils/Database/DatabaseDetails.utils.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.ts
- I worked on fixing the tags not coming while update tags task in Database page.
- remove the request tags task from right panel Tags in Service detail paeg.
Issue : 
Fixed : 
#
#
> fix(ui): the tags not showing in database update tags

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/SummaryPannel/SummaryPanel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCases/TestCases.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCases/TestCases.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PermissionProvider/PermissionProvider.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/PermissionProvider/PermissionProvider.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PermissionProvider/PermissionProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataQuality/DataQualityPage.tsx
> fix(ui): loader on data quality page

- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
Fixes Date issues in tableProfile
#
#
> fix date issues in table profile

- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
Fixes #12552 
- worked on adding immediate parent in Breadcrumb in explore page card 
#
#
> fixed: Show parent container in breadcrumbs of container search results #12552

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/PaginatedEntitiesSource.java
PR for Issues in Reindexing
#
#
> Update Pagination with offset and limit for Reindexing

- openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/LineageNodeLabelV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/custom-node.less
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
Add breadcrumbs to lineage node
#
#
> fix: add lineage breadcrumbs

- openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/TierCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/tier-card.style.less
> fix(client): applying shadow none globally

- ingestion/src/metadata/ingestion/source/database/column_type_parser.py
- ingestion/src/metadata/ingestion/source/sqa_types.py
- ingestion/src/metadata/profiler/orm/converter/common.py
- ingestion/src/metadata/profiler/orm/registry.py
- ingestion/src/metadata/profiler/orm/types/custom_datetimerange.py
- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
> Add DateTimeRange support in postgres

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/SchemaTable/SchemaTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/formUtils.tsx
I worked on the following things
- Table nested structure should not get collapse when the value is updated.
- Form field error should have the same casing
https://github.com/open-metadata/OpenMetadata/assets/59080942/d1b7d2cc-a962-47dc-a095-2cf4bbe97ee2
#
https://github.com/open-metadata/OpenMetadata/assets/59080942/e2dae445-43fe-43f5-ab2d-00de0669c235
#
> chore: ui nested structure and form error casing feedback

- ingestion/src/metadata/ingestion/source/pipeline/dagster/metadata.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/12328
#
#
> Added exception handling message for dasgter pipelines

- ingestion/src/metadata/ingestion/source/dashboard/tableau/client.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/connection.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
- ingestion/src/metadata/utils/helpers.py
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/tableau.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/bigQueryConnection.json
Fixes https://github.com/open-metadata/OpenMetadata/issues/12527
#
#
> Fixed Tableau-Bigquery lineage issue

- openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreV1.style.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
Moved Explore Tabs to be left.
https://github.com/open-metadata/OpenMetadata/assets/33024356/5381322e-63d4-422d-82cb-cde6c595600d
#
#
> feat: explore page tabs revamp

- ingestion/src/metadata/cli/db_dump.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/12582
#
#
> Backup CLI case sensitivity fix for postgres sql

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DomainRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/KpiRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PolicyRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/QueryRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/RoleRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TagRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/bots/BotResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/policies/PolicyResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/SubjectCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/TeamResourceTest.java
> Simplify getting from and to entity relationships

- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
- .github/workflows/java-checkstyle.yml
- .github/workflows/maven-build.yml
- .github/workflows/publish-maven-package.yml
updating the docker image removals to fix the failing ci checks in PRs
the error in all the CI states
`Unable to find image '5bedb4:7dfe2406004d4201b411ff131b94ecc9' locally`
> Removing the docker cleaning from the steps

- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/PrimaryKeyConstraint.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/TableConstraints.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/table-constraints.less
- change table constraints ui for primary key
#
#
> fix(ui):change table constraints ui for primary key

- .github/workflows/airflow-apis-tests-3_9.yml
- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
- .github/workflows/java-checkstyle.yml
- .github/workflows/maven-build.yml
Updating the docker-images cleaning flag to  false
> Adding false flag to image cleaning

- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseServiceUtils.ts
Fixes #12645 
I worked on issue #12645 
#
#
> fix(#12645): pinotDB test connection form

- pom.xml
Wix embedded MySQL is no longer used in the project. It also has vulnerability reported. Removing the dependency from the project.
#
#
> Remove unnecessary wix dependency with vulnerability

- ingestion/src/metadata/ingestion/source/database/postgres/queries.py
Partially fixes postgres 11.9 issue
#12388 
#
#
> fix column doesn't exists for postgres 11.x

- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
Fixes overriding of regular tables by transient tables
#
#
> Add fix for snowflake transient tables

- openmetadata-ui/src/main/resources/ui/cypress/common/TaskUtils.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/ActivityFeed.spec.js
fixed activity feed cypress
#
#
> cypress: fixed activity feed cypress failure

- ingestion/setup.py
- ingestion/src/metadata/ingestion/source/database/athena/metadata.py
- ingestion/src/metadata/ingestion/source/database/athena/query_parser.py
Fixed athena import and lineage/usage validation
Fixes https://github.com/open-metadata/OpenMetadata/issues/12402
#
#
> Fixed athena import and lineage/usage validation

- ingestion/setup.py
> Python Dependency Conflict fixes

- openmetadata-service/src/main/java/org/openmetadata/service/migration/MigrationUtil.java
Remove the batch call and used per request commit
#
#
> no batch in migration updates

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v014__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v014__create_db_connection_info.sql
- ingestion/src/metadata/ingestion/source/database/clickhouse/connection.py
- openmetadata-docs/content/v1.1.1-SNAPSHOT/connectors/database/clickhouse/index.md
- openmetadata-docs/content/v1.1.1-SNAPSHOT/connectors/database/clickhouse/yaml.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/clickhouseConnection.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Clickhouse.md
Clickhouse: Make https protocol as permanent field
#
#
> Clickhouse: Make https protocol as permanent field

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticSearch/ElasticSearchClientImpl.java
- openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
I worked on ... because ...Fix service type aggregation bug
#
- [ x] Bug fix
> Fix service type aggregation bug

- openmetadata-service/src/main/java/org/openmetadata/service/elasticsearch/ElasticSearchEventPublisher.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ClassificationRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardDataModelRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DomainRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MetricsRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ReportDataRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TagRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TypeRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/ReIndexingHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/jdbi/BindFQN.java
- openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/PaginatedDataInsightSource.java
- openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/SearchIndexWorkflow.java
> Add BindFQN jdbi annotation to change fqn to fqnHash

- common/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
> Fix exceptions thrown as reflections scan non java classes

- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/ExtensionTable.tsx
Fixes #12682 
I worked on issue #12682 
#
#
> fix(#12682): fail to display custom properties of the table

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v014__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v014__create_db_connection_info.sql
> Clean old test connections bootstrap

- openmetadata-docs/content/v1.1.0/connectors/pipeline/airbyte/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/dagster/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/databricks-pipeline/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/domo-pipeline/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/fivetran/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/glue-pipeline/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/nifi/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/spline/index.md
Add Pipeline Info
fix #12498 
#
#
> fix 12498: pipeline metadata info

- openmetadata-docs/content/v1.1.0/connectors/pipeline/airbyte/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/dagster/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/databricks-pipeline/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/domo-pipeline/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/fivetran/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/glue-pipeline/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/nifi/index.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/spline/index.md
> quick fix row value docs

- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionListTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionListTable.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/PipelineActions.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/PipelineActions.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/ingestion.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
I worked on 
**Before:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/62e5f4f4-2d34-415a-a18d-ebef8345d5d8
**After:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/d54d59d6-ea69-4fb5-add0-5d84b8206d90
#
#
> fix(ui): ingestion tab bugs on service details page

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/AddGlossaryTermForm/AddGlossaryTermForm.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx
I worked on the glossary terms reviewers issue.
#
#
> fix: glossary term reviewers is not updating

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v014__create_db_connection_info.sql
- bootstrap/sql/com.mysql.cj.jdbc.Driver/v015__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v014__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v015__create_db_connection_info.sql
in 1.1.1 we still need the `deleted` field, at least for event subscriptions. Aligning now the migration files for 1.1.1 and 1.2.0 and we can continue the discussion about these queries being needed at all
#
#
> Add v015 for 1.2.0 release

- .github/workflows/maven-build.yml
- .github/workflows/maven-postgres-tests-build.yml
> Mvn workflows

- ingestion/src/metadata/data_quality/interface/pandas/pandas_test_suite_interface.py
- ingestion/src/metadata/ingestion/source/database/datalake/metadata.py
- ingestion/src/metadata/utils/datalake/common.py
- ingestion/src/metadata/utils/datalake/csv_tsv_dispatch.py
- ingestion/src/metadata/utils/datalake/datalake_utils.py
> Fixes #12555 - Fix DL test suite

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/versions/utils/v110/MigrationUtil.java
> Fix Failing TestSuite Migration

- .github/workflows/cypress-integration-tests-mysql.yml
- .github/workflows/cypress-integration-tests-postgresql.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-postgres-tests-build-skip.yml
- .github/workflows/maven-postgres-tests-build.yml
fix: CI for Maven Builds and Cypress Tests for fail-fast as false for matrix strategy.
#
#
> fix: CI Maven Builds; Cypress Tests

- openmetadata-docs/content/v1.1.1-SNAPSHOT/releases/index.md
- openmetadata-docs/content/v1.1.1-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.1.1-SNAPSHOT/releases/releases/latest.md
- openmetadata-docs/content/v1.1.1-SNAPSHOT/releases/releases/supported.md
- openmetadata-docs/content/v1.1.1-SNAPSHOT/releases/roadmap/index.md
> [Docs] - Update release information for 1.1.1

- ingestion/src/metadata/parsers/avro_parser.py
Avro record dtype fix for datalake
Added a common value of the record datatype for both `FieldModel` and `Column` classes
#
#
> Avro record dtype fix for datalake

- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
redirection issue of frequently joining column
https://github.com/open-metadata/OpenMetadata/assets/71748675/a924e549-f85c-484b-91cf-505aadbbeff1
#
#
> fix(ui): redirection issue of frequently join column

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeader/EntityHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TestSuite/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TestCaseDetailsPage/TestCaseDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/LogsViewer.utils.ts
- fix DQ pipeline  ingestion files redirect issue
- fix glossary asset header links encoded issue
- fix logs breadcumb encoded issue
Issue :
https://github.com/open-metadata/OpenMetadata/assets/66266464/a501d193-5d16-4588-9c99-6e1792d73d19
https://github.com/open-metadata/OpenMetadata/assets/66266464/d5756b01-4283-4f80-9095-3aca53382bdc
https://github.com/open-metadata/OpenMetadata/assets/66266464/0fa9ad37-c34a-4baf-8ee7-757802812a7c
#
#
> fix(ui): the redirect issue in DQ pipeline because of encoding

- ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
- ingestion/src/metadata/ingestion/source/dashboard/superset/client.py
Improve exception handling for superset
#
#
> Improve exception handling for superset

- openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogGenericExceptionMapper.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/SubscriptionUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
> Fixes 12741 Getting entity by name does not return inherited properties

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
Fixes Pagination Issue in TestSuite Postgres
#
#
> test suite listing fixes

- docker/postgresql/Dockerfile_postgres
Update PostgreSQL Base Branch to `14` for `1.1.1` release
#
#
> Update PostgreSQL Base Branch to `14` for `1.1.1` release

- .github/workflows/docker-openmetadata-db.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- .github/workflows/docker-openmetadata-postgres.yml
- .github/workflows/docker-openmetadata-server.yml
- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
Prepare 1.1.1 Release. Version Bump all to 1.1.1
#
#
> feat(version-bump): Prepare 1.1.1-release

- ingestion/src/metadata/cli/restore.py
> Log the query in restore if there are any exceptions

- openmetadata-docs/content/v1.1.1-SNAPSHOT/connectors/database/oracle/index.md
- openmetadata-docs/content/v1.1.1-SNAPSHOT/connectors/database/oracle/yaml.md
- openmetadata-docs/content/v1.1.1-SNAPSHOT/deployment/ingestion/openmetadata.md
> [Docs] - Oracle permissions explanation

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/mysql.spec.js
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.tsx
https://github.com/open-metadata/OpenMetadata/assets/71748675/8c756a75-4e01-4a66-b14b-f4705e912c39
#
#
> ui: fixed table encoding issue while splitting FQN

- openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/ActivityFeed.spec.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AddAndRemoveTierAndOwner.spec.js
- activityFeed
- addAndRemoveTierAndOwner
#
#
> cypress: worked on flaky ui cypress

- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
Fixing server image version in compose files.
#
#
> [FIX] Fixing docker compose OM server version

- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Mssql.md
> Docs: fix mssql pyodbc connection args

- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dashboardServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dataInsightPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceProfilerPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceQueryLineagePipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceQueryUsagePipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtAzureConfig.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtGCSConfig.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtS3Config.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/messagingServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/metadataToElasticSearchPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/mlmodelServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/pipelineServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storage/containerMetadataConfig.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storageServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/testSuitePipeline.json
> chore: add type in json schema

- ingestion/src/metadata/ingestion/sink/metadata_rest.py
- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/database_service.py
- ingestion/src/metadata/ingestion/source/database/databricks/unity_catalog/metadata.py
> Fix #12783: Metadata Ingestion is dropping constraints just to add them again afterwards

- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- ingestion/src/metadata/ingestion/sink/metadata_rest.py
- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/database_service.py
- ingestion/src/metadata/ingestion/source/database/databricks/unity_catalog/metadata.py
Table Constraint & Bump Ingestion Version
#
#
> Table Constraint & Bump Ingestion Version

- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/AddIngestion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/Steps/DataInsightMetadataToESConfigForm/DataInsightMetadataToESConfigForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/Steps/MetadataToESConfigForm/MetadataToESConfigForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/addIngestion.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTConfigForm.interface.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DBTConfigFormUtil.ts
- openmetadata-ui/src/main/resources/ui/src/utils/LogsViewer.utils.ts
I worked on fixing the type reference issue that occurred after https://github.com/open-metadata/OpenMetadata/pull/12780
#
#
> fix(ui): types reference issue

- .github/workflows/maven-build.yml
- .github/workflows/maven-postgres-tests-build.yml
> Fix maven workflows to build the project before running tests

- bootstrap/sql/com.mysql.cj.jdbc.Driver/v014__create_db_connection_info.sql
- bootstrap/sql/org.postgresql.Driver/v014__create_db_connection_info.sql
> Fix impala migration query

- openmetadata-docs/content/v1.1.1/features/index.md
> Updated Gifs

- ingestion/src/metadata/ingestion/source/database/mongodb/connection.py
- ingestion/src/metadata/ingestion/source/database/snowflake/connection.py
- ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
> Fix #12798 - Update Snowflake GetTables test query

- openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AddAndRemoveTierAndOwner.spec.js
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
replace encodeURI with encodeURIComponent to support forward slash encoding
#
#
> ui: replace encodeURI with encodeURIComponent in entity details page

- openmetadata-ui/src/main/resources/ui/src/components/AddGlossary/AddGlossary.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AddGlossaryTermForm/AddGlossaryTermForm.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.style.less
- openmetadata-ui/src/main/resources/ui/src/styles/components/glossary.less
Fixes #12029 
Fixes #11521 
#
#
> fix: show owner in glossary term table

- openmetadata-docs/content/v1.1.1/deployment/docker/index.md
Removed Duplicate section from Docker Deployment Docs.
#
#
> fix(docs) - Duplicate section

- openmetadata-service/src/main/java/org/openmetadata/service/events/ChangeEventHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticSearch/ElasticSearchClientImpl.java
> Fix Cypress Test failures for search

- ingestion/setup.py
> Fix Qliksense import

- ingestion/src/metadata/ingestion/source/database/mssql/utils.py
Fix: pyodbc type not supported for -150
#
#
> Fix: pyodbc type not supported for -150

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/DataConsumerRole.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/ActivityFeedCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AppBar/Appbar.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- openmetadata-ui/src/main/resources/ui/src/styles/spacing.less
- Data consumer role cypress issue fix
- Announcement card styling
- Profile dropdown styling fix
#
#
> fix data consumer role cypress and some ui issues

- ingestion/src/metadata/profiler/metrics/static/max.py
- ingestion/src/metadata/profiler/metrics/static/min.py
- ingestion/tests/cli_e2e/test_cli_mysql.py
- ingestion/tests/cli_e2e/test_cli_postgres.py
> Fix #12479: MariaDB Mysql Time Col profiler issues + fix e2e tests

- ingestion/src/metadata/ingestion/source/mlmodel/sagemaker/metadata.py
> Fixes 12820: SageMaker Metadata Ingestion Success

- openmetadata-service/src/main/resources/logback.xml
Provide a way for controlling bootstrap_storage.sh logs
#
#
> Added LogBack File for bootstrap_storage.sh

- openmetadata-ui/src/main/resources/ui/src/AppState.ts
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/FeedCardHeader/FeedCardHeaderName.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/FeedCardHeader/FeedCardHeaderV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionListTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/UserDataUtils.ts
Fixes #12389
- I worked on supporting display names in the activity feed
- fix the ui issue in ingestion page
https://github.com/open-metadata/OpenMetadata/assets/66266464/4962aeaa-9604-4a01-8c6b-7da6745fbf3e
#
#
> fix: supported display name in activity feed

- openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/PoliciesDetailPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/RuleForm/RuleForm.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesDetailPage/RolesDetailPage.tsx
- Added header for policy and role
- fixed selection issue for Resources and Operations in add policy form
https://github.com/open-metadata/OpenMetadata/assets/71748675/f5b953c0-7b88-42d8-a2dc-b3926173df15
#
#
> ui: added title for policy and role page & fix multi selection issue in create policy

- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/ingestion/source/database/bigquery/queries.py
> Add External Table type support bq

- openmetadata-docs/content/v1.1.1/deployment/ingestion/openmetadata.md
- openmetadata-docs/content/v1.2.0-SNAPSHOT/deployment/ingestion/openmetadata.md
> Fix #11228 - Document Airflow Permissions

- ingestion/examples/workflows/elasticsearch.yaml
- ingestion/src/metadata/ingestion/models/search_index_data.py
- ingestion/src/metadata/ingestion/ometa/mixins/search_index_mixin.py
- ingestion/src/metadata/ingestion/ometa/ometa_api.py
- ingestion/src/metadata/ingestion/sink/metadata_rest.py
- ingestion/src/metadata/ingestion/source/search/elasticsearch/connection.py
- ingestion/src/metadata/ingestion/source/search/elasticsearch/metadata.py
- ingestion/src/metadata/ingestion/source/search/elasticsearch/parser.py
- ingestion/src/metadata/ingestion/source/search/search_service.py
- ingestion/src/metadata/utils/filters.py
- ingestion/src/metadata/utils/fqn.py
- ingestion/tests/unit/topology/search/test_elasticsearch.py
- openmetadata-service/src/main/resources/json/data/testConnections/search/elasticsearch.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/searchIndex.json
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/search/elasticSearchConnection.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/searchServiceMetadataPipeline.json
Fix #12302: Add ElasticSearch Ingestion Source
#
#
> Fix #12302: Add ElasticSearch Ingestion Source 

- .github/workflows/py-cli-e2e-tests.yml
Fixes E2E vars for postgres e2e cli
#
#
> Fix E2E vars

- openmetadata-docs/content/v1.1.1/connectors/ingestion/workflows/data-quality/index.md
Fixes #10529
updated docs for test definition to test type
#
#
> docs: updated heading from test definition to test type

- openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v112/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v112/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/MigrationFile.java
Fix Test Suite Migrations 
#
#
> Fix Test Suite Migrations

- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/MlFlow.spec.js
> fix: mlflow cypress by adding model filter pattern

- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/utils/bigquery_utils.py
- ingestion/src/metadata/utils/credentials.py
> Fix Impersonation issue

- ingestion/src/metadata/ingestion/source/database/oracle/utils.py
> Fix Oracle case issue

- openmetadata-docs/content/v0.13.4/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs/content/v0.13.4/connectors/pipeline/airflow/lineage-operator.md
- openmetadata-docs/content/v1.0.0/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs/content/v1.0.0/connectors/pipeline/airflow/lineage-operator.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs/content/v1.1.0/connectors/pipeline/airflow/lineage-operator.md
- openmetadata-docs/content/v1.1.0/deployment/index.md
- openmetadata-docs/content/v1.1.1/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs/content/v1.1.1/connectors/pipeline/airflow/lineage-operator.md
- openmetadata-docs/content/v1.2.0-SNAPSHOT/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs/content/v1.2.0-SNAPSHOT/connectors/pipeline/airflow/lineage-operator.md
> Update deployment document

- openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/RouterUtils.ts
Fixes #10396
- I worked on refactoring the tags page api calls and ui loading issue 
Issue having :
- After changing the tag name to have dot in it, it shows as ` tagsCount 0 `
https://github.com/open-metadata/OpenMetadata/assets/66266464/262e7b21-eb3b-4791-8a1e-fcec7d9fec71
https://github.com/open-metadata/OpenMetadata/assets/66266464/ec247286-ec41-4820-b403-9710e0d9c694
https://github.com/open-metadata/OpenMetadata/assets/66266464/16d30ff8-8ead-4571-a766-78e559d5b2f6
https://github.com/open-metadata/OpenMetadata/assets/66266464/9c07eafb-e915-4e5e-9f6d-22d9290a7297
#
#
> fix(ui): tags page api optimization after certain action

- ingestion/src/metadata/ingestion/source/database/oracle/lineage.py
> Oracle add filter for lineage query

- openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/RequestDescriptionPage/RequestDescriptionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/RequestTagPage/RequestTagPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/UpdateDescriptionPage/UpdateDescriptionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/UpdateTagPage/UpdateTagPage.tsx
- I worked on fixing encoding issue in entity pages
#
#
> fix(ui): encoding issue in entity pages

- .github/workflows/maven-build.yml
> Fix Maven CI workflow dispatch

- ingestion/src/metadata/profiler/api/workflow.py
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceProfilerPipeline.json
> Add include views to profiler

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> doc(ui): whats new for 1.1.2

- openmetadata-ui/pom.xml
> Attach openmetadata-ui sources in packaging

- .github/workflows/docker-openmetadata-db.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- .github/workflows/docker-openmetadata-postgres.yml
- .github/workflows/docker-openmetadata-server.yml
- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- docker/postgresql/Dockerfile_postgres
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
Prepare 1.1.2 Release. 
Version Bump to 1.1.2
#
#
> [Feat] Version-bump: Prepare 1.1.2-release

- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/AddIngestion.component.tsx
https://github.com/open-metadata/OpenMetadata/assets/71748675/9e2032a3-7d43-4075-9024-cdd5e9f64e53
ui: updated schedule interval to send undefine when none is selected 
#
#
> ui: updated schedule interval to send undefine when none is selected

- bootstrap/sql/migrations/native/1.2.0/postgres/schemaChanges.sql
> Fix airflow config retries postgres migration

- .github/workflows/openmetadata-airflow-apis.yml
> Remove .egg for airflow APIs publish

- openmetadata-service/pom.xml
> [Docs] - Update path for generating API description

- openmetadata-docs/content/v1.1.2/deployment/upgrade/versions/100-to-110.md
- openmetadata-docs/content/v1.2.0-SNAPSHOT/deployment/upgrade/versions/100-to-110.md
Add documentation for Data Quality Breaking Change
#
#
> Add breaking changes for pipeline in v110

- openmetadata-docs/content/v1.1.2/deployment/kubernetes/faqs.md
> fix(docs): Add FAQs for kubernetes

- docker/development/docker-compose-postgres.yml
- docker/development/docker-compose.yml
Enable force migrations for CI
#
#
> fix(CI): Enable force migrations for CI

- .github/workflows/docker-openmetadata-db.yml
- .github/workflows/docker-openmetadata-ingestion-base.yml
- .github/workflows/docker-openmetadata-ingestion.yml
- .github/workflows/docker-openmetadata-postgres.yml
- .github/workflows/docker-openmetadata-server.yml
- .github/workflows/openmetadata-airflow-apis.yml
- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/setup.py
- openmetadata-airflow-apis/setup.py
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
> fix(release): Version bump to 1.1.3

- openmetadata-ui/src/main/resources/ui/cypress/common/common.js
- openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/mysql.spec.js
- openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/AddIngestion.component.tsx
Fixes Fixes Ingestion failed to deploy on 1.1.3
#
#
> fix(ui): ingestion deploy failed on 1.1.3

- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v110/MigrationUtil.java
> Fix test suite migrations for 1.1.x

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/CollectionRegistry.java
Adds JDBI to be added to extension resource to create DAO
#
#
> Changes For Knowledge Center Dev

- openmetadata-docs/content/v1.0.0/menu.md
- openmetadata-docs/content/v1.1.0/menu.md
- openmetadata-docs/content/v1.1.1/menu.md
- openmetadata-docs/content/v1.1.2/menu.md
> Minor changes to test a PR for Docs

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MigrationDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v112/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v114/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v114/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/V112/MigrationUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/V114/MigrationUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v110/MigrationUtil.java
> Fix test suite migrations to 1.1.4

- ingestion/tests/cli_e2e/common/test_cli_dashboard.py
- ingestion/tests/cli_e2e/dashboard/metabase/metabase.yaml
- ingestion/tests/cli_e2e/dashboard/metabase/redshift.yaml
- ingestion/tests/cli_e2e/dashboard/powerbi/powerbi.yaml
- ingestion/tests/cli_e2e/dashboard/powerbi/redshift.yaml
- ingestion/tests/cli_e2e/dashboard/tableau/redshift.yaml
- ingestion/tests/cli_e2e/dashboard/tableau/tableau.yaml
- ingestion/tests/cli_e2e/test_cli_metabase.py
- ingestion/tests/cli_e2e/test_cli_powerbi.py
- ingestion/tests/cli_e2e/test_cli_quicksight.py
- ingestion/tests/cli_e2e/test_cli_redash.py
- ingestion/tests/cli_e2e/test_cli_tableau.py
> Fix e2e for tableau, metabase and powerbi

- ingestion/src/metadata/ingestion/source/dashboard/tableau/models.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/queries.py
`fullyQualifiedName` field is not present in older version of tableau (e.g Tableau 3.10).
We can remove this field and rely on the `name` field to get the name of the data model.
#
#
> Remove FQN field from tableau graphql query

- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
- ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/airbyte/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/fivetran/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/spline/metadata.py
- ingestion/src/metadata/utils/db_utils.py
- ingestion/tests/unit/topology/dashboard/test_looker.py
- ingestion/tests/unit/topology/dashboard/test_metabase.py
- openmetadata-spec/src/main/resources/json/schema/type/entityLineage.json
> Fix #9207: Add source in lineage details

- openmetadata-service/src/test/java/org/openmetadata/service/resources/analytics/ReportDataResourceTest.java
> fix: flaky report data tests

- ingestion/tests/cli_e2e/test_cli_quicksight.py
- ingestion/tests/cli_e2e/test_cli_redash.py
Numbers changed due to workflow changes, status changed for source and sink
addition of DashboardService into status
#
#
> Fix E2E - dashboards

- ingestion/src/metadata/ingestion/ometa/mixins/query_mixin.py
- ingestion/tests/cli_e2e/test_cli_quicksight.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/QueryRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/query/QueryResource.java
Fix #13001: Fix query not populating to all tables
#
#
> Fix #13001: Fix query not populating to all tables

- ingestion/tests/cli_e2e/test_cli_quicksight.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
Fixes #13080 
- added logic to update the summary to all test suites on test case deletion
#
#
Bug fix
> Issue 13080 - Added logic to update Summary on test case deletion

- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
- ingestion/src/metadata/pii/models.py
- ingestion/src/metadata/pii/processor.py
- ingestion/src/metadata/pii/scanners/column_name_scanner.py
- ingestion/src/metadata/pii/scanners/ner_scanner.py
- ingestion/src/metadata/utils/fqn.py
- ingestion/tests/integration/orm_profiler/test_pii_processor.py
- ingestion/tests/unit/pii/test_column_name_scanner.py
- ingestion/tests/unit/pii/test_ner_scanner.py
To handle a bit easier the processing at Collate
#
#
> Update structure for PII processing

- openmetadata-service/src/main/java/org/openmetadata/service/events/ChangeEventHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardDataModelRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SearchIndexRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/FeedUtils.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/FeedResourceTest.java
Cleans up the way tasks are resolved and closed by introducing task workflows
#
#
> Cleanup task resolution and closing with task workflows

- openmetadata-docs/content/v1.1.2/connectors/dashboard/superset/index.md
> Add Superset Upcoming Datamodel support

- ingestion/src/metadata/ingestion/processor/query_parser.py
> Fix usage count issue

- openmetadata-ui/src/main/resources/ui/src/components/authentication/auth-provider/AuthProvider.tsx
Fixes #12736 
I worked on issue #12736 
https://github.com/open-metadata/OpenMetadata/assets/59080942/fd41e421-7264-4629-9ddc-40e989c114f9
#
#
> fix(#12736): OIDC Pulling Keyset multiple times per minute.

- openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
Update test case summary API from put to patch
https://github.com/open-metadata/OpenMetadata/assets/71748675/e9706086-ad28-4c92-ae2c-24e8ec929046
#
#
> ui: updated testCaseResult api from put to patch

- ingestion/src/metadata/profiler/api/models.py
- ingestion/src/metadata/profiler/source/metadata.py
- ingestion/tests/cli_e2e/base/test_cli.py
> Fix e2e profiler status

- ingestion/src/metadata/ingestion/ometa/mixins/query_mixin.py
- ingestion/src/metadata/ingestion/stage/table_usage.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/QueryRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/query/QueryResource.java
- openmetadata-spec/src/main/resources/json/schema/api/data/createQuery.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/query.json
- openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/TableQueries/TableQueryRightPanel/TableQueryRightPanel.component.tsx
Add used by field in query entity
also closes #13085
#
#
> Add used by field in query entity

- ingestion/tests/cli_e2e/test_cli_mysql.py
Fixes Mysql e2e test changes
changes in number of tables caused the issue as we added a new table
#
#
> add mysql e2e changes

- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dashboardServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceProfilerPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceQueryLineagePipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceQueryUsagePipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/messagingServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/mlmodelServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/pipelineServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/searchServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storageServiceMetadataPipeline.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/testSuitePipeline.json
Fix Ingestion Pipeline Configuration Titles
#
#
> Fix Ingestion Pipeline Configuration Titles

- openmetadata-service/pom.xml
I worked on ... because ... doc path error
- [ x] Bug fix
> doc issue fix

- openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
> Fix #11715: Add Owner EntityRef type validation

- openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
Reverts open-metadata/OpenMetadata#13126
> Revert "Fix #11715: Add Owner EntityRef type validation"

- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/hiveConnection.json
> Fix hive metastore test connection

- openmetadata-service/src/main/java/org/openmetadata/service/resources/glossary/GlossaryResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/glossary/GlossaryTermResource.java
- openmetadata-spec/src/main/resources/json/schema/api/data/createGlossary.json
- openmetadata-spec/src/main/resources/json/schema/api/data/createGlossaryTerm.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/glossary.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/glossaryTerm.json
> Fix #12898: Support custom properties for Glossary and Glossary Term

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DomainRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/domains/DomainResourceTest.java
> Fixes 13146 - Patch operation not working for Domain

- ingestion/setup.py
Use Collate SQLLineage Package for lineage
#
#
> Use Collate SQLLineage Package for lineage

- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- added back set engine per project ID
#
#
> Issue 12989 - Fix multi project metadata ingestion in BQ

- Makefile
> [Docs] - Yarn dev on local docker

- ingestion/src/metadata/ingestion/source/database/bigquery/connection.py
- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/ingestion/source/database/bigquery/queries.py
- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/database_service.py
- ingestion/src/metadata/utils/logger.py
Fixes #12879 
Fixes #12738 
#
#
> Bigquery: Add Table Level Tags, fix dataset issue

- openmetadata-docs/content/partials/v1.1/deployment/upgrade/upgrade-prerequisites.md
> [Docs] - Add sort buffer size

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/unitofwork/HttpGetRequestJdbiUnitOfWorkEventListener.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/unitofwork/JdbiTransactionManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/unitofwork/ManagedHandleInvocationHandler.java
> set autocommit to true for non transactional

- Makefile
- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/ingestion/source/database/bigquery/queries.py
- ingestion/src/metadata/ingestion/source/database/database_service.py
- ingestion/src/metadata/ingestion/source/database/redshift/metadata.py
- ingestion/src/metadata/ingestion/source/database/redshift/models.py
- ingestion/src/metadata/ingestion/source/database/redshift/queries.py
- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
- ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
- ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
part of #12998
and create a mixin to centralize lineage and query retrieval
#
#
> Part of #12998 - Add Stored Procedures support for Redshift

- ingestion/setup.py
> check importlib setup

- bootstrap/sql/migrations/native/1.1.5/mysql/schemaChanges.sql
> only add collation to hash columns

- ingestion/src/metadata/ingestion/api/topology_runner.py
- ingestion/src/metadata/ingestion/models/topology.py
- ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
- ingestion/src/metadata/ingestion/source/database/database_service.py
- ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
- ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
- ingestion/src/metadata/ingestion/source/messaging/messaging_service.py
- ingestion/src/metadata/ingestion/source/pipeline/databrickspipeline/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/pipeline_service.py
- ingestion/src/metadata/ingestion/source/search/search_service.py
- ingestion/tests/unit/topology/test_runner.py
We had two parameters in the NodeStage: `context` and `ack_sink`. However, the `ack_sink` only worked properly for certain types `CreateXRequest`, and in our use case, we were storing in the context the values that we receive after the sink has been ack.
Now, we are keeping a single param `context`, which if informed, will be used to ack the sink and store the results from the API in the context. We are adding support for handling different kinds of types as well, such as AddLineageRequest of OMetaTagAndCategories.
#
#
> Simplify topology & update context management

- openmetadata-ui/src/main/resources/ui/src/components/common/EntitySummaryDetails/EntitySummaryDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/EntitySummaryDetails/EntitySummaryDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TeamTypeSelect/TeamTypeSelect.component.tsx
Fixes #13204 
I worked on issue #13204 
https://github.com/open-metadata/OpenMetadata/assets/59080942/5099b3c1-4732-49d5-a75c-4d1d98010b85
#
#
> fix(#13204): after changing the team type action buttons are not disappearing

- openmetadata-ui/pom.xml
> fix om package bundling

- docker/docker-compose-quickstart/Dockerfile
Fixing label version in dockerfile
#
#
> [FIX] Dockerfile label version to 1.1.5

- docker/docker-compose-quickstart/Dockerfile
Fixing dockerfile arg variable syntax
#
#
> [Fix] Fixing dockerfile arg variable

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java
Fixes #13049
This fix changes glossary to glossary term relationship. Glossary has `Contains` relationship to the root glossary terms. The relationship from Glossary to children of root glossary terms is changed to `Has`. The existing parent glossary term having `Contains` relationship to the children terms will remain as it currently is.
#
#
> Fixes #13049 - Glossary recursive delete fails

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/EntityResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java
> Code cleanup necessary for Glossary workflow

- ingestion/tests/unit/topology/metadata/test_atlas.py
- openmetadata-service/pom.xml
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/tags/TagLabelUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/util/TestUtils.java
- openmetadata-spec/src/main/resources/json/schema/type/tagLabel.json
> Fix #12899: UI to use Tier TAG displayName if provided

- openmetadata-spec/src/main/resources/json/schema/type/tagLabel.json
> Fix glossary test

- docker/docker-compose-quickstart/Dockerfile
Updating Docker Label for release version.
> Fix:Updating Docker Label for version update via makefile

- ingestion/src/metadata/ingestion/source/database/database_service.py
- ingestion/src/metadata/ingestion/source/database/life_cycle_query_mixin.py
- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
- ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
- ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
Added caching for life cycle query
#
#
> Added caching for life cycle query
