open-metadata/OpenMetadata

openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationWorkflow.java, openmetadata-service/src/main/java/org/openmetadata/service/util/TablesInitializer.java, openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
=> Fix Failing Maven CI Test

openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestSuiteResource.java, openmetadata-service/src/main/resources/elasticsearch/jp/test_case_index_mapping.json, openmetadata-service/src/main/resources/elasticsearch/zh/test_case_index_mapping.json, openmetadata-service/src/main/resources/json/data/tests/columnValueMeanToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValueMedianToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValueStdDevToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValuesLengthsToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValuesToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/tableColumnToMatchSet.json, openmetadata-service/src/main/resources/json/data/tests/tableRowCountToBeBetween.json
Fixes a few bugs from data quality endpoint
- added zh and jp index
- change testSuite permission to `VIEW_TEST`
- set owner of testSuite to owner of table on creation fixes #12141
#
#
=> Address backend DQ feedback

ingestion/src/metadata/ingestion/api/workflow.py, ingestion/src/metadata/ingestion/connections/test_connections.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/common.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/data_insight.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/es_reindex.py
To make it easier to identify issues
#
#
=> Update logging messages for JWT tokens

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/TagsInput/TagsInput.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/AddGlossary/AddGlossaryPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryLeftPanel/GlossaryLeftPanel.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/styles/components/entity-version-time-line.less, openmetadata-ui/src/main/resources/ui/src/styles/components/glossary.less, openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.ts, openmetadata-ui/src/main/resources/ui/src/utils/TeamUtils.ts
Fixes loading of glossary with name having dot in it.
#
#
=> fix(ui): glossary name with dot loading issue

ingestion/Dockerfile, ingestion/operators/docker/Dockerfile, ingestion/setup.py, ingestion/src/metadata/ingestion/source/database/clickhouse/connection.py, openmetadata-airflow-apis/setup.py
Clickhouse Connection Argument Nonetype Bug
when set the secure flag from UI and do not pass any connection arguments from UI it fails with the error that `NoneType has no attribute __root__` this wasn't happening with the earlier versions because we used to pass the empty dict from the UI itself but since now UI sends null it fails with this error.
#
#
=> Clickhouse Connection Argument Nonetype Bug

bootstrap/sql/com.mysql.cj.jdbc.Driver/v013__create_db_connection_info.sql, bootstrap/sql/org.postgresql.Driver/v013__create_db_connection_info.sql, openmetadata-service/src/main/java/org/openmetadata/service/migration/versions/mysql/v110/MySQLMigration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/versions/postgres/v110/PostgresMigration.java
entries in `query_entity` that do not have the FQN informed are not getting listed when doing the name hash migration.
Adding the FQN solves the issue.
This looks like an issue coming from an old version upgrade, since the UI generates the right data.
This will need to be ported to 1.1.0
#
#
=> Add query_entity migration fix

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java, openmetadata-service/src/main/java/org/openmetadata/service/exception/OMErrorPageHandler.java
Fixes missing security header in response in case of Error Page (404)
Currently the server APIs have the correct response headers from the web configuration , but to serve index.html , whenever we hit 404 that response doesn't seem to contain those header , this Pr takes care of that
#
#
=> Fix Missing Config on Error Page Response in #UI

ingestion/src/metadata/profiler/orm/functions/median.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/12439
I worked on fixing profiling for trino jobs because it fails when column profile is calculated.
#
#
=> Fixes 12439: Remove braces from approx_percentile method (Trino/Presto) in profiler

bootstrap/sql/com.mysql.cj.jdbc.Driver/v014__create_db_connection_info.sql, bootstrap/sql/org.postgresql.Driver/v014__create_db_connection_info.sql, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DomainRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionResource.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/query/QueryResource.java, openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/domains/DataProductResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/domains/DomainResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestDefinitionResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/events/EventSubscriptionResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/kpi/KpiResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/metadata/TypeResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/query/QueryResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/tags/ClassificationResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/tags/TagResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/util/EntityUtilTest.java, openmetadata-spec/src/main/resources/json/schema/entity/data/query.json, openmetadata-spec/src/main/resources/json/schema/events/eventSubscription.json
Fixes issues where different entity resource tests are incorrectly initializing `supportsEmptyDescription` and `supportsSoftDelete` flags. Cleaning up unnecessary `deleted` fields in some entities that don't support soft delete.
#
#
=> Initialize EntityResoruceTest support flags automatically

conf/openmetadata.yaml, openmetadata-service/src/main/java/org/openmetadata/service/util/UserUtil.java
=> Fix #12610: adminUsers lookup should be quoted, do not allow bot users s to be promoted to admin user via adminUsers config

.github/workflows/cypress-integration-tests-mysql.yml, .github/workflows/cypress-integration-tests-postgresql.yml
The following action removes these packages - " azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri"
which are needed in cypress test, making it false so that packages can be found on runner.
In reference to : https://github.com/open-metadata/OpenMetadata/actions/runs/5693882152/job/15433925744?pr=12646
=> Updating the large package removals for cypress

openmetadata-spec/src/main/resources/json/schema/entity/services/storageService.json
Add support to using a custom storage connection
Fixes issue 12528 (https://github.com/open-metadata/OpenMetadata/issues/12528)
I have updated the serviceConnection JSON schema so that it allows defining a serviceConnection of the CustomStorageConnection type, and not just S3. This will allow building custom connectors for storages that are not S3.
- [X ] Improvement
#
=> Fixes 12528: add custom storage connection to storageService.json 

ingestion/Dockerfile, ingestion/Dockerfile.ci, ingestion/operators/docker/Dockerfile, ingestion/operators/docker/Dockerfile-dev
This PR will reduce the ingestion docker image size by a 25%.
Reduction is driven by [avoiding the pip cache](https://pip.pypa.io/en/stable/topics/caching/#avoiding-caching) and vim packages.
It also reduces the output generated in the build process enabling the quiet flag in `curl, apt, pip, wget and unzip` steps.
#
#
=> [CHORE] Reduce docker image size by removing pip cache

ingestion/Dockerfile, ingestion/Dockerfile.ci
Align Docker Base Image to use airflow 2.5.3.
The reason for this change is that Helm Dependencies for Airflow which we depend on only supports airflow version uptill 2.5.
Ref - https://github.com/airflow-helm/charts/tree/main/charts/airflow#key-features
This change will better aling our quick-start methods to use same airflow version.
I've tested this change with Docker deployments as well as Kubernetes Deployments.
#
#
=> fix: Align Docker Base Image to use airflow 2.5.3

openmetadata-docs/content/partials/v1.1.1/deployment/upgrade/upgrade-prerequisites-111.md
Updating version to 1.1.1 in an upgrade docs
#
#
=> [Fix] Docs update to 1.1.1 version

openmetadata-service/src/main/java/org/openmetadata/csv/EntityCsv.java, openmetadata-service/src/test/java/org/openmetadata/csv/EntityCsvTest.java
validate the entity names during the dry run
- [x ] Bug fix
#
=> Fix #10164: Check any name voilations during the import dryrun

.github/workflows/airflow-apis-tests-3_9.yml, .github/workflows/java-checkstyle.yml, .github/workflows/monitor-slack-link.yml, .github/workflows/publish-maven-package.yml, .github/workflows/security-scan.yml, .github/workflows/selenium-noIngestion-tests.yml
Removing the large packages clean as the github action is failing on fetching  http://azure.archive.ubuntu.com/ubuntu which is causing the ci to fail overall
Ref: Tested here in Forked branch - https://github.com/deuex-solutions/OpenMetadata-1/actions/workflows/disk-space-test.yml
=> Removing the large packages clean as the github action is failing

bootstrap/sql/migrations/native/1.2.0/mysql/schemaChanges.sql, bootstrap/sql/migrations/native/1.2.0/postgres/schemaChanges.sql, ingestion/examples/sample_data/datasets/stored_procedures.json, ingestion/src/metadata/ingestion/ometa/ometa_api.py, ingestion/src/metadata/ingestion/ometa/routes.py, ingestion/src/metadata/ingestion/source/database/sample_data.py, openmetadata-service/src/main/java/org/openmetadata/service/Entity.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SearchIndexRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/StoredProcedureRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/StoredProcedureResource.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/StoredProcedureResourceTest.java, openmetadata-spec/src/main/resources/json/schema/api/data/createStoredProcedure.json, openmetadata-spec/src/main/resources/json/schema/entity/data/storedProcedure.json
=> Fix #12167: Support for Stored Procedures as another entity under Database Schema

openmetadata-docs/content/partials/v1.1.2/deployment/upgrade/upgrade-prerequisites-112.md, openmetadata-docs/content/v1.1.2/deployment/docker/index.md, openmetadata-docs/content/v1.1.2/deployment/upgrade/index.md, openmetadata-docs/content/v1.1.2/quick-start/local-docker-deployment.md
Fixing the Doc of 1.1.2 with the required changes
#
#
=> [DOC FIX] Updating 1.1.2 Documentation with the required fixes

ingestion/tests/cli_e2e/test_cli_mysql.py
#12991 introduced new tables
#
#
=> Fix e2e mysql numbers - post #12991

openmetadata-ui/src/main/resources/ui/src/assets/svg/ic-stored-procedure.svg, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.interface.ts, openmetadata-ui/src/main/resources/ui/src/constants/PageHeaders.constant.ts, openmetadata-ui/src/main/resources/ui/src/constants/constants.ts, openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx, openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedurePage.tsx, openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsUtils.tsx, openmetadata-ui/src/main/resources/ui/src/utils/StoredProceduresUtils.tsx
Fixes https://github.com/open-metadata/OpenMetadata/issues/12167
- supported custom property tab in stored procedure and setting page
#
#
=> feat(ui): supported custom property tab in stored procedure and setting page

openmetadata-docs/content/v1.2.0-SNAPSHOT/connectors/messaging/kafka/index.md, openmetadata-docs/content/v1.2.0-SNAPSHOT/connectors/messaging/kafka/troubleshooting.md
Fixes [13015](https://github.com/open-metadata/OpenMetadata/issues/13015)
If you are using Confluent kafka and SSL encryption is enabled you need to add `security.protocol` as key and `SASL_SSL` as value under Consumer Config.
#
#
=> Fixes 13015 : [Docs] Add SSAL_SSL config info for Confluent kafka with SSL encryption

ingestion/src/metadata/profiler/metrics/system/queries/redshift.py, ingestion/src/metadata/profiler/metrics/system/system.py, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityTimeSeriesDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- Revert the ulster logic for profiler system metrics as the timestamp is the one of the operation (and not the one of the profiler execution)
- Removed unnecessary redshift system metric query field
=> fix: added upsert logic back for system metrics

openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertsRuleEvaluator.java
- add logic to check for field updated and field added when evaluating the test result
- add logic to handle entiyFQN filtering for test cases (i.e. this will be the entity against which the test cases are running)
#
#
=> fix: alerting for entiyFQN filter and testResult filter for test cases

ingestion/Dockerfile, ingestion/Dockerfile.ci
Upgrading the airflow base image from 2.5.3 to 2.6.3
=> Upgrade: airflow base image from 2.5.3 to 2.6.3

openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/mocks/DatabaseSchemaPage.mock.ts, openmetadata-ui/src/main/resources/ui/src/rest/storedProceduresAPI.ts
Fixes #13102
- I worked on supporting unit tests for database schema
#
#
=> fix(ui): supported unit test for stored database schema page

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
- move update testSuite summary on test case deletion from postDelete to preDelete. In postDelete the relationship does not exists anymore (the test case has been deleted) - hence causing the testSummary to not be updated.
=> fix: move testSuite summary state update to preDelete

ingestion/src/metadata/great_expectations/action.py
Fixes #10096
I worked on adding the `RuntimeDataBatchSpec` option as a GX backend. This change requires that in the expectation suite the table name is defined under `expectation_suite_name` i.e. `table_name_1`. The format for the name is with underscores and with a unique identifier at the end so multiple suites can be used for the same table. 
```
{
"expectations": [
{
"kwargs": {
"min_value": 1,
"max_value": 3100000
},
"expectation_type": "expect_table_row_count_to_be_between",
"meta": {}
}
],
"data_asset_type": "Dataset",
"meta": {
"great_expectations_version": "0.15.48"
},
"expectation_suite_name": "table_name_1",
"ge_cloud_id": null
}
``` 
Also in the action (this was already there) the `database service`, `database name` and `schema name` should be passed and are not optional.
``` …
```
=> Fixes #10096: adding RuntimeDataBatchSpec as a GX backend

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityInfoDrawer/EntityInfoDrawer.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/DashboardSummary/DashboardSummary.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/GlossaryTermSummary/GlossaryTermSummary.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TagsSummary/TagsSummary.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TopicSummary/TopicSummary.component.tsx, openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
I worked on removing the error toasts for API failures in the summary panels
#
#
=> chore(ui): removed error toasts for API failures in summary panels

openmetadata-ui/src/main/resources/ui/cypress/common/common.js, openmetadata-ui/src/main/resources/ui/cypress/constants/Version.constants.js, openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js, openmetadata-ui/src/main/resources/ui/cypress/constants/tagsAddRemove.constants.js, openmetadata-ui/src/main/resources/ui/cypress/constants/updateDisplayName.constant.js, openmetadata-ui/src/main/resources/ui/cypress/constants/voting.constant.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/Following.spec.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/RecentlyViewed.spec.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AddAndRemoveTierAndOwner.spec.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/EntityVoting.spec.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/TagsAddRemove.spec.js, openmetadata-ui/src/main/resources/ui/src/components/StoredProcedureVersion/StoredProcedureVersion.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/DataModelPage/DataModelPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/rest/dataModelsAPI.ts
Fixes #12998
- added cypress for Stored Procedure and Data Model
#
#
=> supported cypress for stored procedure and data models

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
Fix: Bigquery Table Tag not assigned
#
#
=> Fix: Bigquery Table Tag not assigned

.github/workflows/cypress-integration-tests-mysql.yml, .github/workflows/cypress-integration-tests-postgresql.yml
Cypress Workflow timeout-minutes to 120.
#
#
=> fix(CI): Cypress Workflow timeout-minutes to 120

openmetadata-docs/content/v1.1.x/connectors/pipeline/airflow/yaml.md
fix for seems like copy-paste documentation error when someone was documentation for Airflow connector using airbyte as a template page.
=> Update references to Airflow instead of Airbyte

docker/development/docker-compose-postgres.yml
fix: Postgresql Docker Compose Services Dependency
#
#
=> fix(CI): Postgresql Docker Compose Services Dependency

openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/ManageButton/ManageButton.tsx
I worked on adding support for the prepareType prop in the manage button component as it handles the delete entity operation and we pass the entityType prop to it to dynamically create the delete operation API endpoint, so prepareType will be helpful to let the entity decide it either prepare the entityType or just use the passed entityType as it is.
#
#
=> chore(ui): add prepareType prop support in manage button component

openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/tag-select-fom.style.less, openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
I worked on changing variable file import to a relative path
#
#
=> chore(ui): changed the variables file import to a relative path

openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidget.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/ManageButton/ManageButton.tsx
I worked on adding support for custom messages and options in delete widget modal.
#
#
=> chore(ui): add support for custom messages and options in delete widget modal

openmetadata-service/src/main/resources/elasticsearch/indexMapping.json
I worked on ... because ...Add services index to 'all' alias
#
- [ x] Bug fix
=> Add services index to all alias

openmetadata-docs/content/v1.2.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/openmetadata-server.md
If I cd into bootstrap folder as the current docs suggest, I get `Error: Could not find or load main class`. However, if run from repo root, then it works!
Updating the docs to reflect the working behavior
I worked on this because I noticed it while setting up my local development environment
#
=> docs: run bootstrap from correct folder

openmetadata-docs/content/v1.2.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/prerequisites.md
Java 17 appears to be used everywhere else in the repo, which means the instruction to use Java 11 is out of date. In fact, the build fails with Java 11, but succeeds with Java 17.
Updating the docs to reflect this
I worked on this because I was setting up a development environment and realized this was out of date
#
#
=> docs: update java version in contribution docs

openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPageV1.component.tsx, openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsUtils.tsx
I worked on removing the persona settings option for non-admin users
https://github.com/open-metadata/OpenMetadata/assets/51777795/57402865-4bfe-4c8f-bf9c-bdd944a17d95
#
#
=> fix(ui): removed the persona settings option for non-admin users

openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx, openmetadata-ui/src/main/resources/ui/src/constants/constants.ts, openmetadata-ui/src/main/resources/ui/src/utils/TagsUtils.tsx
I worked on adding a filter classification option in the tags container, added default classification `KnowledgeCenter` for filtering to address this comment https://github.com/open-metadata/OpenMetadata/issues/13316#issuecomment-1767595347
https://github.com/open-metadata/OpenMetadata/assets/59080942/dead3106-351a-4fb5-b8b8-e578cd4b84d3
#
#
=> chore(ui): add filter classifications option in tags container

ingestion/src/metadata/ingestion/source/database/bigquery/query_parser.py, ingestion/tests/unit/topology/database/test_bigquery.py
Fixes #13607
I slightly modified the `metadata.ingestion.source.database.bigquery.query_parser.BigqueryQueryParserSource.get_engine()` method so that it doesn't generate an error when used with the `GcpCredentialsPath` config model.
I tested it by building the `development-ingestion` Docker image and configuring our internal OpenMetadata instance to use the modified image instead of the original one.
#
#
=> Fixes #13607: BigQuery lineage ingestion fails when using GcpCredentialsPath authentication config

openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.test.tsx
I worked on changing the API call to fetch owned assets in my data widget to solve the bug where all assets were not showing in the my data widget.
https://github.com/open-metadata/OpenMetadata/assets/51777795/de920474-1413-4df4-a8f7-ec21f74b25b2
#
#
=> fix(ui): all assets not showing on my data widget

ingestion/src/metadata/ingestion/source/database/databricks/unity_catalog/lineage.py, ingestion/src/metadata/ingestion/source/database/postgres/pgspider/lineage.py
- wrap returned value in `Either` object
#
#
Bug fix
=> Fix databricks lineage with unity catalog

ingestion/src/metadata/ingestion/source/dashboard/mstr/metadata.py
=> MSTR fix either

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryDetailsRightPanel/GlossaryDetailsRightPanel.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx
Fixes #13792 
https://github.com/open-metadata/OpenMetadata/assets/33024356/f7e655dc-eb57-4524-90fb-c40583e2c33b
#
#
=> fix: domain assignment for glossary term

openmetadata-docs/content/v1.2.x/deployment/ingestion/mwaa.md
Simplify ECS Operator setup to not rely on the Service creation. We just need to note down some details during the creation but this simplifies things
#
#
=> [Docs] - MWAA ECS Operator updates

openmetadata-ui/src/main/resources/ui/cypress/common/VersionUtils.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/UpdateDisplayName.spec.js
cypress: fixed bug of passing undefined instead of entity name
#
#
=> cypress: fixed bug of passing undefined instead of entity name

ingestion/examples/sample_data/datasets/stored_procedures.json, ingestion/src/metadata/ingestion/source/database/sample_data.py
Added stored procedures sample data
#
#
=> Added stored procedures sample data

openmetadata-docs/content/partials/v1.2/deployment/upgrade/upgrade-prerequisites.md
Add breaking changes for the use of `DB_PARAMS`.
#
#
=> docs: Add breaking changes for the use of `DB_PARAMS`

openmetadata-ui/src/main/resources/ui/cypress/support/commands.js
I worked on fixing what's new pop-up alert box
#
#
=> fix(cypress): what's new pop-up alert box

openmetadata-docs/content/v1.2.x/deployment/security/keycloak/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/keycloak/kubernetes.md
Updating keycloak SSO doc:
- Removing creating secrets information as we don't require it anymore and it is now deprecated.
#
#
=> [DOC-FIX] Update docs of keycloak SSO

openmetadata-docs/content/v1.0.x/connectors/database/athena/airflow.md, openmetadata-docs/content/v1.0.x/connectors/database/athena/cli.md, openmetadata-docs/content/v1.0.x/connectors/database/athena/index.md, openmetadata-docs/content/v1.1.x/connectors/database/athena/index.md, openmetadata-docs/content/v1.1.x/connectors/database/athena/yaml.md, openmetadata-docs/content/v1.2.x/connectors/database/athena/index.md, openmetadata-docs/content/v1.2.x/connectors/database/athena/yaml.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Athena.md
Fixes #13816 
I worked on removing excess permissions on athena
#
#
=> Fixes 13816: Remove Excess Permissions for athena

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
- fix pagination of test case with testSuiteId filter
#
#
Bug fix
=> fix: paginating test cases with testSuiteId filter

openmetadata-docs/content/v1.2.x/deployment/ingestion/mwaa.md, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java
I worked on ... because ... update respective index with the assets
#
- [ x] Bug fix
=> update respective index with the assets

ingestion/src/metadata/data_insight/producer/cost_analysis_producer.py, ingestion/src/metadata/data_insight/producer/entity_producer.py, ingestion/src/metadata/data_insight/producer/producer_factory.py, ingestion/src/metadata/data_insight/producer/web_analytics_producer.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/13789
#
#
=> Cost Analysis: Process entities with support for profiler and usage

openmetadata-docs/content/v1.2.x/quick-start/local-docker-deployment.md
fix(docs): `curl` command of quickstart guide
#
#
=> fix(docs): `curl` command of quickstart guide

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/SearchIndexDetails.spec.js, openmetadata-ui/src/main/resources/ui/src/components/CreateUser/CreateUser.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomControls.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Users/UsersProfile/UserProfileRoles/UserProfileRoles.component.tsx, openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx
Fixes #13895
- I worked on fixing the search not working in roles input  in the user profile page
https://github.com/open-metadata/OpenMetadata/assets/66266464/91bc371f-c6ea-4849-85a5-62b8223141ef
#
#
=> fix(ui): fix search not working in roles input  in user profile page

ingestion/src/metadata/profiler/metrics/system/queries/snowflake.py, ingestion/src/metadata/profiler/metrics/system/system.py, ingestion/src/metadata/utils/profiler_utils.py
- `result_scan` will only return the info for a query ran by the users, we need to get the info directly from the query_history
#
#
=> fix: remove RESULT_SCAN dep.

conf/openmetadata.yaml, docker/docker-compose-quickstart/docker-compose-postgres.yml, docker/docker-compose-quickstart/docker-compose.yml, openmetadata-service/src/test/resources/openmetadata-secure-test.yaml
=> Remove Migration Extension Path Env

openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
I worked on ... because ... remove wildcard search from source url search OS
#
=> remove wildcard search from source url search OS

docker/development/Dockerfile, docker/docker-compose-quickstart/Dockerfile
I worked on updating openmetadata-server image to execute the container as non-root user as users may need to run it with non-root user due to their security requirements. 
We got such request here: [Thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1697535889992959)
#
#
=> Update Dockerfiles to run OMD as non-root user

ingestion/src/metadata/ingestion/source/database/azuresql/metadata.py, ingestion/src/metadata/ingestion/source/database/azuresql/queries.py, ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py, ingestion/src/metadata/ingestion/source/database/greenplum/metadata.py, ingestion/src/metadata/ingestion/source/database/mssql/metadata.py, ingestion/src/metadata/ingestion/source/database/multi_db_source.py, ingestion/src/metadata/ingestion/source/database/postgres/metadata.py, ingestion/src/metadata/ingestion/source/database/redshift/metadata.py, ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py, ingestion/src/metadata/ingestion/source/database/vertica/metadata.py, ingestion/src/metadata/profiler/source/metadata.py, ingestion/src/metadata/profiler/source/metadata_ext.py, ingestion/src/metadata/utils/fqn.py, ingestion/src/metadata/workflow/metadata.py, ingestion/src/metadata/workflow/profiler.py, ingestion/src/metadata/workflow/usage.py, openmetadata-spec/src/main/resources/json/schema/metadataIngestion/workflow.json
=> Add support for external profiler workflow

ingestion/src/metadata/ingestion/source/storage/storage_service.py, ingestion/src/metadata/readers/dataframe/dsv.py, ingestion/src/metadata/readers/dataframe/models.py, ingestion/src/metadata/readers/dataframe/reader_factory.py, ingestion/src/metadata/utils/datalake/datalake_utils.py, ingestion/tests/unit/readers/test_df_reader.py, ingestion/tests/unit/resources/datalake/transactions_separator.csv, openmetadata-docs/content/partials/v1.2/connectors/storage/manifest.md, openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storage/containerMetadataConfig.json, openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storage/manifestMetadataConfig.json
=> Fix #13699 - Add separator for Storage Container manifest

ingestion/src/metadata/ingestion/ometa/mixins/glossary_mixin.py, ingestion/src/metadata/ingestion/ometa/mixins/role_policy_mixin.py, ingestion/src/metadata/utils/deprecation.py, ingestion/tests/unit/utils/test_deprecation.py
For glossary & role mixins which we don't need anymore since we have the new `metadata.patch` that generates the correct jsonpatch properly
#
#
=> Add deprecation warnings

openmetadata-ui/src/main/resources/ui/src/pages/CustomizablePage/CustomizablePage.tsx
I worked on fixing the import path on customizable landing page
#
#
=> fix(ui): fixed import path in customizable page

openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx
I worked on fixing the issue for the Delete widget modal, where the delete state was being reset to the wrong value.
**Before:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/f867a3e3-058f-4eeb-9fa3-5fd25eb07212
**After:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/070c94d5-77d8-4a5d-8965-8ca3bad0b71c
#
#
=> fix(ui): delete widget modal bug

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DashboardIndex.java, openmetadata-ui/src/main/resources/ui/cypress/common/common.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/SchemaSearch.spec.js, openmetadata-ui/src/main/resources/ui/src/components/ClassificationDetails/ClassificationDetails.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/OwnerLabel/OwnerLabel.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.tsx
**UI:** 
I worked on 
**Before:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/6e91e2a0-c9b8-401b-aec0-1fc174b0d0cc
**After:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/47b2f795-1f2f-4997-8390-feafa25e445f
**Backend:**
Fixed an issue mentioned in #12924 which was not fixed yet.
#
#
=> fix(ui): AUT cypress tests

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ChartRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ClassificationRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardDataModelRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DocumentRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DomainRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EventSubscriptionRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PersonaRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/RoleRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TagRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
=> Make restoring patch attributes consistent across entities

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
- prevent bot user from updating domains on PUT operations (this needs to be handled via a PATCH)
#
#
Bug fix
=> fix: prevent PUT operation from ingestion bot to update domain

openmetadata-ui/src/main/resources/ui/src/components/GithubStarCard/GithubStarCard.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/GithubStarCard/github-star-card.style.less, openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/WhatsNewAlert/WhatsNewAlert.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whats-new-modal.less, openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- I worked on updating github popup description
- added cancelable option
https://github.com/open-metadata/OpenMetadata/assets/66266464/b1f55750-37a5-43af-8f19-57427003d9cf
#
#
=> fix(ui): updated github popup card

.github/workflows/cypress-integration-tests-postgresql.yml
Remove the strategy block from CI to run only with 1 machine
#
#
=> fix: Remove the strategy block from CI to run only with 1 machine

.github/workflows/py-cli-e2e-tests.yml, ingestion/tests/cli_e2e/dashboard/tableau/tableau.yaml, ingestion/tests/cli_e2e/test_cli_tableau.py
Tableau has updated their default sample data in the trial instances. Due to this the counts have changed
#
#
=> Fixed tableau e2e counts due to new sample data in the instance

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/GlossaryTermsV1.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.tsx
Fixes: #13963
I worked on the fix glossary term not updating Custom properties
https://github.com/open-metadata/OpenMetadata/assets/12962843/3a80237a-6b33-4986-b7d9-f3be18baf108
#
#
=> fix(ui): #13963 glossary term custom property update

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/GlossaryOverviewTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx
- fixed re-render issue in glossary term page
- fixed description title
#
#
=> ui: fixed re-render issue in glossary term page

openmetadata-ui/src/main/resources/ui/cypress/common/DomainUtils.js, openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsDetailsPage/DataProductsDetailsPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DataProductsTab/DataProductsTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
Fixes incorrect count issue for domains having dot in their names.
#
#
=> fix: remove quotes around fqn for domain

openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/TagSuggestion.tsx, openmetadata-ui/src/main/resources/ui/src/utils/TagsUtils.tsx
I worked on adding a `tagType` prop in the TagSuggestion component to make it reusable for both tags and glossary tag sources.
#
#
=> chore(ui): add `tagType` prop in TagSuggestion component

bootstrap/sql/migrations/native/1.2.3/postgres/schemaChanges.sql
Fixed viewparsingtimeout migration query
#
#
=> Fix #14077: Fixe viewparsingtimeout migration query

bootstrap/sql/migrations/native/1.3.0/mysql/postDataMigrationSQLScript.sql, bootstrap/sql/migrations/native/1.3.0/postgres/postDataMigrationSQLScript.sql
Fixes #11357 
- rename profile metric key to `customMetrics`
- Delete customMetrics for extension. Implementation has been overhauled and OM has not had support for computing custom metrics since now. As a result we are deleting the existing data if any were ingested from via the API. Users we'll need to recreate it if there were some customMetrics definition
#
#
=> Fix #11357 - DB migration for custom metrics

openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx, openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/TagsSelectForm.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/TagSuggestion.tsx
I worked on adding `initialOptions` prop in the tag suggestion component so that it can render the initial values options with proper styling and label.
#
#
=> chore(ui): add `initialOptions` prop in tag suggestion component

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseSchemaResourceTest.java
=> Issue #14067: DatabaseSchema Restore operation throws error EntityNotFound, if a table that belongs to schema is already restored

openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsDetailsPage/DataProductsDetailsPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DataProductsTab/DataProductsTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/GlossaryTermsV1.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/GlossaryTermsV1.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
Fixes 
Glossary Term Assets adding/removing for terms having dot in name
#
#
=> fix: assets fqn issue

ingestion/src/metadata/ingestion/api/topology_runner.py, ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py, ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py, ingestion/src/metadata/utils/fqn.py
Minor: Fix E2E Tests failure
#
#
=> Minor: Fix E2E Tests failure

.github/workflows/maven-build.yml, .github/workflows/maven-postgres-tests-build-skip.yml, .github/workflows/maven-postgres-tests-build.yml
I worked on changing the concurrency group names for a couple of workflow files - maven-postgres-tests-build-skip.yml and maven-postgres-tests-build.yml. Since these workflows had the same group name as maven-build.yml workflow. So at any given point of time, only 1 workflow can execute among the 3 (which will be the one with latest commit) and it will cancel any in-progress workflow executions (as we have set concurrency.cancel-in-progress to true). With this change, this conflict will not happen.
#
#
=> fix: CI Workflows concurrency group names

openmetadata-ui/src/main/resources/ui/src/pages/ClassificationVersionPage/ClassificationVersionPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/ClassificationVersionPage/ClassificationVersionPage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.tsx
**Describe your changes:**
Earlier the code used to split the classification Name and get the 0th index but it wasn't required. So fixed it by passing the classification name itself.
Fixes: #14187 
https://github.com/open-metadata/OpenMetadata/assets/58542468/5e298387-3539-41f0-8a56-83d3e9bfb6bc
=> fix: #14187 TagsVersionPage break having dot in it's name

openmetadata-ui/src/main/resources/ui/src/components/Applications/AppSchedule/AppSchedule.component.tsx, openmetadata-ui/src/main/resources/ui/src/utils/CronUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/CronUtils.ts
Fixes  #14182 
The change includes changing the starting index of the days from 0 to 1 according to the official documentation of [Quartz cron format](https://www.quartz-scheduler.org/api/2.1.7/org/quartz/CronExpression.html)
https://github.com/open-metadata/OpenMetadata/assets/58542468/25fb6559-161f-4afc-b61b-45d621e8234a
#
#
=> Fixes #14182: Search Index Application weekly schedule

openmetadata-service/src/main/java/org/openmetadata/service/resources/glossary/GlossaryTermResource.java
=> Fix #13850: Glossary FQN should be used

ingestion/src/metadata/data_insight/producer/web_analytics_producer.py, ingestion/tests/integration/ometa/test_ometa_table_api.py
Fixes #14161 
- Skip on failure when listing entities in DI
#
#
Improvement
=> Fix #14161 - Add skip on failure when listing entities in DI

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SearchIndexRepository.java
=> MINOR: missing import in SearchIndexRepository class

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java, openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/PaginatedEntitiesSource.java
=> Format Error on Indexing Application, and in schedule turn off recreate

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
I worked on adding whats new content for 1.2.3
https://github.com/open-metadata/OpenMetadata/assets/59080942/80f1bbcc-754b-462e-b5c4-31e303dedcb5
#
#
=> doc: add whats new for 1.2.3

ingestion/src/metadata/ingestion/models/patch_request.py, ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py, ingestion/src/metadata/ingestion/sink/metadata_rest.py
Fix allows descriptions and tags to be patched from ingestion for only `Add` operation. This ensures we do not update/replace already exiting descriptions and tags
#
#
=> MINOR: Fix description and tags update from ingestion patch

openmetadata-clients/openmetadata-java-client/pom.xml, openmetadata-service/pom.xml, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataInsightChartRepository.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/searchindex/SearchIndexResourceTest.java, openmetadata-ui/pom.xml, pom.xml
=> Update dependencies and plugins

openmetadata-ui/src/main/resources/ui/src/constants/regex.constants.test.ts, openmetadata-ui/src/main/resources/ui/src/constants/regex.constants.ts
Fixes #14311 
I updated the entityName's regex to support Unicode characters in various languages and added tests.
Tested a few scenarios
- Team and glossary, glossary term creation
- Assigning team as owner
- Assigning the glossary term as a tag
- Then filtering the asset on the explore page with owner and tags
https://github.com/open-metadata/OpenMetadata/assets/59080942/fcb3d258-9c6f-4447-b043-8c31c1ac6035
#
#
=> fix(#14311):Unable to add the term's name in Thai.

openmetadata-docs/content/v1.2.x/deployment/security/amazon-cognito-sso/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/amazon-cognito-sso/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/amazon-cognito-sso/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/auth0/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/auth0/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/auth0/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/azure/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/azure/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/azure/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/basic-auth/index.md, openmetadata-docs/content/v1.2.x/deployment/security/custom-oidc/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/custom-oidc/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/custom-oidc/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/google/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/google/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/google/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/keycloak/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/keycloak/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/keycloak/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/ldap/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/okta/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/okta/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/okta/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/one-login/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/one-login/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/one-login/kubernetes.md
=> Minor: Fix docs to include jwt url from OM in all the principalURLs config

openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.component.tsx
Fixes #14337
I worked on improving conditions for displaying approval controls because their current definitions allowed for self-approving workflows.
#
#
=> fixes #14337: remove security gap in approval workflow

openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/ProfilerLatestValue.tsx, openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/SingleColumnProfile.tsx, openmetadata-ui/src/main/resources/ui/src/constants/profiler.constant.ts, openmetadata-ui/src/main/resources/ui/src/utils/ObjectUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/ObjectUtils.ts, openmetadata-ui/src/main/resources/ui/src/utils/TableProfilerUtils.interface.ts, openmetadata-ui/src/main/resources/ui/src/utils/TableProfilerUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/TableProfilerUtils.ts
Fixes #13445
- refactored the logic to generate profiler metrics
- updated logic to not show points in the graph if data is not available.
- added unit test for changes
https://github.com/open-metadata/OpenMetadata/assets/71748675/c09f2498-aff0-483d-be76-9ea649570a97
#
#
=> #13445 Profiler Graph Should not Show a Point if value is None

.github/workflows/py-cli-e2e-tests.yml, ingestion/tests/cli_e2e/database/bigquery_multiple_project/bigquery_multiple_project.yaml, ingestion/tests/cli_e2e/test_cli_bigquery_multiple_project.py, ingestion/tests/cli_e2e/test_cli_dbt_redshift.py, ingestion/tests/cli_e2e/test_cli_mysql.py
Minor: Fix e2e count mismatch
#
#
=> Minor: Fix e2e count mismatch

.github/workflows/cypress-integration-tests-mysql.yml, .github/workflows/cypress-integration-tests-postgresql.yml
PR - https://github.com/open-metadata/OpenMetadata/pull/14334 was missing job strategy fail-fast configuration. Added it in both the Cypress CI.
#
#
=> Update Cypress CI strategy

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/assets-tabs.less
Fixes #14376
I worked fixing pagination not working for assets tab
https://github.com/open-metadata/OpenMetadata/assets/12962843/3b1f0e60-58a8-408a-8f1e-c350db195d8b
#
#
=> FIX #14376: Pagination control get blocked by notification popup

.github/workflows/security-scan.yml
As of now, When Security scan CI is run, certain reports are throwing errors i.e. airflow-apis-code-scan.json, ingestion-code-scan.json, and server-code-scan.json. These are code scan tests that are failing. Snyk container tests are working fine. For example, we can check this Job's artifacts - [security-scan #201](https://github.com/open-metadata/OpenMetadata/actions/runs/7188904386).
Upon checking, we found that "Snyk Code" - The feature that allows code scan is already enabled for OpenMetadata organization in Snyk. However, The preferred organization is set to the user default organization by default.
Hence, with these changes, Snyk CLI will use OpenMetadata organization for all the following checks.
#
#
=> Update security-scan CI to use OpenMetadata Organization

ingestion/src/metadata/cli/db_dump.py, ingestion/src/metadata/cmd.py, openmetadata-docs/content/v1.2.x/connectors/dashboard/looker/index.md, openmetadata-docs/content/v1.2.x/connectors/dashboard/looker/yaml.md, openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/dashboard/looker/index.md, openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/dashboard/looker/yaml.md
Fixes #14043 ensuring that the db uses a cursor when lifting the data
#
#
=> #14043 - Fix metadata backup memory profile

.github/workflows/py-tests.yml
=> MINOR - Don't fail fast python CI

ingestion/Dockerfile, ingestion/Dockerfile.ci, ingestion/operators/docker/Dockerfile
The GPG Signature key for MySQL `EXPKEYSIG 467B942D3A79BD29` - got recently expired [2023-12-14T15:39:35Z]. 
Our CI pipeline started failing due to this - [Security scan #204](https://github.com/open-metadata/OpenMetadata/actions/runs/7216175762/job/19667819467).
As per [the documentation](https://dev.mysql.com/doc/refman/8.0/en/checking-gpg-signature.html), This key is expired and new key to be used is `B7B3B788A8D3785C`.
However, the apt repository still has the old gpg key set - [reference](https://repo.mysql.com/apt/debian/conf/distributions). This bug is already reported [here](https://bugs.mysql.com/bug.php?id=113427).
Hence with this change, we are removing the old keys. 
#
#
=> Update Dockerfile.ci file to use new MySQL Keys

.github/workflows/airflow-apis-tests-3_9.yml, .github/workflows/cypress-integration-tests-mysql.yml, .github/workflows/cypress-integration-tests-postgresql.yml, .github/workflows/java-checkstyle.yml, .github/workflows/maven-build.yml, .github/workflows/maven-postgres-tests-build.yml, .github/workflows/maven-sonar-build.yml, .github/workflows/playwright-integration-tests-mysql.yml, .github/workflows/playwright-integration-tests-postgres.yml, .github/workflows/py-checkstyle.yml, .github/workflows/py-tests.yml, .github/workflows/yarn-coverage.yml
In the CI we;'re currently getting
```
--------------------
5 |     COPY Gemfile Gemfile
6 |     COPY Gemfile.lock Gemfile.lock
7 | >>> RUN gem install bundler
8 |     RUN bundle config set with 'development test'
9 |     RUN bundle install --jobs 20 --retry 5
--------------------
ERROR: failed to solve: process "/bin/sh -c gem install bundler" did not complete successfully: exit code: 1
Error: Docker build failed with exit code 1
```
#
#
=> MINOR - Update CI lewagon/wait-on-check-action version

ingestion/Dockerfile, ingestion/Dockerfile.ci, ingestion/operators/docker/Dockerfile
Reverts open-metadata/OpenMetadata#14400
We're now getting
```
#44 [ingestion  4/25] RUN rm /etc/apt/sources.list.d/mysql.list
#44 0.247 rm: cannot remove '/etc/apt/sources.list.d/mysql.list': No such file or directory
#44 ERROR: process "/bin/bash -o pipefail -o errexit -o nounset -o nolog -c rm /etc/apt/sources.list.d/mysql.list" did not complete successfully: exit code: 1
------
> [ingestion  4/25] RUN rm /etc/apt/sources.list.d/mysql.list:
0.247 rm: cannot remove '/etc/apt/sources.list.d/mysql.list': No such file or directory
------
failed to solve: process "/bin/bash -o pipefail -o errexit -o nounset -o nolog -c rm /etc/apt/sources.list.d/mysql.list" did not complete successfully: exit code: 1
Failed to start Docker instances!
Error: Final attempt failed. Child_process exited with …
```
=> Revert "Update Dockerfile.ci file to use new MySQL Keys"

openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java
Fixes Spotless formatting issue
#
#
=> MINOR: Apply Spotless issue fix

openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/profiler/index.md
There was a typo in the column profiler image name. Changed it from: Colomn.png --> Column.png
#
#
=> FIXED - [docs] profiler image for column

openmetadata-ui/src/main/resources/ui/src/constants/explore.constants.ts, openmetadata-ui/src/main/resources/ui/src/pages/ExplorePage/ExplorePageV1.component.tsx
When searching in global search we get exception if the searchResult is not type of Tabs present. 
To resolve this filtering the data before setting.
=> fix: exception on global search sometimes

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
=> Fix Charts Tasks for description update

openmetadata-ui/src/main/resources/ui/cypress/constants/Version.constants.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/EntityVersionPages.spec.js, openmetadata-ui/src/main/resources/ui/src/components/PipelineVersion/PipelineVersion.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/PipelineVersion/PipelineVersion.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/SchemaTable/SchemaTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/VersionTable/VersionTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/VersionTable/VersionTable.interfaces.ts, openmetadata-ui/src/main/resources/ui/src/components/VersionTable/VersionTable.test.tsx, openmetadata-ui/src/main/resources/ui/src/mocks/PipelineVersion.mock.ts, openmetadata-ui/src/main/resources/ui/src/mocks/VersionTable.mock.ts, openmetadata-ui/src/main/resources/ui/src/utils/EntityVersionUtils.interface.ts, openmetadata-ui/src/main/resources/ui/src/utils/EntityVersionUtils.tsx, openmetadata-ui/src/main/resources/ui/src/utils/ServiceMainTabContentUtils.tsx
Fixes #14363 
I worked on fixing the following bugs:
https://github.com/open-metadata/OpenMetadata/assets/51777795/8099d85b-20f1-4871-b6bb-b63c018a38bb
#
#
=> #14363: Fixed version page breaking issue for Table and Pipeline assets.

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/ExplorePage/ExplorePageV1.component.tsx, openmetadata-ui/src/main/resources/ui/src/styles/components/size.less, openmetadata-ui/src/main/resources/ui/src/styles/components/table.less, openmetadata-ui/src/main/resources/ui/src/styles/position.less, openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsUtils.tsx, openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
this pr fix issue #14257 
**### Before**
**### After**
=> fix(#14257): glossary term name get fully truncate for long text in glossary table

bootstrap/sql/migrations/native/1.2.4/mysql/schemaChanges.sql, bootstrap/sql/migrations/native/1.2.4/postgres/schemaChanges.sql, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/feeds/MessageParser.java
=> Fix #13982: Fix userFQN encoding while creating mentions

openmetadata-ui/src/main/resources/ui/cypress/common/common.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightSettings.spec.js, openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomainForm/AddDomainForm.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/AddGlossary/AddGlossary.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/AddGlossaryTermForm/AddGlossaryTermForm.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryDetails/GlossaryDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.interface.tsx, openmetadata-ui/src/main/resources/ui/src/components/Persona/AddEditPersona/AddEditPersona.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/SelectableList/SelectableList.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/UserSelectableList/UserSelectableList.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/UserSelectableList/UserSelectableList.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/common/UserSelectableList/UserSelectableList.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/UserTag/UserTag.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/UserTag/UserTag.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/common/UserTag/UserTag.test.tsx
Fixes #14486 
- Filter current user from reviewers list
I worked on 
https://github.com/open-metadata/OpenMetadata/assets/12962843/4440dd8a-624d-4e67-b87b-44be92a03a68
#
#
=> FIX: #14486 filter current user from reviewer list

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestSuiteResource.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java, openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.test.tsx, openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
Fixes #14396 
Add parameter to exclude test suite without test cases from listing
#
#
Improvement
=> FIXES #14396: Exclude empty test suites from quality page

ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py, ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py, ingestion/src/metadata/ingestion/source/dashboard/domodashboard/metadata.py, ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py, ingestion/src/metadata/ingestion/source/dashboard/redash/metadata.py, ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py, ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py, ingestion/src/metadata/ingestion/source/database/domodatabase/metadata.py, ingestion/src/metadata/ingestion/source/database/sample_data.py, ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py, ingestion/src/metadata/ingestion/source/pipeline/airflow/models.py, ingestion/src/metadata/utils/constants.py, ingestion/tests/integration/ometa/test_ometa_user_api.py, ingestion/tests/unit/topology/dashboard/test_looker.py, ingestion/tests/unit/topology/pipeline/test_airflow.py, openmetadata-service/src/main/java/org/openmetadata/service/Entity.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java, openmetadata-service/src/main/resources/elasticsearch/en/team_index_mapping.json, openmetadata-service/src/test/java/org/openmetadata/service/resources/pipelines/PipelineResourceTest.java, openmetadata-spec/src/main/resources/json/schema/entity/data/pipeline.json
Related to #11799 
Adding ownership to tasks and using `field_relationship` table to store this info. We're deleting the relationship if a task gets deleted or if the full pipeline is deleted
#
#
=> #11799 - Fix Airfow ownership & add pipeline tasks

conf/openmetadata.yaml
Revert Metadata API endpoint for pipeline for less confusion
=> Revert Metadata API endpoint for pipeline

ingestion/src/metadata/ingestion/source/database/bigquery/connection.py
Fixed an issue in the BigQuery `test_connection` process where a `GetTags-403 Permission denied on resource project None.` error was encountered during the execution of `test_tags`. The previous implementation erroneously executed `list_taxonomies` without utilizing the specified `taxonomyProjectID`, leading to the error. While I am uncertain if `engine.url.host` can contain a GCP Project ID, I have made efforts to maintain backward compatibility as much as possible. However, there is one backward-incompatible change regarding the behavior when `taxonomyLocation` is not set. To prevent errors when `taxonomyLocation` is not configured, I have altered the process to log an info message and skip the execution of `list_taxonomies`.
<details><summary>Ingestion Error Log</summary>
<p>
``` …
```
=> Fixes: `GetTags-403 Permission denied on resource project None.`

ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/14528
I worked on filtering out task instances which are related to tasks no longer present in serialized dag object because fetching statuses for such tasks results in errors during ingestion.
#
#
- [] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.
=> Fixes 14528: skip statuses for tasks that are no longer present in Airflow DAG

openmetadata-ui/src/main/resources/ui/src/components/SchemaTable/SchemaTable.component.tsx
Fixes issue with encoding on permission 
https://github.com/open-metadata/OpenMetadata/assets/12962843/0f723cad-af19-4a41-9a5e-ebccbf3c1aca
#
#
=> fix(ui): pass encoded fqn to fetch table permission

openmetadata-ui/src/main/resources/ui/src/components/SchemaTable/SchemaTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx, openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
**### Before** 
https://github.com/open-metadata/OpenMetadata/assets/80886271/cf209220-cd74-4415-b1de-c90cdd04ea7a
**### After**
https://github.com/open-metadata/OpenMetadata/assets/80886271/cad8ec7f-6108-4345-ba61-9d0342d8e237
=> fix(#14068): show displayName if present in column and search should also show the result considering displayName

openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/mocks/Task.mock.ts, openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.test.tsx, openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.ts
Fixes #14486
- I worked on fixing current user appearing while editing task assignees
https://github.com/open-metadata/OpenMetadata/assets/66266464/55d7be7c-7bcf-4b0a-ac2e-9267ca478832
#
#
=> #14486 : fix current user appearing while editing task assignees

openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/MlModelPage/MlModelPage.component.tsx
Fixes #14565 
I worked on issue #14565 
https://github.com/open-metadata/OpenMetadata/assets/59080942/882f8951-7530-450f-b210-a43d3de7a8d6
#
#
=> FIX[#14565]: container and ml models custom property apis are sending wrong payload

.github/workflows/cypress-integration-tests-mysql-skip.yml, .github/workflows/cypress-integration-tests-mysql.yml, .github/workflows/cypress-integration-tests-postgresql-skip.yml, .github/workflows/cypress-integration-tests-postgresql.yml, openmetadata-docs/content/v1.2.x/deployment/kubernetes/values.md, openmetadata-ui/src/main/resources/ui/cypress.config.ts
Fixes [#14483](https://github.com/open-metadata/OpenMetadata/issues/14483)
Since Cypress project ID for workflows triggered by PRs and schedule (including workflow dispatch) should be different, Introduced a new step in the CI workflows `cypress-integration-tests-mysql.yml` and `cypress-integration-tests-postgresql.yml` that would check the type of event and set a new environment variable `PROJECT_ID` which would be passed to `Run Cypress Tests` step.
Also removed scheduled event triggers from the skip workflows as it is not required.
#
#
=> Update cypress workflows

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java, openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuites/TestSuites.test.tsx
MySQL filter query was not working as expected. Using the same logic with Mysql and postgres now
#
#
=> MINOR - Fix Empty Test Suites list filter

openmetadata-docs/content/v1.2.x/deployment/security/auth0/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/auth0/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/azure/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/azure/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/azure/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/basic-auth/index.md, openmetadata-docs/content/v1.2.x/deployment/security/custom-oidc/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/custom-oidc/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/custom-oidc/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/google/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/google/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/google/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/keycloak/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/keycloak/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/keycloak/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/ldap/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/okta/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/okta/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/okta/kubernetes.md, openmetadata-docs/content/v1.2.x/deployment/security/one-login/bare-metal.md, openmetadata-docs/content/v1.2.x/deployment/security/one-login/docker.md, openmetadata-docs/content/v1.2.x/deployment/security/one-login/kubernetes.md
Fix documented API Endpoint url for PublicKeys.
#
#
=> docs: Fix documented API Endpoint url for PublicKeys

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestSuiteResource.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java
=> Fix #12854: Executable TestSuite should inherit the ownership from it's table

openmetadata-service/src/main/java/org/openmetadata/service/formatter/entity/TestCaseFormatter.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java, openmetadata-spec/src/main/resources/json/schema/tests/basic.json
Fixes #14610 
- User creates a test case for the first time on a table, UI makes call to create a native testSuite and also creates the test case for it. This test suite must show up in DQ page.
- User deletes the last test case belonging to a native test suite. This test suite has zero tests and shouldn't be visible in DQ page.
- Added new status called "Queued" to the TestCaseStatus to indicate a newly created test case is yet to run @ShaileshParmar11 we need to display this in the DQ page as another metric after Aborted.
@TeddyCr give it a review please.
#
#
=> Fix #14610: includeEmptyTestSuite behavior causing not include newly created test suites

openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AppRouter.tsx
I worked on adding a check for if an analytics instance is available then only track the event and collect the page data.
#
#
=> Minor: invoke analytics instance only when it's available

.github/workflows/cypress-integration-tests-mysql.yml, .github/workflows/cypress-integration-tests-postgresql.yml
fix(CI): Cypress CI to use different Record Key for Schedule runs
#
#
=> fix(CI): Cypress CI to use different Record Key for Schedule runs

openmetadata-ui/src/main/resources/ui/webpack.config.prod.js
I updated a `hash` to `fullhash` for both `filename` and `chunkFilename` in the webpack production config because the `hash` is deprecated, for more info read here https://webpack.js.org/configuration/output/#template-strings
#
#
=> Minor: update `hash` to `fullhash` for filename and chunkFilename in webpack prod config

ingestion/src/metadata/ingestion/source/database/databricks/client.py, ingestion/src/metadata/ingestion/source/pipeline/databrickspipeline/connection.py
Minor: Fix Databricks Pipeline Test Connection Fix
#
#
=> Minor: Fix Databricks Pipeline Test Connection Fix

ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
With reference to the [issue](https://github.com/open-metadata/OpenMetadata/issues/13966) we'll remove the patch warnings to set `override` to true since there is no option.
Python sdk has already the doc on how to set the force param if the owner is to be updated via python sdk
#
#
=> MINOR: Removed patch mixin warnings

openmetadata-service/src/main/java/org/openmetadata/service/search/SearchIndexFactory.java, openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/GlossaryIndex.java
=> Minor: Add glossary index to SearchIndexFactory

.github/workflows/cypress-integration-tests-mysql.yml, .github/workflows/cypress-integration-tests-postgresql.yml
Update CRON for Cypress CI.
- MySQL will run on Tuesday and Thursday.
- PostgreSQL will run on Monday, Wednesday and Friday.
#
#
=> chore(ci): Update CRON for Cypress CI

ingestion/src/metadata/ingestion/source/database/column_type_parser.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/metadata.py, ingestion/tests/unit/resources/expected_output_column_parser.json, ingestion/tests/unit/test_column_type_parser.py
Fix #14653: Fix Unity Catalog no children struct issue
#
#
=> Fix #14653: Fix Unity Catalog no children struct issue

.github/workflows/cypress-integration-tests-postgresql.yml
chore(ci): Remove `paths-ignore` block from `pull_request_target`
#
#
=> chore(ci): Remove `paths-ignore` block from `pull_request_target`

ingestion/src/metadata/ingestion/source/dashboard/mode/client.py, ingestion/src/metadata/ingestion/source/dashboard/mode/connection.py, openmetadata-service/src/main/resources/json/data/testConnections/dashboard/mode.json
Fixes https://github.com/open-metadata/OpenMetadata/issues/14578
#
#
=> Fix #14578: Fixed mode test connection

openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.test.tsx
added tests for PipelineDetails page
#
#
=> test(ui): unit tests for pipeline details

ingestion/src/metadata/parsers/protobuf_parser.py, ingestion/tests/unit/test_protobuf_parser.py
=> Minor: Add Column Support in Protobuf Parser

openmetadata-docs/content/v1.2.x/connectors/database/mssql/index.md, openmetadata-docs/content/v1.2.x/connectors/database/mssql/yaml.md, openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/mssql/index.md, openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/mssql/yaml.md
=> Minor: Docs - MSSQL Usage & Lineage Requirements

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java, openmetadata-ui/src/main/resources/ui/src/pages/AddAlertPage/AddAlertPage.tsx
Fixes Issue in expression parsing and failure in abstractConsumer leading to memory leak
#
#
=> [Fix] Expression Parsing and Failure in AbstractConsumer

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
- When filtering for the latest incidents, `assignee` and `status` must be filtered in the outer query.
#
#
=> Minor: fix incident filtering logic

ingestion/src/metadata/ingestion/source/database/athena/client.py, ingestion/tests/cli_e2e/test_cli_athena.py
Fixed the athena e2e to point at new db `e2e_db` and modified counts accordingly.
Changed logger for athena tags from error->warning.
#
#
=> MINOR: Fixed Athena e2e counts and change to e2e_db

ingestion/src/metadata/profiler/processor/core.py, ingestion/src/metadata/profiler/processor/processor.py, openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceProfilerPipeline.json
Fix #14764: Profiler make compute metric configurable
#
#
=> Fix #14764: Profiler make compute metric configurable

ingestion/src/metadata/ingestion/source/database/databricks/client.py, ingestion/src/metadata/ingestion/source/database/databricks/lineage.py, ingestion/src/metadata/ingestion/source/database/databricks/usage.py, ingestion/src/metadata/ingestion/source/pipeline/databrickspipeline/metadata.py
=> Minor: Optimise Databricks Client

ingestion/src/metadata/workflow/application.py, ingestion/src/metadata/workflow/workflow_status_mixin.py
Setting the wrong service name in the `ingestionPipelineFQN` values in the YAML hangeg the workflow, since it failed before stopping the timer.
Adding a couple of things here:
1. Since we are creating the Ingestion Pipeline already, using its FQN. This means that even if users set the wrong serviceName in the `ingestionPipelineFQN`, it will still work. I am not changing this to only pipeline name or anything since it would require to patch the pipeline service client logic.
2. Adding exception handling so that if something explodes, the workflow gets stopped properly
#
#
=> MINOR - Better handling of Ingestion Pipeline Status

openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx
Fixes #14803
Convert both strings to lowercase before comparison.
=> Fixes #14803: ignore capitalization when confirming deletes 

ingestion/src/metadata/ingestion/lineage/parser.py, ingestion/tests/unit/test_query_parser.py
=> MINOR: Lineage handle copy queries being skipped

ingestion/src/metadata/ingestion/source/database/athena/metadata.py
Fixes #13970
The issue described was being caused because Array(Array) failed as the it needs item_type as argument and it was sent empty. As we don't cater to nested arrays for their children and their types, dataType will be Array, arrayDataType will be Array, dataTypeDisplay would be array<array<.....>>
#
#
=> Fix 13970: Fix Consecutive Array issue in Athena

openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionListTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionListTable.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Services/Services.tsx, openmetadata-ui/src/main/resources/ui/src/constants/constants.ts, openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts, openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json, openmetadata-ui/src/main/resources/ui/src/utils/IngestionUtils.tsx
…
Fixes #13767
- Remove ingestion pipeline action buttons  pipeline service is disabled
- Remove the Add Metadata ingestion button and Add service button if pipeline service is disabled
- Change ingestion table message as per disable pipeline service
#
#
=> #13767: Remove ingestion pipeline action buttons and ingestion button if pipelineService is disabled

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py, ingestion/src/metadata/ingestion/source/database/datalake/connection.py, ingestion/src/metadata/ingestion/source/database/datalake/metadata.py, ingestion/tests/unit/test_entity_link.py, ingestion/tests/unit/topology/database/test_datalake.py
Fixes #13149
Worked on fixing multiple project id for datalake gcs
#
#
=> Fix #13149: Multiple Project Id for Datalake GCS

openmetadata-service/src/main/resources/elasticsearch/en/search_service_index_mapping.json, openmetadata-service/src/main/resources/elasticsearch/en/stored_procedure_index_mapping.json
I worked on ... because ... Minor fix Search service 
#
=> Minor fix Search service 

openmetadata-service/src/main/resources/elasticsearch/en/chart_index_mapping.json
Fixes : #14857
I worked on ... because ... fix a part of es exception while migrate
#
=> fix a part of es exception while migrate

ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
Its just a minimum change in the ingestion framework code to handle a bug that affects the ingestion of Airflow DAGs execution data to OpenMetadata
Fixes #14742
I worked on the change of value in the filter so that it is possible to perform the query because the query expects the string of value 'removed' and not the enum object removed
I tested carefully before the change, observing the behavior of the bug and after the change, confirming its resolution.
#
- [X ] Bug fix
#
=> ISSUE-14742: Adjusting metadata.py to filter by enum value

openmetadata-service/src/main/resources/json/data/EntityObservabilityFilterDescriptor.json, openmetadata-service/src/main/resources/json/data/FilterFunctionsDescriptor.json
- This PR fixes Display Name for alerts and notifications.
- Also fixed error condition in filtering for general metadata events
#
#
=> Fix Display Name for Alerts

ingestion/src/metadata/profiler/metrics/system/queries/snowflake.py, ingestion/src/metadata/profiler/metrics/system/system.py, ingestion/src/metadata/profiler/processor/default.py, ingestion/src/metadata/profiler/source/base/profiler_source.py, ingestion/tests/unit/profiler/conftest.py, ingestion/tests/unit/profiler/sqlalchemy/test_metrics.py, ingestion/tests/unit/profiler/test_utils.py
System metrics now support DMLs such as 
```sql
INSERT INTO USERS (name, age) VALUES ('Lévy', 3), ('Lima', 3);
CREATE OR REPLACE PROCEDURE SILVER.PUBLIC.add_data(to_layer VARCHAR)
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS
BEGIN
INSERT INTO IDENTIFIER(:to_layer) (name, age) VALUES ('Lévy', 3), ('Lima', 3);
END;
CALL SILVER.PUBLIC.add_data('GOLD.PUBLIC.USERS');
```
- table does not have the full db.schema.table -> we search in ES
- table is called from within an stored proc dynamically
#
#
=> MINOR - Snowflake system queries to work with ES & IDENTIFIER

openmetadata-ui/src/main/resources/ui/src/components/SchemaTable/SchemaTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/constants/Task.constant.ts
- fix overflow of table cell data
Issue:  
Resolved :
#
#
=> MINOR: fix overflow of table cell data

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryDetails/GlossaryDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexDetailsPage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedurePage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- I worked on fixing the activity feed persisting old data, even if new activity is performed in entity page
Issue :  
https://github.com/open-metadata/OpenMetadata/assets/66266464/cb03ee2d-6353-4654-968a-0f0a23bd58c8
Resolved : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/b2092792-5bf3-4beb-ba73-77ad1fcdbd3f
#
#
=> MINOR: fix activity feed persisting old data even if new activity is performed in entity page

ingestion/src/metadata/ingestion/connections/test_connections.py, ingestion/tests/integration/automations/test_connection_automation.py, openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/run_automation.py, openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java, openmetadata-spec/src/main/java/org/openmetadata/sdk/PipelineServiceClient.java
=> #13934 - Update test connection no response error msg

openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AuthenticatedAppRouter.tsx
redirect to home page for sign in route when user is already logged in
https://github.com/open-metadata/OpenMetadata/assets/71748675/7264bde2-2aa6-438d-b9c1-54e659e59375
#
#
=> Minor: redirect to home page for signin route when user is already logged in

openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
I worked on handling the navigation because if there is no access token of a user, the user should not be direct to the /access-token and so now redirects to the activity tab.
https://github.com/open-metadata/OpenMetadata/assets/58542468/cfe77acf-6239-4b91-b626-10a8b80aa7e2
#
#
=> ui: handle tab navigation if no access token

openmetadata-ui/src/main/resources/ui/src/utils/StringsUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/StringsUtils.ts
I worked on adding logic for formatting the deeply nested object in formatJsonString util.
https://github.com/open-metadata/OpenMetadata/assets/59080942/89ecb664-0ef4-4293-b80d-ba58d5dbd507
#
#
=> Minor: handle deeply nested object parsing in formatJsonString

ingestion/Dockerfile, ingestion/Dockerfile.ci
K8s requires `apache-airflow-providers-cncf-kubernetes` pip package.
Exclusion of the above package fails to bring up Airflow Community Helm Chart Deployments in Kubernetes.
#
#
=> fix(docker): K8s requires `apache-airflow-providers-cncf-kubernetes` pip package

ingestion/src/metadata/utils/helpers.py
While trying some different ways of actually being able to log the time spent on the Source related activities I found out that when I used a similar logic to the one on the `calculate_execution_time_generator` function, I was getting basically the same time stated at the end of the Workflow run.
After some research I found the following:
> time.perf_counter() → float
> Return the value (in fractional seconds) of a performance counter, i.e. a clock with the highest available resolution to measure a short duration. It does include time elapsed during sleep and is system-wide. The reference point of the returned value is undefined, so that only the difference between the results of two calls is valid.
From this I relized that all the time spent outside the method after yielding the value …
=> MINOR: Fix 'calculate_execution_time_generator'

Makefile, docker/development/docker-compose.yml, openmetadata-docs/content/v1.3.x/developers/contribute/build-code-and-run-tests/prerequisites.md, scripts/check_prerequisites.sh
Added a script the goes over the prerequsities checklist and validates they all exist and are on supported versions.
- added scripts/check_prerequisites.sh.
- added usage in docs.
- added prerequisites to Makefile.
```shell
✓ Python version 3.9.18 is supported.
✓ Docker version 24.0.7 is supported.
✓ Java version 17.0.10 is supported.
✓ Maven version 3.9.6 is supported.
✓ jq version 1.7.1 is supported.
✓ Node version v18.19.0 is supported.
✓ Yarn version 1.22.21 is supported.
✓ ANTLR version 4.9.2 is supported.
✓ All prerequisites are met.
```
```shell
✗ ERROR: Python version 3.12.1 is not supported. Supported versions are: 3.9 3.10 3.11
✓ Docker version 24.0.7 is supported.
✓ Java version 17.0.10 is supported.
✓ Maven version 3.9.6 is supported.
✓ jq version 1.7.1 is supported.
✓ Node …
```
=> docs(check-prerequisites): prerequisites recipe

openmetadata-docs/content/v1.1.x/features/integrations/prefect.md, openmetadata-docs/content/v1.2.x/features/integrations/prefect.md, openmetadata-docs/content/v1.3.x/features/integrations/prefect.md
Fixes #15044
I worked on the documentation of the Prefect integration because several links to the integration docs on the Prefect side were broken due to a small typo in the url (the C and T in prefect were flipped).
#
#
=> Fixes #15044: Fix broken link to Prefect OpenMetadata integration docs

openmetadata-docs/content/partials/v1.3/deployment/upgrade/upgrade-prerequisites.md, openmetadata-docs/content/v1.3.x/deployment/upgrade/bare-metal.md, openmetadata-docs/content/v1.3.x/deployment/upgrade/docker.md, openmetadata-docs/content/v1.3.x/deployment/upgrade/index.md, openmetadata-docs/content/v1.3.x/deployment/upgrade/kubernetes.md
Cleaning up 1.3 upgrade docs
#
#
=> MINOR - Docs for 1.3 release

openmetadata-ui/src/main/resources/ui/src/App.tsx, openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AuthenticatedAppRouter.tsx, openmetadata-ui/src/main/resources/ui/src/components/ApplicationConfigProvider/ApplicationConfigProvider.tsx, openmetadata-ui/src/main/resources/ui/src/utils/ApplicationRoutesClassBase.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/ApplicationRoutesClassBase.ts
I worked on adding base class for application routes
#
#
=> Minor: add application router class

.github/e2eLabeler.yml
use minimatch path for e2e labels
#
#
=> use minimatch path for e2e labels

openmetadata-ui/src/main/resources/ui/cypress/common/Entities/EntityClass.ts
Fixes:
- Improve uniq glossary names to avoid any conflict with other tests
#
#
=> test(ui): cypress create uniq glossary for the tests

openmetadata-ui/src/main/resources/ui/src/pages/EditConnectionFormPage/EditConnectionFormPage.component.tsx
Add display name to request body for Service dto(not overwrite value null)
I don't have issue
displayName for service entity rewrite value to null.
how get bug:
1) Edit service entity (fill field display name) and than save
2) Click "connection" and then click "Edit connection" and than click "Save"
After fix. Bug doesn't repeat
Please merge change to branch 1.2.5-realese
#
#
=> add display name to request body (not overwrite value null)

openmetadata-docs/content/partials/v1.3/deployment/upgrade/upgrade-prerequisites.md
=> MINOR - 1.3 release docker breaking docs

scripts/check_prerequisites.sh
Fixes this error when running the `prerequisite` target:
```shell
bash-3.2$ make prerequisites
Makefile:144: warning: overriding commands for target `build-ingestion-base-local'
Makefile:139: warning: ignoring old commands for target `build-ingestion-base-local'
./scripts/check_prerequisites.sh
./scripts/check_prerequisites.sh: line 15: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
make: *** [prerequisites] Error 2
```
#
#
=> MINOR - fix(prerequisite): add check for bash version

openmetadata-ui/src/main/resources/ui/src/pages/Application/ApplicationPage.test.tsx
=> added unit test for ApplicationPage component

openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
=> Add createIndex/updateIndex to openmetadata-ops.sh

bootstrap/openmetadata-ops.sh
Fixes https://github.com/open-metadata/openmetadata-collate/issues/315
```
❯ sh openmetadata-ops.sh deploy-pipelines
Deploying Pipelines
Instantiating the Argo Service Client with server [https://localhost:2746], namespace [argo], image [openmetadata/ingestion-base:1.0.0-alpha]
Failed to deploy pipeline OpenMetadata_dataInsight of type dataInsight for service OpenMetadata
com.google.gson.JsonIOException: Failed making field 'java.time.Instant#seconds' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
```
After this update:
```
❯ ./openmetadata-ops.sh deploy-pipelines
Deploying Pipelines
Instantiating the Argo Service Client with server [https://localhost:2746], namespace [argo], image [openmetadata/ingestion-base:1.0.0-alpha] …
```
=> MINOR - OpenMetadata OPS to load collate-service jars first

openmetadata-service/src/main/java/org/openmetadata/service/security/auth/LdapAuthenticator.java
Use Unbound SDK Filter helper rather than generating with String
#
#
=> Fix Ldap Filter Parsing Issue for "," in DN

openmetadata-service/src/test/java/org/openmetadata/service/resources/mlmodels/MlModelResourceTest.java, openmetadata-spec/src/main/resources/json/schema/entity/data/mlmodel.json
Fixes #14899 
- container image may not necessarily be a URL (see #14899). If not it will fail Pydantic URL validation -- hence converting to plain string
#
#
=> fix: convert imageRepository to string type

openmetadata-ui/src/main/resources/ui/cypress/common/DataInsightUtils.js, openmetadata-ui/src/main/resources/ui/cypress/common/common.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsight.spec.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightSettings.spec.js, openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/MyData.spec.ts, openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/SearchIndexApplication.spec.ts
Worked on fixing AUT cypress test
#
#
=> Minor: fixed AUT failure of main branch

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx
Fixes <issue-15100>
Add tooltip for field "Test type". Text(value from field description) in tooltip will change depend choose Test type.
Sometime comfortably get tooltip for native language
#
#
=> ISSUE-15100: add tooltip for field Text type

openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
Fixes minor misspelling in language files.
I worked on because I noticed the misspelling when testing the docker install.
#
#
=> fix(ui): Fix minor typo in language string

openmetadata-service/src/main/java/org/openmetadata/service/events/AuditEventHandler.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/system/SystemResource.java, openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BasicAuthenticator.java, openmetadata-service/src/main/java/org/openmetadata/service/util/EmailUtil.java
Fixes #14777 and  #15135
- Audit Logs Error are fixed in case the PUT calls are not returning entities
- Added test Connection as part of Email Test
- Made Email test call to be sync
#
#
=> [Fix] Email Test Issues and Audit Log Issues

ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py
Fix #15112: Fix metabase lineage via api
#
#
=> Fix #15112: Fix metabase lineage via api

ingestion/src/metadata/data_insight/processor/reports/cost_analysis_report_data_processor.py, ingestion/src/metadata/data_insight/processor/reports/data_processor.py, ingestion/src/metadata/data_insight/producer/cost_analysis_producer.py, ingestion/src/metadata/data_insight/producer/entity_producer.py, ingestion/src/metadata/data_insight/producer/producer_interface.py, ingestion/src/metadata/data_insight/producer/web_analytics_producer.py, ingestion/src/metadata/data_insight/source/metadata.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/13790
#
#
=> Fix #13790: Cost analysis Data Insights Optimisations

ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/15173
#
#
=> Fix #15173: Added sql to tableau datamodels

openmetadata-spec/src/main/resources/json/schema/api/createEventPublisherJob.json, openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/internal/searchIndexingAppConfig.json, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/metadata/metadataESConnection.json, openmetadata-spec/src/main/resources/json/schema/events/eventSubscription.json, openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json
Fix Typo: description of default batchsize in json files.
#
#
=> fix: typo description of default batchsize

scripts/check_prerequisites.sh
update pre-requisites for node version check
Node 16 & 17 are not longer in support hence removing it.
reference: https://endoflife.date/nodejs
=> add node 18 as pre-requisites 

openmetadata-docs/content/v1.2.x/deployment/security/ldap/docker.md, openmetadata-docs/content/v1.3.x/deployment/security/ldap/docker.md
update java version in ldap auth docs.
OpenMetadata uses JDK 17 from version 1.2.
#
#
=> Fixes: update java version in ldap auth docs

ingestion/src/metadata/ingestion/source/messaging/kafka/connection.py, openmetadata-service/src/main/resources/json/data/testConnections/messaging/kafka.json, openmetadata-service/src/main/resources/json/data/testConnections/messaging/redpanda.json, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/messaging/kafkaConnection.json, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/messaging/redpandaConnection.json, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Messaging/Kafka.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Messaging/Redpanda.md
=> MINOR: Improve Kafka Test Connection

openmetadata-ui/src/main/resources/ui/src/components/Database/SampleDataTable/SampleDataTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
- fix the Entity Table row shifting issue.
- Make Sample Data table header fix while scrolling 
Issue :   
https://github.com/open-metadata/OpenMetadata/assets/66266464/ee3fede2-9df3-4d92-8335-6fedd9682456
Resolved :  
https://github.com/open-metadata/OpenMetadata/assets/66266464/93cb6f0a-b9ad-488c-a2c1-fc5ccebf7c18
https://github.com/open-metadata/OpenMetadata/assets/66266464/38b7649d-acc9-44c6-a0ef-24cfaeb7a283
#
#
=> MINOR: fix the table row issue and make sample data table header fix

ingestion/src/metadata/ingestion/ometa/ometa_api.py
Modified list_all_entities limit param default value to 100.
We are observing sort buffer limit exceeded errors when we are calling the list_all_entities method with the limit set to 1000. We will set the limit to 100 here
#
#
=> MINOR: Modified list_all_entities limit param default value to 100

.github/workflows/cypress-integration-tests-mysql-pr.yml
Spaces and Tabs of YAML in workflow CI
#
#
=> fix: Spaces and Tabs of YAML in workflow CI

ingestion/src/metadata/data_quality/validations/table/base/tableColumnToMatchSet.py, ingestion/src/metadata/data_quality/validations/table/pandas/tableColumnToMatchSet.py, ingestion/src/metadata/data_quality/validations/table/sqlalchemy/tableColumnToMatchSet.py, ingestion/src/metadata/ingestion/source/database/bigtable/metadata.py, ingestion/src/metadata/ingestion/source/database/bigtable/models.py
- Fix return type from `_run_result` in SQA column to match set validation
#
#
Bug fix
=> MINOR - Fix column to match set test

openmetadata-docs/content/v1.3.x/developers/contribute/developing-a-new-connector/apply-ui-changes.md, openmetadata-docs/content/v1.3.x/developers/contribute/developing-a-new-connector/create-java-class-converter.md, openmetadata-docs/content/v1.3.x/developers/contribute/developing-a-new-connector/define-json-schema.md, openmetadata-docs/content/v1.3.x/developers/contribute/developing-a-new-connector/develop-ingestion-code.md, openmetadata-docs/content/v1.3.x/developers/contribute/developing-a-new-connector/index.md, openmetadata-docs/content/v1.3.x/developers/contribute/developing-a-new-connector/test-it.md, openmetadata-docs/content/v1.3.x/developers/contribute/developing-a-new-connector/update-documentation.md, openmetadata-docs/content/v1.3.x/menu.md
Like the title says, Initial proposar for the documentation on How to develop a connector. 
Whenever possible I try to make use of the Code Preview to help the reader follow along with examples.
It is structured with different sections, as follows
---
Small overview on what it means to develop a New Connector and when it makes sense vs a Custom Connector
Points to seting up the Developing environment for OpenMetadata
- Small overview on why JSON Schemas
- Explains the Anatomy of a Connection File
- Explains how to make the Connection available to the Service
- Recommends a good Article explaining the Ingestion Framework
- Explains Service Topology
- Explains Service Source
- Explains what to change to be able to configure the Connector through the UI
- Explains how to create the …
=> MINOR: Initial proposal for the 'developing a connector' user guide

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
=> Fix #15205: Container's Datamodel FQN construction

openmetadata-service/pom.xml, openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java, openmetadata-service/src/test/java/org/openmetadata/service/pipelineService/airflow/AirflowRESTClientIntegrationTest.java
Fixes #15251 
also adding back the executions of non `*ResourceTest.java` files, since they were removed
#
#
=> #15251 - Fix overwriting of airflow path segments

ingestion/src/metadata/cli/db_dump.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/15366 (partially)
#
#
=> Fixes #15366: add profiler_data_time_series to TABLES_DUMP_ALL

openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightProvider.tsx
Fixes #15403 
fixed team filter selection
https://github.com/open-metadata/OpenMetadata/assets/71748675/61b5ca28-bc91-4871-864f-27a1f79afacf
#
#
=> #15403 Team filter on the Data Insights page doesn't work as expected

openmetadata-service/src/main/java/org/openmetadata/service/Entity.java, openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
Makes Dao Return a generic type based on return
#
#
=> Add Dao Get Call based on type

openmetadata-docs/content/v1.3.x/deployment/kubernetes/gke.md
I worked on fixing the broken link on [this](https://docs.open-metadata.org/v1.3.x/deployment/kubernetes/gke) docs page
#
#
=> Docs: Fix the wrong link on kubernetes gke page in the documentation

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/EventAlertProducer.java, openmetadata-service/src/main/java/org/openmetadata/service/events/ChangeEventHandler.java, openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionScheduler.java, openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- Use where before listing
#
#
=> [Perf Fix] Use Where clause on change event listing

ingestion/src/metadata/ingestion/source/database/mssql/queries.py, ingestion/src/metadata/ingestion/source/database/mssql/utils.py
Partially Fixes ISSUE-13473
Modified the join to `sys.extended_properties` on MSSQL for column descriptions to make sure it only retrieves the column or table information. Previously it would pick up other related descriptions like indexes, foreign keys etc.
Ive manually tested locally. I'm not sure how I could add unit/integration tests for this change
=> Fixes ISSUE-13473: Ensure MSSQL columns query filters to tables and views

openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/index.ts, openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/TableMenu/TableMenu.tsx, openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/block-editor.less
I worked on fixing the issue "table is not scrollable in block editor"
https://github.com/open-metadata/OpenMetadata/assets/59080942/21a18bb0-4e4f-45d9-b420-6c64763f129e
#
#
=> Minor: add wrapper for table in block editor to make it scrollable

ingestion/src/metadata/utils/credentials.py, ingestion/tests/unit/test_credentials.py, openmetadata-docs/content/v1.2.x/connectors/database/bigquery/yaml.md, openmetadata-spec/src/main/resources/json/schema/security/credentials/gcpCredentials.json, openmetadata-spec/src/main/resources/json/schema/security/credentials/gcpExternalAccount.json, openmetadata-spec/src/main/resources/json/schema/security/credentials/gcpValues.json
Fixes #14169: Suuport external_account type for GCP Auth 
Currently, the only gcp credentials that can be written in yaml are those with a type of service_account.
I want to use OIDC (external_account) authentication for ingestion, so I will add a configuration for that.
#
#
=> #14169: Support external_account type for GCP Auth

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
Fixes column index when exporting table entity metadata
#
#
Bug fix
=> FIX: index in CSV export for table entities

openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.ts
Fixes the Glossary Term not fetching the owner and auto completing on the Create Task flow.
Complements the prior PR:  https://github.com/open-metadata/OpenMetadata/pull/15535
#
#
=> MINOR: Fix glossary term not fetching owner when creating task

openmetadata-ui/src/main/resources/ui/cypress/common/AlertUtils.ts, openmetadata-ui/src/main/resources/ui/cypress/common/Utils/AdvancedSearch.ts, openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Owner.ts
I worked on improving the SingleFiledSearch, GlossaryVersion and NotificationAlert cypress tests to avoid flakiness
#
#
=> Minor: Cypress improvements for AUT failure fixes

openmetadata-docs/content/v1.3.x/deployment/kubernetes/values.md
Removing `openmetadata.config.airflow.host` helm values as it's not supported anymore.
Ref: https://github.com/open-metadata/openmetadata-helm-charts/issues/225
#
#
=> Docs: fix helm values documentation

openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/Users.component.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/Users.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/Users.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileRoles/UserProfileRoles.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileRoles/UserProfileRoles.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileRoles/UserProfileRoles.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileTeams/UserProfileTeams.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileTeams/UserProfileTeams.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileTeams/UserProfileTeams.test.tsx, openmetadata-ui/src/main/resources/ui/src/context/PermissionProvider/PermissionProvider.tsx, openmetadata-ui/src/main/resources/ui/src/pages/UserPage/UserPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/UserPage/UserPage.test.tsx
- I worked on fixing reloading of user profile page after any edit action perform
Issue : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/bf548da8-f19d-47aa-bf24-006831a3213f
Resolved : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/53fe5cf9-bb4c-46ec-89d0-774992babae9
#
#
=> fix reloading of user profile page on edit action perform

openmetadata-docs/content/v1.3.x/deployment/kubernetes/aks.md, openmetadata-docs/content/v1.4.x-SNAPSHOT/deployment/kubernetes/aks.md
Rel to https://github.com/open-metadata/OpenMetadata/issues/15321
#
#
=> MINOR - AKS Airflow troubleshooting docs

ingestion/src/metadata/data_quality/validations/table/base/tableCustomSQLQuery.py
Fixes Text to show threshold as part of the result status
#
#
=> MINOR: Modify and add threshold as status

bootstrap/sql/migrations/native/1.4.0/mysql/postDataMigrationSQLScript.sql, bootstrap/sql/migrations/native/1.4.0/postgres/postDataMigrationSQLScript.sql, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java, openmetadata-service/src/main/resources/json/data/tests/columnValueMaxToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValueMeanToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValueMedianToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValueMinToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValueStdDevToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValuesLengthsToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValuesSumToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/columnValuesToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/tableColumnCountToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/tableRowCountToBeBetween.json, openmetadata-service/src/main/resources/json/data/tests/tableRowInsertedCountToBeBetween.json, openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestDefinitionResourceTest.java, openmetadata-spec/src/main/resources/json/schema/tests/testDefinition.json
Fixes #13475 
- Add parameter validation for min/max tests.
⚠️ if the parameter value cannot be parsed to a double, we'll skip the validation entirely.
#
#
Improvement
=> FIX #13475 - Add Parameter Validation for Min/Max tests

ingestion/src/metadata/ingestion/source/database/postgres/metadata.py
The ingestion framework pops up some warning due to SQLAlchemy not having a proper mapping for the [`xid`](https://www.postgresql.org/docs/current/datatype-oid.html) and [`bpchar`](https://www.postgresql.org/docs/current/datatype-character.html) types.
In order to avoid this we are adding a mapping to the `String` type that is the closest one that makes sense.
- https://github.com/sqlalchemy/sqlalchemy/issues/5728
- https://github.com/sqlalchemy/sqlalchemy/discussions/8592
#
#
=> MINOR: Add mapping for xid and bpchar for postgresql

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java, openmetadata-spec/src/main/resources/json/schema/configuration/profilerConfiguration.json, openmetadata-spec/src/main/resources/json/schema/settings/settings.json
Add Global config for the profiler allowing admin to set globally the metrics to be computed based on the dtype or to completely disanle metric computation for a specific dtype
#
#
Improvement
=> Fix #11951 [backend] - Implement Profiler Global Config

ingestion/src/metadata/ingestion/lineage/models.py, ingestion/src/metadata/ingestion/lineage/parser.py, ingestion/src/metadata/ingestion/lineage/sql_lineage.py, ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py, ingestion/src/metadata/workflow/output_handler.py
Fix #15208: Lineage - log query parsing issue summary
#
#
=> Fix #15208: Lineage - log query parsing issue summary

openmetadata-ui/src/main/resources/ui/src/utils/LogsClassBase.ts
Update LogsClassBase.ts to convert `getLogBreadCrumbs` method from arrow function to regular function for ability to modify the public method.
#
#
=> Minor: Logs class base update

ingestion/src/metadata/ingestion/source/dashboard/qliksense/client.py, ingestion/src/metadata/utils/ssl_manager.py, openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/dashboard/qliksense/index.md, openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/dashboard/qliksense/yaml.md, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/dashboard/qlikSenseConnection.json, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Dashboard/QlikSense.md
Fix #14973: Qliksense - Add option to disable hostname validation
#
#
=> Fix #14973: Qliksense - Add option to disable hostname validation

ingestion/src/metadata/data_quality/validations/column/sqlalchemy/columnValuesToBeUnique.py, ingestion/src/metadata/profiler/metrics/static/unique_count.py, ingestion/tests/integration/profiler/conftest.py
Fixes #15660 
- move computation of unique and count in the same query
#
#
Bug fix
Improvement
=> Fixes #15660 - Compute unique and count at the same time

ingestion/src/metadata/ingestion/source/database/mssql/queries.py
I rewrote the query that gets stored procedures from ms sql and its definitions.
Because i found out that openmetadata 1.3.0 cant get more than 4000 symbols of stored procedure definition
I have replaced one file in our docker image and ran ingestion. There were not any changes except stored procedure definition being fully loaded.
#
- [1] Bug fix
#
- [1] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.
At first I thought that I had broken the metadata ingestion because it took quite a long time to complete, but then I realized that this was obviously due to the increased amount of …
=> issue-15607(3-rd try)

ingestion/src/metadata/ingestion/source/database/trino/metadata.py, ingestion/src/metadata/profiler/orm/functions/sum.py
Fixes #15776
I worked on fixing numeric out of value for value bigger than bigint.
#
#
=> Minor: Fixes #15776 Numeric out of value error Trino

openmetadata-ui/src/main/resources/ui/src/components/AppContainer/AppContainer.tsx, openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AppRouter.tsx, openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AuthenticatedAppRouter.tsx, openmetadata-ui/src/main/resources/ui/src/components/AppRouter/UnAuthenticatedAppRouter.tsx, openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OidcAuthenticator.tsx
This PR will fix the issue of the 404-page layout and will only show the 404-page content without the header and sidebar.
#
#
=> fix: 404 page layout

ingestion/src/metadata/ingestion/source/storage/s3/metadata.py
The error message was referring to `S3StoreConnection` which does not exist. Rather, it should be `S3Connection`.
I worked on fixing this small typo because I was reading the code 🤓 
#
#
=> MINOR: Fix error message in S3Source

ingestion/src/metadata/workflow/base.py
Set Ingestion pipeline status before waiting on the test connection init from the source
#
#
=> MINOR - Set pipeline status early

ingestion/src/metadata/profiler/processor/metric_filter.py, ingestion/tests/integration/profiler/test_sqa_profiler.py
The Profiler global settings is not mapping properly SQLAlchemy Types to OM Types.
This PR aims to solve this issue.
#
#
=> MINOR: Fix issue with SQLAlchemy types not being correctly mapped to OM Type on the profiler

openmetadata-spec/src/main/resources/json/schema/email/smtpSettings.json, openmetadata-ui/src/main/resources/ui/src/components/Settings/Email/EmailConfigForm/EmailConfigForm.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Email/EmailConfigForm/EmailConfigForm.test.tsx
I worked on making the password and username fields non-required in the email config form.
#
#
=> Minor: make password and username field non required in email config form

ingestion/src/metadata/ingestion/source/storage/s3/metadata.py
Fixes an issue of duplicated code in `S3Source.get_containers`.
I initially thought I was blind in that I did not see the difference between `_generate_structured_containers` and the for loop below it. Turns out the code was indeed identical!
The commit 5d8457b597dfc2e38aebce4431f0798798cf492a (#12017) introduced `_generate_structured_containers` which refactored the `for metadata_entry in metadata_config.entries` loop etc, but it looks like the original implementation was left in place.
This PR simply removes the duplicated code (and reuses the `manifest_entries_for_current_bucket` in the block above).
=> MINOR: Remove duplicated code in S3Source

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/TreeAsyncSelectList.tsx, openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.tsx
- I worked on fixing the glossary terms not showing when the expand click
Issue :   
https://github.com/open-metadata/OpenMetadata/assets/66266464/e934615d-2450-48db-a94d-208b5e9eb06b
Resolved : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/2bc0b34c-a56c-4c51-88f8-321d441467b0
#
#
=> fix the glossary terms not showing when expand click

openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AppRouter.tsx, openmetadata-ui/src/main/resources/ui/src/components/AppRouter/UnAuthenticatedAppRouter.tsx, openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/BasicAuthAuthenticator.tsx, openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/GenericAuthenticator.tsx, openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OidcAuthenticator.tsx, openmetadata-ui/src/main/resources/ui/src/components/Auth/AppCallbacks/Auth0Callback/Auth0Callback.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Auth/AppCallbacks/Auth0Callback/Auth0Callback.tsx, openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx, openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/OktaAuthProvider.tsx, openmetadata-ui/src/main/resources/ui/src/hooks/useApplicationStore.ts, openmetadata-ui/src/main/resources/ui/src/interface/store.interface.ts, openmetadata-ui/src/main/resources/ui/src/pages/SignUp/SignUpPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/SignUp/SignUpPage.tsx
I worked on adding isApplicationLoading in isApplicationLoading to show the loader at the application level when the application is in a loading state which could be fetching config or fetching logged-in user details.
Tested Provider
- Google (confidential and public both)
- Okta
- Auth0
- Basic
- LDAP
- Saml
- Azure
- Saml
#
#
=> minor: add isApplicationLoading state in ApplicationStore

openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/common.py, openmetadata-airflow-apis/tests/unit/test_helpers.py
Fixes failing AUTs due to test suite deployment with long names
#
#
=> FIX - Airflow tagging long names

openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/common.py, openmetadata-airflow-apis/tests/unit/test_helpers.py
Fixes tag clashes if name/type/service are the same
#
#
=> MINOR - Airflow dag_tag PK

openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetAsyncSelectList/DataAssetAsyncSelectList.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetAsyncSelectList/DataAssetAsyncSelectList.tsx
Earlier we were sending queries like this which caused the issue we were only getting back the user and team results.
```
q: * AND isBot:false
index: user,tag,searchIndex,team,database
from: 0
size: 10
```
To fix the issue now we will be using query_filter to filter out the bots
```
query_filter: {"query":{"bool":{"must_not":[{"match":{"isBot":true}}]}}}
```
https://github.com/open-metadata/OpenMetadata/assets/59080942/ce9116b6-7b04-4770-8f9f-ca27e57645dc
#
#
=> Minor: add query_filter for filtering bots

openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
Fixes #10502
#10502 Show dbt node fields in the UI
I've made changes to display the dbt tab for rawSql, even when the SQL query is empty. Additionally, I've added unit tests for these modifications.
Scenario Checked:
- When there is SQL and rawSql present, the SQL query is displayed in the DBT tab.
- When SQL is empty or not present but rawSql is present, the rawSql is displayed in the DBT tab.
- When both SQL and rawSql are not present, the DBT tab is not displayed.
#
#
=> #10502 Show dbt node fields in the UI

ingestion/src/metadata/ingestion/source/pipeline/openlineage/metadata.py
OpenLineage ingestion wasn't updated to include changes from #15201 and #15130. Ingestion failed with errors like:
```
[2024-05-24, 15:14:18 UTC] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
return_value = self.execute_callable()
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
return self.python_callable(*self.op_args, **self.op_kwargs)
File "/home/airflow/.local/lib/python3.10/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 207, in metadata_ingestion_workflow
workflow = MetadataWorkflow.create(config)
File …
```
=> Fix OpenLineage ingestor

openmetadata-docs/content/partials/v1.3/connectors/yaml/workflow-config.md, openmetadata-docs/content/partials/v1.4/connectors/yaml/workflow-config-def.md, openmetadata-docs/content/partials/v1.4/connectors/yaml/workflow-config.md, openmetadata-docs/content/v1.4.x/connectors/database/doris/index.md, openmetadata-docs/content/v1.4.x/connectors/database/greenplum/index.md, openmetadata-docs/content/v1.4.x/connectors/database/greenplum/yaml.md, openmetadata-docs/content/v1.4.x/connectors/database/mysql/index.md, openmetadata-docs/content/v1.4.x/connectors/database/pinotdb/index.md, openmetadata-docs/content/v1.4.x/connectors/database/postgres/index.md, openmetadata-docs/content/v1.4.x/connectors/database/postgres/yaml.md, openmetadata-docs/content/v1.4.x/connectors/database/redshift/yaml.md, openmetadata-docs/content/v1.4.x/connectors/pipeline/openlineage/index.md, openmetadata-docs/content/v1.4.x/deployment/ingestion/external/index.md, openmetadata-docs/content/v1.4.x/deployment/ingestion/openmetadata.md, openmetadata-docs/content/v1.4.x/deployment/security/enable-ssl/ssl-troubleshooting.md, openmetadata-docs/content/v1.4.x/developers/contribute/developing-a-new-connector/define-json-schema.md, openmetadata-docs/content/v1.4.x/main-concepts/metadata-standard/schemas/entity/services/connections/database/mysqlConnection.md, openmetadata-docs/content/v1.4.x/main-concepts/metadata-standard/schemas/security/ssl/validateSSLClientConfig.md
Modify the documentation for SSL
Worked on adding modifications for SSL.
#
#
=> Documentation: Add SSL related modifications

bootstrap/sql/migrations/native/1.4.2/mysql/postDataMigrationSQLScript.sql, bootstrap/sql/migrations/native/1.4.2/postgres/postDataMigrationSQLScript.sql
How was it tested locally:
for postgres and MySQL:
1. ingested a redshift service with tables with KEY and EVEN diststyle
2. migrated from 1.3.4 -> 1.4.0 and validated JSON parse error
3. migrated from 1.4.0 -> 1.4.2 and validated JSON parse error was fixed (i.e. the hanging `tablePartition` key was removed)
#
#
=> [MINOR] partition migration issue with redshift servics

openmetadata-spec/src/main/resources/json/schema/entity/data/glossary.json, openmetadata-spec/src/main/resources/json/schema/entity/data/glossaryTerm.json
Fixes 13814
I checked that all the entities have DataProduct support where the domain is present, except for Glossary and GlossaryTerm.
#
#
=> Fixes 13814 - Added DataProduct support for Glossary and GlossaryTerm.

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
Fixes #16322
- Delete results on hard deletion of test case
#
#
Bug fix
=> Fixes #16322 - Delete results on test case hard deletion

openmetadata-ui/src/main/resources/ui/playwright/constant/delete.constant.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityClass.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/entityUtils.ts
playwright: migrate announcement, rename, soft delete and hard delete test
#
#
=> playwright: migrate announcement, rename, soft delete and hard delete test

openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx
Fixes #16525
- I worked on fixing owner not showing after refresh in teams page
https://github.com/open-metadata/OpenMetadata/assets/66266464/f59dea63-f861-48fe-a790-fdb5a0f840d8
#
#
=> MINNOR: fix owner not showing after refresh in teams page

ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py, ingestion/src/metadata/ingestion/source/dashboard/metabase/models.py, ingestion/src/metadata/ingestion/source/dashboard/redash/metadata.py, ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
Fixes
```
E           metadata.ingestion.connections.test_connections.SourceConnectionException: Some steps failed when testing 
the connection: [failed=["'GetDashboards': This is a mandatory step and we won't be able to extract neces***ry 
metadata. Failed due to: 1 validation error for MetabaseCollectionList\ncollections.1.id\n  Input should be a valid string 
[type=string_type, input_value=1, input_type=int]\n    For further information visit 
[https://errors.pydantic.***/2.7/v/string_type](https://errors.pydantic.%2A%2A%2A/2.7/v/string_type)"] success=[] 
warning=[]]
```
```
1 validation error for EntityName
E             Input should be a valid string [type=string_type, input_value=5, input_type=int]
E               For further information visit …
```
=> FIX - e2e test for pydantic v2

ingestion/src/metadata/ingestion/source/database/iceberg/catalog/rest.py, ingestion/src/metadata/ingestion/source/database/iceberg/helper.py, ingestion/src/metadata/ingestion/source/database/iceberg/metadata.py, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/iceberg/restCatalogConnection.json
Fixes [16595](https://github.com/open-metadata/OpenMetadata/issues/16595)
Pass the Iceberg table identifier tuple to the [get_table_name_as_str() helper function](https://github.com/open-metadata/OpenMetadata/blob/1.4.1-release/ingestion/src/metadata/ingestion/source/database/iceberg/helper.py#L40-L47) to ensure the namespace/schema is properly stripped. 
Tables loaded using pyiceberg's [catalog.load_table()](https://github.com/open-metadata/OpenMetadata/blob/1.4.1-release/ingestion/src/metadata/ingestion/source/database/iceberg/metadata.py#L180) including the catalog name in the table identifier, whereas the [catalog.list_tables()](https://github.com/open-metadata/OpenMetadata/blob/1.4.1-release/ingestion/src/metadata/ingestion/source/database/iceberg/metadata.py#L178) does not. So the …
=> Fixes 16595: Parse Iceberg REST table FQN from identifier

openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamsSelectable/TeamsSelectable.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamsSelectable/TeamsSelectable.tsx
I worked on fixing the no teams alert showing all the time on signup page 
**Before:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/a68fdb31-9946-4015-b047-c6e684049a5b
**After:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/b53ab51d-a14f-446a-b657-2bb7edf23c25
#
#
=> Minor: Fix incorrect alert on signup page

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/GlossaryVersionPage.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/constant/version.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/GlossaryVersionPage.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityClass.ts, openmetadata-ui/src/main/resources/ui/playwright/support/glossary/Glossary.ts, openmetadata-ui/src/main/resources/ui/playwright/support/glossary/GlossaryTerm.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
playwright: migrate glossary version page spec
#
#
=> playwright: migrate glossary version page spec

ingestion/src/metadata/ingestion/source/database/db2/metadata.py
Fixes an issue where BOOLEAN type is not correctly parsed on DB2 Connector
#
#
=> MINOR: Update ischema_names for db2 to take BOOLEAN into account

ingestion/src/metadata/examples/workflows/salesforce.yaml, ingestion/src/metadata/ingestion/source/database/salesforce/connection.py, ingestion/src/metadata/ingestion/source/database/salesforce/metadata.py, ingestion/src/metadata/utils/ssl_manager.py, ingestion/tests/unit/topology/database/test_salesforce.py, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/salesforce/index.md, openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java, openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/SalesforceConnectorClassConverter.java, openmetadata-service/src/test/java/org/openmetadata/service/secrets/converter/ClassConverterFactoryTest.java, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/salesforceConnection.json, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Salesforce.md
Add Support for Salesforce SSL
I worked on implementing / allowing salesforce connection using ssl
#
#
=> #16720: Add Support for Salesforce SSL

openmetadata-ui/src/main/resources/ui/cypress/common/Entities/UserClass.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts
Issue : 
-  Not able to find edit description button due to userProfilePanel was closed.   
-  collapsible panel was already open and we have closed it causing the issue
Resolved :
- Remove the unwanted code to open the collapsible panel as it was already open.
#
#
=> CYPRESS: fix user cypress failure

openmetadata-airflow-apis/openmetadata_managed_apis/operations/deploy.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/application.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/data_insight.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/profiler.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/test_suite.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/usage.py
With the Pydantic v2 migration our `model_dump_json` sets `exclude_defaults=True` as a default.
This is breaking the Profile workflow if configured through the UI.
In order to fix it I'm explicitely passing `exclude_defaults=False` but we should discuss if we should change the default behaviour of the method.
#
#
=> MINOR: added exclude_defaults=False for profiler and deploy on airflow-apis

ingestion/src/metadata/ingestion/source/database/db2/metadata.py
Removing custom `get_pk_constraint` method that disabled Primary Keys on DB2 after testing it with:
- One Primary Key
- Multiple Primary Key
- No Primary Key
The ingestion was successfull without any issues or warnings/errors on the log in DEBUG mode
#
#
=> MINOR: Enable Primary Key Constraint for DB2

ingestion/src/metadata/ingestion/ometa/mixins/custom_property_mixin.py, ingestion/tests/integration/ometa/test_ometa_custom_properties_api.py
Add method to list custom properties for a entity for python sdk
#
#
=> MINOR: Add method to list custom properties for a entity for python sdk

ingestion/src/metadata/ingestion/source/database/datalake/metadata.py
Fixes Return Type Annotation warning on Datalake avoiding any errors 
#
#
=> Minor: Fix return type annotation

ingestion/src/metadata/ingestion/lineage/sql_lineage.py, ingestion/tests/integration/postgres/bad_query_log.csv, ingestion/tests/integration/postgres/test_postgres.py
When lineage ingestion fails due to missing tables, it is not captured by the workflow. This change changes that to capture missing table errors and report them to the user. This is important because it might result in:
1. user error of choosing the wrong query log or service.
2. error with the query parser.
#
#
=> MINOR: raise lineage error when table does not exist

openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java
In [this thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1718753793799799?thread_ts=1717612791.169119&cid=C02B6955S4S) we discovered that it was impossible to toggle an airflow pipeline back on after it was paused without manually editing the Openmetadata database. After some code reviewing, it was found that there was a bug in the code for the state change from "paused" to "unpaused" which would cause the Openmetadata service to become out-of-sync with the underlying Airflow process.
This should resolve the issue.
Thank you to @ulixius9 and @harshach for the suggestion to submit a PR!
=> Fix Airflow Pipeline Toggle On

ingestion/src/metadata/utils/filters.py, ingestion/tests/unit/test_filter_pattern.py
=> #10192 - Validate both include and excludes filters

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityDataClass.ts, openmetadata-ui/src/main/resources/ui/playwright/support/tag/TagClass.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/tag.ts, openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/AsyncSelectList.tsx, openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx, openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx, openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.test.tsx, openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
Fixes #16742 
https://github.com/open-metadata/OpenMetadata/assets/12962843/bff05cb7-0b3e-43fe-9650-c7726a8939f4
#
#
=> Fix: #16742 - allow all the tier tags to be assign on entity 

openmetadata-service/src/main/java/org/openmetadata/service/search/SearchIndexUtils.java
Fixes #16906
Lineage -> Pipeline was being removed in Non Indexable Fields
#
#
=> [Issue-16906] Fix Lineage Edge Being Removed in Non-Indexable Fields

ingestion/src/metadata/ingestion/source/pipeline/openlineage/connection.py, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/pipeline/openLineageConnection.json, openmetadata-spec/src/main/resources/json/schema/security/sasl/saslClientConfig.json, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/OpenLineage.md
Fixes [16582](https://github.com/open-metadata/OpenMetadata/issues/16582).
Update OpenLineage pipeline connector config to support `SASL_SSL` kafka client connections, for use with e.g. [Confluent Cloud](https://docs.confluent.io/kafka-clients/python/current/overview.html#id1) kafka clusters.
#
#
=> Fixes 16582: support SASL_SSL kafka auth for OpenLineage pipeline connector

openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/block-editor.less
I worked on fixing the warning for justify-content property
#
#
=> chore: fix justify-content property warning in BlockEditor component

bootstrap/sql/migrations/native/1.4.5/mysql/schemaChanges.sql, bootstrap/sql/migrations/native/1.4.5/postgres/schemaChanges.sql, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityTimeSeriesDAO.java
Fixes #16788
Improved existing query performances
#
#
=> Fixes #16788 : Fix feed and count api query performance

ingestion/src/metadata/profiler/metrics/static/mean.py, ingestion/src/metadata/profiler/orm/functions/sum.py, ingestion/tests/cli_e2e/test_cli_redshift.py
Fixes #16697 
I worked on fixing Numeric Data Overflow for Redshift
#
#
=> Fixes #16697: Modify the Query to avoid Numeric Data Overflow

openmetadata-service/src/main/java/org/openmetadata/csv/EntityCsv.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- This PR fixes the backend issue on validation in importing a CSV
- Pending Fix from the UI side for "" on empty cells
#
#
=> [Issue-16973] Fix Issue in Import TableCsv

openmetadata-docs/content/v1.4.x/connectors/database/snowflake/index.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/snowflake/index.md
Small improvement to the Snowflake documentation to make clear that an extra permission is needed when using Incremental Extraction.
#
#
=> MINOR: Update Snowflake docs to better inform the needed permissions

ingestion/tests/cli_e2e/test_cli_vertica.py
Vertica E2E Tests were failing due to the State of the Database changing. With @pmbrull's help we restarted the Database to its initial state while also adjusting the expected values.
In the near future it'd be great if we could move this to be an Integration test with TestContainers. It should be farily easy since in order to setup the Database the only thing needed is to spin up a docker container:
```bash
docker run -p 5433:5433 -p 5444:5444 --mount type=volume,source=vertica-data,target=/data --name vertica_ce vertica/vertica-ce
```
It already comes with the default Vmart database setup.
The only thing we could do is to update to a newer image version if needed.
#
#
=> MINOR: Fix Vertica E2E Counts

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AlertFactory.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/Destination.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/email/EmailPublisher.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/feed/ActivityFeedPublisher.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/gchat/GChatPublisher.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/generic/GenericPublisher.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/msteams/MSTeamsPublisher.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/slack/SlackEventPublisher.java, openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/EmailMessageDecorator.java, openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/FeedMessageDecorator.java, openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/GChatMessageDecorator.java, openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MSTeamsMessageDecorator.java, openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java, openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/SlackMessageDecorator.java, openmetadata-service/src/main/java/org/openmetadata/service/util/EmailUtil.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/events/EventSubscriptionResourceTest.java
=> Add Alert Name to Publishers

openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/TestSummaryGraphUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/TestSummaryGraphUtils.ts
issue: area graph throwing undefined error due to inaccurate data.
before:
after:
#
#
=> Minor: fixed testSummaryGraph issue

openmetadata-docs/content/v1.3.x/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md, openmetadata-docs/content/v1.3.x/connectors/metadata/alation/index.md, openmetadata-docs/content/v1.3.x/connectors/metadata/alation/yaml.md, openmetadata-docs/content/v1.4.x/connectors/database/bigquery/create-credentials.md, openmetadata-docs/content/v1.4.x/connectors/database/bigquery/yaml.md, openmetadata-docs/content/v1.4.x/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md, openmetadata-docs/content/v1.4.x/connectors/metadata/alation/index.md, openmetadata-docs/content/v1.4.x/connectors/metadata/alation/yaml.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/bigquery/create-credentials.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/bigquery/index.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/bigquery/yaml.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/metadata/alation/index.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/metadata/alation/yaml.md
I worked on links fix in docs
#
#
=> MINOR: docs links fix

ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
=> MINOR: Databricks view TableType fix

ingestion/src/metadata/profiler/orm/functions/datetime.py, ingestion/src/metadata/workflow/output_handler.py, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/BigQuery.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Clickhouse.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Db2.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Greenplum.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Hive.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Impala.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/MariaDB.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Mssql.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Mysql.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Oracle.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Postgres.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Presto.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Redshift.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/SapHana.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/SingleStore.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Snowflake.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Teradata.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Trino.md, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/NoProfilerBanner/NoProfilerBanner.component.tsx, openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts
#17120
Updating Profiler Workflow Docs URL
#
#
=> Doc: Updated Profiler Workflow Docs URL

scripts/check_prerequisites.sh
added support for docker 20-29
#
#
=> MINOR: fix docker versions to prerequisites scripts

ingestion/Makefile, ingestion/operators/docker/Dockerfile.ci, ingestion/pyproject.toml, openmetadata-airflow-apis/pyproject.toml
=> MINOR: Bump Setuptools version

ingestion/Dockerfile, ingestion/Dockerfile.ci, ingestion/Makefile, ingestion/constraints.txt, openmetadata-airflow-apis/constraints.txt, openmetadata-airflow-apis/pyproject.toml
- Aligned ingestion image constraints to properly use 2.9.1
- In CI we weren't applying the right constraints
- Aligned the airflow APIs to work the new Airflow constraints
- Setuptools yanked the faulty release and we don't need the custom constraint anymore
#
#
=> FIX - Ingestion Airflow Image constraints

openmetadata-ui/src/main/resources/ui/src/utils/IngestionWorkflowUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/IngestionWorkflowUtils.ts
I worked on updating the metadata service ingestion form configuration fields. The `Configure Ingestion` step for metadata services had no fields earlier. I've used the database services JSON schema for the same. cc. @OnkarVO7 
https://github.com/user-attachments/assets/386393a0-370c-45a2-aae1-f5f2442a2990
#
#
=> Minor: Update the metadata service ingestion form configuration fields

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsApp.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/DataInsightsSearchInterface.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/elasticsearch/ElasticSearchDataInsightsClient.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/opensearch/OpenSearchDataInsightsClient.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java, openmetadata-service/src/main/resources/json/data/app/DataInsightsApplication.json, openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/DataInsightsApplication.json, openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/internal/dataInsightsAppConfig.json, openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/DataInsightsApplication.json
Since all Entities store CustomProperties as `extension` and can have name collision while having different types, we decided to change the attribute for which we are storing them for DataInsights based on the EntityType.
We also implemented the possibility of recreating the Data Assets Data Stream on the configuration.
#
#
=> MINOR: Update Data Insights Pipeline to change CustomProperty key based on entityType

openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v150/Migration.java
Migrate Policies never called for postgres, causing migration to fail for EditOwner -> EditOwners
#
- [ x] Bug fix
#
=> Minor: Fix Postgres missing policy rule migrations for EditOwners

openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
In order to retrieve the ingestionPipelineStatus we were requireing the `EditAll` Permission.
This PR changes this permission to `ViewAll`.
#
#
=> MINOR: Fix permission for getPipelineStatus

ingestion/src/metadata/ingestion/source/database/databricks/lineage.py, ingestion/src/metadata/ingestion/source/database/databricks/usage.py
TableQuery `startTime` and `endTime` are defined as `str`. Here we force the result from databricks into `str` to fix `lineage` and `usage` pipeline.
#
#
=> MINOR: Fix Databricks TableQuery timestamps to str

ingestion/src/metadata/ingestion/source/database/databricks/metadata.py, ingestion/src/metadata/ingestion/source/database/databricks/queries.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/client.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/metadata.py
=> Fix #16573: get table owners for databaricks & unitycatalog tables

ingestion/src/metadata/ingestion/source/database/oracle/metadata.py, ingestion/src/metadata/ingestion/source/database/oracle/queries.py, ingestion/src/metadata/ingestion/source/database/oracle/utils.py, ingestion/src/metadata/profiler/orm/functions/table_metric_computer.py, openmetadata-docs/content/v1.4.x/connectors/database/oracle/index.md, openmetadata-docs/content/v1.4.x/connectors/database/oracle/yaml.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/oracle/index.md, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/oracle/yaml.md, openmetadata-service/src/main/resources/json/data/testConnections/database/oracle.json
Based on discussions we decided to go back to using `DBA` tables for Oracle.
This PR aims to tackle that plus fixing some missing queries that were still using `ALL`
#
#
=> Updated oracle to use DBA_ tables

openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnectionModal/TestConnectionModal.tsx, openmetadata-ui/src/main/resources/ui/src/constants/EmailConfig.constants.ts, openmetadata-ui/src/main/resources/ui/src/pages/EmailConfigSettingsPage/EmailConfigSettingsPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.tsx
- Fix the long text in tag or glossary tags, used in entity
- Remove the `template` field data from the EmailConfigutation Page
- Fix the overflow scroll to right in Test connection model
- Hide the `AddClassification` button in case of no create permission like Glossary
Issue : 
Fixed : 
https://github.com/user-attachments/assets/4a20ba88-eac6-4753-a40b-141147ec1185
#
#
=> MINOR: ui improvement

ingestion/Dockerfile, ingestion/Dockerfile.ci, ingestion/operators/docker/Dockerfile, ingestion/operators/docker/Dockerfile.ci, openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/db2/index.md
We were not installing the ODBC driver on the images for x86_64 architectures. This PR aims to fix it by having it installed as default and it also improves minorly the documentation.
#
#
=> MINOR: Install DB2 odbc driver on x86_64 architectures and update docs

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
Data Insights is getting the fields from just the first index found.
Now that we are using MultiIndexes, we need to iterate through all
=> MINOR: Fix DataInsights Field Getter

ingestion/src/metadata/ingestion/source/database/common_db_source.py, openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
=> MINOR: Make Include ddl disabled by default 1.4.7

ingestion/src/metadata/cli/app.py, ingestion/src/metadata/cli/dataquality.py, ingestion/src/metadata/cli/ingest.py, ingestion/src/metadata/cli/profile.py, ingestion/src/metadata/cli/usage.py, ingestion/src/metadata/ingestion/ometa/mixins/ingestion_pipeline_mixin.py
=> MINOR - Clean DEBUG logs

openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/snowflakeConnection.json
Decided to turn `Transient table ingestion` opt-out instead of opt-in in order to allow the users to have all their tables ingested as default and opt-out as they need.
#
#
=> MINOR: Make Transient table ingestion On by default

ingestion/src/metadata/ingestion/source/database/db2/metadata.py
Fixes #16942 
Strips right whitespace from schema names.
#
#
=> FIXES 16942: DB2 Schema Trailing Whitespaces

ingestion/Dockerfile, ingestion/Dockerfile.ci, ingestion/operators/docker/Dockerfile, ingestion/operators/docker/Dockerfile.ci
Fix to add db2 dependency out of the box on amd64 architectures
#
#
=> MINOR: Install db2 dependency on amd64 architectures

ingestion/src/metadata/profiler/processor/default.py, ingestion/src/metadata/profiler/source/base/profiler_source.py
- `db_service` was not passed when instantiating metrics for default profiler
#
You should choose 1 option and delete options that aren't relevant -->
#
=> FIX GEN-1161: db_service not passed to metric instantiation

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py, ingestion/tests/unit/topology/database/test_bigquery.py
Fixes #17461 
- What:  Unquote and interpret escaped characters in BigQuery dataset description
- Why: The query result from BigQuery includes double quote and converts `\` -> `\\`
- How: Using `ast.literal_eval`
#
#
=> Fixes #17461: Unquote and interpret escaped characters in BigQuery dataset description

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchDynamicChartAggregatorInterface.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchDynamicChartAggregatorInterface.java, openmetadata-spec/src/main/resources/json/schema/dataInsight/custom/dataInsightCustomChart.json
Our Data Insights Application didn't have a Unique Count function present. This hindered a lot of possibilities since anything that wasn't a `leaf` entity would be repeated n times (Such as Service Id).
This PR aims to add the Unique Count functionality by using the `cardinality` aggregation from ElasticSearch
#
#
=> MINOR: Add unique count to data insights

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchLineChartAggregator.java, openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchSummaryCardAggregator.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchLineChartAggregator.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchSummaryCardAggregator.java
When the Search Repository returns an empty aggregation an error is thrown.
This PR aims to fix that by handling that scenario gracefully
#
#
=> MINOR: Handle empty aggregations on data insights

ingestion/src/metadata/ingestion/source/database/datalake/clients/gcs.py, ingestion/src/metadata/ingestion/source/database/datalake/metadata.py
This fixes the below error faced for datalake gcs
AttributeError: 'DatalakeGcsClient' object has no attribute 'project'
#
#
=> MINOR: Fixes AttributeError: 'DatalakeGcsClient' object has no attribute 'project'

openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/teradataConnection.json
Add LDAP option for LOGMECH to use ldap for Teradata connections. This option is described in docs but missing in implementation
=> [MINOR] add support for Teradata LDAP logon mechanism

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
Patch response is not sorting the owners field. This will cause the UI to show out of order owners and any further modifications to the owner field will cause wrong position to be removed.
#
#
=> Patch response should sort the owners field

openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityClass.ts, openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx, openmetadata-ui/src/main/resources/ui/src/utils/DashboardDetailsUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/PipelineDetailsUtils.test.ts
Remove the sorting from UI performed before patch operation.
It was previously added here - https://github.com/open-metadata/OpenMetadata/pull/9055
#
#
=> remove sorting of tags

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
Fixed owner not updating from dbt if owners field has an empty list set in db
#
#
=> MINOR: Fixed owner not updating from dbt if owners field has an empty list set in db

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
Adds Pagination through LIMIT/OFFSET to `listEntityVersions` to avoid bringing a lot of data into memory.
#
#
=> MINOR: Add pagination to entity history versions

openmetadata-ui/src/main/resources/ui/src/styles/app.less
This PR will add spacing for table item actions when floating icons are enabled in the application. These changes will also fix the AUT failure where actions were being blocked by the floating icons.
=> minor: add some spacing for table item action when floating icons are enabled

ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
This issue fix this error on dbt ingestion
```
line 173, in get_dbt_owner
owner = self.metadata.get_reference_by_email(name=dbt_owner)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OMetaUserMixin.get_reference_by_email() got an unexpected keyword argument 'name'
```
passing the right named argument, because name is not an arg of get_reference_by_email,
* there should be enough unit test to cover the behavior of get_reference_by_email
* I didn't find any reference to this issue, when searching the issues.
#
#
=> fix: pass the correct argument to get_reference_by_email for dbt ingestion

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
- Added fqnHash for the term search to handle FQN special chars search and long FQN
#
#
Bug fix
=> Fix: lineage lookup for long FQNs

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/Explore/ExploreTree/ExploreTree.tsx
https://github.com/user-attachments/assets/1d184fad-db7a-4902-9b55-e9e8d39aca8d
#
#
=> Explore tree reset

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/APIEndpointRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
=> Minor: remove unnecessary repository calls in SearchRepository

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/LandingPageWidgets/DataAssetsWidget.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/LandingPageWidgets/FollowingWidget.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/Explore/ExploreQuickFilters.tsx, openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizeMyData/CustomizeMyData.tsx, openmetadata-ui/src/main/resources/ui/src/enums/entity.enum.ts, openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx, openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
- I worked on fixing some entities not visible in Following widget
- added playwright test
Issue : 
Resolved : 
#
#
=> fix some entities not visible in Following widget

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/EntityDataConsumer.spec.ts
I worked on fixing the flakiness in EntityDataConsumer spec
#
#
=> Minor: Remove the EntityDataConsumer spec dependency on organization inherited role

ingestion/src/metadata/pii/processor.py, ingestion/src/metadata/pii/scanners/base.py, ingestion/src/metadata/pii/scanners/column_name_scanner.py, ingestion/src/metadata/pii/scanners/ner_scanner.py, ingestion/tests/unit/pii/test_column_name_scanner.py, ingestion/tests/unit/pii/test_ner_scanner.py
1. Prepare base scanner to keep code organized
2. Check data before parsing to recursively check if it's JSON/list and analyze it properly instead of as a single big string
3. Better testing
4. Rename `SSN` to `US_SSN` to match the NER model from presidio when tagging Entities in Collate
#
#
=> MINOR - Better PII classification for JSON data

ingestion/src/metadata/profiler/orm/functions/count.py, ingestion/src/metadata/profiler/orm/functions/unique_count.py, ingestion/tests/cli_e2e/test_cli_oracle.py
Fixes #17085
I worked on Updating Oracle count & unique count function to handle HexByteString/Blob types
#
#
=> Fixes #17085: Update Oracle count & unique count function to handle HexByteString/Blob types

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/CostAnalysisWorkflow.java
Connection is not a required attribute for a DatabaseService. In order to avoid errors we are removing the dependency on this attribute and checking that the DatabaseServiceType belongs to either Snowflake, Redshift or BigQuery, which are the supported databases for this feature.
Fixes #17730 
#
#
=> FIXES 17730: Remove CostAnalysisWorkflow dependency on Service Connection

ingestion/src/metadata/ingestion/source/database/redshift/metadata.py, ingestion/src/metadata/ingestion/source/database/redshift/queries.py, ingestion/src/metadata/ingestion/source/database/redshift/utils.py
=> MINOR: Fix Redshift View Def regex_replace Error

openmetadata-service/src/main/java/org/openmetadata/service/resources/tags/ClassificationResource.java
=> Fixes #17804: Classification API returns Table class for restore

ingestion/setup.py
spacy 3.8 requires numpy 2.0 which is not compatible with openmetadata-ingestion requirements: https://github.com/explosion/spaCy/commit/184e508d9c8db6fc89c60e5ec8e94324817259c9
#
#
=> MINOR: ci: pin spacy version

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/MyData.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tags.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestSuite.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/support/entity/TableClass.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/myData.ts, openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable/IngestionListTable.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable/IngestionListTable.tsx, openmetadata-ui/src/main/resources/ui/src/styles/app.less
fixed failing playwright test of AUT
- Added fix for MyData spec failure
#
#
=> playwright: fixed failing aut test in main

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Policies.spec.ts, openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/AddRulePage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/AddRulePage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/EditRulePage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/EditRulePage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/PoliciesDetailPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/PoliciesDetailPage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/AddRolePage/AddRolePage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/AddRolePage/AddRolePage.tsx, openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
The issue lies in the way the fields are being passed to the `getPolicyByName` function. The expression inside the template literal is using the comma operator, which only evaluates the last operand. Therefore, only `TabSpecificField.ROLES` is being passed. 
Was introduced in https://github.com/open-metadata/OpenMetadata/pull/17013
```js
const data = await getPolicyByName( fqn, ${ (TabSpecificField.OWNERS, TabSpecificField.LOCATION, TabSpecificField.TEAMS, TabSpecificField.ROLES) } );
```
To fix the issue now we are passing fields like this
```js
const data = await getPolicyByName(
fqn,
`${TabSpecificField.OWNERS},${TabSpecificField.LOCATION},${TabSpecificField.TEAMS},${TabSpecificField.ROLES}`
);
```
https://github.com/user-attachments/assets/f6ab16dd-4239-4c6a-8920-debb29159e0e
#
#
=> fix: Teams and owner fields are not being passed in the policy API call.

ingestion/setup.py, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummary.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummaryGraph.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummaryGraph.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummaryCustomTooltip/TestSummaryCustomTooltip.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummaryCustomTooltip/TestSummaryCustomTooltip.test.tsx, openmetadata-ui/src/main/resources/ui/src/constants/TestSuite.constant.ts, openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx
Minor: added seconds to human-readable format scale for test case graph
#
#
=> Minor: added seconds to human-readable format scale for test case graph

docker/run_local_docker.sh, openmetadata-ui/src/main/resources/ui/json2ts.sh, openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/src/mocks/Service.mock.ts, package.json, yarn.lock
=> revert quicktype bump since for CI issue

openmetadata-ui/src/main/resources/ui/playwright/utils/customProperty.ts
In some places, we were using `.fill('value{enter}')`, which was causing the test to be flaky, so I updated it to use the `.press` method instead.
=> minor: fix custom property playwright test for AUT

ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
Fixes #17403 
Manifest is not parsed correctly on dbt versionless
#
#
=> Fixes #17403 - Manifest is not parsed correctly on dbt versionless

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestCases.spec.ts
This pull request fixes a flakiness issue in the test cases spec for the playwright. The issue was related to the table difference test case, where the order of certain actions was causing inconsistent results. The patch in this pull request reorders the actions to ensure consistent behavior.
=> playwright: fixed Flakiness in test cases spec

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TeamsHierarchy.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/activityFeed.ts
=> AUT : fix activity feed and teamHierarchy playwright failure

.github/workflows/py-tests.yml
avoid running the py-tests workflow concurrently on the same PR
#
#
=> MINOR: concurrency control on py-tests github workflow

openmetadata-ui/src/main/resources/ui/playwright/constant/config.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/IncidentManager.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TestSuiteMultiPipeline.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/ServiceIngestion.spec.ts
I worked on adding the ingestion tag for all the playwright specs that require the ingestion container to be running
#
#
=> Minor: Add ingestion tag for playwright tests

ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py, openmetadata-ui/src/main/resources/ui/src/constants/Lineage.constants.ts
=> GEN-1584: powerbi col.lineage fix

openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx
- We are setting displayName once and not updating it on receiving prop change
- I have added a usEffect to update it 
- Also scanned same component in case we are having simmiler issue for any other property 
Fixes: User displayName being persisted across user
https://github.com/user-attachments/assets/f39e14dc-37b1-4655-9821-2bd9a84cfe56
https://github.com/user-attachments/assets/2703bd0e-aa57-489e-8768-9f4fd64f52ee
#
#
=> minor(ui): reset displayName to avoid being persisted

openmetadata-ui/src/main/resources/ui/src/components/Settings/Bot/BotDetails/BotDetails.component.tsx
Fixes: 
Tested:
https://github.com/user-attachments/assets/300c84bc-4c02-43d9-9a69-929b773dd97b
#
#
=> minor(ui): fix role page size from 10 to 50

openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
=> Fix Ops taking in wrong long param

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
=> add what's new for 1.5.6

openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/property-value.less, openmetadata-ui/src/main/resources/ui/src/components/common/ResizablePanels/ResizablePanels.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/RichTextEditor.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/RichTextEditorPreviewer.tsx, openmetadata-ui/src/main/resources/ui/src/styles/app.less
- fix custom property layout issues around cards title and values
- Remove description from right panel custom properties.
- Reduce the description to one line
- Make redirect entity link as link color for better visibility.
- Change the expand icon to resemble what we use in the project.
- Remove the custom property title in the Tab page.
https://github.com/user-attachments/assets/3b38a833-d43c-461a-8052-e7306b67f826
#
#
=> MINOR: fix custom property layout issues

openmetadata-ui/src/main/resources/ui/.licenseheaderrc.json, openmetadata-ui/src/main/resources/ui/LICENSE, openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/playwright/constant/glossaryImportExport.ts, openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/FeedEditor/FeedEditor.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/FeedEditor/FeedEditor.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/custom-property-table.less, openmetadata-ui/src/main/resources/ui/src/constants/ResizablePanel.constants.ts, openmetadata-ui/src/main/resources/ui/src/utils/QuillLink/QuillLink.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/QuillLink/QuillLink.ts, openmetadata-ui/src/main/resources/ui/webpack.config.dev.js, openmetadata-ui/src/main/resources/ui/webpack.config.prod.js, openmetadata-ui/src/main/resources/ui/yarn.lock
=> minor(ui): react-quill package update to maintained one

openmetadata-service/src/main/java/org/openmetadata/service/TypeRegistry.java
fix: Handle NullPointerException when adding custom properties to ensure loop continues for other schemas of the same type for addToRegistry
#
#
=> Minor : Handle exception in Custom property

openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/GreenplumConnectionClassConverter.java
Fix #18005: Mask Greenplum Password
#
#
=> Fix #18005: Mask Greenplum Password

openmetadata-ui/src/main/resources/ui/src/components/Database/RetentionPeriod/RetentionPeriod.component.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/RetentionPeriod/RetentionPeriod.component.tsx
Fixes #18118
This PR introduces UI helper function for decoding iso 8601 duration strings to human readable form 
#
#
=> human readable retention period

openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
This pull request includes a minor change to mark the parameters as optional for the test case reports endpoint. This change allows for more flexibility when querying test case search results by allowing the testCaseType and dataQualityDimension parameters to be optional.
=> Minor: mark params optional for test case reports end point

openmetadata-ui/src/main/resources/ui/README.md, openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
(No issue opened explicitly)
- Allows us to change the backend OpenMetadata server that the development UI connects to easily by an environment variable.
- At the moment, the target server is hard-coded in `webpack.config.dev.js`.
- In certain development scenarios, it would be useful to be able to make changes **without modifying the file**.
- If the environment variable is not set, the behavior is unchanged.
- I have verified in my local environment that it behaves as expected when environment variables are set.
#
#
=> MINOR: add env DEV_SERVER_TARGET for webpack.config.dev.js to specify the OpenMetadata server

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SearchIndexApplication.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/TreeSelectWidget.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/TreeSelectWidget.tsx
- Searching any index of an entity, will filter down the list.
- When all is selected, should only show all in the select and not all the list
Issue : 
Resolved : 
#
#
=> MINOR: supported search filter and only all show in case of all node value selected

openmetadata-spec/src/main/resources/json/schema/entity/services/connections/pipeline/matillionConnection.json, openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/ServiceConnectionDetails/ServiceConnectionDetails.component.tsx
Custom Logic for the Pipeline scoped to Airflow
Fixes an error where other pipeline connectors with `connection` attribute fails because of the custom logic for airflow connector
#
#
=> Refactor ServiceConnectionDetails component

openmetadata-docs/content/v1.5.x/menu.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
I woked on removing  the collate connectors options from OSS menu.md
#
#
=> Remove the collate connector links from the OSS menu.md

openmetadata-docs/content/partials/v1.5/connectors/storage/connectors-list.md, openmetadata-docs/content/partials/v1.6/connectors/storage/connectors-list.md
GCS tile not showing up in storage section, modified to show it.
#
#
=> MINOR: [DOC] Update GCS connector platform in storage connectors list

ingestion/src/metadata/ingestion/source/database/hive/connection.py
Fix #18177: Fix Hive MetaStore connection issue
#
#
=> Fix #18177: Fix Hive MetaStore connection issue

ingestion/src/metadata/profiler/orm/functions/table_metric_computer.py
Fixes: No issue number
The issue was that OpenMetadata's Redshift profiler used the `svv_table_info` system table to fetch details for both internal and external tables. However, `svv_table_info` does not contain metadata for external tables, causing the profiler to return empty results and does not fetches `Row Count`.
The previous implementation handled this scenario by returning `None` when no results were found, which prevented `Row Count` metric computation for Redshift Spectrum external tables.
The fix introduces a fallback mechanism that, if `svv_table_info` returns empty results, triggers a call to the base profiler’s method (`super().compute()`), which directly queries the target external table to compute the metrics. This ensures that profiling works for both internal and …
=> Fix Redshift profiler for external tables in Redshift Spectrum

ingestion/setup.py
Seems on our images sometimes `ibm-db` does not get installed. We're explicitely adding it as a dependency to prevent this issue.
#
#
=> MINOR: Update DB2 dependencies to fix issue about not having ibm-db installed

openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v160/MigrationUtil.java
Properly migrate with JSONB data to avoid `"Token 'SearchIndexingApplication' is invalid"`
#
#
=> FIX - App Extension migration JSONB

ingestion/src/metadata/ingestion/source/dashboard/superset/connection.py, ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
=> FIx #17933: Superset fix chart query for mysql con.

openmetadata-ui/src/main/resources/ui/src/components/Settings/CustomProperty/CustomPropertyTable.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.tsx, openmetadata-ui/src/main/resources/ui/src/styles/app.less
Issue: In our AUT, there are floating buttons in the application that overlap with certain edit buttons, causing failures.
Resolution: To prevent overlapping and ensure smooth test runs in the AUT, added a right margin to the container when the floating button is present.
=> test: custom properties AUT

openmetadata-ui/src/main/resources/ui/src/utils/TagClassBase.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/TagClassBase.ts
Fixes: GEN-1856
https://github.com/user-attachments/assets/3bea6ec3-1365-4470-87a6-880347f73a98
#
#
=> fix: GEN-1856 encode and escape search value for the tag search

ingestion/src/metadata/workflow/application.py, ingestion/src/metadata/workflow/base.py, ingestion/src/metadata/workflow/ingestion.py, ingestion/src/metadata/workflow/workflow_output_handler.py, ingestion/src/metadata/workflow/workflow_status_mixin.py, ingestion/tests/unit/profiler/test_workflow.py, openmetadata-docs/content/partials/v1.6/deployment/upgrade/upgrade-prerequisites.md, openmetadata-spec/src/main/resources/json/schema/metadataIngestion/workflow.json
Adding success % to the status list
```
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Workflow Mysql Summary:
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Processed records: 91
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Updated records: 0
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Warnings: 0
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Errors: 0
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Success %: 100.0
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Workflow OpenMetadata Summary:
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Processed records: 64
[2024-10-15 15:28:50] INFO     {metadata.Utils:logger:181} - Updated records: 0
[2024-10-15 15:28:50] INFO …
```
=> GEN-1166 - Improve Ingestion Workflow Error Summary

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Permission.spec.ts
Skip the permission spec, as there are some changes from the backend that are causing the failure, we need to modify the permission spec based on the changes.
#
#
=> Minor: skip the permission spec

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/RoleRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java, openmetadata-service/src/main/resources/json/data/role/DefaultBotRole.json, openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java
Fixes GEN-927
- Create `DefaultBotRole` that is added to any bot created. It contains the `DefaultBotPolicy` and `DataConsumerPolicy`. Without it, newly created bots did not have any kind of access to the data on a default installation of OM.
- If bots are created with a Domain, the bot user will also have the `DomainOnlyAccessRole` so that unless admins change it, that bot can only access its own data
#
#
=> GEN-927 - Add bot default roles

ingestion/src/metadata/data_quality/interface/test_suite_interface.py, ingestion/src/metadata/data_quality/interface/test_suite_interface_factory.py, ingestion/src/metadata/profiler/source/profiler_source_factory.py
- move classes import to lazy in the factory method
**Note**
`profiler_interface_factory` will be handle using the manifest PR from @sushi30. These 2 factories will temporarily use the lazy loading until we get the manifest implemented for these as well.
#
#
Improvement
=> fix: lazy load classes from factory method

ingestion/src/metadata/utils/timeout.py
Disable SIGALARM timeout on sub threads
#
#
=> MINOR - Only timeout on main threads

openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v160/Migration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v160/Migration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v160/MigrationUtil.java
Organization policy sets default Edit actions for owners and noowners.
However this doesn't put any ViewPolicy which restricts users access to metadata.
Since we added SearchRBAC, this by default doesn't show any results in explore page.
We should allow ViewAll as default Organization Policy to get the first user experience to discover the data assets
#
#
=> Minor: Add ViewAll policy to enable default OrganizationPolicy to allow users to view metadata

.github/workflows/py-cli-e2e-tests.yml
=> MINOR: trying to add job id to logs

openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/yarn.lock
Fix the vulnerability by adding the suggested version of the 'jsonpath-plus' from the [dependabot](https://github.com/open-metadata/OpenMetadata/security/dependabot/174) in the package.json resolutions.
https://github.com/user-attachments/assets/ae7f1624-d3d8-4753-adbc-78ea60c76510
#
#
=> Fix security vulnerability for jsonpath-plus package

openmetadata-docs/content/v1.5.x/deployment/azure-auth.md, openmetadata-docs/content/v1.5.x/menu.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/azure-auth.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md, openmetadata-service/pom.xml, openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java, openmetadata-service/src/main/java/org/openmetadata/service/util/AzureTokenProvider.java, openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java, openmetadata-service/src/main/java/org/openmetadata/service/util/jdbi/AwsRdsDatabaseAuthenticationProvider.java, openmetadata-service/src/main/java/org/openmetadata/service/util/jdbi/AzureDatabaseAuthenticationProvider.java, openmetadata-service/src/main/java/org/openmetadata/service/util/jdbi/DatabaseAuthenticationProvider.java, openmetadata-service/src/main/java/org/openmetadata/service/util/jdbi/DatabaseAuthenticationProviderFactory.java, openmetadata-service/src/main/java/org/openmetadata/service/util/jdbi/JdbiUtils.java, pom.xml
=> Add Azure Token Base Authentication

openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx, openmetadata-ui/src/main/resources/ui/src/components/Modals/ModalWithCustomProperty/ModalWithCustomPropertyEditor.component.tsx, openmetadata-ui/src/main/resources/ui/src/utils/TagClassBase.test.ts
This PR include the following changes
- use `entityType` prop for custom property table
- remove harcoded type for entity details and use generic type
=> minor: improve types in ModalWithCustomPropertyEditor component

openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/MarketPlaceAppDetails/MarketPlaceAppDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/MarketPlaceAppDetails/MarketPlaceAppDetails.test.tsx
**Issue**: We were directly using the email address as the `href` value for the anchor element for application support. This is causing an issue where the link `https://domain.com/path/apps/emailid` is created incorrectly. Instead of opening the email client when clicking on `Get App Support`, it opens the application path and treats the email address as a fully qualified name of the application.
https://github.com/user-attachments/assets/a3758c8c-8f26-4956-ba8d-56cd371c9a9b
**Fix**: Added a `mailto:` URI scheme so that the `Get App Support` link opens the user's default email client with the provided support email address.
https://github.com/user-attachments/assets/64798636-0a4d-460d-a51d-56c80d2af894
=> fix: application support email link with `mailto:` URI schema

openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
Fixes: Fixed navigation to non-exist page to existing page for deleting a service
I worked on:
- When deleting a service from details page, UI tries to move back to older in history which may contain a page which no longer available due to hard delete of service.
- i.e. User visit a table page and navigate to it's service page from breadcrumbs. Now if user delete that service parmenatly UI will try to throw user to table page which no longer exist and trun into an error 
- Instead throwing user to back in history navigate them to relevant service listing page.
- API
- Databases
- Messaging
- Dashboard
- Pipeline
- ML Model
- Storages
- Search
- Metadata
https://github.com/user-attachments/assets/09aa3dd2-070c-4ee8-b2be-b9f99e3f7e08
#
#
=> fix(ui): navigate to listing for deleting a service

bootstrap/sql/migrations/native/1.6.0/mysql/schemaChanges.sql, bootstrap/sql/migrations/native/1.6.0/postgres/schemaChanges.sql
Add the `source` column Without the NOT NULL constraint on `consumers_dlq`, populate it later with Publisher in `postDataMigration`
#
#
=> Fix Debuggability Migration

openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerClassBase.ts, openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerPage.tsx
This is the supporting PR for adding widget in incident manager
#
#
=> Feat: supporting pr for incident manager widget feature

ingestion/src/metadata/ingestion/source/database/glue/metadata.py, ingestion/src/metadata/ingestion/source/database/glue/models.py, ingestion/tests/unit/resources/datasets/glue_db_dataset.json, ingestion/tests/unit/topology/database/test_glue.py, openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/glue/index.md
Added file format, location path and external table lineage to `GlueSource`.
AWS Glue connector is quite poor in comparison to what you can find e.g. in AWS console. Some of the interesting features, like lineage, we can find in Athena connector - however, Glue tables can be queried by other engines, such as Trino. Athena is not a popular solution for companies holding huge amounts of data, due to costs. Fetching storage metadata in Trino is difficult, so adding them to Glue instead is a quick win.
Changes summary:
- `GlueSource` now inherits from `ExternalTableLineageMixin`.
- Table location is extracted directly from StorageDescriptor (if present).
- File format is extracted from StorageDescriptor (if present) by parsing SerDe library class.
- `test_table_names` is fixed - with no …
=> Enhanced Glue ingestion with external table features

ingestion/src/metadata/ingestion/source/database/iceberg/fs/s3.py, ingestion/tests/unit/topology/database/test_iceberg.py
Fixes #18512
Small fix to return the `S3_ENDPOINT` as `str` instead of `Url`.
Needed since the migration to Pydantic V2
#
#
=> Fix #18512: Return s3 endpoint as str() instead of Url

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java
Fix EntityRelationship data disappeared after reindexing
#
#
=> [ER Diagrams]: Fix EntityRelationship data disappeared after reindexing

ingestion/src/metadata/ingestion/bulksink/metadata_usage.py, ingestion/src/metadata/ingestion/lineage/masker.py, ingestion/src/metadata/ingestion/lineage/parser.py, ingestion/src/metadata/ingestion/lineage/sql_lineage.py, ingestion/src/metadata/ingestion/ometa/mixins/query_mixin.py, ingestion/src/metadata/ingestion/processor/query_parser.py, ingestion/src/metadata/ingestion/source/database/athena/lineage.py, ingestion/src/metadata/ingestion/source/database/athena/usage.py, ingestion/src/metadata/ingestion/source/database/databricks/lineage.py, ingestion/src/metadata/ingestion/source/database/databricks/usage.py, ingestion/src/metadata/ingestion/source/database/lineage_source.py, ingestion/src/metadata/ingestion/source/database/postgres/lineage.py, ingestion/src/metadata/ingestion/source/database/postgres/usage.py, ingestion/src/metadata/ingestion/source/database/query_parser_source.py, ingestion/src/metadata/ingestion/source/database/redshift/lineage.py, ingestion/src/metadata/ingestion/source/database/snowflake/queries.py, ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py, ingestion/src/metadata/ingestion/source/database/usage_source.py, ingestion/src/metadata/ingestion/stage/table_usage.py, ingestion/src/metadata/utils/logger.py, ingestion/tests/unit/test_databricks_lineage.py, ingestion/tests/unit/test_sql_lineage.py, ingestion/tests/unit/test_usage_log.py, openmetadata-spec/src/main/resources/json/schema/api/data/createQuery.json, openmetadata-spec/src/main/resources/json/schema/type/queryParserData.json, openmetadata-spec/src/main/resources/json/schema/type/tableQuery.json
=> Mask SQL Queries in Usage & Lineage Workflow

openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
=> MINOR: mising menu for powerbi rs

bootstrap/sql/migrations/native/1.6.0/mysql/schemaChanges.sql, bootstrap/sql/migrations/native/1.6.0/postgres/schemaChanges.sql, ingestion/src/metadata/ingestion/source/database/common_db_source.py, ingestion/src/metadata/ingestion/source/database/common_nosql_source.py, ingestion/src/metadata/ingestion/source/database/database_service.py, ingestion/src/metadata/ingestion/source/database/datalake/metadata.py, ingestion/src/metadata/ingestion/source/database/deltalake/metadata.py, ingestion/src/metadata/ingestion/source/database/domodatabase/metadata.py, ingestion/src/metadata/ingestion/source/database/glue/metadata.py, ingestion/src/metadata/ingestion/source/database/iceberg/metadata.py, ingestion/src/metadata/ingestion/source/database/salesforce/metadata.py, ingestion/src/metadata/ingestion/source/database/sas/metadata.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/metadata.py, ingestion/tests/cli_e2e/common/test_cli_db.py, ingestion/tests/integration/postgres/test_lineage.py, openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/upgrade/versions/150-to-160.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/developers/contribute/developing-a-new-connector/develop-ingestion-code.md, openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
=> Fixes GEN-1994: Remove View Lineage from Metadata Ingestion flow

openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.tsx
**Issue:** We have a common component called PropertyValue that renders input fields based on custom property types. Each input field is associated with a unique form ID. However, when two properties of the same type are being edited simultaneously with the same form ID, the input for the last opened property is triggered instead of the selected one.
**Resolution:** Updated the form ID for each property to ensure a unique name, allowing each property to render with a distinct form ID and preventing conflicts.
https://github.com/user-attachments/assets/cd47fc29-2e5c-4ab0-bea2-b3a8addcf53f
=> fix: checkmark saves wrong custom property field

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/processors/WebAnalyticsEntityViewProcessor.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
The WebAnalytics insights processor isn't properly processing Data Assets with URL Encoded characters on their name.
This PR aims to fix that by decoding it before searching for the asset.
#
#
=> MINOR: Fix App Insights not processing URL Encoded Data Assets

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
- Added latch for consumers
- update status to active error
#
#
=> Fix wait for consumers and status for Sink

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryColumnsSelectionDropdown/DraggableMenuItem.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Glossary/glossaryV1.less
This PR introduces following fixes,
**Glossary Terms Table Styling:**
Fixes layout and styling issues for the terms table to improve readability and alignment.
**Drag-and-Drop Test Update:**
Temporarily disables  a failing drag-and-drop test of Glossary Terms table for further investigation and debugging.
https://github.com/user-attachments/assets/d79aa559-38d8-4569-831e-a6a964a857a2
#
#
=> Fix: update glossary terms table stylings and temporarily bypass failing drag-and-drop test

openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/yarn.lock
I worked on fixing the vulnerability with `jsonpath-plus`, a sub-dependency due `@okta/okta-auth-js` [here](https://github.com/open-metadata/OpenMetadata/security/dependabot/177)
After the package updation:
https://github.com/user-attachments/assets/321d0138-78b5-4b7a-8685-2cda11d60dd1
#
#
=> Update the jsonpath-plus resolution version to fix the vulnerability

openmetadata-ui/src/main/resources/ui/src/constants/Ingestions.constant.ts
I worked on fixing the maven build on main by adding the missing pipeline type in the localization key mapping object
#
#
=> Minor: Fix the maven build on main

openmetadata-service/pom.xml
Reverting f0b76c45d081fe66bded44c60fa4560a879cb346
Due to failures in migration:
```
2024-11-19 17:16:15.916	picocli.CommandLine$ExecutionException: Error while calling command (public java.lang.Integer org.openmetadata.service.util.OpenMetadataOperations.migrate(boolean)): java.lang.NoClassDefFoundError: software/amazon/awssdk/checksums/SdkChecksum
2024-11-19 17:16:15.641	Updating bot users in case of an update on the JSON schema: [managed-aws]
2024-11-19 17:16:14.903	Updating services in case of an update on the JSON schema: [managed-aws]
```
#
#
=> MINOR: revert aws sdk version from f0b76c45d081fe66bded44c60fa4560a879cb346

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java, openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/applicationConfig.json, openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/slackAppTokenConfiguration.json
=> Slack app improvements

ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
Our StoreProcedure ingestion seem to be failing due to an error within its yield_lineage part.
This modification aims to avoid a general failure caused by one specific query.
#
#
=> MINOR: Add Try/Except to store procedure yielding

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/impl/SetEntityCertificationImpl.java
Adding missing check to the set entity certification implementation
#
=> MINOR: Fix missing check on set entity certification

ingestion/src/metadata/data_quality/validations/runtime_param_setter/param_setter_factory.py, ingestion/tests/cli_e2e/base/config_builders/builders.py, ingestion/tests/cli_e2e/base/e2e_types.py, ingestion/tests/cli_e2e/base/test_cli_db.py, ingestion/tests/cli_e2e/common/test_cli_db.py
=> TEST - Add autoClassification for e2e

openmetadata-docs/content/v1.5.x/deployment/security/saml/index.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/security/saml/index.md
I worked on ... because adding Private key note.
#
#
=> Docs: Private key note added

openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableList/DomainSelectableList.component.tsx
=> GEN-2078: fix minor styling of domain component

openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/PolicyEvaluator.java
=> Minor: skip domain check for bots and admin

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/triggers/PeriodicBatchEntityTrigger.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/triggers/impl/FetchEntitiesImpl.java, openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java, openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java, openmetadata-spec/src/main/resources/json/schema/governance/workflows/elements/triggers/periodicBatchEntityTrigger.json
The Glossary Term Tests have been a flaky lately and it seems that the `delete_recursive` test was being running before the end and impacting a some of the terms that were created by other tests that had not finished yet.
For this reason I added an annotation to guarantee the test would be the last one to run.
In order to improve the performance of the Certification Workflow, we are changing the Entity Fetch method to get only the FQN from Elasticsearch as it is what we need.
We are also setting the default batchSize from the PeriodicBatchEntityTrigger to 500.
Other than that we are also transforming the workflow after the startEvent into async behaviour to be able to trigger the workflow without waiting for it to finish.
#
#
=> MINOR: Governance Workflows fixes

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
=> minor: add whats new for 1.5.12

.github/workflows/auto-cherry-pick-labeled-prs.yaml
Adding a new workflow to auto-cherry-pick changes from pull requests to the release branch
To enable automatic cherry-picking for your PR, add the `To release` label.
The workflow will attempt to cherry-pick your changes and will notify you on your PR whether the process was successful.
#
#
=> feat(ci): GEN-2128 add auto cherry pick workflow

openmetadata-docs/content/partials/v1.6/deployment/upgrade/upgrade-prerequisites.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md
Added information about the breaking changes with the `ServiceSpec` connector entrypoint.
#
#
=> MINOR: doc: service spec breaking changes

ingestion/pyproject.toml
there is a new reportExplicitAny rule introduced in https://github.com/DetachHead/basedpyright/commit/529bb2c57131f1a8b3c005a2a1be27dabdd39e37
#
#
=> MINOR: add reportExplicitAny = false for basedpyright

openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightDescriptionAndOwnerTemplate.java
Remove double minus sign coming in percentChangeMessage in DI email template.
#
#
=> FIX: Remove Double Minus Sign in DI Email Templates

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/triggers/PeriodicBatchEntityTrigger.java
Making the Fetching Data step for `PeriodicBatchTrigger` makes the workflow faster by allowing Flowable to keep processing entities while more are being fetched.
#
#
=> MINOR: Make Fetching Data Async

openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v150/MigrationUtil.java
Due to a code Change, the 1.5 migration now throws an error that we are now catching and logging since it should not be an issue.
#
#
=> MINOR: Catch exception that arises due to a change in code.

openmetadata-service/src/main/java/org/openmetadata/service/util/jdbi/DatabaseAuthenticationProviderFactory.java
Fixes #18848 
When `query` is an empty string, `indexOf` returns -1, which results in `subtring(0, -1)`, causing an error.
#
#
=> Fixes #18848: "Failed to parse query parameters from JDBC URL" when query is an empty string

openmetadata-ui/src/main/resources/ui/playwright/utils/customProperty.ts
Update the `createCustomPropertyForEntity` utility method to ensure it only processes custom properties created specifically for the current test run.
=> Minor: improve custom properties e2e test

openmetadata-docs/content/v1.4.x/connectors/database/athena/index.md, openmetadata-docs/content/v1.4.x/connectors/database/athena/yaml.md, openmetadata-docs/content/v1.5.x/connectors/database/athena/index.md, openmetadata-docs/content/v1.5.x/connectors/database/athena/yaml.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/athena/index.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/athena/yaml.md
Fixes #18781 
This PR is an update on the Athena connector documentation to address missing IAM policy permissions. Specifically, the changes include:
Adding lambda:InvokeFunction to support Athena connectors that rely on AWS Lambda for query execution.
Including kms:Decrypt and kms:DescribeKey permissions for accessing encrypted S3 buckets where Athena stores query results.
These changes are necessary to prevent common issues such as query failures and permission errors during metadata ingestion and pipeline execution.
I tested the changes by reviewing AWS documentation and ensuring the new policies cover the required actions for seamless Athena integration.
This update improves usability and helps users avoid common pitfalls related to IAM configuration for the Athena connector.
Type of …
=> Fixes issue #18781: Adding lambda permissions to Athena connector documentation

openmetadata-ui/src/main/resources/ui/src/components/Modals/IngestionRunDetailsModal/IngestionRunDetailsModal.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/ConnectionStepCard/connection-step-card.less
improved the spacing in connection component
#
#
=> Minor: fixed connection modal style

openmetadata-docs/content/v1.4.x/developers/contribute/developing-a-new-connector/define-json-schema.md, openmetadata-docs/content/v1.5.x/developers/contribute/developing-a-new-connector/define-json-schema.md, openmetadata-docs/content/v1.6.x-SNAPSHOT/developers/contribute/developing-a-new-connector/define-json-schema.md
I found a minor typo in the docs.
Minor fix of a typo on the https://docs.open-metadata.org/latest/developers/contribute/developing-a-new-connector/define-json-schema page footer where the `ingestion` word is `ingesion` for the 3 supported versions.
#
#
=> Minor: Fix typo on the ingestion word

openmetadata-service/src/main/java/org/openmetadata/service/exception/EntityNotFoundException.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v160/Migration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v160/Migration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v160/MigrationUtil.java, openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java, openmetadata-service/src/test/java/org/openmetadata/service/EnumBackwardCompatibilityTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java, openmetadata-spec/src/main/java/org/openmetadata/sdk/exception/EntitySpecViolationException.java, openmetadata-spec/src/main/java/org/openmetadata/sdk/exception/EntityUpdateException.java, openmetadata-spec/src/main/resources/json/schema/type/entityRelationship.json
=> Create a relationship to manage ER based on tableConstraints

openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/yarn.lock
Fixes: Need gifsicle for image-webpack-loader more context here: https://github.com/tcoopman/image-webpack-loader/issues/233
#
#
=> chore(ui): add gifsicle as it's needed for image-webpack-loader

ingestion/setup.py, ingestion/src/metadata/ingestion/lineage/parser.py, ingestion/src/metadata/ingestion/lineage/sql_lineage.py, ingestion/src/metadata/ingestion/models/patch_request.py, ingestion/src/metadata/ingestion/source/database/snowflake/lineage.py, ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py, ingestion/src/metadata/ingestion/source/database/snowflake/models.py, ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
=> MINOR: Snowflake UDF Lineage Support - main

ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py, ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py, ingestion/src/metadata/ingestion/source/dashboard/tableau/models.py
=> MINOR: Tableau Capture SQL in Lineage

ingestion/src/metadata/ingestion/source/pipeline/fivetran/metadata.py, ingestion/tests/unit/topology/pipeline/test_fivetran.py, openmetadata-docs/content/partials/v1.6/deployment/upgrade/upgrade-prerequisites.md
=> Fixes GEN-2199: Allow Fivetran filtering of pipelines using name instead of id

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityExportModalProvider/EntityExportModalProvider.component.tsx
**Problem:** When multiple tabs are open and a user starts an export in one tab, multiple files are downloaded once we receive a response from the WebSocket.
**Resolution:** A check has been implemented to verify if an active CSV job reference is available. This ensures that the export is only initiated if a reference exists. As a result, even with multiple tabs open, only the tab where the export job started will have the job reference, preventing multiple files from being downloaded.
https://github.com/user-attachments/assets/fac9b481-82ad-42ca-8421-996b3a3ab11f
=> Minor: Prevent Multiple CSV export download if no active job is present

openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/yarn.lock
I worked on fixing the [vulnerability](https://github.com/open-metadata/OpenMetadata/actions/runs/12226640260) due to the `jsonpath-plus` package.
Upgraded the resolution version `10.0.7` -> `10.2.0`
**After Upgrade:**
https://github.com/user-attachments/assets/4e17012c-99d6-4354-9140-088175426cea
#
#
=> Minor: Update the resolution version for the `jsonpath-plus` package to fix the vulnerability

ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/client.py, ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/connection.py
Minor: Fix kafkaconnect test connection
#
#
=> Minor: Fix kafkaconnect test connection

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/MainWorkflowTerminationListener.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/CheckEntityAttributesTask.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/SetEntityCertificationTask.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/SetGlossaryTermStatusTask.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/endEvent/EndEvent.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/startEvent/StartEvent.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/userTask/UserApprovalTask.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/userTask/impl/CreateApprovalTaskImpl.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/WorkflowInstanceRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
Removing the Workflow Instance States in order to reduce the Database Load until we do it better.
Also fixing an OpenSearch method that wasn't up to date with the code and was causing an infinite loop.
#
#
=> MINOR: Remove workflow instance states

openmetadata-ui/src/main/resources/ui/src/pages/DataQuality/DataQualityPage.interface.ts, openmetadata-ui/src/main/resources/ui/src/rest/dataQualityDashboardAPI.test.ts, openmetadata-ui/src/main/resources/ui/src/rest/dataQualityDashboardAPI.ts
added entity type support to fetch test case count
#
#
=> minor: added entity type support in dq dashboard API

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
- Fix live update of test suite aggregation in search service
#
#
=> Minor logical test suite agg update

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/WorkflowHandler.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/settings/SettingsCache.java, openmetadata-spec/src/main/resources/json/schema/configuration/workflowSettings.json, openmetadata-spec/src/main/resources/json/schema/settings/settings.json
This PR aims to do two different things:
- First of all, it aims to provide a good default for keeping the flowable historic tables nice and tidy to avoid them growing way too much
This is done by setting the following config, with the default being cleaning history of processes after 7 days they ended.
```java
processEngineConfiguration
.setEnableHistoryCleaning(true)
.setCleanInstancesEndedAfter(
Duration.ofDays(
workflowSettings.getHistoryCleanUpConfiguration().getCleanAfterNumberOfDays()));
```
- Second, it parametrizes the main configurations that should be defined depending on the different use cases
This was done by setting a new SystemSetting: WorkflowSetting.
The main thing I'm not sold on is how I'm updating the `ProcessEngine` after a setting change is done. I'd love any inputs …
=> MINOR: Handle Flowable History Cleanup

openmetadata-ui/pom.xml
[Here](https://github.com/open-metadata/OpenMetadata/pull/18900/files#diff-bd9dbd93da4e6e791ee7af355ef4ea97849582e18a3396e8501d4119f9f28b1c) we have added support for a few extensions as nonFilteredExtension in pom.xml. `ttf` is missing, so this PR will add it.
=> minor: add support for ttf file extension in openmetadata-ui/pom.xml

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/WorkflowHandler.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/governance/WorkflowDefinitionResource.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java
- Fixed null pointer for WorkflowSettings
- Added test for Workflow setting
#
#
=> Fix NullPointer for Workflow Setting

openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/mysqlConnection.json, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/postgresConnection.json, openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/database/mysqlConnection.ts, openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/database/postgresConnection.ts
Fix Import for Mysql and Redshift Connection
#
#
=> Correct Imports for Class Converter Factory

conf/openmetadata.yaml, openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java, openmetadata-service/src/main/java/org/openmetadata/service/security/jwt/JWTTokenGenerator.java, openmetadata-service/src/test/java/org/openmetadata/service/security/JWTTokenGeneratorTest.java, openmetadata-spec/src/main/resources/json/schema/configuration/authenticationConfiguration.json, openmetadata-ui/src/main/resources/ui/src/generated/configuration/authenticationConfiguration.ts
[Fixes <issue-number>](https://github.com/open-metadata/OpenMetadata/issues/18594)
#
#
=> Add Algorithm option for validation in yaml

openmetadata-ui/src/main/resources/ui/playwright/constant/explore.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/ExploreTree.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/explore.ts
I worked on Explore page e2e tests.
- Check listing of entities when index is dataAsset
- Check listing of entities when index is all
#
#
=> test(e2e): Explore page tests

openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MSTeamsMessageDecorator.java
1. Use buildDQTemplateData from MessageDecorator in MSTeamsMessageDecorator.
> **Issue:**
> Reason: Failed to publish event of destination type MsTeams due to Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "testCaseDetails" is null
Fixes: #19073
#
#
=> Fixes 19073 : Resolve NullPointerException in MS Teams DQ template handling

openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.test.tsx, openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.test.tsx, openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx, openmetadata-ui/src/main/resources/ui/src/utils/mocks/EntityUtils.mock.ts
Fix #19077
Search Term Highlight Feature.
The text typed in search bar is getting highlighted.
https://github.com/user-attachments/assets/8533eb81-feee-4641-ae7b-040a7241759c
#
#
=> feat(ui): highlight search term for schema table in table details page

ingestion/src/metadata/ingestion/source/database/db2/metadata.py, ingestion/src/metadata/ingestion/source/database/db2/utils.py
Fixes #18140 
DB2 Ingestion could fail under certain conditions since the library is not fetching properly the unique constraints.
This PR aims to solve this by changing the query used for this. It is also being pushed upstream [here](https://github.com/ibmdb/python-ibmdbsa/pull/152)
#
#
=> FIX #18140: DB2 should not fetch wrong unique constraints anymore.

openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyInput.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/property-value.less, openmetadata-ui/src/main/resources/ui/src/components/common/InlineEdit/InlineEdit.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/InlineEdit/inline-edit.less
Fixes #19064
- I worked on fixing the spacing issue around the custom property field in the entity right panel
Previous : 
https://github.com/user-attachments/assets/0d326900-8429-4ac3-a866-5740f01e29d5
Resolved : 
https://github.com/user-attachments/assets/d3ef1d8f-0810-41ae-89aa-afe0996106e5
https://github.com/user-attachments/assets/62698568-74ea-43ba-a3d1-a15437d4dee7
#
#
=> 19064: fix the spacing around the input in custom properties right panel

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
Currently `Soft Delete` and `Constraints` do not fare well together and on different scenarios it errors.
An example is our E2E MySQL Pipeline where we:
1. Ingest all the Tables
2. Ingest Tables with filters, which prompts to soft delete a couple tables
3. Ingest Tables with other filters, which prompts to restore a couple tables
Some of those tables have different Foreign Key constraints and the process is currently erroring for a couple tables due to two different methods being called:
1. **storeEntity** (On soft delete)
Here the `addConstraintRelationship` gets called and searches for the Foreign Key table, which was already soft deleted, raising an exception.
2. **updateTableConstraints** (On restore entity)
Here the `validateTableConstraints` gets called and validates the Foreign Key …
=> MINOR: Fix Table constraint relationships for SoftDeleted entities.

ingestion/tests/cli_e2e/base/config_builders/builders.py, ingestion/tests/cli_e2e/database/mysql/mysql.yaml, ingestion/tests/cli_e2e/test_cli_mysql.py, ingestion/tests/cli_e2e/test_cli_oracle.py, ingestion/tests/cli_e2e/test_cli_powerbi.py
=> Fix e2e tests

openmetadata-ui/src/main/resources/ui/src/components/DataInsight/TotalEntityInsightSummary.component.tsx, openmetadata-ui/src/main/resources/ui/src/interface/data-insight.interface.ts, openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.tsx
Fixes: 
Provision to transform label or not for tooltip
StartCase for TotalEntity Charts
#
#
=> chore(ui): improve data insight chart and tooltip rendering

openmetadata-service/src/test/java/org/openmetadata/service/resources/events/EventSubscriptionResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryResourceTest.java
Fixes failing glossary test in main
#
#
=> Fix Failing test for glossary

ingestion/tests/cli_e2e/common/test_cli_db.py
Remove the sample_data from assert in profiler since it was moved to the classification workflow
#
#
=> MINOR: Fix MSSQL E2E Test

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/IncidentManager.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/MySqlIngestionClass.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/bot.ts
playwright: reset the profiler bot token in AUT
#
#
=> playwright: reset the profiler bot token in AUT

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedFilter.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
For activity feed, we use `updatedAt` field as cursor to support pagination. There are possible cases when multiple threads can have the same value of updatedAt, this results in feed results getting affected and not showing the correct result of threads where duplicate value is present, and in some cases throwing exception.
To avoid this behaviour we have used `two fields (updatedAt,id)` to always get unique value of cursor for comparison. 
`Note` - id is of uuid, so ordering so in case of  same timestamps ordering will not be in lexicographic order , but we will always get all the threads , and there will be no case of missing thread
Before : 
https://github.com/user-attachments/assets/ec0df863-34c8-4bf5-8520-b2859c3a3798
After : …
=> Feed pagination improvement

openmetadata-docs/content/partials/v1.6/connectors/yaml/api/source-config-def.md, openmetadata-docs/content/partials/v1.6/connectors/yaml/api/source-config.md, openmetadata-docs/content/v1.6.x/connectors/api/rest/yaml.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/api/rest/yaml.md
Trivial change of documentation about ApiMetadata ingestion to reflect the [expected schema](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/metadataIngestion/apiServiceMetadataPipeline.json).
The current documentation references the wrong `source-config` section.
#
#
=> Docs: ApiMetadata ingestion source-config

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/WorkflowEventConsumer.java
Removes unused Delete Events from WorkflowConsumer. Currently this is erroring and since we are not even allowing to be used, we are better off removing it for now.
#
#
=> MINOR: Remove Delete Events from Workflow Consumer

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
Fix - 
When uploading a csv to the glossary, if no values are specified in the extension column, the existing custom properties are removed. 
#
#
=> Fix - Existing custom properties getting removed on import of empty extension column

openmetadata-docs/content/v1.6.x/connectors/database/druid/index.md, openmetadata-docs/content/v1.6.x/connectors/database/druid/yaml.md, openmetadata-docs/content/v1.6.x/connectors/database/greenplum/index.md, openmetadata-docs/content/v1.6.x/connectors/database/greenplum/yaml.md, openmetadata-docs/content/v1.6.x/connectors/database/hive/index.md, openmetadata-docs/content/v1.6.x/connectors/database/hive/yaml.md, openmetadata-docs/content/v1.6.x/connectors/database/impala/index.md, openmetadata-docs/content/v1.6.x/connectors/database/impala/yaml.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/druid/index.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/druid/yaml.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/greenplum/index.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/greenplum/yaml.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/hive/index.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/hive/yaml.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/impala/index.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/impala/yaml.md
I worked on Lineage Addition till Impala
#
#
=> Docs: Lineage Addition till Impala

ingestion/src/metadata/profiler/orm/functions/length.py, ingestion/src/metadata/profiler/orm/registry.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/19187
I worked on adding PinotDB to Python Dialect in ORM registry and replacing LEN() with LENGTH() for PinotDB
#
#
=> Fixes 19187 : Specify Length function for PinotDB

ingestion/setup.py, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
Fixes https://github.com/open-metadata/OpenMetadata/issues/19217
Adding ability to use newer confluent-kafka libraries
#
#
=> Fixes 19217: Add ability to use confluent-kafka version greater than 2.1.1

ingestion/src/metadata/ingestion/source/database/sql_column_handler.py, ingestion/src/metadata/profiler/orm/converter/common.py
Fixes #19232
Sampler was failing for postgres array types. There were 2 issues:
1. We were not properly parsing item types of the arrays
2. We were not creating the right ORM column for item types
#
#
=> FIX #19232 - Correct array type mapping in ORM converter

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/impl/SetEntityCertificationImpl.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/impl/SetGlossaryTermStatusImpl.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/util/TestUtils.java
Currently the automated tasks are picking up the user that has last updated the entity and using it for the `updatedBy` value.
This PR aims to change that by introducing the GovernanceBot that will be used when no manual tasks are in place before an automated action takes place. 
#
#
=> MINOR: Add Governance Bot to the workflow automated tasks

openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/index.ts, openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/text-highlight-view.ts, openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx, openmetadata-ui/src/main/resources/ui/src/utils/mocks/EntityUtils.mock.ts
Fix #19077
Worked on highlight search text functionality for description column, as it was not working after implementation of RichTextEditorPreviewerV1 component.
Before:
https://github.com/user-attachments/assets/1b8d5ce3-947e-48e0-b4f6-27cb96a77525
After:
https://github.com/user-attachments/assets/68f73502-0c81-4d88-b8de-ffcfb3878e84
#
#
=> fix(ui): highlight search text functionality for description column

openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable/PipelineActions/PipelineActions.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable/PipelineActions/PipelineActionsDropdown.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable/PipelineActions/PipelineActionsDropdown.tsx, openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchClassBase.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchClassBase.ts, openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
I worked on adding the missing asset-specific filter options for Automator filters
**The tests will be covered in the https://github.com/open-metadata/openmetadata-collate/pull/1069**
#
#
=> Minor: Add missing asset specific filter options for automator filters

openmetadata-docs/content/v1.6.x/deployment/security/saml/azure.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/security/saml/azure.md
Fixes #19162 
I worked on azure saml file correction.
#
#
=> Docs: Azure SAML Correction

openmetadata-service/src/main/java/org/openmetadata/service/search/security/RBACConditionEvaluator.java, openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/RuleEvaluator.java, openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/RuleEvaluatorTest.java
Adding the possibility to define Policies based on the EntityCertification
#
#
=> Add Match Any Certification to Policies

ingestion/src/metadata/ingestion/ometa/routes.py, openmetadata-spec/src/main/resources/json/schema/api/docStore/createDocument.json
Add missing `/docStore` endpoints to OMeta API client routes.
The title of the create document request schema needed to be changed to `CreateDocumentRequest` to match the existing pattern so that the generated pydantic model is appropriately named for the entity/route lookup.
#
#
=> FIX: Add docStore endpoints to Ometa API routes

common/src/main/java/org/openmetadata/annotations/DeprecatedAnnotator.java, common/src/main/java/org/openmetadata/annotations/OpenMetadataAnnotator.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/V112/MigrationUtil.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/V114/MigrationUtil.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v110/MigrationUtil.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v111/MigrationUtilV111.java, openmetadata-spec/src/main/resources/json/schema/api/tests/createTestSuite.json, openmetadata-spec/src/main/resources/json/schema/tests/testSuite.json, openmetadata-ui/src/main/resources/ui/src/generated/api/tests/createTestSuite.ts, openmetadata-ui/src/main/resources/ui/src/generated/tests/testSuite.ts
Following https://github.com/open-metadata/OpenMetadata/pull/19221,  migrations fail because `MigrationUtils` rely on objects which use the old schema that contains deprecated fields.
```java
Failed to db migration due to 
org.openmetadata.service.exception.UnhandledServerException: An exception with message [Failed to process JSON ] was thrown while processing request.
at org.openmetadata.service.util.JsonUtils.readValue(JsonUtils.java:186)
at org.openmetadata.service.migration.utils.v157.MigrationUtil.migrateTableDiffParams(MigrationUtil.java:36)
at org.openmetadata.service.migration.postgres.v157.Migration.runDataMigration(Migration.java:18)
...
aused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "executable" (class …
```
=> FIX: reverted deprecated fields on testSuite

ingestion/src/metadata/ingestion/source/storage/s3/metadata.py, openmetadata-docs/content/partials/v1.6/connectors/storage/manifest.md, openmetadata-docs/content/partials/v1.7/connectors/storage/manifest.md
=> Fix #19160: Add Depth Support for Structured Containers

ingestion/src/metadata/ingestion/source/database/db2/service_spec.py, ingestion/src/metadata/ingestion/source/database/druid/service_spec.py, ingestion/src/metadata/ingestion/source/database/greenplum/service_spec.py, ingestion/src/metadata/ingestion/source/database/hive/service_spec.py, ingestion/src/metadata/ingestion/source/database/impala/service_spec.py, ingestion/src/metadata/ingestion/source/database/mariadb/service_spec.py, ingestion/src/metadata/ingestion/source/database/pinotdb/service_spec.py, ingestion/src/metadata/ingestion/source/database/singlestore/service_spec.py, ingestion/src/metadata/ingestion/source/database/sqlite/service_spec.py, ingestion/src/metadata/ingestion/source/database/teradata/service_spec.py
Added lineage_source_class and profiler_class inside service_spec of different connectors
- Added lineage source class 
- We were facing an error :-
```
File "/opt/airflow/venv-1.6.1/lib64/python3.9/site-packages/metadata/utils/importer.py", line 130, in import_from_module
module_name, obj_name = key.rsplit(MODULE_SEPARATOR, 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
```
- This occured because during the lneage execution the code was expecting a lineage_source_class from service_spec and it got None.
#
#
=> Resolved <NoneType object has no attribute rsplit> issue

ingestion/src/metadata/ingestion/source/database/postgres/queries.py, ingestion/src/metadata/ingestion/source/database/postgres/utils.py, ingestion/tests/unit/topology/database/test_postgres.py
Fixes issue with inability to collect metadata from percona for postgresql server
discussed here: [slack thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1736347276281429)
The only meaningful difference between vanilla postgreSQL and Percona is version string in percona server for postgresql. So commit propose universal and safe way to detect server version by integer string and not complicated parsing of unformatted string.
tested on both postgresql and percona instances, fix is not affecting anything except version check logic in this particular scenario, works the same for vanilla postgreSQL
I worked on it because we need it in out infrastructure and we are using it everyday
#
#
Improvement - no changes in tests and docs necessary
=> Adds percona server for postgresql support

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/TestSuiteIngestion.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddTestCaseList/AddTestCaseList.component.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddTestCaseList/AddTestCaseList.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddTestCaseList/AddTestCaseList.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/DataQualityTab/DataQualityTab.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/DataQualityTab/DataQualityTab.tsx
- Added loading effect while removing test case from test suite
- Added loading effect while adding test case in to test suite
- Added error notification while creating testSuite
https://github.com/user-attachments/assets/9b143bd1-2cb5-4ef3-83bf-415c9d6f96b0
https://github.com/user-attachments/assets/50f88b41-4832-4287-8f2b-4eb0d1e37a3d
#
#
=> Minor: added loading state, and error notification in testSuite.

ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py
Fix #19317: Add MaterializedView & DynamicTable for lineage computation
#
#
=> Fix #19317: Add MaterializedView & DynamicTable for lineage computation

openmetadata-ui/src/main/resources/ui/playwright/constant/conditionalPermissions.ts, openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtils.tsx
I worked on fixing the permission call made for search services with the incorrect resource name
**Before:**
**After:**
#
#
=> Minor: Fix the permissions call made for search service

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/WhatsNewModal.tsx, openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
I worked on changing the localisation key for the `Change Logs` since previous use resulted in a translation where `change` in the `Change Logs` was taken as a verb.
#
#
=> Minor: Change log localization improvement

ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py, ingestion/tests/unit/topology/dashboard/test_looker.py
Fixes [19454](https://github.com/open-metadata/OpenMetadata/pull/19456)
Looker lineage is broken when a table reference is enclosed by backticks (common when using BigQuery).
This addresses that issue.
#
#
=> ISSUE-19454: Fixes broken looker lineage

ingestion/src/metadata/clients/aws_client.py
=> MINOR: fix model dump dict key names (#19484)

openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/CustomizeLandingPage.spec.ts
This PR addresses intermittent test failures for Customize Page Landing ,caused by dynamic elements not being fully loaded before assertions are run. The issue was observed in scenarios where network requests or  dynamic rendering delayed the appearance of widgets on the page after redirection to homepage .
#
#
=> Fix: Failing e2e test for Customize page landing

openmetadata-ui/src/main/resources/ui/src/constants/Navbar.constants.ts, openmetadata-ui/src/main/resources/ui/src/utils/NavbarUtils.tsx
Add handle support click functionality onClick of the support item, which is not a link.
#
#
=> MINOR: Add handle click functionality for menu item

ingestion/src/metadata/ingestion/source/database/bigquery/profiler/system.py
- Wrong dataset and project id pass to system metric query
#
#
Bug fix
=> fix: wrong dataset and project id in filter

openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java, openmetadata-spec/src/main/resources/json/schema/configuration/appsPrivateConfiguration.json, openmetadata-ui/src/main/resources/ui/src/generated/configuration/appsPrivateConfiguration.ts
- added schedule to app private config
- reschedule a schedule application job in quartz if it exists.
#
#
=> MINOR: feat(schedule-application): rescheduling and add schedule to private config

ingestion/src/metadata/ingestion/lineage/masker.py, ingestion/src/metadata/ingestion/lineage/parser.py, ingestion/src/metadata/ingestion/lineage/sql_lineage.py, ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py, ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py, ingestion/src/metadata/ingestion/source/database/lineage_source.py, ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py, ingestion/src/metadata/utils/db_utils.py, ingestion/src/metadata/utils/logger.py, ingestion/tests/unit/test_sql_lineage.py
Fix #19489: Optimise multithreading for lineage
#
#
=> Fix #19489: Optimise multithreading for lineage

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AdvancedSearch.spec.ts
I worked on increasing the test timeout for advanced search playwright tests to avoid AUT flakiness. 
#
#
=> Minor: Fix advanced search playwright flakiness

bootstrap/sql/migrations/native/1.6.3/mysql/schemaChanges.sql, bootstrap/sql/migrations/native/1.6.3/postgres/schemaChanges.sql
Remove apps_data_store since had prebious workflows
#
#
=> Cleanup App data

openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/EntityPageInfos/AnnouncementCard/AnnouncementCard.tsx
- Removed edit owner icon when no owner present
Before
After
- Fixed the display of announcement message, earlier HTML tags were shown with message
Before
After
#
#
=> minor(ui): domain owner edit icon and display of announcement message

openmetadata-ui/src/main/resources/ui/.husky/pre-commit, openmetadata-ui/src/main/resources/ui/generateApplicationDocs.js, openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SearchIndexApplication.spec.ts, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Applications/DataInsightsApplication.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Applications/DataInsightsReportApplication.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Applications/DataRetentionApplication.md, openmetadata-ui/src/main/resources/ui/public/locales/en-US/Applications/SearchIndexingApplication.md, openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppDetails/AppDetails.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppDetails/AppDetails.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationConfiguration/ApplicationConfiguration.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationConfiguration/ApplicationConfiguration.tsx, openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json, openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json, openmetadata-ui/src/main/resources/ui/src/pages/AppInstall/AppInstall.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/AppInstall/AppInstall.test.tsx
Add a documentation panel on Application Configuration Page.
#
#
=> Application doc panel

openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java
=> MINOR: chore(apps): reset error triggers on schedule

ingestion/src/metadata/ingestion/source/database/trino/connection.py
Fixes #19651 
- handle starburst JWToken expiration -- if `is_disconnect` returns True, connection will be invalidated from the pool and a new one created.
#
#
=> ISSUE-19651: handle starburst JWToken expiration

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
Fix #19425: BigQuery External Table with Partition
#
#
=> Fix #19425: BigQuery External Table with Partition

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
This Bug was introduced by PR: https://github.com/open-metadata/OpenMetadata/pull/19423
On that PR we started having more static mappings by using a subset of the same mappings we use for the regular Entities. We failed however to parse the `followers` property to actually fit this mapping and thus any entity with followers is failing to being parsed.
#
#
=> MINOR: Fix followers for Data Insights index

ingestion/src/metadata/ingestion/source/database/db2/connection.py
This PR aims to fix the DB2 license file import by actually turning any escaped special character into the proper character when writing to file.
#
#
=> MINOR: Fix db2 license file import

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/ColumnIndex.java
Removing the `description` check for `columnDescriptionStatus` attribute.
Now it is only checking that all the Columns have description.
#
#
=> MINOR: Remove description check for columnDescriptionStatus

ingestion/src/metadata/ingestion/source/dashboard/powerbi/client.py
Fix #19726  PBI test connection success with bad credentials
#
#
=> Fix #19726 - PBI test connection success with bad credentials

ingestion/src/metadata/ingestion/source/database/snowflake/connection.py, ingestion/src/metadata/ingestion/source/database/snowflake/lineage.py, ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py, ingestion/src/metadata/ingestion/source/database/snowflake/queries.py, ingestion/src/metadata/ingestion/source/database/snowflake/query_parser.py, openmetadata-docs/content/v1.6.x/connectors/database/snowflake/index.md, openmetadata-docs/content/v1.6.x/connectors/database/snowflake/yaml.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/snowflake/index.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/snowflake/yaml.md, openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/snowflakeConnection.json, openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/database/snowflakeConnection.ts
Fix #19635: Snowflake allow custom account_usage schema
#
#
=> Fix #19635: Snowflake allow custom account_usage schema

ingestion/src/metadata/ingestion/lineage/masker.py, ingestion/src/metadata/ingestion/lineage/parser.py, ingestion/src/metadata/ingestion/lineage/sql_lineage.py, ingestion/src/metadata/ingestion/ometa/mixins/query_mixin.py, ingestion/src/metadata/ingestion/source/database/usage_source.py
Fix #19680: mask query method to return none if failed
#
#
=> Fix #19680: mask query method to return none if failed

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineMapper.java, openmetadata-spec/src/main/resources/json/schema/api/services/ingestionPipelines/createIngestionPipeline.json, openmetadata-spec/src/main/resources/json/schema/entity/services/ingestionPipelines/ingestionPipeline.json, openmetadata-ui/src/main/resources/ui/src/generated/api/services/ingestionPipelines/createIngestionPipeline.ts, openmetadata-ui/src/main/resources/ui/src/generated/entity/services/ingestionPipelines/ingestionPipeline.ts
Adds the `IngestionAgent` field to the `IngestionPipeline` schema. The field is a simple entity reference.
There's no db migrations since the field can be null.  
This is required for the Collate's Hybrid ingestion agent feature.
Fixes GEN-2117
#
#
=> MINOR - Hybrid Ingestion Agent - Link ingestion agents to ingestion pipelines

ingestion/src/metadata/ingestion/source/database/unitycatalog/lineage.py
=> MINOR: Fix unity catalog lineage - handle errors

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java
Fixes #19768 
We had some custom logic to delete logical suites in order to not delete test cases. When adding the executable logical suites, I missed this logic. Since the default deletion does not happen, Logical Test Suite children were not deleted.
Adding this logic now
#
#
=> FIX #19768 - Delete pipelines from logical suites at deletion

openmetadata-service/src/main/resources/json/data/governance/workflows/GlossaryApprovalWorkflow.json
Changing the default Glossary Approval Workflow to make independent the Approval Task from the Has Reviewers test.
The way we have it until now there is only one node that sets the status to approved and if the users want to change how either one of the sides behaves, he is unable to change the other side.
Only the default workflow is changed. There are no migrations to avoid messing with any workflow that could have been changed so far, but the new instances should spin up with this improved format.
You can check the difference in the screenshots below.
CURRENT
NEW
#
#
=> Update Glossary Approval Workflow

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/UserDetails.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamsSelectable/TeamsSelectable.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileTeams/UserProfileTeams.component.tsx
**Before:** 
All the teams were not visible for admin.
https://github.com/user-attachments/assets/e148eb73-4f90-4f35-a636-397e97763bb1
**After:** 
Admin can access all the teams to edit in profile page.
https://github.com/user-attachments/assets/7165e140-812a-444f-8d24-f6d7c698d856
#
#
=> Fix: Update teams dropdown for admin

ingestion/setup.py
Fix datadiff version in 1.6.4 prior to releasing collate-data-diff==0.11.4
=> fix datadiff version

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/triggers/PeriodicBatchEntityTrigger.java, openmetadata-service/src/main/resources/json/data/governance/workflows/GlossaryApprovalWorkflow.json
Changing the default Glossary Approval Workflow to make independent the Approval Task from the Has Reviewers test.
The way we have it until now there is only one node that sets the status to approved and if the users want to change how either one of the sides behaves, he is unable to change the other side.
Only the default workflow is changed. There are no migrations to avoid messing with any workflow that could have been changed so far, but the new instances should spin up with this improved format.
Similar to https://github.com/open-metadata/OpenMetadata/pull/19780, but taking into account the changes already in main
#
#
=> MINOR: Update Glossary Approval Workflow

README.md, openmetadata-docs/content/v1.5.x/releases/releases/index.md, openmetadata-docs/content/v1.6.x/releases/releases/index.md, openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
I worked on fixing the incorrect links for the roadmap on the documentation.
#
#
=> Docs: Fix the roadmap link for the collate and OSS docs

openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/yarn.lock
I worked on adding "dompurify" resolution in the package.json since older version was being used in "toast-ui/react-editor" dependency
Ref: https://github.com/open-metadata/OpenMetadata/security/dependabot/196
#
#
=> Fix: dompurify package vulnerability

openmetadata-ui/src/main/resources/ui/package.json, openmetadata-ui/src/main/resources/ui/yarn.lock
I worked on fixing the vulnerability from `jsonpath-plus`. 
Ref: https://github.com/open-metadata/OpenMetadata/security/dependabot/197
#
#
=> Minor: Fix the vulnerability for `jsonpath-plus`

openmetadata-service/src/main/java/org/openmetadata/service/apps/ConfigurationReader.java
We had a `dw` property prefix reader that during Collate app tests it was adding some unwanted parameters that dropwizard (dw) set during the OM test application init
#
#
=> MINOR - Fix collate app yaml reader with unwanted dropwizard java props

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/ServiceIngestion.spec.ts, openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
Issue : #19932
- I worked on fixing the default page size for the Ingestion Page, which was 10 to 15 as the Size changer dropdown.
- Also added support to persist the pagination on browser back
Issue : 
Resolved : 
#
#
=> #19932: fix the default pageSize setting on Ingestions Page

openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionScheduler.java, openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/ServicesStatusJobHandler.java
```java
ERROR [2025-02-24 18:04:43,951] [DefaultQuartzScheduler_QuartzSchedulerThread] o.q.c.ErrorLogger - An error occurred instantiating job to be executed. job= 'status.pipelineServiceStatusJob'
org.quartz.SchedulerException: Failed to create job instance
at org.openmetadata.service.events.scheduled.EventSubscriptionScheduler$CustomJobFactory.newJob(EventSubscriptionScheduler.java:86)
at org.quartz.core.JobRunShell.initialize(JobRunShell.java:128)
at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:403)
Caused by: java.lang.NoSuchMethodException: org.openmetadata.service.events.scheduled.PipelineServiceStatusJob.<init>(org.openmetadata.service.util.DIContainer)
at java.base/java.lang.Class.getConstructor0(Class.java:3585)
at …
```
=> MINOR: use separate quartz scheduler

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
We were getting
```
WARN [2025-02-27 11:23:02,488] [main] o.o.s.r.CollectionRegistry - Encountered exception while initializing resource for class org.openmetadata.service.resources.bots.BotResource
java.lang.reflect.InvocationTargetException: null
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openmetadata.service.resources.CollectionRegistry.createResource(CollectionRegistry.java:300)
at org.openmetadata.service.resources.CollectionRegistry.registerResources(CollectionRegistry.java …
```
=> MINOR - Fix user update roles

openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/index.ts
Updated the URL config for Editor so that clicking on URL will directly navigate to the assigned link.
**Before:**
https://github.com/user-attachments/assets/b2fabd4e-6b89-40f1-bc84-b40a0c3e6fa4
**After:**
https://github.com/user-attachments/assets/90e2bd36-eeba-4330-abb0-114abc1a6a80
#
#
=> Fix: Update block editor url to open when clicked

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
This PR aims to make available on the Data Insigths indexes the following properties:
- tagSources
- descriptionSources
Both attributes hold a map of the amount of tags/descriptions coming from different sources. It could be aggregated directly from ES with something like:
```
{
"size": 0,
"aggs": {
"sum_ingested_descriptions": { "sum": { "field": "descriptionSources.Ingested" } },
"sum_manual_tags": { "sum": { "field": "tagSources.Manual" } }
}
}
```
The important bit is that, due to how ElasticSearch works, you need to know exactly which source type you want to query.
#
#
=> MINOR: Add tag and description Sources to Data Insights

openmetadata-ui/src/main/resources/ui/src/components/Database/SampleDataTable/SampleDataTable.component.tsx, openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts, openmetadata-ui/src/main/resources/ui/src/utils/DocumentationLinksClassBase.ts
This pull request includes changes to update documentation links and constants in the `SampleDataTable` component. The most important changes include replacing the `WORKFLOWS_PROFILER_DOCS` link with `AUTO_CLASSIFICATION_DOCS` and updating the `docs.constants.ts` and `DocumentationLinksClassBase.ts` files to include the new documentation link.
Updates to documentation links:
* [`openmetadata-ui/src/main/resources/ui/src/components/Database/SampleDataTable/SampleDataTable.component.tsx`](diffhunk://#diff-42ceb74d00818c3be7fed72fb995ddf6f64b99078c4602bc2e02358c86bef06dL206-R212): Replaced the `WORKFLOWS_PROFILER_DOCS` link with `AUTO_CLASSIFICATION_DOCS` and updated the label from 'profiler-ingestion' to 'auto-classification'.
* [`openmetadata-ui/src/main/resources/ui/src/constants/docs.cons …
=> MINOR: Modify from Profiler to Auto Classification for sample data

openmetadata-spec/src/main/resources/json/schema/api/domains/createDataProduct.json, openmetadata-ui/src/main/resources/ui/src/generated/api/domains/createDataProduct.ts
The PR fixes #20112, i.e. Creation of Data Product throwing error on not sending domains, which is expected since Data Product cannot be without a domain
This pull request includes a small change to the `openmetadata-spec/src/main/resources/json/schema/api/domains/createDataProduct.json` file. The change adds the "domain" field to the list of required properties in the JSON schema.
* [`openmetadata-spec/src/main/resources/json/schema/api/domains/createDataProduct.json`](diffhunk://#diff-433db411d2509c1e787472cdaf94dab331881738d74557cfdc94c006916e4776L69-R70): Added "domain" to the list of required properties.
=> Fixes-20112: Make domain a required field for Data Product creation

openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.test.ts, openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.ts
- I worked on readding textToHtmlString function which is used in function
#
#
=> readding textToHtmlString function

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsApp.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/DataInsightsSearchInterface.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/IndexTemplate.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/elasticsearch/ElasticSearchDataInsightsClient.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/opensearch/OpenSearchDataInsightsClient.java, openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/DataAssetsWorkflow.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataInsightSystemChartRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java, openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchLineChartAggregator.java, openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchSummaryCardAggregator.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchLineChartAggregator.java, openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchSummaryCardAggregator.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/kpi/KpiResourceTest.java
This PR Aims to add support for ClusterAlias to Data Insights Indexes.
#
#
=> MINOR: Add ClusterAlias to Data Insights indexes

ingestion/setup.py, ingestion/src/metadata/readers/dataframe/parquet.py
Fixes #19619
`s3fs.S3FileSystem` has been replaced with `pyarrow.fs.S3FileSystem` in ParquetDataFrameReader, as:
- it allows `role_arn` as argument, which is not supported by s3fs (hence fixes bug - `assumeRoleArn` was not passed to the filesystem, so it couldn't access the files),
- it's more compatible with ParquetDataFrameReader, which is using pyarrow package anyway,
- s3fs is an unnecessary addition to project dependencies.
#
#
=> Fixes #19619

openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/custom-tests.md
This pull request updates the "Test Result" section in the [Data Quality Observability Custom Tests documentation](https://docs.open-metadata.org/v1.7.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/custom-tests). The changes include:
- Clarifying the JSON payload timestamp format to create and run custom test result.
For more details, refer to the discussion on Slack: [Slack Link](https://openmetadata.slack.com/archives/C02B6955S4S/p1738804777439429)
- Added a comment explaining the Unix timestamp format for writing `TestCaseResults`.
- The Unix timestamp in milliseconds is the correct format that the API accepts, ensuring accurate and consistent test results.
#
#
=> Fix the custom test result timestamp in milliseconds

ingestion/src/metadata/ingestion/source/database/life_cycle_query_mixin.py
I worked on handling cases where `created_at` is `None`. This caused an error when OpenMetadata tried to call `.timestamp()` on `None`.  
To fix this, I added a check before calling `datetime_to_timestamp`, and if `created_at` is `None`,  
it falls back to `datetime.min`. This ensures ingestion does not fail due to missing creation timestamps.
Changes were tested by running metadata ingestion on tables with and without a valid `create_time`.
#
#
=> Fix: Handle NULL created_at

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/dayOneExperience/DayOneExperienceApp.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/triggers/NoOpTrigger.java, openmetadata-service/src/main/resources/applications/DayOneExperienceApplication/openmetadata/DayOneExperienceWorkflow.json, openmetadata-spec/src/main/resources/json/schema/governance/workflows/elements/triggers/noOpTrigger.json
Change how the NoOp Trigger works:
Instead of just doing nothing, it will trigger a workflow, passing all the variables passed to it as GLOBAL variables.
This changes allows NoOp to work similar to other triggers without having to be handled anyway special (We could argue we should change teh name to manual. And eventually imho this should be the raw PeriodicTrigger, but for now it will remain as NoOp)
#
#
=> MINOR: Fix NoOp Trigger Workflow Instance Time Series

ingestion/src/metadata/ingestion/ometa/ometa_api.py, ingestion/tests/integration/ometa/test_ometa_connection_definition_api.py
(No issue opened explicitly)
- At the moment, the [OpenMetadata](https://github.com/fuzmish/OpenMetadata/blob/4a92c760084c680ad1d934146cafe7af87623bcb/ingestion/src/metadata/ingestion/ometa/ometa_api.py#L91) class cannot accept the `extraHeaders` from `OpenMetadataConnection` due to type mismatch.
- I have changed the value to be passed to` ClientConfig` to the raw value (dict), instead of ExtraHeaders object.
#
#
=> Fix: Pass raw value of extraHeaders to ClientConfig

openmetadata-ui/src/main/resources/ui/yarn.lock
Updated yarn.lock to fix the issue from --frozen-lockfile
#
#
=> Fix: --frozen-lockfile run issue

openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts
Fixed an issue where the flaky test "Admin soft & hard delete and restore user from profile page"  was failing to locate the alert-icon due to a page redirection causing the alert to close before it was found.
Fix:-
Updated the  logic to wait for all toast elements (alert-bar, alert-icon, and alert-icon-close) after the delete action. So that the alert elements are detected properly
#
#
=> Fix : Delete user playwright test 

openmetadata-ui/src/main/resources/ui/src/components/AlertBar/AlertBar.tsx, openmetadata-ui/src/main/resources/ui/src/components/AlertBar/alert-bar.style.less, openmetadata-ui/src/main/resources/ui/src/components/PageLayoutV1/PageLayoutV1.tsx, openmetadata-ui/src/main/resources/ui/src/hooks/useAlertStore.ts
Fixed the alert size issues.
#
#
=> Fix: Alert issues

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TypeRepository.java
Minor: Add backend validation on column count when creating table-type custom property
#
#
=> Minor: Add column count validation when creating table-type custom property

openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/WorkflowHandler.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/createAndRunIngestionPipeline/CreateAndRunIngestionPipelineTask.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/flowable/sql/SqlMapper.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/flowable/sql/UnlockExecutionSql.java, openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/flowable/sql/UnlockJobSql.java, openmetadata-spec/src/main/resources/json/schema/configuration/workflowSettings.json, openmetadata-ui/src/main/resources/ui/src/generated/configuration/workflowSettings.ts
We had a short `jobLockTimeInMillis` default in order to be able to rapidly retry a Task if the server crashed in the middle of it.
Sadly this does not work as expected as after the lock expires, flowable picks the task again, even if it is indeed running. This was causing long running tasks to endlessly retrigger.
In order to fix this we did the following:
1. Increase the `jobLockTimeInMillis` from 5min to 15 days, to guarantee no tasks would be retried while running.
2. Implemented a `unlockJobsOnStartup()` method that would reset the lock manually on startup, getting any task ready to be picked up by any executor.
#
#
=> MINOR: Fix LongRunning Steps Retriggering Endlessly

openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/data-asset-header.less, openmetadata-ui/src/main/resources/ui/src/components/Database/RetentionPeriod/RetentionPeriod.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/RetentionPeriod/retention-period.less, openmetadata-ui/src/main/resources/ui/src/components/Metric/MetricHeaderInfo/metric-header-info.less, openmetadata-ui/src/main/resources/ui/src/components/common/DomainLabel/domain-label.less, openmetadata-ui/src/main/resources/ui/src/components/common/OwnerLabel/owner-label.less
Fixed Data Asset Header wrapping issue and updated styling for the retention period edit button.
Before:
After
=> Minor : Fixed header component Wrapping

openmetadata-ui/src/main/resources/ui/src/utils/EntityVersionUtils.tsx
I worked on glossary inside newly created term when user click on version it was displayed the term has been reject but in actual it was in review
Before
https://github.com/user-attachments/assets/bd9e614d-84be-46da-b7e2-96370a647a21
After
=> Minor :fixed Glossary Label condition

openmetadata-ui/src/main/resources/ui/src/utils/DomainUtils.tsx
Fixed the Domain Assets issue in which assets which are part of NewDomain2 was appearing under NewDomain.
**Before:**
https://github.com/user-attachments/assets/3b09a0c1-71fc-460f-ad99-69b8979e6ca8
**After:**
https://github.com/user-attachments/assets/36c1fe3f-45db-4f28-8588-54c9f7b2f8e1
#
#
=> fix(ui): Update query to fix domain asset

ingestion/src/metadata/ingestion/source/storage/s3/metadata.py
S3 ingestion has an empty `logger.warning()` statement that fails the entire ingestion, as the log requires message.
Warning has been deleted - the error is added to list of failures, so additional log is redundant.
#
#
=> [fix] deleted empty warning from s3 ingestion

openmetadata-ui/src/main/resources/ui/src/pages/AddServicePage/AddServicePage.component.tsx, openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts
Add extra info to be called in service page from the ServiceUtilClassBase.
#
#
=> Add extra info in add service page

ingestion/src/metadata/profiler/orm/functions/median.py
- Switched to approx percentile for dbx. Conducting small test, accuracy of approx percentile (even on small dataset ~20K rows) seems to be on part with percentile count
- approx percentile will use t-digest algorithm providing better computational efficiency 
#
#
Improvement
=> FIX: switch dbx to approx_percentile

openmetadata-ui/src/main/resources/ui/playwright/utils/domain.ts
The ingestion bot test "Ingestion bot should be able to access domain specific domain" was experiencing flaky behaviour during domain selection, specifically in the "Assign assets to domains" step. The test would sometimes fail because it was checking the domain header before the page had fully loaded.
Added a wait for the loading state to complete  after the domain selection.
#
#
=> Fix : AUT failure for Ingestion bot

openmetadata-ui/src/main/resources/ui/src/components/IncidentManager/IncidentManager.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/IncidentManager/IncidentManager.test.tsx
Enhance IncidentManager date filtering and update table column title
- Updated date filtering logic to use getStartOfDayInMillis and getEndOfDayInMillis for improved accuracy.
- Changed table column title from 'execution-time' to 'last-updated' for better clarity.
- Added additional mocks in tests for user and team search APIs to ensure proper functionality during testing.
=> Fix: IncidentManager date filtering and update table column title

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/entity-lineage.style.less
I have worked on lineage full screen 
Before
After
#
=> Fixed lineage full screen

openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx, openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts
Updated the Test connection workflow data to have the ingestionRunner outside of config.
#
#
=> MINOR: Ingestion Runner Updates

openmetadata-ui/src/main/resources/ui/src/components/SearchSettings/EntitySeachSettings/EntitySearchSettings.tsx, openmetadata-ui/src/main/resources/ui/src/pages/SearchSettingsPage/SearchSettingsPage.tsx
Worked on breakage of search settings page due to empty allowedFieldValueBoostValues
Before
After
#
#
=> fix(ui): search rankings page breakage

common/src/main/java/org/openmetadata/common/utils/CommonUtil.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/lineage/LineageResourceTest.java
This pr optimises the logic of validating column lineage from O(n^2) to O(n)
Before the fix
After the fix
#
#
=> MINOR: Improve column validation logic in lineage API

openmetadata-ui/src/main/resources/ui/playwright/constant/delete.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/ApiServiceRest.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/EntityVersionPages.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/ServiceEntityVersionPage.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/serviceIngestion.ts
I worked on increasing the timeout for delete toast verification for entities, which might take more time for the delete operation to complete
#
#
=> Chore(ui): Increase timeout for delete toast verification

openmetadata-spec/src/main/resources/json/schema/system/indexingError.json, openmetadata-ui/src/main/resources/ui/src/generated/system/indexingError.ts
Introduced by https://github.com/open-metadata/OpenMetadata/pull/20636
Backward compatibility for failed app run records
https://github.com/open-metadata/OpenMetadata/blob/e2a3eb823a260218cea2dd5773577c210cb90511/openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/OmAppJobListener.java#L147
We should remove these entries from the db using migrations.
Followed up by https://github.com/open-metadata/OpenMetadata/issues/20753
```
025-04-10 11:08:04.145	 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1160] (through reference chain: org.openmetadata.schema.entity.app.AppRunRecord["failureContext"]->org.openmetadata.schema.entity.app.FailureContext["failure"]->org.openmetadata.schema.system.IndexingError["jobStackTrace"]) …
```
=> fix: enable additional properties for indexingError.json

openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts
This PR fixes playwright test  'Check permissions for Data Steward ' of  User.spec
The test was failing because it was not able to find the table checkbox in Assets Filter. The cause of this issue was the aggregate call with size limit 10 happening before the query call sometimes.(which was not having  table in response).
As a fix for this test, have added wait for the query api call.
#
#
=> Fix: User playwright test

openmetadata-ui/src/main/resources/ui/playwright/utils/tag.ts
This PR fixes flaky test 'Add and Remove Assets' of Tag.spec
The test was failing sometimes because it was trying to find the count of assets before the count was updated properly .
As a fix for this have added networkidle before checking the count.
#
#
=> Fix: Tags flaky playwright test

openmetadata-ui/src/main/resources/ui/src/components/DataAssetSummaryPanel/DataAssetSummaryPanel.tsx, openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.test.tsx
This PR fixes the additional  permissions api call happening in the Summary Components (Table Summary and DataAssetsSummaryPanel)
Issue:-
https://github.com/user-attachments/assets/b7ad3449-263f-4bf7-8b68-dbbc46e57a80
Fix
https://github.com/user-attachments/assets/bbf47214-50a5-4799-a32c-7237b35ea8e5
#
#
=> Fix: Additional permissions call happening in summary components

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
This PR fixes flaky test 'Create and Assign Task with Suggestions' in ActivityFeed.spec.ts .
The test was flaky because it was checking task counts after the page was closed sometimes. Fixed the flakiness by adding missing `await` for task count verification.
Issue
#
#
=> Fix : Flaky Activity feed playwright test

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseResultRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseIndex.java, openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseResultIndex.java
Fixes #20962 && fixes #21121
**What**
- Do not consolidate test case and test suite change events 👉 in local tests, I see change events being consolidated, where the change to the status goes from success to failed but is reverted to success (or inversingly) and hence the alerts is either triggered for a successful test or not triggered for a failing 
**[Maybe a better way to handle it than defaulting to False?]**
- record change to testCase testCaseResult field
- remove non-indexable fields on testSuites field
#
#
=> ISSUE #20962 - Issues with test case alerts

openmetadata-ui/src/main/resources/ui/src/components/common/InheritedRolesCard/InheritedRolesCard.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/RolesCard/RolesCard.component.tsx, openmetadata-ui/src/main/resources/ui/src/styles/components/card.less
Issue:-
The addition of 'new-header-border-card' class was causing this issue, since this class had
` &:not(.expanded) {
.ant-card-body {
height: 0 !important;
overflow: hidden;
padding: 0;
}
}`
Roles are not getting displayed in the roles and inherited  roles widget for bots page.
https://github.com/user-attachments/assets/392a0336-462b-4192-9ebd-b08a6cb1e06c
Fix:-
Fixed it referring the design on sandbox currently
https://github.com/user-attachments/assets/d6b77aa0-403b-4797-b131-34362834f7b3
#
#
=> fix(ui): Edit and display roles issue for bot page

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkEditEntity.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/EntityRightCollapsablePanel.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/support/entity/DatabaseClass.ts
Playwright fix: 
- ServiceEntity
- EntityRightCollaspablePanel
- BulkEdit- Table
#
#
=> fix the entityRightPanel and serviceEntity playwright spec

openmetadata-spec/src/main/resources/json/schema/entity/services/connections/messaging/redpandaConnection.json, openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/messaging/redpandaConnection.ts
Fix #19383: Fix AttributeError in redpanda connector
#
#
=> Fix #19383: Fix AttributeError in redpanda connector

openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/generic-widget.less, openmetadata-ui/src/main/resources/ui/src/pages/CustomizeDetailsPage/customize-details-page.less, openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/FrequentlyJoinedTables/FrequentlyJoinedTables.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/PartitionedKeys/PartitionedKeys.component.tsx, openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/TableConstraints.tsx, openmetadata-ui/src/main/resources/ui/src/utils/GenericWidget/GenericWidgetUtils.tsx
Fixes #21405
1. Overflow issue for widgets 
Issue
Fix:
https://github.com/user-attachments/assets/bbc9fc6a-6835-4be5-b5d7-36a68bd20772
2. Border issue for the widgets header cards
Issue:
Fix:
3. Removed expand collapse nested card for widgets which had nested expand collapse cards
1.Data Products widget
Current Data Products widget
Fix:-
2. Frequently Joined Tables Widget
issue
Fix
3. Partioned Keys and Table Constraints
Fix
https://github.com/user-attachments/assets/0e7cf160-5eb5-4637-aa7f-9ab8b51d8cf0
https://github.com/user-attachments/assets/63a9a9e9-7278-43be-a9f1-3e7208204eb0
Entity Page and Version Page rendering the widgets as per expand collapse card (unaffected)
https://github.com/user-attachments/assets/3b6333cf-edb3-4f88-b757-bde8bd5eb116
Impacted areas:-
GenericTabWidgets in …
=> Fix(ui) : Persona customization widgets style issues

ingestion/src/metadata/pii/algorithms/classifiers.py, ingestion/src/metadata/pii/algorithms/presidio_patches.py, ingestion/tests/unit/pii/algorithms/data/pii_samples.py, ingestion/tests/unit/pii/algorithms/test_feature_extraction.py
Fixes #21464 
I worked on improving datetime extraction by introducing a patch over Presidio's existing implementation. Presidio's native datetime extraction often produces false positives on datetimes (e.g., 60001 is marked as a datetime, due to its regular expression-based approach). To address this, I added an extra verification layer that attempts to parse detected date strings into actual datetime objects using the `dateutil` library, filtering out invalid or ambiguous extractions.
I tested the changes by running the patched extraction pipeline on a series of sample texts containing valid and invalid date formats. This improved accuracy by reducing false positives, though it does not target or resolve existing false negatives.
#
#
=> FIX #21464

ingestion/src/metadata/sampler/sqlalchemy/azuresql/sampler.py, ingestion/src/metadata/sampler/sqlalchemy/mssql/sampler.py, ingestion/src/metadata/sampler/sqlalchemy/sampler.py, ingestion/src/metadata/sampler/sqlalchemy/snowflake/sampler.py
Fixes error when running row sampling:
**What**
If user uses randomized row sampled we need to perform a fullscan of the table so we can get `rand n/total_rows`. That full scan did not include the partitioning logic result in partition errors
#
#
Bug fix
=> MINOR: row sampling error

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java, openmetadata-service/src/main/java/org/openmetadata/service/util/EntityRelationshipCleanup.java, openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java, openmetadata-service/src/test/java/org/openmetadata/service/util/EntityRelationshipCleanupTest.java
=> Fix #21533 - Add a tool to openmetadata-ops.sh to delete orphaned relations

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/TaskFeedCard/TaskFeedCardNew.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ProfilerSettingsModal/ProfilerSettingsModal.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/user-team-selectable-list.less
Fixes [#21517](https://github.com/open-metadata/OpenMetadata/issues/21517#top)
Problem :
(misaligned icon)
Solution:
https://github.com/user-attachments/assets/c6e735e3-2d52-46d8-a63c-e6f70d5f2068
#
#
=> Fix #21517: Last user not visible || profile config icon miss aligned

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx
Fixes glossary playwright, as permission changes not yet picked for dot release.
#
#
=> fix glossary playwright tests

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TeamsDragAndDrop.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Metric.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataInsightReportApplication.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/EntityVersionPages.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/ServiceEntityVersionPage.spec.ts
This pull request focuses on improving Playwright test suites for the OpenMetadata UI by enhancing test reliability, introducing reusable user management utilities, and updating version-related tests. The most significant changes include replacing hardcoded storage states with dynamic admin user login, improving network and UI state checks, and updating version-related assertions.
* [`openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TeamsDragAndDrop.spec.ts`](diffhunk://#diff-298d80ddbd49d6371cff7c556829ae5b21239fbf0c116204701c3d41c56f0f3fL104-R108): Replaced `waitForResponse` with `waitForLoadState('networkidle')` and added a check for loader detachment to ensure UI stability before proceeding.
* [`openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Metric.spec.ts`](dif …
=> PLAYWRIGHT: fix delete async alert on other playwright test causing failure

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/generic/GenericPublisher.java
- Align alert message with Content-Type  (i.e. application/json -> json message)
#
#
=> MINOR: Alert test message type

openmetadata-service/src/main/resources/elasticsearch/en/query_cost_record_index_mapping.json, openmetadata-service/src/main/resources/elasticsearch/jp/query_cost_record_index_mapping.json, openmetadata-service/src/main/resources/elasticsearch/zh/query_cost_record_index_mapping.json
Fixes 
```
[errorSource]: Sink
[message]: Issues in Sink to OpenSearch: [org.openmetadata.schema.system.EntityError@10cfd0b[message=OpenSearchException[OpenSearch exception [type=illegal_argument_exception, reason=DocValuesField "query.query" is too large, must be <= 32766]],entity=update {[query_cost_record_search_index][804181ea-d22e-40d6-aa34-3f9723995c34], doc_as_upsert[true], doc[index {[null][null], source[n/a, actual length: [57.7kb], max length: 2kb]}], scripted_upsert[false], detect_noop[true]}]]
[failedEntities]:
[0]:
[message]: OpenSearchException[OpenSearch exception [type=illegal_argument_exception, reason=DocValuesField "query.query" is too large, must be <= 32766]]
[entity]: update {[query_cost_record_search_index][804181ea-d22e-40d6-aa34-3f9723995c34], doc_as_upsert[true], …
```
=> Fix : query_cost_record_search_index Search reindexing issue

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- Guava Cache always returns the same instance of the object, until the object is evicted/invalidated people are always using instance that have been played with
- We are return a copy of the original instance from the cache, to avoid changes to the cached copy
#
#
=> fix: Fix Cache To have immutable entities

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/TaskFeedCard/TaskFeedCardNew.component.tsx
Issue
The condition `feed?.postsCount && feed?.postsCount > 0`  was returning 0 and not false in case of postsCount being 0, due to which the count 0 was been shown as 0.
Fix
https://github.com/user-attachments/assets/8725fa2d-aeb0-4d3b-8754-8bc63f14f8e8
#
#
=> Fix(ui): Reply count being shown as 0 in task feed card

.github/workflows/typescript-type-generation.yml
I fixed the yml error in the template action file and ability to trigger it for a specific branch.
Necessary for testing [Chore: Add github action to generate and commit types based on schema changes](https://github.com/open-metadata/OpenMetadata/pull/21796#top)
#
#
=> Fix the error in the template yml and add ability to trigger it from specific branch

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
=> fix(test): Close and comment task failure

ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py
The `metadata ingest-dbt` command failed to ingest DBT artifacts into the OpenMetadata service due to missing _.json_ files. The root cause was the use of backslashes (\) in one of the Python scripts, which led to incorrect path resolution for Windows OS.
#
#
=> fix: cross-platform path resolution for dbt ingestion (on Windows)

ingestion/src/metadata/ingestion/source/database/databricks/connection.py, ingestion/tests/unit/topology/database/test_databricks.py
Currently when a catalog in databricks does not contain the `default` schema it fails with the following error 
sqlalchemy.exc.DatabaseError: (databricks.sql.exc.ServerOperationError) [SCHEMA_NOT_FOUND] The schema `demo-test-cat`.`default` cannot be found. Verify the spelling and correctness of the schema and catalog.
this pr tries to fix that
#
#
=> MINOR: Fix databricks default schema issue

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AutoPilot.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ServiceBaseClass.ts, openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.test.tsx, openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
Fixes #21401 
I worked on the following:
#
#
=> Fix#21401: Auto pilot trigger button enable and improve test coverage

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkImport.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/importUtils.ts
Updated the Playwright test for the bulk import feature to improve reliability.
Previously, the test intermittently failed because the first cell of the last row was not focused within the expected time.
This has been addressed by explicitly waiting for the correct focus before proceeding with assertions.
=> Playwright Update: Bulk Import

openmetadata-ui/src/main/resources/ui/playwright/utils/importUtils.ts
- I worked on  fixing the flaky glossary bulk edit failure around the owner's tab
#
#
=> PLAYWRIGHT: fix the flaky glossary bulk edit failure

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts, openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.test.tsx, openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
- I worked on fixing the cycle lineage nodes when being collapsed
- Restrict the RootNode to be removed when collapsed is perform on cycle lineage, as when collapsing it drop down to the root node to remove it, which create imbalance on the flow!
https://github.com/user-attachments/assets/329c7015-b2b3-44d4-a4f3-82b2caac4336
#
#
=> fix the cycle lineage nodes when being collapsed

openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
Fix failure due to config not read in tests
#
#
=> [Minor] - Fix Test Failures due to config not read in app tests

openmetadata-docs/content/v1.7.x/deployment/security/keycloak/kubernetes.md, openmetadata-docs/content/v1.8.x/deployment/security/keycloak/kubernetes.md, openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/security/keycloak/kubernetes.md
The KeyCloak URLs were incorrect for the current version of KeyCloak, and additionally the documentation was missing the required key to enable OIDC.
=> (Docs) Correct URLs and Enable OIDC

openmetadata-ui/src/main/resources/ui/src/components/Entity/Task/TaskTabIncidentManagerHeader/TasktabIncidentManagerHeaderNew.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/UserPopOverCard.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/UserPopOverCard.tsx
Issue:-
Team redirection not working on User popover card
https://github.com/user-attachments/assets/c1b445c0-1852-4a03-a522-e2cd1f24807c
Fix
https://github.com/user-attachments/assets/41899199-98de-462c-9519-ba5556c88278
#
#
=> fix(ui): User popover card team redirection issue

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/CuratedAssets.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ExploreSortOrderFilter.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tags.spec.ts
Fixes playwright tests
1. CuratedAssets.spec
2. ExploreSortOrderFilters.spec
3. Tags.spec
#
#
=> fix AUT tests

ingestion/src/metadata/utils/bigquery_utils.py
Fixes #22619 
This pull request refactors type hinting and import handling in the `bigquery_utils.py` utility module to improve static analysis and avoid unnecessary runtime imports. The main focus is on using `TYPE_CHECKING` for conditional imports and updating type annotations for better compatibility.
Type hinting and import improvements:
* Added a conditional import for `bigquery` using `TYPE_CHECKING` to ensure that the import only occurs during static type checking, reducing runtime overhead.
* Changed the return type annotation of `get_bigquery_client` to use a string literal `"bigquery.Client"` for forward compatibility with type checking.
Runtime import adjustment:
* Moved the import statement for `bigquery` inside the `get_bigquery_client` function to ensure the module is only …
=> MINOR: Refactor BigQuery client type hinting in bigquery_utils.py

openmetadata-service/src/main/java/org/openmetadata/service/resources/types/TypeResource.java
This pull request updates the documentation and API descriptions for custom property management in OpenMetadata. The changes clarify that the API is intended for creating custom property definitions using existing data types, not for defining new custom data types.
API documentation and description updates:
* Updated the main API tag description in `TypeResource.java` to specify that the APIs are for managing custom property definitions using existing data types, and do not support creating new custom data types.
* Revised the `createType` endpoint summary and description to clarify that it creates custom property definitions (templates) using existing OpenMetadata data types, and updated the response description accordingly.
=> MINOR: Modify Documentation for metadata/types api

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Dashboards.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DashboardChartTable/DashboardChartTable.tsx, openmetadata-ui/src/main/resources/ui/src/constants/constants.ts, openmetadata-ui/src/main/resources/ui/src/utils/DashboardDetailsUtils.tsx
Fixes #22345
**Summary**
Implements a toggle functionality to show both deleted and non-deleted charts on dashboard pages. This feature provides users with the ability to view soft-deleted charts alongside active ones, similar to the functionality available on other entity pages.
**Problem**
Currently, dashboard pages only display non-deleted charts. Users have no way to view soft-deleted charts that were removed when a dashboard was deleted, limiting visibility into the complete chart inventory.
**Solution**
Added a toggle switch in the dashboard chart table that allows users to:
- Toggle OFF (Default): Show only active/non-deleted charts
- Toggle ON: Show only soft-deleted charts
- Auto-default behaviour: When the parent dashboard is deleted, the toggle automatically defaults to showing …
=> feat(ui): allow toggle to see both deleted and non-deleted chart on dashboard page

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java, openmetadata-service/src/main/java/org/openmetadata/service/security/mask/PIIMasker.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
Fixes https://github.com/open-metadata/openmetadata-collate/issues/1883
This PR fixes inconsistent visibility of **PII-Sensitive** information in the **Data Observability → Column Profile** UI:
* **Unauthorized users** (without PII permission) could view the **column detail** profile, even though the **overview** properly masked it.
* **Authorized users** (admins or owners) could see sensitive column profiles in the **detail** view, but not consistently in the **overview**.
* **Centralized PII authorization logic** by moving the `authorizePII` check into `PIIMasker`, ensuring it uses the latest authorization patterns from the `Authorizer` class.
* **Refactored** `PIIMasker.getTableProfile(...)` to accept the **fully qualified table name (FQN)**, so it can fetch the correct `owners` for …
=> Fix Consistent masking of PII in table column profiling

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/processors/DatabaseServiceTablesProcessor.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/security/mask/PIIMasker.java
* **DatabaseServiceTablesProcessor**
Replaced the call to `TableRepository#getLatestTableProfile` with a direct DAO call (`profilerDataTimeSeriesDao#getLatestExtension`). This avoids relying on overloaded repository methods and removes the need for a `SecurityContext` in the processor.
* **TableRepository**
Inlined `getLatestTableProfileInternal` into a single method. The logic is now self-contained: it fetches the latest profile JSON, attaches it to the table, populates tags, applies column profiling (if requested), and applies masking through `PIIMasker`.
* **PIIMasker**
Inlined `maskColumnsIfNotAuthorized` into `getTableProfile`. Masking is now handled directly in the main method for clarity and simplicity.
This refactor reduces indirection, simplifies the call chain, and removes the …
=> Refactor DatabaseServiceTablesProcessor and simplify getLatestTableProfile logic

ingestion/src/metadata/profiler/interface/sqlalchemy/databricks/profiler_interface.py, ingestion/src/metadata/profiler/interface/sqlalchemy/unity_catalog/profiler_interface.py, ingestion/src/metadata/profiler/metrics/system/databricks/system.py, ingestion/src/metadata/sampler/sqlalchemy/databricks/sampler.py, ingestion/src/metadata/sampler/sqlalchemy/unitycatalog/sampler.py, ingestion/src/metadata/utils/logger.py, ingestion/tests/unit/sampler/sqlalchemy/test_unitycatalog_sampler.py
This pull request introduces improvements and bug fixes to the Databricks and Unity Catalog profiler and sampler interfaces, enhancing compatibility with catalog-aware operations and improving the handling of special characters in database identifiers. The most significant changes include correct quoting of table references with hyphens, ensuring the catalog is set for each session, and refactoring the Unity Catalog sampler to inherit from the Databricks sampler for code reuse.
**Databricks/Unity Catalog compatibility and session management:**
* Added `visit_table` method to `DatabricksProfilerInterface` to correctly quote database, schema, and table names containing hyphens, ensuring compatibility with Unity Catalog and Databricks table references.
* Updated session creation in both …
=> Minor: Fix Databricks & Unity Catalog, Table or View Not found

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PersonaRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java, openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/PersonaDeletionUserProfile.spec.ts
=> handle persona deletion and relations fetch when entitynotfoundexceptoin is thrown

openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v196/Migration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v196/Migration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v196/MigrationUtil.java
Renamed migration classes and utilities to v196 for MySQL and PostgreSQL.
=> Rename migration files from v195 to v196

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DirectoryRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FileRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SpreadsheetRepository.java, openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/WorksheetRepository.java
Fixes setInherited fields for file,directory, spreadsheet and worksheet
#
#
=> Fix: setInheritedFields for spreadsheet, worksheet, file, directory

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JSONSchemaTemplate/ObjectFieldTemplate.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JSONSchemaTemplate/ObjectFieldTemplate.tsx
Fixed the advanced configs in the add service form restricting the next steps if there are required fields present
**Before:**
https://github.com/user-attachments/assets/93d6010d-ddaa-412e-a0d6-aebc5e24d9d2
**After:**
https://github.com/user-attachments/assets/44d8c13e-5865-42e9-9304-77269e02b1d4
=> Fix the advanced config in service form restricting the next action

openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/IngestionBot.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataContracts.spec.ts
- fix the DataContract and IngestionBot playwright flaky test
#
#
=> PLAYWRIGHT : fix the DataContract and IngestionBot playwright flaky test

openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ServiceBaseClass.ts
This pull request makes a small change to the ingestion pipeline test logic by removing the code that checks for failed pipeline statuses and logs their output to the console. This simplifies the test code and eliminates unnecessary logging during test runs.
=> playwright: remove logging for failed ingestion pipelines in ServiceBaseClass

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AdvancedSearch.spec.ts, openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ApiIngestionClass.ts, openmetadata-ui/src/main/resources/ui/playwright/utils/observabilityAlert.ts
=> Chore(UI): Fix the AUT flakiness in NotificationAlert and ServiceIngestion specs

ingestion/src/metadata/pii/algorithms/classifiers.py, ingestion/src/metadata/pii/algorithms/presidio_recognizer_factory.py, ingestion/src/metadata/pii/algorithms/presidio_utils.py, ingestion/src/metadata/pii/processor_factory.py, ingestion/src/metadata/pii/tag_analyzer.py, ingestion/src/metadata/pii/tag_processor.py, ingestion/src/metadata/workflow/classification.py, ingestion/tests/unit/metadata/pii/test_classifiers.py, ingestion/tests/unit/metadata/pii/test_presidio_utils.py, ingestion/tests/unit/metadata/pii/test_tag_processor.py, ingestion/tests/unit/pii/algorithms/test_presidio_utils.py
Builds on top of #23289 
I've added a new `TagProcessor` and downstream code required to use all tag recognizers from OM a build `presidio` recognizers, somewhat replacing the static configuration used in `PIIProcessor`.
I've added new test cases that describe the use case this PR includes.
This includes testing that PII tags configured with the appropriate recognizers are selected accordingly
#
#
#
I'll have to update the PR upstream to include certain changes after discussing with Harsha
=> Use tag's recognizers configuration to classify columns

ingestion/src/metadata/profiler/orm/converter/converter_registry.py, ingestion/src/metadata/profiler/orm/converter/trino/__init__.py, ingestion/src/metadata/profiler/orm/converter/trino/converter.py, ingestion/src/metadata/profiler/orm/types/__init__.py, ingestion/src/metadata/profiler/orm/types/trino.py, ingestion/tests/integration/trino/conftest.py, ingestion/tests/integration/trino/data/complex_and_simple.sql, ingestion/tests/integration/trino/data/only_complex.sql, ingestion/tests/integration/trino/test_classifier.py, ingestion/tests/integration/trino/test_metadata.py, ingestion/tests/integration/trino/test_profiler.py
Fixes #16983
I worked on fixing the Trino sampler to properly handle complex data types (structs, arrays, maps) because OpenMetadata was failing to ingest sample data for Hive tables containing these types when using Trino as the data source.
The Trino Python client returns `NamedRowTuple` objects for struct types, which Pydantic couldn't serialize, causing the sampling process to fail with "Error trying to ingest sample data for table". This prevented users from previewing sample data, running classification workflows, or having complete data discovery for tables with complex schemas.
- Added `TypeDecorator`s that handle `trino.types.NamedRowTuple`s
- Added integration tests covering classification, profiling, and metadata ingestion for tables with complex types
- Tested locally with …
=> FIxes #16983: can't sample data from trino tables with complex types

openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionRecentRun/IngestionRecentRun.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionRecentRun/IngestionRecentRuns.component.tsx
This pull request enhances the sorting and display logic for recent ingestion pipeline runs in the `IngestionRecentRuns` component. The main improvement is ensuring that runs are consistently sorted by their `timestamp` (handling missing values gracefully), and only the most recent five runs are shown. Comprehensive tests have been added to validate this behavior.
**Sorting and Display Logic Improvements:**
* Updated the logic in `IngestionRecentRuns.component.tsx` to sort pipeline runs and app runs by their `timestamp` values in ascending order (treating missing timestamps as `0`), then select the last five runs for display. This ensures the most recent runs are always shown, regardless of the original order or missing timestamps. …
=> Improve timestamp sorting logic in IngestionRecentRuns component

openmetadata-ui/src/main/resources/ui/src/components/common/AirflowMessageBanner/AirflowMessageBanner.test.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/AirflowMessageBanner/AirflowMessageBanner.tsx
I worked on adding logic to display the platform info banner, even in cases where the status is 200, and the API response contains `reason` for the `Hybrid` platform.
Earlier, we used to show the banner if the platform API status was not 200. This change is to fulfil the requirements of https://github.com/open-metadata/openmetadata-collate/pull/2054
=> Improvement(UI): Platform info banner logic update

openmetadata-service/src/main/java/org/openmetadata/service/util/SchemaFieldExtractor.java, openmetadata-service/src/test/java/org/openmetadata/service/resources/metadata/TypeResourceTest.java
Fix: /metadata/types/fields/{entityType} to check for in definition references as well
Previously for table, we received the below which is wrong
```
{
"name": "columns",
"displayName": "columns",
"type": "array<string>",
"customPropertyConfig": null
}
```
After the fix, we receive columns and their nested refs like description, displayName etc etc
```
{
"name": "columns",
"displayName": "columns",
"type": "array<column>",
"customPropertyConfig": null
}
```
#
#
=> Fix TypeResource to handle inDefinition references

openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomainForm/AddDomainForm.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/common/IconPicker/IconPicker.constants.ts, openmetadata-ui/src/main/resources/ui/src/components/common/IconPicker/IconPicker.interface.ts, openmetadata-ui/src/main/resources/ui/src/components/common/IconPicker/MUIIconPicker.tsx
Updated default icon for Add domain and data product
|  <img width="642" height="634" alt="Screenshot 2025-09-30 at 5 09 34 PM" src="https://github.com/user-attachments/assets/a2ca8306-bf7e-4f3c-8f8c-1ac2bb632415" /> | <img width="642" height="634" alt="Screenshot 2025-09-30 at 5 09 43 PM" src="https://github.com/user-attachments/assets/22c19dd5-2d75-42c7-806c-c4c3334b3b40" /> |
|---|---|
#
#
=> Add default icons for domains and data product

ingestion/src/metadata/data_quality/validations/runtime_param_setter/base_diff_params_setter.py, ingestion/src/metadata/data_quality/validations/runtime_param_setter/table_diff_params_setter.py, ingestion/src/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py, ingestion/src/metadata/ingestion/source/database/common/data_diff/databricks_base.py, ingestion/src/metadata/ingestion/source/database/databricks/data_diff/__init__.py, ingestion/src/metadata/ingestion/source/database/databricks/data_diff/data_diff.py, ingestion/src/metadata/ingestion/source/database/databricks/service_spec.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/data_diff/__init__.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/data_diff/data_diff.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/service_spec.py, ingestion/src/metadata/profiler/orm/registry.py, ingestion/tests/unit/metadata/data_quality/test_table_diff_param_setter.py
This pull request introduces enhanced support for Databricks and Unity Catalog connections in the data diff functionality, refactors connection handling to improve extensibility, and updates the parameter setter logic to accommodate these new connection types. The changes also include codebase improvements for clarity and maintainability.
**Databricks and Unity Catalog support:**
* Added `DatabricksBaseTableParameter` as a shared base class for Databricks-based data diff operations, which builds connection URLs correctly for Databricks and Unity Catalog services. (`ingestion/src/metadata/ingestion/source/database/common/data_diff/databricks_base.py`)
* Implemented `DatabricksTableParameter` and `UnityCatalogTableParameter` classes, delegating connection logic to the shared base class for …
=> feat: Add Unity Catalog data diff module to use DBX connection instead of workspaceclient

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts, openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationFeedCard.component.tsx, openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationFeedCard.test.tsx, openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.tsx
Fixes #23223 and #23042
Fix NotificationFeedCard to show actual mentioning user and timestamp and redirection glitch on Activity Feed for notification feeds.
Problem
The NotificationFeedCard component was incorrectly displaying the thread creator (createdBy) and thread creation timestamp
instead of the actual user who made the mention and when the mention occurred. This caused confusion in notification feeds
where users would see outdated information like "admin mentioned you 15 days ago" when it was actually "stevegreen" who
mentioned them "just now".
Root Cause
In NotificationBox.component.tsx, the notification dropdown logic was using:
- feed.createdBy (original thread creator) instead of the actual mentioning user
- feed.threadTs (thread creation time) instead of when the mention was …
=> fix(ui): mentions in notification box

ingestion/src/metadata/pii/algorithms/classifiers.py, ingestion/src/metadata/pii/algorithms/presidio_recognizer_factory.py, ingestion/src/metadata/pii/algorithms/presidio_utils.py, ingestion/src/metadata/pii/processor_factory.py, ingestion/src/metadata/pii/tag_analyzer.py, ingestion/src/metadata/pii/tag_processor.py, ingestion/src/metadata/workflow/classification.py, ingestion/tests/unit/metadata/pii/test_classifiers.py, ingestion/tests/unit/metadata/pii/test_presidio_utils.py, ingestion/tests/unit/metadata/pii/test_tag_processor.py, ingestion/tests/unit/pii/algorithms/test_presidio_utils.py
**Disclaimer**: publishing this PR as well because it seems like I removed the merge commit of #23446 into #23289 
I've added a new `TagProcessor` and downstream code required to use all tag recognizers from OM a build `presidio` recognizers, somewhat replacing the static configuration used in `PIIProcessor`.
I've added new test cases that describe the use case this PR includes.
This includes testing that PII tags configured with the appropriate recognizers are selected accordingly
#
#
=> Use recognizer in classification

ingestion/src/metadata/pii/base_processor.py, openmetadata-ui/src/main/resources/ui/playwright/e2e/nightly/AutoClassification.spec.ts
Fixes the following [broken test (AutoClassification.spec.ts)](https://github.com/open-metadata/openmetadata-nightly/actions/runs/18283697111/attempts/1#summary-52056461021)
Commit by commit:
- Fixed some ordering issue between table's columns and sample data's columns
- Removed an expectation from the playwright test that no longer made sense
#
#
=> PLAYWRIGHT FIXES: ensure sample data is passed to the right columns

bootstrap/sql/migrations/native/1.11.0/data/tags/NonSensitive.json, bootstrap/sql/migrations/native/1.11.0/data/tags/Sensitive.json, ingestion/src/metadata/pii/algorithms/presidio_recognizer_factory.py, ingestion/src/metadata/pii/processor_factory.py, openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/auto_classification.py, openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationProcess.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationProcessImpl.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v1110/Migration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v1110/Migration.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/MigrationFile.java, openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v1110/MigrationProcessBase.java, openmetadata-service/src/main/resources/json/data/tags/piiTagsWithRecognizers.json, openmetadata-spec/src/main/resources/json/schema/type/predefinedRecognizer.json, openmetadata-ui/src/main/resources/ui/src/generated/api/classification/createTag.ts, openmetadata-ui/src/main/resources/ui/src/generated/api/classification/createTagWithRecognizers.ts, openmetadata-ui/src/main/resources/ui/src/generated/api/classification/loadTags.ts, openmetadata-ui/src/main/resources/ui/src/generated/entity/classification/tag.ts, openmetadata-ui/src/main/resources/ui/src/generated/type/predefinedRecognizer.ts, openmetadata-ui/src/main/resources/ui/src/generated/type/recognizer.ts
Builds on #23289 
I added the necessary files for v1.10.0 migrations with the goal of setting up existing tags' recognizers.
The reason why I used Java classes and not SQL is that the JSON value of the recognizers was so long that the server migration long couldn't support it.
#
#
=> Ensure recognizers are created

ingestion/src/metadata/ingestion/source/database/unitycatalog/client.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/lineage.py, ingestion/src/metadata/ingestion/source/database/unitycatalog/models.py, ingestion/src/metadata/ingestion/source/storage/s3/metadata.py, ingestion/tests/unit/topology/database/test_unity_catalog_lineage.py
Updated Unity Catalog lineage processing to use the new `/lineage-tracking/table-lineage` API endpoint and added support for external location (S3/cloud storage) lineage tracking.
- **Endpoint**: Changed from `/lineage-tracking/table-lineage/get` to `/lineage-tracking/table-lineage`
- **Response Format**: New API returns richer lineage information including external storage locations
The new API response includes `fileInfo` objects for external storage locations (S3, ADLS, etc.) in addition to table-to-table lineage:
**Old Response Structure:**
```json
{
"upstream_tables": [...],
"downstream_tables": [...]
}
```
**New Response Structure:**
```json
{
"upstreams": [
{"tableInfo": {...}},
{"fileInfo": {
"path": "s3://bucket/path/file.parquet",
"storage_location": "s3://bucket/path", …
```
=> feat: Unity Catalog Lineage Enhancement - External Location Support
