open-metadata/OpenMetadata

openmetadata-docs/content/v1.1.x/deployment/docker/index.md

fix: docs error

---

openmetadata-ui/src/main/resources/ui/src/constants/elasticsearch.constant.ts

fix(ui): align reindex values from server

---

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/src/metadata/ingestion/source/database/redshift/metadata.py
ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/utils/logger.py

Fix Stored Procedures - Don't get queries without context

---

bootstrap/sql/migrations/native/1.2.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.2.0/postgres/schemaChanges.sql
ingestion/src/metadata/clients/domo_client.py
ingestion/src/metadata/examples/workflows/domodashboard.yaml
ingestion/src/metadata/ingestion/source/dashboard/domodashboard/connection.py
ingestion/src/metadata/ingestion/source/dashboard/domodashboard/metadata.py
ingestion/src/metadata/ingestion/source/database/domodatabase/metadata.py
ingestion/src/metadata/ingestion/source/pipeline/domopipeline/metadata.py
ingestion/tests/unit/topology/dashboard/test_domodashboard.py
ingestion/tests/unit/topology/database/test_domodatabase.py
ingestion/tests/unit/topology/pipeline/test_domopipeline.py
openmetadata-docs/content/partials/v1.2/deployment/upgrade/upgrade-prerequisites.md
openmetadata-service/src/main/resources/json/data/testConnections/dashboard/domodashboard.json
openmetadata-service/src/test/java/org/openmetadata/service/resources/query/QueryResourceTest.java
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/dashboard/domoDashboardConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/domoDatabaseConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/pipeline/domoPipelineConnection.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceProfilerPipeline.json
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Dashboard/DomoDashboard.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/DomoDatabase.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/DomoPipeline.md

Fix #13237 - Rename to instanceDomain and test DomoDashboard charts

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v110/MigrationUtil.java

We updated the name hash column for the `QueryDAO` [here](https://github.com/open-metadata/OpenMetadata/pull/13215/files#diff-18e882a3c8d7462c692bd1e2bd91e1f4dd740df320f63d442eacf52b452b5b92). However, that information was being used in 1.1.0 migrations when creating the name hash cols.
What happened is that the rename from `nameHash` -> `fqnHash` does not happen until 1.2.
This PR overloads the fqn generation methods to allow us to pass the nameHash when needed (for query and test suites)
#
#

Clean migration and pass nameHashColumn as param when needed

---

ingestion/src/metadata/ingestion/source/storage/s3/metadata.py

Fixes KeyError in Response under storage
#
#

Fix Storage Key in response

---

openmetadata-service/src/main/java/org/openmetadata/service/search/EntityBuilderConstant.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClientImpl.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/ContainerIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DashboardDataModelIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DashboardIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DomainIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/GlossaryTermIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/MlModelIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/PipelineIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchEntityIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/StoredProcedureIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TagIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TopicIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClientImpl.java
openmetadata-service/src/main/resources/elasticsearch/en/dashboard_data_model_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/table_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/dashboard_data_model_index.json
openmetadata-service/src/main/resources/elasticsearch/jp/table_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/dashboard_data_model_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/table_index_mapping.json

- added aggregations for new fields and indexes.
- some missing things
#

addded aggreagtions for new indexes and fields, and added missing things

---

scripts/slack-link-monitor.py

Get alerted if the monitor fails due to the service

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v116/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v116/Migration.java

Move 1.1.4 migrations to 1.1.6 and add an empty dir for 1.1.6 migrations to invoke the data migration

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/QueryRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/StoredProcedureRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java

Otherwise we can end up with null required fields that lead to inconsistent data. Before this PR, we could run the following PATCH request:
```
metadata.client.patch(
path=f"/queries/{created_query.id.__root__}",
data=json.dumps([
{
"op": "remove",
"path": "/query",
}
])
)
```
#
#

Check for required fields before update

---

openmetadata-service/src/main/java/org/openmetadata/service/events/ChangeEventHandler.java
openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SearchIndexRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestTransactionRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TokenRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UsageRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v110/MigrationUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v111/MigrationUtilV111.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/feeds/FeedResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/usage/UsageResource.java
openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BasicAuthenticator.java
openmetadata-service/src/main/java/org/openmetadata/service/security/auth/LdapAuthenticator.java
openmetadata-service/src/main/java/org/openmetadata/service/security/auth/UserTokenCache.java
openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/util/NotificationHandler.java
openmetadata-service/src/main/java/org/openmetadata/service/util/SubscriptionUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/util/jdbi/BindUUID.java

Add BindUUID JDBI support to directly pass UUID to queries

---

openmetadata-spec/src/main/resources/json/schema/type/entityRelationship.json

Adds Edited By as relationship

---

ingestion/src/metadata/ingestion/lineage/sql_lineage.py
ingestion/src/metadata/ingestion/source/database/bigquery/helper.py
ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/src/metadata/ingestion/source/database/bigquery/query_parser.py
ingestion/src/metadata/ingestion/source/database/lineage_source.py
ingestion/src/metadata/ingestion/source/database/query_parser_source.py
ingestion/src/metadata/ingestion/source/database/usage_source.py
ingestion/tests/unit/test_sql_lineage.py

Fix: Bigquery query log not picked up for multiproject
#
#

Fix: Bigquery query log not picked up for multiproject

---

ingestion/src/metadata/ingestion/source/database/bigquery/connection.py
ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/tests/unit/topology/database/test_bigquery.py

Fixes 13321: Fix Test Connection timeout

---

.github/workflows/cypress-integration-tests-mysql-skip.yml
.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql-skip.yml
.github/workflows/cypress-integration-tests-postgresql.yml

fix(ci): reduce cypress machines to 1

---

openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx

Fixes: Multiple constraint icons visible for a column
Fix: Reduce same icons for a column
#
#

fix(ui): constraint icon for table

---

openmetadata-docs/content/partials/v1.1/deployment/upgrade/upgrade-prerequisites.md
openmetadata-docs/content/partials/v1.2/deployment/upgrade/upgrade-prerequisites.md
openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java

And update docs to make it more explicit that the Airflow external installations need to update their packages
#
#

Pipeline Service Client - Handle unexpected status response

---

openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx
openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsUtils.tsx

I worked on fixing the error on the search index custom attribute settings page
https://github.com/open-metadata/OpenMetadata/assets/51777795/33d90047-7f14-440b-b5dc-c92d092198d6
#
#

fix(ui): error on the search index custom attribute settings page

---

openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/TrinoConnectionClassConverter.java
openmetadata-service/src/test/java/org/openmetadata/service/secrets/converter/ClassConverterFactoryTest.java

Fixes 13350: Trino Secrets masking

---

ingestion/setup.py
openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v117/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/V114/MigrationUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/V117/MigrationUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v120/MigrationUtil.java

Prepares a new 1.1.7 migration step where:
1. We fix test cases `entityFQN` and `entityLink` if they were generated by third-party tools (e.g., dbt) where we did not properly handle tables with upper/lowercase.
2. Retry the test suite migration: Create the executable suite if not there (due to test cases not linked to a table properly) and add any missing relationship
#
#

Prep v1.1.7 migrations to address test cases & suites

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/TeamsHeaderSection/TeamsInfo.component.tsx

Fixes https://github.com/open-metadata/OpenMetadata/issues/12533
- I worked on fixing team hierarchy cypress
#
#

fix(ui): Teams hierarchy cypress fix

---

ingestion/src/metadata/ingestion/source/database/snowflake/connection.py
ingestion/src/metadata/ingestion/source/database/snowflake/queries.py

Fix snowflake test connection
#
#

Fix snowflake test connection

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/EntityResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dashboards/DashboardResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/domains/DataProductResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ServiceEntityResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/dashboard/DashboardServiceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/database/DatabaseServiceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/messaging/MessagingServiceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/metadata/MetadataServiceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/mlmodel/MlModelServiceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/pipeline/PipelineServiceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/searchIndexes/SearchServiceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/storage/StorageServiceResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/domains/DataProductResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/domains/DomainResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/DashboardServiceResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/DatabaseServiceResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/MessagingServiceResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/MlModelServiceResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/PipelineServiceResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/SearchServiceResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/ServiceResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/StorageServiceResourceTest.java

Fixes part 1 of 13255 - list filtering for services and data products

---

openmetadata-docs/content/v1.2.x-SNAPSHOT/connectors/database/mssql/index.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Mssql.md

I worked on the mssql connector docs because it was requested by Harsha to update this page after resolving the connection issue on Slack support channel. Thank you @harshach and @ulixius9! https://openmetadata.slack.com/archives/C02B6955S4S/p1695229785643939?thread_ts=1694206363.231229&cid=C02B6955S4S
#
#

[Docs] - Add context for windows authentication from linux

---

bootstrap/sql/migrations/native/1.2.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.2.0/postgres/schemaChanges.sql

Add indexes to name column for efficient ORDER BY name queries

---

openmetadata-docs/content/v1.1.x/how-to-guides/index.md

chore(docs): added quick links in how to guide homepage

---

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/CollectionRegistry.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/settings/SettingsCache.java

Fix SettingsCache initialization

---

openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
openmetadata-ui/src/main/resources/ui/cypress/constants/tagsAddRemove.constants.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/TagsAddRemove.spec.js
openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx

Fixes #13398
- Fixing initial load tab details in the container page
- fix cypress failure in tagsAddAndRemove
https://github.com/open-metadata/OpenMetadata/assets/66266464/140d9320-38ea-462d-88b1-eeba904ca530
#
#

fix(ui):  initial load tab details in container page

---

openmetadata-docs/content/v1.1.x/deployment/ingestion/openmetadata.md
openmetadata-docs/content/v1.2.x-SNAPSHOT/deployment/ingestion/openmetadata.md

Fix #12870 - Troubleshoot Debian/CentOS Airflow apis installation

---

ingestion/src/metadata/ingestion/models/table_metadata.py
ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
ingestion/src/metadata/ingestion/sink/metadata_rest.py
ingestion/src/metadata/ingestion/source/metadata/atlas/metadata.py
ingestion/src/metadata/pii/processor.py
ingestion/src/metadata/profiler/api/models.py
ingestion/tests/integration/ometa/test_ometa_es_api.py
ingestion/tests/integration/ometa/test_ometa_patch.py
ingestion/tests/integration/orm_profiler/test_pii_processor.py

To generate a single version change
#
#

Batch PII tagging

---

.pylintrc
ingestion/plugins/print_checker.py
ingestion/setup.py

Fix Latest Pylint 3.0.0 issues

---

ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py

Fixed dbt optional files for local config
#
#

Fixed dbt optional files for local config

---

openmetadata-docs/content/v1.0.x/connectors/database/bigquery/index.md
openmetadata-docs/content/v1.1.x/connectors/database/bigquery/index.md
openmetadata-docs/content/v1.2.x-SNAPSHOT/connectors/database/bigquery/index.md

Fix 7410: add documentation for sharded tables

---

openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.tsx

fix: encode search query text

---

ingestion/src/metadata/ingestion/source/database/snowflake/connection.py
ingestion/tests/cli_e2e/test_cli_mysql.py

Fix failing E2Es

---

ingestion/src/metadata/ingestion/lineage/sql_lineage.py

Fix column lineage noneType error: Fix for MSSQL e2e tests
#
#

Fix column lineage noneType error

---

openmetadata-ui/src/main/resources/ui/src/App.tsx
openmetadata-ui/src/main/resources/ui/src/components/ApplicationConfigProvider/ApplicationConfigProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/slashCommand/items.ts
openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/LeftSidebar.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/router/AuthenticatedAppRouter.tsx

I worked on adding support for route and sidebar elements prop in the App component.
#
#

chore(ui): add route and sidebar prop support in app

---

openmetadata-ui/src/main/resources/ui/src/components/Draggable/DraggableBodyRow.tsx
openmetadata-ui/src/main/resources/ui/src/components/Draggable/DraggableBodyRowProps.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/TeamHierarchy.tsx
openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/team.interface.ts
openmetadata-ui/src/main/resources/ui/src/constants/Teams.constants.ts
openmetadata-ui/src/main/resources/ui/src/styles/components/table.less

Fixes #12596
I worked on supported drag and drop to glossary level for glossary terms
https://github.com/open-metadata/OpenMetadata/assets/66266464/c67d8a9a-d40e-4d1f-a86f-504b7cdaf9fc
#
#

fix(ui): supported drag and drop to glossary level for glossary terms

---

ingestion/setup.py
ingestion/src/metadata/profiler/processor/core.py
openmetadata-ui/src/main/resources/ui/src/constants/Services.constant.ts

Fixes #13191 
- implement logic to filter metrics from the profiler config file (previously we were only looking in the entity object)
- made green plum connector beta
#
#

fix: handle tableConfig for profiler CLI

---

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/tests/unit/test_handle_partitions.py
ingestion/tests/unit/topology/database/test_bigquery.py

Fix Bigquery Test connection for multiproject

---

openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreV1.test.tsx
openmetadata-ui/src/main/resources/ui/src/enums/search.enum.ts

Fixes #13442
- I worked on changing search index value for search and data product
#
#

fix(ui): change search index value for search and data product

---

openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/tagsV1.less

fix: Glossary tags are not showing proper name when using in entities #13440

---

openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainPage.component.tsx

Fixes  #13449
- I worked on fixing domain cypress
- Domain not found issue after delete a single last domain
- Domain api won't call even if the url has certain name following domain, unless domain list has anything
https://github.com/open-metadata/OpenMetadata/assets/66266464/9e9e859d-b063-4fd2-96a2-af471d4033e9
#
#

fix(ui): domain cypress and not found  domain issue after deleting last entry

---

ingestion/Dockerfile
ingestion/Dockerfile.ci
ingestion/operators/docker/Dockerfile
ingestion/operators/docker/Dockerfile-dev
ingestion/src/metadata/ingestion/source/dashboard/looker/bulk_parser.py
ingestion/src/metadata/readers/file/local.py

- [Looker] Update missing function
- [Looker] add git execution to ingestion Dockerfile
Fixes Looker issues
#
#

Fix looker missing git execution on container image

---

ingestion/src/metadata/ingestion/source/pipeline/nifi/client.py

Fix #12952: Fix Nifi json decode error
#
#

Fix #12952: Fix Nifi json decode error

---

.github/workflows/maven-build.yml
.github/workflows/maven-postgres-tests-build.yml

Make tests to run mvn clean package

---

.github/workflows/py-tests.yml

Modify pytest timeout from 30 to 40 mins

---

ingestion/src/metadata/cli/backup.py
ingestion/src/metadata/cli/dataquality.py
ingestion/src/metadata/cli/ingest.py
ingestion/src/metadata/cli/insight.py
ingestion/src/metadata/cli/lineage.py
ingestion/src/metadata/cli/profile.py
ingestion/src/metadata/cli/usage.py
ingestion/src/metadata/cmd.py
openmetadata-docs/content/v1.1.x/connectors/pipeline/airflow/mwaa.md
openmetadata-docs/content/v1.2.x-SNAPSHOT/connectors/pipeline/airflow/mwaa.md

metadata CLI accepts tilde for relative paths

---

ingestion/examples/airflow/dags/airflow_metadata_to_es.py
ingestion/setup.py
ingestion/src/metadata/ingestion/source/database/athena/metadata.py
ingestion/src/metadata/pii/processor.py

Fixes #12082
Bumping Athena version & cleaning up NER loading
#
#

Fix #12082 - Bump PyAthena version

---

conf/openmetadata.yaml
ingestion/src/metadata/ingestion/ometa/mixins/ingestion_pipeline_mixin.py
ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/src/metadata/ingestion/ometa/routes.py
ingestion/src/metadata/utils/class_helper.py
ingestion/src/metadata/workflow/base.py
ingestion/src/metadata/workflow/workflow_status_mixin.py
ingestion/tests/unit/test_ometa_endpoints.py
openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java
openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/noop/NoopClient.java
openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/PipelineServiceStatusJobHandler.java
openmetadata-service/src/test/java/org/openmetadata/service/pipelineService/MockPipelineServiceClient.java
openmetadata-spec/src/main/java/org/openmetadata/sdk/PipelineServiceClient.java
openmetadata-spec/src/main/resources/json/schema/configuration/pipelineServiceClientConfiguration.json

- We skip the status validation of the PipelineServiceClient if we configure as `enabled: false`
- We are creating ingestion pipelines if we specify the FQN in the YAML config
- This allows us to see the status and ingestion registered on the UI, even for external pipelines
- I'll need to make a followup change to Collate for the `pipelineServiceClient` methods
The `/status` call will be returning a `platform: disabled` message for us to flag this behavior
#
#

Register Ingestion pipelines just from YAML

---

ingestion/tests/cli_e2e/test_cli_hive.py

Fix hive e2e test count

---

ingestion/setup.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/12480
#
#

Enable pymssql python library

---

docker/run_local_docker.sh

Point Reindex request to new Applications api

---

openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/slashCommand/items.ts

fix(ui): assets path in editor command items

---

openmetadata-service/pom.xml

Created Uber Jar for openmetada-service

---

bootstrap/sql/migrations/native/1.2.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.2.0/postgres/schemaChanges.sql
openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AbstractOmAppJobListener.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java

- Remove not required fields from app_extension table
#
#

- Add Latest App Run Endpoint

---

.github/workflows/py-tests.yml

Enable workflow_dispatch for PyTests
#
#

fix(CI): Enable workflow_dispatch for PyTests

---

openmetadata-ui/src/main/resources/ui/src/components/common/SelectableList/SelectableList.component.tsx

Fixes #13167 
https://github.com/open-metadata/OpenMetadata/assets/12962843/909f679a-ee25-4cf2-af30-7d9e5b252d6a
I worked on disabling sorting on selection of the list item in the SelectionList component
#
#

fix(ui): disable sorting on user selection

---

openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/BlockEditor.tsx
openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/block-editor.less

I worked on adding support for focusing the editor when the wrapper area is captured.
#
#

chore(ui): focus editor when wrapper area is captured

---

openmetadata-spec/src/main/resources/json/schema/api/domains/createDataProduct.json
openmetadata-spec/src/main/resources/json/schema/entity/domains/dataProduct.json

Make domain optional for data product

---

ingestion/tests/cli_e2e/test_cli_mysql.py

Fix mysql E2E test count

---

bootstrap/bootstrap_storage.sh
openmetadata-service/src/main/java/org/openmetadata/service/util/TablesInitializer.java

Fix extensions migrations path

---

pom.xml

Do not run sonar by default

---

.github/workflows/py-tests.yml

Fix Python Tests for limited storage in CI.
#
#

fix(CI): Python Tests

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java

I worked on ... because ... Fix Crentials issue on Elastic Search
#
- [ x] Bug fix

Fix credentials issue elastic search

---

openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java

remove log from initializeRepositories

---

openmetadata-ui/src/main/resources/ui/src/App.tsx
openmetadata-ui/src/main/resources/ui/src/components/ApplicationConfigProvider/ApplicationConfigProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/LeftSidebar.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/LeftSidebarClassBase.ts

chore(ui): add base class for left sidebar

---

ingestion/src/metadata/profiler/processor/sampler/sqlalchemy/sampler.py
ingestion/tests/integration/orm_profiler/test_orm_profiler_e2e.py

- change column from table bound column to rnd table bound columns
#
#
Bug Fix

fix: pass rnd table bound columns to sample query

---

.github/workflows/maven-sonar-build.yml

Fixes
I worked on workflow for Maven build with SonarCloud because as part of Issue #13538, Sonar won't run by default anymore with Maven builds.
#
#

Maven-sonarcloud ci

---

openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeader/EntityHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/TagsSelectForm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/tag-select-fom.style.less
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.interface.ts
openmetadata-ui/src/main/resources/ui/src/constants/Color.constants.ts
openmetadata-ui/src/main/resources/ui/src/styles/app.less
openmetadata-ui/src/main/resources/ui/src/utils/ClassificationUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx

ui: glossary badge feature feedback

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/AdvanceSearchModal.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/AdvanceSearchProvider/AdvanceSearchProvider.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/AdvanceSearchProvider/AdvanceSearchProvider.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Explore/advanced-search-modal.less
openmetadata-ui/src/main/resources/ui/src/components/Explore/exlore.mock.ts
openmetadata-ui/src/main/resources/ui/src/components/Explore/explore.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreV1.test.tsx
openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/explore/ExplorePageV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/CustomProperties/CustomProperty.utils.ts
openmetadata-ui/src/main/resources/ui/src/utils/ExplorePage/ExplorePageUtils.ts
openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.tsx

Fixes #13038 
Fixes explore search 
https://github.com/open-metadata/OpenMetadata/assets/33024356/c0dfe8e9-f23c-4f0c-9abd-370bc991e8cd
#
#

feat: add custom property filter in advanced search modal

---

openmetadata-ui/src/main/resources/ui/src/components/Applications/AppDetails/AppDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Applications/AppRunsHistory/AppRunsHistory.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/components/size.less

- Disabled logs  button in table while on running state and on success  if doesn't have logs
- minor ui fixes
https://github.com/open-metadata/OpenMetadata/assets/66266464/fe193ca1-473d-40a7-8eb8-0cedb121cca9
#
#

fix(ui): disabled logs on running state and minor fixes

---

openmetadata-ui/src/main/resources/ui/src/components/AppBar/Suggestions.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/ImportResult/GlossaryImportResult.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/TourEndModal/TourEndModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/tour/Tour.tsx
openmetadata-ui/src/main/resources/ui/src/constants/Glossary.constant.ts
openmetadata-ui/src/main/resources/ui/src/constants/mockTourData.constants.ts
openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
openmetadata-ui/src/main/resources/ui/src/pages/explore/ExplorePageV1.component.tsx

Fixes [#13378](https://github.com/open-metadata/OpenMetadata/issues/13378)
fixed tour feature
#
#

ui: fixed broken tour feature

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/resources/elasticsearch/en/glossary_term_index_mapping.json

I worked on ... because ... fix glossary highlighter issue
#
- [ x] Bug fix

Fix glossary highlighter

---

conf/openmetadata.yaml
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DashboardDataModelIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DataProductIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchEntityIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/StoredProcedureIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/resources/elasticsearch/en/dashboard_data_model_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/glossary_term_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/search_entity_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/stored_procedure_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/dashboard_data_model_index.json
openmetadata-service/src/main/resources/elasticsearch/jp/search_entity_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/stored_procedure_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/dashboard_data_model_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/search_entity_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/stored_procedure_index_mapping.json

I worked on ... because ... Added missing search things
#
- [ x] Bug fix

Added missing search things

---

openmetadata-ui/src/main/resources/ui/src/components/common/BrandImage/BrandImage.tsx
openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.tsx
openmetadata-ui/src/main/resources/ui/src/pages/SignUp/SignUpPage.tsx
openmetadata-ui/src/main/resources/ui/src/utils/BrandImage/BrandImageClassBase.ts

updated import logic of logo as classbased
#
#

ui: importing brand logo with classBase approach

---

openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/AddGlossaryTermForm/AddGlossaryTermForm.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/tags-container.style.less

- fixed displayName not visible
- spacing issue in selector
- on hover tooltip was showing undefined while editing
- updated style for glossaryTerm table
#
#

ui: fixed glossary badge feedback

---

ingestion/src/metadata/ingestion/api/status.py

Fix incorrect ingestion pipeline duration
#
#

Fix incorrect ingestion pipeline duration

---

.github/workflows/cypress-integration-tests-mysql-skip.yml
.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql-skip.yml
.github/workflows/cypress-integration-tests-postgresql.yml

fix(CI): Run Cypress CI on Main Branch Only
#

fix(ci): Run Cypress CI on Main Branch Only

---

ingestion/src/metadata/ingestion/api/step.py
ingestion/src/metadata/ingestion/bulksink/metadata_usage.py
ingestion/src/metadata/utils/life_cycle_utils.py

LifeCycle Usage Workflow: query type value fixes
#
#

LifeCycle Usage Workflow: query type value fixes

---

openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-clients/pom.xml

upgrade java version in openmetadata-clients pom

---

ingestion/src/metadata/ingestion/source/database/databricks/unity_catalog/metadata.py

Fix #13555: Long column names considered repeated

---

.github/workflows/publish-maven-package.yml

Updated Maven Central Publish Command
#
#

fix(CI): Maven Central Publish Command

---

ingestion/src/metadata/ingestion/api/status.py

Fixed init of status class pydantic model
#
#

Fixed init of status class pydantic model

---

ingestion/src/metadata/data_quality/source/test_suite.py
ingestion/src/metadata/workflow/base.py
ingestion/src/metadata/workflow/data_quality.py
ingestion/src/metadata/workflow/workflow_status_mixin.py

Fix DQ Workflow

---

.github/workflows/py-cli-e2e-tests.yml
ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
ingestion/src/metadata/ingestion/source/database/azuresql/metadata.py
ingestion/src/metadata/ingestion/source/database/mssql/metadata.py
ingestion/src/metadata/utils/sqa_utils.py
ingestion/tests/cli_e2e/database/bigquery/bigquery.yaml
ingestion/tests/cli_e2e/database/bigquery_multiple_project/bigquery_multiple_project.yaml
ingestion/tests/cli_e2e/database/oracle/oracle.yaml
ingestion/tests/cli_e2e/test_cli_athena.py
ingestion/tests/cli_e2e/test_cli_bigquery_multiple_project.py
ingestion/tests/cli_e2e/test_cli_oracle.py

Add e2e - oracle, athena
remove duplicated code
#
#

Add E2E - Oracle, Athena. Remove Duplicated code

---

.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql.yml

Cypress CI Runs group name scoping to CI
#
#

fix(CI): Cypress CI Runs group name scoping to CI

---

openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

I worked on ... because ... fixed a minor fix in opensearch
#
- [ x] Bug fix

fixed a minor fix in opensearch

---

.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql.yml

fix(CI): Cypress CI enable parallelization

---

openmetadata-ui/src/main/resources/ui/src/components/FeedEditor/FeedEditor.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/FeedEditor/FeedEditor.tsx
openmetadata-ui/src/main/resources/ui/src/components/authentication/auth-provider/AuthProvider.tsx
openmetadata-ui/src/main/resources/ui/src/pages/explore/ExplorePageV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/QuillLink/QuillLink.ts

Fixes Quill links
https://github.com/open-metadata/OpenMetadata/assets/33024356/60b4ca21-c360-4dff-adcc-2e79be5a8207
#
#

fix: links in quill mentions

---

ingestion/tests/cli_e2e/database/athena/athena.yaml
ingestion/tests/cli_e2e/test_cli_hive.py

Fixes env issue, and hive count
#
#

Fix E2E failures

---

openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-service/pom.xml
pom.xml

Update dependencies and plugins for release 1.3.0

---

openmetadata-service/pom.xml
openmetadata-shaded-deps/elasticsearch-dep/pom.xml
openmetadata-shaded-deps/opensearch-dep/pom.xml
pom.xml

Fix vulnerabilities in server dependencies

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/common/serviceUtils.js
openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
openmetadata-ui/src/main/resources/ui/cypress/constants/redirections.constants.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/RecentlyViewed.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/UpdateDisplayName.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/GlossaryVersionPage.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Policies.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Service.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Service/superset.spec.js
openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/yarn.lock

cypress: fixed failing cypress of main and downgraded cypress version to 12.17.4

---

openmetadata-ui/src/main/resources/ui/src/mocks/SearchIndex.mock.ts
openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexFieldsTable/SearchIndexFieldsTable.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexFieldsTable/SearchIndexFieldsTable.tsx

I worked on fixing the wrong field data shown in place of the `Data Type` field when there is no `dataTypeDisplay` field present
**Before:**
**After:**
#
#

fix(ui): incorrect field data showing in data type for search indexes

---

.github/workflows/publish-maven-package.yml
openmetadata-shaded-deps/elasticsearch-dep/pom.xml
openmetadata-shaded-deps/elasticsearch-dep/src/main/java/elasticsearch/ElasticSearchNoop.java
openmetadata-shaded-deps/opensearch-dep/pom.xml
openmetadata-shaded-deps/opensearch-dep/src/main/java/opensearch/OpenSearchNoop.java

Add dummy sources

---

openmetadata-service/pom.xml
pom.xml

fix remaining vulnerabilities in server image

---

ingestion/src/metadata/cli/backup.py
ingestion/src/metadata/cmd.py

Fixes Issue 13517
I worked on adding this optional argument in the CLI because to help resolve these issues. 
#
#

ISSUE-13517: Added option to explicitly specify backup filename 

---

openmetadata-shaded-deps/elasticsearch-dep/pom.xml
openmetadata-shaded-deps/opensearch-dep/pom.xml
pom.xml

Fixes warning for performance 
#
#

Fix log warning

---

ingestion/src/metadata/ingestion/source/database/bigquery/query_parser.py
ingestion/tests/unit/topology/database/test_bigquery.py

Fix Checkstyle on main

---

bootstrap/sql/migrations/native/1.2.0/postgres/schemaChanges.sql

Fixed domo dashboard migration syntax
#
#

Fixed domo dashboard migration syntax

---

openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/index.ts
openmetadata-ui/src/main/resources/ui/src/constants/BlockEditor.constants.ts

chore(ui): improve block editor drop cursor by adding width and color

---

ingestion/tests/unit/topology/database/test_bigquery.py

Fixes Bigquery pytest failure on main
#
#

Fix Bigquery lineage Pytests

---

openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/resources/elasticsearch/indexMapping.json

I worked on ... because ... delete data products when the domain of it is deleted
#
- [ x] Bug fix

Fix data product issue

---

openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsDetailsPage/DataProductsDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/Feeds.constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/SignUp/BasicSignup.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/SignUp/SignUpPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/login/index.tsx

- https://github.com/open-metadata/OpenMetadata/issues/13316#issuecomment-1773480616
-  fix domain styling color in the title if provided
-  UI spacing issue.
-  added autofocus in login and signup page
#
#

fix(ui): domain styling color in the title if provided

---

ingestion/src/metadata/workflow/base.py
ingestion/src/metadata/workflow/workflow_status_mixin.py
openmetadata-docs/content/v1.2.x/deployment/ingestion/index.md

Fix status handling for new services

---

openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx

- chip styling in tags/glossary input styling changes in case of edit
Issue : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/ad9797d7-30c6-4765-808d-dcb07bd783c3
Resolved : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/9da0f79b-cd9d-41f4-8871-9c476d5342eb
#
#

fix(ui): chip styling in tags/glossary input styling changes in case of edit

---

openmetadata-docs/content/v1.2.x/connectors/database/trino/index.md
openmetadata-docs/content/v1.2.x/connectors/database/trino/yaml.md
openmetadata-docs/content/v1.2.x/connectors/search/elasticsearch/index.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Search/ElasticSearch.md

Fix Docs for Elasticsearch & Trino

---

openmetadata-docs/content/v1.2.x/menu.md

[Docs] - Fix menu 1.2.0

---

ingestion/src/metadata/cmd.py

Fix for docker start command
#
#

Fix for docker start command

---

ingestion/Dockerfile
ingestion/operators/docker/Dockerfile
ingestion/setup.py
openmetadata-airflow-apis/setup.py

Bump ingestion version to 1.2.0.1
#
#

Bump ingestion version to 1.2.0.1

---

docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml

Fixing Docker env variable "DB_PARAM" value. Removing quotes as its create an issue when running a migration.
#
#

[FIX] Fixing docker env variable

---

openmetadata-docs/content/partials/v1.2/deployment/upgrade/upgrade-prerequisites.md

[Docs] - Added Helm Chart breaking changes

---

openmetadata-docs/content/partials/v1.2/deployment/upgrade/upgrade-prerequisites.md

[Docs] - Highlight ES requirements

---

bootstrap/sql/migrations/native/1.2.0/postgres/schemaChanges.sql
openmetadata-docs/content/partials/v1.2/deployment/upgrade/upgrade-prerequisites.md
openmetadata-docs/content/v1.2.x/deployment/upgrade/kubernetes.md

1.2.0 - Fix postgres migrations

---

.github/workflows/maven-postgres-tests-build.yml
openmetadata-service/pom.xml

- Fix how we are activating the profile in the CI to run the postgres tests
- Update postgres version to 15, since that's the one we use in the compose files
#
#

Fix mvn postgres CI

---

openmetadata-docs/content/v1.0.x/connectors/ingestion/workflows/dbt/index.md
openmetadata-docs/content/v1.1.x/connectors/database/postgres/yaml.md
openmetadata-docs/content/v1.1.x/connectors/ingestion/workflows/dbt/index.md
openmetadata-docs/content/v1.1.x/connectors/ingestion/workflows/dbt/ingest-dbt-descriptions.md
openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/dbt/index.md
openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/dbt/ingest-dbt-descriptions.md

dbt and postgres docs fix

---

openmetadata-ui/src/main/resources/ui/cypress/common/entityUtils.js
openmetadata-ui/src/main/resources/ui/cypress/constants/entityConstant.js
openmetadata-ui/src/main/resources/ui/cypress/constants/redirections.constants.js
openmetadata-ui/src/main/resources/ui/cypress/constants/updateDisplayName.constant.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/RecentlyViewed.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/RestoreEntity.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/UpdateDisplayName.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Task.spec.js

cypress: fixed AUT failure part 1 
#
#

cypress: fixed AUT failure part 1

---

ingestion/src/metadata/ingestion/source/database/athena/metadata.py

Add support for partitioned table support for Athena
part of fix for #13603
#
#

Add support for partitioned table support for Athena

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchAggregatedUnusedAssetsCountAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchAggregatedUnusedAssetsSizeAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchAggregatedUsedvsUnusedAssetsCountAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchAggregatedUsedvsUnusedAssetsSizeAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchEntitiesDescriptionAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchEntitiesOwnerAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchMostActiveUsersAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchMostViewedEntitiesAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchPageViewsByEntitiesAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchServicesDescriptionAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchServicesOwnerAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchTotalEntitiesAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchTotalEntitiesByTierAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchAggregatedUnusedAssetsCountAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchAggregatedUnusedAssetsSizeAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchAggregatedUsedvsUnusedAssetsCountAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchAggregatedUsedvsUnusedAssetsSizeAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchEntitiesDescriptionAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchEntitiesOwnerAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchMostActiveUsersAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchMostViewedEntitiesAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchPageViewsByEntitiesAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchServicesDescriptionAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchServicesOwnerAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchTotalEntitiesAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchTotalEntitiesByTierAggregator.java

- handle null aggregation bucket when retrieving value
#
#

fix: handle null aggregation bucket

---

ingestion/tests/unit/metadata/utils/test_entity_link.py
ingestion/tests/unit/test_entity_link.py
openmetadata-spec/src/main/antlr4/org/openmetadata/schema/EntityLink.g4

Add Multilingual Support in EntityLink

---

openmetadata-ui/src/main/resources/ui/cypress.config.ts
openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/RestoreEntity.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/SearchIndexDetails.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Service/redshiftWithDBT.spec.js

cypress: fix AUT failure part 3
#
#

cypress: fix AUT failure part 3

---

openmetadata-docs/content/partials/v1.2/deployment/upgrade/upgrade-prerequisites.md
openmetadata-docs/content/v1.2.x/deployment/index.md
openmetadata-docs/content/v1.2.x/sdk/python/build-connector/bulk-sink.md
openmetadata-docs/content/v1.2.x/sdk/python/build-connector/index.md
openmetadata-docs/content/v1.2.x/sdk/python/build-connector/sink.md
openmetadata-docs/content/v1.2.x/sdk/python/build-connector/source.md
openmetadata-docs/content/v1.2.x/sdk/python/build-connector/stage.md

Showing the internal updates we did in the Exception Management and Status Handling and how those translate to Custom Connectors
#
#

[Docs] - Workflow Breaking Changes - Custom Connectors

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v120/MigrationUtil.java

migration error on Postgres
#
#

fix: handle postgres migration error

---

openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/RestoreEntity.spec.js

Fixes #[13069](https://github.com/open-metadata/OpenMetadata/issues/13069)
cypress: fixed cypress AUT failure part 4 #13840
#
#

cypress: fixed cypress AUT failure part 4

---

openmetadata-docs/content/v1.2.x/deployment/bare-metal/index.md

Update baremetal installation docs to refer Java 17

---

ingestion/src/metadata/parsers/avro_parser.py
ingestion/tests/unit/test_avro_parser.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/13371
#
#

Fixed avro recursive record infinite loop

---

ingestion/src/metadata/data_quality/interface/sqlalchemy/sqa_test_suite_interface.py
ingestion/src/metadata/profiler/interface/pandas/profiler_interface.py
ingestion/src/metadata/profiler/interface/sqlalchemy/bigquery/profiler_interface.py
ingestion/src/metadata/profiler/interface/sqlalchemy/profiler_interface.py

Fix Trino Dialect Import issue

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java

Fix Pagination Api failure

---

openmetadata-service/src/main/java/org/openmetadata/service/Entity.java

Fixes [#13373](https://github.com/open-metadata/OpenMetadata/issues/13373)
#
#

Allow Activity Feed to have User entity Updates

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PolicyRepository.java

Prevent Rules with same name in a Policy

---

ingestion/tests/integration/ometa/test_ometa_glossary.py
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ChartRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardDataModelRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/KpiRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SearchIndexRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/WebAnalyticEventRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/events/EventSubscriptionResourceTest.java
openmetadata-spec/src/main/resources/json/schema/type/entityReference.json

Fixes #13863 - Show inherited relationships of an entity

---

openmetadata-ui/src/main/resources/ui/cypress/common/DataInsightUtils.js
openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/TeamsHierarchy.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AddTeamAsOwner.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsight.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightSettings.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.js
openmetadata-ui/src/main/resources/ui/src/components/Applications/AppSchedule/AppSchedule.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Applications/MarketPlaceAppDetails/MarketPlaceAppDetails.component.tsx

cypress: Auto skip test part 1
- DataQuality spec
- DataInsight spec
- DataInsightApplication setting spec
- AddTeamAsOwner spec
#
#

cypress: Auto skip test part 1

---

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityInfoDrawer/EntityInfoDrawer.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.interface.ts

Fixes #13880
- I worked on fixing table data issue in entity table lineage sidebar
https://github.com/open-metadata/OpenMetadata/assets/66266464/8163b4a4-534e-48ed-85e9-90efc5e1800b
#
#

fix(ui): table data issue in entity table lineage sidebar

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedListV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/tour-page/TourPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx

Fixes #13901
- I worked on fixing  tour page not showing
- minor code optimization
https://github.com/open-metadata/OpenMetadata/assets/66266464/6d86c639-86b6-42a5-ba8d-ade5604f56c5
#
#

fix(ui): tour page not showing

---

ingestion/src/metadata/profiler/processor/sample_data_handler.py
ingestion/tests/cli_e2e/test_cli_athena.py
ingestion/tests/cli_e2e/test_cli_datalake_s3.py
ingestion/tests/cli_e2e/test_cli_redshift.py

Move pandas top level import

---

ingestion/src/metadata/ingestion/ometa/mixins/mlmodel_mixin.py
ingestion/tests/integration/ometa/test_ometa_mlmodel_api.py

Fix #13906 - Fix add_mlmodel_lineage description field

---

ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/src/metadata/ingestion/ometa/routes.py
ingestion/tests/integration/ometa/test_ometa_domains_api.py
openmetadata-spec/src/main/resources/json/schema/api/domains/createDataProduct.json
openmetadata-spec/src/main/resources/json/schema/api/domains/createDomain.json

Fix #13794 - Add domain support to the Python SDK

---

ingestion/src/metadata/ingestion/lineage/sql_lineage.py
ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py

Consider the default schema name returned by sqllineage lib as None to query the ES
#
#

Fix ES search during lineage ingestion

---

bootstrap/sql/migrations/native/1.2.1/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.2.1/postgres/schemaChanges.sql
ingestion/src/metadata/ingestion/source/database/dbt/metadata.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/13828
#
#

Convert dbt test result timestamps to millis

---

ingestion/src/metadata/cli/db_dump.py

Fix #13660 - Metadata Backup Memory Exhaustion

---

ingestion/src/metadata/ingestion/source/search/elasticsearch/parser.py
ingestion/tests/unit/topology/search/test_elasticsearch.py
openmetadata-docs/content/partials/v1.2/deployment/upgrade/upgrade-prerequisites.md
openmetadata-spec/src/main/resources/json/schema/entity/data/searchIndex.json

Fix #13787: Add support for ES data types
#
#

Fix #13787: Add support for ES data types

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/support/commands.js
openmetadata-ui/src/main/resources/ui/src/components/GithubStarCard/GithubStarCard.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/GithubStarCard/github-star-card.style.less
openmetadata-ui/src/main/resources/ui/src/components/Modals/GithubStarModal/GithubStarModal.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/GithubStarModal/github-star-modal.style.less
openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/WhatsNewAlert/WhatsNewAlert.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx
openmetadata-ui/src/main/resources/ui/src/components/NavBar/PopupAlertClassBase.ts
openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts

https://github.com/open-metadata/OpenMetadata/assets/66266464/d3eb377c-bdb9-4da0-a934-8e0e271203f3
- I worked on fixing cypress
- change modal to popup
#
#

chore(ui): change github start modal to popup

---

openmetadata-docs/content/v1.2.x/deployment/iam-auth.md
openmetadata-docs/content/v1.2.x/menu.md

[Docs] - RDS IAM Auth

---

bootstrap/sql/migrations/native/1.2.1/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.2.1/postgres/schemaChanges.sql
ingestion/src/metadata/ingestion/source/search/elasticsearch/connection.py
ingestion/src/metadata/ingestion/source/search/elasticsearch/metadata.py
ingestion/src/metadata/workflow/base.py
openmetadata-docs/content/v1.2.x/connectors/search/elasticsearch/index.md
openmetadata-docs/content/v1.2.x/connectors/search/elasticsearch/yaml.md
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ElasticSearchConnectionClassConverter.java
openmetadata-service/src/test/java/org/openmetadata/service/secrets/converter/ClassConverterFactoryTest.java
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/common/sslCertPaths.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/common/sslCertValues.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/common/sslConfig.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/search/elasticSearch/apiAuth.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/search/elasticSearch/basicAuth.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/search/elasticSearchConnection.json
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Search/ElasticSearch.md

ElasticSearch: Fix ES connection

---

ingestion/src/metadata/ingestion/source/pipeline/nifi/client.py

Nifi log incorrect password in test connection
#
#

Nifi log incorrect password in test connection

---

ingestion/Dockerfile
ingestion/Dockerfile.ci
ingestion/operators/docker/Dockerfile
ingestion/operators/docker/Dockerfile-dev

Fix #12406
lgtm locally. We'll need to put some time in creating integration tests for the base image
#
#

Fix #12406 - Ingestion image with python 3.10

---

ingestion/Dockerfile
ingestion/Dockerfile.ci
ingestion/operators/docker/Dockerfile
ingestion/operators/docker/Dockerfile-dev
ingestion/src/metadata/ingestion/source/pipeline/nifi/client.py
openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AbstractOmAppJobListener.java
openmetadata-service/src/main/java/org/openmetadata/service/exception/SourceException.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchDataInsightProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchEntitiesProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchIndexSink.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchDataInsightProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchEntitiesProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchIndexSink.java
openmetadata-service/src/main/java/org/openmetadata/service/workflows/interfaces/Source.java
openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/PaginatedDataInsightSource.java
openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/PaginatedEntitiesSource.java
openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/ReindexingUtil.java
openmetadata-spec/src/main/resources/json/schema/entity/applications/appRunRecord.json
openmetadata-spec/src/main/resources/json/schema/system/eventPublisherJob.json
openmetadata-ui/src/main/resources/ui/src/components/Applications/AppLogsViewer/AppLogsViewer.component.tsx

Logs added for Search Indexing and Stats issue fixed

---

openmetadata-docs/content/v1.2.x/connectors/pipeline/nifi/troubleshooting.md
openmetadata-docs/content/v1.2.x/menu.md

[Docs] - Add nifi troubleshooting

---

openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/profiler/external_workflow.md
openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/profiler/sample_data.md

[Docs] - Fix profiler page

---

openmetadata-docs/content/v1.2.x/sdk/python/index.md
openmetadata-docs/content/v1.2.x/sdk/python/ingestion/lineage.md
openmetadata-docs/content/v1.2.x/sdk/python/ingestion/tags.md

[Docs] use BasicAuth in python sdk docs

---

bootstrap/sql/migrations/native/1.2.1/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.2.1/postgres/schemaChanges.sql

Fix 121 migration

---

ingestion/src/metadata/great_expectations/action.py

fix: GX integration ts ms

---

ingestion/setup.py
openmetadata-airflow-apis/setup.py

vers: bumped up py version

---

openmetadata-docs/content/v1.1.x/connectors/database/athena/index.md
openmetadata-docs/content/v1.1.x/connectors/database/athena/yaml.md
openmetadata-docs/content/v1.2.x/connectors/database/athena/index.md
openmetadata-docs/content/v1.2.x/connectors/database/athena/yaml.md

Added athena min permissions in docs
#
#

Added athena min permissions in docs

---

.github/workflows/docker-openmetadata-db.yml
.github/workflows/docker-openmetadata-ingestion-base.yml
.github/workflows/docker-openmetadata-ingestion.yml
.github/workflows/docker-openmetadata-postgres.yml
.github/workflows/docker-openmetadata-server.yml
Makefile
common/pom.xml
docker/docker-compose-ingestion/docker-compose-ingestion.yml
docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
docker/docker-compose-quickstart/Dockerfile
docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml
ingestion/Dockerfile
ingestion/operators/docker/Dockerfile
ingestion/setup.py
openmetadata-airflow-apis/setup.py
openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-clients/pom.xml
openmetadata-dist/pom.xml
openmetadata-service/pom.xml
openmetadata-shaded-deps/elasticsearch-dep/pom.xml
openmetadata-shaded-deps/opensearch-dep/pom.xml
openmetadata-shaded-deps/pom.xml
openmetadata-spec/pom.xml
openmetadata-ui/pom.xml
pom.xml

Bump Pom Version to 1.3.0-SNAPSHOT

---

openmetadata-ui/src/main/resources/ui/src/pages/SwaggerPage/index.tsx

fix(ui): path not found in swagger file

---

openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts

ui: fixed advance search suggestion issue for user field #14005
https://github.com/open-metadata/OpenMetadata/assets/71748675/82c99f57-3e0a-4ea5-9d3b-bb8b92269bbd
#
#

ui: fixed advance search suggestion issue for user field

---

openmetadata-service/pom.xml
openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java

Package Test-Jar to be used in Collate
#
#

Add Test Jar for Collate Testing

---

openmetadata-docs/content/v1.1.x/connectors/database/athena/index.md
openmetadata-docs/content/v1.1.x/connectors/database/athena/yaml.md
openmetadata-docs/content/v1.2.x/connectors/database/athena/index.md
openmetadata-docs/content/v1.2.x/connectors/database/athena/yaml.md

Generalised Athena policy docs
#
#

Generalised Athena policy docs

---

ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/ingestion/source/database/snowflake/models.py
ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
openmetadata-docs/content/v1.2.x/connectors/database/snowflake/index.md

Fix #14012 - Snowflake procedure with empty definition

---

ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/ingestion/source/database/snowflake/queries.py

Since the service can live in one warehouse and the queries are executed in another
#
#

Snowflake SP don't filter by warehouse

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardDataModelRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SearchIndexRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/datamodels/DashboardDataModelResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/pipelines/PipelineResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/searchindex/SearchIndexResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/storages/ContainerResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/topics/TopicResourceTest.java
openmetadata-spec/src/main/java/org/openmetadata/schema/CreateEntity.java
openmetadata-spec/src/main/resources/json/schema/api/services/createMetadataService.json
openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/appMarketPlaceDefinition.json
openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.json

Fixes #14006 Validate tag labels before creating/updating an entity

---

openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
openmetadata-ui/src/main/resources/ui/src/pages/EmailConfigSettingsPage/EmailConfigSettingsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/rest/settingConfigAPI.ts

Fixes #13270
- I worked on supported test email button in email smtp page
#
#

fix(ui): supported test email button in email smtp page

---

ingestion/src/metadata/ingestion/source/database/databricks/connection.py
ingestion/src/metadata/ingestion/source/database/databricks/legacy/metadata.py
ingestion/src/metadata/ingestion/source/database/databricks/unity_catalog/metadata.py
ingestion/tests/unit/topology/database/test_databricks.py

Fix #13954: Fix ParseException for older version
#
#

Fix #13954: Fix ParseException for older version of databricks

---

openmetadata-ui/src/main/resources/ui/cypress/common/DomainUtils.js
openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsDetailsPage/DataProductsDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx

- Disabled the option to rename for domain and data product, only allow user to update displayname
- fixed cypress according to the change.
#
#

ui: only allow updating displayName for domain and data product

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/ClassificationVersionPage.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataModelVersionPage.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DatabaseSchemaVersionPage.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DatabaseVersionPage.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/EntityVersionPages.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/GlossaryVersionPage.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/ServiceVersionPage.spec.js

Revert the changes of  version page cypress
#
#

cypress: revert version related cypress in 1.2.2

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/KpiRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SearchIndexRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TypeRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/V117/MigrationUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v110/MigrationUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseSchemaResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/PersonaResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/RoleResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/TeamResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/util/TestUtils.java

Use entity cache for lookup instead of reading from the database
#
#

Use entity cache for lookup

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Customproperties.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Teams.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Service/MlFlow.spec.js
openmetadata-ui/src/main/resources/ui/cypress/plugins/index.js
openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/TeamDetailsV1.tsx

cypress: fixed AUT cypress part 2
#
#

cypress: fixed AUT cypress part 2

---

ingestion/pyproject.toml
ingestion/setup.py

already had issues after merging https://github.com/open-metadata/OpenMetadata/pull/14025 since it was failing in main but not the branch.
fixing depdencies and adding dynamic properties which worked before
#
#

Fix pyproject - TypeError: 'list' object is not a mapping

---

openmetadata-ui/src/main/resources/ui/src/components/FeedEditor/FeedEditor.tsx
openmetadata-ui/src/main/resources/ui/src/components/FeedEditor/feed-editor.less
openmetadata-ui/src/main/resources/ui/src/constants/Feeds.constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/QuillUtils.js

Part of #14047 
I worked on adding RTL support in the feed editor.
https://github.com/open-metadata/OpenMetadata/assets/59080942/2dc12fae-bd2a-4b21-8809-2c0fc3d916dc
#
#

feat(ui): add RTL support in feed editor

---

ingestion/examples/sample_data/datasets/tables.json
ingestion/examples/sample_data/profiler/tableProfile.json
ingestion/pyproject.toml
ingestion/src/metadata/ingestion/source/database/sample_data.py

- Add custom metrics sample data
- rename cli to `metadata`
#
#

Add Custom metrics sample data

---

ingestion/src/metadata/ingestion/source/database/athena/models.py
ingestion/src/metadata/ingestion/source/database/athena/query_parser.py
ingestion/src/metadata/ingestion/source/database/athena/usage.py
openmetadata-docs/content/v1.2.x/connectors/database/athena/index.md

Athena: Add support for work groups in usage & lineage

---

Makefile

make ingestion build docker image using Dockerfile.ci
#
#

fix: make ingestion build docker image using Dockerfile.ci

---

ingestion/setup.py

Update great-expectations~=0.18.0
#
#

great-expectations~=0.18.0

---

.github/workflows/py-cli-e2e-tests.yml

MINOR: fix path for cli e2e coverage configuration

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.js
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCases/TestCases.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx

Fixes #14083 ui is breaking while updating test case and resolution status
https://github.com/open-metadata/OpenMetadata/assets/71748675/c9ab07ad-7d04-4127-a314-25a18b6291ea
#
#

#14083: ui is breaking while updating test case and resolution status

---

.github/workflows/py-cli-e2e-tests.yml

MINOR: fix sonar upload for py e2e tests

---

openmetadata-service/pom.xml

Also fixes the command line running of a test so that only the default or passed in profile executes

Minor: Fix maven profiles to run tests for MySQL and Postgres using maven profiles

---

openmetadata-ui/src/main/resources/ui/src/components/ContainerDetail/ContainerChildren/ContainerChildren.tsx
openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelsTable.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataModels/ModelTab/ModelTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/SchemaTable/SchemaTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicSchema/TopicSchema.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/SchemaTablesTab.tsx
openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexFieldsTable/SearchIndexFieldsTable.tsx
openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedureTab.tsx
openmetadata-ui/src/main/resources/ui/src/utils/DatabaseDetails.utils.tsx

Fixes #14003
- I worked on fixing the column name overlapping issue  in entity tables
#
#

fix(ui): column name overlapping in entity table

---

openmetadata-docs/content/v1.2.x/quick-start/local-docker-deployment.md

MINOR - Fix docs quickstart commands

---

ingestion/src/metadata/ingestion/source/database/mssql/queries.py

Fix #14100: mssql fix usage query, make table name lowercase
#
#

#14100: mssql fix usage query, make table name lowercase

---

openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/hiveConnection.json

Fixes #14121 
I worked fixing #14121 
https://github.com/open-metadata/OpenMetadata/assets/59080942/9f9d0227-aa03-4d29-bcfc-73207092459d
#
#

fix(#14121): hive connection `metastoreConnection` field is not updating the value correctly

---

openmetadata-ui/src/main/resources/ui/src/utils/AuthProvider.util.ts

Fixes #13773
I worked on Supporting `code` flow for OIDC SSO
Instead depending on hardcoded `id_token` we will use responseType provided from the config. 
Default value is still `id_token` to avoid any break in the existing workflows
#
#

fix(ui): support for code authflow in OIDC

---

openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx

fix: domain cypress

---

openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/AddGlossaryTermForm/AddGlossaryTermForm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/TagSuggestion.tsx

Fixes #13958
- I worked on fixing the loss of tags on edit glossary
https://github.com/open-metadata/OpenMetadata/assets/66266464/910ce8d9-483d-46d1-bd41-fb490b747541
#
#

fix(ui): glossary tags missing while edit operation

---

ingestion/src/metadata/ingestion/api/topology_runner.py

Fixed overwriting data for service entities and stage.overwrite in topology
#
#

Fixed overwriting data for service entities and stage.overwrite in topology

---

ingestion/src/metadata/ingestion/source/database/bigquery/connection.py
ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/src/metadata/ingestion/source/database/bigquery/queries.py
ingestion/src/metadata/utils/fqn.py

Fix #14099: fix bigquery test connection & SP query
#
#

#14099: fix bigquery test connection & SP query

---

openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/profiler/external_workflow.md

MINOR: Fix external profiler yaml docs

---

openmetadata-service/src/main/resources/json/data/app/DataInsightsApplication.json
openmetadata-service/src/main/resources/json/data/app/DataInsightsReportApplication.json
openmetadata-service/src/main/resources/json/data/app/SearchIndexingApplication.json

- Data Insights app was not getting properly initialized after latest changes
- Apps were missing displayName when being installed on server start
#
#

MINOR - Fix app init details

---

common/src/main/java/org/openmetadata/common/utils/CommonUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/secrets/SecretsManager.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/DatabaseServiceResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/PipelineServiceResourceTest.java

Otherwise we dont load tags/marketplace/glossaries from Collate's binaries
#
#

MINOR - Add Collate resources from classPath jars

---

openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/AddGlossaryTermForm/AddGlossaryTermForm.component.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/AsyncSelect.mock.ts

- I worked on fixing glossary add term not working
- filtered out glossary term options for the same term in  related terms field while edit glossary.
- 
https://github.com/open-metadata/OpenMetadata/assets/66266464/e404ac8d-3e47-4b6e-ac76-f9384f130604
#
#

Minor: fix glossary add term not working

---

openmetadata-service/src/main/java/org/openmetadata/service/secrets/SecretsManager.java
openmetadata-service/src/main/resources/json/data/app/DataInsightsReportApplication.json

- By Default the Application for Data Insight Reporting is init with daily scheduled run , updating it to run weekly.
#
#

MINOR: Change Default Report to Weekly instead of daily during Server Init

---

openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityRightPanel/EntityRightPanel.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityRightPanel/EntityRightPanel.tsx
openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceMainTabContent.tsx
openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedurePage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityRightPanelClassBase.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityRightPanelClassBase.ts

I worked on adding a base class for the entity right panel.
#
#

Minor: add base class for entity right panel

---

ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py

Minor: Fix 'str' object has no attribute 'serviceType' for SP Lineage

---

ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py

Minor: Fix airflow empty status

---

openmetadata-docs/content/v1.2.x/menu.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/auth_provider.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/client.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/client_utils.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/credentials.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/dashboard_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/data_insight_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/es_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/index.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/ingestion_pipeline_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/lineage_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/mlmodel_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/models.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/ometa_api.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/patch_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/patch_mixin_utils.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/pipeline_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/provider_registry.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/query_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/role_policy_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/routes.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/search_index_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/server_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/service_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/table_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/tests_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/topic_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/user_mixin.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/utils.md
openmetadata-docs/content/v1.2.x/sdk/python/api-reference/version_mixin.md

Python API reference documentation

doc: Python API reference documentation

---

openmetadata-docs/content/v1.2.x/connectors/database/snowflake/yaml.md

Fixes #14153: Fix snowflake docs
#
#

#14153: Fix snowflake docs

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java

Fix Patch in Apps

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java

Assignee can only be user who is not a bot or Team

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/resources/elasticsearch/en/container_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/dashboard_data_model_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/dashboard_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/data_products_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/glossary_term_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/mlmodel_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/pipeline_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/search_entity_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/stored_procedure_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/table_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/tag_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/team_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/topic_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/user_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/tag_index_mapping.json
openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/ExplorePage/ExplorePageV1.component.tsx

Fixes : 
#13922 , #14143
I worked on ... because ... Aggregation case insensitive issue and explore page search fix
#
- [x ] Bug fix

Aggregation case insensitive issue and explore page search fix

---

openmetadata-docs/content/v1.0.x/deployment/kubernetes/on-prem.md
openmetadata-docs/content/v1.0.x/menu.md
openmetadata-docs/content/v1.2.x/menu.md

Fixed links for /deployment/kubernetes/on-prem in the documentation
#
#

Minor: fixed the links for kubernetes on premises page

---

common/pom.xml
pom.xml

#14217: remove logback dependency

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java

USer password appears in failing entities

---

openmetadata-ui/src/main/resources/ui/cypress/common/DataInsightUtils.js
openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Service/postgres.spec.js
openmetadata-ui/src/main/resources/ui/src/components/AppBar/Suggestions.tsx

fixed failing cypress for 
- superset
- metabase
#
#

Miner: cypress - fixed failing cypress in main

---

openmetadata-docs/content/v1.2.x/how-to-guides/index.md

Corrected link on home page
#
#

Docs: Link corrected

---

openmetadata-service/src/main/resources/elasticsearch/en/test_case_resolution_status_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/test_case_resolution_status_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/test_case_resolution_status_index_mapping.json

Minor: Fix test case resolution status indexes

---

ingestion/src/metadata/ingestion/models/patch_request.py

Remove column displayName from patch request
#
#

MINOR: Remove column displayName from patch request

---

openmetadata-service/src/main/resources/elasticsearch/indexMapping.json

fix: revert testCaseResolutionStatus index mapping

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/resources/elasticsearch/en/glossary_term_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/metadata_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/tag_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/glossary_term_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/metadata_service_search_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/tag_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/glossary_term_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/metadata_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/tag_index_mapping.json

Minor: fix entityType aggregation

---

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/assets-tabs.less
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TagsUtils.tsx

fix(ui): tag updataion with derived tags

---

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/assets-tabs.less

Fixes missalignement of Delete notification for Assets tab
Fixed: 
https://github.com/open-metadata/OpenMetadata/assets/12962843/a19b043a-4efb-4328-b70a-d87e90c69903
#
#

FIXED: notificaiton widget position issue

---

openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

I worked on ... because ... remove keyword for entitytype aggregation in opensearch as well
#
- [ x] Bug fix

[MINOR] remove keyword for entitytype aggregation in opensearch as well

---

openmetadata-service/src/main/resources/json/data/app/DataInsightsReportApplication.json

Propogate assets to es

---

openmetadata-service/src/main/java/org/openmetadata/service/search/EntityBuilderConstant.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchEntityIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TopicIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/resources/elasticsearch/en/container_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/search_entity_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/table_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/topic_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/indexMapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/container_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/search_entity_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/table_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/topic_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/table_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/topic_index_mapping.json

Fix #14308: Search is not working for column/schema field level

---

ingestion/src/metadata/ingestion/source/database/mssql/metadata.py
ingestion/src/metadata/ingestion/source/database/mssql/queries.py
ingestion/src/metadata/ingestion/source/database/mssql/utils.py
ingestion/tests/unit/topology/database/test_mssql.py

#13696: add support for dot in schema name to fetch tables

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Customproperties.spec.js
openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.tsx

https://github.com/open-metadata/OpenMetadata/assets/33024356/1eebfa72-5930-4a37-b2b5-480af0a0e5bc
#
#

Fix custom attrs for glossary term

---

ingestion/tests/cli_e2e/common/test_cli_dashboard.py
ingestion/tests/cli_e2e/test_cli_metabase.py
ingestion/tests/cli_e2e/test_cli_powerbi.py
ingestion/tests/cli_e2e/test_cli_quicksight.py
ingestion/tests/cli_e2e/test_cli_redash.py
ingestion/tests/cli_e2e/test_cli_tableau.py

Fixed dashboard e2e counts due to:
- Since now after the 1st ingestion run in the subsequent ingestion runs we only update the entities if something has changed on the source side, the counts for 2nd and 3rd tests have been reduced.
- Changes happened on the dashboard instances due to some new dashboards were added into the instances for demo instance
#
#

MINOR: Fixed dashboard e2e counts after put v/s patch update and demo instance changes

---

openmetadata-ui/src/main/resources/ui/cypress/common/DataInsightUtils.js
openmetadata-ui/src/main/resources/ui/cypress/common/advancedSearch.js
openmetadata-ui/src/main/resources/ui/cypress/common/advancedSearchQuickFilters.js
openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/constants/redirections.constants.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/ActivityFeed.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AddTeamAsOwner.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AdvancedSearchQuickFilters.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/SearchFlow.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsight.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightAlert.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightSettings.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Domains.spec.js
openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.component.tsx

Minor(Cypress): Fixed failing cypress

---

openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchIndexFactory.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchEntitiesProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchEntitiesProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/util/TablesInitializer.java

I worked on ... because ... chnages needed for adding knowledgeCenterIndex
#

changes needed for adding knowledgeCenterIndex

---

openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummary.tsx

Fixes #12539
Change default value from last 3 days, to last 30 days in test case result screen
#
#

#12539 change the default "last 3 days" for Data Quality TestCaseResults

---

openmetadata-spec/src/main/resources/json/schema/api/data/createQuery.json
openmetadata-spec/src/main/resources/json/schema/entity/data/query.json
openmetadata-spec/src/main/resources/json/schema/type/queryParserData.json
openmetadata-spec/src/main/resources/json/schema/type/tableQuery.json

Fixed json schema descriptions for query duration from seconds to milliseconds
#
#

MINOR: Fixed json schema descriptions for query duration from seconds to milliseconds

---

openmetadata-docs/content/v1.1.x/how-to-guides/data-governance/index.md
openmetadata-docs/content/v1.1.x/how-to-guides/quick-start-guide-for-admins/index.md
openmetadata-docs/content/v1.1.x/how-to-guides/quick-start-guide-for-admins/teams-and-users/index.md
openmetadata-docs/content/v1.2.x/how-to-guides/admin-guide/index.md
openmetadata-docs/content/v1.2.x/how-to-guides/admin-guide/teams-and-users/index.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-governance/index.md

Corrected the URL for v1.1 and v1.2 docs for the Admin guide on Roles & Policies
v1.2 - https://docs.open-metadata.org/v1.2.x/how-to-guides/admin-guide/roles-policies
v1.1 - https://docs.open-metadata.org/v1.1.x/how-to-guides/quick-start-guide-for-admins/admin-guide-roles-policies
#
#

DOCS: URL corrections

---

ingestion/src/metadata/ingestion/ometa/mixins/tests_mixin.py
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseResolutionStatusRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResolutionStatusResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java

- renamed API endpoint to `incident`
#
#

MINOR: renamed API endpoints from `resolution` to `incident`

---

ingestion/src/metadata/ingestion/api/topology_runner.py

Fixed entity request left check in topology runner
#
#

MINOR: Fixed entity request left check in topology runner

---

openmetadata-docs/content/v1.2.x/deployment/security/enable-jwt-tokens.md

chore(docs): Update JWT Token snippet path

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.js
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ProfilerSettingsModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ProfilerSettingsModal.tsx

Fixes #14351
fixed profiler setting does not persist for sample data count
https://github.com/open-metadata/OpenMetadata/assets/71748675/f1265025-2109-45c0-8115-6e20536d6dbc
#
#

#14351 fixed profiler setting is not persist for sample data count

---

openmetadata-docs/content/partials/v1.2/releases/latest.md
openmetadata-docs/content/v1.0.x/developers/open-source-community.md
openmetadata-docs/content/v1.0.x/quick-start/local-deployment.md
openmetadata-docs/content/v1.0.x/releases/releases/index.md
openmetadata-docs/content/v1.1.x/developers/open-source-community.md
openmetadata-docs/content/v1.1.x/how-to-guides/data-collaboration/index.md
openmetadata-docs/content/v1.1.x/how-to-guides/data-discovery/index.md
openmetadata-docs/content/v1.1.x/how-to-guides/data-insights/data-culture.md
openmetadata-docs/content/v1.1.x/how-to-guides/data-insights/index.md
openmetadata-docs/content/v1.1.x/how-to-guides/data-lineage/column.md
openmetadata-docs/content/v1.1.x/how-to-guides/data-lineage/index.md
openmetadata-docs/content/v1.1.x/how-to-guides/data-lineage/manual.md
openmetadata-docs/content/v1.1.x/how-to-guides/data-quality-profiler/index.md
openmetadata-docs/content/v1.1.x/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.1.x/releases/releases/index.md
openmetadata-docs/content/v1.2.x/connectors/custom-connectors.md
openmetadata-docs/content/v1.2.x/developers/open-source-community.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-collaboration/index.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-discovery/index.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-governance/glossary/approval.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-insights/data-culture.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-insights/index.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-lineage/column.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-lineage/index.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-lineage/manual.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-quality-profiler/index.md
openmetadata-docs/content/v1.2.x/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.2.x/releases/releases/index.md

All the docs with embedded Youtube videos have been resized
For example
#
#

Docs: YouTube images have been resized

---

.github/workflows/cypress-integration-tests-mysql-skip.yml
.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql-skip.yml
.github/workflows/cypress-integration-tests-postgresql.yml

Fixes [issue-#14324](https://github.com/open-metadata/OpenMetadata/issues/14324)
These changes introduces the changes requested in issue #14324. With these changes,
1.  The workflow will be triggered for main branch everyday at 00:30 UTC.
2. The workflow will not run for draft PRs.
3. The workflow will run only if one of the labels contains 'e2e' in its name.
4. The workflow will run on 4 machines parallelly.
#
#

Update Cypress CI workflows for issue-14324

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/CustomMetric.spec.js
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx

fixed failing cypress for the custom metric 
#
#

Minor (cypress): fixed failing cypress for custom metric

---

ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py

Minor: Improve exception handling in Superset

---

ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py

Minor: Airflow skip task status if task deleted

---

.github/workflows/java-checkstyle.yml
.github/workflows/yarn-coverage.yml

Fix ci label

---

openmetadata-docs/content/v1.2.x/connectors/database/athena/index.md
openmetadata-docs/content/v1.2.x/connectors/database/azuresql/yaml.md
openmetadata-docs/content/v1.2.x/connectors/database/bigquery/index.md
openmetadata-docs/content/v1.2.x/connectors/database/bigquery/yaml.md
openmetadata-docs/content/v1.2.x/connectors/database/couchbase/yaml.md
openmetadata-docs/content/v1.2.x/connectors/database/databricks/index.md
openmetadata-docs/content/v1.2.x/connectors/database/presto/yaml.md
openmetadata-docs/content/v1.2.x/connectors/ingestion/deployment/index.md
openmetadata-docs/content/v1.2.x/connectors/ingestion/lineage/index.md
openmetadata-docs/content/v1.2.x/connectors/ml-model/mlflow/yaml.md
openmetadata-docs/content/v1.2.x/connectors/ml-model/sagemaker/yaml.md
openmetadata-docs/content/v1.2.x/connectors/storage/s3/yaml.md
openmetadata-docs/content/v1.2.x/deployment/docker/index.md
openmetadata-docs/content/v1.2.x/deployment/security/index.md
openmetadata-docs/content/v1.2.x/deployment/security/okta/bare-metal.md
openmetadata-docs/content/v1.2.x/deployment/security/okta/docker.md
openmetadata-docs/content/v1.2.x/deployment/upgrade/kubernetes.md
openmetadata-docs/content/v1.2.x/how-to-guides/admin-guide/how-to-ingest-metadata.md
openmetadata-docs/content/v1.2.x/how-to-guides/index.md
openmetadata-docs/content/v1.2.x/how-to-guides/user-guide-data-users/tags.md
openmetadata-docs/content/v1.2.x/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.2.x/quick-start/local-kubernetes-deployment.md
openmetadata-docs/content/v1.2.x/quick-start/sandbox.md

Based on the file shared for broken links in Docs, the links have been corrected in v1.2
#
#

DOCS: Broken links in v1.2 corrected

---

openmetadata-service/src/main/resources/json/data/testConnections/metadata/alation.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/metadata/alationConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/metadataService.json
openmetadata-spec/src/main/resources/json/schema/security/credentials/apiAccessTokenAuth.json

Prepare alation connector json schemas
#
#

MINOR: Prepare alation connector json schemas

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/util/NotificationHandler.java

Fixes issue with missing bell notification for glossary task to assignees
#
#

Add notification for Glossary Approval Task

---

ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py

Superset exception handling in 1.1.7

---

ingestion/Dockerfile
ingestion/operators/docker/Dockerfile
ingestion/setup.py
openmetadata-airflow-apis/setup.py

Ingestion inplace package release 1.1.7.
#
#

Minor: Ingestion package release 1.1.7

---

ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py

Superset DataModel Check Fix and integer validation for column
#
#

Minor: Superset DataModel Check Fix

---

ingestion/Dockerfile
ingestion/operators/docker/Dockerfile
ingestion/setup.py
openmetadata-airflow-apis/setup.py

Bumping ingestion package 1.1.7
#
#

Minor: Bump ingestion package version 1.1.7

---

bootstrap/sql/migrations/native/1.3.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.3.0/postgres/schemaChanges.sql

In case any old test connection workflow is still stored with the `noop` provider.
#
#

MINOR - Truncate automations_workflow

---

openmetadata-ui/src/main/resources/ui/src/components/InlineEdit/InlineEdit.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/InlineEdit/InlineEdit.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/InlineEdit/InlineEdit.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyInput.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyInput.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.tsx

Fixes #14266 
I worked on  #14266 
https://github.com/open-metadata/OpenMetadata/assets/59080942/61d7e8e3-c53d-4b91-bac4-06a75a69dae1
#
#

Fix [#14266]: CustomProperty page loading and error toast issue

---

openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts

The PR fixes add ingestion page breaking error as shown in below video
https://github.com/open-metadata/OpenMetadata/assets/28966081/7cf96c40-4fd1-4616-8d09-0ce76652e406
#
#

MINOR: Fixed add ingestion page breaking

---

README.md

Worked on modifying Readme
#
#

MINOR: Update README.md

---

openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/AsyncSelectList/AsyncSelectList.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/TagsSelectForm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/TagsSelectForm.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsViewer/TagsViewer.interface.ts
openmetadata-ui/src/main/resources/ui/src/constants/Tag.constants.ts

Fixes #14317 
I worked on fixing the broken glossary link in the table.
https://github.com/open-metadata/OpenMetadata/assets/58542468/0eba00df-cd6f-472c-9b36-43d73b3a5804
#
#

#14317 fix: glossary term broken link

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java

Fixes [#14355](https://github.com/open-metadata/OpenMetadata/issues/14355)
#
#

Remove and unschedule jobs on

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/ActivityFeedCard.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AppBar/Appbar.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AppContainer/AppContainer.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/ApplicationConfigProvider/ApplicationConfigProvider.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/AnnouncementModal/AddAnnouncementModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Reactions/Emoji.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Reactions/Reactions.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/WebAnalytics/WebAnalyticsProvider.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/EntityPageInfos/AnnouncementDrawer/AnnouncementDrawer.test.tsx
openmetadata-ui/src/main/resources/ui/src/hooks/LocationSearch/useLocationSearch.test.ts
openmetadata-ui/src/main/resources/ui/src/pages/CreateUserPage/CreateUserPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/KPIList.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/SignUp/SignUpPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/WebAnalyticsUtils.test.ts

Fix failing test of #14349 
#
#

fix failing test case of cleanup UI

---

ingestion/src/airflow_provider_openmetadata/lineage/status.py
ingestion/tests/integration/airflow/test_lineage_runner.py
ingestion/tests/integration/airflow/test_status_callback.py
ingestion/tests/integration/integration_base.py
ingestion/tests/integration/ometa/test_ometa_table_api.py

#14320 - FIx Airflow Callback datetime conversion

---

ingestion/tests/integration/airflow/test_lineage_runner.py

Ci passed here https://github.com/open-metadata/OpenMetadata/pull/14487 but blew up in main
#
#

MINOR - Fix py CI

---

openmetadata-service/src/main/resources/elasticsearch/en/dashboard_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/pipeline_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/dashboard_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/pipeline_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/dashboard_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/pipeline_service_index_mapping.json

I worked on ... because ... pipelinseservice and dashboard service . search API throws error after ingesting
#
- [x ] Bug fix

MINOR search fix 

---

openmetadata-service/src/main/java/org/openmetadata/csv/EntityCsv.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseSchemaResource.java
openmetadata-service/src/main/resources/json/data/database/databaseCsvDocumentation.json
openmetadata-service/src/main/resources/json/data/databaseSchema/databaseSchemaCsvDocumentation.json
openmetadata-service/src/test/java/org/openmetadata/csv/EntityCsvTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseSchemaResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/TeamResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java

…tity
Fixes #14493 - Part 1
#
#

14493 Part 1 - Support for database schema, table import export

---

openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts

chore(ui): update star us url with utm_source to track the activity

---

ingestion/src/metadata/ingestion/lineage/parser.py

Minor: Handle Column Lineage Exceptions

---

openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionListTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionListTable.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionPipelineList/IngestionPipelineList.component.tsx

Fixes Remove Ingestion pipeline Links
https://github.com/open-metadata/OpenMetadata/assets/12962843/98b9c350-c98a-4fe4-88b4-5dcd94f1ccf3
#
#

fix(ui): remove pipeline links to dag

---

openmetadata-service/src/main/java/org/openmetadata/csv/EntityCsv.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
openmetadata-service/src/test/java/org/openmetadata/csv/EntityCsvTest.java

Add support for multi record CSV import export
#
#

Add support for multi record CSV import export

---

ingestion/src/metadata/ingestion/models/patch_request.py
ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin_utils.py
ingestion/src/metadata/ingestion/ometa/mixins/server_mixin.py
ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
ingestion/src/metadata/utils/logger.py

Adding extra validation on top of the changed introduced in https://github.com/open-metadata/OpenMetadata/pull/14373
- We are also updating how we are logging the ometa versioning in the workflow execution to help us debug
- Logging cleaner names for Patch requests and pipeline status to keep the logs easier to read
#
#

#13638 - Filter task instance by removed state

---

openmetadata-service/src/main/java/org/openmetadata/service/util/TablesInitializer.java

Validate Migration Needs Search Repository in Extensions

---

ingestion/src/airflow_provider_openmetadata/lineage/runner.py
ingestion/tests/integration/airflow/test_lineage_runner.py

To follow the same logic introduced in PUT vs. PATCH https://github.com/open-metadata/OpenMetadata/issues/14040
#
#

MINOR - Airflow Lineage Backend to verify the fingerprint

---

openmetadata-service/src/main/java/org/openmetadata/csv/EntityCsv.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
openmetadata-service/src/main/resources/json/data/table/tableCsvDocumentation.json
openmetadata-service/src/test/java/org/openmetadata/csv/EntityCsvTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java

Add import export support for Table
#
#

14492 part3 - Add import export support for Table

---

openmetadata-ui/src/main/resources/ui/src/components/Applications/AppRunsHistory/AppRunsHistory.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Applications/AppRunsHistory/AppRunsHistory.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Applications/AppSchedule/AppSchedule.component.tsx

Revert #14119 
This will be now handled from backend
cc -  @mohityadav766 
#
#

revert search index disabling from ui

---

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py

Fixes #10203 
I worked on deleting temp json file.
#
#

#10203 delete temp creds files

---

openmetadata-ui/src/main/resources/ui/src/components/CustomEntityDetail/CustomPropertyTable.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx

https://github.com/open-metadata/OpenMetadata/assets/80886271/e65a8850-2a42-48db-b6fc-bc8a800c92cf
https://github.com/open-metadata/OpenMetadata/assets/80886271/5f556462-53d2-4756-8841-5b2177f563a9

fix(#14369): added sort option in custom property table

---

openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.tsx

Fixes #13982 
I worked on fixing the users and teams mentions which wasn't working as expected before. The team users will now be notified if there is a mention.
#
#

#13982: fix user & teams mentions issue

---

openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/PipelineServiceClientFactory.java

MINOR - Update exception in PipelineServiceClientFactory

---

ingestion/src/metadata/ingestion/lineage/models.py

Fix #14176: Add AzureSQL dialect in lineage

---

openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
openmetadata-ui/src/main/resources/ui/webpack.config.prod.js

Fixes PR #14282 
I worked on adding support for oktaAuth.
https://github.com/open-metadata/OpenMetadata/assets/58542468/edaed59e-3bb0-4e55-a12c-de9ca81ea118
#
#

fix PR #14282 : process/browser support for okta

---

ingestion/src/metadata/ingestion/source/database/salesforce/metadata.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/14569
#
#

Fixes 14569: Fixed salesforce createtablerequest issue

---

ingestion/src/metadata/ingestion/source/database/dbt/constants.py
ingestion/src/metadata/ingestion/source/database/dbt/metadata.py

dbt-core 1.7 generated run_results.json file gives the timestamp in a `str` format instead of a `datetime` object. Added validation to handle the same
#
#

MINOR: Fixed dbt run_results timestamp

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts

Update what's new section for 1.2.4. release
#
#

feat(ui): whats new update for 1.2.4

---

openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/RowData.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/RowData.tsx

- I worked on fixing the sample data value displayed on UI
- Shows the `0` value, rather than showing  NO_DATA_PLACEHOLDER
- optimize a code a bit.
#
#

MINOR: fix the sample data value displayed on UI

---

openmetadata-docs/content/v1.3.x-SNAPSHOT/api/java-sdk.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/api/python-sdk.md

Added sample content, for reference, for API and SDK page
#
#

Minor: Add sample content for the API and SDK pages.

---

openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-service/pom.xml
pom.xml

Update maven plugins and dependencies
#
#

Update maven plugins and dependencies

---

openmetadata-docs/content/v1.2.x/deployment/docker/index.md
openmetadata-docs/content/v1.2.x/quick-start/local-docker-deployment.md

Fixing release version in docker deployment docs
#
#

Docs: Fixing release version for docker deployment

---

ingestion/src/metadata/ingestion/source/database/mssql/lineage.py

Minor: Filter Create SP & Declare Queries for MSSQL Lineage

---

openmetadata-docs/content/v1.2.x/deployment/kubernetes/values.md

Updated the [helm-values page](https://docs.open-metadata.org/v1.2.x/deployment/kubernetes/helm-values) for v1.2.x as per the changes made in [this PR](https://github.com/open-metadata/openmetadata-helm-charts/pull/205).
#
#

docs: Update helm-values documentation for v1.2.4

---

openmetadata-docs/content/v1.2.x/deployment/docker/index.md
openmetadata-docs/content/v1.2.x/quick-start/local-docker-deployment.md

Updating documentation to keep the latest release version i.e. 1.2.4
#
#

[docs]: Update release to 1.2.4

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java

#14471 - Clean up ingestion status when deleting the ingestion pipeline

---

openmetadata-docs/content/v1.2.x/connectors/database/db2/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/db2/index.md

DB2 connector docs, call out db2 package installation

---

ingestion/src/metadata/utils/storage_metadata_config.py
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/GcpConnectionClassConverter.java
openmetadata-service/src/main/resources/json/data/testConnections/storage/gcs.json
openmetadata-service/src/test/java/org/openmetadata/service/secrets/converter/ClassConverterFactoryTest.java
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/storage/gcsConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/storageService.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storage/storageMetadataADLSConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storage/storageMetadataGCSConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storageServiceMetadataPipeline.json

Fixes #11890 
Add GCS support
#
#

#11890: Add GCS Json schema changes

---

openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java

Minor: Revert JWT Filter changes to extract username

---

ingestion/Dockerfile
ingestion/Dockerfile.ci

Minor: Fix IBM DB2 Dependency Installation Issue

---

ingestion/setup.py
ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/qliksense/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/redash/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/client.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/connection.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/models.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/queries.py
openmetadata-service/src/main/resources/json/data/testConnections/dashboard/tableau.json

Fixes https://github.com/open-metadata/OpenMetadata/issues/14109 https://github.com/open-metadata/OpenMetadata/issues/14325
#
#

Fixes 14109 and 14325: Optimised Tableau Connector

---

openmetadata-docs/content/v1.2.x/connectors/metadata/alation/index.md
openmetadata-docs/content/v1.2.x/connectors/metadata/alation/yaml.md
openmetadata-docs/content/v1.2.x/connectors/metadata/index.md
openmetadata-docs/content/v1.2.x/menu.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/metadata/alation/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/metadata/alation/yaml.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/metadata/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/menu.md

Added alation connector docs
#
#

MINOR: Added alation connector docs

---

openmetadata-service/pom.xml
pom.xml

exclude logback

---

.github/workflows/airflow-apis-tests-3_9.yml
.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql.yml
.github/workflows/java-checkstyle.yml
.github/workflows/maven-build.yml
.github/workflows/maven-postgres-tests-build.yml
.github/workflows/maven-sonar-build.yml
.github/workflows/playwright-integration-tests-mysql.yml
.github/workflows/playwright-integration-tests-postgres.yml
.github/workflows/py-checkstyle.yml
.github/workflows/py-tests.yml
.github/workflows/yarn-coverage.yml

See if this gets rid of one error we get sometimes
```
Post job cleanup.
Error: The template is not valid. lewagon/wait-on-check-action/v1.3.1/action.yml (Line: 53, Col: 14): hashFiles('**/Gemfile.lock') failed. Fail to hash files under directory '/home/runner/work/OpenMetadata/OpenMetadata'
```
#
#

MINOR - Bump CI labeller version

---

openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/CustomHtmlRederer/CustomHtmlRederer.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/RichTextEditorPreviewer.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/RichTextEditorPreviewer.tsx

Fixes #14242 
I worked on issue #14242 
https://github.com/open-metadata/OpenMetadata/assets/59080942/b6232cc8-4604-4a8b-8f6f-bcb28ae9687e
#
#

Fix[#14242]: displaying artifacts when using codeBlock in the description of objects

---

openmetadata-ui/src/main/resources/ui/src/components/IngestionWorkflowForm/IngestionWorkflowForm.tsx

I worked on fixing the type error for the validator in the ingestion workflow form.
#
#

Minor: fix validator type error for ingestion workflow form

---

openmetadata-ui/src/main/resources/ui/webpack.config.prod.js

I added a hash for both `filename` and `chunkFilename` in the webpack production config. This means that with each new build, there is a unique hash assigned to each chunk. Users will no longer need to perform a hard refresh to see the changes made in the new build.
#
#

Minor: add hash for filename and chunkFilename in webpack prod config

---

conf/openmetadata.yaml
ingestion/pipelines/sample_data.yaml
openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchDataInsightProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchEntitiesProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/search/models/IndexMapping.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchDataInsightProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchEntitiesProcessor.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
openmetadata-spec/src/main/resources/json/schema/configuration/elasticSearchConfiguration.json
openmetadata-ui/src/main/resources/ui/src/components/Execution/ListView/ListViewTab.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/constants/explore.constants.ts
openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
openmetadata-ui/src/main/resources/ui/src/pages/ExplorePage/ExplorePageV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/Assets/AssetsUtils.ts
openmetadata-ui/src/main/resources/ui/src/utils/Explore.utils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/Explore.utils.ts

Fix #8496: Segregate ES indexes for use in shared infrastructure

---

ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/ingestion/source/database/snowflake/models.py
ingestion/tests/unit/topology/database/test_snowflake.py

#14492 - Fix Snowflake SP parsing with empty signature

---

openmetadata-service/src/main/resources/json/data/eventsubscription/ActivityFeedEvents.json

Fixes issue in activity feed alert , need to add list syntax
#
#

[Fix] Syntax for Activity Feed Alert

---

ingestion/tests/cli_e2e/test_cli_mysql.py

Fix count of tables increased by [this](https://github.com/open-metadata/OpenMetadata/commit/dad886eabaa7cd72a07a0bc1e67aac4c13277c83) commit
#
#

Minor: Fix Mysql E2E Count

---

openmetadata-service/src/main/java/org/openmetadata/service/Entity.java

Fix #11700: While doing recursive delete, check if a previous iteration already deleted the children

---

ingestion/src/metadata/ingestion/ometa/client.py

MINOR: Fixed auth header in REST client
#
#

MINOR: Fixed auth header in REST client

---

openmetadata-docs/content/v1.0.x/deployment/security/azure/bare-metal.md
openmetadata-docs/content/v1.0.x/deployment/security/enable-ssl/ssl-troubleshooting.md
openmetadata-docs/content/v1.1.x/deployment/security/enable-ssl/ssl-troubleshooting.md
openmetadata-docs/content/v1.1.x/deployment/security/okta/bare-metal.md
openmetadata-docs/content/v1.2.x/deployment/security/enable-ssl/ssl-troubleshooting.md
openmetadata-docs/content/v1.2.x/deployment/security/okta/bare-metal.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/security/enable-ssl/ssl-troubleshooting.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/security/okta/bare-metal.md

…ta.yaml
Updated Troubleshooting docs to new env and keys in openemtadata.yml
#
#

[DOCS] Update Troublesbooting docs for SSL to new env and keys

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/glossary/GlossaryResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/GlossaryIndex.java
openmetadata-service/src/main/resources/elasticsearch/en/glossary_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/indexMapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/glossary_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/glossary_index_mapping.json
openmetadata-service/src/main/resources/json/data/app/SearchIndexingApplication.json
openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/SearchIndexingApplication.json
openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json

Fix #14442: Glossary index is not updated on Glossary deletion

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/CustomizeLandingPage.spec.js

I worked on the fix for the Cypress test for a customizable landing page
#
#

Minor: Fix customizable landing page cypress test

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java

- Change Required on OM for building external List Filter 
- Made the Query Param Available for child classes
- Made the getCondtion() as protected so to Override.
#
#

[FEAT] Change for Building Collate List Filter

---

ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
ingestion/src/metadata/ingestion/source/database/snowflake/utils.py

Snowflake - Add Support For Materialised Views
#
#

Minor: Snowflake - Add Support For Materialised Views

---

openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/SchemaTablesTab.tsx

- I worked on fixing table redirect link from databaseSchema tables
Issue :
https://github.com/open-metadata/OpenMetadata/assets/66266464/7efd9851-5d00-4ae7-9938-61979223f80f
Resolved : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/238a8354-b40d-4537-aff7-340025a1aa4e
#
#

MINOR: fix table redirect link from databaseSchema tables

---

openmetadata-docs/content/v1.2.x/deployment/bare-metal/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/bare-metal/index.md

Our [docker image](https://github.com/open-metadata/OpenMetadata/blob/e08891fbade2b7a1a320ae93c62e05d8a1b287db/docker/postgresql/Dockerfile_postgres#L1) already uses postgres version 15 hence the docs are misleading, also [here](https://github.com/open-metadata/OpenMetadata/blob/e08891fbade2b7a1a320ae93c62e05d8a1b287db/openmetadata-docs/content/v1.2.x/deployment/kubernetes/eks.md?plain=1#L27) we already state that the version supported is 12 or greater
#
#

Minor: Fix postgres version on docs

---

openmetadata-docs/content/v1.2.x/how-to-guides/data-governance/glossary/import.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/security/enable-ssl/ssl-troubleshooting.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/how-to-guides/data-governance/glossary/import.md

Added Video to Glossary Bulk Import - https://docs.open-metadata.org/v1.2.x/how-to-guides/data-governance/glossary/import
#
#

Docs: Minor change - Glossary Import Video added

---

.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql.yml

Update CRON of Nightly runs of Cypress CI
New Cron time - `30 2 * * 1-5`
Ref - https://crontab.guru/#30_2_*_*_1-5
#
#

chore(ui): Update CRON of Nightly runs of Cypress CI

---

ingestion/setup.py
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/db2/index.md
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/db2Connection.json
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Db2.md

Fix #11556: Add support for Db2 for IBM i
#
#

Fix #11556: Add support for Db2 for IBM i

---

openmetadata-service/src/main/java/org/openmetadata/service/util/PasswordUtil.java

Fixes  #12584 , Increase the Password range to (8 , 56)
#
#

[Improvement] Increase maximum password length , fixes #12584

---

ingestion/src/metadata/ingestion/source/search/elasticsearch/connection.py
ingestion/src/metadata/ingestion/source/search/elasticsearch/metadata.py

Fix #13894: Ingest only open search indexes ES
#
#

Fix #13894: Ingest only open search indexes ES

---

openmetadata-docs/content/v1.2.x/connectors/database/athena/index.md
openmetadata-docs/content/v1.2.x/connectors/database/athena/yaml.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-governance/glossary/import.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/athena/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/athena/yaml.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/how-to-guides/data-governance/glossary/import.md

**Changes in v1.2 and v1.3**
- Removed redirection to the same page in Athena.
- Corrected link in Athena YAML doc.
- Replaced the Glossary video link - https://docs.open-metadata.org/v1.2.x/how-to-guides/data-governance/glossary/import
#
#

Docs: Change Glossary Video Link

---

openmetadata-ui/src/main/resources/ui/cypress/constants/lineage.constants.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Lineage.spec.js
openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityInfoDrawer/EdgeInfoDrawer.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/AppPipelineModel/AddPipeLineModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomEdge.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomEdge.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomNodeV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/LineageProvider/LineageProvider.tsx

Add cypress for lineage
- Add pipeline between table and table
- Add pipeline between table and topic
- Add column lineage
#
#

add cypress for lineage

---

ingestion/src/metadata/ingestion/source/dashboard/superset/client.py
ingestion/src/metadata/ingestion/source/dashboard/superset/connection.py

Minor: Fix Superset API Test Connection

---

ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/queries.py

Fixes 13343: Fix Superset table name issue

---

ingestion/src/metadata/clients/aws_client.py
ingestion/src/metadata/ingestion/models/lf_tags_model.py
ingestion/src/metadata/ingestion/source/database/athena/client.py
ingestion/src/metadata/ingestion/source/database/athena/connection.py
ingestion/src/metadata/ingestion/source/database/athena/metadata.py
ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/tests/unit/topology/database/test_databricks.py
ingestion/tests/unit/topology/database/test_mssql.py
openmetadata-docs/content/v1.2.x/connectors/database/athena/index.md
openmetadata-docs/content/v1.2.x/connectors/database/athena/yaml.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/athena/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/athena/yaml.md

Fixes https://github.com/open-metadata/OpenMetadata/issues/12180, https://github.com/open-metadata/OpenMetadata/issues/14158
#
#

Fix 12180, 14158: Added LF tags to Athena

---

openmetadata-ui/src/main/resources/ui/src/components/JsonSchemaWidgets/AsyncSelectWidget.tsx

fix: metapilot fqn issue

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
openmetadata-ui/src/main/resources/ui/cypress/support/commands.js
openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/LeftSidebarItem.component.tsx

- I worked on fixing the glossary cypress
#
#

cypress: fix glossary cypress

---

ingestion/tests/unit/topology/database/test_oracle.py

MINOR: Fixed oracle py tests

---

.github/teams.yml

MINOR - Add Pablo to CI teams

---

ingestion/src/metadata/ingestion/source/database/oracle/queries.py
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/oracle/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/oracle/yaml.md

#14727 change all all_ query to dba_ query

---

openmetadata-docs/content/v1.2.x/deployment/ingestion/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/mssql/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/mssql/yaml.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/ingestion/index.md

MINOR - Run ingestion externally docs

---

ingestion/examples/sample_data/usage/query_log.csv
openmetadata-ui/src/main/resources/ui/cypress/e2e/Service/postgres.spec.js

Minor: Postgres cypress move to query log file usage

---

ingestion/setup.py
ingestion/src/metadata/profiler/interface/profiler_interface.py

MINOR: remove typing-extension dependency

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java

- Clear incident ID from testCase entity when a test case result is Sucess
https://github.com/open-metadata/OpenMetadata/assets/13626425/b176ddfc-46f1-424f-86ef-c3274631f443
#
#
Bug fix

MINOR: clear incident ID when testCase result is success

---

ingestion/src/metadata/profiler/metrics/composed/null_ratio.py

Fixes a part of #14544 
I worked on fixing null propagation when col is null.
#
#

#14544 fix null prop. when entire col is null

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/email/EmailPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertsRuleEvaluator.java

Fixes for Ingestion Pipeline Status
#
#

[Fix] Remove info log and using JsonUtils to convert the Ingestion Pipeline

---

ingestion/examples/airflow/dags/airflow_extended_sample_data.py
ingestion/examples/extended_sample_data/datasets/upstream_edge_tables.json
ingestion/pipelines/extended_sample_data.yaml
ingestion/src/metadata/ingestion/source/database/extended_sample_data.py
ingestion/tests/unit/resources/expected_output_column_parser.json
ingestion/tests/unit/test_column_type_parser.py

MINOR: Add Static Sample Data, Modify Lineage

---

openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/LeftSidebar.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/left-sidebar.less

- Remove open/active  Dropdown background color
- fix the background patch from the dropdown element while hovering
https://github.com/open-metadata/OpenMetadata/assets/66266464/e911eb2c-68b7-4937-bea7-d5d9d7b11142
#
#

MINOR: sidebar ui fix

---

openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-service/pom.xml
pom.xml

Dependency updates

---

openmetadata-docs/content/v1.2.x/developers/contribute/build-code-and-run-tests/openmetadata-server.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/openmetadata-server.md

Minor update to developers documentation to make it easier to follow:
- Updated stale information on how to load sample data
- Added small part on how to run the OpenMetadata server directly by running the shell script
- Reordered the sections to avoid having to jump down and up the code a couple times
#
#

MINOR - Update Developers documentation to make it easier to follow

---

openmetadata-docs/content/partials/v1.2/deployment/external-ingestion.md
openmetadata-docs/content/partials/v1.3/deployment/external-ingestion.md
openmetadata-docs/content/v1.2.x/connectors/pipeline/airflow/gcs-composer.md
openmetadata-docs/content/v1.2.x/deployment/ingestion/airflow.md
openmetadata-docs/content/v1.2.x/deployment/ingestion/gcs-composer.md
openmetadata-docs/content/v1.2.x/deployment/ingestion/github-actions.md
openmetadata-docs/content/v1.2.x/deployment/ingestion/index.md
openmetadata-docs/content/v1.2.x/deployment/ingestion/mwaa.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/pipeline/airflow/gcs-composer.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/ingestion/airflow.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/ingestion/gcs-composer.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/ingestion/github-actions.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/ingestion/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/deployment/ingestion/mwaa.md

MINOR - Add notes on external ingestion docs

---

ingestion/src/metadata/profiler/source/metadata.py
ingestion/src/metadata/profiler/source/metadata_ext.py
ingestion/tests/unit/profiler/test_workflow.py
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceProfilerPipeline.json

Fixes #10709: Add useFqnForFiltering to profiler workflow
#
#

Fixes 10709: Add useFqnForFiltering to profiler workflow

---

.github/workflows/maven-build-collate.yml

Rel to https://github.com/open-metadata/openmetadata-collate/pull/267
This PR adds a CI workflow that will trigger a build in the Collate repo. The process will be:
1. New PR in OM
2. Build triggered in Collate to:
1. Checkout PR code 
2. Build OM
3. Build Collate
3. The step will pass only if Collate's build passes
#
#

MINOR - Add Maven Collate Tests CI

---

.github/workflows/maven-build-collate.yml

MINOR - Fix Collate CI action

---

Makefile

Enable Security Scan Reports for ingestion base slim docker image
#
#

fix(CI): Enable Security Scan Reports for ingestion base slim docker image

---

openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/profiler/external_workflow.md
openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/profiler/index.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/ingestion/workflows/profiler/external_workflow.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/ingestion/workflows/profiler/index.md

Minor: Docs add compute metric config for profiler

---

openmetadata-service/pom.xml

Latest version of Mysql removes https://github.com/testcontainers/testcontainers-java/issues/8130
We have to use until testContainer fixes this
#
#

[Fix] Use 8.2.0 version of mysql

---

ingestion/src/metadata/profiler/orm/functions/median.py

MINOR: Fix Vertica profiler median query

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.js
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/TableProfilerChart.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerDetailPage/IncidentManagerDetailPage.tsx

Fixes #14554 test case name's length limitation-DBT
- fixed failing cypress for data quality 
#
#

#14554 test case name's length limitation-DBT

---

.github/workflows/maven-build-collate.yml

Otherwise it failed with `Error: Required input 'sha' not provided`
#
#

MINOR - Maven Collate CI to work on main

---

ingestion/src/metadata/ingestion/api/topology_runner.py
ingestion/src/metadata/ingestion/models/topology.py
ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/tests/unit/topology/dashboard/test_looker.py

- Stored Procedures were not properly following the PUT/PATCH logic cc @ulixius9 
- Looker was not properly migrated to the new context in the usage management cc @OnkarVO7 
#
#

MINOR - Fix SP topology context & Looker usage context

---

ingestion/src/metadata/ingestion/source/database/bigquery/connection.py
ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py

Fixes #14598 
I worked on modifying table level tag issue, and modified the test connection for bigquery taxonomy
#
#

Fixes #14598: Fix Tags / Labels ingestion on includeTags as False

---

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/src/metadata/ingestion/source/database/life_cycle_query_mixin.py
ingestion/src/metadata/ingestion/source/database/redshift/metadata.py
ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py

Added table validation for cost analysis data
#
#

MINOR: Added table validation for cost analysis data

---

.github/CODEOWNERS

minor(config): update openmetadata-ui code reviewers

---

openmetadata-spec/src/main/antlr4/org/openmetadata/schema/EntityLink.g4

Update EntityLink.g4 with new entity types and fields

---

docker/development/Dockerfile
docker/docker-compose-quickstart/Dockerfile

Optimize Server Docker Image and minimize RUN Instruction Layers.
#
#

fix(CI): Optimize Server Docker Image

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/yarn.lock

I worked on adding axios@1.6.4 resolutions in package.json to make sure all the dependencies use Axios with version 1.6.4
https://github.com/open-metadata/OpenMetadata/assets/59080942/64055a64-40af-45ab-872e-2553c21c3ca0
#
#

Minor: add axios@1.6.4 resolutions in package.json

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/src/components/SchemaTable/SchemaTable.component.tsx
openmetadata-ui/src/main/resources/ui/yarn.lock

bump: react-tour to 1.2.6 and styled-components to 6.1.8

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Owner.ts
openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/constants/Version.constants.js
openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
openmetadata-ui/src/main/resources/ui/cypress/constants/glossary.constant.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/redirections.constants.js
openmetadata-ui/src/main/resources/ui/cypress/constants/service.constants.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/GlossaryVersionPage.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Users.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryDetailsRightPanel/GlossaryDetailsRightPanel.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryDetailsRightPanel/GlossaryDetailsRightPanel.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx

- fix glossary term version re-direction back to that term
- fix user and glossary cypress
Issue : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/e15d3e27-11ff-43ca-934b-ac229ed10645
Resolved :  
https://github.com/open-metadata/OpenMetadata/assets/66266464/5c0340a9-6c44-45ce-83cd-a21bfa5c2c2f
#
#

MINOR: fix glossary version re-direction and user and glossary cypress

---

ingestion/src/metadata/data_insight/processor/reports/cost_analysis_report_data_processor.py

Add Cost Analysis timestamp check
#
#

MINOR: Add Cost Analysis timestamp check

---

ingestion/src/metadata/clients/domo_client.py
ingestion/src/metadata/ingestion/models/patch_request.py
ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
ingestion/src/metadata/ingestion/source/dashboard/domodashboard/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/lightdash/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/mode/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/mstr/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/qliksense/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/quicksight/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/redash/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/src/metadata/ingestion/source/database/postgres/metadata.py
ingestion/tests/integration/integration_base.py
ingestion/tests/integration/ometa/test_ometa_patch.py
ingestion/tests/unit/topology/dashboard/test_looker.py
ingestion/tests/unit/topology/dashboard/test_superset.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/14794
#
#

Fix #14794: Refactored and cleaned owner processing in sources

---

ingestion/src/metadata/ingestion/api/topology_runner.py
ingestion/src/metadata/ingestion/models/topology.py
ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
ingestion/src/metadata/ingestion/source/dashboard/domodashboard/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/lightdash/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/mode/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/mstr/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/qliksense/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/quicksight/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/redash/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
ingestion/src/metadata/ingestion/source/messaging/messaging_service.py
ingestion/src/metadata/ingestion/source/mlmodel/mlmodel_service.py
ingestion/src/metadata/ingestion/source/pipeline/databrickspipeline/metadata.py
ingestion/src/metadata/ingestion/source/pipeline/pipeline_service.py
ingestion/src/metadata/ingestion/source/search/search_service.py
ingestion/src/metadata/ingestion/source/storage/storage_service.py
ingestion/tests/unit/topology/dashboard/test_metabase.py
ingestion/tests/unit/topology/test_context.py
ingestion/tests/unit/topology/test_runner.py

Added a few bugs in the last context-related PR. Used the chance to organize the code better and add tests on the main context ops
#
#

MINOR - Fix & Organize topology context

---

ingestion/src/metadata/ingestion/source/database/databricks/client.py
ingestion/src/metadata/ingestion/source/pipeline/databrickspipeline/metadata.py

MINOR: Fix Databricks pipeline client pagination
#
#

MINOR: Fix Databricks pipeline client pagination

---

openmetadata-docs/content/v1.2.x/deployment/docker/index.md
openmetadata-docs/content/v1.2.x/deployment/upgrade/kubernetes.md
openmetadata-docs/content/v1.2.x/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.2.x/releases/roadmap/index.md

Updating documentation to keep the latest release version i.e. 1.2.5
#
#

Minor: Docs update for 1.2.5 release

---

ingestion/src/metadata/ingestion/source/database/snowflake/query_parser.py

Since we are running query against `snowflake.account_usage.query_history` which will contain the query logs for all the databases, we fetch list of all databases and run the query against each database which is not required as it will fetch only duplicate data.
#
#

MINOR: Snowflake fix lineage & usage muti db query

---

openmetadata-docs/content/v1.2.x/connectors/database/hive/yaml.md
openmetadata-docs/content/v1.3.x-SNAPSHOT/connectors/database/hive/yaml.md

MINOR: Fix hive yaml docs

---

openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java
openmetadata-ui/src/main/resources/ui/src/components/common/AirflowMessageBanner/AirflowMessageBanner.tsx

Fix #14590: Improve airflow plugin error message
#
#

Fix #14590: Improve airflow plugin error message

---

openmetadata-ui/src/main/resources/ui/cypress/constants/lineage.constants.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Lineage.spec.js

fix flaky lineage cypress

---

openmetadata-ui/src/main/resources/ui/cypress/common/TaskUtils.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/ActivityFeed.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Task.spec.js
openmetadata-ui/src/main/resources/ui/src/components/Explore/ExplorePage.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/EntityPopOverCard.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerDetailPage/IncidentManagerDetailPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TestCaseDetailsPage/TestCaseDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/SearchClassBase.ts
openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx

- support test case data in entity popover card
- fix activity feed and task cypress failure
https://github.com/open-metadata/OpenMetadata/assets/66266464/c282158a-075a-471f-998c-b269793c596d
#
#

MINOR: support testCase data in entity card popover and fix cypress

---

ingestion/src/metadata/applications/auto_tagger.py
ingestion/src/metadata/data_insight/processor/reports/entity_report_data_processor.py
ingestion/src/metadata/data_insight/processor/reports/web_analytic_report_data_processor.py
ingestion/src/metadata/data_insight/source/metadata.py
ingestion/src/metadata/data_quality/processor/test_case_runner.py
ingestion/src/metadata/data_quality/source/test_suite.py
ingestion/src/metadata/ingestion/bulksink/metadata_usage.py
ingestion/src/metadata/ingestion/processor/query_parser.py
ingestion/src/metadata/ingestion/sink/metadata_rest.py
ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
ingestion/src/metadata/ingestion/source/database/query_parser_source.py
ingestion/src/metadata/ingestion/source/messaging/messaging_service.py
ingestion/src/metadata/ingestion/source/mlmodel/mlmodel_service.py
ingestion/src/metadata/ingestion/source/pipeline/pipeline_service.py
ingestion/src/metadata/ingestion/source/search/search_service.py
ingestion/src/metadata/ingestion/source/storage/storage_service.py
ingestion/src/metadata/ingestion/stage/table_usage.py
ingestion/src/metadata/pii/processor.py
ingestion/src/metadata/profiler/processor/processor.py
ingestion/src/metadata/profiler/source/metadata.py
ingestion/tests/cli_e2e/base/test_cli.py

Add better names to each step involved in the ingestion. It will appear in the ingestion status modal
#
#

MINOR - Update step names

---

openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/LeftSidebar.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/LeftSidebar.constants.ts

- I worked on fixing the sidebar duplicate key for observability alerts
- supported nested selected route to 1 level.
Issue :  
https://github.com/open-metadata/OpenMetadata/assets/66266464/f526ccf4-fb41-404d-9f8d-23339b5b0658
#
#

MINOR: fix sidebar duplicate key for observability alerts

---

openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/FeedResourceTest.java

Fix feedResourceTest

---

openmetadata-service/pom.xml

Use mysql 8.3.0 for integration tests
#
#

MINOR - Bump testcontainers & mysql test version

---

docker/docker-compose-quickstart/Dockerfile

This reverts commit 390e731eb42e8b1757cefd0b302d20bc83e049a9.
#
#

Revert "fix: docker/docker-compose-quickstart/Dockerfile to reduce vulnerabilities (#14862)"

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java

[Fix] Sort Tier Data

---

openmetadata-ui/src/main/resources/ui/cypress/support/commands.js
openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/LeftSidebar.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/LeftSidebar.constants.ts

CYPRESS : fix logout cypress issue

---

openmetadata-airflow-apis/pyproject.toml

MINOR: Fix pyproject.toml readme

---

docker/development/Dockerfile
docker/docker-compose-quickstart/Dockerfile

Update alpine package to avoid vulnerabilities in docker image
#
#

Minor: fix alpine package to avoid vulnerabilities

---

docker/docker-compose-quickstart/Dockerfile

fix(CI): Dockerfile Instructions
#
#

fix(CI): Dockerfile Instructions

---

docker/development/docker-compose-postgres.yml
docker/development/docker-compose.yml
docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml

fix `DB_PARAMS` for Docker Compose files
#
#

chore(docker-compose): fix `DB_PARAMS` for Docker Compose files

---

openmetadata-ui/src/main/resources/ui/src/components/AppContainer/AppContainer.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/left-sidebar.less

- I worked on supporting `RTL` in sidebar
https://github.com/open-metadata/OpenMetadata/assets/66266464/fc38e745-dfe8-4786-9388-058243372c1a
#
#

MINOR : supported rtl in sidebar

---

.github/workflows/maven-build-collate.yml

until we figure out how to get the CI clean and faster on our runners
#
#

MINOR - Run Collate CI only on main

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

I worked on ... because ... Knowledge Center SearchFIx
#

Knowledge Center SearchFIx

---

openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EventSubscriptionRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/events/EventSubscriptionResourceTest.java

Fixed Issues for Patch Filters
#
#

[Fixes] Patch Minor Fixes

---

openmetadata-service/src/main/java/org/openmetadata/service/util/EmailUtil.java
openmetadata-service/src/main/resources/emailTemplates/dataInsightReport.ftl

Issue With View report Link Fix
#
#

[Fix]Data Insight Report Link Fix

---

ingestion/tests/cli_e2e/database/athena/athena.yaml
ingestion/tests/cli_e2e/test_cli_mssql.py
ingestion/tests/cli_e2e/test_cli_redshift.py

Filter the e2e_db in athena e2e yaml
#
#

MINOR: Fix E2E failures

---

openmetadata-ui/src/main/resources/ui/src/components/Applications/AppDetails/AppDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ConnectionConfigForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/FormBuilder/FormBuilder.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx
openmetadata-ui/src/main/resources/ui/src/pages/AppInstall/AppInstall.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx

https://github.com/open-metadata/OpenMetadata/assets/12962843/b89ccff1-29c1-438e-8833-e182c7a17384
#
#

fix(ui): remove airflow from generic form component

---

openmetadata-ui/src/main/resources/ui/src/pages/NotificationListPage/NotificationListPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ObservabilityAlertsPage/ObservabilityAlertsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/ObservabilityUtils.test.ts

Unit tests for #10757 
I worked on adding unit tests for newly added components in #14749 
#
#

Unit tests for observability and notification alert flow components

---

openmetadata-ui/src/main/resources/ui/src/components/Applications/AppDetails/AppDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Applications/AppDetails/app-details.less
openmetadata-ui/src/main/resources/ui/src/components/BotListV1/BotListV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/UserTab/UserTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Team/TeamDetails/teams.less
openmetadata-ui/src/main/resources/ui/src/pages/Application/ApplicationPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/Configuration/LoginConfigurationDetails/LoginConfigurationPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/CustomLogoConfigSettingsPage/CustomLogoConfigSettingsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/CustomPageSettings/CustomPageSettings.tsx
openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx
openmetadata-ui/src/main/resources/ui/src/pages/EmailConfigSettingsPage/EmailConfigSettingsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/NotificationListPage/NotificationListPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ObservabilityAlertDetailsPage/ObservabilityAlertDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ObservabilityAlertsPage/ObservabilityAlertsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/Persona/PersonaDetailsPage/PersonaDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/Persona/PersonaListPage/PersonaPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesListPage/PoliciesListPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesListPage/RolesListPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ServicesPage/ServicesPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteDetailsPage/TestSuiteDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/UserListPage/UserListPageV1.tsx
openmetadata-ui/src/main/resources/ui/src/styles/app.less

- I worked on fixing side spacing( x-axis) in setting and other pages
#
#

MINOR : fix side spacing in setting and other pages

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataModels/DataModelDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedurePage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx

- I worked on removing count API call on every patch action in entities pages
https://github.com/open-metadata/OpenMetadata/assets/66266464/8288ebbd-0cb6-4893-aee9-4f59eaa402b0
#
#

UI: remove count api call on every patch in entities pages

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/IncidentManager.spec.js
openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TotalDataAssetsWidget/TotalDataAssetsWidget.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/TasksPage.interface.ts
openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.ts

Addressed Incident manager feedback
https://github.com/open-metadata/OpenMetadata/assets/71748675/1113c027-ca0b-4e67-86ed-64a04b60f25c
#
#

Minor: address feedback for incident manager feature

---

.github/workflows/sync-docs-v1.yml

MINOR - Docs sync alert CI

---

openmetadata-docs/content/v1.3.x/menu.md

Minor: Documentation menu item url fix for v1.3

---

openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidget.interface.ts

Update DeleteWidget.interface.ts to use ReactNode for description

---

SECURITY.md
openmetadata-docs/content/v1.0.x/deployment/security/azure/bare-metal.md
openmetadata-docs/content/v1.0.x/deployment/security/azure/docker.md
openmetadata-docs/content/v1.0.x/deployment/security/azure/kubernetes.md
openmetadata-docs/content/v1.1.x/deployment/security/azure/bare-metal.md
openmetadata-docs/content/v1.1.x/deployment/security/azure/docker.md
openmetadata-docs/content/v1.1.x/deployment/security/azure/kubernetes.md
openmetadata-docs/content/v1.2.x/deployment/security/azure/bare-metal.md
openmetadata-docs/content/v1.2.x/deployment/security/azure/docker.md
openmetadata-docs/content/v1.2.x/deployment/security/azure/kubernetes.md
openmetadata-docs/content/v1.3.x/deployment/security/azure/bare-metal.md
openmetadata-docs/content/v1.3.x/deployment/security/azure/docker.md
openmetadata-docs/content/v1.3.x/deployment/security/azure/kubernetes.md

Fixes #12461
I worked on fixing documentation for Azure SSO
#
#

Fix #12461: Azure SSO Docs

---

openmetadata-ui/src/main/resources/ui/src/pages/AddNotificationPage/AddNotificationPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/AddObservabilityPage/AddObservabilityPage.test.tsx

Unit tests for https://github.com/open-metadata/OpenMetadata/issues/10757
I worked on adding unit tests for newly added components in https://github.com/open-metadata/OpenMetadata/pull/14749
#
#

add notification & observability unit test cases

---

openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.tsx

I worked on fixing the fqn mention encoding because ...
#
#

fix mention fqn encoding

---

openmetadata-docs/content/partials/v1.3/deployment/upgrade/upgrade-prerequisites.md

MINOR: Docs - Lineage Breaking Change

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Task/TaskTab/TaskTab.component.tsx

- I worked on fixing user activity feed data in case of admin visited any user page
- fix the new data load in the entities page after the task is accepted.
- 
https://github.com/open-metadata/OpenMetadata/assets/66266464/d4bb46c5-f2eb-44eb-ad82-2fe93a57383d
https://github.com/open-metadata/OpenMetadata/assets/66266464/3cf5cfbb-605d-4e54-922e-a177297b2761
#
#

MINOR: fix user activity feed data in case of admin

---

openmetadata-ui/src/main/resources/ui/src/pages/AppInstall/AppInstall.component.tsx

Fixes schedule option for DataInsightReport Application
https://github.com/open-metadata/OpenMetadata/assets/12962843/d64c6161-eb99-49ec-9525-7899ef884542
#
#

fix(ui): schedule option for DataInsightReport Application

---

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DashboardDataModelIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchEntityIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/StoredProcedureIndex.java

I worked on ... because ... missing followers in data assets
#

missing followers in data assets

---

ingestion/pipelines/extended_sample_data.yaml
ingestion/src/metadata/ingestion/source/database/extended_sample_data.py

Adds Nested Glossary Terms to Extended Sample Data
#
#

Minor: Add extended glossary

---

openmetadata-ui/src/main/resources/ui/src/utils/SearchClassBase.ts

Refactor search options in SearchClassBase

---

openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

Fix TestSuiteSearch case for OpenSearch

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

Fixes OpenMetadata Operations to wait for the job to finish
#
#

[Fix] Wait for Indexing Job to complete

---

ingestion/tests/cli_e2e/test_cli_powerbi.py

I worked on fixing e2e counts
#

Minor: Fix E2E Powerbi

---

conf/openmetadata.yaml
openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
openmetadata-service/src/main/java/org/openmetadata/service/util/TablesInitializer.java
openmetadata-spec/src/main/resources/json/schema/configuration/elasticSearchConfiguration.json

I worked on ... because ... Added Index Factory Config
https://github.com/open-metadata/OpenMetadata/assets/112613760/56a43fb7-6275-441a-9a52-ff8f0ad25507
#

Added Index Factory Config

---

openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java

Issue in initOrganization() due to Policy and Role Repository not initialised
#
#

[Fix]Init Organization Errors Fix

---

ingestion/src/metadata/ingestion/models/patch_request.py
ingestion/src/metadata/ingestion/source/database/athena/client.py
ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py
ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtAzureConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtGCSConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtS3Config.json

Optimised dbt topology and better exception handling for athena LF tags
#
#

MINOR: Optimised dbt topology and better exception handling for athena LF tags

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java
openmetadata-service/src/main/java/org/openmetadata/service/security/MultiUrlJwkProvider.java

Add localhost:8585 as jwks urls; Fix entity consolidations when there is no previous chnage available

---

openmetadata-ui/src/main/resources/ui/src/components/LineageProvider/LineageProvider.tsx
openmetadata-ui/src/main/resources/ui/src/constants/mockTourData.constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx

I worked on fixing the tour flow and updating the mock data for lineage.
https://github.com/open-metadata/OpenMetadata/assets/59080942/e3872705-4833-4f62-80f3-aac90a51b069
#
#

Fix: tour flow and update the mock data

---

ingestion/src/metadata/ingestion/source/database/snowflake/utils.py

`SHOW VIEWS` does not incorporate the changes of a view in case it has been modified using `ALTER VIEW` statement.
We'll use the [GET_DDL](https://docs.snowflake.com/en/sql-reference/functions/get_ddl) method to get the correct view definitions.
#
#

MINOR: Modified snowflake view definition query

---

openmetadata-ui/src/main/resources/ui/cypress/common/AlertUtils.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/ActivityFeed.spec.js

I worked on fixing the cypress tests for 
#
#

Minor: Cypress tests fixes

---

ingestion/src/metadata/utils/datalake/datalake_utils.py

Minor: Fix pyarrow import error

---

.github/workflows/maven-build-collate.yml

This action is just failing for now. Will simplify it on Collate side
#
#

MINOR - Update Collate dispatch CI

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MigrationDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

Fix migration for postgres db

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

Add boosting function and cleanup highlight builder code

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java

taskCount should show total count for openedBy or assignedTo a user

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java

Issue in App Init since the field bot is missing when getting the bot
#
#

[Fix] App Bot is null during init

---

docker/development/docker-compose-postgres.yml
docker/development/docker-compose.yml
docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml

Use `openmetadata-ops.sh` script for migrations.
#
#

feat(docker-compose): Use `openmetadata-ops.sh` script for migrations

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

Add boosting function for tiers

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/CustomMetric.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.js

fixed AUT cypress
- Data quality
- Custom metrics
#
#

cypress: fixed cypress AUT failure for custom metric & data quality

---

openmetadata-ui/src/main/resources/ui/src/components/Applications/AppInstallVerifyCard/app-install-verify-card.less
openmetadata-ui/src/main/resources/ui/src/pages/AppInstall/AppInstall.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json

- fix glossary default selector in search index application while installation
#
#

MINOR: fix glossary default selector in search index application while installation

---

openmetadata-spec/src/main/antlr4/org/openmetadata/schema/EntityLink.g4
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProviderContext.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Widgets/FeedsWidget/FeedsWidget.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/app.less

- Added mention count in landing page mention tab.
- Fix more option in task feed on landing page.
- Remove all count for user's and landing page activity feed.
#
#

MINOR : remove all count for user's activity feed and fix more option in task feed

---

openmetadata-docs/content/v1.2.x/deployment/ingestion/airflow.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/airflow.md

MINOR - Docs for Airflow virtualenv external run

---

docker/development/docker-compose-postgres.yml
docker/development/docker-compose.yml
docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml

fix: docker-compose failed randomly without healthcheck of elasticsearch

---

openmetadata-docs/content/v1.3.x/developers/contribute/build-code-and-run-tests/ingestion-framework.md

put all the `make` commands in a dedicated code block. under the `python setup` section. the `generated service` section now contains explanations for curious individuals.
From my experience, this can be a smoother experience for setting up an environment because it separate ths **actions** from the **context**
#
#

MINOR - docs(ingestion-framework): use code block

---

Makefile
scripts/update_version.py

Update Make Recipes for 1.3.0 changes
#
#

chore(Makefile): Update Make Recipes for 1.3.0 changes

---

openmetadata-docs/content/v1.3.x/deployment/ingestion/airflow.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/gcs-composer.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/mwaa.md
openmetadata-docs/content/v1.3.x/deployment/upgrade/kubernetes.md
openmetadata-docs/content/v1.3.x/quick-start/local-docker-deployment.md

Update documentation with the latest release 1.3.0
#
#

Minor: Update Openmetadata docs with latest release 1.3.0

---

openmetadata-docs/content/v1.2.x/releases/roadmap/index.md
openmetadata-docs/content/v1.3.x/connectors/database/sas/index.md
openmetadata-docs/content/v1.3.x/releases/roadmap/index.md

Docs: SAS connector content modification for documentation

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

https://github.com/open-metadata/OpenMetadata/assets/59080942/d3d74907-d08f-4517-9ca3-060ccfea854e

Update video links in WhatsNewModal

---

openmetadata-docs/content/v1.3.x/deployment/kubernetes/aks.md
openmetadata-docs/content/v1.3.x/deployment/kubernetes/index.md
openmetadata-docs/content/v1.3.x/deployment/kubernetes/values.md
openmetadata-docs/content/v1.3.x/menu.md

docs: Update k8s Helm Values; Add AKS docs for 1.3.X
#
#

docs: Update k8s Helm Values; Add AKS docs for 1.3.X

---

.github/e2eLabeler.yml
.github/workflows/labeler.yml

Add dynamic e2e labeller for cypress tags.
These tags will be used to filter specific cypress tests
#
#

Add e2e labeller

---

openmetadata-docs/content/v1.2.x/connectors/dashboard/powerbi/index.md
openmetadata-docs/content/v1.2.x/connectors/dashboard/powerbi/yaml.md
openmetadata-docs/content/v1.3.x/connectors/dashboard/powerbi/index.md
openmetadata-docs/content/v1.3.x/connectors/dashboard/powerbi/yaml.md

Modified PowerBI Documentation Requirements
#
#

MINOR: Modified PowerBI Documentation Requirements

---

ingestion/src/metadata/great_expectations/action.py
openmetadata-docs/content/v1.3.x/features/integrations/great-expectations.md

- For runtime batch execution of GX we don't have any connection details, hence user need to provide db, schema, and table names -- e.g. running GX against a DF.
#
#
Bug fix

Minor update gx runtime batch

---

.github/workflows/team-labeler.yml

workflow: update team labeler to execute only once

---

openmetadata-service/src/main/java/org/openmetadata/service/exception/UnhandledServerException.java

Fix wrong error type for UnhandledServerException

---

openmetadata-ui/src/main/resources/ui/src/pages/EditEmailConfigPage/EditEmailConfigPage.test.tsx

added unit test for EditEmailConfigPage

---

ingestion/src/metadata/profiler/processor/sample_data_handler.py

MINOR: Fix Sample Data Deserialisation

---

openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AppRouter.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ForgotPassword/ForgotPassword.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ForgotPassword/ForgotPassword.test.tsx

I worked on adding unit test case of forgot password component.
#
#

test: unit test case of forgot password

---

openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OktaAuthenticator.tsx
openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/OktaAuthProvider.tsx

Fixes #15109 
https://github.com/open-metadata/OpenMetadata/assets/12962843/86a26a4e-3f12-4c04-b80e-78e7e4ace323
Summary of the changes:
- We are logging out from okta instead clearing out tokens, Logingout API needs a redirect URL which will be `/signin` in our case. Check which we have to `signout` was always true. hence App keep loading for infinite steps 
Solution
- Instead of calling `signout` we just clear tokens on logout which resolved issue of infinite loading state.
P.S. It wasn't caught with basic testing since it's working fine with dev mode `:3000` 
Testing done with this changes:
- Able to login to Okta on both 3000 as well as 8585
- Okta is able to refresh the token while hitting the expiry of current token
- Logout of application is working fine
#
#

fix(ui): #15109 okta keep loading infinitly

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/ObservabilityAlerts.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/GlossaryVersionPage.spec.js

I worked on fixing the glossary version cypress for AUT
#
#

Minor: Fix glossary version cypress for AUT

---

openmetadata-docs/content/partials/v1.3/deployment/upgrade/upgrade-prerequisites.md
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v130/MigrationUtil.java

MINOR: Fix Mongodb Migration Issue

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ChartRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardDataModelRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SearchIndexRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/StoredProcedureRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/tags/ClassificationResourceTest.java

Source Hash does not need to be part of setFields
#
#

Fix Source Hash Issue

---

openmetadata-ui/src/main/resources/ui/src/components/GithubStarCard/GithubStarCard.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/GithubStarCard/GithubStarCard.test.tsx

- added unit test for github star popup
#
#

Test : added unit test for github star popup

---

openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/AnnouncementsWidget.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/FollowingWidget.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Skeleton/MyData/EntityListSkeleton/EntityListSkeleton.component.tsx

I worked on adding unit test case of announcements widget
#
#

test: unit test cases of right side bar

---

openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.test.tsx

added unit test for CustomPropertiesPageV1

---

openmetadata-ui/src/main/resources/ui/src/components/Skeleton/MyData/EntityListSkeleton/EntityListSkeleton.test.tsx

I worked on adding unit test case for entity list skeleton.
#
#

test: unit test case of entity list skeleton

---

.github/workflows/docker-openmetadata-db.yml
.github/workflows/docker-openmetadata-ingestion-base-slim.yml
.github/workflows/docker-openmetadata-ingestion-base.yml
.github/workflows/docker-openmetadata-ingestion.yml
.github/workflows/docker-openmetadata-postgres.yml
.github/workflows/docker-openmetadata-server.yml
common/pom.xml
docker/docker-compose-ingestion/docker-compose-ingestion.yml
docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml
ingestion/pyproject.toml
openmetadata-airflow-apis/pyproject.toml
openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-clients/pom.xml
openmetadata-dist/pom.xml
openmetadata-service/pom.xml
openmetadata-shaded-deps/elasticsearch-dep/pom.xml
openmetadata-shaded-deps/opensearch-dep/pom.xml
openmetadata-shaded-deps/pom.xml
openmetadata-spec/pom.xml
openmetadata-ui/pom.xml
pom.xml

Prepare `main` for next release cycle
#
#

feat: Prepare `main` for next release cycle

---

openmetadata-docs/content/v1.3.x/menu.md

Realized that the section # links in local are different from the one's on the Docs site. Replaced the links
#
#

Release Docs: Links replaced

---

openmetadata-ui/src/main/resources/ui/src/components/Setting/SettingItemCard/SettingsItemCard.test.tsx

I worked on adding unit test case of settings item card.
#
#

test: add unit test case of settings item card

---

openmetadata-docs/content/v1.2.x/connectors/metadata/alation/yaml.md
openmetadata-docs/content/v1.3.x/connectors/metadata/alation/index.md
openmetadata-docs/content/v1.3.x/connectors/metadata/alation/yaml.md

Added alation filter pattern docs
#
#

DOCS: Added alation filter pattern docs

---

ingestion/src/metadata/ingestion/api/topology_runner.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/15106
#
#

Fix #15106: Fixed Service display name gets updated after an ingestion

---

ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/queries.py

MINOR: Fix superset query to fetch columns

---

ingestion/src/metadata/ingestion/source/mlmodel/sagemaker/metadata.py

Fixed Either for sagemaker
#
#

MINOR: Fixed Either for sagemaker

---

openmetadata-docs/content/v1.2.x/how-to-guides/user-guide-data-users/browser-ext.md
openmetadata-docs/content/v1.2.x/menu.md
openmetadata-docs/content/v1.3.x/how-to-guides/user-guide-data-users/browser-ext.md
openmetadata-docs/content/v1.3.x/how-to-guides/user-guide-data-users/index.md
openmetadata-docs/content/v1.3.x/menu.md
openmetadata-docs/content/v1.3.x/releases/releases/index.md

Changed the title from Chrome Ext to Browser ext for the doc.
Made some partial changes to v1.3 All releases page.... still not complete... will take up the remaining next week.
#
#

Docs: Edits to Chrome Ext & Releases

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Lineage.spec.js
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/NodeSuggestions.component.tsx

lineage cypress fix

---

ingestion/tests/cli_e2e/test_cli_metabase.py
ingestion/tests/cli_e2e/test_cli_powerbi.py
ingestion/tests/cli_e2e/test_cli_quicksight.py
ingestion/tests/cli_e2e/test_cli_redash.py

Fixed dashboard e2e counts:
This [PR](https://github.com/open-metadata/OpenMetadata/pull/15127) now makes sure that we do not update the service entities. Hence we have to do -1 entity
Some modifications were made to the dashboards on their instance.
#
#

MINOR: Fixed dashboard e2e counts

---

openmetadata-docs/content/v1.2.x/connectors/pipeline/databricks-pipeline/index.md
openmetadata-docs/content/v1.2.x/connectors/pipeline/databricks-pipeline/yaml.md
openmetadata-docs/content/v1.3.x/connectors/pipeline/databricks-pipeline/index.md
openmetadata-docs/content/v1.3.x/connectors/pipeline/databricks-pipeline/yaml.md

MINOR: Fix Databricks pipeline lineage docs

---

openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ConnectionConfigForm.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ConnectionConfigForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ServiceConfig.test.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/Service.mock.ts

I worked on adding unit test case of below components:
#
#

test: unit test case of service config component

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/test/NoOpTestApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightDescriptionAndOwnerTemplate.java
openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightTotalAssetTemplate.java
openmetadata-service/src/main/java/org/openmetadata/service/util/EmailUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/util/Utilities.java
openmetadata-service/src/main/resources/emailTemplates/dataInsightReport.ftl

Fixes #15185
- updated the template for Insights Report
- Added graph building and normalization for sending mail 
#
#

Add new Template and Graph building logic for Insights reporting

---

openmetadata-service/src/main/java/org/openmetadata/service/util/UserUtil.java

- In case of ADMIN username create password as ADMIN
- Only create random password In case SMTP is enabled and USERNAME is not admin
#
#

[Fix] AUT issues Create Admin Password for Admin User

---

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java

Fix Cache Init Issue in Startup
#
#

[Fix] Cache Init In Startup

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx

https://github.com/open-metadata/OpenMetadata/assets/71748675/017edddf-e079-4849-b688-b3fed878d8a9
Addressing comments of #15159
#
#

Minor: Addressing comments of #15159

---

bootstrap/sql/migrations/native/1.4.0/mysql/postDataMigrationSQLScript.sql
bootstrap/sql/migrations/native/1.4.0/postgres/postDataMigrationSQLScript.sql
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestDefinitionResource.java
openmetadata-service/src/main/resources/json/data/tests/columnValueMaxToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValueMeanToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValueMedianToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValueMinToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValueStdDevToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesLengthsToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesMissingCountToBeEqual.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesSumToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesToBeInSet.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesToBeNotInSet.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesToBeNotNull.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesToBeUnique.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesToMatchRegex.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesToNotMatchRegex.json
openmetadata-service/src/main/resources/json/data/tests/tableColumnCountToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/tableColumnCountToEqual.json
openmetadata-service/src/main/resources/json/data/tests/tableColumnNameToExist.json
openmetadata-service/src/main/resources/json/data/tests/tableColumnToMatchSet.json
openmetadata-service/src/main/resources/json/data/tests/tableCustomSQLQuery.json
openmetadata-service/src/main/resources/json/data/tests/tableRowCountToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/tableRowCountToEqual.json
openmetadata-service/src/main/resources/json/data/tests/tableRowInsertedCountToBeBetween.json
openmetadata-spec/src/main/resources/json/schema/api/tests/createTestDefinition.json
openmetadata-spec/src/main/resources/json/schema/tests/testDefinition.json

support thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1707970145212869
- Update testDefinition to testCase relation from `APPLIED_TO` to `CONTAINS` 
- Allow recursive deletion of testDefinition (i.e. deleting a testDefinition recursively will delete all associated testCase)
- Prevent deletion of `OpenMetadata` system testCase
#
#
Bug fix

MINOR - fix test definition deletion

---

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/entity-lineage.style.less

I worked on keeping the lineage style LTR only, therefore if the selected application language is RTL then also lineage will have the LTR styling.
#
#

Minor: keep the lineage style LTR only

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionRecentRun/IngestionRecentRun.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionRecentRun/IngestionRecentRuns.component.tsx

Fixes #15214
https://github.com/open-metadata/OpenMetadata/assets/12962843/fc16938c-6594-4df0-95b3-33bb6c8234cc
I worked on showing detailed run status for non-detailed runs
#
#

fix(ui): #15214 open detailed logs for each runs

---

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/NodeSuggestions.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/app.less
openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx

Fixes #15227
- I worked on support display name in lineage search node
#
#

#15227 support display name in lineage search node

---

.github/workflows/maven-build-collate.yml

rel to https://github.com/open-metadata/openmetadata-collate/pull/328
#
#

MINOR - Update Collate dispatch input

---

openmetadata-docs/content/v1.2.x/connectors/pipeline/spline/index.md
openmetadata-docs/content/v1.3.x/connectors/pipeline/spline/yaml.md

update spline docs to support lineage

---

ingestion/src/metadata/ingestion/source/messaging/common_broker_source.py
ingestion/src/metadata/ingestion/source/messaging/kafka/connection.py

MINOR: Kafka handle test connection if Schema Registry not passed

---

ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
ingestion/tests/unit/test_dbt.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/15247
#
#

Fix #15247: Fixed ingesting dbt owners with dot in name

---

.github/e2eLabeler.yml

I worked on changing the PR Labels.
#
#

change PR Labels name

---

openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/NotificationBox/NotificationBox.test.tsx

I worked on adding unit test case of notification box component.
#
#

test: unit test case of notification box

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseResultTab/TestCaseResultTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/ProfilerDashboard/profilerDashboard.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummary.tsx

Fixes #15262
-  UI: tooltip is not visible for the edge of the graph in data quality
- Removed unused code.
#
#

#15262 UI: tooltip is not visible for the edge of the graph in data quality

---

.github/e2eLabeler.yml
.github/workflows/cypress-integration-tests-postgresql.yml

I worked on modifying the PR Labels for integration with cypress.
#
#

changed PR labels for cypress integration

---

openmetadata-docs/content/v1.3.x/connectors/database/unity-catalog/index.md
openmetadata-docs/content/v1.3.x/connectors/database/unity-catalog/yaml.md
openmetadata-docs/content/v1.3.x/releases/roadmap/index.md

MINOR: Fix Unity Catalog & Roadmap Dates Docs

---

.github/workflows/cypress-integration-tests-mysql-pr.yml

Simplify the logic for get cypress filter step
#
#

fix: Simplify the logic for get cypress filter step

---

.github/workflows/cypress-integration-tests-mysql-pr.yml

I worked on modifying the cypress install command.
#
#

fix: cypress pr workflow

---

.github/workflows/cypress-integration-tests-mysql-pr.yml

Github Actions Cypress CI PR custom command and checkout Pull request repo during forked PR.
#
#

fix(CI): Github Actions Cypress CI PR custom command

---

openmetadata-docs/content/partials/v1.3/connectors/yaml/workflow-config-def.md
openmetadata-docs/content/partials/v1.3/connectors/yaml/workflow-config.md
openmetadata-docs/content/v1.3.x/connectors/index.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/external/airflow.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/external/credentials.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/external/gcs-composer.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/external/github-actions.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/external/index.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/external/mwaa.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/index.md
openmetadata-docs/content/v1.3.x/menu.md

https://github.com/open-metadata/OpenMetadata/assets/35870520/0910d2d0-2cf5-40aa-84fb-8c5c34b9fa4f
#
#

MINOR - Update external docs and add examples

---

openmetadata-docs/content/v1.3.x/connectors/database/mongodb/index.md
openmetadata-docs/content/v1.3.x/connectors/database/mongodb/yaml.md

Add profiler documentation for MongoDB.
Depends on:
1. https://github.com/open-metadata/OpenMetadata/pull/15237
2. https://github.com/open-metadata/OpenMetadata/pull/15189
#
#

MINOR: add Mongodb profiler docs

---

ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
ingestion/src/metadata/utils/filters.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/15288
#
#

Fix #15288: Fixed looker projects and optional project filter patterns

---

.github/workflows/cypress-integration-tests-mysql-pr.yml

I worked on fixing the Cypress Pr workflow not working issue.
#
#

fix cypress pr workflow

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java

Fix #15231: Glossary tasks is not showing on landing page to reviewer

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/email/EmailPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/gchat/GChatPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/generic/GenericPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/msteams/MSTeamsPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/slack/SlackEventPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/feeds/MessageParser.java
openmetadata-service/src/main/java/org/openmetadata/service/util/SubscriptionUtil.java

- Added Notification in case of Mention or Task
- Properly formatted username in mention
- Added Notification in case of Mention or Task
#
#

Task and Mention Notification 

---

openmetadata-ui/src/main/resources/ui/public/locales/en-US/Dashboard/workflows/metadata.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/metadata.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/profiler.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Messaging/workflows/metadata.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/MlModel/workflows/metadata.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/workflows/metadata.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Search/workflows/metadata.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Storage/workflows/metadata.md

Minor: update ingestion workflow ui doc

---

openmetadata-service/src/main/java/org/openmetadata/service/secrets/AWSSecretsManager.java

Fixes #15074
This way we don't have any recovery period set (which default to 7 days) and we can recreate a service with the same name and get it to store a new secret properly.
#
#

#15074 - Force AWS Secrets Manager deletion

---

.github/workflows/cypress-integration-tests-mysql-pr.yml

Cypress CI for PR - Use `github.event.number` to fetch PR Labels.
Ref - 
- https://cli.github.com/manual/gh_pr_view
- https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
- https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request
#
#

chore(ci): Use `github.event.number` to fetch PR Labels.

---

openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/ClassConverterFactory.java
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/HiveConnectionClassConverter.java
openmetadata-service/src/test/java/org/openmetadata/service/secrets/converter/ClassConverterFactoryTest.java

MINOR: Fix Hive Metastore Password Encryption

---

ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
ingestion/src/metadata/ingestion/source/database/databricks/queries.py
openmetadata-docs/content/v1.3.x/connectors/database/databricks/index.md
openmetadata-docs/content/v1.3.x/connectors/database/databricks/yaml.md

MINOR: Improve Databricks Tags Ingestion

---

ingestion/src/metadata/ingestion/source/dashboard/metabase/client.py
ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/metabase/models.py
ingestion/tests/unit/topology/dashboard/test_metabase.py

Fixes #15375
Metabase changed the API on version 0.48 and the Metadata Ingestion is not working for the later versions.
https://www.metabase.com/releases/metabase-48#fyi--breaking-changes
This PR renames `ordered_cards` to `dashcards` and adds a small if to handle the breaking change.
#
#

Fixes 15375: Metabase metadata extraction fix

---

ingestion/src/metadata/profiler/orm/functions/conn_test.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/15132
#
#

Fixes #15132: remove semi-colon from db2 query

---

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py

Fixes #15355: fix KeyError issue if not present

---

ingestion/src/metadata/profiler/orm/functions/sum.py

Fixes #15066
Worked on fixing Bigint error in postgres
#
#

Fixes #15066 - bigint out of range issue

---

ingestion/src/metadata/examples/workflows/dbt.yaml
ingestion/src/metadata/ingestion/api/parser.py
ingestion/tests/cli_e2e/dbt/redshift/dbt.yaml
ingestion/tests/unit/test_dbt.py
ingestion/tests/unit/test_workflow_parse.py
openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v132/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v132/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v132/MigrationUtil.java
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtPipeline.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtAzureConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtCloudConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtGCSConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtHttpConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtLocalConfig.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtconfig/dbtS3Config.json

Part 1 of https://github.com/open-metadata/OpenMetadata/issues/15090 dbt JSON Schema & Parsing Improvements
#
#

MINOR: Part 1 of #15090: dbt JSON Schema & Parsing Improvements

---

.github/workflows/cypress-integration-tests-mysql-pr.yml

Use the standard cypress GHA way with environments.
#
#

fix(CI): Use the standard cypress GHA way with environments

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java

[Fix] Remove Instance on delete of the Application

---

pom.xml

MINOR - Bump postgresql version

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java

- Fix User Instance not found 
- Fix Not Authorized Token Non Present
#
#

[Fix] Bug in Token and User Instance due to cache

---

openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/EntityPopOverCard.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerDetailPage/IncidentManagerDetailPage.tsx

- I worked on fixing url malformed issue in entity popover and Incident Manager detail page
-  In Entity popover in case of special character
- In the Incident Manager detail page in case of a special character
Issue :  
https://github.com/open-metadata/OpenMetadata/assets/66266464/2d369606-a35d-49f2-ac32-f428b7780b93
https://github.com/open-metadata/OpenMetadata/assets/66266464/7ee48640-00c9-414a-ba9b-999a6e663db7
Resolved :  
https://github.com/open-metadata/OpenMetadata/assets/66266464/7964fff4-dabf-45e1-a799-b36f93361491
https://github.com/open-metadata/OpenMetadata/assets/66266464/13afd73c-b254-4e71-91e2-de57746a7aca
#
#

fix url malformed issue in entity popover and data insight detail page

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionWorkflowForm/IngestionWorkflowForm.tsx

I worked on fixing the type error for pr #15297 changes.
#
#

fix: type errors for pr #15297

---

openmetadata-service/src/main/resources/json/data/app/SearchIndexingApplication.json
openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/SearchIndexingApplication.json
openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json

[Fix] Make Recreate Index Default as true

---

openmetadata-docs/content/v1.3.x/connectors/database/azuresql/index.md
openmetadata-docs/content/v1.3.x/connectors/database/clickhouse/index.md
openmetadata-docs/content/v1.3.x/connectors/database/couchbase/index.md
openmetadata-docs/content/v1.3.x/connectors/database/domo-database/yaml.md
openmetadata-docs/content/v1.3.x/connectors/database/druid/index.md
openmetadata-docs/content/v1.3.x/connectors/database/greenplum/yaml.md
openmetadata-docs/content/v1.3.x/connectors/database/impala/index.md
openmetadata-docs/content/v1.3.x/connectors/database/pinotdb/index.md
openmetadata-docs/content/v1.3.x/connectors/database/sqlite/yaml.md
openmetadata-docs/content/v1.3.x/connectors/database/unity-catalog/index.md
openmetadata-docs/content/v1.3.x/connectors/ingestion/lineage/index.md
openmetadata-docs/content/v1.3.x/connectors/metadata/atlas/yaml.md
openmetadata-docs/content/v1.3.x/connectors/pipeline/airbyte/index.md
openmetadata-docs/content/v1.3.x/connectors/pipeline/dagster/index.md
openmetadata-docs/content/v1.3.x/connectors/pipeline/databricks-pipeline/index.md
openmetadata-docs/content/v1.3.x/deployment/backup-restore-metadata.md
openmetadata-docs/content/v1.3.x/deployment/docker/index.md
openmetadata-docs/content/v1.3.x/deployment/upgrade/how-does-it-work.md
openmetadata-docs/content/v1.3.x/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.3.x/sdk/java/index.md
openmetadata-docs/content/v1.3.x/sdk/python/entities/ml-model.md

I worked on fixing the broken links and hash references for the v1.3.x content
#
#

Docs: Update the docs content to fix broken links

---

openmetadata-docs/content/v1.3.x/connectors/database/iceberg/index.md
openmetadata-docs/content/v1.3.x/connectors/metadata/amundsen/yaml.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/openmetadata.md
openmetadata-docs/content/v1.3.x/menu.md

MINOR: Fix some links on ingestion docs

---

docker/docker-compose-quickstart/Dockerfile

Minor: Fix dockerfile release version

---

openmetadata-spec/src/main/resources/json/schema/events/eventSubscription.json
openmetadata-ui/src/main/resources/ui/cypress/common/AlertUtils.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/NotificationAlerts.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/ObservabilityAlerts.spec.ts
openmetadata-ui/src/main/resources/ui/src/pages/LoginPage/SignInPage.tsx
openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx
openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/ObservabilityUtils.tsx

Fixes #15438 
I worked on the following:
#
#

Fix #15438: Update filters and destination for 'Conversation' source in notification alert

---

ingestion/src/metadata/utils/importer.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/15446
I worked on the import issue because I discovered the issue and was able to test locally
#
#

fix: get_connection import when using customDashboard

---

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/secrets/SecretsManagerUpdateService.java
openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

#15425 - Move SecretsManagerUpdateService to migrate command

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/QueryEntity.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/ClassificationVersionPage.spec.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Tags.spec.js

Fixes cypress tests related to description changes
#
#

fix description related cypress tests

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/AddIngestion/AddIngestion.component.tsx
openmetadata-ui/src/main/resources/ui/src/rest/metadataTypeAPI.ts
openmetadata-ui/src/main/resources/ui/src/utils/IngestionWorkflowUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/IngestionWorkflowUtils.ts

I worked on adding changes for filtering out the `FilterPatterns` if both `includes` and `excludes` are empty. 
[Ingestion changes](https://github.com/open-metadata/OpenMetadata/pull/15289/files#diff-e4de40023ad2e49484822051c6145f6231671d6fbd5d7414ab4633bf566357b3R57) 
#
#

Minor: filter out the filterPatterns if excludes and includes are empty

---

ingestion/src/metadata/examples/workflows/test_suite.yaml

I [asked for help in Slack](https://openmetadata.slack.com/archives/C02B6955S4S/p1709236547690259) #support channel regarding trying to deploy test cases by yaml files configuration because I was getting erros, even though I was using that yaml file example found in this repository. Teddy Crépineau helped me finding the correct yaml structure and suggested that I opened this PR to update the example also.
#
#

Fix: Update test suite workflow example in ingestion folder

---

openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java

Implement fix when retrieving data products entity reference
#
#
Bug fix

MINOR: fix entity reference look up for data products

---

openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/PoliciesDetailPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesDetailPage/RolesDetailPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesDetailPage/roles-detail.less

- Fixed alignment issue of description title
- Fixed alignment issue between title, description and tabs for roles and policy page
#
#

Minor: fixed ui layout issue of role page

---

openmetadata-docs/content/v1.3.x/connectors/pipeline/airflow/yaml.md

MINOR - Note on airflow docs

---

openmetadata-docs/content/v1.3.x/deployment/bare-metal/index.md
openmetadata-docs/content/v1.3.x/deployment/docker/index.md
openmetadata-docs/content/v1.3.x/deployment/kubernetes/aks.md
openmetadata-docs/content/v1.3.x/deployment/kubernetes/eks.md
openmetadata-docs/content/v1.3.x/deployment/kubernetes/gke.md
openmetadata-docs/content/v1.3.x/deployment/kubernetes/on-prem.md

Unify Prerequisites of Kubernetes Deployment Docs
#
#

fix(docs): Unify Prerequisites of Kubernetes Deployment Docs

---

openmetadata-service/src/main/java/org/openmetadata/service/events/ChangeEventHandler.java
openmetadata-service/src/main/java/org/openmetadata/service/security/MultiUrlJwkProvider.java

Fix #15503: Cache MultiJWKsProvider response

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppMarketPlaceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
openmetadata-spec/src/main/resources/json/schema/entity/applications/app.json
openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/appMarketPlaceDefinition.json
openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.json

Add the option for an app to be defined as a system app so it cannot be uninstalled.
#
#

MINOR: add the systemApp property

---

openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PolicyRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/policies/PolicyResource.java
openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/CompiledRule.java

Limit SPeL getValue to SimpleEvaluationContext

---

ingestion/src/metadata/profiler/source/databricks/profiler_source.py
ingestion/src/metadata/profiler/source/profiler_source_factory.py

Fixes #15436 
- Added `is_disconnect` method to Databricks SQA client
#
#

FIX  #15436 - Add disconnect method for databricks client

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/Severity/Severity.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummary.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerPage.tsx

Fixes #15507 
- Fixed Severity badge style issue in the profile page task tab
- Incident details page graph re-render issue
- fixed Date time filter was not working in incident manager details page
https://github.com/open-metadata/OpenMetadata/assets/71748675/9ba13273-60e5-4db0-aa68-9e79ee38bcd4
https://github.com/open-metadata/OpenMetadata/assets/71748675/c1b5cbe2-8996-431b-8c1b-5ceedfe360ea
#
#

#15507 Date filtering not working for Incident manager and ui feedbacks

---

ingestion/pipelines/sample_usage.yaml
ingestion/src/metadata/workflow/workflow_output_handler.py

Add stack trace while throwing an error to debug

---

ingestion/src/metadata/parsers/json_schema_parser.py
ingestion/tests/unit/test_json_schema_parser.py

Fix #15533: Fix name & display name for kafka json schema parser

---

openmetadata-docs/content/v1.3.x/connectors/database/postgres/yaml.md

MINOR: postgres add ssl options in yaml docs

---

openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.ts

Currently when creating a new task for a Glossary Term the owner information is not fetched.
This PR intends to fix this issue by also fetching the owner information
#
#

MINOR: Small change to fix the Glossary Term Tasks not fetching Owner 

---

ingestion/src/metadata/great_expectations/action.py

- Update GX module logger to respect logger hierarchy
#
#
Bug fix

[MINOR] GX logging hierarchy

---

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java

added OpenMetadataApplication.getDao

---

openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java

forbid modification of system app
#
#

MINOR: forbid modification of systemApp

---

ingestion/src/metadata/ingestion/api/topology_runner.py
ingestion/src/metadata/utils/source_hash.py

MINOR: Skip source hash generation for service

---

conf/openmetadata.yaml

WebAnalyticsHandler does not exist on the class path
it causes 
java.lang.ClassNotFoundException: org.openmetadata.service.events.WebAnalyticEventHandler
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:375)
at org.openmetadata.service.events.EventFilter.registerEventHandlers(EventFilter.java:54)
at org.openmetadata.service.events.EventFilter.<init>(EventFilter.java:44)
at org.openmetadata.service.OpenMetadataApplication.registerEventFilter(OpenMetadataApplication.java:475)
at …

[Fix] Remove WebAnalyticsHandler from yaml

---

openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx

Fixes 15358
I worked on adding bots to the options of the filters.
#
#
I couldn't find any tests that I had to modify.

Fixes #15358: add bots to the options of the filters.

---

openmetadata-ui/src/main/resources/ui/src/utils/i18next/i18nextUtil.ts

There is a typo in the language selection section of the UI. German is translated as "Deutsh",  but the correct translation is "Deutsch"
I have not written any tests, nor opened and issue since this is a trivial change. I do not seem to have the rights to open a bug report issue.
#
- [x ] Bug fix
#

fix: corrrect typo in language selection menu "Deutsh" -> "Deutsch"

---

openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/Alerts/AlertsUtil.tsx

I worked on the following:
https://github.com/open-metadata/OpenMetadata/assets/51777795/9cc2806d-d338-4da6-a3b1-ae3b11a168fa
#
#

Minor: Alert form user list suggestion fixes

---

ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
ingestion/src/metadata/ingestion/source/storage/s3/metadata.py
ingestion/src/metadata/ingestion/source/storage/s3/models.py
ingestion/tests/unit/topology/storage/test_storage.py
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/storages/ContainerResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/ContainerIndex.java
openmetadata-service/src/main/resources/elasticsearch/en/container_index_mapping.json
openmetadata-spec/src/main/resources/json/schema/api/data/createContainer.json
openmetadata-spec/src/main/resources/json/schema/entity/data/container.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
openmetadata-spec/src/main/resources/json/schema/type/entityLineage.json
openmetadata-ui/src/main/resources/ui/src/constants/Lineage.constants.ts

…owflake
Fix #11905: Automated lineage between external table and container snowflake
#
#

Fix #11905: Automated lineage between external table and container snowflake

---

ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py

MINOR: Fix multiline insert query stored procedure lineage
#
#

MINOR: Fix multiline insert query stored procedure lineage

---

ingestion/src/metadata/ingestion/models/patch_request.py
ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
ingestion/src/metadata/ingestion/sink/metadata_rest.py
ingestion/tests/integration/ometa/test_ometa_topology_patch.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/15563
#
#

Fix #15563: Fixed incorrect col ordering after patch request from ingestion

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/SchemaSearch.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/CustomizeLandingPage.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/ClassificationVersionPage.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsight.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.ts

I worked on fixing the invalid token issue in cypress tests.
#
#

Fix: cypress tests invalid token issue

---

ingestion/src/metadata/ingestion/source/dashboard/looker/utils.py

MINOR: Fix Looker clone repo failure for bitbucket
#
#

MINOR: Fix Looker clone repo failure for bitbucket

---

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/feeds/FeedResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/FeedResourceTest.java
openmetadata-spec/src/main/resources/json/schema/api/feed/createThread.json
openmetadata-spec/src/main/resources/json/schema/entity/feed/thread.json

Required for https://github.com/open-metadata/openmetadata-collate/pull/373
We're adding the `ai` property to the threads so that we can pass AI generated queries information when chatting with AI
#
#

MINOR - Prepare AI chat feed

---

ingestion/src/metadata/ingestion/lineage/parser.py
ingestion/src/metadata/ingestion/source/database/mssql/lineage.py
ingestion/src/metadata/ingestion/source/database/mssql/usage.py

To avoid errors on queries from where we can't expect necessary information (e.g., `CREATE FUNCTION`)
#
#

MINOR - Clean MSSQL lineage & usage

---

ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
ingestion/src/metadata/ingestion/source/database/databricks/queries.py
ingestion/src/metadata/ingestion/source/database/external_table_lineage_mixin.py
ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/ingestion/source/database/unitycatalog/metadata.py

MINOR: Add support for databricks external table lineage
#
#

MINOR: Add support for databricks external table lineage

---

ingestion/src/metadata/ingestion/lineage/parser.py

Fix #15118: Handle exception while processing usage comparisons

---

openmetadata-docs/content/v1.1.x/connectors/ingestion/great-expectations.md
openmetadata-docs/content/v1.1.x/developers/webhooks.md
openmetadata-docs/content/v1.2.x/connectors/ingestion/great-expectations.md
openmetadata-docs/content/v1.2.x/developers/webhooks.md
openmetadata-docs/content/v1.2.x/how-to-guides/data-insights/cost-analysis.md
openmetadata-docs/content/v1.3.x/connectors/ingestion/great-expectations.md
openmetadata-docs/content/v1.3.x/developers/webhooks.md
openmetadata-docs/content/v1.3.x/how-to-guides/data-insights/cost-analysis.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/ingestion/great-expectations.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/developers/webhooks.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/how-to-guides/data-insights/cost-analysis.md
openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts

I worked on fixing the broken link references in the documentation
#
#

Docs: Fix broken links in the documentation

---

openmetadata-docs/content/v1.3.x/deployment/security/saml/index.md

Fix SAML config indentation

---

ingestion/src/metadata/ingestion/source/dashboard/looker/utils.py

Fixes a typo in the Looker Bitbucket URL

[TYPO] Fix typo in Looker Bitbucket URL

---

ingestion/src/metadata/ingestion/source/dashboard/looker/utils.py

MINOR: Looker fix bitbucket protocol

---

ingestion/src/metadata/ingestion/source/pipeline/dagster/metadata.py

Fixed dagster tasks status
#
#

MINOR: Fixed dagster tasks status

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java

- Removed unused stats in entity stats
#
#

Fix Search Indexing Empty Stats

---

openmetadata-service/pom.xml
openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AppRouter.tsx
openmetadata-ui/src/main/resources/ui/src/components/AppRouter/UnAuthenticatedAppRouter.tsx
openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx
openmetadata-ui/src/main/resources/ui/src/hooks/useApplicationStore.ts
openmetadata-ui/src/main/resources/ui/src/interface/store.interface.ts
openmetadata-ui/src/main/resources/ui/src/rest/LoginAPI.ts
pom.xml

chore(ui): fix callback component not loading for okta issue

---

ingestion/src/metadata/utils/helpers.py
ingestion/tests/unit/test_helpers.py

Fixes #15544 
I worked on fixing histogram unit places issue with scientific notation (e)
#
#

Fixes 15544: Histogram not working for more than 15 units

---

openmetadata-ui/src/main/resources/ui/cypress/constants/constants.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/LoginConfiguration.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Service.spec.ts
openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx

Fixes #15296 
I worked on issue #15296 
https://github.com/open-metadata/OpenMetadata/assets/59080942/b6136685-f7e2-41b2-9572-0e0ed414d944
#
#

Fix(#15296): Issue with the same service name

---

openmetadata-ui/src/main/resources/ui/src/components/AppRouter/UnAuthenticatedAppRouter.tsx

I worked on Fixing: Login.spec.ts
#
#

fix(e2e): login spec fialure

---

ingestion/src/metadata/profiler/orm/converter/converter_registry.py
ingestion/src/metadata/profiler/orm/converter/redshift/converter.py
ingestion/src/metadata/profiler/orm/registry.py

Opening as result of https://github.com/open-metadata/OpenMetadata/issues/10171 (tho not really related...)
#
#

MINOR: add profiler support for Redshift GEOMETRY type

---

openmetadata-service/pom.xml

Remove Slf4j coming from pac4j creating multiple deps on class path
#
#

- Fix slf4j coming from pac4j

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java

Fix failing tests in Task Resolution

---

openmetadata-docs/content/v1.3.x/deployment/ingestion/external/gcs-composer.md
openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/AppException.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/NativeApplication.java
openmetadata-spec/src/main/resources/json/schema/configuration/appsPrivateConfiguration.json
openmetadata-spec/src/main/resources/json/schema/entity/applications/app.json

If we now specify on the openmetadata.yaml the `preview` parameter for an application:
```
applications:
appsPrivateConfiguration: # Defined as private configs
- name: DataInsightsApplication
preview: ${ENV_VAR:-false}
```
Then we won't allow that application to be initialized.
For example, this is what we'd see if we were to add this parameter to the Data Insights. This will help us keep the MetaPilot in the preview mode for 1.3.2 just by setting env vars.
**Note that each application can define its own exception. The one in the image is the default.**
#
#

MINOR - Application Preview

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SuggestionFilter.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SuggestionRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/feeds/SuggestionsResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/SuggestionsResourceTest.java

https://github.com/open-metadata/openmetadata-collate/issues/367
- Add accept/reject all to suggestions
- Add bot displayName (from App displayName)
Still need a solution for the logo cc @karanh37 
#
#

#367C - Suggestions Accept / Reject All 

---

ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
ingestion/src/metadata/pii/scanners/ner_scanner.py
ingestion/src/metadata/profiler/source/metadata.py
ingestion/src/metadata/workflow/base.py

Fixes #14943
- clean patch log to make it easier to identify the asset that fails
- clean NER tagging
- the profiler source (OM) now loads the tags if we are processing PII sensitive. This ensures that we do not re-tag an entity with existing PII tags. Speeds up the process a lot, since we don't do unnecessary processing.
- in the workflows, only load the ingestion pipeline if the FQN is informed cc @IceS2 
#
#

#14943 - Check tags before PII processor

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/resources/elasticsearch/en/dashboard_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/dashboard_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/dashboard_index_mapping.json

Fix #15501: Explore - Showcase Dashboard project and filter by it

---

openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightHeader/DataInsightHeader.component.tsx

Fixes #15545
I worked on hiding counts of the filter
#
#

#15545 Data Insights filter counter

---

openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/RetentionPeriod/RetentionPeriod.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/RetentionPeriod/RetentionPeriod.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/RetentionPeriod/RetentionPeriod.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.test.tsx

- Remove the edit button when table is soft deleted.
https://github.com/open-metadata/OpenMetadata/assets/66266464/d6222083-f139-4b7a-91f2-4da6deed2330
#
#

MINOR : remove retention period and displayName edit button if table is soft deleted

---

openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/UserPopOverCard.tsx
openmetadata-ui/src/main/resources/ui/src/hooks/user-profile/useUserProfile.ts
openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
openmetadata-ui/src/main/resources/ui/src/utils/UserDataUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/UserDataUtils.ts

Add floating button for tables pages - External functionality.
Show profile pic for bots.
#
#

Show profile pic for bots

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightReportApplication.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightSettings.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/SearchIndexApplication.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppLogsViewer/AppLogsViewer.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppLogsViewer/AppLogsViewer.test.tsx

- fix breaking issue in `DataInsightReportApplication` page after log button click
- supported cypress for DataInsightReportApplication.
- support cypress for `logs clickable action` in searchIndex and dataInsight application.
Issue : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/31e636ed-6c60-440a-bc6a-9d7a47e65b9a
Resolved : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/6e6074d9-04b8-4759-ac01-8eef60ebae22
#
#

fix breaking issue in data insight report page after log button click

---

openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/GenericAuthenticator.tsx
openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx
openmetadata-ui/src/main/resources/ui/src/utils/AuthProvider.util.ts

Fixes:
- RefreshToken API to hit a threshold of 25s for clientType confidential
- For clientType Public it will be 2 minute before expiry
Test cases:
- Tested refreshToken with clientType confidential
- Able to update token with refresh 3 times and not getting kicked out of session
#
#

fix(ui): auth refresh token for confidential client type

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AbstractOmAppJobListener.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-spec/src/main/resources/json/schema/entity/applications/appRunRecord.json
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppLogsViewer/AppLogsViewer.test.tsx

- Fix App Run Type
- Remove Init on App Start
- Migrate stats setup for SearchIndexing to execution
- Fix [#15496](https://github.com/open-metadata/OpenMetadata/issues/15496)
#
#

[Fix] Application Fixes,  Updated AppRunType and Removed Server App Inits

---

ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
ingestion/src/metadata/ingestion/source/database/external_table_lineage_mixin.py
ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/ingestion/source/database/unitycatalog/metadata.py

MINOR: Move external table lineage to post processing
#
#

MINOR: Move external table lineage to post processing

---

ingestion/src/metadata/profiler/processor/sample_data_handler.py

MINOR: Fix sample data upload - binary data error

---

openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsProvider/SuggestionsProvider.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsProvider/SuggestionsProvider.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsProvider/SuggestionsProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsSlider/SuggestionsSlider.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsSlider/SuggestionsSlider.tsx
openmetadata-ui/src/main/resources/ui/src/rest/suggestionsAPI.ts

Added UI support for Accept/Reject All actions
https://github.com/open-metadata/OpenMetadata/assets/33024356/828a7c1d-a888-4949-8e21-5967a42b103f
#
#

Accept/Reject All Suggestions

---

openmetadata-docs/content/v1.3.x/deployment/security/oidc/index.md

Added Documentation for Oidc
#
#

- Oidc Documentation

---

openmetadata-service/pom.xml
pom.xml

Fixes below security vulnerabilities :-
- https://snyk.io/vuln/SNYK-JAVA-COMNIMBUSDS-6247633
- https://security.snyk.io/vuln/SNYK-JAVA-COMMYSQL-6075938
#
#

[Vulnerabilities] Fixes Security Flagged Dependencies

---

openmetadata-ui/src/main/resources/ui/cypress/common/Services/BigQueryIngestionClass.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Services/PostgresIngestionClass.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Services/S3IngestionClass.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Permission.spec.ts

Fixed below cypress:
- S3 service cypress
- Permission cypress
#
#

Cypress: fixed s3 service and permission cypress

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SuggestionRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/SuggestionsResourceTest.java

In each `applySuggestion` we were re-fetching the Table entity, which erased any previous applied suggestions when doing an Accept All.
We're now keeping the state on a single entity and generalized which fields are necessary to be fetched for each entity.
#
#

MINOR - Fix suggestion accept all

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

Fixes: Update what's new content for 1.3.2
#
#

feat(ui): what's new details update for 1.3.2

---

ingestion/src/metadata/utils/credentials.py
ingestion/tests/unit/test_credentials.py
openmetadata-spec/src/main/resources/json/schema/security/credentials/gcpExternalAccount.json

Fixes Json Schema Issue on Bigquery
#
#

Fix External Account Json Schema Issue

---

ingestion/src/metadata/ingestion/source/database/datalake/metadata.py
ingestion/src/metadata/ingestion/source/storage/storage_service.py
ingestion/src/metadata/parsers/json_schema_parser.py
ingestion/src/metadata/readers/dataframe/json.py
ingestion/src/metadata/readers/dataframe/models.py
ingestion/src/metadata/utils/datalake/datalake_utils.py
ingestion/tests/unit/topology/database/test_datalake.py
ingestion/tests/unit/topology/storage/test_storage.py

Adds support for json schema parsing for datalake and s3
#
#

MINOR: Add support for json schema parsing for datalake & s3

---

openmetadata-service/src/main/resources/json/data/testConnections/metadata/alation.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/metadata/alationConnection.json

Updated Alation connector json schemas
#
#

MINOR: Updated Alation connector json schemas

---

openmetadata-service/src/main/resources/json/data/EntityObservabilityFilterDescriptor.json

[MINOR] Fix: Removed Schema Changes from TestCase and TestSuite

---

bootstrap/sql/migrations/native/1.3.2/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.3.2/postgres/schemaChanges.sql
bootstrap/sql/migrations/native/1.4.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.4.0/postgres/schemaChanges.sql

since we'll bring https://github.com/open-metadata/OpenMetadata/pull/15524 to 1.3.2
#
#

MINOR - Move app migrations to 1.3.2

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AbstractOmAppJobListener.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java

follows https://github.com/open-metadata/OpenMetadata/pull/15612
#
#

MINOR: use appName instead of id

---

ingestion/src/metadata/ingestion/source/database/external_table_lineage_mixin.py

Fixes the below error
for entity_request in node_post_process():
TypeError: yield_external_table_lineage() missing 1 required positional argument: '_'
as the method it is an abstract of has that arg:
def yield_external_table_lineage(self, _) -> Iterable[Either[AddLineageRequest]]:
"""
Process external table lineage
"""
#
#

Minor: Fix TypeError Missing arg

---

.github/workflows/cypress-integration-tests-mysql-pr.yml

- We will be running specs as per PR changes so if there were no filter applier by default it will run all the spec
- To avoid much consumption unnecessary will limit cypress run for PRs for UI folder only
- Other changes are expecting to be catch as nightly runs 
#
#

chore(e2e): run cypress workflow for ui/* folder only 

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java
openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightDescriptionAndOwnerTemplate.java
openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/template/DataInsightTotalAssetTemplate.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/resources/emailTemplates/dataInsightReport.ftl

Fixes #15686 : Updated Data Insights Report Schema

---

openmetadata-ui/src/main/resources/ui/cypress/common/Entities/EntityClass.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Glossary.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Owner.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/Alert.constant.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/ObservabilityAlerts.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/GlossaryVersionPage.spec.ts

Fixed cypress tests for Services, ObservabilityAlerts and Glossary VersionPage specs
#
#

Minor: AUT Cypress fixes for failing tests

---

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/RelatedTerms.tsx
openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx

Fixes: #15672
- If we do not change anything on terms it's not able to pick those terms which are present
- In the loop we are expecting terms to be as option object but for initial values it will be string[]
- Hence comparing it like, If it's string we directly expecting it to be term name else obj.value
https://github.com/open-metadata/OpenMetadata/assets/12962843/1371b63a-a3e6-49d9-a94b-3f5d2f98a380
#
#

fix(ui): Glossary term related term got vanish on update

---

ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py

Fix #14285: Add column lineage support for tableau datamodels
#
#

Fix #14285: Add column lineage support for tableau datamodels

---

ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/src/metadata/ingestion/source/database/external_table_lineage_mixin.py

MINOR: Fix external table lineage processing

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AbstractOmAppJobListener.java
openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/util/TestUtils.java

Added a test that triggers the indexing app. Before the fix the test fails:
```java
org.apache.http.client.HttpResponseException: status code: 500, reason phrase: An exception with message [No Available Application Run Records.] was thrown while processing request.
at org.openmetadata.service.util.TestUtils.readResponseError(TestUtils.java:221)
at org.openmetadata.service.util.TestUtils.readResponse(TestUtils.java:235)
at org.openmetadata.service.util.TestUtils.get(TestUtils.java:361)
at org.openmetadata.service.resources.apps.AppsResourceTest.getLatestAppRun(AppsResourceTest.java:142)
at org.openmetadata.service.resources.apps.AppsResourceTest.post_trigger_app_200(AppsResourceTest.java:86)
...
```
#
#

CRITICAL: fix AbstractOmAppJobListener

---

ingestion/src/metadata/ingestion/source/dashboard/metabase/client.py
ingestion/src/metadata/ingestion/source/dashboard/metabase/connection.py
ingestion/src/metadata/ingestion/source/dashboard/metabase/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/metabase/models.py

Fix #15678: Accomodate Metabase API changes
#
#

Fix #15678: Accomodate Metabase API changes

---

openmetadata-ui/src/main/resources/ui/src/components/common/DatePickerMenu/DatePickerMenu.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DatePickerMenu/DatePickerMenu.test.tsx

Fixes #15650
- reverted default value changes, keeping old Behaviour the same in the profiler
- Allow users to select start and end date whenever users open the custom date picker
https://github.com/open-metadata/OpenMetadata/assets/71748675/04bf192c-f457-491a-9365-b8e60920fe9b
#
#

#15650 UI: Not able to select all possible dates range from the custom date picker in the incident manager

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java

This operation matches the [migration here](https://github.com/open-metadata/OpenMetadata/blob/84941a7d32d1d9c630f267b3e4fbdc19279dfbc8/bootstrap/sql/migrations/native/1.3.2/mysql/schemaChanges.sql#L4)
`QRTZ_JOB_DETAILS.JOB_DATA` holds serialized java bytecode. There is no elegant way of manipulating it with SQL. This is the reason we are moving all job context away from quartz.
example payload:
```
¬í  sr  org.quartz.JobDataMap ° è¿©°Ë   xr &org.quartz.utils.StringKeyDirtyFlagMap  èÃûÅ](   Z  allowsTransientDataxr  org.quartz.utils.DirtyFlagMap æ.­(v Î   Z  dirtyL  mapt  Ljava/util/Map;xp sr  java.util.HashMap  ÚÁÃ `Ñ   F  loadFactorI  thresholdxp?@      w         t  applicationInfoKeyt  {"id":"5edfa809-681b-4141-a55b-0ecbb2b36cef","name":"DataInsightsReportApplicatio …
```

MINOR: added handling for new schedule when migrating quartz context

---

ingestion/src/metadata/ingestion/ometa/routes.py
ingestion/tests/integration/ometa/test_ometa_app_api.py
openmetadata-docs/content/partials/v1.3/connectors/metadata/connectors-list.md
openmetadata-docs/content/partials/v1.4/connectors/metadata/connectors-list.md
openmetadata-spec/src/main/resources/json/schema/entity/applications/createAppRequest.json
openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.json
scripts/datamodel_generation.py

- Update some titles in the JSON Schemas to follow the same convention
- Add `App` routes in the ometa client
- The App generated model is missing an import. Opened an issue https://github.com/koxudaxi/datamodel-code-generator/issues/1895
- For now, patching the generate script to let us move on using the App model
Required for https://github.com/open-metadata/openmetadata-collate/pull/407
#
#

MINOR - App routes & datamodel

---

openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/DataModelDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/ParameterForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/CustomMetricForm/CustomMetricForm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ProfilerSettingsModal/ProfilerSettingsModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/SchemaEditor.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/SchemaEditor.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/SchemaEditor.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/schema-editor.less
openmetadata-ui/src/main/resources/ui/src/components/Database/TableQueries/QueryCard.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/StoredProcedureSummary/StoredProcedureSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/ModalWithQueryEditor/ModalWithQueryEditor.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.tsx
openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedurePage.tsx

Fixes [#15561](https://github.com/open-metadata/OpenMetadata/issues/15561)
- supported `copy button in query editor` and also direct copy from the editor
- also supported copy from the editor for `storedProcedure` and `dashboardDataModel` in the `sql and code tab`.
https://github.com/open-metadata/OpenMetadata/assets/66266464/e04bffaa-e0ba-4a42-954b-3150039a797c
#
#

#15561: supported copy button in query editor

---

openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx

Fixes:
- Fix missing dataProduct params for below entities
https://github.com/open-metadata/OpenMetadata/assets/12962843/9013ebdc-5377-43cb-a215-f32901d615d5
#
#

fix(ui): data product wans't shown for few entities

---

openmetadata-docs/content/v1.3.x/connectors/metadata/alation/index.md
openmetadata-docs/content/v1.3.x/connectors/metadata/alation/yaml.md

Updated Alation Documentation for:
1. Knowledge Articles
2. Domains/subdomains
3. users and groups
4. BI/dashboard data
5. Database connection for extra metadata
#
#

MINOR: Alation documentation update

---

openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/metaPilotAppConfig.json

MINOR - MetaPilot updated conf

---

ingestion/src/metadata/ingestion/source/dashboard/superset/metadata.py

MINOR: Fixed superset class init

---

ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py

Fixed dbt cloud raise exception condition
#
#

MINOR: Fixed dbt cloud raise exception condition

---

ingestion/src/metadata/ingestion/source/database/oracle/connection.py
ingestion/src/metadata/ingestion/source/database/oracle/queries.py
openmetadata-docs/content/v1.1.x/connectors/database/oracle/index.md
openmetadata-docs/content/v1.1.x/connectors/database/oracle/yaml.md
openmetadata-docs/content/v1.2.x/connectors/database/oracle/index.md
openmetadata-docs/content/v1.2.x/connectors/database/oracle/yaml.md
openmetadata-docs/content/v1.3.x/connectors/database/oracle/index.md
openmetadata-docs/content/v1.3.x/connectors/database/oracle/yaml.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/oracle/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/oracle/yaml.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Oracle.md
openmetadata-ui/src/main/resources/ui/public/locales/fr-FR/Database/Oracle.md

Fixes Oracle Test Connection bug and check access to DBA Table
#
#

MINOR: Check Test Connection Oracle DBA Access

---

bootstrap/sql/migrations/native/1.3.2/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.3.2/postgres/schemaChanges.sql
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppMarketPlaceResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
openmetadata-spec/src/main/resources/json/schema/entity/applications/app.json
openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/appMarketPlaceDefinition.json
openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.json

MINOR: change systemApp to system

---

openmetadata-service/src/main/java/org/openmetadata/service/security/AuthCallbackServlet.java
openmetadata-service/src/main/java/org/openmetadata/service/security/AuthLoginServlet.java
openmetadata-service/src/main/java/org/openmetadata/service/security/AuthRefreshServlet.java

- Added more logs for context
#
#

- add Step logs for Auth

---

openmetadata-service/pom.xml

Fixes affected Vulnerabilities
#
#

[Vulnerabilities] Update Dependencies to fix Vulnerabilities

---

openmetadata-service/src/main/java/org/openmetadata/service/security/AuthLoginServlet.java

- Change Prompt to consent on every login

---

openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java

Fixes #15780
- Remove Domain Validation for Bots
#
#

[Fix] Do not validate bot domain

---

ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/models.py
ingestion/src/metadata/ingestion/source/dashboard/superset/queries.py
ingestion/tests/unit/resources/datasets/superset_dataset.json
ingestion/tests/unit/topology/dashboard/test_superset.py
openmetadata-docs/content/v1.3.x/connectors/dashboard/superset/yaml.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/dashboard/superset/yaml.md

FIX #13553 Added option to exclude drafts: superset ingestion

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Login.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx

Login cypress fixes

---

openmetadata-ui/src/main/resources/ui/src/components/SearchedData/SearchedData.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/SearchedData/SearchedData.tsx

Fixes #15301 
Before
After
#
#

fix matches description

---

openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/EmailMessageDecorator.java
openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/FeedMessageDecorator.java
openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/GChatMessageDecorator.java
openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MSTeamsMessageDecorator.java
openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java
openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/SlackMessageDecorator.java
openmetadata-service/src/main/resources/json/data/eventsubscription/ActivityFeedEvents.json

- Adds Redirection Link to Assets on conversations
- Update Redirection as suggested
#
#

[AlertNotication] Fix formatting

---

openmetadata-spec/src/main/java/org/openmetadata/sdk/PipelineServiceClient.java
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppDetails/AppDetails.interface.ts
openmetadata-ui/src/main/resources/ui/src/pages/LogsViewer/LogsViewer.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/LogsViewer/LogsViewer.interfaces.ts

To load app logs from the UI
#
#

MINOR - Add Application type for logs

---

ingestion/src/metadata/ingestion/source/database/sample_data.py

Fixes issue with SampleData
#
#

MINOR: Fix OMetaLifeCycleData call

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/QueryEntity.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsight.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightSettings.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.ts

Fixed below specs:
- DataQualityAndProfiler
- QueryEntity
- DataInsightSettings
- DataInsight
#
#

cypress: fixed AUT failure of main branch

---

openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java

Validate against PersonalAccess

---

ingestion/tests/cli_e2e/dashboard/tableau/tableau.yaml
ingestion/tests/cli_e2e/test_cli_tableau.py

[MINOR] Fix tableau e2e

---

CONTRIBUTING.md

fix: good-first-issue link

---

openmetadata-docs/content/v1.3.x/connectors/database/mssql/index.md
openmetadata-docs/content/v1.3.x/connectors/database/mssql/yaml.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/mssql/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/mssql/yaml.md

To add the missing `ingestAllDatabases` flag
#
#

DOCS - MSSQL service connection
