openmetadata-ui/src/main/resources/ui/src/components/Modals/ModalWithMarkdownEditor/ModalWithMarkdownEditor.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx

Fixes:
- Set autoFocus for DescriptionEditor Modal
- Allow have more options for Service page
#
#

chore(ui): support extra dropdown items for service details page

---

openmetadata-docs/content/v1.4.x-SNAPSHOT/developers/how-to-add-language-support.md

Update documentation for adding language support for entities

---

openmetadata-docs/content/v1.3.x/developers/how-to-add-language-support.md

Update documentation for adding language support for entities for 1.3.x

---

ingestion/tests/unit/test_entity_link.py
openmetadata-spec/src/main/antlr4/org/openmetadata/schema/EntityLink.g4

Fixes error in creation of entitylink
#
#

MINOR: Fix Entity Link Error

---

bootstrap/sql/migrations/native/1.3.3/postgres/schemaChanges.sql

Fix Migration SQL , not executing from Handle

---

bootstrap/sql/migrations/native/1.4.0/mysql/schemaChanges.sql

MINOR - delete mysql ES pipelines

---

ingestion/src/metadata/profiler/interface/pandas/profiler_interface.py
ingestion/src/metadata/profiler/interface/sqlalchemy/profiler_interface.py
ingestion/src/metadata/profiler/orm/functions/table_metric_computer.py

- fix bigquery row computation for view
- fix mySQL row count for Innodb engine
#
#
Bug fix

Minor fix row computation for views

---

ingestion/src/metadata/ingestion/ometa/mixins/tests_mixin.py

MINOR: fixed typo for failed samples field

---

ingestion/examples/sample_data/tests/testCaseResults.json
ingestion/examples/sample_data/tests/testSuites.json
ingestion/src/metadata/ingestion/source/database/sample_data.py

MINOR: fixed ingestion of sample data for failed sample rows

---

ingestion/setup.py

MINOR: Add Databricks ssl dependencies

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/AddDataQualityTest.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/TestSuiteIngestion.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/TestSuiteScheduler.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/TestSuiteScheduler.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppSchedule/AppSchedule.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/AppInstall/AppInstall.component.tsx

This PR introduces functionality to activate debug logging within the test suite ingestion pipeline.
This PR includes the following changes:
- Implementation of debug log functionality in both add and edit modes for the test suite pipeline.
- Unit testing for the newly added feature.
#
#

Minor: added functionality to enable debug log for test suite ingestion

---

ingestion/src/metadata/ingestion/source/database/databricks/metadata.py

MINOR: Fix databricks connector

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/CustomProperty.ts

I worked on fixing the cypress tests of the custom property table that we show on the right panel.
#
#

fix custom property cypress test

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/SearchIndexApplication.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/SelectWidget.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/SelectWidget.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/FormBuilder/FormBuilder.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/SelectWidget.mock.ts
openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
openmetadata-ui/src/main/resources/ui/src/styles/variables.less

Fixes #15825
- I worked on fixing search index language configuration not saving.
https://github.com/open-metadata/OpenMetadata/assets/66266464/372bf00b-27ed-439f-a924-8a437e4c6d99
https://github.com/open-metadata/OpenMetadata/assets/66266464/771a54c8-1f85-4ed7-8376-014dd1b4eca9
#
#

MINOR: fix search index language configuration not saving

---

bootstrap/sql/migrations/native/1.3.2/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.3.2/postgres/schemaChanges.sql

Remove SQls from 1.3.2

---

openmetadata-docs/content/partials/v1.3/releases/latest.md
openmetadata-docs/content/v1.3.x/releases/releases/index.md

Add Documentation for 1.3.2 release
#
#

Add/Modify Release notes for 1.3.2

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
openmetadata-spec/src/main/resources/json/schema/entity/policies/accessControl/resourceDescriptor.json

https://github.com/open-metadata/openmetadata-collate/issues/388
#
#

MINOR: added a DELETE method for failedRowsSample

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/IngestionPipelineIndex.java

Fixes [#15886](https://github.com/open-metadata/OpenMetadata/issues/15886)
- Adds Pipeline status to the ingestion_pipeline_status to ES
#
#

Add Pipeline Status to Ingestion Pipeline Index

---

README.md

MINOR: Fix error link

---

ingestion/src/metadata/ingestion/source/database/sample_data.py

MINOR: Fix Glue Sample Data

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/MarketPlaceAppDetails/MarketPlaceAppDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/MarketPlaceAppDetails/MarketPlaceAppDetails.test.tsx

Show preview alert only for preview apps
#
#

Show preview alert only for preview apps

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/MarketPlaceAppDetails/MarketPlaceAppDetails.component.tsx

application tooltip fix

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersProfile/UserProfileDetails/UserProfileDetails.test.tsx

fix(ui): hide email if not present in the data

---

ingestion/src/metadata/profiler/orm/functions/table_metric_computer.py

Fixes #15909
Modifying to DBA_ table instead of ALL_ to standardize fetching of metadata on the metadata ingestion as well as 
profiler side
#
#

Fixes #15909: Profiler: Fix All_ table to DBA_

---

ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
ingestion/src/metadata/ingestion/source/dashboard/qlikcloud/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/qliksense/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py

Fix #9281: Column level lineage for other entities
I worked on Column level lineage for Superset, QlikCloud, QlikSense
#
#

Fix #9281: Column level lineage for other entities

---

ingestion/src/metadata/ingestion/source/database/sample_data.py

MINOR: Fix sample data CI error

---

bootstrap/sql/migrations/native/1.3.3/mysql/schemaChanges.sql
openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v133/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v133/Migration.java

Move migration for apps to 1.3.3 all together

---

ingestion/README.md

aligning with pyproject.toml
https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/pyproject.toml#L16
#
#

MINOR: Update README.md python version

---

.github/workflows/validate-jsons-yamls.yml
scripts/validate_json_yaml.sh

Fix directory exclusion and pipeline stage names in json/yaml validations.
#
#

fixed exclusion for yaml/json validation

---

openmetadata-clients/openmetadata-java-client/pom.xml

Fixes Vulnerable coming from nimble-jose-jwt
#
#

[Vulnerability] Fix Vulnerable Dependency in -java-client

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java

Change init() so that individual app failure, still allows other apps to be registered
#
#

[MINOR] Fix Default App Init

---

openmetadata-docs/content/partials/v1.3/releases/latest.md
openmetadata-docs/content/v1.3.x/releases/releases/index.md

MINOR - 1.3.3 release docs

---

openmetadata-docs/content/v1.3.x/sdk/go/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/sdk/go/index.md

Minor: Doc Fix GO SDK repo link

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

Fix issue in search with hierarchy for glossary terms
- In certain cases , when we were trying to get the nested children tag directly, sometimes the hierarchy would not show correctly, this PR fixes the issue
#
#

Fix issue in search with hierarchy for glossary terms

---

openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/topics/TopicResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/util/RetryableAssertionError.java
openmetadata-service/src/test/java/org/openmetadata/service/util/TestUtils.java

Use a polling mechanism for tests that assert changes in Elasticsearch. This will have 2 benefits:
1. We expect less cases of false positives for tests that rely on data being reflected in ElasticSearch.
2. Performance! Here is an example of a test case that is running at 1.9s instead of 3s. This specific test case is inherited by about 30 other classes... Aggregating all the cases where we use the `waitForEsAsyncOp` method might reduce the tests runtime by a significant amount.
#
#

MINOR: use polling mechanism for bnackend tests

---

.github/workflows/py-tests.yml

fixed `environemnt` to `env`.
#
#

MINOR: fix pytest githab action

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

fix- Allow Lineage for stored Procedure

---

openmetadata-ui/src/main/resources/ui/cypress/common/Entities/EntityClass.ts

test(e2e): export basic details from EntityClass.ts

---

ingestion/src/metadata/ingestion/source/mlmodel/sagemaker/metadata.py
ingestion/tests/unit/topology/mlmodel/test_sagemaker.py

Fixes #13209
Small change on the code to pick up also the Model Storage.
#
#

FIXES 13209: Add Sagemaker Model Storage

---

ingestion/src/metadata/ingestion/source/database/hive/metadata.py
ingestion/src/metadata/ingestion/source/database/presto/metadata.py
ingestion/src/metadata/ingestion/source/database/saphana/metadata.py
ingestion/tests/integration/profiler/conftest.py

Fixes inspector for Presto, Hive and SapHana
I worked on fixing setting inspector attribute error
#
#

Minor: Fixes SQLalchemy Inspector

---

ingestion/pyproject.toml
ingestion/src/metadata/profiler/processor/core.py

delete it again after it was brought back my mistake 👻 
#
#

MINOR: delete ingestion/src/metadata/__init__.py

---

ingestion/src/metadata/profiler/source/base/profiler_source.py

Fixes Import error on sample data
#
#

Minor: Fix Import error

---

openmetadata-docs/content/v1.3.x/deployment/secrets-manager/supported-implementations/azure-key-vault/index.md

[Fixes 15839](https://github.com/open-metadata/OpenMetadata/issues/15839)
It is possible to use Azure Key Vault as Secrets Manager but the docs needed few more pointers. If you don't want to add this all boring stuff about Manged Identities then the updates YAML snippets should be enough. 
#
#

Fixes 15839: More accurate documentation about setting up Secret Manager in Azure

---

openmetadata-docs/content/v1.3.x/deployment/kubernetes/values.md
openmetadata-docs/content/v1.3.x/deployment/secrets-manager/supported-implementations/azure-key-vault/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/deployment/kubernetes/values.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/deployment/secrets-manager/supported-implementations/azure-key-vault/index.md

Updated Docs for 1.3.X and 1.4.X
#
#

chore(docs): Update Helm Values; Azure Key Vault Docs for 1.4.X

---

ingestion/setup.py
ingestion/src/metadata/data_quality/validations/column/base/columnValuesMissingCount.py
ingestion/src/metadata/profiler/metrics/registry.py
ingestion/src/metadata/profiler/metrics/static/null_missing_count.py
ingestion/src/metadata/profiler/source/base/profiler_source.py
ingestion/tests/unit/test_suite/conftest.py
ingestion/tests/unit/test_suite/test_validations_databases.py

Fixes #14812 
Add support for empty string as missing count
#
#

Issue #14812: Add support for empty string as missing count

---

openmetadata-spec/src/main/resources/json/schema/entity/services/connections/metadata/alationConnection.json

Added None option to db config in Alation
#
#

MINOR: Added None option to db config in Alation

---

ingestion/tests/integration/ometa/test_ometa_tags_mixin.py
ingestion/tests/unit/topology/test_context.py
openmetadata-service/src/test/java/org/openmetadata/service/resources/tags/ClassificationResourceTest.java
openmetadata-spec/src/main/resources/json/schema/api/classification/createClassification.json
openmetadata-spec/src/main/resources/json/schema/api/classification/createTag.json
openmetadata-spec/src/main/resources/json/schema/entity/classification/classification.json
openmetadata-spec/src/main/resources/json/schema/entity/classification/tag.json
openmetadata-spec/src/main/resources/json/schema/entity/policies/filters.json

Fixes #15732 
I worked on referencing pattern of entityName to tag
#
#

Fixes #15732: Modify Reference for Tags to EntityName

---

ingestion/src/metadata/ingestion/source/database/oracle/connection.py
ingestion/src/metadata/ingestion/source/database/oracle/queries.py
ingestion/src/metadata/ingestion/source/database/oracle/utils.py
ingestion/src/metadata/profiler/orm/functions/table_metric_computer.py
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Oracle.md

Fixes #15977 revert DBA_ to ALL_
#
#

Fixes #15977: Revert from DBA_ to ALL_

---

openmetadata-docs/content/v1.4.x-SNAPSHOT/deployment/upgrade/versions/130-to-140.md

doc: added classifier config breaking change

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ColumnUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java

MINOR: Add support for search index column lineage

---

ingestion/src/metadata/ingestion/models/custom_properties.py
ingestion/tests/integration/ometa/test_ometa_custom_properties_api.py

Added enum type support in custom properties python sdk
#
#

MINOR: Added enum type support in custom properties python sdk

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/lineage/LineageResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/resources/json/data/lineage/lineageCsvDocumentation.json

Fix #12502: Add support for lineage export

---

openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java

Fixes UserResource CI
Error was introduced in https://github.com/open-metadata/OpenMetadata/pull/15983
I believe that changed uncovered a weird test that tried to create a user without being an admin.
#
#

FIX - UserResource CI

---

ingestion/ingestion_dependency.sh
ingestion/src/metadata/profiler/source/base/profiler_source.py

Otherwise ingestion only works when running via compose and not direct `docker run` unless passing explicitly the backend auth requirements. Those should be handled with safe defaults of what we need
#
#

MINOR - Add default to ingestion dependency sh

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java

MINOR - Migration validation list diff message

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/IncidentManager.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/IncidentManagerPageHeader/IncidentManagerPageHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseStatus/TestCaseIncidentManagerStatus.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseStatus/TestCaseIncidentManagerStatus.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCaseStatusModal/TestCaseStatusModal.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCaseStatusModal/test-case-status-modal.style.less
openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerPage.tsx

Fixes #15260
I have updated assignee select list with owner/team select popup
#
#

#15260 UI: consistent user/team for assignee in incident manager

---

.github/workflows/maven-build.yml
.github/workflows/maven-postgres-tests-build.yml

retry tests up to 3 times in main branch. this is in order to reduce false positives after pushing to main. handle exists like this:
Next step would be to let the `mvn` command return 0 even when tests fail (not on error).
#
#

MINOR: ci: retries

---

.github/workflows/maven-build.yml

MINOR: fix maven CI with retry

---

openmetadata-docs/content/v1.3.x/developers/contribute/build-code-and-run-tests/ingestion-framework.md
openmetadata-docs/content/v1.3.x/how-to-guides/data-lineage/workflow.md

Docs: Fixed 404 links

---

openmetadata-spec/src/main/java/org/openmetadata/schema/EntityInterface.java

[MINOR] Fix displayName

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Bots.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/Settings/Bot/BotListV1/BotListV1.component.tsx

- fix bot cypress
- Glossary cypress issue have been skipped and issue ticket for the same -> https://github.com/open-metadata/OpenMetadata/issues/15809
#
#

cypress: fix cypress issues

---

openmetadata-ui/src/main/resources/ui/src/mocks/Teams.mock.ts
openmetadata-ui/src/main/resources/ui/src/utils/TeamUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/TeamUtils.ts

Fixes #12981
- I worked on fixing the miss ordering of teams due to displayName
https://github.com/open-metadata/OpenMetadata/assets/66266464/6b5a6435-e54f-4abb-839e-2ce17b7af67b
#
#

#12981: fix the miss ordering of teams

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AbstractOmAppJobListener.java
openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

- fix Reindex status in Operations

---

ingestion/tests/unit/resources/datasets/superset_dataset.json
ingestion/tests/unit/topology/dashboard/test_superset.py

Fixes #15719
I worked on unit test improvments to increase test coverage
#
#

Fix #15719: Improve unit test to increase coverage.

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ClassificationRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java

- Do not update mutuallyExclusive (#15377 first)
- Do not update the tags if original and updated are equal (#15377 second , decription update invokes updateTags flow) 
#
#

[GlossaryTerm] Fix Glossary Term Issue

---

ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
ingestion/src/metadata/ingestion/source/database/snowflake/utils.py
openmetadata-spec/src/main/resources/json/schema/entity/data/table.json

Fix #16064: Add support for dynamic table type
#
#

Fix #16064: Add support for dynamic table type

---

ingestion/src/metadata/ingestion/source/database/datalake/connection.py

Fixes GCS Datalake client throwing arg error
#
#

Minor: Fix DataLake Client

---

openmetadata-docs/content/v1.3.x/deployment/docker/index.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/external/gcs-composer.md
openmetadata-docs/content/v1.3.x/deployment/ingestion/external/mwaa.md
openmetadata-docs/content/v1.3.x/deployment/kubernetes/faqs.md
openmetadata-docs/content/v1.3.x/deployment/upgrade/kubernetes.md
openmetadata-docs/content/v1.3.x/quick-start/local-docker-deployment.md

Fixing and updating docs with links and new release 1.3.1
#
#

Minor: Updated docs to 1.3.3

---

.github/workflows/maven-build.yml
.github/workflows/maven-postgres-tests-build.yml

Revert mvn retries and re-enable postgres mvn test

Minor revert mvn retry

---

ingestion/src/metadata/ingestion/source/messaging/common_broker_source.py
ingestion/src/metadata/utils/messaging_utils.py
ingestion/tests/unit/resources/protobuf_parser/address.proto
ingestion/tests/unit/resources/protobuf_parser/company.proto
ingestion/tests/unit/resources/protobuf_parser/contact.proto
ingestion/tests/unit/resources/protobuf_parser/department.proto
ingestion/tests/unit/resources/protobuf_parser/employee.proto
ingestion/tests/unit/resources/protobuf_parser/team.proto
ingestion/tests/unit/test_protobuf_parser.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/15454
#
#

Fix #15454: Added protobuf parser complex schema support

---

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityInfoDrawer/EdgeInfoDrawer.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomEdge.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Lineage/Lineage.interface.ts
openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.interface.tsx
openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx

get pipeline status from elastic search

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java

fix issue in directChildrenOf api for postgresql
#
#

fix issue in directChildrenOf api for postgresql

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/SearchIndexApplication.spec.ts

add cypress for search index app

---

openmetadata-docs/content/partials/v1.4/connectors/yaml/dashboard/source-config.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/dashboard/tableau/yaml.md

MINOR: Remove overrideOwner attribute that isn't there anymore

---

ingestion/tests/cli_e2e/test_cli_powerbi.py

Updated powerbi e2e counts
#
#

MINOR: Updated powerbi e2e counts

---

openmetadata-docs/content/v1.3.x/connectors/database/mssql/index.md
openmetadata-docs/content/v1.3.x/connectors/database/mssql/yaml.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/mssql/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/mssql/yaml.md

MINOR: Mark SISS packages as unsupported docs

---

openmetadata-ui/src/main/resources/ui/cypress/common/Entities/ServiceBaseClass.ts
openmetadata-ui/src/main/resources/ui/cypress/common/common.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/constants.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/GlossaryVersionPage.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Login.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/ProfilerConfigurationPage.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Teams.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Users.spec.ts

cypress: fixed cypress AUT part 3

---

ingestion/src/metadata/ingestion/ometa/mixins/patch_mixin.py
ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
ingestion/src/metadata/utils/tag_utils.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/16091
Fixed issue where column wasn't recognised from dbt if the case in manifest/catalog does not match.
Fixed picking up column descriptions from catalog file if present instead of manifest file.
#
#

Fix #16091: Fixed case issue in dbt

---

ingestion/src/metadata/ingestion/source/database/trino/connection.py
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/trino/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/trino/yaml.md
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/trinoConnection.json
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Trino.md

Fix #14130: Add support for azure auth in trino
#
#

Fix #14130: Add support for azure auth in trino

---

openmetadata-docs/content/v1.2.x/how-to-guides/user-guide-data-users/browser-ext.md
openmetadata-docs/content/v1.3.x/how-to-guides/user-guide-data-users/browser-ext.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/how-to-guides/user-guide-data-users/browser-ext.md

Add extension redirect url information in docs

---

ingestion/src/metadata/utils/elasticsearch.py

MINOR - Add missing ES mappings

---

ingestion/src/metadata/ingestion/source/storage/s3/connection.py
ingestion/src/metadata/ingestion/source/storage/s3/metadata.py
ingestion/src/metadata/ingestion/source/storage/s3/models.py
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/storage/s3/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/storage/s3/yaml.md
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/storage/s3Connection.json
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Storage/S3.md

MINOR: S3 Add support for single bucket ingestion

---

.github/workflows/java-checkstyle.yml
.github/workflows/maven-build-skip.yml
.github/workflows/maven-build.yml
.github/workflows/maven-postgres-tests-build-skip.yml
.github/workflows/maven-postgres-tests-build.yml
.github/workflows/maven-sonar-build.yml
.github/workflows/py-checkstyle.yml

For UI specific changes skipping below workflows
#
#

CI: update maven ci to be skipped for ui directory

---

openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java

fix: test suite resource test

---

openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts

Remove alation and kafkaconnect icons from oss service page.
#
#

MINOR: remove alation and kafkaconnect from oss service page

---

ingestion/src/metadata/ingestion/models/custom_properties.py
ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py
ingestion/tests/integration/ometa/test_ometa_custom_properties_api.py

Added custom property EntityReference support to python sdk
#
#

MINOR: Added custom property EntityReference support to python sdk

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/AddDataQualityTestV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuiteList/TestSuites.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ColumnProfileTable/ColumnProfileTable.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/QualityTab/QualityTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/TableProfiler.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/TableProfilerProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTab/SchemaTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTab/SchemaTab.interfaces.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomNode.utils.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/NodeChildren/NodeChildren.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/TestSuiteSummaryWidget/TestSuiteSummaryWidget.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/mocks/TableSummary.mock.ts
openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx

#16129
Fixed UI dependency of testSuite on table entity object,
#
#

Minor: fixed testSuite dependency on table entity object

---

ingestion/src/metadata/ingestion/source/storage/s3/connection.py

MINOR: improve s3 test connection

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v110/MigrationUtil.java

FIX - try-catch test suite migrations

---

ingestion/src/metadata/__version__.py
ingestion/src/metadata/ingestion/ometa/mixins/server_mixin.py
ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
ingestion/tests/unit/test_version.py
openmetadata-docs/content/v1.3.x/deployment/ingestion/openmetadata.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/deployment/ingestion/openmetadata.md

We now only validate major and minor versions between Server and Client
#
#

MINOR - Version match logic update & Airflow docs

---

openmetadata-ui/src/main/resources/ui/src/constants/Services.constant.ts

Moving SSL Config under Advanced Config
Fixes #16164
#
#

MINOR: Add SSL config in advanced config

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java

MINOR: Fix column lineage in export

---

openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetAsyncSelectList/DataAssetAsyncSelectList.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetAsyncSelectList/DataAssetAsyncSelectList.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetAsyncSelectList/DataAssetAsyncSelectList.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.tsx

I added clear options and a value prop to the data asset async select component.
https://github.com/open-metadata/OpenMetadata/assets/59080942/bb89ed13-e91c-4c5b-aa50-88a31a649234
#
#

minor: add value prop in data asset async select list

---

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/NodeChildren/NodeChildren.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/custom-node.less

allow record fields to have column lineage

---

openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java
openmetadata-spec/src/main/resources/json/schema/api/teams/createUser.json
openmetadata-spec/src/main/resources/json/schema/entity/teams/user.json

- Default value for isBot should be false

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Customproperties.spec.ts
openmetadata-ui/src/main/resources/ui/src/constants/CustomProperty.constants.ts

I worked on disabling the date custom property from UI
#
#

minor: disable date custom property from UI

---

openmetadata-docs/content/v1.3.x/connectors/storage/adls/index.md
openmetadata-docs/content/v1.3.x/connectors/storage/adls/yaml.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/storage/adls/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/storage/adls/yaml.md

Added the Supported File types for ADLS Storage
#
#

Minor: Added the Supported File types for ADLS Storage

---

openmetadata-docs/content/v1.3.x/connectors/storage/gcs/index.md
openmetadata-docs/content/v1.3.x/connectors/storage/gcs/yaml.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/storage/gcs/index.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/storage/gcs/yaml.md

Added the Supported File types for GCS Storage
#
#

Minor: Added the Supported File types for GCS Storage

---

openmetadata-docs/content/v1.3.x/deployment/kubernetes/faqs.md
openmetadata-docs/content/v1.3.x/deployment/kubernetes/values.md
openmetadata-docs/content/v1.3.x/quick-start/local-kubernetes-deployment.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/deployment/kubernetes/faqs.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/deployment/kubernetes/values.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/quick-start/local-kubernetes-deployment.md

Improve docs for k8s with updated references
#
#

chore(docs): Improve docs for k8s with updated references

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCases/TestCases.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCases/TestCases.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DatePickerMenu/DatePickerMenu.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/profiler.constant.ts
openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/DataQualityUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/DataQualityUtils.ts

address the test case filters styling feedback
https://github.com/open-metadata/OpenMetadata/assets/71748675/9f38f7c0-fb0f-4b3f-886f-8db1d1f52e67
#
#

Minor: Incorporated feedback on test case filters implementation

---

openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetAsyncSelectList/DataAssetAsyncSelectList.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetAsyncSelectList/DataAssetAsyncSelectList.tsx

I worked on adding the filter isBot:false in the user search list to filter out the bots.
https://github.com/open-metadata/OpenMetadata/assets/59080942/8ea0b42b-101f-4edf-a952-1069924bd622
#
#

minor: filter out bots from user list

---

ingestion/src/metadata/ingestion/processor/query_parser.py
openmetadata-docs/content/v1.1.x/connectors/ingestion/workflows/usage/usage-workflow-query-logs.md
openmetadata-docs/content/v1.2.x/connectors/ingestion/workflows/usage/usage-workflow-query-logs.md
openmetadata-docs/content/v1.3.x/connectors/ingestion/workflows/usage/usage-workflow-query-logs.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/ingestion/workflows/usage/usage-workflow-query-logs.md

Fixes [#16185](https://github.com/open-metadata/OpenMetadata/issues/16185)
I worked on try - catch the usage parsing workflow because I have 100,000+ Hive SQL and if one of them fails, the whole workflow would stop and I will lose all parsing results.
#
#

Fixes 16185: try - catch the usage parsing error

---

openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ColumnProfileTable/ColumnProfileTable.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/TestCaseStatusSummaryIndicator/TestCaseStatusSummaryIndicator.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/TestCaseStatusSummaryIndicator/TestCaseStatusSummaryIndicator.component.tsx

This pull request adds a redirection link to the data quality tab and a tooltip for better user experience. The redirection link allows users to navigate directly to the data quality tab when clicking on a test indicator. The tooltip provides additional information about each test status.
https://github.com/open-metadata/OpenMetadata/assets/71748675/e0dffaa2-59cd-4f64-8ee0-90de2d8ec77b
#
#

Minor: Add redirection link to data quality tab and tooltip for better UX

---

ingestion/src/metadata/profiler/interface/sqlalchemy/databricks/profiler_interface.py

Fixes #16111: Hive Compiler error profiler

---

openmetadata-service/src/main/java/org/openmetadata/service/security/SecurityUtil.java

Credential expiry need not be checked

---

bootstrap/sql/migrations/native/1.4.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.4.0/postgres/schemaChanges.sql
openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/Collection.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/CollectionRegistry.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/bots/BotResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/policies/PolicyResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/RoleResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/TeamResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

- Fix Search Indexing issues in Ops
- BatchSize and recreate updated
- added conditional Init of resources
#
#

[ReindexingOps] Fixes Issues in Reindexing Ops

---

ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py

Fixes #9281 
I worked on col. lineage for powerbi
#
#

issue-9281: column lineage for powerbi

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UserProfileIcon/UserProfileIcon.component.tsx

- I worked on fixing the `displayName` passed as `userName` causing Profile Picture failure
Issue : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/111a0d93-0086-42ea-b7a8-d37527b7bc1a
Resolved : 
https://github.com/open-metadata/OpenMetadata/assets/66266464/b564bdf1-0741-4afd-8f99-63b1195bb542
#
#

MINOR: fix the profile picture caused due to displayName

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/AddIngestion/IngestionWorkflow.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/AddIngestion/Steps/ScheduleInterval.tsx
openmetadata-ui/src/main/resources/ui/src/enums/Explore.enum.ts
openmetadata-ui/src/main/resources/ui/src/utils/SearchClassBase.ts

I worked on the necessary Automator feedback changes in the OSS
#
#

Minor: Automator feedback changes for OSS

---

openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/SchemaEditor.tsx

**Before**
https://github.com/open-metadata/OpenMetadata/assets/59080942/f750d298-0355-4641-b682-2bcc88b723e3
**After**
https://github.com/open-metadata/OpenMetadata/assets/59080942/906b8df9-3705-4ab3-b634-f150f7932025
#
#

minor: fix schema editor copy button tooltip

---

openmetadata-ui/src/main/resources/ui/cypress.config.ts
openmetadata-ui/src/main/resources/ui/cypress/common/EntityUtils.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/DataQuality.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/constants.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityLink.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityLink.ts
openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx

Fixes #15856 
Resolved issue encountered when creating test cases if the table name includes "COLUMN".
Root cause: Incorrect generation of entityLink on the UI side.
Solution: Implemented the use of the EntityLink class to generate table/column entityLink.
Preventive measures: Included unit tests and Cypress tests for future validation.
https://github.com/open-metadata/OpenMetadata/assets/71748675/b0911cb9-3757-4c16-9ca8-2ac32034fcf9
#
#

#15856 Error when creating test cases if the table contains the name COLUMN

---

docker/validate_compose.py

validate_compose.py needed to be cleaned after we removed the cli/docker module
#
#

MINOR - Fix validate compose CI

---

ingestion/src/metadata/ingestion/source/database/database_service.py

MINOR: Fix missing attribute get_table_owner

---

openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx

- The user initially logged into the application. However, if they return after some time and their token is nearing expiration, attempting to access the `'/users/loggedInUser'` API will trigger a 401 error. To resolve this, we'll attempt to refresh the token. Once the token is successfully refreshed, we'll retry the `'/users/loggedInUser'` API call that previously failed.
#
#

minor: retry logged in user after token refresh

---

ingestion/src/metadata/ingestion/source/pipeline/dagster/queries.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/12875
Updated and optimised dagster graphql queries
1. Added limit 1 to the test connection query to fetch the data
2. Removed unused `runs` data from query
#
#

Fix #12875: Updated and optimised dagster graphql queries

---

ingestion/setup.py
ingestion/src/metadata/examples/workflows/kafka_connect.yaml
ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/client.py
ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/connection.py
ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/metadata.py
ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/models.py
openmetadata-docs/content/v1.3.x/menu.md
openmetadata-ui/src/main/resources/ui/src/utils/PipelineServiceUtils.ts
openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts

Fix #11351 Add Kafka Connect Connector

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java

I worked on ... remove aggregation owner.displayName for team_search_index
#
#

[MINOR] remove aggregation owner.displayName for team_search_index

---

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/src/metadata/ingestion/source/database/clickhouse/metadata.py
ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/hive/metadata.py
ingestion/src/metadata/ingestion/source/database/oracle/metadata.py
ingestion/tests/unit/topology/metadata/test_amundsen.py
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/connectionBasicType.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/bigQueryConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/clickhouseConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/databricksConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/hiveConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/mssqlConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/mysqlConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/oracleConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/postgresConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/redshiftConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/snowflakeConnection.json

MINOR:  remove supportsDDL and handles no attr warning.
#
#

MINOR:  Removed supportsDDL from json schemas

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/FeedCardBody/FeedCardBodyV1.tsx
openmetadata-ui/src/main/resources/ui/src/constants/Feeds.constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtilClassBase.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/SearchClassBase.ts

I worked on Activity feed improvements and bug fixes:
**Before:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/40dba567-88b6-424a-aa2c-162b32d4b10b
**After:**
https://github.com/open-metadata/OpenMetadata/assets/51777795/5a4c7846-a783-4aa8-8b64-eec3b22b8af0
#
#

Minor: Activity feed bug fixes and improvements part 2

---

ingestion/src/metadata/ingestion/source/database/azuresql/connection.py

Minor: Fix AzureSQL Authentication mode error
#
#

Minor: Fix AzureSQL Authentication mode error

---

openmetadata-service/src/main/java/org/openmetadata/service/exception/AppException.java
openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

- Fix for reindex job not waiting for completion

---

openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/common.py
openmetadata-airflow-apis/tests/unit/ingestion_pipeline/test_workflow_creation.py

To help identify OM DAGs easily from Airflow UI, since we updated the name to a UUID
#
#

MINOR - Add labels in OM Airflow DAGs

---

openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

- Catch no app run exception

---

ingestion/tests/integration/postgres/conftest.py

This strategy should be friendlier to environnements with more restrictions...
#
#

MINOR: use archive instead of volume for postgres test

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java

Fixes #16102
I worked on 
- Updating logic to add a reviewer as an assignee to task ,when they are added to a glossary term.
#
#

Fix #16102 : Ensure adding reviewer to term adds them as an assignee to the task

---

ingestion/src/metadata/data_insight/processor/reports/web_analytic_report_data_processor.py

Fixes issue with Data Insights misbehaving due to ValidationError.
With this fix it should be able to continue the execution, just logging a warning and skipping the record.
#
#

MINOR: Fix data insights misbehaving due to validation error

---

ingestion/src/metadata/ingestion/source/database/saphana/connection.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/16249
#
#

Fix #16249: Fixed saphana connection

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MigrationDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/MigrationFile.java
openmetadata-service/src/test/java/org/openmetadata/service/util/MigrationWorkflowTest.java

To make sure we are executing Collate migrations when moving from OSS -> Collate
#
#

MINOR - Migrate extension separated from native

---

ingestion/src/metadata/ingestion/source/database/oracle/queries.py
ingestion/src/metadata/utils/stored_procedures.py
ingestion/tests/unit/utils/test_stored_procedures.py

MINOR: Fix Oracle SP Lineage for begin...end SP call

---

ingestion/src/metadata/ingestion/source/database/trino/connection.py
ingestion/tests/unit/test_source_connection.py

Fix #16211: Fix special charechter encoding in trino username
#
#

Fix #16211: Fix special charechter encoding in trino username

---

openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtilClassBase.ts

implemented permission support for import/export feature
#
#

Minor: implemented permissions for import export feature

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java

[MINOR] Fix Import Issue

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/tags/TagResource.java

- Remove Migrate Tags

---

openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java

- Fix Buffering Capacity Issue in Test Case

---

openmetadata-ui/src/main/resources/ui/cypress.config.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Entities/UserClass.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Task.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/SingleColumnProfile.tsx

cypress: fixed cypress aut failure part 3

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx

Team page was showing incorrect data after joining/leaving team
Before:
https://github.com/open-metadata/OpenMetadata/assets/71748675/aeb29e90-f201-4e1e-b1a9-d9f04f9d8463
After:
https://github.com/open-metadata/OpenMetadata/assets/71748675/3e33b273-0160-4f9b-a35d-afa31365cae7
#
#

Minor: fixed join and leave team issue

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/CustomProperty.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Customproperties.spec.ts

test: fix custom properties cypress tests

---

docker/mysql/mysql-script.sql

MINOR: Add PROCESS Priviledge

---

openmetadata-ui/src/main/resources/ui/src/components/Database/SampleDataTable/SampleDataTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/SampleDataWithMessages/SampleDataWithMessages.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizeMyData/CustomizeMyData.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizeMyData/CustomizeMyData.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppInstallVerifyCard/AppInstallVerifyCard.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppInstallVerifyCard/AppInstallVerifyCard.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableList/DomainSelectableList.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/ErrorWithPlaceholder/CreateErrorPlaceHolder.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/ErrorWithPlaceholder/ErrorPlaceHolderES.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/ErrorWithPlaceholder/FilterErrorPlaceHolder.tsx
openmetadata-ui/src/main/resources/ui/src/pages/CustomPageSettings/CustomPageSettings.tsx
openmetadata-ui/src/main/resources/ui/src/pages/CustomizablePage/CustomizablePage.tsx
openmetadata-ui/src/main/resources/ui/src/utils/IngestionUtils.tsx

I worked on updating the hardcoded link color with the theme.
#
#

minor: update hardcoded link color with theme

---

openmetadata-docs/content/partials/v1.4/deployment/upgrade/upgrade-prerequisites.md

WIP - MINOR - Backward Incompatible Docs

---

.github/workflows/py-ingestion-publish.yml
ingestion/pyproject.toml
ingestion/setup.py

Since we moved to pyproject.toml and the setuptools is a build system requirement, we might not even need this anymore https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/pyproject.toml#L2
#
#

MINOR - Remove setuptools req

---

openmetadata-docs/content/v1.1.x/connectors/database/bigquery/yaml.md
openmetadata-docs/content/v1.1.x/connectors/database/trino/yaml.md
openmetadata-docs/content/v1.2.x/connectors/database/bigquery/yaml.md
openmetadata-docs/content/v1.2.x/connectors/database/trino/yaml.md
openmetadata-docs/content/v1.3.x/connectors/database/bigquery/yaml.md
openmetadata-docs/content/v1.3.x/connectors/database/trino/yaml.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/bigquery/yaml.md
openmetadata-docs/content/v1.4.x-SNAPSHOT/connectors/database/trino/yaml.md

1. bigquery - changed example names to strings that resemble actual values
2. trino - added example for http_scheme
#
#

MINOR: small doc improvements

---

openmetadata-ui/src/main/resources/ui/cypress/common/Services/PostgresIngestionClass.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/DataQuality.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/IncidentManager.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightReportApplication.spec.ts

cypress: fixed cypress aut failure 5 and improve recursion logic
#
#

cypress: fixed cypress aut failure 5 and improve recursion logic

---

openmetadata-service/pom.xml

FIX - Pom after docs removal

---

ingestion/tests/integration/powerbi/test_powerbi_file_client.py
ingestion/tests/unit/topology/dashboard/test_superset.py

MINOR: skip pbit test

---

ingestion/tests/unit/topology/dashboard/test_superset.py

I worked on superset pytests fix
#
#

MINOR: superset pytest fix

---

ingestion/setup.py
ingestion/src/metadata/__version__.py

Using the `packaging` module instead. Ref https://setuptools.pypa.io/en/latest/pkg_resources.html
#
#

MINOR - pkg_resources is deprecated

---

ingestion/src/metadata/ingestion/source/dashboard/quicksight/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/quicksight/models.py
ingestion/tests/unit/topology/dashboard/test_quicksight.py

MINOR - Added quicksight pydantic models
#
#

MINOR - Added quicksight pydantic models

---

openmetadata-docs/content/v1.4.x/connectors/storage/adls/yaml.md
openmetadata-docs/content/v1.4.x/connectors/storage/gcs/yaml.md

DOCS - fix YAML for gcs

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

added whats new content for health check feature
#
#

Minor: added whats new content for health check feature

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/SchemaDefinition.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/support/commands.ts

cypress: added cypress to validate schemaDefinition(views)
#
#

cypress: added cypress to validate schemaDefinition(views)

---

openmetadata-ui/src/main/resources/ui/src/constants/Feeds.constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.tsx

- fix the header in deleted team feed
Issue :  
Resolved : 
#
#

MINOR: fix the header in deleted team feed

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/CustomProperty.ts
openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetAsyncSelectList/DataAssetAsyncSelectList.tsx

I worked on adding cypress tests for these custom properties
- Entity Ref
- EntityRef List
#
#

test: add cypress tests for entity ref and entity ref list custom properties

---

openmetadata-docs/content/v1.4.x/how-to-guides/user-guide-data-users/theme.md
openmetadata-docs/content/v1.4.x/menu.md

I worked on adding docs for the custom theme.
#
#

doc: add doc for custom theme

---

openmetadata-ui/src/main/resources/ui/cypress/common/AlertUtils.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/EntityConstant.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/ObservabilityAlerts.spec.ts
openmetadata-ui/src/main/resources/ui/src/utils/ObservabilityUtils.tsx

I worked on fixing the flaky Observability cypress test [here](https://cloud.cypress.io/projects/a9yxci/runs/34205/test-results/9d2c00c0-3392-435b-800e-2f8037c349bb?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github)
Fixed the incorrect icons for destination options
#
#

Minor: Bug fixes and improvements

---

openmetadata-docs/content/v1.4.x/how-to-guides/user-guide-data-users/theme.md

doc: fix typo in custom theme doc

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppLogsViewer/AppLogsViewer.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppLogsViewer/AppLogsViewer.test.tsx

Minor: fixed log viewer ui breaking issue
https://github.com/open-metadata/OpenMetadata/assets/71748675/fecbbf05-bd7c-4e30-bb9f-01a5d525e552
#
#

Minor: fixed log viewer ui breaking issue

---

openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

I worked on  fix OpenSearchClient import
#
#

fix OpenSearchClient import

---

openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx

Fixes lineage export creation after every new node addition.
https://github.com/open-metadata/OpenMetadata/assets/33024356/1b167275-4aad-4f4c-aa3c-706e2bf22259
#
#

create lineage export data 

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java

- Fix Reindex

---

openmetadata-ui/src/main/resources/ui/cypress/common/DataInsightUtils.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Services/PostgresIngestionClass.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/service.constants.ts

cypress: fix AUT flakiness part 7
#
#

cypress: fix AUT flakiness part 7

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/GlossaryTermsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/GlossaryTermsV1.test.tsx

Fixes #15809
I worked on  fix  to  get related  tags and assets on glossary rename
#
#

fix get tags asset on glossary rename

---

openmetadata-ui/src/main/resources/ui/cypress/common/Services/PostgresIngestionClass.ts

cypress: skip cypress usage for AUT
#
#

cypress: skip cypress usage for AUT

---

openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

Fix slow reindexing

---

ingestion/setup.py

MINOR: requests version fix

---

openmetadata-docs/content/v1.4.x/connectors/database/mongodb/yaml.md

MINOR: fix mongodb docs

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/CustomProperty.ts

Minor: improve custom property cypress

---

ingestion/tests/integration/mlflow/test_mlflow.py

MINOR: Fix flaky pytest for mlflow

---

ingestion/src/metadata/ingestion/source/database/unitycatalog/metadata.py

MINOR: Fix UC missing table type
#
#

MINOR: Fix UC missing table type

---

openmetadata-docs/content/v1.4.x/deployment/bare-metal/index.md
openmetadata-docs/content/v1.4.x/deployment/upgrade/bare-metal.md
openmetadata-docs/content/v1.4.x/developers/architecture/code-layout.md
openmetadata-docs/content/v1.4.x/developers/contribute/build-code-and-run-tests/openmetadata-server.md

DOCS - Upgrade bootstrap_storage

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java

Fix Initial Loading offset 
#
#

Fix Initial Offset

---

openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DashboardDetails/DashboardDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MlModel/MlModelDetail/MlModelDetail.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Pipeline/PipelineDetails/PipelineDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Topic/TopicDetails/TopicDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedurePage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx

Fixes Ownership changes for Inherited Owners
https://github.com/open-metadata/OpenMetadata/assets/33024356/901e14ac-ee52-493e-afd5-e7f5ea503584
#
#

fix patch request for inherited ownership

---

openmetadata-docs/content/v1.3.x/connectors/ingestion/workflows/dbt/index.md
openmetadata-docs/content/v1.4.x/connectors/ingestion/workflows/dbt/index.md

Updated dbt core supported versions in docs
#
#

MINOR: [DOCS] Updated dbt core supported versions in docs

---

ingestion/src/metadata/ingestion/source/database/redshift/lineage.py

MINOR: remove newline char in lineage queries

---

openmetadata-service/src/main/java/org/openmetadata/service/search/SearchListFilter.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
openmetadata-ui/src/main/resources/ui/cypress/common/EntityUtils.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/DataQuality.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCases/TestCases.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/DataQualityTab/DataQualityTab.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/DataQualityTab/DataQualityTab.tsx

- Implemented should logic for entityFQN filtering when passing `allTests=true`
- Added tests to validate patch
#
#
Bug fix

[MINOR] test case listing with prefix

---

openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/OidcAuthenticator.tsx
openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx

I worked on fixing the infinite loader issue due to the stale state in oidc auth flow.
- Clear any stale state in the user manager before starting the sign in flow Remove the existing user configuration for the user who is different from the user trying to log in `userManager.clearStaleState();`
- Remove the existing user configuration for the same user who is trying to log `userManager.removeUser()`
Tested Provider
#
#

Minor: clear the stale state before login in oidc

---

openmetadata-ui/src/main/resources/ui/cypress/common/Entities/DatabaseClass.ts

cypress - verify owner propagation

---

bootstrap/sql/migrations/native/1.4.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.4.0/postgres/schemaChanges.sql

1. `ADD UNIQUE` was failing if we had duplicate checksums
2. Syntax error on the `UPDATE` query
```
java.lang.RuntimeException: Failed to run sql: [UPDATE query_entity SET json = jsonb_set(json::jsonb, '{checksum}', MD5((json->>'checksum')::text)::jsonb)] due to [org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: inva
lid input syntax for type json
Detail: Token "d79a8b259915f0abab400dcf9aaf5d24" is invalid.
Where: JSON data, line 1: d79a8b259915f0abab400dcf9aaf5d24 [statement:"UPDATE query_entity SET json = jsonb_set(json::jsonb, '{checksum}', MD5((json->>'checksum')::text)::jsonb)", arguments:{positional:{}, named:{}, finder:[]}]]
```
#
#

FIX - Query checksum & fix update

---

ingestion/setup.py

Version 0.18.14 was just published 30min ago and is breaking our tests. We'll fix to less than that until we can provide a fix or they rollback the interface changes
#
#

MINOR - Fix GX version

---

openmetadata-docs/content/v1.4.x/deployment/upgrade/versions/130-to-140.md

Added init change of pipeline_name to breaking changes in docs
#
#

MINOR: [DOCS] Added init change of pipeline_name to breaking changes in docs

---

common/pom.xml
docker/docker-compose-ingestion/docker-compose-ingestion.yml
docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
docker/docker-compose-quickstart/Dockerfile
docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml
ingestion/Dockerfile
ingestion/operators/docker/Dockerfile
ingestion/pyproject.toml
openmetadata-airflow-apis/pyproject.toml
openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-clients/pom.xml
openmetadata-dist/pom.xml
openmetadata-service/pom.xml
openmetadata-shaded-deps/elasticsearch-dep/pom.xml
openmetadata-shaded-deps/opensearch-dep/pom.xml
openmetadata-shaded-deps/pom.xml
openmetadata-spec/pom.xml
openmetadata-ui/pom.xml
pom.xml

chore: Update `main` branch for `1.5.0` Release

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/EditTestCaseModal.tsx

Fixes [#16381](https://github.com/open-metadata/OpenMetadata/issues/16381)
- fixed Test case not showing test type
- Added cypress
#
#

#16381 Test case not showing test type

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/AbstractEventConsumer.java

Remove Retry From Abstract Event Consumer

---

ingestion/src/airflow_provider_openmetadata/hooks/openmetadata.py
ingestion/src/metadata/utils/ssl_registry.py
openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplicationConfig.java
openmetadata-ui/src/main/resources/ui/src/utils/ConnectionSchemas/SupersetConnection.json

Fixes 1.4.x sslCertificate -> caCertificate issue
#
#

Fix SSL related changes

---

openmetadata-docs/content/v1.4.x/sdk/python/index.md

update python sdk pages to reflect latest version of python package

---

openmetadata-docs/content/v1.3.x/connectors/ingestion/workflows/lineage/lineage-workflow-query-logs.md
openmetadata-docs/content/v1.3.x/connectors/ingestion/workflows/usage/usage-workflow-query-logs.md
openmetadata-docs/content/v1.4.x/connectors/ingestion/workflows/lineage/lineage-workflow-query-logs.md
openmetadata-docs/content/v1.4.x/connectors/ingestion/workflows/usage/usage-workflow-query-logs.md

MINOR: improve query log lineage docs

---

openmetadata-docs/content/partials/v1.3/releases/latest.md

Updating Release Page For 1.3.4
#
#

Minor: Updating Release Page For 1.3.4

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/Severity/Severity.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseStatus/TestCaseIncidentManagerStatus.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuiteList/TestSuites.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerPage.tsx

Before: minor alignment issue in SEVERITY, and no bottom space 
After:
Before:
After:
#
#

Minor: address ui feedback on data observability

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Lineage.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomControls.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomNodeV1.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/LineageLayers/LineageLayers.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/LineageLayers/LineageLayers.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/LineageLayers/lineage-layers.less
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/entity-lineage.style.less
openmetadata-ui/src/main/resources/ui/src/components/Lineage/Lineage.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/Lineage.constants.ts
openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.interface.tsx
openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx
openmetadata-ui/src/main/resources/ui/src/styles/variables.less
openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx

Fixes #16404 
Show Node level lineage by default.
Center the root node on init.
Root node will be selected on launch.
Contains cypress for checking default layer as empty.
Enable the cypress layer to column when performing column lineage operations.
https://github.com/open-metadata/OpenMetadata/assets/33024356/7040f2d6-3407-41d3-8f3f-740b248cc9fd
#
#

Fix#16404 - Show Node level lineage by default

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/CustomProperty.ts
openmetadata-ui/src/main/resources/ui/cypress/common/serviceUtils.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Customproperties.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Database.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Entity.spec.ts

cypress: fixed cypress AUT for mysql

---

ingestion/src/metadata/ingestion/source/database/postgres/usage.py
ingestion/src/metadata/ingestion/source/database/usage_source.py

MINOR: add usage query to the logs

---

openmetadata-docs/content/v1.4.x/quick-start/local-docker-deployment.md

Update local-docker-deployment.md to point to 1.4.1

---

openmetadata-docs/content/v1.4.x/deployment/docker/index.md

Fix 1.3.1 references in docs

---

ingestion/src/metadata/ingestion/source/database/common_db_source.py

MINOR: Only parse valid view query
#
#

MINOR: Only parse valid view query

---

ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
ingestion/src/metadata/ingestion/source/database/databricks/queries.py

Fix #16425 : Correct Schema Definition for Databricks 

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/resources/elasticsearch/en/glossary_term_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/glossary_term_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/glossary_term_index_mapping.json
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Entity.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/advancedSearchQuickFilters.constants.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/constants.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/glossary.constant.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreSearchCard/ExploreSearchCard.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryStatusBadge/GlossaryStatusBadge.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryStatusBadge/GlossaryStatusBadge.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/RelatedTerms.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/TagsSelectForm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/TagsSelectForm.interface.ts
openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
openmetadata-ui/src/main/resources/ui/src/enums/AdvancedSearch.enum.ts
openmetadata-ui/src/main/resources/ui/src/rest/glossaryAPI.ts
openmetadata-ui/src/main/resources/ui/src/rest/miscAPI.ts
openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TagsUtils.tsx

Fixes #16278
Fixes #16431 
Contains Cypress for verifying approved and draft filter.
Also added verification of terms in glossary table once they are created.
https://github.com/open-metadata/OpenMetadata/assets/33024356/985d8f0a-d220-4185-a5ed-8c4fc69ec627
#
#

Fix #16278 : Search to display Draft glossaryTerms on Explore page

---

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java

- Remove Change Description from Lineage

---

ingestion/src/metadata/profiler/processor/metric_filter.py

- Fix `None` is not iterable if `columns_config` is null 
#
#
Bug fix

MINOR: Metric Filter in profiler

---

openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java

Fixes #16493
Added additional check before user deletion from search
#
#

Fix #16493 :User Deletion Error in Search - Adding Conditional Check

---

openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx

Fixes #16466
I worked on fixing tooltip of glossaryTerms in entity page
#
#

#16466 : fix tooltip of glossaryTerms in entity page

---

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java

[Do not Merge ]Non Indexable fields should be remvoed at the end

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Annoucement.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Database.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Entity.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardV2/FeedCardHeader/FeedCardHeaderV2.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardV2/FeedCardHeader/FeedCardHeaderV2.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/AnnouncementsWidget.tsx

- I worked on fixing announcement not redirect from landing page
Issue :  
Resolved :  
https://github.com/open-metadata/OpenMetadata/assets/66266464/b3fc3fbe-e4ef-4510-a75e-ef8c6eed476d
#
#

fix announcement not redirect from landing page

---

.github/workflows/playwright-mysql-e2e.yml

minor: updated workflow to run playwright from branch changes #16511
#
#

minor: updated workflow to run playwright from branch changes

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java

Fixes Null Schema Field Issue
#
#

Fix Schema Field Null Issue

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/ContainerClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/DashboardClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/DashboardDataModelClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/Entity.interface.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/MlModelClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/PipelineClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/SearchIndexClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/TopicClass.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/entityUtils.ts

Added playwight test for follow/un-follow and up vote/down vote
#
#

playwright: added follow unfollow and up vote down vote test

---

openmetadata-docs/content/partials/v1.4/connectors/yaml/database/source-config-def.md
openmetadata-docs/content/partials/v1.4/connectors/yaml/database/source-config.md

Update Multithreading Docs for clarity while configuring the ingestion through YAML files.
#
#

MINOR: Update multithreading docs

---

openmetadata-docs/content/partials/v1.3/deployment/upgrade/post-upgrade-steps.md
openmetadata-docs/content/partials/v1.4/deployment/upgrade/post-upgrade-steps.md

Adding Docs for openmetadata-ops Script under Post Upgrade
#
#

Minor: Adding Docs for openmetadata-ops Script

---

openmetadata-docs/content/v1.3.x/menu.md
openmetadata-docs/content/v1.4.x/menu.md

Adding Menu for Reindexing Search in Admin Guide
#
#

Minor: Adding Menu for Reindexing Search in Admin Guide

---

openmetadata-docs/content/v1.3.x/how-to-guides/admin-guide/roles-policies/use-cases.md
openmetadata-docs/content/v1.4.x/how-to-guides/admin-guide/roles-policies/use-cases.md

Updating docs for adding a simple policy example using API
#
#

Minor: Updating docs for adding a simple policy example using API

---

openmetadata-docs/content/v1.3.x/deployment/docker/index.md
openmetadata-docs/content/v1.4.x/deployment/docker/index.md

Adding Docs for Custom Openmetadata.yaml file
#
#

Minor: Adding Docs for Custom Openmetadata.yaml file

---

openmetadata-docs/content/partials/v1.3/deployment/upgrade/upgrade-prerequisites.md
openmetadata-docs/content/partials/v1.4/deployment/upgrade/upgrade-prerequisites.md

Updating the upgrade docs for Backups & Restore
#
#

Minor: Updating the upgrade docs for Backups & Restore

---

bootstrap/sql/migrations/native/1.4.2/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.4.2/postgres/schemaChanges.sql

Add appType as part of schema in ingestion pipeline

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchListFilter.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseIndex.java
openmetadata-service/src/main/resources/elasticsearch/en/test_case_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/test_case_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/test_case_index_mapping.json
openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
openmetadata-spec/src/main/resources/json/schema/tests/testCase.json

Fixes #16229 
- Inherit tags from tables. Column test case will inherit from table + column tags
- Add filters to list test cases by tags and service
#
#
Improvement

Fix  #16229 - Tag and Service filters for test cases

---

openmetadata-docs/content/partials/v1.4/connectors/python-requirements.md

MINOR: python requirements doc fix

---

openmetadata-ui/src/main/resources/ui/playwright.config.ts

playwright: add support for base url via env variable
#
#

playwright: add support for base url via env variable

---

ingestion/tests/cli_e2e/test_cli_oracle.py

MINOR: Fixed oracle e2e count

---

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/src/metadata/ingestion/source/database/clickhouse/metadata.py
ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/hive/metadata.py
ingestion/src/metadata/ingestion/source/database/oracle/metadata.py

Fix #16370 - Added view/DDL definition rule

---

openmetadata-ui/src/main/resources/ui/src/components/Database/TableDataCardBody/TableDataCardBody.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SearchIndexSummary/SearchIndexSummary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/TagsInput/TagsInput.test.tsx

Fixes #16489
- I worked on fixing unable to open glossary term and tag in new tab
- Decrease mouseDelay of popover to 500ms on `Tags`
https://github.com/open-metadata/OpenMetadata/assets/66266464/76c804b1-bf63-4c7a-8649-42235b1a71db
#
#

#16489: fix the redirect issue to new tab for tags and glossary

---

ingestion/tests/cli_e2e/test_cli_tableau.py

MINOR: Fixed tableau e2e

---

ingestion/src/metadata/ingestion/source/dashboard/quicksight/metadata.py

MINOR: Fixed quicksight conn

---

openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/BlockEditor.tsx
openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.ts

This PR will enhance the block editor's initial content history functionality.
**Before:**
1. Create an article and add content in a single session.
2. Later, return to the article and try to edit it. If you use the undo function, it only reverts changes made in the current session.
3. However, if you attempt to undo changes to the existing content (from previous sessions), the undo function reverts the entire content to its previous state.
**After:**
1. Create an article and add content in a single session.
2. Later, return to the article and try to edit it. If you use the undo function, it only reverts changes made in the current session.
3. If you attempt to undo changes to the existing content (from previous sessions), the undo function does not revert the entire content to its …

minor: improve the block editor initial content history

---

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java
openmetadata-service/src/test/resources/openmetadata-secure-test.yaml

Fix settings for email not encrypted on init

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java

Update documentation for Search Index apis
#
#

Update documentation for Search Index apis

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Lineage.spec.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx

Fixes #16491 
https://github.com/open-metadata/OpenMetadata/assets/33024356/4188f1be-13cf-4a21-9988-58156fb87dcd
#
#

Fix#16491 -  fix lineage edge description update

---

openmetadata-service/src/main/java/org/openmetadata/service/events/EventFilter.java

Fix Event Handlers registration Issue

---

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TopicIndex.java

Fixes messageSchema missing from topic_search_index
#
#

[Bug] Fix Topic Index missing messageSchema

---

.github/workflows/playwright-mysql-e2e.yml

fix(workflow): typo for paths-ignore for playwright

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuiteList/TestSuites.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuiteList/TestSuites.test.tsx

fixed type issue in data quality page
#
#

Minor: fixed data quality page type issue

---

.github/workflows/issues-notion-sync.yml

Sync Github issues to notion

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

I worked on What's new for 1.4.2
#
#

minor(ui) : update what's new for 1.4.2

---

ingestion/tests/cli_e2e/base/test_cli.py
openmetadata-spec/src/main/resources/json/schema/api/createEventPublisherJob.json
openmetadata-spec/src/main/resources/json/schema/api/voteRequest.json
scripts/datamodel_generation.py

FIX - e2e test for pydantic v2

---

Makefile

Added make command to run the playwright code
- `make yarn_start_e2e` to run all the e2e tests in headless mode
- `make yarn_start_e2e_ui` to open and run the test in headed mode
- `make yarn_start_e2e_codegen` to generate e2e test by using ui clicks
#
#

playwright: add make command to run playwright test

---

openmetadata-ui/src/main/resources/ui/playwright.config.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/AnnouncementsWidget.tsx

playwright: fixed AUT announcement test
#
#

playwright: fixed AUT announcement test

---

openmetadata-ui/src/main/resources/ui/cypress/common/Entities/ServiceBaseClass.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Annoucement.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/DataQuality.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Users.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Roles.spec.ts

fixed announcement and flaky cypress
#
#

cypress: fixed flakiness and announcment cypress

---

CONTRIBUTING.md

addded more detail on issue creation in contributors page

---

bootstrap/sql/migrations/native/1.5.0/mysql/postDataMigrationSQLScript.sql
bootstrap/sql/migrations/native/1.5.0/postgres/postDataMigrationSQLScript.sql
ingestion/src/metadata/data_quality/validations/base_test_handler.py
ingestion/src/metadata/data_quality/validations/column/base/columnValueLengthsToBeBetween.py
ingestion/src/metadata/data_quality/validations/column/base/columnValueMaxToBeBetween.py
ingestion/src/metadata/data_quality/validations/column/base/columnValueMeanToBeBetween.py
ingestion/src/metadata/data_quality/validations/column/base/columnValueMedianToBeBetween.py
ingestion/src/metadata/data_quality/validations/column/base/columnValueMinToBeBetween.py
ingestion/src/metadata/data_quality/validations/column/base/columnValueStdDevToBeBetween.py
ingestion/src/metadata/data_quality/validations/column/base/columnValuesSumToBeBetween.py
ingestion/src/metadata/data_quality/validations/column/base/columnValuesToBeBetween.py
ingestion/src/metadata/data_quality/validations/table/base/tableRowCountToBeBetween.py
ingestion/src/metadata/profiler/orm/registry.py
openmetadata-service/src/main/resources/json/data/tests/columnValueMaxToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValueMeanToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValueMedianToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValueMinToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValueStdDevToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesLengthsToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesSumToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/columnValuesToBeBetween.json
openmetadata-service/src/main/resources/json/data/tests/tableRowCountToBeBetween.json
openmetadata-spec/src/main/resources/json/schema/tests/basic.json
openmetadata-spec/src/main/resources/json/schema/tests/testCase.json
openmetadata-spec/src/main/resources/json/schema/tests/testDefinition.json

- added `supportsDynamicAssertion` and `useDynamicAssertion` flag to test case and test definition
- Added migration for `supportsDynamicAssertion` to `true
- Passed `max/minBound` directly to test case results
#
#
Improvement

MINOR - Data Quality Preparatory Work

---

openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

Fix: Ensure correct index mapping in Elasticsearch for clusterAlias

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/ReindexingUtil.java

Minor: Ensure correct index mapping in Elasticsearch for clusterAlias

---

bootstrap/sql/migrations/native/1.4.2/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.4.2/postgres/schemaChanges.sql
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java

Fix Postgres Application listing

---

.github/workflows/py-cli-e2e-tests.yml
ingestion/src/metadata/ingestion/source/dashboard/metabase/models.py
ingestion/tests/cli_e2e/base/test_cli_dashboard.py
ingestion/tests/cli_e2e/test_cli_metabase.py
ingestion/tests/cli_e2e/test_cli_powerbi.py
ingestion/tests/cli_e2e/test_cli_redash.py

MINOR: Fix e2e

---

docker/run_local_docker.sh

Update `run_local_docker.sh` script with cluster alias ES endpoint
#
#

fix(CI): update `run_local_docker.sh` script with cluster alias ES endpoint

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Annoucement.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Ingestion.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Users.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/glossary.constant.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/Lineage.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsight.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/GlossaryVersionPage.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Policies.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Roles.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/SearchIndexApplication.spec.ts
openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx

cypress: fixed 1.4.2 AUT cypress #16602
#
#

cypress: fixed 1.4.2 AUT cypress

---

openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts

playwright announcement click
#
#

playwright: announcement-click-issue

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Login.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/constants.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Customproperties.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Database.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Entity.spec.ts

This PR will add support for updateJWTTokenExpiryTime util, which can be used in spec to update the default JWT token expiry.
#
#

test: add updateJWTTokenExpiryTime util

---

ingestion/src/metadata/data_quality/interface/pandas/pandas_test_suite_interface.py
ingestion/src/metadata/data_quality/interface/sqlalchemy/sqa_test_suite_interface.py

modify Test Suite get_connection to bring in connection
#
#

Add Test Suite SSL

---

.github/workflows/playwright-mysql-e2e-skip.yml
.github/workflows/playwright-mysql-e2e.yml
.github/workflows/playwright-postgresql-e2e-skip.yml
.github/workflows/playwright-postgresql-e2e.yml

workflow: add postgresql playwright and skip workflow
#
#

chore(CI): Add PostgreSQL playwright and skip workflows

---

ingestion/src/metadata/ingestion/source/database/query_parser_source.py

MINOR: Fix ssl connection in usage & lineage

---

openmetadata-service/src/main/java/org/openmetadata/service/util/SubscriptionUtil.java

Fix owner notification

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/ServiceEntity.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityClass.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/customProperty.ts

Remove sample data dependency for custom property
#
#

playwright: updated entity spec with custom property test

---

.github/actions/setup-openmetadata-test-environment/action.yml
.github/workflows/playwright-integration-tests-mysql.yml
.github/workflows/playwright-integration-tests-postgres.yml
.github/workflows/py-tests.yml

use "Setup OpenMetadata Test Environment" in playwright tests. Suggesting after noticing failures like this:
https://github.com/open-metadata/OpenMetadata/actions/runs/9482484761/job/26127460640?pr=16554x
#
#

MINOR: use test setup action for playwright tests

---

openmetadata-ui/src/main/resources/ui/cypress/common/DomainUtils.ts

Domain flaky cypress fix

---

.github/workflows/playwright-integration-tests-mysql.yml
.github/workflows/playwright-mysql-e2e.yml
.github/workflows/playwright-postgresql-e2e.yml

MINOR: use setup aciton in playwright e2e tests

---

ingestion/src/metadata/ingestion/source/dashboard/qliksense/metadata.py

Arg mismatch fixed for datamodels in qliksense
#
#

Minor: Fix Arg for Qliksense

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Services.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/ServiceEntity.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/ContainerClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/DashboardClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/DashboardDataModelClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/MlModelClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/PipelineClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/SearchIndexClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/TopicClass.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/customProperty.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts

playwright: improve the existing playwright test
#
#

playwright: improve the existing playwright test

---

ingestion/tests/cli_e2e/test_cli_metabase.py
ingestion/tests/cli_e2e/test_cli_powerbi.py

MINOR: Fix E2E count

---

openmetadata-docs/content/v1.4.x/deployment/upgrade/index.md

Fixing Typo in the Upgrade Docs
#
#

Doc: Fixing Typo in the Upgrade Docs

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java

- Fix User Signup

---

openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-service/pom.xml
openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

chore: Update What's new and vulnerability fix

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java

Fixes #16663
Fix the if condition `path.equals("/roles")` to `path.contains("/roles")`
This is because the actual payload comes in as `{"op": "remove", "path": "/roles/0/(some thing)"}`, and the `equals` statement does not perform authorization verification for the roles modification API.
#
#

Fixes #16663: Fix the UserResource.patch's if condition (PATCH `v1/users/{id}`)

---

ingestion/tests/integration/sql_server/test_lineage.py

MINOR: skip mssql test for python

---

openmetadata-clients/openmetadata-java-client/src/main/java/org/openmetadata/client/gateway/OpenMetadata.java

Fixes #15499
The previous PR #15500 has been merged, ~~but it has not yet been reflected in the official release.~~(I found it confirmed in v1.4.0) Additionally, the previous PR had a bug where the null check for apiClient was insufficient. I am submitting code to fix this issue as well.
#
#

Fixes #15499: Fix the OpenMetadata(Client) constructor bug - ApiClient null check. (re-commit)

---

openmetadata-docs/content/v1.3.x/how-to-guides/data-insights/cost-analysis.md
openmetadata-docs/content/v1.4.x/how-to-guides/data-insights/cost-analysis.md

Updated Cost Analysis supported connectors
#
#

MINOR: [DOCS] Updated Cost Analysis supported connectors

---

ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/tests/unit/topology/dashboard/test_superset.py

MINOR: Fix superset cypress error

---

ingestion/src/metadata/ingestion/source/database/mssql/lineage.py
ingestion/src/metadata/ingestion/source/database/mssql/metadata.py
ingestion/src/metadata/utils/helpers.py
ingestion/tests/integration/sql_server/test_lineage.py

SQL Server Lineage was failing after the timezone change was introduced in b3eae8c1b975a39207df242a67158f54da355fe8.
This change fixes the issue and introduces the regression test to avoid it in the future.
#
#

MINOR: fix sql lineage with timezone change

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/TeamsDragAndDrop.spec.ts

- I worked on fixing cypress failure for teams drag and drop in before
- Remove the `sidebarClick` method as it is already present in the `settingClick` method
#
#

CYPRESS: fix cypress failure for teams drag and drop

---

ingestion/setup.py

MINOR: Fix numpy version for bigquery ingestion

---

docker/development/docker-compose-postgres.yml
docker/development/docker-compose.yml
docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml

Add WebConf Env to Compose

---

openmetadata-docs/content/v1.4.x/how-to-guides/index.md

Updating Icon for Data Quality and Observability
#
#

Doc: Updating Icon for Data Quality and Observability

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Owner.ts

I worked on fixing cypress for dataModelVersionPage
#
#

CYPRESS: fix cypress for dataModelVersionPage

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/CustomProperty.ts

The PATCH request response is taking more than expected time in the AUT environment so updated the responseTimeout to `70000`
#
#

test: fix custom properties spec

---

openmetadata-docs/content/v1.3.x/deployment/ingestion/external/airflow.md
openmetadata-docs/content/v1.4.x/deployment/ingestion/external/airflow.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/ingestion/external/airflow.md

Updating Enum for PipelineType
#
#

Doc: Updating Enum for PipelineType

---

openmetadata-docs/content/v1.3.x/deployment/security/saml/index.md
openmetadata-docs/content/v1.4.x/deployment/security/saml/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/saml/index.md

Updating Private Key Information for SAML
#
#

Doc: Updating Private Key Information for SAML

---

ingestion/tests/cli_e2e/test_cli_datalake_s3.py

Fixed Datalake S3 expected filter excluded e2e test
#
#

MINOR: Fixed expected result for schemas exclude

---

ingestion/src/metadata/profiler/metrics/window/percentille_mixin.py

chore: update percentille_mixin.py

---

openmetadata-docs/content/v1.3.x/deployment/security/saml/index.md
openmetadata-docs/content/v1.3.x/how-to-guides/index.md
openmetadata-docs/content/v1.4.x/deployment/security/saml/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/saml/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/how-to-guides/index.md

Fixes #16723
Adding Example for SAML Private Key
#
#

Doc: Adding Example for SAML Private Key

---

openmetadata-docs/content/v1.4.x/sdk/python/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/sdk/python/index.md

Add docs for better understanding on how to add SSLConfig using Python SDK
#
#

Docs: Add Docs around SSL under OpenMetadataConfig

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java

- When hitting a loggedInUserApi, both the userName and Email needs to be validated and match agains the claims of the token , so that valid user that is looked for is returned
#
#

Add Validation for username and email on logged in user

---

ingestion/setup.py
ingestion/src/_openmetadata_testutils/ometa.py
ingestion/tests/integration/airflow/test_lineage_runner.py
ingestion/tests/integration/airflow/test_status_callback.py
ingestion/tests/integration/conftest.py
ingestion/tests/integration/integration_base.py
ingestion/tests/integration/ometa/test_ometa_app_api.py
ingestion/tests/integration/ometa/test_ometa_lineage_api.py
ingestion/tests/integration/ometa/test_ometa_patch.py
ingestion/tests/integration/ometa/test_ometa_suggestion_api.py
ingestion/tests/integration/ometa/test_ometa_table_api.py
ingestion/tests/integration/ometa/test_ometa_user_api.py
ingestion/tests/integration/profiler/test_nosql_profiler.py
ingestion/tests/integration/profiler/test_sqa_profiler.py
ingestion/tests/integration/s3/conftest.py
ingestion/tests/unit/conftest.py

MINOR: moved int_admin_ometa to a dedicated module

---

.github/workflows/playwright-mysql-e2e.yml
.github/workflows/playwright-postgresql-e2e.yml

fixed npx playwright version to 1.44.1
#
#

Minor: fix version of playwright in CI

---

ingestion/src/metadata/ingestion/lineage/sql_lineage.py

MINOR: fixed lineage error

---

openmetadata-docs/content/v1.4.x/connectors/database/redshift/yaml.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/redshift/yaml.md

Fixes Redshift Documentation
#
#

Docs: Fix Redshift docs formatting

---

openmetadata-docs/content/v1.3.x/deployment/ingestion/external/index.md
openmetadata-docs/content/v1.4.x/deployment/ingestion/external/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/ingestion/external/index.md

Add CLI examples on the main external docs page
#
#

DOCS - Add CLI on external docs

---

ingestion/src/metadata/utils/credentials.py
ingestion/tests/unit/test_credentials.py

Fixes AttributeError for external account
#
#

Minor: Fixes Bigquery External Account AttributeError

---

ingestion/src/metadata/ingestion/models/custom_pydantic.py
ingestion/tests/integration/ometa/test_ometa_custom_properties_api.py

MINOR: Include default values in custom pydantic model

---

ingestion/tests/integration/ometa/test_ometa_table_api.py
ingestion/tests/integration/ometa/test_ometa_tags_mixin.py
openmetadata-spec/src/main/resources/json/schema/type/tagLabel.json

Fixes #16760
I worked on remove tagFQN limit
#
#

Fixes #16760: Remove maxLength for tagFQN

---

.github/workflows/py-tests-skip.yml

MINOR - Add 3.11 to py-test skip CI

---

openmetadata-docs/content/v1.4.x/connectors/database/bigquery/create-credentials.md
openmetadata-docs/content/v1.4.x/connectors/database/bigquery/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/bigquery/create-credentials.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/bigquery/index.md

MINOR: BigQuery Create Credentials Docs Correction

---

.github/actions/setup-openmetadata-test-environment/action.yml
ingestion/src/metadata/ingestion/source/database/azuresql/connection.py
ingestion/tests/integration/sql_server/conftest.py
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/mssqlConnection.json

Fixes #16435 
I worked on modifying pyodbc conditions that will validate if it's from mssql or azuresql
#
#

Fixes #16435: Fix pyodbc error for mssql

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Collect.spec.ts

I worked on adding the e2e playwright test for the collect end point and removed the cypress test spec `Collect.spec.ts`
#
#

test: add e2e playwright test for collect endpoint

---

.github/actions/prepare-for-docker-build-and-push/action.yml
.github/workflows/docker-openmetadata-db.yml
.github/workflows/docker-openmetadata-ingestion-base-slim.yml
.github/workflows/docker-openmetadata-ingestion-base.yml
.github/workflows/docker-openmetadata-ingestion.yml
.github/workflows/docker-openmetadata-postgres.yml
.github/workflows/docker-openmetadata-server.yml

This PR addresses common issues for Ingestion Release Cycle Process.
We will additionally include a new Image Tag aligning with the ingestion pypi version for the docker images and keep updating the existing docker image tags whenever there will be a new release.
This will give us flexibility to deploy newer docker images with just the ingestion changes published.
Example, for new releases, we will have ingestion docker images with 2 tags (1.5.0, 1.5.0.0). So next time, if we have new python libraries published, the CI will update ingestion docker images with new tags (1.5.0,1.5.0.1). For users consuming the image tags with <MAJOR>.<MINOR>.<PATCH> , this will be a non breaking changes.
#
#

feat: Ingestion Docker Image Tags

---

ingestion/tests/cli_e2e/base/test_cli.py
ingestion/tests/cli_e2e/base/test_cli_db.py
ingestion/tests/cli_e2e/database/redshift/redshift.yaml
ingestion/tests/cli_e2e/test_cli_redshift.py
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/redshift/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/redshift/troubleshooting.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/redshift/yaml.md

exclude information_schema in tests and document it as best practice.
#
#

MINOR: exclude information_schema in redshift

---

openmetadata-docs/content/partials/v1.5/connectors/dashboard/configure-ingestion.md
openmetadata-docs/content/partials/v1.5/connectors/database/advanced-configuration.md
openmetadata-docs/content/partials/v1.5/connectors/database/configure-ingestion.md
openmetadata-docs/content/partials/v1.5/connectors/ingestion-schedule-and-deploy.md
openmetadata-docs/content/partials/v1.5/connectors/messaging/configure-ingestion.md
openmetadata-docs/content/partials/v1.5/connectors/metadata-ingestion-ui.md
openmetadata-docs/content/partials/v1.5/connectors/metadata/configure-ingestion.md
openmetadata-docs/content/partials/v1.5/connectors/ml-model/configure-ingestion.md
openmetadata-docs/content/partials/v1.5/connectors/pipeline/configure-ingestion.md
openmetadata-docs/content/partials/v1.5/connectors/search/configure-ingestion.md
openmetadata-docs/content/partials/v1.5/connectors/storage/configure-ingestion.md
openmetadata-docs/content/partials/v1.5/connectors/test-connection.md
openmetadata-docs/content/partials/v1.5/connectors/yaml/data-profiler.md
openmetadata-docs/content/partials/v1.5/connectors/yaml/lineage.md
openmetadata-docs/content/partials/v1.5/connectors/yaml/query-usage.md
openmetadata-docs/content/partials/v1.5/deployment/redeploy.md
openmetadata-docs/content/partials/v1.5/deployment/reindex.md
openmetadata-docs/content/partials/v1.5/deployment/upgrade/post-upgrade-steps.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/bigquery/create-credentials.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/pipeline/dbtcloud/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/pipeline/dbtcloud/yaml.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/pipeline/flink/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/pipeline/flink/yaml.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/ingestion/external/index.md

DOCS: doc fix v1.5

---

.github/workflows/cypress-integration-tests-mysql-pr.yml

support e2e label for running cypress

---

openmetadata-service/src/main/resources/json/data/tags/piiTags.json
openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.mock.ts

Just a typo in the tags description
I worked on this description fix because descriptions are important.
#
#

fix: PII description

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java

- fix breaking ingestion pipeline filters
#
#

MINOR - Fix Ingestion Pipeline Filters

---

.github/workflows/py-tests.yml

following the outage described here: https://community.sonarsource.com/t/outage-sonarscanner-cli-docker-sonarqube-sonarcloud-github-actions/113548/36#report-summary-and-improvements-following-the-sonarscanner-cli-docker-release-on-april-16-2024-1
changed sonarcloud action to use the tagged version as described in [their README](https://github.com/SonarSource/sonarcloud-github-action/commit/9c11606f1328e4a0d52d6df7cbe4b21e62b8dfdc)
#
#

MINOR: use tagged sonarcloud action

---

common/pom.xml
docker/docker-compose-ingestion/docker-compose-ingestion.yml
docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
docker/docker-compose-quickstart/Dockerfile
docker/docker-compose-quickstart/docker-compose-postgres.yml
docker/docker-compose-quickstart/docker-compose.yml
ingestion/Dockerfile
ingestion/operators/docker/Dockerfile
ingestion/pyproject.toml
openmetadata-airflow-apis/pyproject.toml
openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-clients/pom.xml
openmetadata-dist/pom.xml
openmetadata-service/pom.xml
openmetadata-shaded-deps/elasticsearch-dep/pom.xml
openmetadata-shaded-deps/opensearch-dep/pom.xml
openmetadata-shaded-deps/pom.xml
openmetadata-spec/pom.xml
openmetadata-ui/pom.xml
pom.xml

chore: Update main branch for 1.5.0 Release

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
openmetadata-spec/src/main/resources/json/schema/api/tests/createTestCase.json

Fix dynamic assertion create json schema
#
#
Bug fix

MINOR: Fix dynamic assertion create json schema

---

ingestion/examples/sample_data/tests/testCaseResults.json
ingestion/examples/sample_data/tests/testSuites.json
ingestion/src/metadata/ingestion/source/database/sample_data.py

added table diff results sample
#
#

MINOR: added table diff sample results

---

openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsClassBase.ts

Fixes: Testsuite re-deploy pipeline test failues
Issue: While merging Limit PR, we accidentally removed the Data Observability option from the settings page, causing failure for the relevant e2e test.
Fix: Added Data Observability option again
https://github.com/open-metadata/OpenMetadata/assets/12962843/e84f0745-a6f0-4c34-a570-7532f61c9697
#
#

chore(ui): fix re-deploy ingestion pipeline e2e tests

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DomainRepository.java
openmetadata-spec/src/main/resources/json/schema/entity/domains/domain.json

Fixes #16507 
Add field 'assets'  tpo Domains
#
#

Add Assets field to domain

---

openmetadata-docs/content/v1.3.x/deployment/metrics/index.md
openmetadata-docs/content/v1.3.x/menu.md
openmetadata-docs/content/v1.4.x/deployment/metrics/index.md
openmetadata-docs/content/v1.4.x/menu.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/metrics/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/menu.md

MINOR: added docs for metrics

---

openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java

Minor: Do not start limits if its disabled

---

openmetadata-docs/content/partials/v1.5/deployment/upgrade/upgrade-prerequisites.md

Ingestion Version Tagging system update for `1.5.0`
#
#

docs: Ingestion Version Tagging system update for `1.5.0`

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java

MINOR: fix getter for failed rows sample

---

ingestion/src/metadata/data_quality/processor/test_case_runner.py
ingestion/src/metadata/utils/entity_link.py
ingestion/tests/integration/conftest.py
ingestion/tests/integration/postgres/test_data_quality.py
ingestion/tests/integration/postgres/test_postgres.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/16700
#
#

Fix #16700: Fail ingestion gracefully when column is not compatible with test type

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

Minor: change 1.4.4 release date
#
#

Minor: change 1.4.4 release date

---

openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/DataAssetsWidget/DataAssetCard/DataAssetCard.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/DataAssetsWidget/DataAssetCard/DataAssetCard.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/DataAssetsWidget/DataAssetsWidget.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/DataAssetsWidget/data-assets-widget.less
openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts

- I worked on fixing the service name which was in `capitalize` and don't follow their naming convention like service name `BigQuery` before it was displayed like `Bigquery`
- Remove unwanted spacing around the card and changed the background color to more lighter.
#
#

MINOR: fix data assets label for all the services

---

openmetadata-docs/content/v1.5.x-SNAPSHOT/how-to-guides/data-quality-profiler/test.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/how-to-guides/data-quality-profiler/tests-yaml.md
openmetadata-service/src/main/resources/json/data/tests/tableDiff.json

- copied openmetadata-docs/content/v1.4.x/how-to-guides/data-quality-observability/quality/tests-yaml.md to v1.5
- added table diff docs
#
#

MINOR: table diff docs

---

openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/PipelineServiceStatusJob.java

cast pipeline to PipelineServiceClientInterface
Fixes:
```java
ERROR [2024-07-02 14:22:01,802] [DefaultQuartzScheduler_Worker-9] o.q.c.JobRunShell - Job status.pipelineServiceStatusJob threw an unhandled Exception: 
java.lang.ClassCastException: class org.openmetadata.service.clients.pipeline.MeteredPipelineServiceClient cannot be cast to class org.openmetadata.service.clients.pipeline.PipelineServiceClient (org.openmetadata.service.clients.pipeline.MeteredPipelineServiceClient and org.openmetadata.service.clients.pipeline.PipelineServiceClient are in unnamed module of loader 'app')
at org.openmetadata.service.events.scheduled.PipelineServiceStatusJob.execute(PipelineServiceStatusJob.java:30)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at …
```

MINOR: fix: cast to pipeline

---

ingestion/src/metadata/ingestion/source/dashboard/superset/api_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py
ingestion/tests/unit/topology/dashboard/test_superset.py

Fix #16735 
I worked on superset lineage error
#
#

superset lineage fix

---

ingestion/src/metadata/ingestion/source/mlmodel/sagemaker/metadata.py

Fixes #16899 
Minor update to the logic when iterating over the ML model results.
#
#

Fix #16899: Iterate over all results collected from response

---

openmetadata-ui/src/main/resources/ui/.licenseheaderignore

Minor: updated licenseheaderignore file for playwright
#
#

Minor: updated licenseheaderignore file for playwright

---

openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts

- I worked on fixing playwright test for DataAssetsWidget
#
#

MINOR : fix playwright test for DataAssetsWidget

---

openmetadata-docs/content/v1.3.x/connectors/ingestion/workflows/dbt/ingest-dbt-ui.md
openmetadata-docs/content/v1.3.x/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md
openmetadata-docs/content/v1.4.x/connectors/ingestion/workflows/dbt/ingest-dbt-ui.md
openmetadata-docs/content/v1.4.x/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/ingestion/workflows/dbt/ingest-dbt-ui.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/dbt.md

Updated dbt cloud permissions
#
#

MINOR: [DOCS] Updated dbt cloud permissions

---

ingestion/src/_openmetadata_testutils/pydantic/test_utils.py
ingestion/tests/integration/data_quality/test_data_diff.py

moved `assert_equal_pydantic_objects` to a dedicated util library
#
#

MINOR: Pydantic equal assert util

---

common/src/main/java/org/openmetadata/common/utils/CommonUtil.java

use set to dedupe jar list when retrieving resources
Avoid situations like these:
#
#

MINOR: fix get resources

---

openmetadata-service/pom.xml
openmetadata-service/src/main/java/org/openmetadata/service/resources/analytics/WebAnalyticEventResource.java

Throw exception on HTML input for collect endpoint

---

openmetadata-docs/content/v1.4.x/menu.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/menu.md

Docs: Fixing broken Menu Link

---

openmetadata-docs/content/v1.4.x/connectors/ingestion/workflows/dbt/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/ingestion/workflows/dbt/index.md

MInor: Added Tiers&Glossary in dbt docs main page
#
#

MInor: Added Tiers&Glossary in dbt docs main page

---

openmetadata-ui/src/main/resources/ui/src/components/common/Form/Form.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/Form/FormItemLabel.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/Form/FormItemLabel.tsx
openmetadata-ui/src/main/resources/ui/src/interface/FormUtils.interface.ts
openmetadata-ui/src/main/resources/ui/src/styles/components/form.less
openmetadata-ui/src/main/resources/ui/src/utils/formUtils.tsx

The below image is for demonstration purpose.
#
#

Minor: Add support for beta tag for form field

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/CustomProperty.ts
openmetadata-ui/src/main/resources/ui/src/components/Settings/CustomProperty/CustomPropertyTable.tsx

I worked on improving the custom property table on the settings page.
1. make the table scrollable
2. make the action column fixed
#
#

minor: improve the custom property table in settings page

---

openmetadata-docs/content/v1.4.x/sdk/python/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/sdk/python/index.md

Modify Python SDK docs

---

openmetadata-docs/content/v1.4.x/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.4.x/quick-start/local-kubernetes-deployment.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/quick-start/local-kubernetes-deployment.md

Updating the Admin User ID
#
#

Doc: Updating the Admin User ID

---

ingestion/src/metadata/ingestion/source/database/redshift/queries.py

Fixes #16647 (Redshift view lineage error)
#
#

MINOR: Redshift view lineage error

---

openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/CustomHtmlRederer/CustomHtmlRederer.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/CustomHtmlRederer/CustomHtmlRenderer.test.ts
openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/RichTextEditor.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/RichTextEditorPreviewer.tsx

Fixes https://github.com/open-metadata/OpenMetadata/issues/14234
I worked on Fixes https://github.com/open-metadata/OpenMetadata/issues/14234
The latex content should be wrapped inside `$$latex $$`
Example: 
```
$$latex
\text{$\dfrac{NetSales}{Quantity Invoiced}=Average Price, \:$ If QuantityInvoiced is Null then,$\: AveragePrice=Null$}
$$
```
https://github.com/open-metadata/OpenMetadata/assets/59080942/047f671e-596e-456a-beac-586fcbeb9bb6
#
#

minor: add latex node in description editor

---

ingestion/setup.py
ingestion/src/metadata/profiler/interface/sqlalchemy/databricks/profiler_interface.py
ingestion/tests/unit/profiler/sqlalchemy/databricks/test_visit_column.py

Fixes #16562 
I worked on modifying the HiveCompiler to compile the column names properly to integrate backticks for struct columns
#
#

Fixes 16562: Modify HiveCompiler to compile column names properly

---

ingestion/examples/sample_data/tests/testSuites.json
ingestion/src/metadata/ingestion/source/database/sample_data.py

Fixes sample data ingestion
#
#
Bug fix

MINOR - fix sample data ingestion

---

bootstrap/sql/migrations/native/1.5.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.5.0/postgres/schemaChanges.sql
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataConnectionBuilder.java
openmetadata-service/src/main/resources/json/data/policy/DefaultBotPolicy.json
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResourceTest.java
openmetadata-spec/src/main/resources/json/schema/entity/policies/accessControl/resourceDescriptor.json

Related to https://github.com/open-metadata/openmetadata-collate/issues/460
1. Adding the `CREATE_INGESTION_PIPELINE_AUTOMATOR` permission.
1. Ingestion pipeline permissions authorization are dynamic and based on the pipelineType or appType. We could expand the permissions following this convention if we ever need a `CREATE_INGESTION_PIPELINE_TEST_SUITE` or `CREATE_INGESTION_PIPELINE_METAPILOT`.
2. Adding a new `EDIT_INGESTION_PIPELINE_STATUS` to better scope how bots can interact with Ingestion Pipelines (which required updating the default bot policy and migrations from https://github.com/open-metadata/OpenMetadata/pull/16941)
@aniketkatkar97, now you'll get the following permission response for Ingestion Pipelines:
```
{
"operation": "CreateIngestionPipelineAutomator",
"access": …
```

REL #460-CL - Metadata Actions Create Permissions

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/lineage.ts
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityInfoDrawer/EntityInfoDrawer.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/AppPipelineModel/AddPipeLineModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomEdge.component.tsx

Fixes Tier showing in lineage summary.
Allow adding pipeline between all entities.
#
#

Allow adding pipeline between all entities in lineage

---

ingestion/src/metadata/data_quality/validations/column/base/columnValuesToMatchRegex.py
ingestion/src/metadata/data_quality/validations/column/pandas/columnValuesToMatchRegex.py
ingestion/src/metadata/data_quality/validations/column/sqlalchemy/columnValuesToMatchRegex.py

- Compute total count and regex count in the same query to have consistent sample for both metrics
#
#
Bug fix

MINOR: fix regex to match test case

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/DataAssetsWidget.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts

playwright: fixed tier, DataAssetWidget test for AUT
#
#

playwright: fixed tier, dataAssets test for AUT

---

openmetadata-docs/content/v1.4.x/connectors/storage/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/storage/index.md

MINOR: Docs example for s3 unstructured file

---

openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java
openmetadata-service/src/main/java/org/openmetadata/service/formatter/entity/IngestionPipelineFormatter.java

Fixes #16951 the Ingestion Pipeline Url generated for PipelineTypes, TestSuite, Application, others.
#
#

[Issue-16951] Fix Ingestion Pipeline Url in Emails and Alert Notifications

---

ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py

MINOR: Fix snowflake test failure due to sqlparse upgrade

---

ingestion/examples/sample_data/api_service/api_collection.json
ingestion/examples/sample_data/api_service/api_endpoint.json
ingestion/examples/sample_data/api_service/service.json
ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/src/metadata/ingestion/ometa/routes.py
ingestion/src/metadata/ingestion/source/database/sample_data.py
openmetadata-service/src/main/java/org/openmetadata/service/resources/apis/APICollectionResource.java
openmetadata-spec/src/main/resources/json/schema/api/services/createApiService.json
openmetadata-spec/src/main/resources/json/schema/entity/services/apiService.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/serviceConnection.json

API service sample data

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SearchIndexApplication.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/task.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts
openmetadata-ui/src/main/resources/ui/src/styles/app.less

- I worked on supporting util method for toast Notification
- Beta badge size fix
Issue : 
Resolved : 
#
#

PLAYWRIGHT: supported util method for toast Notification

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TestSuiteMultiPipeline.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/TableClass.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddTestCaseList/AddTestCaseList.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteIngestionPage/TestSuiteIngestionPage.tsx

issue: modification of test case in test suite pipeline was not getting reflected
https://github.com/open-metadata/OpenMetadata/assets/71748675/781bdd68-4ecb-41a4-82b6-223fe97c7156
#
#

Minor: fixed edit test suite pipeline issue

---

ingestion/src/metadata/ingestion/source/database/common_db_source.py

When troubleshooting issues with ingestion we get only the name of the table:
```python
metadata.Ingestion:status:76} - Unexpected exception to yield table [my_table]: ()
[2024-07-05 15:12:59] DEBUG    {metadata.Ingestion:status:77} - Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/metadata/ingestion/source/database/common_db_source.py", line 454, in yield_table
) = self.get_columns_and_constraints(
File "/usr/local/lib/python3.10/site-packages/metadata/utils/execution_time_tracker.py", line 195, in inner
result = func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/metadata/ingestion/source/database/sql_column_handler.py", line 239, in get_columns_and_constraints
columns = inspector.get_columns(table_name, schema_name, db_name=db_name)
File …
```

MINOR: log context when failing to yield table

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/TestCaseForm.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/TestCaseForm.tsx

Fixes #16699
https://github.com/open-metadata/OpenMetadata/assets/71748675/3e3446c4-e655-4494-894d-f91c01e720c9
#
#

#16699 [Data Quality] Column is displayed for unsupported columns

---

ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py

Added Owner support for tableau datamodels
#
#

MINOR: Added Owner support for tableau datamodels

---

ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
ingestion/src/metadata/ingestion/source/database/oracle/metadata.py
ingestion/src/metadata/ingestion/source/pipeline/airflow/metadata.py
ingestion/tests/integration/ometa/test_ometa_user_api.py

Fix #16590: Allow only team groups to be owner 
#
#

Fix #16590: Allow only team groups to be owner

---

openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SearchIndexSummary/SearchIndexSummary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsV1/TagsV1.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/TierCard.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/TierCard.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/TableData.mock.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx

Fixes #16742
- I worked on supporting style in entity tier.
- also added style in entitySummaryPanel
#
#

#16742: support style in entity tier

---

ingestion/examples/sample_data/ometa_api_service/ometa_api_collection.json
ingestion/examples/sample_data/ometa_api_service/ometa_api_endpoint.json
ingestion/examples/sample_data/ometa_api_service/service.json
ingestion/src/metadata/ingestion/source/database/sample_data.py

api service sample data(ometa apis)

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/apis/APIEndpointResourceTest.java

Minor: Fix API Endpoint listings via apiCollection param

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
openmetadata-ui/src/main/resources/ui/src/mocks/Teams.mock.ts
openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx

Fixes #16980
- I worked on fixing the asset count in the teams' page.
- Minor placeholder letter issue.
https://github.com/open-metadata/OpenMetadata/assets/66266464/c2c5aa39-a02a-4766-947c-8064147fb342
#

#16980: fix the asset count and placeholder issue in teams page

---

openmetadata-docs/content/v1.4.x/how-to-guides/data-quality-observability/quality/configure.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/quality-and-observability/data-quality/index.md

Doc: Update Test Suite Docs

---

bootstrap/sql/migrations/native/1.4.5/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.4.5/postgres/schemaChanges.sql

Related to https://github.com/open-metadata/OpenMetadata/pull/17005 but for 1.5
#
#

MINOR - Clean automations_workflow in 1.4.5

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/apis/APIEndpointResource.java

APIEndpoint Resources referring to Schema class that doesn't exist causing malformed swagger.json 
#
#

Minor: Fix API docs

---

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/APIServiceIndex.java

Minor: fix API Service Index entity type

---

ingestion/src/metadata/ingestion/source/messaging/common_broker_source.py
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/messaging/kafkaConnection.json

Fixes https://github.com/open-metadata/OpenMetadata/issues/17023
#
#

feat: allow specify schemaRegistryTopicSuffixName

---

openmetadata-docs/content/v1.4.x/connectors/database/db2/index.md
openmetadata-docs/content/v1.4.x/connectors/database/trino/index.md
openmetadata-docs/content/v1.4.x/developers/index.md

I worked on fixing the broken links in the documention.
#
#

Minor: Fix the broken links in the documentation

---

openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertsRuleEvaluator.java

Fixes #16357: Improve Alerts Filtering with Exact FQN Matching

---

ingestion/tests/cli_e2e/test_cli_metabase.py

Update Count on Metabase E2E Test.
Everything looks correct on the instance after ingesting metabase. Because of this I'm updating the count to fix the E2E Test.
One interesting thing is that even though we are updating only two tables lineage records, we get them repeatedly. @ulixius9 any ideas of what this might be? Thanks
```
source_start_time=1721035107.493684 records=[
'table [id: 98a7b911-764f-4cbd-af33-a491ca7ada42]',
'table [id: f9d3380c-1122-4162-ba7a-0326b0ffa4e5]',
'table [id: 98a7b911-764f-4cbd-af33-a491ca7ada42]',
'table [id: 98a7b911-764f-4cbd-af33-a491ca7ada42]',
'table [id: f9d3380c-1122-4162-ba7a-0326b0ffa4e5]',
'table [id: 98a7b911-764f-4cbd-af33-a491ca7ada42]', 'table [id: f9d3380c-1122-4162-ba7a-0326b0ffa4e5]'
] updated_records=[] warnings=[] filtered=[] failures=[] …
```

MINOR: Update test_cli_metabase.py

---

openmetadata-ui/src/main/resources/ui/webpack.config.dev.js

Updated proxy context from `/api` to `/api/` for accurate routing to the target server.
#
#

chore: update webpack development proxy configuration context from `/api` to `/api/`

---

openmetadata-ui/src/main/resources/ui/src/components/AppContainer/AppContainer.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AppContainer/AppContainer.tsx
openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AppRouter.tsx

Fixes loading issue of Metapilot.
#
#

fix router redirection paths

---

ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
ingestion/tests/unit/topology/database/test_databricks.py

MINOR: fix column name in databricks ingestion fail

---

openmetadata-docs/content/v1.4.x/developers/contribute/build-code-and-run-tests/openmetadata-server.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/openmetadata-server.md

Fixes #17040
Updating  Developers Docs for OpenSearch
#
#

Doc: Updating  Developers Docs for OpenSearch

---

ingestion/src/metadata/ingestion/source/database/lineage_source.py
ingestion/src/metadata/ingestion/source/database/usage_source.py
ingestion/tests/unit/resources/log_files/failed_logs.txt
ingestion/tests/unit/resources/log_files/query_log_file1.csv
ingestion/tests/unit/resources/log_files/query_log_file2.csv
ingestion/tests/unit/test_usage_log.py

I worked on fetching query logs as both directory and single file.
#
#

MINOR: query log path as dir/file

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java

- Added `testSuites` when fetching test case to set summary to not override value
#
#
Bug fix

MINOR: Fix test case summary update on test result PUT

---

ingestion/Makefile
ingestion/pyproject.toml
ingestion/setup.py
ingestion/src/metadata/cmd.py

Adding PyRight to our Python Project.
#
#

MINOR: Add PyRight TypeCheck to our Python Project

---

openmetadata-service/src/main/resources/json/data/app/SearchIndexingApplication.json
openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/SearchIndexingApplication.json
openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json

I worked on adding apiService, apiEndpoint and apiCollection entity SearchIndexingApplication.json

minor: add apiService, apiEndpoint and apiCollection entity SearchIndexingApplication.json

---

openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/entity-header-title.less

I worked on fixing entity icon overlapping on text.
Issue : 
Resolved : 
#
#

MINOR: fix entity icon overlapping on text

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestDefinitionResourceTest.java

- Fix PSQL query for supportedDataType return type
#
#
Bug fix

MINOR - fix test definition dtype filter

---

openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/SamlAuthenticator.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/SamlAuthenticator.tsx

minor: saml reject token renewal

---

openmetadata-service/src/main/java/org/openmetadata/service/events/ChangeEventHandler.java

[Issue-17054] Ignore Entity No Change Events

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java

[Issue-16569] Fix App Issue on Disabled

---

openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

[Issue- 13263]Add Sync Option in OpenmetadataOperations

---

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseIndex.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java

Fixes #17049 
- test case indexing -- remove changeDescription from testSuites list
#
#
Bug fix

Fix: test case indexing -- remove changeDescription from testSuites list

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/activityFeed.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/task.ts
openmetadata-ui/src/main/resources/ui/src/components/Entity/Task/TaskTab/TaskTab.component.tsx

Fixes #17043
- I worked on fixing the same suggestion content being displayed on a different task
Issue :  
https://github.com/user-attachments/assets/0ef50bf0-808b-49cf-8ba4-681de8935722
Resolved : 
https://github.com/user-attachments/assets/7d746633-6d45-4e2b-b255-28f2b605f070
#
#

#17043: fix the same suggestion content being displayed on task

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java

[MINOR] Fix Condition for deleted App

---

ingestion/src/metadata/cmd.py
ingestion/tests/cli_e2e/test_cli_oracle.py

Fixes Oracle E2E Tests
Profiler test is broken due to a bug. We don't seem to support Oracle Blob Type. An issue [will be open](https://github.com/open-metadata/OpenMetadata/issues/17085) to fix this and remove the expected failure.
```
sqlalchemy.exc.DatabaseError: (oracledb.exceptions.DatabaseError) ORA-00932: inconsistent datatypes: expected - got BLOB
Help: https://docs.oracle.com/error-help/db/ora-00932/
[SQL: /* {"app": "***", "version": "1.5.0.0.***0"} */
SELECT anon_2.anon_1, anon_2."valuesCount", anon_2."distinctCount", anon_2.anon_1 AS anon_1_1, anon_2.anon_1 AS anon_1_2, anon_2."nullCount", anon_2.anon_1 AS anon_1_3, anon_2.anon_1 AS anon_1_4 
FROM (SELECT NULL AS anon_1, count(photo) AS "valuesCount", count(DISTINCT photo) AS "distinctCount", NULL AS anon__1, NULL AS anon__2, …
```

MINOR: Fix Oracle E2E Tests

---

ingestion/src/metadata/profiler/processor/sampler/sampler_factory.py
ingestion/src/metadata/profiler/processor/sampler/sqlalchemy/sampler.py
ingestion/src/metadata/profiler/processor/sampler/sqlalchemy/snowflake/sampler.py

Fixes #16501
I worked on optimizing row sample type in snowflake
#
#

Fixes #16501: Optimize Rows Sample Type Snowflake

---

openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Athena.md

Updating Athena Service Connection Docs
#
#

Doc: Updating Athena Service Connection Docs

---

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseIndex.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java

- handle potential null pointer in test case reindex
#
#
Bug fix

fix: handle potential null pointer in test case reindex

---

openmetadata-docs/content/v1.4.x/connectors/database/athena/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/athena/index.md

Doc: Updated Athena Docs

---

openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/metaPilotAppConfig.json

Required for updating the config in MetaPilot for Collate
#
#

MINOR - Update MetaPilot config

---

ingestion/operators/docker/Dockerfile.ci

Adding a bound to setuptools as it fails with the error added in the issue below
ref: https://github.com/pypa/setuptools/issues/4496
#
#

Minor: Add Bound to Setuptools

---

ingestion/src/metadata/ingestion/source/database/domodatabase/metadata.py
ingestion/src/metadata/ingestion/source/database/domodatabase/models.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/16786
#
#

Fix #16786: Added domo federated dataset support

---

openmetadata-docs/content/v1.4.x/deployment/security/basic-auth/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/basic-auth/index.md

I worked on fixing some documents because they don't follow an implementation.
#
#

Fixes 16849: fix usernames

---

ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
ingestion/tests/unit/test_handle_partitions.py

Fixes https://github.com/open-metadata/OpenMetadata/issues/17098
#
#

Fix #17098: Fixed case sensitive partition column name in Bigquery

---

ingestion/src/metadata/ingestion/models/ometa_lineage.py
ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py
ingestion/src/metadata/ingestion/sink/metadata_rest.py
ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/pipeline/pipeline_service.py
ingestion/tests/integration/ometa/test_ometa_lineage_api.py
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/lineage/LineageResource.java
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dashboardServiceMetadataPipeline.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/pipelineServiceMetadataPipeline.json

Fix #16692: Override Lineage Support for View & Dashboard Lineage
#
#

Fix #16692: Override Lineage Support for View & Dashboard Lineage

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/ExploreTree/ExploreTree.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Explore/ExploreTree/ExploreTree.tsx
openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreV1.component.tsx

Fix needed for knowledge center 
#
#

fix explore type changes

---

ingestion/src/metadata/profiler/orm/types/custom_hex_byte_string.py

log parsing errors on hexbytes as `debug` because byte data does have to be utf8. 
#
#

MINOR: changed log level to debug

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java

Fixes #16588 : Get feed and count data of soft deleted user

---

openmetadata-docs/content/v1.4.x/deployment/security/oidc/index.md
openmetadata-docs/content/v1.4.x/menu.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/oidc/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/menu.md

Doc: Adding OIDC Docs in 1.4.x

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/CustomProperty.ts

I worked on updating the custom property entity reference value from user to team so that it will always be present for tests.
#
#

test: update the custom property entityReference data

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

Minor: Added whats new content for 1.4.6 release
#
#

Minor: Added whats new content for 1.4.6 release

---

ingestion/Makefile
openmetadata-airflow-apis/pyproject.toml

Fixes Setuptools installation issue
ref: https://github.com/pypa/setuptools/issues/4483
#
#

MINOR: Update setuptools version in Makefile and pyproject.toml

---

openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/AddWidgetModal/AddWidgetModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/AddWidgetModal/AddWidgetModal.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/CustomizablePage.mock.ts
openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx

Fixes #17021
- I worked on fixing the newly added widget to the bottom.
- Fix the check display on the widget even if it has been removed.
https://github.com/user-attachments/assets/eb79cd58-a182-4cee-b83f-ce7930f1bdc9
https://github.com/user-attachments/assets/8b534b09-8d75-463b-a34d-dfd53394f946
https://github.com/user-attachments/assets/135fe0b3-0dc7-4f21-8c49-54f0b488f3a0
#

#17021: fix the widget placement when adding new

---

openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/MysqlConnectionClassConverter.java
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/PostgresConnectionClassConverter.java
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/TrinoConnectionClassConverter.java

MINOR: Fix Trino Azure config secret not hidden

---

openmetadata-ui/src/main/resources/ui/public/robots.txt
openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
openmetadata-ui/src/main/resources/ui/webpack.config.prod.js

This pull request includes changes to remove the robots.txt file as we don't need it for the application since it's for internal usage only.

chore: remove robots.txt

---

openmetadata-docs/content/v1.4.x/developers/contribute/build-code-and-run-tests/prerequisites.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/prerequisites.md

Updated Node Version in Docs
#
#

Doc: Updated Node Version in Docs

---

openmetadata-ui/src/main/resources/ui/playwright/support/entity/TableClass.ts

playwright: aut test failure for testSuitePipeline
#
#

playwright: aut test failure for testSuitePipeline

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/util/TestUtils.java

run scheduling procedures for apps with Scheduled or ScheduledOrManual schedule type
#
#

MINOR: fix: scheduled apps

---

ingestion/tests/cli_e2e/test_cli_tableau.py

Minor: Fix tableau e2e changed filter count
Changed count to 13 :
`AssertionError: 14 != 13 in assert_filtered_mix `
#
#

Minor: Fix tableau e2e changed filter count

---

openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummaryGraph.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummaryGraph.tsx

https://github.com/user-attachments/assets/232c4ae6-efb4-4ee0-80e3-81b430841a64
#
#

Minor: added test case graph filters

---

bootstrap/sql/migrations/native/1.5.0/mysql/postDataMigrationSQLScript.sql
bootstrap/sql/migrations/native/1.5.0/postgres/postDataMigrationSQLScript.sql

Fixes GEN-1011
- fix typo in DQ migration
#
#
Bug fix

GEN-1011: typo in DQ migration filter

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java

MINOR change deploy failure message

---

ingestion/src/_openmetadata_testutils/helpers/docker.py
ingestion/src/_openmetadata_testutils/postgres/conftest.py
ingestion/tests/integration/sql_server/conftest.py
ingestion/tests/integration/trino/conftest.py

MINOR: copy data to sql server container instead of using volumes

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-ui/src/main/resources/ui/src/constants/Lineage.constants.ts

allow dropping off pipeline as node

---

ingestion/tests/cli_e2e/test_cli_bigquery_multiple_project.py

Minor: Fix bigquery multiple project e2e test
#
#

Minor: Fix bigquery multiple project e2e test

---

openmetadata-docs/content/v1.3.x/deployment/ingestion/external/index.md
openmetadata-docs/content/v1.4.x/deployment/ingestion/external/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/ingestion/external/index.md

added `pip install openmetadata-ingestion` to the external ingestion guide
#
#

MINOR: docs: explicit install command

---

bootstrap/sql/migrations/native/1.5.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.5.0/postgres/schemaChanges.sql

Update entity_extension to move owner to array

---

openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/CustomHtmlRederer/CustomHtmlRederer.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/rich-text-editor-previewer.less

https://github.com/user-attachments/assets/4d27e072-6d11-4c79-aa3a-da7cabe37241
#
#

Minor: description code block copy button should work properly

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseResultTab/TestCaseResultTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseResultTab/TestCaseResultTab.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseResultTab/TestCaseResultTabClassBase.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummaryGraph.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummaryGraph.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerDetailPage/IncidentManagerDetailPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerDetailPage/useTestCase.store.ts
openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/TestSummaryGraphUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/TestSummaryGraphUtils.ts

This is supporting PR for adding banner for collate side
#
#

Minor: Added Ai learning banner if data is not accurate

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestCases.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/EditTestCaseModal.tsx

Fixed mysql statement test case bug
https://github.com/user-attachments/assets/18c42d64-a747-4bd9-a5b4-103b9af881fb
#
#

Minor: fixed test case and mysql query bug

---

ingestion/setup.py
ingestion/src/_openmetadata_testutils/postgres/conftest.py

MINOR: Fix postgres conftest import

---

conf/openmetadata.yaml

Minor: add bindHost to configure the host ip for OpenMetadata Server

---

openmetadata-docs/content/v1.4.x/deployment/security/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/index.md

Updated Security Docs For SSO
#
#

Doc: Updated Security Docs For SSO

---

openmetadata-service/src/main/java/org/openmetadata/service/util/FullyQualifiedName.java
openmetadata-service/src/test/java/org/openmetadata/service/util/FullyQualifiedNameTest.java

Fix #17165 : Fix isParent method to correctly identify FQN parent-child relationships

---

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/RelatedTerms.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/TagsSelectForm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsSelectForm/TagsSelectForm.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/TreeAsyncSelectList.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/TreeAsyncSelectList.tsx
openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.tsx

- I worked on filtering out glossary term option of same term in the related term
https://github.com/user-attachments/assets/05a06b7b-2c5f-4576-a640-a5e9dacfb34e
#
#

MINOR: filter out glossary term option of same term in the related term

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
openmetadata-spec/src/main/resources/json/schema/api/tests/createCustomMetric.json
openmetadata-spec/src/main/resources/json/schema/tests/customMetric.json

Updated CustomMetric owner to entityReferenceList.
#
#

Updated CustomMetric owner to entityReferenceList.

---

ingestion/src/metadata/ingestion/source/database/saperp/client.py
ingestion/src/metadata/ingestion/source/database/saperp/constants.py
ingestion/src/metadata/ingestion/source/database/saperp/metadata.py
ingestion/src/metadata/ingestion/source/database/saperp/models.py
ingestion/tests/unit/topology/database/test_saperp.py
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/sapErpConnection.json

PR incorporated below feedback for SAPERP connector:
1. Moved label from description to displayName
2. Excluded `.INCLUDE` columns
3. Added length info for CHAR columns
4. Added SSL config
5. Updated the retry codes incase the rate limit exceeds on the SAP ERP server.
#
#

MINOR: Implemented SAPERP Connector feedback

---

ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/models.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/queries.py
openmetadata-spec/src/main/resources/json/schema/entity/data/dashboardDataModel.json

Fixes https://github.com/open-metadata/OpenMetadata/issues/15218
1.  Tableau Connector will now unify all the `Embedded Datasources` that the `Workbooks` use by creating an upstream lineage to the `Published Datasource` which will then get connected to the upstream tables. It will be represented as shown in below image
2.  Process Column level lineage for the datasources and tables as shown in below image
3.  Added Support to create lineage from Tableau Custom SQL Queries
#
#

Fix #15218: Unify Tableau Datamodels and added Support to create lineage from Tableau Custom SQL Queries

---

openmetadata-docs/content/v1.4.x/connectors/custom-connectors.md
openmetadata-docs/content/v1.4.x/connectors/ingestion/workflows/metadata/filter-patterns/database.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/custom-connectors.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/ingestion/workflows/metadata/filter-patterns/database.md

Updated Ingestion Filter Docs
#
#

Doc: Updated Ingestion Filter Docs

---

ingestion/src/metadata/ingestion/source/database/athena/connection.py

Fixes #16476
I worked on athena test connection changes for `GetTables` method.
#
#

MINOR: Athena test connection changes

---

openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/Airflow.md

Updated Airflow Service Connection Docs
#
#

Doc: Updated Airflow Service Connection Docs

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardV2/FeedCardBody/DescriptionFeed/DescriptionFeed.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardV2/FeedCardBody/DescriptionFeed/DescriptionFeed.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/DescriptionFeed.mock.ts

- I worked on fixing the ui breaking because of description feed
Issue : 
#
#

MINOR: fix the ui breaking because of description feed

---

ingestion/src/metadata/ingestion/source/pipeline/fivetran/client.py
ingestion/src/metadata/ingestion/source/pipeline/fivetran/metadata.py
ingestion/src/metadata/ingestion/source/pipeline/fivetran/models.py
ingestion/src/metadata/ingestion/source/pipeline/openlineage/metadata.py
ingestion/src/metadata/ingestion/source/pipeline/pipeline_service.py
ingestion/tests/unit/topology/pipeline/test_fivetran.py

Fixes #14945 
I worked on Fivetran Epic improvements
#
#

Fixes #14945: FiveTran Improvements

---

ingestion/src/metadata/ingestion/source/database/dynamodb/metadata.py
ingestion/src/metadata/ingestion/source/database/dynamodb/models.py

FIX #17206: Dynaomodb pagination type fix
#
#

FIX #17206: Dynaomodb pagination type fix

---

openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java

maven build failure due to old version of TableResourceTest
#
#

fix test after merging multi-owner ,maven build fail

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/DataAssetsWidget.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ExploreQuickFilters.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/ProfilerConfigurationPage.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/glossary/Glossary.interface.ts
openmetadata-ui/src/main/resources/ui/playwright/support/glossary/Glossary.ts
openmetadata-ui/src/main/resources/ui/playwright/support/glossary/GlossaryTerm.ts
openmetadata-ui/src/main/resources/ui/playwright/support/tag/TagClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/user/UserClass.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/admin.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts

I worked on fixing the errors on playwright tests due to circular dependencies
#
#

Minor: Fix playwright circular dependencies

---

openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/automator/addOwnerAction.json

MINOR - Automator multiple ownership

---

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/UserPage/UserPage.component.tsx

- fix user data  not appearing in MyData Widget
- fix user data  not appearing in User Profile MyData Page
- Fix Assets not coming in Teams
Issue : 
Resolved :
#
#

MINOR: fix user asset not coming in myData and widget

---

.github/teams.yml

MINOR: Update Teams

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/EditTestCaseModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/ParameterForm.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/ParameterForm.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/TestSuite.mock.ts

Minor: add support for column dropdown for current table if test definition has field name column 
https://github.com/user-attachments/assets/5fd5ecae-5180-4251-a787-cd27c7aede9b
#
#

Minor: add support for column dropdown for current table if test definition has field name column

---

openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.test.tsx
openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
openmetadata-ui/src/main/resources/ui/src/pages/APICollectionPage/APIEndpointsTab.tsx
openmetadata-ui/src/main/resources/ui/src/utils/DataAssetsHeader.utils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx

I worked on showing the available request method of the api endpoint
#
#

minor: show request method for api endpoint

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataInsightSystemChartRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/datainsight/system/DataInsightSystemChartResource.java

MINOR: Fix DataInsightsReport App filter

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v150/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v150/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v150/MigrationUtil.java

Update Automator ingestion pipelines to manage multiple ownership changes
#
#

MINOR - Migration - Automator multiple ownership

---

ingestion/src/metadata/ingestion/source/database/mssql/constants.py
ingestion/src/metadata/ingestion/source/database/mssql/lineage.py
ingestion/src/metadata/ingestion/source/database/mssql/metadata.py
ingestion/src/metadata/ingestion/source/database/mssql/queries.py
ingestion/src/metadata/ingestion/source/database/mssql/utils.py
ingestion/tests/integration/sql_server/test_lineage.py

Fix #16434 
I worked on mssql date format issue when using different language
#
#

Fix #16434: SQL server date format issue

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProviderContext.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/FeedsWidget/FeedsWidget.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/FeedsWidget/FeedsWidget.test.tsx
openmetadata-ui/src/main/resources/ui/src/rest/feedsAPI.ts

I worked on increasing the feed size for the landing page feed widget
https://github.com/user-attachments/assets/f3a44ac4-764a-402a-baf2-0fdb7ade3956
#
#

MINOR: increase the feed size for the landing page feed widget

---

ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java

MINOR: Fix lineage PATCH API

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v150/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v150/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v150/MigrationUtil.java

MINOR: Data insights app migration

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/yarn.lock

Bump braces to 3.0.3 in /openmetadata-ui/src/main/resources/ui

---

bootstrap/sql/migrations/native/1.5.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.5.0/postgres/schemaChanges.sql

This info is already there on the entity_relationship.
In sandbox beta we might have older data that has these 2 fields populated. The `owner` field is giving us issues for the migration after the multiple ownership.
#
#

MINOR - remove owner and service field from ingestion pipeline

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java

After multi owner changes, adding owners via patch request (with only id and type), fails the cypress tests for single field search
Fix for below scenario:
when owner added via patch request:
```
[
{
"op": "add",
"path": "/owners/0",
"value": {
"id": "d1fef383-0928-471a-8ecb-061a4aaf8fab",
"type": "user"
}
}
]
```
#
#

Minor : fix populateOwners method to patch all fields of owners

---

ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
ingestion/tests/cli_e2e/test_cli_tableau.py

Fixed tableau multi owner and e2e counts
#
#

MINOR: Fixed tableau multi owner and e2e counts

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/DataAssetsWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v150/MigrationUtil.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java

MINOR: Update data insights migration to make the flow easier

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsApp.java

MINOR: Improve DI error log

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v150/Migration.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v150/MigrationUtil.java

In 1.5.0 we are updating owner -> owners to allow multiple individual owners to be able to own a data asset.
In this process we updated EditOwner -> EditOwners, there must be a migration to handle old policies to have new EditOwners operation
#
#

Minor: Fix Policy rule migration due to owner -> owners

---

openmetadata-service/pom.xml
openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/NativeApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/settings/SettingsCache.java
openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java
openmetadata-spec/src/main/resources/json/schema/configuration/slackAppConfiguration.json
openmetadata-spec/src/main/resources/json/schema/settings/settings.json

Slack App Integration.

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/DataQuality.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/CustomMetric.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/IncidentManager.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/QueryEntity.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/constant/login.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/auth.setup.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/login.ts
openmetadata-ui/src/main/resources/ui/src/pages/AddCustomMetricPage/AddCustomMetricPage.tsx

Minor: fixed AUT test of main

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsApp.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/CostAnalysisWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/DataAssetsWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/WebAnalyticsWorkflow.java

Providing better errors in order to help debug DataInsights Pipeline issues.
#
#

MINOR: Data insights provide better exceptions

---

openmetadata-docs/content/v1.4.x/how-to-guides/admin-guide/alerts.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/how-to-guides/admin-guide/alerts.md

Updated SMTP Configuration Path in Docs.
#
#

Doc: Updated SMTP Configuration Path in Docs

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v150/MigrationUtil.java

Otherwise if we ran the migration twice (e.g., with --force), there was a big stacktrace complaining about the `owner` key not being present.
#
#

MINOR - Clean Automator owner migration

---

openmetadata-ui/src/main/resources/ui/src/constants/Services.constant.ts

Remove the following services from the beta list
- couchbase
- doris
- greenplum
- Iceberg
- QlikCloud
- QlikSense
- Spark

minor: update beta services list

---

openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/MsalAuthenticator.tsx

Fixes: Azure issue
- From UI user email has value from username instead of actual email from the token.
- This makes an update call to the user email and will alter user's email on DB causing and invalid entry on DB
- To fix that, I have to ensure that all principle claims value as being passed as it is as user object. Refer to recording with multiple logins
**In case we face any user without login issue after this change, they should try changing their `principleClaims` as [preffered_username] as the first claim followed by email and sub**
https://github.com/user-attachments/assets/c69e1a1c-2529-463b-a1fb-c27fd6bbb68c
#
#

fix(ui): msal authentictor to share UserProfile object on login success

---

bootstrap/sql/migrations/native/1.4.7/mysql/postDataMigrationSQLScript.sql
bootstrap/sql/migrations/native/1.4.7/postgres/postDataMigrationSQLScript.sql

Add Fqn Migration to lowercase

---

bootstrap/sql/migrations/native/1.4.7/mysql/postDataMigrationSQLScript.sql
bootstrap/sql/migrations/native/1.4.7/postgres/postDataMigrationSQLScript.sql
openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java

Migrate NameHash

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

feat(ui): whats new content for 1.4.7

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsApp.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/WorkflowStats.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/CostAnalysisWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/processors/AggregatedCostAnalysisReportDataAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/processors/AggregatedCostAnalysisReportDataProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/processors/DatabaseServiceTablesProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/processors/RawCostAnalysisReportDataProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/DataAssetsWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/WebAnalyticsWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/processors/WebAnalyticsEntityViewProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/processors/WebAnalyticsUserActivityAggregator.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/processors/WebAnalyticsUserActivityProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/sources/PaginatedWebAnalyticEventDataSource.java

A few modifications to help debug any issue with the Data Insights Pipeline:
- Better Names for the Steps
- Add Exception message to the bubbled up exception
- Store all the errors and create one Exception that will be printed by the end of the Workflow
#
#

MINOR: Provide better errors on DataInsights Pipeline

---

openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/TestSummaryGraphUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/TestSummaryGraphUtils.ts

Minor: fixed graph calculation issue for y axis

---

openmetadata-service/src/main/java/org/openmetadata/service/dataInsight/MostViewedEntitiesAggregator.java

MINOR: Fix DI most view data assets aggregation

---

ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/looker/utils.py
ingestion/src/metadata/readers/file/api_reader.py
ingestion/src/metadata/readers/file/gitlab.py
ingestion/tests/unit/readers/test_credentials.py
ingestion/tests/unit/topology/dashboard/test_lookml_gitlab_reader.py
openmetadata-docs/content/v1.5.x-SNAPSHOT/menu.md
openmetadata-service/src/main/java/org/openmetadata/service/secrets/converter/LookerConnectionClassConverter.java
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/dashboard/lookerConnection.json
openmetadata-spec/src/main/resources/json/schema/security/credentials/gitlabCredentials.json

Fixes [16010](https://github.com/open-metadata/OpenMetadata/issues/16010)
Included new readers and repo clone utilities for gitlab.com-hosted LookML ingestion
#
#

Fixes 16010: Support Looker ingestion from Gitlab

---

openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Hive.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Impala.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/MongoDB.md
openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Salesforce.md

Updated Database SSL Service Connection Docs
#
#

Doc: Updated Database SSL Service Connection Docs

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightSettings.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppLogsViewer/AppLogsViewer.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppLogsViewer/AppLogsViewer.test.tsx
openmetadata-ui/src/main/resources/ui/src/constants/constants.ts

- Fix DataInsightSettings cypress test
- Fix Glossary Rename playwright test
- Fix the wrong status and icon being showed in applogs
Issue : 
Resolved : 
#
#

TEST : fix DataInsightSetting cypress and glossary rename playwright issue

---

openmetadata-service/src/main/java/org/openmetadata/service/security/AuthenticationCodeFlowHandler.java

[Azure] Check Expiry on Callback for fetched Tokens

---

ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py

Small improvement on PowerBI connector to avoid showing an unecessary WARNING:
```
[2024-08-07 15:38:02] WARNING  {metadata.Ingestion:base:133} - Error trying to close the step <metadata.ingestion.source.dashboard.powerbi.metadata.PowerbiSource object at 0x10e4f5fc0> due to ['NoneType' object has no attribute 'delete_tmp_files']
```
#
#

MINOR: Add a check to see if file_client is present

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseResultTab/TestCaseResultTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/components/code-mirror.less

Fixed SQL copy button icon
before
After
#
#

Minor: fixed ui feedback for data quality

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java

Removing `sampleData` and `changeDescription` fields from the Data Insights document since they are not useful at the moment and they are conflicting.
#
#

MINOR: Remove sampleData and changeDescription from Data Insights documents

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/ApiDocs.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Tour.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx

test: add playwright test for tour and api docs

---

openmetadata-ui/src/main/resources/ui/cypress/common/CustomizeLandingPageUtils.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Entities/UserClass.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/PersonaFlow.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/AddWidgetModal/AddWidgetModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/AddWidgetModal/AddWidgetModal.tsx
openmetadata-ui/src/main/resources/ui/src/rest/DocStoreAPI.ts

- I worked on fixingAUT cypress failure for user,persona and customize landing
#
#

CYPRESS: fix AUT cypress failure for user,persona and customizeLanding

---

openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.component.tsx

supporting file for bulk import
#
#

Minor: bulk import supporting file

---

openmetadata-docs/content/v1.3.x/connectors/dashboard/superset/yaml.md
openmetadata-docs/content/v1.4.x/connectors/dashboard/superset/yaml.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/dashboard/superset/yaml.md

set example port for superset to 8088 which is default port used by the application
#
#

MINOR: superset port example

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java

Fixes https://github.com/open-metadata/OpenMetadata/issues/16039
Fix the error `contains no value for name 'sourceHash'` while patching the DatabaseSchema entity wherein patch had the sourceHash updated.
#
#

Fix #16039: Fixed sourceHash patch for DatabaseSchema entity

---

openmetadata-docs/content/v1.5.x-SNAPSHOT/how-to-guides/data-quality-profiler/tests-yaml.md

add supported connector list
#
#

MINOR: add add supported connector list for table diff docs

---

.github/labeler.yml

MINOR - Add spec label on PRs for easy tracking

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java

Minor: Validate apiEndpoint response schema fields

---

ingestion/src/metadata/ingestion/source/database/database_service.py

Fixes #17331 
I worked on the ingestion module because the type hint in one of the class is incorrect which causes confusion when I trace the codebase.
#
#

Fixes #17331: Incorrect type hint

---

openmetadata-docs/content/v1.4.x/deployment/security/azure/bare-metal.md
openmetadata-docs/content/v1.4.x/deployment/security/azure/docker.md
openmetadata-docs/content/v1.4.x/deployment/security/azure/index.md
openmetadata-docs/content/v1.4.x/deployment/security/azure/kubernetes.md
openmetadata-docs/content/v1.4.x/deployment/security/keycloak/bare-metal.md
openmetadata-docs/content/v1.4.x/deployment/security/keycloak/docker.md
openmetadata-docs/content/v1.4.x/deployment/security/keycloak/kubernetes.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/azure/bare-metal.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/azure/docker.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/azure/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/azure/kubernetes.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/keycloak/bare-metal.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/keycloak/docker.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/keycloak/kubernetes.md

Adding Note for JWT_PRINCIPAL_CLAIMS Order
#
#

Doc: Adding Note for JWT_PRINCIPAL_CLAIMS Order

---

openmetadata-docs/content/v1.4.x/deployment/kubernetes/aks.md
openmetadata-docs/content/v1.4.x/deployment/kubernetes/eks.md
openmetadata-docs/content/v1.4.x/deployment/kubernetes/gke.md
openmetadata-docs/content/v1.4.x/deployment/kubernetes/index.md
openmetadata-docs/content/v1.4.x/deployment/kubernetes/on-prem.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/kubernetes/aks.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/kubernetes/eks.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/kubernetes/gke.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/kubernetes/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/kubernetes/on-prem.md

Updating Broken K8 FAQ Links
#
#

Doc: Updating Broken K8 FAQ Links

---

openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/TestSummaryGraphUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/TestSummaryGraphUtils.ts

Minor: fixed params calculation for aborted test
Before:
After:
#
#

Minor: fixed params calculation for aborted test

---

ingestion/src/metadata/ingestion/source/pipeline/dbtcloud/client.py
ingestion/src/metadata/ingestion/source/pipeline/dbtcloud/metadata.py

Fixed dbt cloud connector:
1. Token not passing correctly
2. Error if the lineageDetails object was not populated.
#
#

MINOR: Fixed dbt cloud connector

---

ingestion/examples/sample_data/looker/dashboardDataModels.json

To showcase a bit more easily looker
#
#

MINOR - LKML sample data

---

conf/openmetadata.yaml

Fix #17372: Add Connection Pooling config to database

---

openmetadata-ui/src/main/resources/ui/src/components/common/DomainLabel/DomainLabel.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DomainLabel/DomainLabel.interface.ts

minor(ui): support onUpdate for domain to skip default save behavior

---

ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py
ingestion/src/metadata/ingestion/source/database/column_type_parser.py
ingestion/tests/unit/topology/dashboard/test_superset.py

Fix #16958: column parser data type fix

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/APIEndpointRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/apis/APIEndpointResourceTest.java

Fix #17118: Elasticsearch HTTP Method Error in update_by_query; Fix: patch tags for request/response schema in ApiEndpoint

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Tour.spec.ts

This PR will fix the tour playwright test

test: fix tour playwright test

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/DataQuality.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TestSuiteMultiPipeline.spec.ts

Minor: Fixed AUT test for DQ and testSuiteMultiPipeline

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/UserTab/UserTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/UserTab/UserTab.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/Users.util.tsx

- I worked on removing the team column in the team details page, since  we are within a team, we don't need to know if they belong to other teams
- Fix the popover pointing from entire cell to the user only
Issue : 
Resolved : 
#
#

MINOR: Remove team column in team details page

---

ingestion/src/metadata/ingestion/source/database/column_type_parser.py
ingestion/src/metadata/profiler/processor/sampler/sampler_factory.py
ingestion/src/metadata/profiler/processor/sampler/sqlalchemy/azuresql/sampler.py
ingestion/src/metadata/utils/sqa_utils.py

Fixes #17377 
- Add support for "HIERARCHYID" column type in column_type_parser.py
- Register AzureSQLSampler for "AzureSQLConnection" in sampler_factory.py
- Fixes PyODBC error for HIERARCHYID and GEOGRAPHY, skips columns that are UNDETERMINEDTYPE / UNKNOWN
#
#

Fixes #17377: HIERARCHYID & GEOGRAPHY pyodbc error

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/DataAssetsWorkflow.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchIndexSink.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchIndexSink.java

- Removes redundant construction
- add open search
#
#

Add Opensearch max payload Size

---

openmetadata-ui/src/main/resources/ui/src/pages/Persona/PersonaDetailsPage/PersonaDetailsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/Persona/PersonaDetailsPage/PersonaDetailsPage.tsx

- I worked on adding breadcrumb in persona detail page
https://github.com/user-attachments/assets/3bb1efe2-ad11-4627-ac0d-a79bd50864a9
#
#

MINOR: added breadcrumb in persona detail page

---

ingestion/src/metadata/ingestion/lineage/models.py

MINOR: Add Unity Catalog Lineage Dialect

---

ingestion/src/metadata/ingestion/source/database/databricks/metadata.py

I worked on query change update affected in fetching table_type module
#
#

MINOR: databricks describe table query update

---

openmetadata-service/src/main/java/org/openmetadata/service/security/SecurityUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BasicAuthenticator.java
openmetadata-service/src/main/java/org/openmetadata/service/security/auth/LdapAuthenticator.java

Login configurations are not being fetched properly, which results in missing the latest data from the database.
#
#

[MINOR] Fix retrieval of loginConfiguration

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/AdvanceSearchProvider/AdvanceSearchProvider.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx
openmetadata-ui/src/main/resources/ui/src/components/NavBar/nav-bar.less
openmetadata-ui/src/main/resources/ui/src/components/common/DomainLabel/DomainLabel.component.tsx
openmetadata-ui/src/main/resources/ui/src/hooks/useDomainStore.ts
openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchClassBase.ts
openmetadata-ui/src/main/resources/ui/src/utils/DomainUtils.tsx

minor domain feedbacks

---

openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

Update Max Payload Size for OpenmetadataOperations

---

conf/openmetadata.yaml
openmetadata-service/src/main/java/org/openmetadata/service/security/saml/SamlSettingsHolder.java
openmetadata-service/src/test/resources/openmetadata-secure-test.yaml
openmetadata-spec/src/main/resources/json/schema/security/client/samlSSOClientConfig.json

- Added config option to set SP private key 
- Added config to control XML validation 
#
#

Update SAML to have signed Messages

---

ingestion/src/metadata/ingestion/source/database/postgres/usage.py

Fixes #16454 
I worked on correct sql query syntax for wild card
Use filter condition with `query like '%db_name%'`
#
#

Fix #16454: usage query filter condition error

---

openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/saml/azure.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/menu.md

Fix Broken Doc for SAML

---

openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/saml/azure.md

Broken Verification Link on Page

---

ingestion/src/metadata/ingestion/source/database/dbt/constants.py
ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py
ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
ingestion/src/metadata/ingestion/source/database/dbt/models.py
ingestion/tests/unit/test_dbt.py
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/ingestion/workflows/dbt/setup-multiple-dbt-projects.md

Added support to process multiple dbt run_results.json for a single dbt project
#
#

MINOR: Added support to process multiple dbt run_results.json for a single dbt project

---

ingestion/src/metadata/ingestion/source/pipeline/dagster/metadata.py
ingestion/src/metadata/ingestion/source/pipeline/dbtcloud/metadata.py

Fixes #17367 
- Change Timestamp None to Current Time noting pending pipeline
- dbtCloud & Dagster
#
#

Fixes #17367: PipelineStatus Timestamp None not allowed

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TestSuiteMultiPipeline.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Tour.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestCases.spec.ts

Minor: fixed failing test case in AUT part 1
#
#

Minor: fixed failing test case in AUT part 1

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/processors/WebAnalyticsEntityViewProcessor.java
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/processors/WebAnalyticsUserActivityProcessor.java

On Data Insights Pipeline we encounter a few issues when users are missing such as
```
Failed processing events from [WebAnalyticsWorkflow] Event Data Source 2024-08-14: org.openmetadata.service.exception.SearchIndexException: WebAnalytics User Activity Processor Encounter Failure: user instance for 211f7e0c-77e0-49ec-bdd3-9547211216bb not found
```
For the WebAnalytics part we moved to fetching deleted users as well.
For DataAssets we are logging when a User is not present anymore and thus we can't fetch its team instead of failing.
#
#

MINOR: Fix Missing Users errors on Data Insights Pipeline

---

openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/metaPilotAppConfig.json

MINOR - Config to PATCH metapilot descriptions if empty

---

openmetadata-spec/src/main/antlr4/org/openmetadata/schema/EntityLink.g4
openmetadata-ui/src/main/resources/ui/src/utils/EntityLink.test.ts

#17437 Data Quality UI can't display `type` as column name

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TagRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v131/MigrationUtil.java

- updates the listBefore and listAfter methods to use both name and id (in a json object form) as cursor for pagination instead of only name.
- pagination changes have only been done where name was used as cursor, and not in methods where different column were used as cursor
```
{
"name": "name value of Entity",
"id": "id value of Entity"
}
```
#
#

Updated pagination logic  to use  both name and id as cursors in listBefore and listAfter methods

---

ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py

In case the full the path of the dbt files has path like below 
```
/home/dbt_proj/dbt_run_results_multi/manifest.json
/home/dbt_proj/dbt_run_results_multi/run_result.json
```
The current logic is parsing up all the files(manifest and run_result both) as run_results.json due to there being `run_results` in the path.
The PR fixes this issue by matching the name of the files instead the entire path
#
#

MINOR: Update the logic match correct file names for the dbt files

---

openmetadata-ui/src/main/resources/ui/playwright/utils/customizeLandingPage.ts
openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamsHeaderSection/TeamsHeadingLabel.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamsHeaderSection/TeamsInfo.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamsHeaderSection/TeamsInfo.test.tsx

- I worked on remove edit button from team type group
- fix the edit button color difference on the panel
Issue : 
Resolved : 
#
#

MINOR: remove edit button from team type group and fix color of button

---

ingestion/src/metadata/data_quality/validations/column/sqlalchemy/columnValueLengthsToBeBetween.py
ingestion/src/metadata/data_quality/validations/column/sqlalchemy/columnValuesToBeBetween.py
ingestion/tests/integration/conftest.py
ingestion/tests/integration/mysql/conftest.py
ingestion/tests/integration/mysql/data/mysql/README.md
ingestion/tests/integration/mysql/test_data_quality.py
ingestion/tests/integration/mysql/test_metadata.py
ingestion/tests/integration/mysql/test_profiler.py
ingestion/tests/integration/postgres/conftest.py
ingestion/tests/integration/postgres/test_data_quality.py
ingestion/tests/integration/sql_server/conftest.py
ingestion/tests/integration/trino/conftest.py
openmetadata-docs/content/v1.3.x/connectors/ingestion/workflows/data-quality/tests.md

Fixes https://github.com/open-metadata/OpenMetadata/issues/17413
#
#

Fixes 17413: Fix one sided tests for columnValueLengthsToBeBetween and columnValuesToBeBetween

---

openmetadata-docs/content/partials/v1.5/deployment/upgrade/upgrade-prerequisites.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/how-to-guides/data-insights/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/menu.md

Updated documentation to remove stale links. Added entry for Backward Incompatible Change for Data Insights.
#
#

MINOR: Removed stale links. Updated Backward Incompatible Changes

---

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/EntityImport/EntityImport.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/ToastUtils.ts

Show Import Export Button only if it has All or Edit All permissions for Glossary Term.
Updated handling of 403 toast errors. Only GET request errors should be treated silently.
Show Fqn for Glossary terms in suggestions.
#
#

fix import export permissions

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

- I worked on what's new for 1.4.8
#
#

what's new for 1.4.8

---

openmetadata-service/src/main/java/org/openmetadata/service/security/auth/LdapAuthenticator.java

Fix Ldap Username issue

---

bootstrap/sql/migrations/native/1.5.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.5.0/postgres/schemaChanges.sql

Fix #17177 -  add index on extension_index table

---

bootstrap/sql/migrations/native/1.5.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.5.0/postgres/schemaChanges.sql

Fix entity_extension owner update query
#
#

MINOR: Fix entity_extension owner update query

---

ingestion/src/metadata/ingestion/source/dashboard/qlikcloud/client.py
ingestion/tests/unit/topology/dashboard/test_qlikcloud.py
ingestion/tests/unit/topology/database/test_bigquery.py

follow up of https://github.com/open-metadata/OpenMetadata/pull/16885
Qlik cloud connection passes with bad configuration dues to test function returning generator
https://github.com/user-attachments/assets/df3d351f-21fd-44a0-8a45-979f36252f42
#
#

MINOR: fix qlikcloud test connection

---

ingestion/src/metadata/ingestion/source/storage/gcs/client.py
ingestion/src/metadata/ingestion/source/storage/gcs/metadata.py
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/database/bigquery/yaml.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/connectors/storage/gcs/yaml.md

1. update docs using gcp credentials in path.
2. updated example `clientIt` in docs
3. fixed client to work with implicit project
4. fixed workflow to warn about missing buckets
#
#

MINOR: fix gcs for release 1.5.0

---

bootstrap/sql/migrations/native/1.5.0/mysql/schemaChanges.sql
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/automations/WorkflowResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/automations/WorkflowResourceTest.java

MINOR - Fix list API for automation workflows

---

ingestion/src/metadata/great_expectations/action.py

Fixes #16560
- Remove `root` when accessing fqn of test suite entity reference
#
#
Bug fix

GEN 1015 - Fix GX OM action 

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

I worked on changing what's new release date for 1.4.8
#
#

MINOR: change what's new release date for 1.4.8

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataInsightSettings.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/AppContainer/AppContainer.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppDetails/ApplicationsClassBase.ts
openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppSchedule/AppSchedule.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/AppInstall/AppInstall.component.tsx

fix(ui): move schedule option logic to class base

---

openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java

Allows to configure seaerch class as Extension 
#
#

Adds Ability to Extend search functionalty

---

openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java

Add UnmappedType Sort Field

---

openmetadata-service/src/main/java/org/openmetadata/csv/CsvUtil.java
openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryResourceTest.java

Fixes #15529 
1. Adds validation in EntityRepository validateOwners to restrict to either team or owners. Individual owners up to 5
2. Fix reviewers formatting while export/import in glossary
#
#

Fix #15529: Glossary CSV import with empty synonyms

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java

Keep Status ActiveError on Job Run

---

openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java

Init Search Repo in Entity

---

openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java

Add Page Type filter

---

openmetadata-docs/content/v1.4.x/deployment/security/basic-auth/index.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/security/basic-auth/index.md

Updating Admin Principal information
#
#

Doc: Updating Admin Principal information

---

.github/teams.yml

cc @Prajwal214 @ayush-shah 
#
#

MINOR - Add Prajwal to safe to test list

---

ingestion/tests/integration/conftest.py
ingestion/tests/integration/postgres/test_lineage.py

added test cases for lineage with and without includeDDL
follows https://github.com/open-metadata/OpenMetadata/pull/17450 
#
#

MINOR: lineage tests

---

ingestion/src/metadata/clients/domo_client.py
ingestion/src/metadata/ingestion/source/dashboard/domodashboard/metadata.py
ingestion/src/metadata/ingestion/source/pipeline/domopipeline/metadata.py

Domo dashbaord and pipeline connector wasn't ingesting the records due to a Pydantic issue related with the Pydantic v2 migration.
This PR addresses the issues by casting the ids to string where needed.
#
#

MINOR: Fix pydantic v2 issues with domo

---

bootstrap/sql/migrations/native/1.5.0/mysql/schemaChanges.sql
bootstrap/sql/migrations/native/1.5.0/postgres/schemaChanges.sql
openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
openmetadata-service/src/main/resources/json/data/app/SearchIndexingApplication.json
openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/SearchIndexingApplication.json
openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json

Add Api Service, Collection and Endpoint in reindex app

---

ingestion/src/metadata/ingestion/source/dashboard/metabase/client.py
ingestion/src/metadata/ingestion/source/pipeline/fivetran/client.py

Fixes Http 404 not found due to extra trailing space
#
#

Minor: Remove trailing slash from FivetranClient base URL

---

openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseIndex.java

do not index failed rows sample
Failed samples have undetermined types and are an unnecessary burden on the search index.
#
#

MINOR: do not index failed sample for test case

---

conf/openmetadata.yaml
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/util/JsonUtils.java
openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/ReindexingUtil.java
openmetadata-service/src/main/resources/elasticsearch/indexMapping.json

fix domain propagation apiCollection -> apiEndpoint, remove default cluster alias, catch exceptions while counting the docs for reindex
#
#

 fix domain propagation apiCollection -> apiEndpoint, remove default cluster alias, catch exceptions while counting the docs for reindex

---

openmetadata-service/src/main/resources/elasticsearch/en/api_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/dashboard_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/database_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/messaging_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/metadata_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/mlmodel_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/pipeline_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/search_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/en/storage_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/api_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/dashboard_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/database_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/messaging_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/metadata_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/mlmodel_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/pipeline_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/search_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/storage_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/api_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/dashboard_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/database_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/messaging_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/metadata_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/mlmodel_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/pipeline_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/search_service_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/storage_service_index_mapping.json

Fixes - Added lowercase_normalizer in serviceType for missing entities  to have consistency in aggregation results
#
#

Minor : Added lowercase_normalizer in serviceType for missing entities  to have consistency in aggregation results

---

openmetadata-docs/content/partials/v1.5/deployment/upgrade/upgrade-prerequisites.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/deployment/database-connection-pooling.md
openmetadata-docs/content/v1.5.x-SNAPSHOT/menu.md

Adding Database Connection Pool in for v1.5.0
#
#

Doc: Adding Database Connection Pool in for v1.5.0

---

openmetadata-docs/content/partials/v1.4/releases/latest.md
openmetadata-docs/content/v1.4.x/deployment/docker/index.md
openmetadata-docs/content/v1.4.x/menu.md
openmetadata-docs/content/v1.4.x/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.4.x/releases/releases/index.md

Updating Release Docs for 1.4.8
#
#

Doc: Updating Release Docs for 1.4.8

---

ingestion/tests/integration/postgres/test_lineage.py

add test for cell with 100k characters
#
#

MINOR: add test case for cell with 100k characters

---

openmetadata-docs/content/v1.4.x/menu.md

Fixing Broken Menu in v.1.4 Docs
#
#

Doc: Fixing Broken Menu in v.1.4 Docs

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java

Our timestamps are fixed at the start of day. This change aims to be able to retrieve the first day correctly.
#
#

MINOR: Add Fix for timestamps

---

ingestion/src/metadata/ingestion/connections/builders.py

Fix none password issue for mysql and postgresql databases
#
#

MINOR: Fix none password issue for mysql and postgresql databases

---

ingestion/src/metadata/ingestion/source/database/redshift/connection.py
ingestion/src/metadata/ingestion/source/database/redshift/queries.py

The SELECT statement was taking a big chunk of time, whereas the grant check command works wonders.
We could eventually port this to other systems as well if they support it
#
#

MINOR - Speed up redshift test connection

---

openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/ServiceConfig/ConnectionConfigForm.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/ServiceConfig/ConnectionConfigForm.tsx
openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesListPage/PoliciesListPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesListPage/RolesListPage.tsx

- change the hostip card style description to alert for better visibility
- UI improvement in case no description is there in roles and policy
Issue : 
Resolved : 
#
#

MINOR: change the hostip card style description to alert for better visibility

---

openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java

Due to the way we handle the Tier when it is absent, we need a workaround to calculate it.
Should be properly addressed on next release.
#
#

MINOR: Add a Workaround for the Tier Calculation on DataInsightsReport

---

openmetadata-ui/src/main/resources/ui/cypress/common/Entities/ServiceBaseClass.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Services/MysqlIngestionClass.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Owner.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/IncidentManager.spec.ts
openmetadata-ui/src/main/resources/ui/src/utils/RouterUtils.ts

I worked on fixing the breaking edit ingestion page when special character is present in the FQN
**Before:**
https://github.com/user-attachments/assets/b1248226-d9a9-4a59-a29a-d5ea7f9aa6d9
**After:**
https://github.com/user-attachments/assets/77de1834-e8b2-4bcf-8971-5648fbc948b5
#
#

Minor: Fix the encoding issue on edit ingestion page

---

ingestion/src/metadata/ingestion/source/database/column_type_parser.py
ingestion/src/metadata/ingestion/source/database/postgres/converter_orm.py
ingestion/src/metadata/ingestion/source/database/postgres/metadata.py
ingestion/src/metadata/ingestion/source/database/postgres/metrics.py
ingestion/src/metadata/ingestion/source/database/postgres/types/money.py
ingestion/src/metadata/profiler/metrics/static/mean.py
ingestion/src/metadata/profiler/orm/functions/median.py
ingestion/src/metadata/profiler/orm/registry.py
ingestion/src/metadata/utils/importer.py
ingestion/tests/integration/postgres/test_profiler.py
openmetadata-spec/src/main/resources/json/schema/entity/data/table.json

add support for profiling of money type
Fixes https://github.com/open-metadata/OpenMetadata/issues/17539
#
#

Fixes 17539: add support for money data type profiling for postgres

---

ingestion/src/metadata/profiler/interface/sqlalchemy/profiler_interface.py
ingestion/tests/cli_e2e/database/bigquery/bigquery.yaml
ingestion/tests/cli_e2e/database/bigquery_multiple_project/bigquery_multiple_project.yaml
ingestion/tests/cli_e2e/database/datalake_s3/datalake_s3.yaml
ingestion/tests/cli_e2e/database/hive/hive.yaml
ingestion/tests/cli_e2e/database/mssql/mssql.yaml
ingestion/tests/cli_e2e/database/mysql/mysql.yaml
ingestion/tests/cli_e2e/database/oracle/oracle.yaml
ingestion/tests/cli_e2e/database/postgres/postgres.yaml
ingestion/tests/cli_e2e/database/redshift/redshift.yaml
ingestion/tests/cli_e2e/database/snowflake/snowflake.yaml
ingestion/tests/cli_e2e/database/vertica/vertica.yaml

FIX - profiler interface system metrics validation & e2e YAML includeDDL

---

openmetadata-ui/src/main/resources/ui/cypress/common/CustomizeLandingPageUtils.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Owner.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Tier.ts
openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Users.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/IncidentManager.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/QueryEntity.spec.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/DataQualityAndProfiler.spec.ts

I worked on fixing following cypress tests:
#
#

Minor: Fix failing cypress tests in main

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardDataModelRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java

Fixes Some parts of #17566
#
#

Fix Get Parent

---

openmetadata-ui/src/main/resources/ui/src/components/DataInsight/DataInsightChartCard.tsx
openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.tsx

Fixes 
- Remove Percentage from Tooltip & Y Axis
- Add % for Right side summary header
#
#

fix(ui): count vs percentage value shows correctly

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/CustomThemeConfig.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/ApiCollectionClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/DatabaseClass.ts

This PR fixes issues in Playwright’s automated testing for API collection, database interactions, and custom theme configurations to ensure consistent and reliable test results across all environments.

test: fix playwright AUT for API collection, database and custom theme config

---

openmetadata-ui/src/main/resources/ui/cypress/common/Services/RedshiftWithDBTIngestionClass.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/constants.ts
openmetadata-ui/src/main/resources/ui/cypress/constants/service.constants.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Tour.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/ApiCollectionClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/DatabaseClass.ts
openmetadata-ui/src/main/resources/ui/src/pages/AppearanceConfigSettingsPage/AppearanceConfigSettingsPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/AppearanceConfigSettingsPage/appearance-config-settings-page.less
openmetadata-ui/src/main/resources/ui/src/styles/app.less

This PR will take care of the playwright AUT failures

test: fix playwright AUT failures

---

openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v150/MigrationUtil.java

fixes
```
[java.lang.ClassCastException: class org.postgresql.util.PGobject cannot be cast to class java.lang.String 
(org.postgresql.util.PGobject is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 
'bootstrap')]
```
#
#

FIX - PG Migration for automator

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataInsight.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/KPIWidget/KPIWidget.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/KPIWidget/KPIWidget.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/KPIPage/KPIMock.mock.ts

- I worked on fixing KPI data not showing in widget
Issue : 
Resolved : 
#
#

MINOR: fix KPI data not showing in widget

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BasicAuthenticator.java

[FIX] Fix IsEmailServiceEnabled.

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/user/UserClass.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts

Add playwright for sorted owners
#
#

add playwright for sorted owners

---

openmetadata-ui/src/main/resources/ui/cypress/common/Services/RedshiftWithDBTIngestionClass.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/dataInsightApp.ts

fixed Minor AUT failure
- DBT 
- Data insight application
#
#

Minor: Fixed AUT failure

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/ApiCollection.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/ApiCollectionClass.ts

This PR addresses the owner propagation end-to-end test for the API collection entity.

fix(e2e): api collection owner propagation

---

common/pom.xml
openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-clients/pom.xml
openmetadata-dist/pom.xml
openmetadata-service/pom.xml
openmetadata-shaded-deps/elasticsearch-dep/pom.xml
openmetadata-shaded-deps/opensearch-dep/pom.xml
openmetadata-shaded-deps/pom.xml
openmetadata-spec/pom.xml
openmetadata-ui/pom.xml
pom.xml

Bump Openmetadata Snapshot version

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java

- Don't allow Email to be Updated
#
#

[MINOR] Fix Email Updates

---

docker/docker-compose-quickstart/Dockerfile
ingestion/Dockerfile
ingestion/operators/docker/Dockerfile
ingestion/pyproject.toml
openmetadata-airflow-apis/pyproject.toml

Fixes Version Mismatch error
#
#

MINOR: Bump Ingestion and Dockerfile versions

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java

MINOR: Fix delete lineage in case of override lineage enabled

---

.github/workflows/playwright-mysql-e2e.yml
.github/workflows/playwright-postgresql-e2e.yml

ci(e2e): speed up playwright with 2 machines

---

openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreSearchCard/ExploreSearchCard.tsx

show tier tag with styles

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

minor(ui): what's new for 1.5.2

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Features/IncidentManager.spec.ts
openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/IncidentManagerPageHeader/IncidentManagerPageHeader.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/OwnerLabel/OwnerLabel.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.interface.ts

https://github.com/user-attachments/assets/5a113ac2-464d-4399-ae4c-b3573ae7a143
#
#

Minor: added support for edit assign button in incident manager

---

openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/TestCaseForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ProfilerSettingsModal/ProfilerSettingsModal.tsx

- Added search support in column fields
https://github.com/user-attachments/assets/7e180b01-6d42-4408-838e-6e125efe2ee0
https://github.com/user-attachments/assets/f391ef67-04b1-445d-bc4e-83349a1776b7
- Fixed dropdown overlapping on button issue
#
#

Minor: fixed styling issue for DQ

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

minor: update what's new for 1.5.2

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/domains/DataProductResource.java
openmetadata-service/src/main/resources/elasticsearch/en/data_products_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/jp/data_products_index_mapping.json
openmetadata-service/src/main/resources/elasticsearch/zh/data_products_index_mapping.json
openmetadata-spec/src/main/resources/json/schema/api/domains/createDataProduct.json
openmetadata-spec/src/main/resources/json/schema/entity/domains/dataProduct.json
openmetadata-ui/src/main/resources/ui/playwright/constant/customProperty.ts
openmetadata-ui/src/main/resources/ui/playwright/constant/settings.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Domains.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/domain/DataProduct.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/Entity.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/DataModelDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsDetailsPage/DataProductsDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsPage/DataProductsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.interface.ts
openmetadata-ui/src/main/resources/ui/src/constants/GlobalSettings.constants.ts
openmetadata-ui/src/main/resources/ui/src/constants/PageHeaders.constant.ts
openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx
openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsClassBase.ts

Fixes #16498
https://github.com/user-attachments/assets/d40ca6df-06f4-408c-bdd8-1db1a4b0b7b2
#
#

Fixes #16498 : Support custom properties for Data Products

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataInsightReportApplication.spec.ts

fix(e2e): remove data insight report if already present

---

.github/workflows/sync-docs-v1.yml

I messed up the syntax when preparing the new steps
#
#

FIX - Docs sync workflow syntax

---

ingestion/src/metadata/ingestion/source/database/athena/models.py

MINOR: Fix Athena lineage models

---

common/pom.xml
openmetadata-clients/openmetadata-java-client/pom.xml
openmetadata-service/pom.xml
pom.xml

Upgrade dependencies for release 1.6

---

openmetadata-docs/content/v1.5.x/connectors/database/sap-hana/yaml.md
openmetadata-docs/content/v1.5.x/connectors/ingestion/great-expectations.md
openmetadata-docs/content/v1.5.x/connectors/pipeline/openlineage/index.md
openmetadata-docs/content/v1.5.x/how-to-guides/index.md
openmetadata-docs/content/v1.5.x/how-to-guides/user-guide-data-users/data-asset-tabs.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/sap-hana/yaml.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/ingestion/great-expectations.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/pipeline/openlineage/index.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/index.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/user-guide-data-users/data-asset-tabs.md

Updated the broken links in v.1.5.x
#
#

Docs: Updated the broken links in v.1.5.x

---

openmetadata-docs/content/v1.4.x/connectors/messaging/kafka/index.md
openmetadata-docs/content/v1.4.x/connectors/messaging/kafka/troubleshooting.md
openmetadata-docs/content/v1.4.x/connectors/messaging/kafka/yaml.md
openmetadata-docs/content/v1.4.x/connectors/messaging/redpanda/index.md
openmetadata-docs/content/v1.4.x/connectors/messaging/redpanda/yaml.md
openmetadata-docs/content/v1.4.x/main-concepts/metadata-standard/schemas/entity/services/connections/messaging/kafkaConnection.md
openmetadata-docs/content/v1.5.x/connectors/messaging/kafka/index.md
openmetadata-docs/content/v1.5.x/connectors/messaging/kafka/troubleshooting.md
openmetadata-docs/content/v1.5.x/connectors/messaging/kafka/yaml.md
openmetadata-docs/content/v1.5.x/connectors/messaging/redpanda/index.md
openmetadata-docs/content/v1.5.x/connectors/messaging/redpanda/yaml.md
openmetadata-docs/content/v1.5.x/main-concepts/metadata-standard/schemas/entity/services/connections/messaging/kafkaConnection.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/messaging/kafka/index.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/messaging/kafka/troubleshooting.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/messaging/kafka/yaml.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/messaging/redpanda/index.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/messaging/redpanda/yaml.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/main-concepts/metadata-standard/schemas/entity/services/connections/messaging/kafkaConnection.md

Updated Kafka Schema Registry Config Broken Link
#
#

Docs: Updated Kafka Schema Registry Config Broken Link

---

openmetadata-ui/src/main/resources/ui/cypress/common/Utils/Users.ts

I worked on fixing permission cypress due to missing file
#
#

fix permission cypress due to missing file

---

openmetadata-ui/src/main/resources/ui/src/components/AppBar/Suggestions.tsx
openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.tsx

show display name in suggestions with fqn

---

ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py

Fixed dbt cloud run_results.json name
#
#

MINOR: Fixed dbt cloud run_results.json name

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/APICollectionRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/apis/APICollectionResource.java

Going through the code I found a few typos on the APICollection documentation and methods.
This PR aims to fix those
#
#

Fixes some things on the APICollection

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/yarn.lock

minor(ui): align dependency version to fix vulnerabilities

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/support/glossary/Glossary.interface.ts
openmetadata-ui/src/main/resources/ui/playwright/support/glossary/GlossaryTerm.ts
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx

fix expand all operation on terms page

---

openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/RedshiftWithDBTIngestionClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ServiceBaseClass.ts
openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/SnowflakeIngestionClass.ts

minor(test): fix ingestion related flaky for aut

---

pom.xml

Minor: remove unused dependency

---

openmetadata-docs/content/v1.4.x/how-to-guides/data-insights/cost-analysis.md

make cost analysis as collate only

---

ingestion/tests/integration/ometa/test_ometa_table_api.py
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
openmetadata-service/src/main/java/org/openmetadata/service/util/RestUtil.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java

- Add TS validation on DQ and profiler data ingestion
#
#
Bug fix

GEN-1333 Add TS validation on DQ and Porfiler data ingestion

---

openmetadata-ui/src/main/resources/ui/cypress/common/CustomizeLandingPageUtils.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityVersionUtils.tsx

- Fix cypress for the Customize Landing 
- Fix breaking of entity version page, due to empty oldText or newText
#
#

fix cypress for the Customize Landing  and EntityVersion page

---

.github/workflows/sync-docs-v1.yml

In Collate docs we need all the partials to be inside `content/`, since we only have one single version.
In this PR, we're preparing some pre-cooking of the files so that it matches the final repo expectations
#
#

MINOR - Fix Collate docs sync for partials

---

ingestion/setup.py
ingestion/src/metadata/pii/ner.py
ingestion/src/metadata/pii/scanners/ner_scanner.py
ingestion/tests/unit/pii/test_ner_scanner.py

MINOR - Bump Presidio Analyzer and validate support for legal entities

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/PersonaFlow.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/UserDetails.spec.ts

- Fix userDetails flaky test while search
- PersonFlow, create persona flaky test
#
#

fix userDetails and personFlow flaky test

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts

minor(ui): what's new updated for 1.5.3

---

ingestion/tests/unit/profiler/pandas/test_custom_metrics.py

- fix typo in test region name causing error in botocore-1.35.x
#
#
Bug fix

MINOR - Fix region typo in test

---

openmetadata-docs/content/v1.5.x/deployment/upgrade/index.md

fix upgrade docs version

---

ingestion/src/metadata/ingestion/source/database/redshift/utils.py

MINOR: Fix redshift ingestion warnings in case of ext table

---

openmetadata-service/src/main/resources/json/data/testConnections/pipeline/matillion.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/pipeline/matillionConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/pipelineService.json

Add Matillion Pipeline Connector
#
#

MINOR: Add Matillion test connection and schema for pipeline service

---

openmetadata-docs/content/v1.5.x/collate-menu.md
openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/airflow.md
openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/credentials.md
openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/gcs-composer.md
openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/github-actions.md
openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/index.md
openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/mwaa.md
openmetadata-docs/content/v1.5.x/getting-started/day-1/index.md
openmetadata-docs/content/v1.5.x/getting-started/index.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/airflow.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/credentials.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/gcs-composer.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/github-actions.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/index.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/mwaa.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/index.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/index.md

DOCS - Getting Started Collate

---

ingestion/src/metadata/profiler/metrics/system/system.py

MINOR: fix typo in profiler metric

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Permission.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/IncidentManager.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestCases.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestSuite.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/testCases.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/QualityTab/QualityTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/QualityTab/QualityTab.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/TableProfiler.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/TableProfilerProvider.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/TableProfilerProvider.tsx

Fixes #1654 
https://github.com/user-attachments/assets/775ebff0-374c-4553-b0cb-57d28d5644c0
#
#

#1654 Add a search field in Profiler & Data Quality

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/EntityVersionPages.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/ServiceEntityVersionPage.spec.ts

playwright: fixed failing aut of 1.5.4

---

openmetadata-docs/content/partials/v1.5/releases/latest.md
openmetadata-docs/content/v1.5.x/menu.md
openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.5.x/releases/releases/index.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/quick-start/local-docker-deployment.md
openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md

Updating the latest Release v.1.5.3
#
#

Docs: Updating the latest Release v.1.5.3

---

ingestion/src/metadata/ingestion/source/database/bigquery/connection.py
ingestion/src/metadata/ingestion/source/database/redshift/connection.py
ingestion/src/metadata/ingestion/source/database/redshift/queries.py
ingestion/src/metadata/ingestion/source/database/redshift/utils.py
ingestion/src/metadata/ingestion/source/database/snowflake/connection.py
ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
ingestion/src/metadata/pii/scanners/ner_scanner.py

MINOR: Optimise Snowflake Test Connection

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TeamsDragAndDrop.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts

playwright: fixed AUT test for 1.5.4
#
#

playwright: fixed AUT test for 1.5.4

---

openmetadata-ui/src/main/resources/ui/jest.config.js
openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/yarn.lock

fix(ui): security vulnerability for ui package.json

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestCases.spec.ts

Playwright: fixed AUT testCases spec
#
#

Playwright: fixed AUT testCases spec

---

openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
openmetadata-ui/src/main/resources/ui/playwright/utils/activityFeed.ts

I worked on playwright improvement in Activity Feed spec
#
#

playwright improvement in activity feed spec
