- ingestion/src/metadata/pii/scanners/ner_scanner.py
- ingestion/src/metadata/workflow/base.py
- ingestion/src/metadata/workflow/profiler.py
- We were logging the PII processor even when it was disabled, which can easily create confusion.
- also, noticed that a new version of spacy/presidio gives quite some more WARNINGs that we should be able to ignore. Managed the logging level
- Added the `updated` field in the workflow timer, so we can track the full status we manage
#
#
> GEN-1410 - Improve PII Logging information

- .github/actions/setup-openmetadata-test-environment/action.yml
- .github/workflows/py-tests-postgres.yml
- ingestion/tests/integration/ometa/test_ometa_es_api.py
Adding CI and skipping paginate search tests until they are fixed for opensearch
#
#
> GEN-1494 - Add CI for py-tests with Postgres and Opensearch

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tags.spec.ts
> Playwright: fixed Tags AUT test

- ingestion/examples/sample_data/datasets/tables.json
> MINOR: add children to array of struct

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/IncidentManager.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tags.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/incidentManager.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/task.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/team.ts
- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/mention/mentionSuggestions.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/mocks/Task.mock.ts
- openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/miscAPI.ts
- openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.ts
We have completely removed the suggestion API with this ([Issue-15768: Support Metric Entity](https://github.com/open-metadata/OpenMetadata/pull/17680)) PR, so we're also removing its usage from the UI.
#
#
> minor: remove suggestion api from UI

- openmetadata-docs/content/partials/v1.5/releases/latest.md
- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md
Updating the latest Release v.1.5.3
#
#
> Docs: Updating the latest Release v.1.5.4

- ingestion/tests/integration/alationsink/test_alationsink.py
Fixed AlationSink pytest for postgres CI
#
#
> MINOR: Fixed AlationSink pytest for postgres CI

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
- Fix glossary request tag/description failure
- Skip the lineage playwright, @karanh37 will take care of the failure in it
#
#
> fix failing playwright test

- ingestion/LICENSE
Add Collate License to the ingestion framework
#
#
> Docs - Ingestion License

- ingestion/setup.py
add pin for deltalake<0.20 to avoid https://github.com/delta-io/delta-rs/commit/ad35eda7983385c3011f8ae87afc24456791cd9e#diff-f81b8b91e9721dc0a3235b6674a57c0700153b92b59f3988d357950a9c8c4760R1142-R1144
#
#
> MINOR: fix(ingestion): deltalake

- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
> MINOR: Apply multi threading in View Lineage Processing

- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
> minor(ci): e2e playwright limit install dependacy step

- ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py
- ingestion/tests/integration/ometa/test_ometa_lineage_api.py
> FIX #17896 - Python lineage SDK to work with Uuid & FQN models

- ingestion/src/metadata/ingestion/sink/metadata_rest.py
- ingestion/src/metadata/pii/processor.py
- ingestion/src/metadata/profiler/api/models.py
- ingestion/src/metadata/profiler/processor/core.py
- ingestion/src/metadata/profiler/processor/models.py
- ingestion/tests/integration/orm_profiler/test_pii_processor.py
- ingestion/tests/unit/profiler/test_profiler_models.py
- We will fetch the sample data from the source if we have `generateSampleData` or `processPIISensitive` as `true`
- We will only store the sample data if `generateSampleData` is enabled
#
#
> GEN-996 - Allow PII Processor without storing Sample Data

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/IngestionPipelineIndex.java
- Adds applicationt type to schema 
#
#
> Fix Automator Search

- openmetadata-ui/src/main/resources/ui/src/utils/NavbarUtilClassBase.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/NavbarUtilClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/NavbarUtils.tsx
- I worked on supported class base for navbar utils items
#
#
> supported class base for navbar utils items

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataInsight.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/RedshiftWithDBTIngestionClass.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UserProfileIcon/UserProfileIcon.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/UserDataUtils.ts
> fix(ui): GEN-1523 exclude defaultPersona if not present in personas

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/activityFeed.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/customProperty.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
I worked on fixing aut activity feed for 1.5.5
#
#
> fix aut activity feed for 1.5.5

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
This PR will include the what's new content for release 1.5.5
> what's new for 1.5.5

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> update what's new 1.5.5

- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
- openmetadata-ui/src/main/resources/ui/webpack.config.prod.js
- openmetadata-ui/src/main/resources/ui/yarn.lock
> revert for "fork-ts-checker-webpack-plugin": "6.5.0",

- openmetadata-ui/src/main/resources/ui/playwright/utils/team.ts
I worked on adding the missing search team function
#
#
> Playwright AUT : added the missing searchTeam function

- ingestion/setup.py
> MINOR: pin testcontainers by minor version

- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/webpack.config.prod.js
- openmetadata-ui/src/main/resources/ui/yarn.lock
Fixes Build timeout
Webpack 5 is using more memory in our CI due to memory leaks found [here](https://github.com/webpack/webpack/issues/13550) 
The CI builds are failing due to this. We don't want to increase the resources and as a result we are adding this fix.
The problem is with jest worker leaking memory.
For fix, we have made resolution of terser webpack plugin to 5.1.1 which uses older version of jest worker v26.
#
#
> update webpack dependencies

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Table.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/dataInsightApp.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/RedshiftWithDBTIngestionClass.ts
> fix(test): playwright flaky tests

- openmetadata-docs/content/partials/v1.5/releases/latest.md
- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/deployment/docker/index.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.5.x/sdk/python/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/sdk/python/index.md
Updating latest release v1.5.5 in Docs
#
#
> Docs: Updating latest release v1.5.5 in Docs

- openmetadata-docs/content/v1.5.x/how-to-guides/data-quality-observability/quality/tests-yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/tests-yaml.md
> MINOR: add note about comparing across different connectors

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/PersonaFlow.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataInsightSettings.spec.ts
> fix flaky persona and dataInsightSettings spec

- ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
Minor: fix lineage & queries in dbt versionless
#
#
> Minor: fix lineage & queries in dbt versionless

- openmetadata-docs/content/v1.4.x/connectors/metadata/alation/index.md
- openmetadata-docs/content/v1.4.x/connectors/metadata/alation/yaml.md
- openmetadata-docs/content/v1.4.x/connectors/storage/adls/index.md
- openmetadata-docs/content/v1.4.x/connectors/storage/adls/yaml.md
- openmetadata-docs/content/v1.5.x/connectors/database/synapse/index.md
- openmetadata-docs/content/v1.5.x/connectors/database/synapse/troubleshooting.md
- openmetadata-docs/content/v1.5.x/connectors/database/synapse/yaml.md
- openmetadata-docs/content/v1.5.x/connectors/metadata/alation/index.md
- openmetadata-docs/content/v1.5.x/connectors/metadata/alation/yaml.md
- openmetadata-docs/content/v1.5.x/connectors/storage/adls/index.md
- openmetadata-docs/content/v1.5.x/connectors/storage/adls/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/synapse/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/synapse/troubleshooting.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/synapse/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/metadata/alation/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/metadata/alation/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/ml-model/vertexai/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/ml-model/vertexai/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/pipeline/matillion/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/pipeline/matillion/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/storage/adls/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/storage/adls/yaml.md
Fixes for collate only docs changes
connectors considered are listed below:
- storage/adls
- database/synapse
- metadata/alation
- pipeline/matillion
- mlmodel/vertexai
#
#
> MINOR: collate docs changes

- ingestion/setup.py
> MINOR: MSTR connector import fix

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
> MINOR: DI Missing Dashboard Description Status

- openmetadata-docs/content/v1.5.x/how-to-guides/getting-started/day-1/database-service-setup.md
- openmetadata-docs/content/v1.5.x/how-to-guides/getting-started/day-1/index.md
- openmetadata-docs/content/v1.5.x/how-to-guides/getting-started/index.md
- openmetadata-docs/content/v1.5.x/how-to-guides/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/getting-started/day-1/database-service-setup.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/getting-started/day-1/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/getting-started/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/index.md
I worked on updating getting started by adding tile on how to guides page along with some rectification.
#
#
> Docs: Updating Getting Started

- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/property-value.less
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- Fix Enum chip styling as per mock
- Fix the timestamp and time-interval input form error message
Issue :
Resolved : 
#
#
> MINOR: fix custom property enum styling fix

- openmetadata-docs/content/v1.5.x/deployment/bare-metal/index.md
Add a note regarding Postgres on Azure created after September 2024.
#
#
> [DOCS] Add a note for Postgres MD5 missing on Azure

- openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
Added api for test case result
#
#
> Minor: added test case result api

- openmetadata-docs/content/v1.5.x/how-to-guides/data-insights/cost-analysis.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-insights/cost-analysis.md
> Docs: Fixing Broken Links

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> minor: update whats new for 1.5.6

- ingestion/src/metadata/ingestion/source/metadata/alationsink/metadata.py
- ingestion/tests/integration/alationsink/test_alationsink.py
- Add displayName(OM) to title(Alation) if it is present else update name(OM)
- For columns add datatypeDisplayName(OM) to datatype(Alation) if it is present else update name(OM)
- Added support for foreign keys
#
#
> GEN-1672: AlationSink connector improvements

- ingestion/src/metadata/ingestion/source/dashboard/mstr/client.py
MSTR Ingestion fails because the base url generated is in this format `http://ip//api/path`  which contains an extra `/` this pr aims to removing that extra `/`
#
#
> MINOR: MSTR URI Fix

- openmetadata-docs/content/partials/v1.5/releases/latest.md
- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/deployment/docker/index.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.5.x/sdk/python/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/sdk/python/index.md
I worked on updating the documentation latest release references to 1.5.6
#
#
> Minor: Update latest release references to 1.5.6

- ingestion/Dockerfile
- ingestion/Dockerfile.ci
- ingestion/operators/docker/Dockerfile
- ingestion/operators/docker/Dockerfile.ci
Depending on how we are building the Docker Images, a couple commands would fail as the syntax was not compatible with SH.
This PR aims to fix that by changing the syntax to a more portable one.
It was tested locally by building and running the ingestion dockerfile using zsh, bash and sh.
#
#
> MINOR: Fix Ingestion Dockerfile Compatibility by changing IF syntax

- openmetadata-docs/content/v1.5.x/connectors/database/salesforce/yaml.md
- openmetadata-docs/content/v1.5.x/connectors/storage/s3/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/salesforce/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/storage/s3/yaml.md
> MINOR: Fix s3 & salesforce yaml docs

- ingestion/src/metadata/ingestion/source/database/glue/metadata.py
- ingestion/src/metadata/ingestion/source/database/glue/models.py
> Fix #18070: Add support for glue database descriptions

- ingestion/operators/docker/Dockerfile
- ingestion/operators/docker/Dockerfile.ci
fixes: PostgreSQL installation in Ingestion Docker
I worked on PostgreSQL installation in Ingestion Docker.
#
#
> fix: PostgreSQL installation in Ingestion Docker

- ingestion/src/metadata/pii/scanners/ner_scanner.py
Fixes the protected namespace warning which comes up during ingestion
```
python3.10/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_name" in NLPEngineModel has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
warnings.warn(
```
#
#
> Minor: Resolve protected namespace warning

- ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py
> MINOR: Fix superset arrray/struct sub-datatype error

- ingestion/pyproject.toml
- ingestion/src/metadata/data_quality/validations/runtime_param_setter/table_diff_params_setter.py
- ingestion/tests/integration/data_quality/conftest.py
- ingestion/tests/integration/data_quality/test_data_diff.py
- ingestion/tests/unit/metadata/data_quality/test_table_diff_param_setter.py
fixed table diff url to include database in all cases
#
#
> MINOR: fix(table-diff): support cross database

- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/CollectionRegistry.java
- Scan only in accepted packages
#
#
> Fix performance issue

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java
Fixes #18121 
Empty Connection Overwrite bug fixed, empty connection can now be edited and saved with new connection details.
#
#
> Fixes #18121: Empty Connection Overwrite Logic

- openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/CustomHtmlRederer/CustomHtmlRederer.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/RichTextEditorPreviewer.test.tsx
Fixes #18043
- For RichTextEditor and RichTextEditorPreviewer components, enable code block highlighting by using CodeMirror.  
|before|after|
|:-----:|:---:|
|![Screenshot 2024-10-06 at 23 15 25](https://github.com/user-attachments/assets/7faa49e8-6273-4a96-9784-00643ea7054b)|![Screenshot 2024-10-06 at 23 18 47](https://github.com/user-attachments/assets/0d81b19d-eefc-45b6-91af-9e6ecbbcb192)|
- This is accomplished by using CoreMirror's [runMode](https://codemirror.net/5/doc/manual.html#addon_runmode) in CustomHTMLRenderer.
- We are considering to put a document with sample code in the entity description as design information for the data. It helps a lot if the code is highlighted.
- Added unit tests …
> Fix #18043: Highlight code blocks in RichTextEditor

- openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx
- openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
- openmetadata-ui/src/main/resources/ui/webpack.config.prod.js
This PR include the changes for resolving the css files for reactdatagrid module
> minor: update webpack config to resolve reactdatagrid css

- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v160/MigrationUtil.java
fixes
```
Error migrating app extension [{appid=fb781068-88a9-4c7a-af96-d81212f53819, json={"appId": "fb781068-88a9-4c7a-af96-d81212f53819", "status": "success", "endTime": 1716487200996, "runType": "Custom", "startTime": 1716487200283, "timestamp": 1716487200283, "scheduleInfo": {"cronExpression": "0 0/1 * * *", "scheduleTimeline": "Custom"}, "executionTime": 713, "successContext": {"stats": null}}}] due to [java.lang.ClassCastException: class org.postgresql.util.PGobject cannot be cast to class java.lang.String (org.postgresql.util.PGobject is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')]
```
caught by AUTs
#
#
> FIX - PG AppName Migration

- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/yarn.lock
> fix(ui): security deps for cookie package

- openmetadata-ui/src/main/resources/ui/src/utils/i18next/i18nextUtil.ts
Fixes: enable Persian lang selection in dropdown
#
#
> chore(ui): support Persian language option

- .github/workflows/sync-docs-v1.yml
Earlier we were maintaining the documentation content in the `publish` branch of `docs-v1`, making it harder to manage the content and logical changes. Hence, the content will be moved to the `main` branch. 
The ultimate goal would be to not have the content in the `docs-v1` repository, which needs to be taken care of in the future.
#
#
> Update docs sync workflow to push content to main branch

- ingestion/setup.py
We have updated the `pyiceberg` version to 0.5.1, as using higher versions caused the following error:
```
metadata.utils.importer.DynamicImportException: Cannot import metadata.ingestion.source.database.iceberg.connection.get_connection due to No module named 'mypy_boto3_glue'
```
We have created a task to update the code for compatibility with newer versions of `pyiceberg` in the 1.7 release.
#
#
> Minor: Updated pyiceberg version to 0.5.1

- SECURITY.md
- openmetadata-docs/content/v1.4.x/connectors/pipeline/glue-pipeline/yaml.md
- openmetadata-docs/content/v1.5.x/connectors/pipeline/glue-pipeline/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/pipeline/glue-pipeline/yaml.md
Fixes Yaml discrepancy with the types for glue pipeline
#
#
> MINOR: [Doc] Glue Pipeline Yaml fixed, Security.md Modified

- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v160/MigrationUtil.java
Using the wrong column name
#
#
> FIX - App Extension Migration

- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppMarketPlaceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
Orders Apps Resource to be of higher order in registration, since the Metapilot and Onboarding uses the repository for getting app information
#
#
> [OnBoarding] Order Apps Order on Resource 

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Entity/Task/TaskTab/TaskTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/KPIList.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- Added space for metapilot in DataInisght KPI Table
- Make the Task Modal not closeable on outside click .
#
#
> PLAYWRIGHT: fix activityFeed and DataInsight AUT playwright test

- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/visualize.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
I worked on rectifying data quality links.
#
#
> Docs: Data Quality link correction

- openmetadata-docs/content/v1.5.x/how-to-guides/data-quality-observability/quality/adding-test-suites.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/adding-test-suites.md
I worked on correcting suite link
#
#
> Docs: Suite link correction

- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderElasticsearchFormatUtils.js
**Before**:
https://github.com/user-attachments/assets/8fb676e1-e0f5-492c-a999-a1ef593b62f6
**After**:
https://github.com/user-attachments/assets/7b5193c0-448f-4174-bb32-97619aa5cdc7
#
#
> Minor: Fix the automator page breaking when no source is selected

- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
I worked on updating collate menu.
#
#
> Docs: Updating Collate Menu

- openmetadata-docs/content/v1.5.x/how-to-guides/data-governance/automation/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-governance/automation/index.md
> Docs: Fixing Automation Docs

- openmetadata-docs/content/v1.5.x/quick-start/getting-started/day-1/database-service-setup.md
- openmetadata-docs/content/v1.5.x/quick-start/getting-started/day-1/index.md
- openmetadata-docs/content/v1.5.x/quick-start/getting-started/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/quick-start/getting-started/day-1/database-service-setup.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/quick-start/getting-started/day-1/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/quick-start/getting-started/index.md
Updating getting started Docs
#
#
> Docs: Updating getting started Docs

- openmetadata-docs/content/v1.4.x/menu.md
- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
I worked on removing the unnecessary lines in menu.md and collate-menu.md
#
#
> Minor: Remove unwanted items in menu.md

- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
Removing Broken Menu Links
#
#
> Docs: Removing Broken Menu Links

- openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx
Fixes: Comparison should be done when we have version info to avoid unwanted popups
#
#
> fix(ui): compare version only if version is set

- bootstrap/sql/migrations/native/1.6.0/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.6.0/postgres/schemaChanges.sql
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-ui/src/main/resources/ui/src/pages/ServicesPage/ServicesPage.tsx
- Add Apps data store , needs for Onboarding app
#
#
> [OnBoardingApp] Add apps data store

- ingestion/tests/integration/integration_base.py
- ingestion/tests/integration/ometa/test_ometa_es_api.py
Adding some more tests around ES pagination
#
#
> TEST - Add ES pagination with multiple filters

- ingestion/src/metadata/data_quality/validations/runtime_param_setter/table_diff_params_setter.py
fixed url for table diff when using service connection
running e2e manually: https://github.com/open-metadata/OpenMetadata/actions/workflows/py-cli-e2e-tests.yml?query=branch%3Asnowflake-e2e-tests
#
#
> MINOR: fix table diff url

- bootstrap/sql/migrations/native/1.6.0/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.6.0/postgres/postDataMigrationSQLScript.sql
Migrate ApiServiceType from REST to Rest
#
#
> Migrate ApiServiceType

- openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertsRuleEvaluator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/util/FormatterUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/events/subscription/AlertsRuleEvaluatorResourceTest.java
- Fix alerts for test suites
- Rename alert resource test file to match class name
#
#
Bug fix
> GEN 1654 - Fix Alerts for Test Suites

- openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/ConfigurationReader.java
- Read runtime config when running any application method
- Read config from resource instead of file
#
#
> GEN-1793: fix app config from resource

- ingestion/tests/cli_e2e/test_cli_mysql.py
Minor: Fixed mysql E2E
Updated Table count
#
#
> Minor: Fixed mysql E2E

- bootstrap/sql/migrations/native/1.6.0/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.6.0/postgres/postDataMigrationSQLScript.sql
- openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v160/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v160/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v160/MigrationUtil.java
> Migrations fixes for #17967

- openmetadata-ui/src/main/resources/ui/src/components/AppContainer/app-container.less
- openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/left-sidebar.less
- I worked on fixing the dark border shown at the bottom of the navbar.
- Removed the white blank space from logo and first Menu item.
Issue Reason:  The Header ANTD component has a dark background color and only after the screen re-sizing, we were able to see it due to some difference in pixel height or the screen that contains this pixel width. 
Issue : 
Resolved : 
https://github.com/user-attachments/assets/811be1c2-b709-41eb-bcbd-3735988e52ff
#
#
> MINOR: fix dark border shown in navbar

- ingestion/setup.py
https://github.com/looker-open-source/sdk-codegen/issues/1518
#
#
> MINOR: fix(looker): exclude version

- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
> Minor: Add deleteEntityByFQNPrefix

- openmetadata-docs/content/v1.5.x/Metapilot/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/Metapilot/index.md
This should show the youtube video which currently is not being shown
#
#
> [MINOR] Doc: Fix Metapilot Video Link

- openmetadata-docs/content/v1.5.x/deployment/backup-restore-metadata.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/backup-restore-metadata.md
- added missing privileges for MySQL. These were required when I was restoring from sandbox.
- using the [COMPOSE_FILE](https://docs.docker.com/reference/cli/docker/compose/#set-up-environment-variables) for a more ergonomic shell experiences
#
#
> docs(restore): database restore clarifications

- ingestion/src/metadata/parsers/json_schema_parser.py
- ingestion/tests/unit/test_json_schema_parser.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/17062
#
#
> [GEN-962] Add array children support for json schema parser

- ingestion/src/metadata/ingestion/source/database/pinotdb/connection.py
- ingestion/src/metadata/ingestion/source/database/pinotdb/metadata.py
> Fix #17963: Fix PinotDB Ingestion

- .github/workflows/maven-sonar-build.yml
> minor(ci): enable sonar CI on release branch

- openmetadata-ui/src/main/resources/ui/playwright/utils/task.ts
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/activity-feed-tab.less
- openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx
- Added loader on Open and Closed task count until data is fetched from API.
- This will avoid the wrong count to be displayed to user until the API got resolved.
- This will fix the AUT failure for the count since we are awaiting on the loader to be removed
https://github.com/user-attachments/assets/61adb1de-bd56-4175-bb30-ea6d0ed436f9
#
#
> MINOR: added loader in activity feed open and closed count

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
- ingestion/tests/unit/resources/datasets/manifest_v8.json
- ingestion/tests/unit/test_dbt.py
Fixed below dbt invalid tag name error
```
metadata.ingestion.ometa.client.APIError: Invalid name "22
```
#
#
> [GEN-1194] Fixed dbt invalid tag name error

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestSuiteResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java
- added domain param for search list filter domain filtering
#
#
Bug fix
> MINOR: add domain params for test suite search list filter

- ingestion/src/metadata/ingestion/source/dashboard/quicksight/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/quicksight/models.py
Fixes #18186 
Fixes below errors as well.
UnboundLocalError: cannot access local variable 'data_source_resp' 
pydantic_core._pydantic_core.ValidationError: 1 validation error for DescribeDataSourceResponse
#
#
> Fixes #18186: Quicksight Ingestion Error handled

- ingestion/src/metadata/ingestion/source/database/couchbase/metadata.py
- ingestion/src/metadata/ingestion/source/database/couchbase/queries.py
> MINOR: Fix Couchbase columns not fetched

- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
Fix if Dashboard is soft deleted, the charts of that dashboard shouldn't be visible in search.
#
#
> GEN-1662 : Fix - on dashboard soft delete, chart should not be visible in search

- ingestion/src/metadata/ingestion/source/database/pinotdb/metadata.py
> MINOR: Fix pinotdb col. datatype error

- ingestion/src/metadata/ingestion/source/database/salesforce/metadata.py
Fixes: We are using query to get description in salesforce tables.
```
"query/?q=SELECT+Description+FROM+EntityDefinition+WHERE+QualifiedApiName='{table_name}'"
```
In many cases it's not able to get description from this(possible in free tier version), so we can get that from table/describe API.
#
#
> MINOR: salesforce table description from label if not through query

- bootstrap/sql/migrations/native/1.5.7/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.5.7/postgres/postDataMigrationSQLScript.sql
added migrations for data diff test definition
#
#
> MINOR: chore(data-diff): added migrations

- openmetadata-ui/src/main/resources/ui/src/utils/CSV/CSV.utils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/CSV/CSV.utils.tsx
This PR improves the CSV parsing for custom properties by adding extra check for updated values.
> minor: improve csv parsing for custom properties

- openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationProcess.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationProcessImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/MigrationFile.java
Add an option to load data migration code from Collate repo.
#
#
> Minor: Add an option to execute data migrations in ext migrations

- openmetadata-service/src/main/java/org/openmetadata/service/search/EntityBuilderConstant.java
We are increasing the MAX_AGGREGATE_SIZE in search, to address the issue in Elasticsearch of  missing certain databases or schemas when the number of aggregations in bucket exceeds the current MAX_AGGREGATE_SIZE of 50.
#
#
> Minor : increase MAX_AGGREGATE_SIZE in search

- openmetadata-spec/src/main/resources/json/schema/type/basic.json
Minor : remove EnumWithDescriptions in basic.json
#
#
> Minor : remove EnumWithDescriptions in basic.json

- openmetadata-service/src/main/resources/elasticsearch/indexMapping.json
- Remove test case result index from all index
#
#
> MINOR - Remove test case result index from all index

- openmetadata-docs/content/v1.5.x/connectors/metadata/alation/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/metadata/alation/index.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Metadata/Alation.md
Added Alation Connector side panel docs
#
#
> MINOR: [DOCS] Added Alation Connector side panel docs

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
- added test suites field back
#
#
> MINOR: added testSuite field back to lineage response

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> What's new in 1.5.7

- openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx
Fixes: Refresh logic isn't being triggered due to cleanup
- Due to an additional cleanup call, the Timer that we are setting one time got cleaned upon any deps change of the `handleSuccessfulLogin` function
- It was introduced with #16762 
- Since the timer is set only once we need to clean it up on the same effect and not with any other effect
#
#
> fix(ui): cleaning up timer for refresh token

- ingestion/src/metadata/workflow/application.py
- ingestion/tests/unit/workflow/test_application_workflow.py
Recent PR broke the init of external apps (only used in Collate, and py CI indeed fails there). Adding a test init here and a fix to be covered
#
#
> MINOR - Validate app runner init

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java
- Update testSuite field on test suite creation in table index
#
#
Bug fix
> MINOR - live index on test suite creation

- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java
- openmetadata-service/src/main/resources/elasticsearch/en/table_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/table_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/table_index_mapping.json
- openmetadata-spec/src/main/resources/json/schema/api/data/createTable.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
> MINOR: Add location path to table entity

- openmetadata-docs/content/partials/v1.5/releases/latest.md
- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/deployment/docker/index.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.5.x/sdk/python/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/sdk/python/index.md
Updating latest release to v1.5.7
#
#
> Docs: Updating latest release to v1.5.7

- openmetadata-docs/content/partials/v1.5/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.6/connectors/database/connectors-list.md
I worked on adding SAP ERP in connectors list.
#
#
> Docs: Adding SAP ERP in Connectors List

- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
I worked on fixing 404 by making changes in menu
#
#
> Docs: Getting Started Corrected in Menu

- openmetadata-service/src/main/resources/elasticsearch/en/table_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/table_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/table_index_mapping.json
> MINOR: Fix LocationPath Index

- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ExplorePage/ExplorePage.interface.ts
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderUtils.ts
Persist value when passed from form values
#
#
> persist es query value in query builder widget

- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-governance/domain-&-data-products/domain.md
I worked on fixing Goverance images.
#
#
> Docs: Image Fix for Goverance

- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/AppInstall/AppInstall.component.tsx
Fixes 
Loads entity type value from schema value and updates the widget options.
Changed the width of configuration on AppInstall page.
#
#
> query builder improvements

- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
I worked on Basic Auth Removal from Collate Menu.
#
#
> Docs: Basic Auth Removal from Collate Menu

- ingestion/src/metadata/ingestion/source/dashboard/mode/client.py
Fixes Mode Test Connection failure, not a blocker
#
#
> MINOR: Mode test connection returns data in dict instead of json

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/DataAssetsWorkflow.java
> MINOR: Not Include Soft Deleted Assets in DI

- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseResolutionStatusIndex.java
- openmetadata-service/src/main/resources/elasticsearch/en/test_case_resolution_status_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/test_case_resolution_status_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/test_case_resolution_status_index_mapping.json
- added test case domain, tags and owners field to search incident index
#
#
Improvement
> MINOR: added test case domain, tags and owners field to search incident index

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
added Whats new content for 1.5.8
#
#
> Minor: Whats new content for v1.5.8

- openmetadata-ui/src/main/resources/ui/src/components/AppRouter/withAdvanceSearch.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/query-builder-widget.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
- openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderUtils.tsx
> add query builder widget ui improvements

- openmetadata-docs/content/v1.5.x/how-to-guides/user-guide-data-users/custom.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/user-guide-data-users/custom.md
This PR will update the list of supported custom property types in the documentation.
> docs: update list of supported custom properties type

- ingestion/src/metadata/ingestion/source/database/couchbase/metadata.py
- ingestion/src/metadata/ingestion/source/database/couchbase/models.py
> MINOR: Couchbase Secondary Index Fix

- openmetadata-service/src/main/java/org/openmetadata/service/resources/types/TypeResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/SchemaFieldExtractor.java
> Minor: Fix custom properties API and add cache

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UsersTab/UsersTab.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/UserListPage/UserListPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/Users.util.tsx
- Supported displayName field in User listing page
- Change the add user to add admin in Admin Page
#
#
> MINOR: supported displayName field in User listing page

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchDynamicChartAggregatorInterface.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchLineChartAggregator.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchDynamicChartAggregatorInterface.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchLineChartAggregator.java
- openmetadata-spec/src/main/resources/json/schema/dataInsight/custom/dataInsightCustomChartResult.json
- openmetadata-spec/src/main/resources/json/schema/dataInsight/custom/lineChart.json
> GEN-1664: DI Make Horizontal Axis Configurable

- openmetadata-docs/content/partials/v1.5/connectors/pipeline/connectors-list.md
- openmetadata-docs/content/partials/v1.6/connectors/pipeline/connectors-list.md
Adding dbt Cloud in connector list
#
#
> Docs: Adding dbt Cloud in connector list

- openmetadata-service/src/main/java/org/openmetadata/service/exception/OMErrorPageHandler.java
> Add Cache-Control and Pragma Header

- openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
Even if the app is not scheduled, we need the Ingestion Pipeline to be deployed and triggered on demand.
#
#
> MINOR - None schedules still need Ingestion Pipelines

- ingestion/src/metadata/ingestion/source/database/doris/metadata.py
Fixes module docstring in doris metadata module (drive by finding)
#
> Fixes: docstring in the Doris metadata module

- bootstrap/sql/migrations/native/1.5.9/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.5.9/postgres/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.6.0/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.6.0/postgres/postDataMigrationSQLScript.sql
Moving post migration script from https://github.com/open-metadata/OpenMetadata/pull/18072
#
#
> MINOR - Move appName migration to 1.5.9

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/team.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/miscAPI.ts
- openmetadata-ui/src/main/resources/ui/src/utils/UserDataUtils.ts
- fix organization data show in teams data after search
- fix the expand icon being visible on group team type after search
Issue: 
https://github.com/user-attachments/assets/35169279-a6c3-40f3-b25b-edf8759738c3
Resolved : 
https://github.com/user-attachments/assets/e6c30387-ebf7-482e-9554-971ff83f5f5b
#
#
> MINOR: fix organization data show in teams data after search

- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-service/pom.xml
- openmetadata-service/src/main/java/org/openmetadata/csv/CsvUtil.java
- pom.xml
> Update dependencies for release 1.6

- openmetadata-spec/src/main/antlr4/org/openmetadata/schema/EntityLink.g4
> Update EntityLink.g4, remove entities from EntityLink parser

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> added whats new for 1.5.9

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
> Parallelize the search indexing process

- openmetadata-ui/src/main/resources/ui/src/components/Settings/CustomProperty/AddCustomProperty/AddCustomProperty.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/CustomProperty/EditCustomPropertyModal/EditCustomPropertyModal.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Services.constant.ts
- openmetadata-ui/src/main/resources/ui/src/styles/components/select.less
Fixes: user unable to add more custom-property for enum type
- Limit height for enum select so that it doesn't occupy full view port 
- Hide dropdown as it's not required via passing `open` as `false`
https://github.com/user-attachments/assets/77be76a7-4a98-4788-8d99-95c62e2aa09b
#
#
> fix(ui): unable to add more enum values for enum cp

- openmetadata-ui/src/main/resources/ui/src/pages/GlobalSettingPage/GlobalSettingPage.tsx
Update settings tab with the latest values fetched
#
#
> fix: update settings tab with proper values

- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/TableConstraints.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/TableConstraintsModal/TableConstraintsModal.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/TableConstraintsModal/table-constraint.style.less
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseSchemaClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseSchemaDetailsUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
- I worked on revamping table constraint modal design
#
#
> MINOR: revamp table constraint modal design

- openmetadata-docs/content/partials/v1.5/releases/latest.md
- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md
> DOCS - Prep 1.5.9 release

- ingestion/pyproject.toml
- ingestion/src/metadata/ingestion/source/database/snowflake/profiler/profiler.py
- ingestion/src/metadata/ingestion/source/database/snowflake/profiler/system.py
Fix after https://github.com/open-metadata/OpenMetadata/pull/18322
E2E run https://github.com/open-metadata/OpenMetadata/actions/workflows/py-cli-e2e-tests.yml?query=branch%3Afix-snowflake-profiler
#
#
> MINOR Fix snowflake profiler by using case-insensitive strings

- .github/workflows/py-cli-e2e-tests.yml
Fix a bug in how the `DEBUG` flag is resolved for python e2e workflow.
#
#
> MINOR: fix debug resolution in e2e python github workflow

- openmetadata-ui/src/main/resources/ui/src/components/Classifications/ClassificationDetails/ClassificationDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/DataModelsTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuiteList/TestSuites.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/DatabaseSchema/DatabaseSchemaTable/DatabaseSchemaTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/QualityTab/QualityTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppRunsHistory/AppRunsHistory.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Bot/BotListV1/BotListV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable/IngestionListTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Services.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/UserTab/UserTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/NextPrevious/NextPrevious.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/NextPrevious/NextPrevious.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/APICollectionPage/APIEndpointsTab.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/Application/ApplicationPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/CustomPageSettings/CustomPageSettings.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/KPIList.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/SchemaTablesTab.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/MarketPlacePage/MarketPlacePage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/MetricsPage/MetricListPage/MetricListPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/NotificationListPage/NotificationListPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ObservabilityAlertsPage/ObservabilityAlertsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/Persona/PersonaListPage/PersonaPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesListPage/PoliciesListPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesListPage/RolesListPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceMainTabContent.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceVersionPage/ServiceVersionMainTabContent.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedureTab.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/UserListPage/UserListPageV1.tsx
Fixes: Disabled Next / Prev / Page size change for any fetching operation to avoid dirty state of UI
- If user keeps clicking on Next / Prev button page number keep getting updated relevant API didn't make it since it will be skipped for ongoing API call.
https://github.com/user-attachments/assets/f8571db7-351b-468b-937b-8e8a256e167f
- Introduce a loading flag for Pagination component to determine if there's any on going Network req for data.
- If so block user from changing pagination
https://github.com/user-attachments/assets/5c41fcd1-d927-496b-a7ec-3af1ee416644
#
#
> fix(ui): block multiple paging req while fetching data

- openmetadata-docs/content/v1.5.x/deployment/ingestion/openmetadata.md
> Docs: Fixing Ingestion Docs

- openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchClassBase.ts
> add debounce on autocomplete in advanced search

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/team.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/OwnerLabel/OwnerLabel.component.tsx
Fixes encoding on teams assets page.
The problem was with & character.
#
#
> fix query encoding for team asset query

- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/query-builder-widget.less
Do not allow deleting of first rule.
Added conditions for empty query.
For empty query is should return empty string as output.
#
#
> fix empty rule state in query builder

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> update 1.5.10 whats new data

- openmetadata-docs/content/v1.5.x/deployment/azure-passwordless-auth.md
- openmetadata-docs/content/v1.5.x/menu.md
> docs: Add Docs for Azure Database Passwordless Backend Connection support

- ingestion/src/metadata/data_quality/validations/column/base/columnValuesToBeInSet.py
- fix inSet passed rows computation
#
#
Bug fix
> fix: pass row and result computation for inSet test

- openmetadata-docs/content/partials/v1.5/releases/latest.md
- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md
> DOCS - Prep 1.5.10 release

- .github/workflows/py-cli-e2e-tests.yml
> MINOR: revert e2e python job link

- openmetadata-service/src/main/java/org/openmetadata/service/search/EntityBuilderConstant.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
Fixes an issue with highlighting large text fields in OpenSearch where we were hitting a `max_analyzed_offset` error due to highlight size limits . 
**Solution :** 
Setting `max_analyzed_offset` directly in the `HighlightBuilder` at the query level
**Error Message:**
```
The length of [description] field of doc in the index has exceeded [1000000] - maximum allowed to be analyzed for highlighting.
```
**Both OpenSearch and Elasticsearch have slightly different ways to set this:**
ElasticSearch:
OpenSearch : 
- **Elasticsearch** uses `hb.maxAnalyzedOffset(MAX_ANALYZED_OFFSET);`
- **OpenSearch** uses `hb.maxAnalyzerOffset(MAX_ANALYZED_OFFSET);`
**Solution from the discussion on these GitHub issues:**
- [OpenSearch Issue #553](https://github.com/opensearch-project/opensearch-java/issues/553) …
> Set max_analyzed_offset in HighlightBuilder to Fix Highlighting Errors for Large Fields

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/settings/SettingsCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/configuration/limitsConfiguration.json
- openmetadata-spec/src/main/resources/json/schema/configuration/lineageSettings.json
- openmetadata-spec/src/main/resources/json/schema/configuration/searchSettings.json
- openmetadata-spec/src/main/resources/json/schema/settings/settings.json
> Add LineageSettings to control Lineage Default depth, layers

- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseResolutionStatusIndex.java
- openmetadata-service/src/main/resources/elasticsearch/en/test_case_resolution_status_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/test_case_resolution_status_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/test_case_resolution_status_index_mapping.json
- Added `entityFQN` to incident index
#
#
Improvement
> MINOR: add entityFQN to incident index

- ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
- ingestion/src/metadata/utils/sqlalchemy_utils.py
> Fix #17778  : Databricks query run optimisation

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
> fix: Remove DataSourceFactory credentials from logs

- openmetadata-service/src/main/java/org/openmetadata/service/resources/system/SystemResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java
> Minor: lineage settings should be readable by all users

- ingestion/setup.py
> MINOR: Airflow dependency Fix

- openmetadata-service/pom.xml
The scope was set to test, so that dependency won’t be included when OSS is packaged and used on the Collate end.
#
#
> Fix #18497 Socket Dependency

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
I worked on adding what's new content for 1.5.11 release
#
#
> Add what's new for 1.5.11 release

- ingestion/setup.py
> MINOR: Fix pytest 3.11 taking 2hr

- ingestion/src/metadata/ingestion/source/database/common_db_source.py
> MINOR: Fix Materialised View Lineage

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/ChartWidgets/DataStatisticWidget/DataStatisticWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/ChartWidgets/DataStatisticWidget/data-statistic-widget.less
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
this is the supporting PR for overview tab improvement
#
#
> Minor: style improvement for DataStatisticWidget

- openmetadata-docs/content/partials/v1.6/connectors/api/connectors-list.md
- openmetadata-docs/content/v1.5.x/connectors/dashboard/microstrategy/yaml.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/api/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/dashboard/microstrategy/yaml.md
Fixing connector Docs for MicroStrategy
#
#
> Docs: Fixing connector Docs for MicroStrategy

- openmetadata-docs/content/partials/v1.5/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.6/connectors/database/connectors-list.md
I worked on correcting orders for connectors.
#
#
> Docs: Connectors Order Correction

- openmetadata-docs/content/partials/v1.5/connectors/dashboard/connectors-list.md
- openmetadata-docs/content/partials/v1.5/connectors/metadata/connectors-list.md
- openmetadata-docs/content/partials/v1.6/connectors/metadata/connectors-list.md
I worked on Connectors Missing Tile Addition.
#
#
> Docs: Connectors Missing Tile Addition

- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/roadmap/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/api/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/roadmap/index.md
Removing Roadmap from collate docs
#
#
> Docs: Removing Roadmap from collate docs

- openmetadata-service/src/main/java/org/openmetadata/service/resources/EntityResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseSchemaResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/glossary/GlossaryResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/database/DatabaseServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/TeamResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java
- openmetadata-ui/src/main/resources/ui/src/rest/glossaryAPI.ts
- openmetadata-ui/src/main/resources/ui/src/rest/teamsAPI.ts
> Add export apis back and new apis should be called exportAsync

- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
- ingestion/tests/integration/postgres/test_lineage.py
> MINOR: Fix table not found error

- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionCleanupJob.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionScheduler.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionResource.java
- openmetadata-spec/src/main/resources/json/schema/events/api/eventSubscriptionDiagnosticInfo.json
1. List records from latest to earliest.
2. Exclude unprocessed events from the listEvents API.
3. Refactor EventSubscriptionDiagnosticInfo.
#
#
> Debuggability Improvements and Fixes

- openmetadata-service/src/main/java/org/openmetadata/service/util/JsonUtils.java
> Minor: JsonUtils.extractValue shouldn't throw exceptions

- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
> Minor: Return pagination of for listHierarchy

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
In PostgreSQL, the DELETE statement does not support ORDER BY directly as part of the syntax.
We can use a WHERE clause with a subquery to specify the rows to delete in a specific order.
#
#
> MINOR: Fix PostgreSQL query for deleting old records

- ingestion/src/metadata/ingestion/source/dashboard/sigma/client.py
- ingestion/src/metadata/ingestion/source/dashboard/sigma/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/sigma/models.py
- openmetadata-spec/src/main/resources/json/schema/entity/data/dashboardDataModel.json
Added Sigma Column Level Lineage and Data Models
Here we are using the charts metadata to create a data model to create column level lineage
#
#
> GEN-1877 : Added Sigma Column Level Lineage and Datamodels

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/DataQuality.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomEdge.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomNodeV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/custom-node.less
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/entity-lineage.style.less
- openmetadata-ui/src/main/resources/ui/src/components/Lineage/Lineage.interface.ts
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.test.tsx
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/lineageAPI.ts
This is supporting PR for linage tracing for Data quality failure
#
#
> GEN-920 Minor: lineage data quality failure tracing support

- openmetadata-ui/src/main/resources/ui/src/components/Database/SampleDataTable/RowData.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/SampleDataTable/SampleDataTable.component.tsx
fixed sample data overlapping issue
Issue:
https://github.com/user-attachments/assets/252e48ab-3fb0-4d6c-86ed-b5ec0a71352c
Fix
https://github.com/user-attachments/assets/1242abb9-529f-4434-b8e7-a63b64dbbff1
#
#
> Minor: fixed sample data overlapping issue

- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
> Minor: add searchPageHierarchy method

- openmetadata-docs/content/partials/v1.5/deployment/configure-ingestion.md
- openmetadata-docs/content/partials/v1.6/deployment/configure-ingestion.md
I worked on updating one line in security section.
#
#
> Docs: One Line Updation in Security Section

- openmetadata-docs/content/v1.5.x/deployment/security/jwt-troubleshooting.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/security/jwt-troubleshooting.md
I worked on updating one section in Jwt troubleshooting doc.
#
#
> Docs: JWT Troubleshooting Doc Updation

- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/connectors/dashboard/powerbi-report-server/index.md
- openmetadata-docs/content/v1.5.x/connectors/dashboard/powerbi-report-server/yaml.md
> MINOR: mising menu for powerbi rs in 1.5

- openmetadata-service/src/main/java/org/openmetadata/service/search/security/ConditionCollector.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/security/RBACConditionEvaluator.java
- openmetadata-service/src/test/java/org/openmetadata/service/search/security/ElasticSearchRBACConditionEvaluatorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/search/security/OpenSearchRBACConditionEvaluatorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/util/TestUtils.java
> Search RBAC improvements

- openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationWorkflow.java
This change Fixes the Migration comparison issue to do comaprison on the basis of major . minor . patch
#
#
> Fix Version Comparison Logic

- bootstrap/sql/migrations/native/1.6.0/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.6.0/postgres/schemaChanges.sql
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v150/MigrationUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchSummaryCardAggregator.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchSummaryCardAggregator.java
- openmetadata-service/src/test/java/org/openmetadata/service/search/elasticsearch/ElasticSearchDynamicChartAggregatorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/search/opensearch/OpenSearchDynamicChartAggregatorTest.java
- openmetadata-spec/src/main/resources/json/schema/dataInsight/custom/summaryCard.json
> MINOR: Summary Card changes require for New UI

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts
> fix playwright lineage tests

- openmetadata-ui/src/main/resources/ui/src/pages/LogsViewerPage/LogsViewerPage.tsx
log viewer loading issue, and reduce repetitive api call
Issue:
https://github.com/user-attachments/assets/0ca7d2b6-5b6d-48a6-acb9-7eb3e31b0243
Solution:
https://github.com/user-attachments/assets/99073a32-216c-4622-949f-4791cecc3891
#
#
> GEN-2071 fix: logs loading issue and reduce repetitive api call

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
- openmetadata-service/src/main/resources/json/data/app/SearchIndexingApplication.json
- openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/SearchIndexingApplication.json
- openmetadata-spec/src/main/resources/json/schema/system/eventPublisherJob.json
- openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json
Make Queue Size Configurable
#
#
> Fix Unlimited Queue Size Issue

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/SetEntityCertificationTask.java
- openmetadata-spec/src/main/resources/json/schema/governance/workflows/elements/nodes/automatedTask/setEntityCertificationTask.json
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderElasticsearchFormatUtils.js
- JSON logic config needed for workflows
- Minor spacing change for Certification
- Added Enum for Certification task
#
#
> MINOR - fix config for workflows

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
> Fix Producer Sync Issue

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchDynamicChartAggregatorInterface.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/ElasticSearchLineChartAggregator.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchDynamicChartAggregatorInterface.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/OpenSearchLineChartAggregator.java
> DI - Add metric name in group name

- openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/internal/searchIndexingAppConfig.json
> MINOR: Add missing queueSize in searchIndexingAppConfig

- openmetadata-ui/src/main/resources/ui/playwright/constant/service.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/RedshiftWithDBTIngestionClass.ts
> MINOR: Fix Redshift DBT Playwright

- ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py
- ingestion/tests/integration/ometa/test_ometa_user_api.py
> MINOR: Fix user search - exclude bots

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
> Search Index Issues

- ingestion/src/metadata/data_quality/validations/models.py
- ingestion/src/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py
- ingestion/tests/integration/data_quality/test_data_diff.py
- ingestion/tests/unit/metadata/data_quality/test_data_diff.py
handle the sampling condition separately for the 2 tables allowing to apply sampling on columns with mismatching cases
#
#
> [GEN-1996] Data diff sample fix

- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/index.md
- openmetadata-docs/content/v1.5.x/how-to-guides/data-collaboration/knowledge-center.md
- openmetadata-docs/content/v1.5.x/how-to-guides/data-insights/cost-analysis.md
- openmetadata-docs/content/v1.5.x/how-to-guides/data-insights/custom-dashboard.md
- openmetadata-docs/content/v1.5.x/how-to-guides/data-quality-observability/incident-manager/root-cause-analysis.md
- openmetadata-docs/content/v1.5.x/how-to-guides/data-quality-observability/quality/overview.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-collaboration/knowledge-center.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-insights/cost-analysis.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-insights/custom-dashboard.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-quality-observability/incident-manager/root-cause-analysis.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/overview.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
I worked on updating collate only on cost analysis, custom dashboard, and knowledge center.
#
#
> Docs: Collate Only Correction

- openmetadata-service/src/main/resources/json/data/governance/workflows/GlossaryApprovalWorkflow.json
Improves Glossary Approval Workflow Name.
#
#
> MINOR: Update Glossary Approval Workflow name

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
- openmetadata-spec/src/main/resources/json/schema/system/eventPublisherJob.json
- openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json
Added Queue Size in Search Indexing Application Operation 
#
#
> Add Queue Size in Configuration

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
> Change Defaults Values for Indexing

- openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
> Minor: Fix Column Level Lineage export

- openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityNameModal/EntityNameModal.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/SanitizedInput/SanitizedInput.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/SanitizedInput/SanitizedInput.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/formUtils.tsx
Fixes https://github.com/open-metadata/OpenMetadata/security/advisories/GHSA-59gm-6h39-397f
This PR introduces SanitizedInput to handle content sanitization, preventing XSS vulnerabilities.
#
#
> Minor: Add SanitizedInput Component for Input Sanitization

- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/KPIWidget/kpi-widget.less
Fix style issue for KPI chart overflowing metrics
**Before:**
**After:**
#
#
> fix: overflowing metrics for kpi charts

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityDAO.java
> Removed Consumer

- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/how-to-guides/data-discovery/hierarchy.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/how-to-guides/data-discovery/hierarchy.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/menu.md
> Docs: Search Hierarchy Update

- openmetadata-docs/content/v1.5.x/collateai/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/collate-ai/index.md
I worked on Collate Image Path Rectification
#
#
> Docs: Collate Image Path Rectification

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
- handle potential null node in DQ failure lineage
#
#
Bug fix
> FIX: handle potential null node in DQ failure lineage

- ingestion/src/metadata/data_quality/runner/base_test_suite_source.py
- ingestion/src/metadata/utils/service_spec/service_spec.py
Until we get the right `source` from test suites from the UI
#
#
> MINOR - Fallback for testsuite imports

- ingestion/src/metadata/data_quality/validations/runtime_param_setter/param_setter_factory.py
> MINOR - Fix import

- openmetadata-ui/src/main/resources/ui/src/constants/Services.constant.ts
Hide Support field from service form
#
#
> Fixed: GEN-1984 Hide Support field from service form

- openmetadata-ui/src/main/resources/ui/src/components/PageHeader/PageHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/PageHeader/PageHeader.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/SearchRBACSettingsPage/SearchRBACSettingsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/app.less
- openmetadata-ui/src/main/resources/ui/src/styles/spacing.less
- Fix the switch placement
- Added beta tag
Issue :  
Resolved :  
#
#
> fix the switch placement and added beta tag

- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummaryGraph.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummaryCustomTooltip/TestSummaryCustomTooltip.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/date-time/DateTimeUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/date-time/DateTimeUtils.ts
updated time to human readable conversion function for y axis
https://github.com/user-attachments/assets/3b241e13-557e-47f7-bff6-96b4c8b8ff64
#
#
> Fix: time series of conversion of y-Axis in test case graph

- openmetadata-docs/content/v1.5.x/sdk/python/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/sdk/python/index.md
> Docs: Version Updation on Python SDK

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
- Add null check on source config and config
#
#
> MINOR : Add Null check for source config

- ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/client.py
> Fixes #18441 - Kafka Connect Ingestion Undecrypted Password

- ingestion/src/metadata/ingestion/source/database/athena/metadata.py
Minor: Fix Athena location path
#
#
> Minor: Fix Athena location path

- openmetadata-service/src/main/java/org/openmetadata/service/search/security/RBACConditionEvaluator.java
> Minor: Search RBAC, handle tier tags

- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/table-profiler.less
- openmetadata-ui/src/main/resources/ui/src/styles/components/code-mirror.less
Fix View definition tab, query display issue 
https://github.com/user-attachments/assets/4b80599d-b843-44b9-a169-ae22ffe85918
https://github.com/user-attachments/assets/bee4f9e9-dac3-4f4b-abde-1ef76bca04d5
#
#
> GEN-1529: Fix View definition tab, query display issue

- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/CommonEntitySummaryInfo/CommonEntitySummaryInfo.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.interface.ts
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
fixed failing incident manager test
#
#
> playwright: fixed failing incident manager test

- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableConstraints/TableConstraints.tsx
- I worked on modifying some test id in table constraints, to write better test
#
#
> MINOR: modify some test id in table constraints

- openmetadata-service/src/main/java/org/openmetadata/service/resources/EntityResource.java
Minor : update import csv response  message
#
#
> Minor : update import csv response  message

- ingestion/src/metadata/ingestion/source/dashboard/superset/db_source.py
> MINOR: Fix StackTraceError validation error - Superset

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/StoredProcedureRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/StoredProcedureResource.java
- openmetadata-spec/src/main/resources/json/schema/api/data/createStoredProcedure.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/storedProcedure.json
> MINOR: Add UDF support for SP - backend

- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/TableProfilerProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableProfilerUtils.ts
- openmetadata-ui/src/main/resources/ui/src/utils/date-time/DateTimeUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/date-time/DateTimeUtils.ts
> GEN-1224: fixed Profiler is not displaying correct time for table profile

- openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/ConnectionStepCard/ConnectionStepCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/ConnectionStepCard/connection-step-card.less
https://github.com/user-attachments/assets/314ba21e-21c2-45bd-bbb7-90536eb374aa
#
#
> GEN-2073: Not able to copy full logs from log viewer

- ingestion/src/metadata/data_quality/validations/runtime_param_setter/table_diff_params_setter.py
- ingestion/src/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py
- ingestion/tests/integration/data_quality/test_data_diff.py
- use both columns to calculate schema diff
#
#
> MINOR: fix(data-diff): get added columns

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/client.py
Minor: Fix Powerbi refresh token on expire
#
#
> Minor: Fix Powerbi refresh token on expire

- ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py
Minor: fix dbt ingest failed runs
`"status": "10" `is a optional param indicates to bring up only successful runs 
#
#
> Minor: fix dbt ingest failed runs

- openmetadata-ui/src/main/resources/ui/src/constants/docs.constants.ts
updated old docs link with new docs link
#
#
> Minor: updated docs link in the application

- openmetadata-ui/src/main/resources/ui/src/utils/ApplicationUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/ApplicationUtils.tsx
Sort data assets in alphabetical order for search indexing application
#
#
> Sort assets in search indexing app

- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/QualityTab/QualityTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/QualityTab/QualityTab.test.tsx
> GEN-2031: fix Add profiler configuration button in Data Quality tab

- openmetadata-ui/src/main/resources/ui/src/components/Explore/AdvanceSearchProvider/AdvanceSearchProvider.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/AddIngestion/Steps/ScheduleInterval.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/AddIngestion/Steps/ScheduleInterval.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
- openmetadata-ui/src/main/resources/ui/src/enums/AdvancedSearch.enum.ts
- openmetadata-ui/src/main/resources/ui/src/utils/JSONLogicSearchClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderUtils.tsx
Fixes needed for Workflow UI
#
#
> Workflow UI changes

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseResolutionStatusRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResolutionStatusResource.java
- Remove sample row failed on incident resolution
- Fix column summary not being computed for test suites
#
#
Bug fix
> MINOR: observability bugs

- ingestion/src/metadata/data_quality/builders/i_validator_builder.py
to allow monkeypatching in collate
#
#
> MINOR: fix: use importer as module

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppRunsHistory/AppRunsHistory.component.tsx
If endTime is not present, then calculate duration based on current time.
#
#
> fix: show duration based on current time if endTime is not there

- openmetadata-docs/content/v1.5.x/menu.md
> Docs: Fixing Broken Menu

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityTimeSeriesRepository.java
required for changes in collate
#
#
> MINOR feat: added getLatestRecord for extension

- openmetadata-docs/content/v1.6.x-SNAPSHOT/developers/contribute/developing-a-new-connector/develop-ingestion-code.md
I worked on Service Spec content updation
#
#
> Docs: Service Spec updation

- ingestion/src/metadata/ingestion/models/patch_request.py
- ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
- ingestion/src/metadata/utils/sqlalchemy_utils.py
> MINOR: Databricks LocationPath Update Fix

- ingestion/src/metadata/ingestion/source/database/snowflake/connection.py
> MINOR: Fix snowflake test connection on - in db name

- openmetadata-docs/content/v1.5.x/deployment/bare-metal/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/deployment/bare-metal/index.md
I worked on Airflow Version Update
#
#
> Docs: Airflow Version Update

- ingestion/src/metadata/ingestion/ometa/models.py
- ingestion/src/metadata/ingestion/ometa/ometa_api.py
- ingestion/src/metadata/utils/helpers.py
- ingestion/tests/integration/ometa/test_ometa_table_api.py
> MINOR - Fix clean_uri and add before pagination

- ingestion/setup.py
- ingestion/src/metadata/ingestion/lineage/parser.py
- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
- ingestion/src/metadata/ingestion/models/patch_request.py
- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
- ingestion/src/metadata/ingestion/source/database/snowflake/models.py
- ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
> MINOR: Snowflake UDF Lineage Support

- openmetadata-service/src/main/resources/json/data/EntityObservabilityFilterDescriptor.json
- openmetadata-ui/src/main/resources/ui/playwright/utils/observabilityAlert.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
Creates 1 alert per test case in the suite.
**UI:**
https://github.com/user-attachments/assets/89860fce-f61e-45f2-843b-26d44da205e3
#
#
> Add trigger option 'TestSuiteStatusUpdates' for TestSuite status changes

- openmetadata-docs/content/v1.5.x/sdk/python/ingestion/lineage.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/sdk/python/ingestion/lineage.md
I worked on Adding Import Entity Reference
#
#
> Docs: Adding Import Entity Reference

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomNode.utils.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/NodeChildren/NodeChildren.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/custom-node.less
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/entity-lineage.style.less
- I worked on updating lineage column with new design
New : 
https://github.com/user-attachments/assets/4d2a7e51-8e3d-47bd-98b0-55caeabf9177
Old :  
#
#
> MINOR: update lineage column with new design

- openmetadata-service/src/main/java/org/openmetadata/service/security/AuthenticationCodeFlowHandler.java
- On Refresh requests , google sso returns null for refresh tokens
- Null refresh tokens needs to be ignored 
#
#
> [SSO] Google returns null refresh token on Refresh requests

- openmetadata-ui/src/main/resources/ui/src/utils/CSV/CSVUtilsClassBase.tsx
This PR adds the changes to improve the encoding of column description and column glossary terms for CSV import.
> Minor: improve the CSV import encoding for column description and glossaryTerms

- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/releases/releases/index.md
I worked on updating collate in pipeline status widget.
#
#
> Docs: Updating Collate in Pipeline Status Widget

- openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreSearchCard/ExploreSearchCard.tsx
Moved the Domain tag before the Owner.
#
#
> MINOR: Reorder domain and owner tags

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
> Minor: removing logging on jdbcURL

- ingestion/src/metadata/ingestion/source/database/dbt/dbt_service.py
Minor: Fix dbt source file issue
dbt source file is not always available as it's optional
#
#
> Minor: Fix dbt source file issue

- ingestion/src/metadata/ingestion/source/dashboard/mstr/client.py
- ingestion/src/metadata/ingestion/source/dashboard/mstr/connection.py
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/mstr.json
Fixes: microstrategy test connection
https://github.com/open-metadata/OpenMetadata/pull/18889
#
#
> Fixes: microstrategy test connection

- openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
> Make it clear when to use docker compose down

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/QueryEntity.spec.ts
- openmetadata-ui/src/main/resources/ui/src/pages/AddQueryPage/AddQueryPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
Fixes #18700
The dropdown list for 'Add New Query' displays both the table name and its FQN instead of just the table name.
#
#
> Fix: show full fqn for reference tables

- ingestion/src/metadata/ingestion/source/dashboard/mstr/client.py
- ingestion/src/metadata/ingestion/source/dashboard/mstr/connection.py
- openmetadata-service/src/main/resources/json/data/testConnections/dashboard/mstr.json
Revert: remove Gettokens and fix test_conn on ui
#
#
> Revert: remove Gettokens

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ProfilerSettingsModal/ProfilerSettingsModal.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/TableProfilerProvider.tsx
Fixes GEN-2186
https://github.com/user-attachments/assets/47bee61b-94b6-4b79-9b45-996c9475d800
#
#
> GEN-2186: Fix Updating sampling config from deep link issue

- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/lineage.ts
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/LineageNodeLabelV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/NodeChildren/NodeChildren.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/custom-node.less
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/lineage-node-label.less
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
- openmetadata-ui/src/main/resources/ui/yarn.lock
> Change lineage positioning algorithm

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/resources/json/data/table/tableCsvDocumentation.json
Remove per Csv records db calls for table
#
#
> Fix Table Column Imports

- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/webpack.config.prod.js
- openmetadata-ui/src/main/resources/ui/yarn.lock
> chore(ui): remove deprecated image-webpack-loader

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
Added what's new content for 1.6.0 release
https://github.com/user-attachments/assets/16d8287e-bdeb-4af3-923b-1d3568b545ac
#
#
> Added what new content for 1.6.0

- ingestion/src/metadata/ingestion/source/database/snowflake/connection.py
> Fixes GEN-2198: Snowflake unencrypted key support, connection error on storing bytes 

- ingestion/src/metadata/ingestion/source/database/db2/connection.py
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/db2/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/db2/yaml.md
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/db2Connection.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Db2.md
> MINOR: DB2 Support License

- openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/index.md
I worked on updating Collate ingestion doc
#
#
> Docs: Updating Collate Ingestion Doc

- openmetadata-docs/content/v1.5.x/developers/contribute/build-code-and-run-tests/prerequisites.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/prerequisites.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/developers/contribute/developing-a-new-connector/develop-ingestion-code.md
I worked on 3.7 version removal from Python and Separator removal from  service spec section.
#
#
> Docs: Python Version Correction and Separator removal

- openmetadata-docs/content/v1.6.x-SNAPSHOT/developers/bots.md
I worked on developer bot image version change from 1.4 to 1.6 in 1.6
#
#
> Docs: Developer Bot Image Version Change

- openmetadata-docs/content/v1.5.x/getting-started/day-1/hybrid-saas/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/getting-started/day-1/hybrid-saas/index.md
I worked on collate ingestion correction.
#
#
> Docs: Collate Ingestion Correction

- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
> QueryBuilderWidget - change query generated format

- openmetadata-ui/src/main/resources/ui/src/components/common/CertificationTag/CertificationTag.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/CertificationTag/certification-tag.less
> update certification image size

- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
Fixes the below Column rearrangement issue in Glossary Terms table:-
When users attempts to rearrange columns in the Terms table, the changes are applied immediately instead of waiting for the user to  click the "Save" button.
https://github.com/user-attachments/assets/1295d2d3-67ff-4de9-bb6e-f69dd6f16042
Demo of Issue Fix
https://github.com/user-attachments/assets/d69d5647-49a6-4aee-9e99-c6858c292ab5
#
#
> fix: column rearrangement issue in Glossary Terms table

- openmetadata-ui/src/main/resources/ui/src/components/APIEndpoint/APIEndpointDetails/APIEndpointDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/DataModelDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Metric/MetricDetails/MetricDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModel/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Pipeline/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Topic/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexDetailsPage.tsx
extend the DQ alert support for all the entity
#
#
> Minor: extend the support for dq failure support to all the entity

- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderUtils.tsx
> minor - ui fixes for 1.6 release

- openmetadata-ui/src/main/resources/ui/src/generated/antlr/EntityLinkLexer.js
- openmetadata-ui/src/main/resources/ui/src/generated/antlr/EntityLinkListener.js
- openmetadata-ui/src/main/resources/ui/src/generated/antlr/EntityLinkParser.js
- openmetadata-ui/src/main/resources/ui/src/generated/antlr/FqnLexer.js
- openmetadata-ui/src/main/resources/ui/src/generated/antlr/FqnListener.js
- openmetadata-ui/src/main/resources/ui/src/generated/antlr/FqnParser.js
- openmetadata-ui/src/main/resources/ui/src/generated/antlr/JdbcUriLexer.js
- openmetadata-ui/src/main/resources/ui/src/generated/antlr/JdbcUriListener.js
- openmetadata-ui/src/main/resources/ui/src/generated/antlr/JdbcUriParser.js
> Minor: Check in generated files

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TagRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
- openmetadata-service/src/main/resources/elasticsearch/indexMapping.json
- Asset Certification Tags were not updated, this PR handles the updates for entitiy certification tags
#
#
> Fix Certification tags not updating in ES

- openmetadata-docs/content/partials/v1.6/deployment/upgrade/upgrade-prerequisites.md
> DOCS - EditTags RBAC changes for 1.6

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
Updated Whats new content for 1.6
https://github.com/user-attachments/assets/2ff6b158-e405-4553-aa83-32cf4079168b
#
#
> update whats new content for 1.6

- openmetadata-docs/content/partials/v1.6/deployment/upgrade/upgrade-prerequisites.md
> MINOR: Add Lineage breaking changes

- openmetadata-ui/src/main/resources/ui/src/components/Classifications/ClassificationDetails/ClassificationDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/SelectableList/SelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.tsx
- Fixes Loading of Users in teams page.
https://github.com/user-attachments/assets/06668e69-ac66-438d-9e3e-289bcb529e8c
- Minor displayName fix in Classification and tags page
#
#
> fix loading of users and other minor fixes

- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/AsyncSelectList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/TreeAsyncSelectList.tsx
Reverts open-metadata/OpenMetadata#18950
> Revert "fix: close select dropdpwn when parent compoment is changed"

- bootstrap/sql/migrations/native/1.6.0/postgres/schemaChanges.sql
1. Rename and remove 'offset' to 'currentOffset' and add 'startingOffset'.
#
#
> FIX: Postgresql Migrations For EventSubscriptionOffset.

- openmetadata-docs/content/v1.5.x/connectors/database/doris/index.md
- openmetadata-docs/content/v1.6.x-SNAPSHOT/connectors/database/doris/index.md
I worked on Doris Connector DBT Updation.
#
#
> Docs: Doris Connector DBT Updation

- openmetadata-service/src/main/resources/elasticsearch/indexMapping.json
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/ExploreTree.spec.ts
> Fix ES Tag Index failing

- openmetadata-docs/content/partials/v1.6/deployment/upgrade/upgrade-prerequisites.md
- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/v1.6.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
> DOCS - 1.6 release docs

- .github/workflows/sync-docs-v1.yml
I worked on the docs sync workflow to pick up the 1.6.x content for collate docs.
#
#
> Minor: Update the docs sync workflow for collate images

- openmetadata-service/pom.xml
I worked on updating the `pom.xml` for docs.
#
#
> Fix: Pom after docs removal

- openmetadata-docs/content/partials/v1.6/releases/latest.md
> minor: fix typo in latest.md doc file

- openmetadata-docs/content/v1.5.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.6.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-service/pom.xml
I worked on updating the documentation for OpenMetadata Docker deployment to improve flexibility and usability. Previously, the Cleanup section combined stopping the services and cleaning up named volumes into a single step. This approach stopped the services and removed the associated named volumes simultaneously, which might not always be desirable, especially when preserving data is important.
To address this, I restructured the documentation so that: 
1. If the user only wants to stop the services, the volumes are preserved. 
2. If the user wants to stop the services and remove the volumes, the commands are separated into distinct steps.
This update ensures that users have clear, flexible options depending on their requirements, minimizing the risk of unintended …
> feat: Updated docs for quickstart docker deployment

- ingestion/src/metadata/utils/constants.py
- ingestion/src/metadata/utils/elasticsearch.py
> MINOR - Add APIs to Ref Map

- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
> Ignore Bot on Domain restriction

- openmetadata-spec/src/main/resources/json/schema/entity/teams/persona.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/teams/persona.ts
> Fix #16041 The persona JSON schema is named Team

- openmetadata-ui/src/main/resources/ui/playwright/support/user/UserClass.ts
Updated the auth test for Collate onboarding modal.
#
#
> Update auth test

- ingestion/src/metadata/profiler/orm/converter/azuresql/converter.py
- ingestion/src/metadata/profiler/orm/converter/converter_registry.py
- ingestion/src/metadata/sampler/sqlalchemy/azuresql/sampler.py
- ingestion/tests/unit/profiler/sqlalchemy/azuresql/test_azuresql_sampling.py
- Add TABLESAMPLE and Rowversion converter for AzureSQL
#
#
> fix: azuresql sampler logic

- openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java
> MINOR - Pass Airflow host on every failed /status call

- openmetadata-docs/content/partials/v1.5/deployment/redeploy.md
- openmetadata-docs/content/partials/v1.5/deployment/reindex.md
- openmetadata-docs/content/partials/v1.6/deployment/redeploy.md
- openmetadata-docs/content/partials/v1.6/deployment/reindex.md
- openmetadata-docs/content/partials/v1.7/deployment/redeploy.md
- openmetadata-docs/content/partials/v1.7/deployment/reindex.md
I worked on Adding Reindex Pointer
#
#
> Docs: Adding Reindex Pointer

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionPipelineList/IngestionPipelineList.component.tsx
Fixes: IngestionList not updating upon pageSize change
Fix: #18001 
https://github.com/user-attachments/assets/4bdc6969-5184-4bfb-bb72-732523ba0eb1
#
#
> fix(ui): #18001 changing pageSize will fetch pipeline with updated size

- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/connectors/database/mssql/troubleshoot.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/connectors/database/mssql/troubleshoot.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mssql/troubleshoot.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on MSSQL Troubleshooting Doc Updation.
#
#
> Docs: MSSQL Troubleshooting Doc Updation

- openmetadata-docs/content/v1.5.x/deployment/security/azure/index.md
- openmetadata-docs/content/v1.6.x/deployment/security/azure/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/security/azure/index.md
Fixes #18680
I updated the documentation to clarify how to handle the client secret for Azure SSO in Docker deployments. The changes explain that for Web applications, you need to provide both the client ID and client secret when using the `OIDC` Authorization Code Flow.
on clicking the `OIDC Authorization Code Flow` is will be redirect user to here.
#
#
> feat:Updated docs for azure SSO with secret client

- openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.component.tsx
Fixes: #18577 
- Instead adding ellipsis to 1 row for Type expand it to 3 rows now
- Also on hovering we are showing the full type as tooltip
https://github.com/user-attachments/assets/f90c5561-b1c9-441b-ad33-d505718f49ac
#
#
> fix(ui): render column type max 3 lines and ellipsis

- openmetadata-ui/src/main/resources/ui/src/pages/LogsViewerPage/LogsViewerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/applicationAPI.ts
- openmetadata-ui/src/main/resources/ui/src/utils/IngestionLogs/LogsUtils.ts
https://github.com/user-attachments/assets/f8027774-e3e4-43c6-9573-8c9a2427a8c1
#
#
> fix downloading of app logs

- openmetadata-spec/src/main/resources/json/schema/governance/workflows/elements/nodes/userTask/userApprovalTask.json
- openmetadata-ui/src/main/resources/ui/src/generated/governance/workflows/elements/nodes/userTask/userApprovalTask.ts
> remove extra assignees from workflow

- bootstrap/sql/migrations/native/1.5.15/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.5.15/postgres/schemaChanges.sql
- openmetadata-service/src/main/resources/json/data/policy/DomainAccessPolicy.json
- openmetadata-service/src/main/resources/json/data/role/DomainOnlyAccessRole.json
Make DomainOnlyAccessPolicy and Role not system entity
#
#
> Domain Policy Update to be non-system

- openmetadata-docs/content/v1.6.x/connectors/dashboard/powerbi-report-server/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/powerbi-report-server/index.md
> Docs - Fix PowerBI RS Slug

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/QueryBuilder.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/queryBuilder.ts
- openmetadata-ui/src/main/resources/ui/src/components/Explore/AdvanceSearchProvider/AdvanceSearchProvider.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/query-builder-widget.less
- openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.test.tsx
- openmetadata-ui/src/main/resources/ui/src/enums/AdvancedSearch.enum.ts
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderElasticsearchFormatUtils.js
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderUtils.tsx
> fix query builder state issues

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
Fix : Handle Index out of bounds exception in feed api
#
#
> Fix : Handle Index out of bounds exception in feed api

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
> fix postgres offset query

- openmetadata-docs/content/v1.6.x/collate-menu.md
I worked on correcting collate menu.
#
#
> Docs: Collate Menu Updation

- bootstrap/sql/migrations/native/1.6.2/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.6.2/postgres/schemaChanges.sql
- Added index on `timestamp DESC` for test case result for reindex operation
#
#
Improvement
> GEN-2237: Added index on timestamp field for reindex

- openmetadata-service/src/main/java/org/openmetadata/service/exception/CatalogExceptionMessage.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/settings/SettingsCache.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BasicAuthenticator.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/auth/LdapAuthenticator.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/auth/LoginAttemptCache.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/system/ConfigResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java
- Update Block time restriction to 30 seconds
- Fix update login config not updated in LoginAttemptCache
#
#
> Fix Login Configuration Issue

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
- if run result file has not changed, handle ingestion of existing test case result in dbt
#
#
Improvement
> MINOR: Handle existing dbt results

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/client.py
- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
I worked on PowerBI workspace api limit error, avoid bulk data prepare so different apis are called for dashboards, datasets, reports.
#
#
> GEN-2346: PowerBI workspace api limit error, avoid bulk data prepare

- ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py
- ingestion/tests/integration/ometa/test_ometa_user_api.py
> MINOR: User search should only look in name & displayName

- openmetadata-docs/content/partials/v1.5/releases/latest.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/v1.5.x/collate-menu.md
- openmetadata-docs/content/v1.5.x/menu.md
- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
I worked on Release updation.
#
#
> Docs: Release updation

- ingestion/src/metadata/ingestion/api/topology_runner.py
> MINOR - Improve MissingExpectedEntityAckException msg

- openmetadata-docs/content/v1.6.x/deployment/docker/index.md
- openmetadata-docs/content/v1.6.x/deployment/ingestion/external/airflow.md
- openmetadata-docs/content/v1.6.x/deployment/ingestion/openmetadata.md
- openmetadata-docs/content/v1.6.x/sdk/python/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/ingestion/external/airflow.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/ingestion/openmetadata.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/sdk/python/index.md
I worked on Change in Doc Content from 1.5 to 1.6
#
#
> Docs: Change in Content from 1.5 to 1.6

- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/BarMenu/BarMenu.tsx
- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/block-editor.less
> refactor: remove unused highlight option from BarMenu and improve focus styles in block editor

- openmetadata-docs/content/v1.6.x/connectors/database/pinotdb/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/pinotdb/index.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/PinotDB.md
Fixes 17024
https://github.com/open-metadata/OpenMetadata/issues/17024
I worked on improving documentation for PinotDB connection
#
#
> Fixes 17024: Improve PinotDB connection documentation

- openmetadata-docs/content/partials/v1.6/connectors/yaml/lineage.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/lineage.md
I worked on Lineage Ingestion Yaml Updation with New Feature
#
#
> Docs: Lineage Ingestion Yaml Updation with New Feature

- openmetadata-ui/src/main/resources/ui/src/components/common/RichTextEditor/RichTextEditorPreviewer.tsx
Deprecate RichTextEditorPreviewer component and recommend alternative
#
#
> Minor: Deprecate RichTextEditorPreviewer component and recommend alternative RichTextEditorPreviewerV1

- openmetadata-docs/content/v1.6.x/connectors/database/mariadb/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/mysql/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/mysql/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/yaml.md
I worked on MySql And Mariadb Lineage updation.
#
#
> Docs: MySql And Mariadb Lineage updation

- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/useGlossary.store.ts
- openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.tsx
Fixes: Glossary term table expand collapse state
Issue:
https://github.com/user-attachments/assets/a7e05acc-3596-4699-ba34-ff3e5b4ebf1d
Fix:
https://github.com/user-attachments/assets/07e3dfc8-3991-4db7-9169-0d70d7b3b4b4
#
#
> fix(ui): glossary terms table expand / collapse state

- openmetadata-docs/content/v1.6.x/menu.md
I worked on auto classification correction in menu.
#
#
> Docs: Auto Classification Correction in Menu

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/pipelines/PipelineResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/JsonUtils.java
- Added some helper functions and changes needed for sample data 
#
#
> Onboarding Application Changes for OSS

- openmetadata-ui/src/main/resources/ui/src/components/Classifications/ClassificationDetails/ClassificationDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsDetailsPage/DataProductsDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryHeader/GlossaryHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TagPage/TagPage.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/glossaryAPI.ts
Fixes: 
- Console error
- API reponse from AxiosResponse to GlossaryTerm which is needed for cherry-picked changes [here](https://github.com/open-metadata/OpenMetadata/commit/c4f3fa7e82d1a55994a1e36a9857a1d44eadd9e6)
#
#
> chore(ui): ui errors and glossary term api response fix

- openmetadata-docs/content/v1.6.x/connectors/database/athena/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/azuresql/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/azuresql/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/db2/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/db2/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/athena/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/azuresql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/azuresql/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/db2/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/db2/yaml.md
I worked on lineage addition to connectors till db2.
#
#
> Docs: Lineage Link Addition to Connectors

- ingestion/setup.py
Fix #15952: Update SQLParse to Version 0.5
#
#
> Fix #15952: Update SQLParse to Version 0.5

- openmetadata-docs/content/v1.6.x/connectors/database/azuresql/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/db2/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/druid/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/azuresql/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/db2/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/druid/yaml.md
I worked on file location correction for Connectors.
#
#
> Docs: File Location correction for Connectors

- openmetadata-docs/content/v1.6.x/connectors/database/hive/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/impala/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/hive/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/impala/yaml.md
I worked on File Location correction for Impala and Hive.
#
#
> Docs: File Location correction for Impala and Hive

- openmetadata-docs/content/v1.6.x/connectors/database/mariadb/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/mysql/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/oracle/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/pinotdb/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/pinotdb/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/sap-hana/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/sap-hana/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/singlestore/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/singlestore/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mariadb/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/oracle/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/pinotdb/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/pinotdb/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/sap-hana/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/sap-hana/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/singlestore/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/singlestore/yaml.md
I worked on connectors YAML Updation till Singlestore.
#
#
> Docs: Connectors YAML Updation till Singlestore

- ingestion/src/metadata/utils/constants.py
- Remove unity from non sqa profiler db
#
#
Bug fix
> MINOR - fix unity profiler

- openmetadata-ui/src/main/resources/ui/src/generated/entity/data/metrics.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/apiService/restConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/dashboard/mstrConnection.ts
> Minor: Add UI typescript types

- openmetadata-docs/content/v1.6.x/connectors/database/sqlite/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/sqlite/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/teradata/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/teradata/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/trino/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/trino/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/unity-catalog/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/vertica/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/vertica/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/sqlite/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/sqlite/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/teradata/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/teradata/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/trino/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/trino/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/unity-catalog/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/vertica/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/vertica/yaml.md
I worked on Connectors Lineage YAML Updation till Vertica
#
#
> Docs: Connectors Lineage YAML Updation till Vertica

- ingestion/src/metadata/utils/constants.py
Fixes #19220
- Remove druid and doris from non sqa connections
#
#
Bug fix
> ISSUE-19220: remove druid and doris from non sqa

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/client.py
- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
I worked on improve better logging in empty api response.
#
#
> MINOR: PowerBI improve error logging

- .github/workflows/auto-cherry-pick-labeled-prs.yaml
> chore(ci): adding write permissions to issues

- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
move activeFqn to new method in interface
#
#
> Persist knowledge page hierarchy on page refresh part-2 

- .github/workflows/auto-cherry-pick-labeled-prs.yaml
> chore(ci): updating auto cherry pick wf

- openmetadata-service/pom.xml
- pom.xml
> upgrade logback versions

- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/storage/containerMetadataConfig.json
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/storage/containerMetadataConfig.ts
Fix #19160-1: Add Depth Support Part-1
#
#
> Fix #19160: Add Depth Support Part-1

- openmetadata-docs/content/v1.5.x/how-to-guides/data-discovery/advanced.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-discovery/advanced.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-discovery/advanced.md
Fixes https://github.com/open-metadata/OpenMetadata/pull/19113
I worked on Format Note Mention In Advanced Search.
#
#
> Docs: Format Note Mention In Advanced Search

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/UserUtil.java
This PR adds an option in operation to allow Infra/Admins to reset user password.
#
#
> [OMOperations] Add Reset Password option

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
Fixes #19131 
- Fetch test suites field as part of the patch operation
#
#
Bug fix
> ISSUE-19131: Fix patch removing testSuites field

- ingestion/setup.py
> MINOR: Kafka dependency conflict resolution

- ingestion/src/metadata/ingestion/source/database/redshift/queries.py
Fixes #18145 
cast `query_user_name` into string when  it's fetched as int from db to avoid pydantic validation error on `QueryByProcedure` model.
#
#
> MINOR: Redshift stored procedure query parse fix

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whats-new-modal.less
- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
I worked on adding what's new content for 1.6.2
https://github.com/user-attachments/assets/1d6c0a15-e8e8-4f10-96d0-e3a9ef7ee578
#
#
> Minor: Update the what's new for 1.6.2

- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/property-value.less
- openmetadata-ui/src/main/resources/ui/src/components/common/InlineEdit/InlineEdit.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/InlineEdit/inline-edit.less
I worked on fixing the spacing in the inline button on user page.
Issue : 
Resolved : 
#
#
> MINOR: fix the inline edit button spacing on user page

- openmetadata-docs/content/v1.6.x/developers/contribute/build-code-and-run-tests/generate-typescript-types-from-json-schema.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/generate-typescript-types-from-json-schema.md
I worked on content updation of Generate Typescript Types From JSON Schema.
#
#
> Docs: Content updation of Generate Typescript Types From JSON Schema

- openmetadata-docs/content/v1.5.x/connectors/ingestion/workflows/dbt/index.md
- openmetadata-docs/content/v1.6.x/connectors/ingestion/workflows/dbt/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ingestion/workflows/dbt/index.md
I worked on Fixing error Images in Connectors workflow DBT.
#
#
> Docs: Fixing error Images in Connectors workflow DBT

- ingestion/tests/cli_e2e/test_cli_powerbi.py
> MINOR: powerbi e2e fix

- docker/development/docker-compose-postgres.yml
- docker/development/docker-compose.yml
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
Reverts open-metadata/OpenMetadata#18821
> Revert "fixes #18820: updated docker compose files"

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
> revert: Circular Rendering issue for lineage (#19270)

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
Install App Through Ops (Onboarding currently)
[NOTE] This PR doesn't add ability to handle appConfiguration and schedules since the schema cannot be mapped easily
#
#
> Add Operations to install Onboarding app

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/ElasticSearchIndexSink.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/OpenSearchIndexSink.java
Add Stack in Indexing Logs
#
#
> Add Indexing Stack Trace in app logs

- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
- Fixes breaking cherry pick
#
#
> 1.6.2-MINOR: Fix breaking cherry pick

- ingestion/tests/integration/conftest.py
- ingestion/tests/integration/mongodb/conftest.py
- ingestion/tests/integration/mongodb/test_metadata.py
- Added integration(metadata) testcontainer test for mongodb
- Pytest
#
#
> Added integration testcontainer test for mongodb

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/GlossaryTermsV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/useGlossary.store.ts
https://github.com/user-attachments/assets/c10aac68-1c46-4c6d-b1b5-dbb5c0b12627
https://github.com/user-attachments/assets/69ebbca8-b6f9-4a57-bc98-82b2dbf87351
#
#
> fix(ui): update glossary term table upon new term added

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
I worked on updating the what's new content
#
#
> Minor: Update what's new content

- openmetadata-ui/src/main/resources/ui/src/App.tsx
- openmetadata-ui/src/main/resources/ui/src/hooks/useWelcomeStore.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
Set welcome page visible flag to true by default.
#
#
> Update welcome page condition

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/UserDetails.spec.ts
I worked on fixing flaky playwright test
- UserDetails - (Description editor clear issue)
- Glossary - (Due to timeout)
#
#
> PLAYWRIGHT: fix flaky playwright test

- openmetadata-docs/content/partials/v1.6/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.6/connectors/pipeline/connectors-list.md
- openmetadata-docs/content/partials/v1.7/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.7/connectors/pipeline/connectors-list.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/datafactory/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/datafactory/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/datafactory/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/datafactory/yaml.md
Add in dbt tile & Renaming Datafactory
#
#
> Docs: Add in dbt tile & Renaming Datafactory

- ingestion/tests/cli_e2e/test_cli_mysql.py
> Fix mysql e2e count

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SearchIndexApplication.spec.ts
> test(e2e): fix flaky searchIndexApplication.spec.ts

- openmetadata-docs/content/v1.5.x/developers/contribute/developing-a-new-connector/update-documentation.md
- openmetadata-docs/content/v1.6.x/developers/contribute/developing-a-new-connector/update-documentation.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/developers/contribute/developing-a-new-connector/update-documentation.md
I worked on connectors Documentation update.
#
#
> Docs: Documentation update

- openmetadata-docs/content/v1.6.x/connectors/pipeline/datafactory/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/datafactory/index.md
Fixing Context Name Azure Data Factory
#
#
> Docs: Fixing Context Name Azure Data Factory

- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
I worked on 1.6.2 Release Updation.
#
#
> Docs: 1.6.2 Release Updation

- openmetadata-docs/content/v1.6.x/connectors/database/doris/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/doris/yaml.md
I worked on Doris YAML Correction.
#
#
> Docs: Doris YAML Correction

- openmetadata-docs/content/v1.5.x/connectors/messaging/kinesis/index.md
- openmetadata-docs/content/v1.6.x/connectors/messaging/kinesis/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/messaging/kinesis/index.md
I worked on Kinesis Image path correction.
#
#
> Docs: Kinesis Image path correction

- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java
Fix issue when we have table - table relationship and one of the tables is soft-deleted.
the call to fetch table fails since we are looking for non deleted tables.
#
#
> [ERD] Fix Search Index for ER Model

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
- openmetadata-docs/content/v1.6.x/main-concepts/metadata-standard/schemas/metadataIngestion/dbtPipeline.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/main-concepts/metadata-standard/schemas/metadataIngestion/dbtPipeline.md
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/dbtPipeline.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/workflows/dbt.md
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/dbtPipeline.ts
Fixes #19313 
dbt ingestion picks up wrong service to patch metadata
#
#
> Fix #19313 - dbt ingestion picks up wrong service to patch metadata

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/team.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TeamsPage/TeamsPage.tsx
Fixes #19280
- I worked on fixing the wrong count being displayed on Organization Team page Tab
#
#
> MINOR: fix the wrong team count displayed on team tab

- ingestion/src/metadata/ingestion/lineage/models.py
Fix #19370: Fix Mariadb Dialect
#
#
> Fix #19370: Fix Mariadb Dialect

- openmetadata-docs/content/partials/v1.5/connectors/yaml/ml-model/source-config-def.md
- openmetadata-docs/content/partials/v1.5/connectors/yaml/ml-model/source-config.md
- openmetadata-docs/content/partials/v1.6/connectors/yaml/ml-model/source-config-def.md
- openmetadata-docs/content/partials/v1.6/connectors/yaml/ml-model/source-config.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/ml-model/source-config-def.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/ml-model/source-config.md
I worked on SageMaker YAML correction
#
#
> Docs: SageMaker YAML correction

- openmetadata-docs/content/partials/v1.6/connectors/yaml/messaging/source-config-def.md
- openmetadata-docs/content/partials/v1.6/connectors/yaml/messaging/source-config.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/messaging/source-config-def.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/messaging/source-config.md
- openmetadata-docs/content/v1.6.x/connectors/messaging/kafka/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/messaging/redpanda/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/messaging/kafka/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/messaging/redpanda/yaml.md
Document update
I worked on updating docs of mesaging in connector section to provide all avaiable configs with in the docs.
#
#
> feat: Updated messaging docs in connectors

- openmetadata-docs/content/v1.5.x/how-to-guides/data-quality-observability/profiler/profiler-workflow.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-quality-observability/profiler/profiler-workflow.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-quality-observability/profiler/profiler-workflow.md
…orkflow
I worked on Removing PII Sensitive and Generate Sample Data from Profiler workflow.
#
#
> Docs: Removing PII Sensitive and Generate Sample Data from Profiler Workflow

- openmetadata-docs/content/partials/v1.6/connectors/yaml/database/source-config-def.md
- openmetadata-docs/content/partials/v1.6/connectors/yaml/database/source-config.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/database/source-config-def.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/database/source-config.md
I worked on Database YAML correction.
#
#
> Docs: Database YAML correction

- openmetadata-ui/src/main/resources/ui/src/utils/i18next/i18nextUtil.ts
Currently, the English version is presented to all users when visiting OM for the first time. After login, users can change the language and that option is stored in the i18next cookie.
This is an improvement to support detection of browser language settings. With this PR, users landing in OM for the first time will see the UI in their default language, as defined in the browser (if already supported by OM).
This PR takes advantage of the multiple options offered by [i18next browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector).
Currently, we are using just one option:
```Javascript
detection: {
order: ['cookie'],
caches: ['cookie'], // cache user language on
},
```
This PR add two more options:
```Javascript
detection: {
order: ['querystring', 'cookie', …
```
> Browser language detection

- ingestion/setup.py
I worked on removing hard pin on google-cloud-storage library version because when using alongside dbt 1.8 bigquery adapter it broke the installation process. This version (1.4.3) is almost 5 years old and I think it'd be better to make it less restrictive version-wise. Usage of it is quite minimal and it's covered with tests so the riskt is quite minimal.
#
#
> chore: remove hard pin on google cloud storage

- ingestion/src/metadata/automations/runner.py
Fixes Test Connection alongwith Kafka test connection
#
#
> MINOR: Fix Kafka Test connection

- ingestion/src/metadata/clients/aws_client.py
Fixes isformat error for datetime attribute, added models for better ways to validate
#
#
> MINOR: Typo for datetime attribute

- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/ingestion/source/database/bigquery/profiler/profiler.py
- ingestion/src/metadata/sampler/partition.py
I worked on adding support for external partitioned tables + fixing nonetype system metric profiler issue
#
#
https://github.com/open-metadata/OpenMetadata/actions/runs/12841865269
Test results for Nonetype error
> MINOR: BigQuery Improvement, Hive Partitioned Tables, Nonetype issue resolved

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataInsightSystemChartRepository.java
> MINOR: Fix DI Filter not getting applied

- ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/kafkaconnect/models.py
Fixes #19091  Kafkaconnect validation errors
#
#
> Fixes #19091 - Kafkaconnect validation errors

- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
> bump(playwright): update playwright for batter tracing

- openmetadata-docs/content/v1.5.x/connectors/database/bigtable/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/bigtable/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/bigtable/yaml.md
I worked on fixing BigQuery YAML 
#
#
> Docs: BigQuery Yaml fix

- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on fixing the menu not showing for SNAPSHOT version
#
#
> Docs: Fix the wrong indentation in the menu.md for 1.7.x.SNAPSHOT

- openmetadata-docs/content/v1.6.x/connectors/pipeline/dbtcloud/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dbtcloud/yaml.md
Fixing Intendation in the dbt cloud YAML
#
#
> Docs: Fixing Intendation in the dbt cloud YAML

- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
Reverts open-metadata/OpenMetadata#19440
> Revert "bump(playwright): update playwright for batter tracing"

- openmetadata-docs/content/v1.6.x/how-to-guides/admin-guide/roles-policies/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/admin-guide/roles-policies/index.md
I worked on Advanced Guide Section Addition.
#
#
> Docs: Advanced Guide Section Addition

- openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/EventSubscriptionScheduler.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppMarketPlaceRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppMapper.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppMarketPlaceMapper.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionMapper.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/TestApp.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/events/BaseCallbackResource.java
- openmetadata-spec/src/main/resources/json/schema/entity/applications/app.json
- openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/appMarketPlaceDefinition.json
- openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.json
- openmetadata-spec/src/main/resources/json/schema/events/api/createEventSubscription.json
- openmetadata-spec/src/main/resources/json/schema/events/eventSubscription.json
- openmetadata-spec/src/main/resources/json/schema/type/basic.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/app.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/marketplace/appMarketPlaceDefinition.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.ts
- openmetadata-ui/src/main/resources/ui/src/generated/events/api/createEventSubscription.ts
- openmetadata-ui/src/main/resources/ui/src/generated/events/eventSubscription.ts
- added support for apps with event subscriptions.
- added support for custom consumers on event subscriptions.
- use native application methods instead of reflection in ApplicationHandler
#
#
> MINOR: feat(apps): support event subscriptions

- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ApiIngestionClass.ts
Fixes: update schema source to something smaller so that deletion won't take much time to effect.
On the other end we are working on making deletion async so that we don't run into such issue in future. ref: #19391
#
#
> fix(test): rest api service deletion taking longer

- openmetadata-docs/content/v1.6.x/how-to-guides/admin-guide/roles-policies/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/admin-guide/roles-policies/index.md
I worked on Advanced Guide Section Correction.
#
#
> Docs: Advanced Guide Section Correction

- openmetadata-docs/content/v1.6.x/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/postgres/index.md
I worked on postgres stored procedure update.
#
#
> Docs: Postgres Stored Procedure Update

- openmetadata-docs/content/v1.6.x/connectors/metadata/alationsink/index.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-insights/index.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-insights/report.md
- openmetadata-docs/content/v1.6.x/quick-start/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/alationsink/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-insights/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-insights/report.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/quick-start/index.md
I worked on 404 URL Correction.
#
#
> Docs: 404 URL Correction

- openmetadata-docs/content/v1.6.x/connectors/database/exasol/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/exasol/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/exasol/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/exasol/yaml.md
I worked on fixing Exasol Connector UI.
#
#
> Docs: Exasol Connector CHANGES

- openmetadata-docs/content/v1.5.x/how-to-guides/admin-guide/alerts.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-quality-observability/observability/alerts.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/admin-guide/alerts.md
> MINOR: docs: add required permissions callout for setting up alerts

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Domains.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/domain/Domain.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/domain/SubDomain.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsDetailsPage/DataProductsDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainDetailsPage/DomainDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.test.tsx
Fix #19358
Fixed the edit-description permission issue for domain owner
Before:
After:
https://github.com/user-attachments/assets/0d669ab4-0e52-440c-8029-6b81fbe9c2df
#
#
> fix: edit description permission for domain owner

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamImportResult/TeamImportResult.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/UserImportResult/UserImportResult.component.tsx
- I worked on fixing the description renderer in team and user import.
Issue : 
Resolved : 
#
#
> MINOR: fix the description renderer in team and user import

- .github/workflows/playwright-integration-tests-mysql.yml
- .github/workflows/playwright-integration-tests-postgres.yml
- .github/workflows/py-cli-e2e-tests.yml
- .github/workflows/security-scan.yml
update actions/upload-artifact to v4 as v3 is deprecated and will not run:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Version tags will not be removed from the project repositories, however, attempting to use a version of the actions after the deprecation date will result in a workflow failure.
#
#
> chore: bump actions/upload-artifact

- .github/workflows/py-cli-e2e-tests.yml
> MINOR: fix py-cli-e2e-tests.yml

- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/sql_column_handler.py
Fixes #19488 Duplicate constraint issue while ingesting tables
#
#
> Fix #19488 -  Duplicate table constraints

- ingestion/src/metadata/ingestion/source/database/mssql/queries.py
> Fix: Updated MSSQL queries causing arithmetic overflow error

- ingestion/tests/cli_e2e/common/test_cli_db.py
- ingestion/tests/cli_e2e/test_cli_athena.py
- ingestion/tests/cli_e2e/test_cli_bigquery.py
- ingestion/tests/cli_e2e/test_cli_bigquery_multiple_project.py
- ingestion/tests/cli_e2e/test_cli_datalake_s3.py
- ingestion/tests/cli_e2e/test_cli_hive.py
- ingestion/tests/cli_e2e/test_cli_mssql.py
- ingestion/tests/cli_e2e/test_cli_mysql.py
- ingestion/tests/cli_e2e/test_cli_oracle.py
- ingestion/tests/cli_e2e/test_cli_postgres.py
- ingestion/tests/cli_e2e/test_cli_redshift.py
- ingestion/tests/cli_e2e/test_cli_snowflake.py
- ingestion/tests/cli_e2e/test_cli_vertica.py
- changed method name to expected_sample_count
#
#
> MINOR: tests: fix sample row count for bigquery

- bootstrap/sql/migrations/native/1.7.0/postgres/schemaChanges.sql
Fix postgres query added in pr #19411, failing ci workflow on main branch 
#
#
> Fix postgres query added in pr #19411

- ingestion/tests/cli_e2e/base/config_builders/builders.py
- use the data quality pipeline new schema with a list of service configurations
#
#
> tests(e2e): data quality

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/client.py
- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
> issue-19508: PowerBI tables, datamodel metadata missing

- ingestion/tests/integration/test_suite/test_e2e_workflow.py
Currently fails about one in 20 runs. This will fail one in 100.
based on experiment in https://gist.github.com/sushi30/3083e96c9081371fa55e55b0847b96d2
>
#
#
> MINOR: tests(e2e): increase CI for sampling test

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
Fix #19198: di fix custom property filter
#
#
> Fix #19198: di fix custom property filter

- bootstrap/sql/migrations/native/1.7.0/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.7.0/postgres/postDataMigrationSQLScript.sql
eventBasedEntityWorkflow -> eventBasedEntity
periodicBatchEntityWorkflow -> periodicBatchEntity
#
#
> MINOR: fix(governance-workflows): fix migrations for 1.7.0

- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
- Added `entityFQN` query param for TestCase resource
#
#
> ISSUE #1052 - Added `entityFQN` query param for TestCase resource

- bootstrap/sql/migrations/native/1.7.0/postgres/postDataMigrationSQLScript.sql
> MINOR: fix syntax in migration

- openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/LoginAPI.ts
Fixes: Issue with not logging out for failed refresh request
#
#
> chore(ui): logout user on unsuccessful refresh attempt

- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.ts
- I worked on removing unwanted spacing around the list in block editor
Issue: 
Resolved : 
#
#
> remove unwanted spacing around the list in block editor

- ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
> MINOR: Optimise Snowflake SP Query

- openmetadata-docs/content/v1.6.x/connectors/database/athena/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/glue/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/greenplum/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/mysql/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/postgres/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/s3-datalake/index.md
- openmetadata-docs/content/v1.6.x/connectors/messaging/kinesis/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/ml-model/sagemaker/index.md
- openmetadata-docs/content/v1.6.x/connectors/ml-model/sagemaker/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/storage/s3/index.md
- openmetadata-docs/content/v1.6.x/connectors/storage/s3/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/athena/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/glue/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/greenplum/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/postgres/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/s3-datalake/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/messaging/kinesis/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ml-model/sagemaker/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ml-model/sagemaker/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/s3/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/s3/yaml.md
I worked on Assume role Note Updation for AWS in Connectors.
#
#
> Docs: Assume role Note Updation for AWS in Connectors

- openmetadata-docs/content/v1.6.x/deployment/production-ready-requirements.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/production-ready-requirements.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on adding Requirement Doc in Deployment.
#
#
> Docs: Requirement Doc Added in Deployment

- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
updated testSuite icon in common utils
#
#
> Minor: updated testSuite icon for common utils

- ingestion/src/metadata/ingestion/source/database/mariadb/lineage.py
> MINOR: Mariadb Lineage Fix

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
> MINOR: Make DBT Tests failure log to debug

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
- I worked on updateing the what's new for 1.6.3
#
#
> Update the what's new for 1.6.3

- openmetadata-docs/content/v1.6.x/deployment/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/index.md
I worked on Production ready tile addition in Deployment Index.
#
#
> Docs: Production ready tile addition in Deployment Index

- openmetadata-docs/content/partials/v1.5/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.6/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.7/connectors/database/connectors-list.md
> Update PostgreSQL name in connector list

- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/mocks/EntityUtils.mock.ts
Fix #18124 
Displayed the schema name along with display name in the breadcrumb of search results for Database and Database Schema.
#
#
> feat: display schema name to the breadcrumb in search results

- openmetadata-ui/src/main/resources/ui/src/styles/tree.less
> fix missing tree styles

- ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py
- ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
> MINOR: Fix ES Req for Views

- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
I worked on Release 1.6.3 doc Update.
#
#
> Docs: Release 1.6.3 Update

- openmetadata-ui/src/main/resources/ui/playwright/utils/tag.ts
I worked on fixing tags page flaky playwright test
#
#
> PLAYWRIGHT: fix tags page flaky playwright test

- openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableList/DomainSelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableTree/DomainSelectableTree.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.tsx
Fixes: Issue with domains not getting set for searched one.
Also fix initial loading for when use has passed popoverProps.open
https://github.com/user-attachments/assets/5430f201-1bb5-405d-9f14-7804db2453ad
https://github.com/user-attachments/assets/90ccf4d8-e3a2-4eb6-a1a6-51713859ebb7
#
#
> fix(ui): domain updation for searched domain

- openmetadata-docs/content/v1.6.x/deployment/security/keycloak/docker.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/security/keycloak/docker.md
Fixes (no issue, trivial change) 
There is a missing quotation mark in Keycloak config example, this change adds the missing quotation mark.
> Fix missing quote in template (trivial)

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/looker/parser.py
Added debug logs in looker
#
#
> Added debug logs in looker

- openmetadata-ui/src/main/resources/ui/src/constants/profiler.constant.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
> fix(ui)Data Quality Control: Types and Status Support Internationalization

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ExploreQuickFilters.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Navbar.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/explore.ts
- openmetadata-ui/src/main/resources/ui/src/components/AppBar/Appbar.tsx
- openmetadata-ui/src/main/resources/ui/src/components/AppBar/Suggestions.tsx
Fixes #18008
- I worked on persisting quick filter when global search is applied on it
https://github.com/user-attachments/assets/7b0c860b-dd37-4c6c-b84c-8fb82f424fc2
#
#
> #18008: global search should persist quick filter in explore

- ingestion/src/metadata/ingestion/source/api/rest/metadata.py
> issue-19112: API service schema fields of object type not listed

- ingestion/tests/cli_e2e/test_cli_powerbi.py
> MINOR: powerbi e2e count fix

- openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/DataQualityUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DataQuality/DataQualityUtils.ts
Fixes https://github.com/open-metadata/openmetadata-collate/issues/1133
Before:  (from sandbox)
https://github.com/user-attachments/assets/a9e17e5f-914d-449b-94ca-71d87f66a0a3
After: (from Local data)
https://github.com/user-attachments/assets/f916e69d-8cdf-44bd-bd85-4e1eb50d409e
#
#
> Fix: Multiple Tier selection not resulting correct DQ dashboard view

- openmetadata-docs/content/v1.6.x/connectors/ingestion/workflows/dbt/ingest-dbt-ui.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ingestion/workflows/dbt/ingest-dbt-ui.md
I worked on adding note to ingest DBT UI page.
#
#
> Docs: Adding note to ingest DBT UI Page

- openmetadata-docs/content/v1.6.x/connectors/metadata/alation/index.md
- openmetadata-docs/content/v1.6.x/connectors/metadata/alation/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/metadata/alationsink/index.md
- openmetadata-docs/content/v1.6.x/connectors/metadata/alationsink/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/metadata/amundsen/index.md
- openmetadata-docs/content/v1.6.x/connectors/metadata/amundsen/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/metadata/atlas/index.md
- openmetadata-docs/content/v1.6.x/connectors/metadata/atlas/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/alation/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/alation/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/alationsink/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/alationsink/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/amundsen/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/amundsen/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/atlas/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/metadata/atlas/yaml.md
I worked on Metadata Connector Feature Updation.
#
#
> Docs: Metadata Connector Feature Updation

- openmetadata-docs/content/v1.6.x/connectors/ml-model/mlflow/index.md
- openmetadata-docs/content/v1.6.x/connectors/ml-model/mlflow/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ml-model/mlflow/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ml-model/mlflow/yaml.md
I worked on ML Model connector content and feature correction.
#
#
> Docs: ML Model Connector content and feature Correction

- openmetadata-service/src/main/java/org/openmetadata/service/events/scheduled/DatabseAndSearchServiceStatusJob.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/JsonUtils.java
… String value length (20054016) exceeds the maximum allowed (20000000, from
Fixes issue with object mapper String value length (20054016) exceeds the maximum allowed (20000000, from
#
#
> [MINOR] Fixes String value length (20054016) exceeds the maximum allowed (20000000,

- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
- ingestion/src/metadata/ingestion/source/database/lineage_source.py
- ingestion/src/metadata/ingestion/source/database/query_parser_source.py
- ingestion/src/metadata/ingestion/source/database/snowflake/lineage.py
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceQueryLineagePipeline.json
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/databaseServiceQueryLineagePipeline.ts
Fix #12094: Add support for temp table lineage
#
#
> Fix #12094: Add support for temp table lineage

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
I worked on Teradata Updation in Collate Menu.
#
#
> Docs: Teradata Updation in Collate Menu

- openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
> fix glossary playwright flakiness

- openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
Issue #19363
- I worked on removing `isNull` and `is not null` condition from description and column description field, since here we have only 2 criteria of `COMPLETE` and `INCOMPLETE`, and the above 2 condition will not work in this case.
#
#
> #19363: remove isNull and not null condition from description in advance search

- ingestion/setup.py
> MINOR: Fix Teradata SQA version

- openmetadata-docs/content/partials/v1.7/connectors/metadata-ingestion-ui.md
- openmetadata-docs/content/v1.5.x/getting-started/day-1/index.md
- openmetadata-docs/content/v1.5.x/getting-started/index.md
- openmetadata-docs/content/v1.5.x/quick-start/getting-started/day-1/index.md
- openmetadata-docs/content/v1.5.x/quick-start/getting-started/index.md
- openmetadata-docs/content/v1.5.x/releases/releases/index.md
- openmetadata-docs/content/v1.6.x/getting-started/day-1/index.md
- openmetadata-docs/content/v1.6.x/getting-started/index.md
- openmetadata-docs/content/v1.6.x/quick-start/getting-started/day-1/index.md
- openmetadata-docs/content/v1.6.x/quick-start/getting-started/index.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/getting-started/day-1/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/getting-started/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/quick-start/getting-started/day-1/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/quick-start/getting-started/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
> Updated number of connectors and other fixes

- ingestion/src/metadata/ingestion/source/database/redshift/metadata.py
- ingestion/src/metadata/ingestion/source/database/redshift/queries.py
Fixes #19535 
- Added external table lineage support for redshift
#
#
> Added redshift external table lineage support

- openmetadata-docs/content/v1.6.x/connectors/pipeline/matillion/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/matillion/index.md
I worked on Matillion Note Update in Requirements.
#
#
> Docs: Matillion Note Update in Requirements

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AdvancedSearch.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Topic.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Users.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ContainerClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/Entity.interface.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityDataClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/TableClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/glossary/Glossary.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/advancedSearch.ts
Fixes #16082
- I worked on adding the newly added advanced search filters/fields to the explore page e2e tests.
Fields added : 
- Status
- Charts
- Table Type
- Entity Type
#
#
> test(e2e): Added new Fields for e2e for advanced search filters on Explore page

- ingestion/tests/cli_e2e/test_cli_vertica.py
> MINOR: vertica e2e fix

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/DataAssetsHeader.utils.tsx
Fixes: Show sourceUrl if present for any entity
For long names:
#
#
> feat(ui): show sourceUrl if present

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
- ingestion/tests/unit/topology/dashboard/test_looker.py
Fixes #19171 - Looker parse [derived view references](https://cloud.google.com/looker/docs/derived-tables#referencing_derived_tables_in_other_derived_tables) query
#
#
> Fixes #19171 - Looker parse derived view references query

- openmetadata-docs/content/v1.6.x/connectors/pipeline/matillion/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/matillion/index.md
I worked on Matillion Pointer Updation in Requirements.
#
#
> Docs: Matillion Pointer Updation in Requirements

- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.ts
> Markdown editor fix

- openmetadata-service/src/main/java/org/openmetadata/service/resources/settings/SettingsCache.java
- Fixes issue with system repository being init to null
- Issue with email configuration in case the email setting fetch return null or exception 
below isue
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "org.openmetadata.service.jdbi3.SystemRepository.getEmailConfigInternal()" because "org.openmetadata.service.resources.settings.SettingsCache.systemRepository" is null
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2085)
at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4040)
#
#
> [MINOR] Fixes Email Issue in system repository being null

- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/classification/Auto Classification/auto-pii-tagging.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-governance/classification/Auto Classification/auto-pii-tagging.md
I worked on PII Tagging Note Removal.
#
#
> Docs: PII Tagging Note Removal

- openmetadata-docs/content/partials/v1.6/connectors/yaml/auto-classification.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/auto-classification.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/classification/Auto Classification/external-workflow.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-governance/classification/Auto Classification/external-workflow.md
I worked on Auto classification YAML and Pointers Updation.
#
#
> Docs: Auto classification YAML and Pointers Updation

- openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/MsalAuthenticator.tsx
Fixes: Popup login starts creating multiple popup with login option which is not expected. We need redirect login in case of any failure for refresh, hence eliminating it
#
#
> chore(ui): disable popup based login for msal

- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
> add missing locales

- ingestion/src/metadata/sampler/sqlalchemy/bigquery/sampler.py
- ingestion/tests/unit/profiler/sqlalchemy/bigquery/test_bigquery_sampling.py
> MINOR BQ sampler type missing

- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/data/table.ts
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
> MINOR: Add support for cluster key information - bigquery

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-discovery/troubleshooting.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-discovery/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on Troubleshooting Doc Updation in Data Discovery.
#
#
> Docs: Troubleshooting Doc Updation in Data Discovery

- ingestion/src/metadata/profiler/source/fetcher/config.py
- ingestion/src/metadata/profiler/source/fetcher/fetcher_strategy.py
- ingestion/tests/unit/profiler/test_entity_fetcher.py
the `includeViews` config of the Auto Classifier and Profiler was not properly filtering views. Updated the db fetcher to handle this configuration
#
#
> FIX - Profiler Source Include Views Filter

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestSuiteResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TestCaseResolutionStatusIndex.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java
> MINOR - Validate basic suites do have basicEntityRef

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/AsyncSelectList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/TreeAsyncSelectList.tsx
**Before:** 
https://github.com/user-attachments/assets/edf843b7-2ea8-4876-a5c4-c3d037902c41
**After:** 
https://github.com/user-attachments/assets/bbd935af-ce0e-4a17-a8d1-e61ba5ad012f
#
#
> Fix: close select dropdown when focus is shifted

- ingestion/setup.py
> MINOR: Added missing test dependencies

- ingestion/tests/cli_e2e/base/config_builders/builders.py
- ingestion/tests/cli_e2e/test_cli_snowflake.py
> Minor: Fix mysql & snowflake lineage e2e

- openmetadata-ui/src/main/resources/ui/package.json
I worked on fixing the vulnerability for the serialize-javascript reported in https://github.com/open-metadata/OpenMetadata/security/dependabot/195
#
#
> Chore(ui): Add a resolution version for serialize-javascript to fix the vulnerability

- openmetadata-docs/content/partials/v1.6/connectors/yaml/lineage.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/lineage.md
I worked on SnowFlakes YAML Correction.
#
#
> Docs: SnowFlakes YAML Correction

- openmetadata-docs/content/v1.6.x/deployment/oss-security.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/oss-security.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on OSS Security Doc Updation in Deployment.
#
#
> Docs: OSS Security Doc Updation in Deployment

- openmetadata-docs/content/v1.6.x/deployment/oss-security.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/oss-security.md
I worked on OSS Security Line Remover
#
#
> Docs: OSS Security Line Remover

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestSuite.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/DomainLabel/DomainLabel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteDetailsPage/TestSuiteDetailsPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteDetailsPage/TestSuiteDetailsPage.test.tsx
Fixes #19562 
- Fixed domain not getting displayed issue
- Added playwright test
https://github.com/user-attachments/assets/867bf0c3-50da-47f2-8c93-30fd9851543c
#
#
> fixed #19562 Domain data is not getting saved for testSuite

- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/mssql/metadata.py
- ingestion/src/metadata/ingestion/source/database/mssql/queries.py
Fixes #19552 
- Added func. to add stored procedrues description
test your changes?
#
#
> Mssql stored procedure description

- openmetadata-ui/src/main/resources/ui/src/components/Visualisations/Chart/OperationDateBarChart.tsx
- openmetadata-ui/src/main/resources/ui/src/interface/data-insight.interface.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.tsx
Fixes #19686
https://github.com/user-attachments/assets/930eeb72-bbeb-4e5c-820e-1a777fcfe483
#
#
> fix #19686: Table Update Sys Metric shows wrong value

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/ParameterForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/TestCaseForm.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/TestSuite.constant.ts
> fix #19772: Not able to see Data diff option in table test case in DataBricks service

- ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
Fix dbt Test case Timestamp issue
#
#
> Fix dbt Test case Timestamp issue

- openmetadata-docs/content/v1.6.x/quick-start/local-docker-deployment.md
Update quick-start guide to point to latest v1.6.3 version
#
#
> Update quick-start guide to point to latest v1.6.3 version

- ingestion/src/metadata/ingestion/source/database/unitycatalog/service_spec.py
- ingestion/src/metadata/profiler/interface/sqlalchemy/unity_catalog/sampler_interface.py
> Fix #19807 - Implement the right SQA Sampler for UnityCatalog

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseResultTab/TestCaseResultTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseResultTab/TestCaseResultTab.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerDetailPage/IncidentManagerDetailPage.tsx
> fix #19805: Not able to edit sql query from test case details page

- openmetadata-docs/content/v1.6.x/connectors/database/mysql/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/yaml.md
I worked on MySQL YAML Correction.
#
#
> Docs: MySQL YAML Correction

- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppMarketPlaceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/AppMarketPlaceUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
> Fix install application

- openmetadata-ui/src/main/resources/ui/src/styles/components/rjsf.less
> fix #19824 Section heading not visible in the add/edit ingestion page

- .github/workflows/trivy-scan-ingestion-base-slim-image.yml
- .github/workflows/trivy-scan-ingestion-image.yml
- .github/workflows/trivy-scan-openmetadta-server.yml
> fix: Trivy Scan CI checkout Action

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/AsyncSelectList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/TreeAsyncSelectList.tsx
Reverts open-metadata/OpenMetadata#19764
> Revert "Fix: close select dropdown when focus is shifted"

- openmetadata-service/pom.xml
- pom.xml
> Fix json smart version

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
> MINOR: Optimise Pipeline Lineage Extraction

- docker/development/docker-compose.yml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/Dockerfile.ci
- ingestion/ingestion_dependency.sh
- ingestion/setup.py
- openmetadata-docs/content/partials/v1.6/deployment/upgrade/upgrade-prerequisites.md
> MINOR - Bump Ingestion versions

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/QueryEntity.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestSuite.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/importUtils.ts
I worked on fixing the failing playwright tests on main 
#
#
> Playwright: Fix the failing playwright tests on main

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EventSubscriptionRepository.java
Fixes issue in sync offset , alert in scheduler needs to be updated as well
#
#
> [MINOR-Alerts] Remove and read alert on sync offset

- pom.xml
Fixes #19863
Lombok issue on CLI build
#
#
> Fix Lombok Annotation Processor Issues

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
> Fix Deleted filter

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> update whats new for 1.6.4

- openmetadata-service/src/main/java/org/openmetadata/service/TypeRegistry.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/types/TypeResource.java
Improve logging to indicate that missing types are expected and new type instances are created when starting the server.
#
#
> Minor : improve log message for registering new type in db

- openmetadata-docs/content/partials/v1.6/connectors/dashboard/connectors-list.md
- openmetadata-docs/content/partials/v1.7/connectors/dashboard/connectors-list.md
I worked on Power Bi Report Server Connector Updation.
#
#
> Docs: Power Bi Report Server Connector Updation

- openmetadata-docs/content/v1.6.x/connectors/database/mongodb/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mongodb/yaml.md
I worked on Mongodb Updation.
#
#
> Docs: Mongodb Updation

- openmetadata-ui/src/main/resources/ui/playwright/utils/domain.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
Fixes passing of filter
Before
https://github.com/user-attachments/assets/dde0d57a-8e6e-4eb2-b531-3820fc9547eb
After
https://github.com/user-attachments/assets/d1dc93ff-5cc2-45b9-bc33-d86aa3903af4
#
#
> pass filters when refreshing for domain assets

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/EntityDataConsumer.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/EntityDataSteward.spec.ts
> playwright: fixed timeout issue in entity related specs

- ingestion/src/metadata/ingestion/source/database/lineage_source.py
- ingestion/src/metadata/ingestion/source/database/snowflake/lineage.py
- ingestion/src/metadata/ingestion/source/database/usage_source.py
Fix #19876: Snowflake Lineage Ingestion Fails Due to KeyError
#
#
> Fix #19876: Snowflake Lineage Ingestion Fails Due to KeyError

- openmetadata-docs/content/v1.6.x/connectors/ingestion/workflows/metadata/filter-patterns/database.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ingestion/workflows/metadata/filter-patterns/database.md
I worked on Database Example 3 Note Updation
#
#
> Docs: Database Example 3 Note Updation

- openmetadata-docs/content/v1.5.x/connectors/database/mssql/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/mssql/index.md
- openmetadata-docs/content/v1.6.x/connectors/storage/gcs/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mssql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/gcs/index.md
I worked on 404 Images Fix
#
#
> Docs: 404 Images Fix

- .github/workflows/py-operator-build-test.yml
- ingestion/Dockerfile
- ingestion/Dockerfile.ci
- ingestion/operators/docker/Dockerfile
- ingestion/operators/docker/Dockerfile.ci
We had to fix with @tutte and @pellejador some packages that were failing on GH runners to deploy 1.6.4.
#
#
> VERSION - Bump ingestion debian to bookworm

- .github/workflows/py-operator-build-test.yml
- scripts/validate_sample_data.py
> CI - Fix operator build test

- .github/workflows/py-operator-build-test.yml
> CI - Update py-operator-build-test.yml

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/UserUtil.java
- openmetadata-spec/src/main/java/org/openmetadata/sdk/exception/UserCreationException.java
> Add cmd line user ops

- openmetadata-ui/src/main/resources/ui/src/components/common/ResizablePanels/PanelContainer/PanelContainer.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx
- I worked on fixing the glossary Pagination/infinite scroll issue. 
- Issue occurred due to not having the root element of the observer element.
Issue : 
https://github.com/user-attachments/assets/4e37c3a6-545d-4e06-a12d-af5c03d2b3ca
Resolved : 
https://github.com/user-attachments/assets/30455e83-1a14-4d52-86a2-32618d17c035
#
#
> MINOR: fix the glossary pagination issue

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AdvancedSearch.spec.ts
I worked on removing the custom timeout for the AdvancedSearch.spec.ts to reduce the waiting time
#
#
> Minor: Remove the custom timeout for Advanced Search playwright

- openmetadata-service/src/main/java/org/openmetadata/service/formatter/field/DomainFormatter.java
Fixes on removal of domain from entity, relevant feed not getting generated
#
#
> Minor : get domain removal activity feed update

- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
- remove unwanted code from the service ingestion page for 1.6.5
#
#
> MINOR: remove unwanted code from the service ingestion page for 1.6.5

- openmetadata-docs/content/v1.6.x/developers/architecture/code-layout.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/developers/architecture/code-layout.md
I worked on Code Layout Updation.
#
#
> Docs: Code Layout Updation

- openmetadata-ui/src/main/resources/ui/src/components/BulkImport/BulkEntityImport.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryDetails/GlossaryDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/ImportGlossary/ImportGlossary.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/ImportGlossary/ImportGlossary.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/ImportGlossary/import-glossary.less
- openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryPage/GlossaryPage.component.tsx
Fixes #19850
- I worked on fixing the scroll issue for action button in Glossary import
Issue :  
https://github.com/user-attachments/assets/ca942b73-9bb2-4c2b-a0de-ec9da7599441
https://github.com/user-attachments/assets/7d543a31-78ab-4081-b399-335f08c34417
Resolved :  
#
#
> #19850: fix the scroll issue for action button in Glossary import

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
- openmetadata-service/src/main/resources/dataInsights/config.json
Removing the `followers` property from Data Insights.
#
#
> MINOR: Remove followers from data insights processing

- bootstrap/sql/migrations/native/1.7.0/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.7.0/postgres/postDataMigrationSQLScript.sql
- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplicationConfig.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/WorkflowHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationProcessImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v150/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v170/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v150/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/MigrationFile.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
- openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/util/MigrationWorkflowTest.java
Fixing Migrations for the changes done to Governance Workflows.
#
> MINOR: Fix Migrations

- openmetadata-service/src/main/java/org/openmetadata/service/util/SchemaFieldExtractor.java
`ERROR [2025-02-25 14:41:59,419] [dw-179 - GET /api/v1/metadata/types/customProperties] o.o.s.u.SchemaFieldExtractor - Failed to load schema for type 'entityReference': Schema file not found for path: json/schema/entity/entityReference.json`
#
#
> Minor - Fix schema file path for entityReference in SchemaFieldExtractor

- .github/workflows/maven-build-collate.yml
> fix: Trigger workflow  on Pull Requests

- .github/workflows/trivy-scan-ingestion-base-slim-image.yml
- .github/workflows/trivy-scan-ingestion-image.yml
- .github/workflows/trivy-scan-openmetadta-server.yml
Updated the Trivy Scan workflow to trigger on changes to .py and .java files, along with its respective Dockerfile. This ensures that security scans run whenever relevant code or the corresponding Dockerfile is modified.
#
#
> Feat: Update Trivy Scan to Trigger Workflow on Changes to .py, .java, and Dockerfile Files

- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplicationConfig.java
Small code refactor to get a Map in a better way.
#
#
> MINOR: Small improvement

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> Minor: Added Whats new content for 1.6.5

- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/EmailMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/FeedMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/GChatMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MSTeamsMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/SlackMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
Fixes issue observerd in endocing fqns while building URL
#
#
> - Encode Urls for Diferent destinations

- ingestion/src/metadata/sampler/sqlalchemy/azuresql/sampler.py
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
Issue - While testing in test-argo for 1.6.5 release got the error message in logs while resolving the task, affecting final term status
Previously, we were always picking the first element from changeDescription.getFieldsAdded() and changeDescription.getFieldsDeleted(), in case of multiple changed fields present in changeDescription.getFieldsAdded()/Deleted() , the mapping to tagLabel class fails
```
List<TagLabel> tagLabels =
JsonUtils.readObjects((String) field.getNewValue(), TagLabel.class);
```
Logs - 
```
ERROR [2025-02-26 09:53:41,855] [dw-869 - PUT /api/v1/feed/tasks/357/resolve] o.o.s.s.SearchRepository - Issue in Updating the search document for entity [8e3ea7d3-51d4-440c-815b-249c9541c162] and entityType [glossaryTerm]. Reason[An exception with message [Failed to process JSON ] …
```
> Minor Fix - issues in SearchRepository.propagateGlossaryTags method

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
- openmetadata-service/src/main/resources/json/data/lineage/lineageCsvDocumentation.json
> Minor: Add pipeline display name in lineage export

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/CreateIngestionPipelineTask.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/RunIngestionPipelineTask.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppTask.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/flowable/builders/ParallelGatewayBuilder.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/flowable/builders/SubProcessBuilder.java
Adds the needed logic to trigger a Data Insights run for a given service.
#
#
> MINOR: Update run app to run data insights

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
> MINOR: Looker case insensitive search for users

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Container.spec.ts
- I worked on fixing fix AUT playwright failure for Container
#
#
> AUT: fix AUT playwright failure for Container

- conf/openmetadata.yaml
> Add max/min server threads config

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/IncidentManager.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizeMyData/CustomizeMyData.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/IncidentManager/IncidentManagerDetailPage/IncidentManagerDetailPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/APICollection/APICollectionUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseSchemaDetailsUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/SearchIndexUtils.tsx
Fixes: #20017 
Issue: Safari is showing API calls without the required parameter which causes issue on UI for loading the wrong feed. 
In code we had duplication for adding ActivityFeedProvider, I had work on removing those along with any other place which may have similar issue
https://github.com/user-attachments/assets/6af50198-0a97-4c99-becd-ee633cb04569
#
#
> fix(ui): #20017 remove duplicate activity feed providers

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Tour.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationsProvider/ApplicationsProvider.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationsProvider/ApplicationsProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/context/PermissionProvider/PermissionProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/GlobalSettingPage/GlobalSettingPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
Fixes: Issue with tour not triggering for `/tour` endpoint from Welcome screen. attaching recording
https://github.com/user-attachments/assets/37e4f08f-6e8a-4fff-b4f6-eb46451b0ebc
#
#
> fix(ui): tour page issue clicking on tour from welcome screen

- openmetadata-service/src/main/java/org/openmetadata/service/security/AuthenticationCodeFlowHandler.java
- openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AppRouter.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/GenericAuthenticator.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Auth/AppAuthenticators/SamlAuthenticator.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/BasicAuthProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
- openmetadata-ui/src/main/resources/ui/src/hooks/useApplicationStore.ts
- openmetadata-ui/src/main/resources/ui/src/pages/LogoutPage/LogoutPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/LogoutPage/LogoutPage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/Auth/TokenService/TokenServiceUtil.ts
- openmetadata-ui/src/main/resources/ui/src/utils/AuthProvider.util.ts
Fixes: It fix issue with refresh failure, From BE it will send redirect to serverURL which didn't clear userInfo and ends up to infinite loader on UI side 
To avoid that, created `/logout` path redirecting there from BE so that UI will clear the LoggedIn info and throw the user to the sign in page for a smoother experience 
https://github.com/user-attachments/assets/202e4105-7096-4437-bd82-2b293cb06da7
#
#
> feat(ui): support /logout path to perform logout from api redirect

- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
I worked on 1.6.5 Release Updation
#
#
> Docs: 1.6.5 Release Updation

- openmetadata-docs/content/v1.6.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.6.x/sdk/python/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/sdk/python/index.md
I worked on Version Update to 1.6.5 in Python.
#
#
> Docs: Version Update to 1.6.5 in Python

- openmetadata-docs/content/v1.6.x/deployment/azure-passwordless-auth.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/azure-passwordless-auth.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on Azure File Updation in 1.6 & 1.7.
#
#
> Docs: Azure File Updation in 1.6 & 1.7

- openmetadata-spec/src/main/resources/json/schema/api/data/createCustomProperty.json
Fixes #19942
I worked on adding a displayName when creating a CustomProperty because CustomProperty already has the displayName but CreateCustomPropertyRequest is missing it
#
#
> Add displayName field in the createCustomProperty schema

- openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts
- fix the user spec failure for the dataConsumer user permission, issue occuered due to transfer of import/export in OSS
#
#
> PLAYWRIGHT: fix the user spec failure for the dataConsumer user permission

- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
- ingestion/src/metadata/ingestion/source/database/lineage_source.py
> MINOR: Improve memeory in temp table lineage

- ingestion/src/metadata/ingestion/source/database/redshift/metadata.py
- ingestion/src/metadata/ingestion/source/database/redshift/utils.py
> MINOR: Redshift - better log for view with no schema binding

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/CreateIngestionPipelineTask.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/impl/CreateIngestionPipelineImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppTask.java
- Preventing some flowable database lock errors by setting CreateIngestionPipelineTask and RunAppTask to exclusive
- Avoid Creating an Ingestion Pipeline if one already exists
- Avoid erroring if App is not installed.
#
#
> MINOR: Workflow improvements

- .github/actions/setup-openmetadata-test-environment/action.yml
- .github/workflows/airflow-apis-tests-3_9.yml
- .github/workflows/docs-tests.yml
- .github/workflows/java-checkstyle.yml
- .github/workflows/maven-build-collate.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-postgres-tests-build.yml
- .github/workflows/maven-sonar-build.yml
- .github/workflows/monitor-slack-link.yml
- .github/workflows/phylum.yml
- .github/workflows/playwright-integration-tests-mysql.yml
- .github/workflows/playwright-integration-tests-postgres.yml
- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
- .github/workflows/publish-maven-package.yml
- .github/workflows/py-checkstyle.yml
- .github/workflows/py-cli-e2e-tests.yml
- .github/workflows/py-operator-build-test.yml
- .github/workflows/py-tests-postgres.yml
- .github/workflows/py-tests.yml
- .github/workflows/python-packages-publish.yml
- .github/workflows/security-scan.yml
- .github/workflows/selenium-noIngestion-tests.yml
- .github/workflows/sync-docs-v1.yml
- .github/workflows/trivy-scan-ingestion-base-slim-image.yml
- .github/workflows/trivy-scan-ingestion-image.yml
- .github/workflows/trivy-scan-openmetadta-server.yml
- .github/workflows/validate-jsons-yamls.yml
- .github/workflows/yarn-coverage.yml
> chore(CI): Upgrade all steps actions to latest release

- ingestion/src/metadata/ingestion/source/database/usage_source.py
Fixes #20067
I worked on DatabaseUsage workflow because of the bug described in the issue 
#
#
> Fixes 20067: Don't overwrite query to execute

- openmetadata-docs/content/v1.5.x/connectors/dashboard/tableau/index.md
- openmetadata-docs/content/v1.5.x/connectors/dashboard/tableau/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/tableau/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/tableau/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/tableau/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/tableau/yaml.md
I worked on Tableau Note Updation in Connectors.
#
#
> Docs: Tableau Note Updation in Connectors

- openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts
- openmetadata-ui/src/main/resources/ui/src/pages/UserListPage/UserListPageV1.tsx
Before
https://github.com/user-attachments/assets/137cad0c-9a40-4190-ad5e-9243863ac5e2
After
https://github.com/user-attachments/assets/042b16e1-2f62-48de-a2f6-4603353dda71
#
#
> fix search query for non admin pages

- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
- ingestion/src/metadata/ingestion/source/database/snowflake/utils.py
- unknown column error fix:
- added vector column support
#
#
> MINOR: snowflake vector col. fix, unknown col. nulltype error

- ingestion/src/metadata/ingestion/source/dashboard/sigma/client.py
- ingestion/src/metadata/ingestion/source/dashboard/sigma/connection.py
- ingestion/src/metadata/ingestion/source/dashboard/sigma/models.py
Fixes #20075   Sigma not ingesting all workbooks
#
#
> Fix Sigma not ingesting all dashboards/workbooks

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataConnectionBuilder.java
> MINOR: Fix test connection on updating bot jwt

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationsProvider/ApplicationsProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/Users.component.tsx
- I worked on fixing user profile page playwright test.
- Issue occurred due to re-render of page if changes made to team or role for the admin logged in user. Where new permission are fetch based on the current role and team. Since the permission was making in the dependency of application provider which was not needed there. Application was re-rendering!
- Also fix the HTML tags rendered in user profile description, if seeing for other user profile page.
Issue : 
Resolved : 
#
#
> MINOR: fix user profile page playwright test

- .github/workflows/py-tests.yml
> fix timeout field in pytest ci

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
Fixes https://github.com/open-metadata/openmetadata-collate/issues/1241
this is the field change I am getting:
```json
{
"fieldsAdded" : [ ],
"fieldsUpdated" : [ {
"name" : "columns.testNested.description",
"oldValue" : "testNested",
"newValue" : "nested description"
} ],
"fieldsDeleted" : [ ],
"previousVersion" : 0.1
}
```
This is my patch request:
```json
[ {
"op" : "replace",
"path" : "/columns/1/children/0/description",
"value" : "nested description"
} ]
```
This fix makes the fiel change name `columns.withNested.testNested.description`.
In this PR it is only applied to columns descriptions. But it probably needs to be applied to other fields.
#
#
> Fix 1241: fix(updater): process nested columns

- openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Auth.constants.ts
Fixes: whenever server fails with some error on loggedInUser api we are not surfacing actual error, With this changes user will see it upfront 
#
#
> chore(ui): add loggedInAPI to show actual error instead generic one

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/client.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
- ingestion/tests/unit/topology/dashboard/test_tableau.py
[#1049](https://github.com/open-metadata/openmetadata-collate/issues/1049) Dashboard Usage - Tableau, Looker
We are not supporting Powerbi usage because powerbi usage api doesn't support service principal auth.
To fetch usage metrics powerbi needs to be authenticated using username password.
#
#
> #1049 Day 1 Dashboard Usage - Tableau, Looker

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationsProvider/ApplicationsProvider.tsx
- I worked on fixing the application re-loading on profile page. Issue occurred due to re-render of page if changes made to team or role for the admin logged in user. Where new permission are fetch based on the current role and team. Since the permission was making in the dependency of application provider which was not needed there. Application was re-rendering!
Issue: 
https://github.com/user-attachments/assets/f33bfe5b-c669-430d-b5b5-8fc908492b60
Resolved: 
https://github.com/user-attachments/assets/0d620063-8227-48d8-b9f3-7e918a549997
#
#
> MINOR: fix the application re-loading on profile page team or role changes

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/client.py
- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
- ingestion/tests/unit/test_powerbi_filter_query.py
Fixes #15696 
Added method to add filter query in powerbi api call to filter out projects on call itself
A method that changes ProjectFilterPattern(if provided) into odata condition
To allow pushing down the filtering to the Power BI level, using a different API with an odata filter.
Test for method
Project Filter pattern:- 
Before odata filter:- 
After filter:- 
#
#
> Fixes #15696: Added Powerbi filter query

- openmetadata-docs/content/v1.5.x/connectors/database/adls-datalake/index.md
- openmetadata-docs/content/v1.5.x/connectors/database/adls-datalake/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/adls-datalake/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/adls-datalake/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/adls-datalake/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/adls-datalake/yaml.md
I worked on ADLS datalake Connector Change.
#
#
> Docs: ADLS datalake Connector Change

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/DescriptionSuggestion.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsProvider/SuggestionsProvider.tsx
- I worked fixing wrong suggestion count being fetched on Table entity if switch to another table from one table. Due to Provider being wrapped on the TableDetailPage!
Issue : 
https://github.com/user-attachments/assets/217e723e-2843-46aa-9ae3-023a01a0c811
Resolved : 
https://github.com/user-attachments/assets/04013c15-c947-4e34-b9ed-1ec42e9e786c
#
#
> MINOR: fix wrong suggestion count being fetched on table change

- bootstrap/sql/migrations/native/1.7.0/postgres/schemaChanges.sql
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v170/Migration.java
> MINOR: Fix cost analysis build failing for postgres

- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/default-workflows/dashboard-certification.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/default-workflows/glossary-approval.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/default-workflows/table-certification.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/elements/nodes/check-entity-attributes.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/elements/nodes/create-user-task.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/elements/nodes/set-asset-certification.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/elements/nodes/set-glossary-term-status.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/elements/triggers/event-based-entity-trigger.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/elements/triggers/periodic-batch-entity-trigger.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/workflows/how-to-edit-workflow.md
I worked on fixing the documentation links for the governance workflows
#
#
> Docs: Fix the documentation links for governance workflows

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuiteList/TestSuites.component.tsx
> fix #19869: Other columns are not visible when testSuite name is large

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/FeedRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/StoredProcedureRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
This PR fixes the issue with deletion of entities
#
#
> Fix Deletion of Entities

- openmetadata-spec/src/main/java/org/openmetadata/schema/EntityInterface.java
Required for auto tier app
#
#
> MINOR - Add UsageDetails to EntityInterface

- ingestion/src/metadata/pii/processor.py
- ingestion/src/metadata/pii/scanners/column_name_scanner.py
- ingestion/tests/unit/pii/test_column_name_scanner.py
FIX #19765
Rather than allowing to completely disable the scanner, fixing the parsing to ensure the given example passes properly.
Also, we're switching the priorities of the scan, giving preference to the NER scanner rather than the column name one, so if NER already identifies some data as not sensitive, the column name scanner won't change.
Let's get more feedback before allowing to completely disable the logic. Might be more interesting to improve the scanners rather than hiding possible issues
#
#
> FIX #19765 - Improve Column Name Scanner

- openmetadata-ui/src/main/resources/ui/src/components/ServiceInsights/service-insights-tab.less
I worked on fixing the background color for the service insights tab
**Before:**
**After:**
#
#
> Minor: Fix the service insights card background color

- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsProvider/SuggestionsProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsSlider/SuggestionsSlider.tsx
- I worked on fixing suggestion more button throwing error, due to button onClick reference were passed to the function where the function expect some arguments.
- This will fix the playwright's failure as well on main.
#
#
> MINOR: fix suggestion more button throwing error

- ingestion/src/metadata/workflow/application.py
- openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/NativeApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/OmAppJobListener.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppMarketPlaceResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/applicationConfig.json
- openmetadata-spec/src/main/resources/json/schema/entity/applications/createAppRequest.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/app.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/createAppRequest.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/marketplace/appMarketPlaceDefinition.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.ts
Reverts open-metadata/OpenMetadata#20056 to unblock collate build
> Revert "Fixes 20063: Allowing to trigger an app with a payload"

- .github/workflows/airflow-apis-tests-3_9.yml
- .github/workflows/maven-sonar-build.yml
- .github/workflows/playwright-integration-tests-mysql.yml
- .github/workflows/playwright-integration-tests-postgres.yml
- .github/workflows/publish-maven-package.yml
- .github/workflows/py-operator-build-test.yml
- .github/workflows/py-tests-postgres.yml
- .github/workflows/py-tests.yml
- .github/workflows/selenium-noIngestion-tests.yml
- .github/workflows/yarn-coverage.yml
> chore(ci): only run maven build on Main merge

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
Fixes Jdbi being null on migrations
#
#
> Fix Openmetadata Operations Jdbi null 

- openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/NativeApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsReportApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/AppScheduler.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/scheduler/OmAppJobListener.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
redo https://github.com/open-metadata/OpenMetadata/pull/20056
#
#
> feat(apps): trigger apps with config

- openmetadata-service/src/main/resources/json/data/app/DayOneExperienceApplication.json
Disable the app so it wont kill playwright
#
#
> MINOR - Update DayOneExperienceApplication.json

- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OSLineageGraphBuilder.java
Fixes import from ES that should have been from OS
#
#
> Fix Invalid Imports on the OSLineageGraphBuilder

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Markdown.spec.ts
- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.ts
Added rendering options of table, strikethough etc
https://github.com/user-attachments/assets/a2fd1276-e070-439e-b66a-f311378a2c9c
#
#
> enable showdown rendering options

- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/DescriptionTabs.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/DescriptionTabs.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/DescriptionTask.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/DiffView/DiffView.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/DiffView/DiffView.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/DiffView/diff-view.less
- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.ts
Fixes #20144
- I worked on the description diff generated for the Task.
- Have changed the diff generation from the `diffWord to diffLines` as we have moved to BlockEditor which is now an HTML and not a string. So creating a `diff` for `words` will also have the HTML tag in the diff since it calculate every words changes in it.
- Have used the BlockEditorPreviour for the diff to show,  by which the content is more in readable way around the different  formats of the BlockEditor
Previous: 
Now:
https://github.com/user-attachments/assets/85b53b6e-bc44-4a9a-ba9f-b4ea85ebac17
https://github.com/user-attachments/assets/60a1181d-c457-412f-a6c2-67770ea68410
#
#
> #20144: fix the task description viewer around the diff creation

- ingestion/tests/cli_e2e/test_cli_metabase.py
- ingestion/tests/cli_e2e/test_cli_powerbi.py
- ingestion/tests/cli_e2e/test_cli_vertica.py
> MINOR: fix e2e tests

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/IncidentManager.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/SchemaEditor.tsx
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx
Add playwright fixes for Lineage and Custom Properties
#
#
> fix playwright tests

- ingestion/src/metadata/ingestion/source/database/common_db_source.py
Fixes #19949 - Snowflake ingestion failing with table constraint error
#
#
> Fix table constraint error

- ingestion/src/metadata/sampler/sqlalchemy/sampler.py
- Use raw dataset when sample type if PERCENTAGE and sample is 100%
#
#
> fix: default to raw dataset

- openmetadata-ui/src/main/resources/ui/playwright.config.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AdvanceSearchCustomProperty.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/activityFeed.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/tag.ts
I worked on fixing playwright failure which are flaky and expected one.
- Tags.spec
- AdvanceSearchCustomPropertn.spec
#
#
> PLAYWRIGHT: fix playwright failure

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TestSuiteMultiPipeline.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/TestSuite.spec.ts
> playwright: skipping failing playwright test

- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/hooks/useCustomEditor.ts
- openmetadata-ui/src/main/resources/ui/src/components/Container/ContainerChildren/ContainerChildren.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Persona/PersonaDetailsCard/PersonaDetailsCard.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationCard/ApplicationCard.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsAlert/SuggestionsAlert.test.tsx
> fix failing unit test of block editor in main

- ingestion/src/metadata/ingestion/models/ometa_lineage.py
- ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py
- ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py
- ingestion/src/metadata/ingestion/sink/metadata_rest.py
- ingestion/src/metadata/ingestion/source/database/lineage_source.py
- ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/StoredProcedureRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/StoredProcedureIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java
- openmetadata-service/src/main/resources/elasticsearch/en/stored_procedure_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/en/table_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/stored_procedure_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/table_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/stored_procedure_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/table_index_mapping.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/storedProcedure.json
- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceQueryLineagePipeline.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/data/storedProcedure.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/data/table.ts
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/databaseServiceQueryLineagePipeline.ts
> Incremental Lineage Processing

- openmetadata-service/pom.xml
- pom.xml
Fixes 
CVE-2024-52316 - Critical
#
#
> Fixed tomcat-jdbc dependency

- ingestion/src/metadata/ingestion/source/dashboard/superset/mixin.py
- Safely handle chart SQL attribute using getattr
- Update error message for dashboard lineage details to be more generic
Fixes Superset Dashboard Lineage Handling
#
#
> Minor: Fix Superset Dashboard Lineage Handling

- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/BlockEditor.tsx
> Fix: custom prop test

- ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py
> MINOR: Fix incremental lineage if processedLineage is null

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AutoClassification.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Table.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/PersonaFlow.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Login.spec.ts
> fix: skip the failing playwright test

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> chore(ui): whats new for 1.6.6.

- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/looker/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/looker/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/powerbi/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/powerbi/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/tableau/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/tableau/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/airbyte/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dagster/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dagster/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/databricks-pipeline/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/databricks-pipeline/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dbtcloud/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dbtcloud/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/domo-pipeline/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/domo-pipeline/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/fivetran/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/fivetran/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/flink/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/flink/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/glue-pipeline/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/glue-pipeline/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/kafkaconnect/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/kafkaconnect/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/nifi/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/nifi/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/openlineage/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/spline/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/spline/yaml.md
I worked on Usage Pill Updation in 1.7 Version.
#
#
> Docs: Usage Pill Updation in 1.7 Version

- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
> chore(ci): run ingestion tests for ingestion changes

- .github/workflows/airflow-apis-tests-3_9.yml
- .github/workflows/maven-build-collate.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-postgres-tests-build.yml
- .github/workflows/maven-sonar-build.yml
- .github/workflows/playwright-integration-tests-mysql.yml
- .github/workflows/playwright-integration-tests-postgres.yml
- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
- .github/workflows/py-checkstyle.yml
- .github/workflows/py-operator-build-test.yml
- .github/workflows/py-tests-postgres.yml
- .github/workflows/py-tests.yml
- .github/workflows/trivy-scan-ingestion-base-slim-image.yml
- .github/workflows/trivy-scan-ingestion-image.yml
- .github/workflows/trivy-scan-openmetadta-server.yml
- .github/workflows/yarn-coverage.yml
> chore: Disable CI Runs on Draft Pull Requests

- openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
> MINOR: Fix DataInsights Test

- openmetadata-docs/content/partials/v1.6/connectors/yaml/workflow-config-def.md
- openmetadata-docs/content/partials/v1.6/connectors/yaml/workflow-config.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/workflow-config-def.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/workflow-config.md
I worked on Yaml file updation with ingestionPipelineFQN.
#
#
> Docs: Yaml file updation with ingestionPipelineFQN

- openmetadata-spec/src/main/resources/json/schema/api/tests/createTestCase.json
- openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/automator/addDataProductAction.json
- openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/automator/addTestCaseAction.json
- openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/automator/removeTestCaseAction.json
- openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/external/automatorAppConfig.json
- openmetadata-ui/src/main/resources/ui/src/generated/api/tests/createTestCase.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/configuration/external/automator/addDataProductAction.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/configuration/external/automator/addTestCaseAction.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/configuration/external/automator/removeTestCaseAction.ts
Prepare JSON Schemas for Test Case automator.
Taking the chance to add a missing param for DP Automator as well
#
#
> MINOR - Add Test Case Automator

- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
> chore(CI): Revert to Standard Github Runners

- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
Fixes #20245
Fixed iteration over `None` in Tableau ingestion.
#
#
> Fixes #20245

- ingestion/tests/unit/test_sample_usage.py
> MINOR: Fix pytests - usage count

- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/pyproject.toml
- ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py
- ingestion/src/metadata/ingestion/source/database/lineage_source.py
- openmetadata-airflow-apis/pyproject.toml
> MINOR: Fix Lineage in 1.6.6

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataConnectionBuilder.java
- openmetadata-service/src/main/resources/json/data/bot/autoClassificationBot.json
- openmetadata-service/src/main/resources/json/data/botUser/autoClassificationBot.json
- openmetadata-service/src/main/resources/json/data/policy/AutoClassificationBotPolicy.json
- openmetadata-service/src/main/resources/json/data/role/AuoClassificationBotRole.json
> FIX #20252 - Add Auto Classification bot

- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/deployment/docker/index.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.6.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.6.x/sdk/python/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/sdk/python/index.md
I worked on 1.6.6 Release Updation.
#
#
> Docs: 1.6.6 Release Updation

- openmetadata-docs/content/v1.5.x/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/airflow/lineage-backend.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/airflow/lineage-backend.md
> DOCS - Airflow Base URL for lineage backend

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SuggestionRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/SuggestionsResourceTest.java
> FIX #20250 - Suggestions to handle mutually exclusive tags

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/DescriptionSuggestion.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TagsSuggestion.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/suggestions.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/RetentionPeriod/RetentionPeriod.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableDescription/TableDescription.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableDescription/TableDescription.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableTags/TableTags.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Pipeline/PipelineDetails/PipelineDetails.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsAlert/SuggestionsAlert.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsAlert/SuggestionsAlert.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsAlert/SuggestionsAlert.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsAlert/suggestions-alert.less
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsProvider/SuggestionsProvider.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsProvider/SuggestionsProvider.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsProvider/SuggestionsProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsSlider/SuggestionsSlider.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Suggestions/SuggestionsSlider/SuggestionsSlider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AvatarCarousel/AvatarCarousel.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AvatarCarousel/AvatarCarousel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AvatarCarouselItem/AvatarCarouselItem.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/EntityDescription/DescriptionV1.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/Suggestion/SuggestionUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/Suggestion/SuggestionUtils.tsx
Fixes #20060
- I worked on supporting Tags Suggestion support for Table Entity
https://github.com/user-attachments/assets/9d6b6a1f-a2d9-4fcb-83fb-bfbe548d05f9
https://github.com/user-attachments/assets/6d2c0ee0-3478-460c-af0c-aa2695f146c7
https://github.com/user-attachments/assets/8e8c582b-bdeb-4917-aa07-06edab8ec2d7
#
#
> #20060: supported tags AI suggestion being showed in Table entity

- openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx
- I worked on fixing the TestConnection showing timeout even after being successful.
- The issue occurred because the running workflow could not be found within the setTimeout function, which was scheduled to run after 2 minutes. Once the execution is complete, we delete and clear the state for the workflow. As a result, when the setTimeout triggers after 2 minutes, it checks the workflow's status. However, since the TestConnection process had already finished and the data was no longer available, it triggers the timeout message in this case.
Issue : 
https://github.com/user-attachments/assets/666707f9-ffd7-4464-bb9a-ef60058f5d07
Resolved : 
https://github.com/user-attachments/assets/0662ace3-cccb-42ea-9682-5ef63c192823
#
#
> MINOR: fix test connection showing timeout even after being successfull

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AdvancedSearch.spec.ts
> Minor: Increase the timeout for advanced search beforeAll and afterAll

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuitePipelineTab/TestSuitePipelineTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestSuite/TestSuitePipelineTab/TestSuitePipelineTab.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/QualityTab/QualityTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/QualityTab/QualityTab.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/TableProfilerProvider.tsx
Fixes #19905
https://github.com/user-attachments/assets/e24c1114-1f41-4482-9f93-ece73979d20c
#
#
> fix: #19905 Data quality pipeline page is only displaying a maximum of 10 pipelines

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Permission.spec.ts
> playwright: un-skip the playwright test related to permission

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/createAndRunIngestionPipeline/CreateIngestionPipelineImpl.java
> MINOR - Add schedule to day 1 pipelines

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
> Update Data Insights to compute Tier Sources (#20128)

- .github/workflows/trivy-scan-openmetadta-server.yml
> Added MEDIUM vulnerability

- openmetadata-airflow-apis/openmetadata_managed_apis/operations/deploy.py
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/createAndRunIngestionPipeline/CreateIngestionPipelineImpl.java
> MINOR - Day 1 to set ingestion as deployed

- .github/teams.yml
> CI - Update teams.yml
