catalog-rest-service/src/main/resources/ui/src/styles/tailwind.css
catalog-rest-service/src/main/resources/ui/src/styles/x-master.css

Closes #193 
I worked on the Popover css to make links clickable on production build
#
#
</p>
#
#
@shahsank3t

Fixed non clickable link issue in popover

---

catalog-rest-service/src/main/resources/ui/src/pages/teams/index.tsx

Closes #210 
I worked on the team's page because of the need to add users and asset count.
#
#

adding number of users and asset count on teams page

---

catalog-rest-service/src/main/resources/ui/src/components/common/facetfilter/FacetFilter.tsx
catalog-rest-service/src/main/resources/ui/src/components/common/facetfilter/FacetTypes.ts
catalog-rest-service/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx
catalog-rest-service/src/main/resources/ui/src/components/common/table-data-card/TableDataCardBody.tsx
catalog-rest-service/src/main/resources/ui/src/pages/explore/index.tsx
catalog-rest-service/src/main/resources/ui/src/pages/my-data-details/index.tsx

Close #26 
I worked on the faceted filtering because previously there was no option to clear the filter selection.
#
#
#
#

adding clear filter option for faceted filters

---

ingestion/examples/shopify_schemas/tables.json

Fix #272 
tableType wasn't defined in sample tables, which caused elastic search exception errors. 
#
#
@shahsank3t

Sample Tables tableType added, fixes issue 272

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/search/SearchResource.java
ingestion/examples/kafka_schemas/topics.json

Issue #287 search api not returning all aggregations for Topics index
#
#
- [x ] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ x] I have performed a self-review of my own. 
- [ x] I have tagged my reviewers below.
- [ x] All new and existing tests passed.
#

Fix #287: search api not returning all aggregations for Topics index

---

catalog-rest-service/src/main/resources/ui/src/components/my-data-details/FrequentlyJoinedTables.tsx

Closes #333 
I worked on the frequently used table joins part because needs to sort frequently used tables based on usage.
#
#
#
#

Fixed #333 sort frequently used tables based on usage.

---

ingestion/src/metadata/ingestion/sink/elasticsearch.py
ingestion/src/metadata/ingestion/source/metadata.py

This bug happens with the following steps
1. Run clean DB, open metadata server
2. Run sample-tables connector
3. During the API requests OpenMetadataServer's even handler tries to update the elasticsearch index. 
4. At this stage we do not have any indexes yet as we didn't run the elasticsearch ingestion
5. UpdateRequests will create an index but it doesn't create document mappings
6. Which will cause the listing and explore page to break with the errors mentioned in Issue #384 
7. Fix is to check if the mappings exists even if the index exists , if not update the mapping.
#
#
@ayush-shah

Fix #384: Check if the elastic search index exists and make sure we have document mappings

---

catalog-rest-service/src/main/resources/ui/src/axiosAPIs/miscAPI.ts
catalog-rest-service/src/main/resources/ui/src/components/app-bar/Suggestions.tsx

Closes #405 , Closes #362 
I worked on the Search Suggestions Thing because the need to show suggestions for all the entities type.
#
#
#
#

Fixed #362  UI should show suggestions across all entities and group them by type

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogHealthCheck.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/ChartRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DashboardRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DatabaseRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TeamRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TopicRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/UserRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/charts/ChartResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/dashboards/DashboardResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/databases/DatabaseResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/databases/TableResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/TeamResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/UserResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/topics/TopicResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/ResultList.java
catalog-rest-service/src/main/resources/json/schema/type/basic.json
catalog-rest-service/src/main/resources/json/schema/type/paging.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/TestUtils.java

Total number of entities is required in listing APIs. The count of entities can be found in paging as shown below in list results:
```
{
"data" : [ ...],
"paging": {
"total": "count" <-- total number of entities here
"after": "afterCursor",
"before": "beforeCursor"
}
}
```
#
- [] Bug fix
#
- [ x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ x] I have performed a self-review of my own. 
- [x ] I have tagged my reviewers below.
- [x ] I have commented on my code, particularly in hard-to-understand areas.
- [x ] My changes generate no new warnings.
- [ x] I have added tests that prove my fix is effective …

Fix #379 - Add total number of entities to list APIs

---

catalog-rest-service/src/main/resources/ui/src/components/app-bar/Suggestions.tsx
catalog-rest-service/src/main/resources/ui/src/pages/explore/explore.constants.ts
catalog-rest-service/src/main/resources/ui/src/pages/explore/index.tsx

Closes #435 
I worked on the explore page and suggestion dropdown because need to add icons for entity
#
#
#
#

Added entity icons on explore tabs and suggestion dropdown

---

catalog-rest-service/src/main/resources/ui/src/components/common/error-with-placeholder/ErrorPlaceHolderES.tsx
catalog-rest-service/src/main/resources/ui/src/components/my-data-details/SampleDataTable.tsx

Closes #427 , #428 
I worked on the sample data and elastic search error placeholder because of #427 and #428
#
#
#
#

Fixed #427, #428 Sample Data breaks -UI and elastic-search unsecure mode breaks

---

catalog-rest-service/src/main/resources/ui/src/components/app-bar/Appbar.tsx
catalog-rest-service/src/main/resources/ui/src/components/dropdown/DropDown.tsx

Closes #480 
I worked on the App bar because In Secure-mode, the "Need help" icon shows the User profile image.
#
#
#
#

Fixed #480 In Secure-mode, "Need help" icon shows User profile image

---

catalog-rest-service/src/main/resources/ui/src/components/dropdown/DropDownList.tsx
catalog-rest-service/src/main/resources/ui/src/components/my-data-details/ManageTab.tsx

Closes #519 
I worked on the manage tab because if a user is an admin need to show all users and teams list for entity owner.
#
#
#
#

Fixed #519 As admin UI doesn't list the user or teams list

---

catalog-rest-service/src/main/resources/ui/src/components/recently-viewed/RecentlyViewed.tsx

Closes #537 
I worked on the Recently viewed thing because it is not showing tier info
#
#
#
#

Fixed #537 Recently viewed is not showing tier info

---

catalog-rest-service/src/main/resources/ui/src/pages/topic-details/index.tsx

Closes #539 
I worked on the topics page because max message size needs to have bytes next to it
#
#
#
#

Fixed #539 Kafka description page, max message size needs to have bytes next to it

---

catalog-rest-service/src/main/resources/ui/src/pages/topic-details/index.tsx

Closes #549 
I worked on the tabs pane because Manage should always be last tab in data asset details page
#
#
#
#

Fixed #549 Manage should always be last tab in data asset details page

---

catalog-rest-service/src/main/resources/ui/src/components/common/facetfilter/FacetFilter.tsx
catalog-rest-service/src/main/resources/ui/src/constants/constants.ts
catalog-rest-service/src/main/resources/ui/src/pages/explore/explore.constants.ts
catalog-rest-service/src/main/resources/ui/src/pages/explore/index.tsx

Closes #598 
I worked on the faceted filter because #598 
#
#
#
#

Fixed #598 Explore/Search filters should be in ordered fashion

---

ingestion/pipelines/metadata_to_es.json
ingestion/src/metadata/ingestion/ometa/openmetadata_rest.py
ingestion/src/metadata/ingestion/source/metadata.py

Ingestion tries to fetch all data in one call for tables, topics, dashboards. This will not work when we high no.of entities. This PR fixes by doing paginate with a default limit of 1000 per call.
#
#
#

Fix #605: Ingestion: metadata list apis should paginate

---

catalog-rest-service/src/main/resources/json/schema/entity/services/dashboardService.json
catalog-rest-service/src/main/resources/json/schema/entity/services/pipelineService.json
catalog-rest-service/src/main/resources/ui/src/generated/entity/services/dashboardService.ts
catalog-rest-service/src/main/resources/ui/src/generated/entity/services/pipelineService.ts
docs/openmetadata-apis/schemas/entities/dashboardservice.md
ingestion/src/metadata/generated/schema/entity/services/dashboardService.py
ingestion/src/metadata/generated/schema/entity/services/pipelineService.py

I worked on the documentation because it incorrectly referenced "messaging service" instead of "pipeline" or "dashboard".
#
#
- [] I have added tests that prove my fix is effective or that my feature works.
#

Fixes docs that reference messaging service

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/search/SearchResource.java
ingestion/src/metadata/ingestion/sink/elasticsearch_constants.py

ElasticSearch matches are case-sensitive this will not match tables with capitalized words etc.
#
#
#

Fix #611: ElasticSearch matches are case-sensitive

---

catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/charts/ChartResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/dashboards/DashboardResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/databases/TableResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/pipelines/PipelineResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/tasks/TaskResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/topics/TopicResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/TestUtils.java

Removing duplicated code
#
#
</p>
#
- [ x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ x] I have performed a self-review of my own. 
- [ x] My changes generate no new warnings.
- [ x] All new and existing tests passed.
#

Fix #644 Move duplicated validateTags method in tests to a common util

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/pipelines/PipelineResource.java

Fix #662: PipelineResource API tagging has both pipeline and pipelines causing it to divide into 2 sections in API docs

---

ingestion/setup.py
ingestion/src/metadata/ingestion/source/sql_source.py

and add the _NST (Non Standard Type) extension to the column name.
We are a heavy user of the PostgreSQL PostGIS extension and currently
columns with that type are completely dropped from the metadata.
#
#
#
- [x ] I have tagged my reviewers below.
- [ x] I have commented on my code, particularly in hard-to-understand areas.
- [ x] My changes generate no new warnings.
- [] All new and existing tests passed.
#

Map SQL columns with unknown type to VARCHAR

---

ingestion/src/metadata/ingestion/source/redash.py

I  fixed a small issue with the redash API because the dashboard id was sent instead of the slug. 
See [issue-995](https://github.com/open-metadata/OpenMetadata/issues/995)
#
#
- [ X] I have performed a self-review of my own. 
- [ X] I have tagged my reviewers below.
- [] All new and existing tests passed.
#

ISSUE-995: fix redash dashboard slug

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogHealthCheck.java

Fix #1007: Health check api returns unhealthy if there are no users bootstrapped

---

catalog-rest-service/src/main/resources/ui/src/pages/teams/index.tsx

Closes #702 
I worked on the Teams page because need to remove `Add new user` button from Users tab if logged-in user is not admin
#
#
Non-admin users:
Admin users:
</p>
#
#

Fix : UI: not show add user button if the logged-in user is not admin

---

catalog-rest-service/src/main/resources/ui/src/pages/services/index.tsx

Closes #874 
I worked on the Services page because need to update UI for search-bar based on total services available
#
#
</p>
#
#

Fix : Services search visible only after service count increases by 10

---

ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/tests/integration/ometa/test_ometa_model_api.py

Small addition that fixes #999.
We are adding the possibility of passing a `fields` list as a parameter for GET requests in the high-level API.
Thanks!
#
#
#

Add GET with fields param

---

catalog-rest-service/src/main/resources/json/schema/entity/data/topic.json

I worked on this due to #1062
#
</p>
#
#
@sureshms @harshach

Fix topic partition count min to be an integer instead of string

---

catalog-rest-service/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
catalog-rest-service/src/main/resources/ui/src/components/TableProfiler/TableProfiler.component.tsx

Fixes #1047 
I worked on the Lineage and Dataprofiler because need to add helpful text when there is no data available.
#
#
Profiler
Lineage
#
#

Fix : #1047 Lineage and Dataprofiler should show helpful text when there is no data available.

---

catalog-rest-service/src/main/resources/ui/src/components/Explore/Explore.component.tsx
catalog-rest-service/src/main/resources/ui/src/constants/explore.constants.ts
catalog-rest-service/src/main/resources/ui/src/pages/explore/ExplorePage.component.tsx

Resolved bug related to the search query on initial load
#
#
#
#

Fix: search-query bug on initial page load

---

catalog-rest-service/src/main/resources/ui/src/components/Explore/Explore.component.tsx
catalog-rest-service/src/main/resources/ui/src/components/Explore/Explore.test.tsx
catalog-rest-service/src/main/resources/ui/src/components/Explore/explore.interface.ts
catalog-rest-service/src/main/resources/ui/src/pages/explore/ExplorePage.component.tsx

- I worked on this because If we click on explore page, and switch to another tab and change the filter like click on Tier1 then if we click on explore again, it calls api with filters (Tier1).
- tab count issue fixed
- fix failing test
#
#
#
#

Fix: API call onClick of explore link from explore page

---

catalog-rest-service/src/main/resources/ui/src/components/Explore/Explore.component.tsx

I worked on this because the Filter part goes blank on click of any filter option
#
#
#
#
@shahsank3t, @darth-coder00, @Sachin-chaurasiya

fix: filter goes blank on click of any filter value

---

catalog-rest-service/src/main/resources/ui/src/components/app-bar/Appbar.tsx
catalog-rest-service/src/main/resources/ui/src/components/dropdown/AnchorDropDownList.tsx
catalog-rest-service/src/main/resources/ui/src/components/dropdown/types.ts

I worked on the #1109
Changes:- 
Make the whole area clickable for the drop-down box.
it Closes #1109 
#
#
#
#

Fix: made whole area clickable for drop-down box

---

catalog-rest-service/src/main/resources/ui/src/components/dropdown/DropDownList.tsx
catalog-rest-service/src/main/resources/ui/src/components/dropdown/types.ts
catalog-rest-service/src/main/resources/ui/src/components/tags-container/tags-container.tsx
catalog-rest-service/src/main/resources/ui/src/hooks/useWindowDimensions.ts
catalog-rest-service/src/main/resources/ui/src/utils/DropDownUtils.ts

I worked on this because Tags listing overlaps with bottom panel #1131 
Changes:-
- Add support to the auto-adjust  position of drop-down
#
#
#
#

Fix: Add support of auto positioning for tag's drop-down 

---

ingestion/src/metadata/ingestion/source/redash.py

I worked on the support of dashboard charts (widgets) in the redash connector because it is not supported in the current implementation
#
#
example of supported chart with redash
#
- [] My changes generate no new warnings.
#

ISSUE-1012 support dashboard charts of redash (widgets)

---

.github/workflows/docker-openmetadata-db.yml
.github/workflows/docker-openmetadata-ingestion.yml
.github/workflows/docker-openmetadata-server.yml
docker/local-metadata/Dockerfile_mysql

This PR fixes bug in Dockerfile_msql to build with root context as every other dockerfile is configured.
This PR also adds feature for Docker Hub Image Push workflow for openmetadata/server, openmetadata/db, openmetadata/ingestion on New Release Publishes.
@harshach , @shahsank3t  - We will require github repository secrets to be created to login to docker hub. Let's connect on getting that setup as I do not have access to create those.
Secrets Configuration -
- DOCKERHUB_OPENMETADATA_USERNAME
- DOCKERHUB_OPENMETADATA_TOKEN
#
#
</p>
#

feat: Docker Image Push Workflow

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/TestUtils.java

Bugfix for location findEntityReferenceById. getName was not returning the FQN. Now location is behaving like the other entities and the service name and the location name are joined using a dot. ```marketing.s3://bucket/dwh/schema/table```. getName was returning ```s3://bucket//dwh/schema/table``` and TestUtils was checking for ```:/``` instead of ```.```. Fixing the test uncovered the bug.
#
#
#
@sureshms @harshach

Bug fix for location findEntityReferenceById

---

catalog-rest-service/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx

Fixes #1206 
I worked on issue #1206 because the Tier tag is not showing up on assets cards.
#
#
#
#
@shahsank3t, @darth-coder00,

Fixed #1206 Tier tag is not showing up on assets cards.

---

catalog-rest-service/src/main/resources/ui/src/components/EntityVersionTimeLine/EntityVersionTimeLine.tsx
catalog-rest-service/src/main/resources/ui/src/utils/EntityVersionUtils.tsx

I worked on the versioning side panel because need to fix the summary text-overflow styling issue.
#
#
#
#

Fix : #1221 UI: Versioning right panel should wrap the summary.

---

catalog-rest-service/src/main/resources/ui/src/components/Pagination/Pagination.css
catalog-rest-service/src/main/resources/ui/src/components/Pagination/index.tsx

I worked on this because button text hover for pagination was giving hover effect only when we hover over text
#
#
#
#

Fix: Pagination button hover issue

---

catalog-rest-service/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
catalog-rest-service/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
catalog-rest-service/src/main/resources/ui/src/pages/database-details/index.tsx
catalog-rest-service/src/main/resources/ui/src/pages/service/index.tsx
catalog-rest-service/src/main/resources/ui/src/pages/tags/index.tsx

Now Non-admin/non-owner will not able to open the edit description dialog box in UI.
#
#
#
#

Fix: description issue where non-admin or non-owner can able to access edit description dialog box in UI

---

catalog-rest-service/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx

Fixes #1230
I worked on the assets tags because need to fix redundant tier tags on recently viewed cards on my data page.
#
#
#
#

Fix : Getting redundant tier tags on recently viewed cards on my data page.

---

catalog-rest-service/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx

I worked on the asset tags because of the need to fix the issue of tags not showing up if the tier tag is not present.
#
#
#
#

Fix: If tier tag is not present show other tags.

---

.github/workflows/py-checkstyle.yml
.github/workflows/py-generate.yml
ingestion/tests/unit/test_ometa_endpoints.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1260.
We currently have the make generate recipe taking care of generating the models. However, it is easy to miss updates and get code not properly aligned.
The prepared action checks all pushes against `main` that update code inside `catalog-rest-service/src/main/resources/json/**`, so it will only run if we are indeed changing JSON schemas.
Then, it will run the `make generate` recipe and push the code to the repo with a fake user `open-metadata`.
Here we might need to check if this is the right approach or if we should have a bot account with proper write permissions.
> OBS: It also fixes a random missed import that breaks a test
Thanks!
#
#
#
@sureshms @harshach, if you could take a look, please! 🙏  Any thoughts on …

[Issue-1260] - Github action to generate pydantic models

---

catalog-rest-service/src/main/resources/json/schema/entity/data/chart.json
catalog-rest-service/src/main/resources/json/schema/entity/data/dashboard.json
catalog-rest-service/src/main/resources/json/schema/entity/data/database.json
catalog-rest-service/src/main/resources/json/schema/entity/data/location.json
catalog-rest-service/src/main/resources/json/schema/entity/data/metrics.json
catalog-rest-service/src/main/resources/json/schema/entity/data/mlmodel.json
catalog-rest-service/src/main/resources/json/schema/entity/data/pipeline.json
catalog-rest-service/src/main/resources/json/schema/entity/data/report.json
catalog-rest-service/src/main/resources/json/schema/entity/data/topic.json
catalog-rest-service/src/main/resources/json/schema/entity/feed/thread.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/accessControl/rule.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/accessControl/tagBased.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/lifecycle/deleteAction.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/lifecycle/moveAction.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/lifecycle/rule.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/policy.json
catalog-rest-service/src/main/resources/json/schema/entity/services/dashboardService.json
catalog-rest-service/src/main/resources/json/schema/entity/services/databaseService.json
catalog-rest-service/src/main/resources/json/schema/entity/services/messagingService.json
catalog-rest-service/src/main/resources/json/schema/entity/services/pipelineService.json
catalog-rest-service/src/main/resources/json/schema/entity/services/storageService.json
catalog-rest-service/src/main/resources/json/schema/entity/teams/team.json
catalog-rest-service/src/main/resources/json/schema/operations/workflows/ingestion.json
catalog-rest-service/src/main/resources/json/schema/type/auditLog.json
catalog-rest-service/src/main/resources/json/schema/type/entityUsage.json
catalog-rest-service/src/main/resources/json/schema/type/jdbcConnection.json
catalog-rest-service/src/main/resources/json/schema/type/paging.json
catalog-rest-service/src/main/resources/json/schema/type/usageDetails.json

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1293.
In https://github.com/open-metadata/OpenMetadata/pull/1292 we noticed how the `codegen` tool was not properly importing all necessary `pydantic` classes. This miss in the automatic generation made it impossible to use specific modules such as `location` without fixing manually the missing classes.
As the missing class was `Extra`, in order to configure pydantic with `Extra.forbid`, a way to force the `codegen` tool to add the import is to update the JSON schemas adding the `additionalProperties: false`.
This has been a good opportunity to review all the schemas and disable random properties in the files that were missing this definition.
Thanks!
#
#
#
@sureshms @harshach @amiorin if you could please take a look! …

[Issue-1293] - Disable additional properties

---

catalog-rest-service/src/main/resources/ui/src/components/app-bar/Appbar.tsx

When running the GUI in development mode with eg
`npm run start`
the GUI shows a blank screen because of a runtime error (`"_" undefined)`) at `Appbar.tsx:293`
This PR replaces an undefined version with '?'
#
#
@shahsank3t, @darth-coder00, @Sachin-chaurasiya

Handle undefined version in GUI

---

catalog-rest-service/src/main/resources/ui/src/utils/EntityVersionUtils.tsx

Fixes #1236 
I worked on the version side panel because the owner changed data is missing from the version summary.
#
#
#
#

Fix #1236 Version Summary for owner change is missing data.

---

catalog-rest-service/pom.xml
openmetadata-ui/pom.xml

Closes #1366 
I worked on the moving `copy-resources` plugin to openmetadata-ui from catalog-rest-services pom.xml because mvn build was not picking up correct dist folder for UI package
#
#
</p>
#
#
@harshach @shahsank3t

Fix: Moved mvn copy-plugin from pom of catalog-rest-service to pom of openmetadata-ui

---

ingestion/src/metadata/__main__.py

I worked on this because some setups of Python are broken.
```python``` is install as admin and ```pip``` is installed as user. The ```PATH``` is misconfigured. They have to do ```python -m install openmetadata-ingestion``` but ```metadata``` CLI will not be found. With this patch they will be able to do ```python -m metadata docker --start``` to work around the misconfiguration of Python.
#
#
#
Ingestion: @harshach @ayush-shah @pmbrull

Fix #1385: python -m metadata should work

---

README.md

Users seem to be having difficulty getting up and running with docker-compose. In any case our installation instructions in the readme are inconsistent with what's in the docs.
I am proposing a change to the readme to direct users to our installation docs for running OpenMetadata locally.
#
#
- [x ] I have performed a self-review of my own. 
#
@harshach

Direct users to the install docs

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/MlModelRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/mlmodels/MlModelResource.java
catalog-rest-service/src/main/resources/json/schema/api/data/createMlModel.json
catalog-rest-service/src/main/resources/json/schema/entity/data/mlmodel.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/mlmodels/MlModelResourceTest.java

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1284.
It adds the following properties to the ML Model entity:
- MlStore: to indicate where the trained model file (e.g., pkl) is stored and/or where to find the Docker image
- Server: endpoint where users/integrations can access the model data or run live prediction services
#
#
#

[issue-1284] - Add MlStore and Server to MlModel

---

ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/tests/integration/ometa/test_ometa_chart_api.py
ingestion/tests/integration/ometa/test_ometa_dashboard_api.py
ingestion/tests/integration/ometa/test_ometa_database_api.py
ingestion/tests/integration/ometa/test_ometa_model_api.py
ingestion/tests/integration/ometa/test_ometa_pipeline_api.py
ingestion/tests/integration/ometa/test_ometa_table_api.py
ingestion/tests/integration/ometa/test_ometa_topic_api.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1561
While working on a tutorial for the Python API, I noticed that passing the ID from a resulting entity as `str` was too much work.
This change allows to still pass the `str` but also allows `basic.Uuid` from the `pydantic` models for simplicity.
Thanks
#
#
#

[issue-1561] - Get id as str or uuid

---

openmetadata-ui/src/main/resources/ui/src/pages/teams/index.tsx

Fixes #1602 
I worked on the Teams page because the team's page goes blank if there is no team in params.
#
#
#
#

Fix #1602 Team page goes blank if there is not team in params.

---

openmetadata-ui/src/main/resources/ui/src/axiosAPIs/serviceAPI.ts

Fixes #1407 
I worked on the Service API call because need to change how we are making put request. 
#
#
#
#

Fix #1407 PUT method for service APIs give 405 Method not allowed exception.

---

openmetadata-ui/src/main/resources/ui/src/auth-provider/AuthProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/app-bar/Appbar.tsx
openmetadata-ui/src/main/resources/ui/src/utils/APIUtils.js

Closes #1632 
I worked on the removing Welcome modal for new users as it shows up after every clean-up post new release when user has to sign-up again
#
#
</p>
#
#

Fix: Turned-off welcome message when a new user signs up

---

ingestion/src/metadata/ingestion/ometa/ometa_api.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1617.
Based on https://github.com/open-metadata/OpenMetadata/issues/1349, we can now use a proper PUT instead of a POST for creating and updating services.
All ometa integration tests pass with the change. Thanks!
#
#
</p>
#
#

[issue-1617] - Simplify service create or update

---

openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfiler.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx

I worked on the table profiler because the need to show Profiler should show primary key, non null column information in profiler tab
#
#
#
#

Fix #1626 Profiler should show primary key, non null column information in profiler tab

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/MlModelRepository.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/mlmodels/MlModelResourceTest.java

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1700.
We were duplicating some logic in `prepare` and `storeRelationship` for the MlModel regarding the dashboard href.
We are now validating that the received dashboard indeed exists and keeping the relationship setter at `storeRelationship`.
There is a new test validating that passing an invalid dashboard is flagged as 404.
Thanks!
#
#
#
@sureshms @harshach

[issue-1700] - Invalid Dashboard and duplicate logic in MlModel

---

catalog-rest-service/src/main/resources/json/schema/entity/data/table.json

fix #1662 , added Bytes as a supported datatype
#
#
</p>
#
#
@harshach

Added Bytes as a supported data type

---

ingestion/examples/workflows/trino.json
ingestion/src/metadata/ingestion/source/trino.py
ingestion/tests/unit/trino_test.py

I have decided to rename ```schema_name``` to ```database``` and make it mandatory. Without ```database``` there is an error while scanning all available tables. The connector doesn't support multiple databases at the moment. It has to be tested with passwords. Trino requires SSL if you use passwords. It has to be tested with impersonation. I have removed quote_plus because I don't think it's needed.
#
#
#

Fix #1729: Connector Trino works with username.

---

ingestion/src/metadata/ingestion/sink/metadata_rest.py

I worked on the ingestion framework because the locationType was missing from the Glue example. I have added the owner field and removed the tags because the other entities didn't have them.
#
#
#

Fix #1749: Location is missing some fields

---

docker/metadata/docker-compose.yml

Let's use explicit docker image tags with docker-compose.yaml.
This will make sure the `metadata docker --start` command will always fetch the latest version.
This issue resolves #1429 .
#
#
#

Update docker image tags to 0.6.0

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/CollectionDAO.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/UserRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/UserResource.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/UserResourceTest.java

UI needs an API to get all the users filtered by team name.
I couldn't reuse the default list implementation because the team name is in another table. A user may not have a team and this required a LEFT JOIN. A user may have multiple teams and this requires distinct. I have implemented the distinct with a group as suggested by one of our users @francescomucio.
#
#
#
@sureshms @harshach

Fix #1694: Add parameter team to filter the list of users

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx

I worked on the Faceted search Clear All button to fix position issue
#
#
</p>
#
#

Fix: Position issue of clear all button

---

openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.tsx
openmetadata-ui/src/main/resources/ui/src/styles/x-master.css

I worked on the text highlight issue because it's applying a duplicate highlight style when there is multiple texts found in a single description.
#
#
#
#

Fix: text highlight issue on search

---

.idea/encodings.xml
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/MlModelRepository.java
catalog-rest-service/src/main/resources/json/schema/entity/data/mlmodel.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/mlmodels/MlModelResourceTest.java

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1746
By adding the dataSource attribute to the MlFeatureSource we have the required ingredients to iterate on this and have proper lineage information between MlModels and Tables.
I'll prepare a follow-up PR updating the Python API to add the lineage on PUT/POST.
Thanks!
#
#
#

[issue-1746] - Add dataSource to MlModel

---

openmetadata-ui/src/main/resources/ui/src/components/common/title-breadcrumb/title-breadcrumb.component.tsx

Closes #1745 
I worked on the details page breadcrumb because need to replace the two arrow with single arrow.
#
#
#
#

Fix:  #1745 Two arrows seem unnecessary In details page breadcrumb.

---

conf/openmetadata-security.yaml

There is an error in the mysql jdbc option information in `openmetadata-security.yaml` provided as an example.
Using mysql 8.x, only `useSSL=false` option exists and `allowPublicKeyRetrieval=true` option does not exist.
A runtime error occurs.
#
#
</p>
#
#

fix: openmetadata-security.yaml jdbc-option

---

ingestion/setup.py

See #1868 
To test it.
```sh
pip install 'git+https://github.com/amiorin/OpenMetadata@ISSUE-1868#egg=openmetadata-ingestion[trino]&subdirectory=ingestion'
metadata ingest -c examples/workflows/trino.json
```

Fix #1868: Add openmetadata-ingestion-core as dependency

---

ingestion/src/metadata/ingestion/ometa/mixins/mlModelMixin.py
ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/tests/integration/ometa/test_ometa_model_api.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1834
To have the complete view of a MlModel inside a Data Platform, we had already added the possibility to have an `EntityReference` as the `dataSource` of a `MlFeatureSource`.
In this PR, we are updating the Python API to easily ingest the lineage for a given MlModel.
Thanks!
#
#

[issue-1834] - Prepare MlModel lineage

---

openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfiler.component.tsx

Fixes #1878 
I worked on the table profiler because of the need to show the column constraints.
#
#
#
#

Fix #1878 Profiler tab should show the column constraints.

---

ingestion/tests/unit/test_ometa_endpoints.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1887
A slight deja-bug, I thought we had that fixed already! Small removal of the deprecated DBT Model having its own endpoint.
Thanks!
#
#
#

[issue-1887] - Clean DBT Model

---

ingestion/src/metadata/cmd.py
ingestion/src/metadata/ingestion/source/trino.py

Both PyHive and sqlalchemy-trino were installed in my venv. I removed accidentaly sqlalchemy-trino.
Instead of getting
```
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:trino
```
I got
```
[2021-12-19 18:36:54,665] INFO     {metadata.ingestion.source.sql_source:361} - Parsing Data Models
[2021-12-19 18:36:57,887] INFO     {metadata.ingestion.source.sql_source:64} - Table Scanned: local_trino.call_center
[2021-12-19 18:36:57,887] ERROR    {metadata.ingestion.source.sql_source:148} - Table Description Error :
/Users/amiorin/.pyenv/versions/3.9.7/envs/test2/lib/python3.9/site-packages/pyhive/sqlalchemy_presto.py:151: SAWarning: Did not recognize type 'char(16)' of column 'cc_call_center_id'
util.warn("Did not recognize type '%s' of column '%s'" % (row.Type, …
```

Fix #1821: PyHive registers the trino:// schema too

---

docs/openmetadata/connectors/mysql.md

I worked on the MySql connector documentation because an option was missing in the sample connector file and I had to spend some time to figure out what was missing, with this other people will save a bit of time.
#
#
#
@harshach

Close #2006: The MySql connector sample configuration file lacks `host_port` 

---

ingestion/src/metadata/ingestion/source/access_control_policies.py
ingestion/src/metadata/ingestion/source/gcs.py

Iterable imported from collections is not working as expected in python 3.8 version.
Changed it to typing as it is compatible with other versions.
#
#
</p>
#
#
Ingestion: @harshach

Iterable from Collections not working

---

docker/local-metadata/Dockerfile
docker/metadata/Dockerfile

This PR updates the docker image.
Alpine linux is small and lightweight. Adopt Open JDK can be easily installed using `apk` command.
TODO:
Result : 
On MAC OS (M1) -
openmetadata/openmetadata-server:0.7.0 --> Image size ~ 800MB
new docker image with alpine linux --> Image size ~ 360MB
#
#

fix: update base image to alpine linux and refactor dockerflie instructions

---

.github/workflows/java-checkstyle-ro.yml
.github/workflows/java-checkstyle-rw.yml

See #2060 
The first version of this PR was reverting java-checkstyle.
Now, the second version of this PR is fixing the bug.
There are two actions. The first one is executed in the context of the PR to check the style and save the result. The second one is executed after the first one and in the context of the target (OpenMetadata/main) to leave a comment with the instructions for the developer submitting the PR with code failing the java-checkstyle.
This approach is safe as described in the [Github blog](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Fix #2060: java-checkstyle is not working anymore

---

ingestion/tests/integration/ometa/test_ometa_model_api.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/2079
With the soft delete we have name clashing in the integration tests for Ometa which cause it to sometimes fail when running them in parallel
#
#
</p>
#
#

[issue-2079] - Update naming

---

openmetadata-ui/src/main/resources/ui/src/pages/explore/ExplorePage.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/DatasetDetailsUtils.ts

Closes #2029 
I worked on the Search functionality to fix ambiguous tab switching
#
#
</p>
#
#

Fix: Search bar is searching in last active tab

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/UserDetailsModal/UserDetailsModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/UserList/UserList.tsx
openmetadata-ui/src/main/resources/ui/src/enums/user.enum.ts

Fixes #2171 
I worked on the user listing page because of the need to add a separate tab for `bots`.
#
#
#
#

Fixed : Add bots tab to group users with isBot set to true.

---

openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.tsx

Closed #2178 
Fixed issue-2178 were The 'matches' when searched for any keyword doesn't show appropriate count.
#
#
#
#

Fix: issue-2178 The 'matches' when searched for any keyword doesn't show appropriate count.

---

openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx

Fixes #2238
Fixes #2241 
I worked on the Lineage editor to fix the main node highlighting and Two nodes for the same table in lineage.
#
#
#
#

Fixed #2238 #2241 Lineage: In view mode, the main node is not highlighted and Two nodes for same table in lineage.

---

openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx
openmetadata-ui/src/main/resources/ui/src/styles/x-master.css

Tags drop-down menu is getting overlapped by another elements for tags page.
Closes #2044 
#
#
#
#

Fix:- Tags drop-down menu is getting overlapped by another elements for tags page

---

catalog-rest-service/src/main/resources/json/schema/entity/policies/accessControl/rule.json
ingestion-core/src/metadata/_version.py

For #1940 , default all rules to 25000 for priority
DataSteward will have 1000 as priority (higher priority for this special role) - set through seed data
For other roles, we won't expose priority for 0.8 release - we will default to 25000
#
#
</p>
#
#
Backend: @sureshms @harshach @Sachin-chaurasiya

Set Access Control Rule default priority to 25000

---

ingestion/src/metadata/ingestion/source/sql_source.py
ingestion/src/metadata/profiler/databases/bigquery.py
ingestion/src/metadata/profiler/profiler.py
ingestion/src/metadata/profiler/profiler_runner.py

Issue #2048 
Bigquery data profiler uses schema name instead of project id
**DRAFT PR - Work under progress**
#
#

ISSUE-2048: Bigquery data profiler uses schema name instead of project id

---

Makefile

Following #2345 and #2359, makefile updated for ingestion core to use `venv` instead of `virtualenv` as CI fails to find module for `virtualenv`.
```
/opt/hostedtoolcache/Python/3.9.9/x64/bin/python: No module named virtualenv
```
#
#
#

fix: Use venv instead of virtualenv

---

Makefile

Following #2345 and #2359, makefile updated for core_generate recipe which fails CI on Ubuntu with datamodel-codegen module not found error.
Ref - https://github.com/open-metadata/OpenMetadata/runs/4918139776?check_suite_focus=true
Steps to reproduce the CI issue - 
- `docker pull ubuntu:latest`
- `docker run -it -v OpenMetadata:/openmetadata ubuntu:latest`
- Inside docker:
- Install python3, python3-dev, python3-venv
- cd /openmetadata
- run `make core_generate`
#
#

fix: Update make core_generate to run on ubuntu as well

---

ingestion/src/metadata/cli/backup.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/2379.
Try to import boto3 only when interested in running the backup command with the upload. This allows normal use of the CLI if backup is not needed.
Thanks
#
#
</p>
#
#

Fix #2379 - CLI backup Import on call

---

ingestion/src/airflow_provider_openmetadata/lineage/utils.py
ingestion/tests/integration/lineage/airflow/test_airflow_lineage.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/2153#issuecomment-1019701270
The main issue was that `start_date` is not a required property when defining a DAG. We are now allowing the key to not exist in the DAG properties and pass that as `None`.
While checking the date conversion, we also fixed the keys for the task start and end dates. Although they are already `datetime`, we use our custom `convert_epoch_to_iso` to have the final format match both for the DAG and tasks.
Moreover, we are no longer picking up the attributes of the serialized objects from `repr`, as that forces the transformation to string and we need to transform it back with `ast.literal_eval`. The `literal_eval` does not function properly when the node is a call, which is the case for the tasks …

Fix #2153 - Lineage date parsing

---

.idea/codeStyles/codeStyleConfig.xml
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/EntityRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/dashboard/DashboardServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/database/DatabaseServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/messaging/MessagingServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/pipeline/PipelineServiceResource.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java

I allowed editing services descriptions via PUT API calls.
#
#
- [] I have tagged my reviewers below.
#

Fix #1877: Editing services description does not save

---

openmetadata-ui/src/main/resources/ui/src/components/DashboardVersion/DashboardVersion.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DashboardVersion/DashboardVersion.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/PipelineVersion/PipelineVersion.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/PipelineVersion/PipelineVersion.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/TopicVersion/TopicVersion.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TopicVersion/TopicVersion.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.tsx
openmetadata-ui/src/main/resources/ui/src/pages/EntityVersionPage/EntityVersionPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityVersionUtils.tsx

I worked on the Versions page for deleted entities
#
#
</p>
#
#
@Sachin-chaurasiya @shahsank3t

Fix: Added UI support for deleted entity versions

---

ingestion/src/metadata/ingestion/source/sql_source.py

Issue #2422 
Ingestion logs failure to parse 'NoneType' Attribute from Oracle and MSSql
#
#
#
Ingestion: @harshach @ayush-shah @pmbrull

ISSUE-2422: Handled None datatype

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/events/AbstractEventPublisher.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/slack/SlackWebhookEventPublisher.java

Fix #2439: Slack Event publisher do not throw errors when an event unpublished , fix bug for entity created events

---

ingestion/src/metadata/cli/docker.py

If the user has memory allocated less than the expected amount, it should throw an MemoryError.
As the package changed from docker-sdk to python-on-whales, the attributes and the object changed from where we fetched the allocated memory, which throws a TypeError.
Fixed that with the current PR. 
#
#
</p>
#
#
@harshach @akash-jain-10

Docker cli TypeError fixed

---

openmetadata-ui/src/main/resources/ui/src/components/app-bar/Appbar.tsx
openmetadata-ui/src/main/resources/ui/src/pages/services/index.tsx

Closes #2392 
Closes #2297 
Fix: issue-2392 & 2297: Database Services page is not responsive to 1024 resolutions & 404 screen flickers while logging out 
#
#
#2392
#2297 
https://user-images.githubusercontent.com/71748675/151779510-8bc92e90-b76f-4477-b0d6-a7835c7b2845.mov
#
#

Fix: issue-2392 & 2297: Database Services page is not responsive to 1024 resolutions & 404 screen flickers while logging out

---

openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx

I worked on the rows graph to show total row-count
#
#
</p>
#
#
@Sachin-chaurasiya @shahsank3t

Fix: #1430 Display latest value of number of rows alongside the trendline

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplication.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/config/ConfigResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/permissions/PermissionsResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/AuthenticationConfiguration.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/config/ConfigResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/permissions/PermisssionsResourceTest.java

The Api `/api/v1/config/permissions` was throwing 401 because we filter out any APIs that contain "config" in its path to avoid the JWT filter. But the permissions API was designed to serve only logged-in users which needs to pass the JWT filter to get a valid principal name.  To solve this issue, I have moved the permissions API from config resource to `/api/v1/permissions` and tested that it works when security is enabled.
#
#

Fix #2507: Getting 401 unauthorised error for retrieve permissions API

---

openmetadata-ui/src/main/resources/ui/src/components/RecentSearchedTerms/RecentSearchedTerms.tsx
openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx

Fixes #2432 
I worked on issue #2432 to add support for removing recently searched terms.
#
#
https://user-images.githubusercontent.com/59080942/152358247-4a00fadd-73c1-4714-b22f-7781b07f7348.mov
#
#

Fix #2432 Need a way to delete recently searched item on the main page.

---

catalog-rest-service/pom.xml
pom.xml

see #2530 #2529 
We do not need protobuf-java lib and excludeded out of the dependency
We already use snakeyaml-1.27 but we are snakeyaml-1.23-android due another dependency and excluded that too
#
#
</p>
#
#

Fix #2530: CVE-2021-22569 com.google.protobuf:protobuf-java, Fix #2529: 9: CVE-2017-18640 snakeyaml: Billion laughs attack via alias feature

---

bootstrap/sql/mysql/v004__create_db_connection_info.sql
catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/CollectionDAO.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/UserRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/RoleResource.java
catalog-rest-service/src/main/resources/json/schema/entity/teams/role.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/RoleResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/UserResourceTest.java
ingestion-core/src/metadata/_version.py

- Add default field to role
- Amend GET /roles to query default roles
- Assign default role to new users being created
When a new user is created, the default role is assigned to the user automatically by the backend.
Default role can be queried through GET /roles API
There is one more part remaining -- to switch default role from existing one to another.
See #2460 for details
#
#
</p>
#
#

Add support for default role 

---

openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx

Closes #2590 
I worked on the lineage editor to only allow edit if the user has permission `Update Lineage` 
#
#
#
#

Fix: #2590 not allow users (even if they own the entity) to update lineage without the "Update Lineage" permission.

---

ingestion-core/src/metadata/_version.py

Because of #2488, we need to publish a new Python package.

Bump openmetadata-core

---

ingestion/src/metadata/ingestion/source/sql_source.py

issue #2585 
dataprofile module perform check on first object only
#
#
#

Fix #2585: dataprofile module perform check on first object only

---

catalog-rest-service/src/main/resources/json/schema/entity/data/table.json
ingestion/src/metadata/ingestion/source/sql_source.py
ingestion/src/metadata/ingestion/source/vertica.py
ingestion/src/metadata/utils/column_type_parser.py

Fix #2678: Fixed vertica import errors and invalid dataTypeDisplay also added UUID data type 
#
#
#
Ingestion: @harshach @ayush-shah

Fix #2678: Fixed vertica import errors and invalid dataTypeDisplay

---

ingestion/src/metadata/ingestion/sink/elasticsearch_constants.py

ES  index mappings have json syntax error
#
#
</p>
#
#

Minor Fix: elastic search mappings

---

openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx

Fixes #2800 
I worked on the entity details page to reset lineage value when `fqn` gets changes
#
#
#
#

Fix #2800 Lineage board not updating after navigating to different service from search box

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/databases/TableResourceTest.java

Fix #2843: Ignore ordinalPosition when comparing the columns, carry forward description, tags when a column is changed

---

ingestion/src/metadata/ingestion/source/tableau.py

Tableau Lineage Implementation

---

bootstrap/sql/mysql/v004__create_db_connection_info.sql
catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/CollectionDAO.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/UserRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/RoleResource.java
catalog-rest-service/src/main/resources/json/schema/entity/teams/role.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/RoleResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/UserResourceTest.java
ingestion-core/src/metadata/_version.py

- Add default field to role
- Amend GET /roles to query default roles
- Assign default role to new users being created
When a new user is created, the default role is assigned to the user automatically by the backend.
Default role can be queried through GET /roles API
There is one more part remaining -- to switch default role from existing one to another.
See https://github.com/open-metadata/OpenMetadata/issues/2460 for details
#
#
</p>
#
#

Add support for default role  (#2631)

---

catalog-rest-service/src/main/resources/json/schema/entity/policies/accessControl/rule.json
ingestion-core/src/metadata/_version.py

I worked on this to fix the schema documentation
#
#
</p>
#
#

Fix access control rule userRoleAttr to point to roleName

---

bootstrap/sql/mysql/v004__create_db_connection_info.sql
catalog-rest-service/src/main/java/org/openmetadata/catalog/exception/CatalogExceptionMessage.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/EntityRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/UserRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/WebhookRepository.java
catalog-rest-service/src/main/resources/json/data/role/DataConsumer.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/RoleResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/UserResourceTest.java
ingestion-core/src/metadata/_version.py

Pseudocode:
```
A. patchRole(role1, default=True):
B.   set role1.default = True
for all users:
add role1 to user.roles
C.   for role in roles if role != role1:
set role.default = False
for all users:
delete role from user.roles
```
This logic ensures that changeDescription for the role(s) and user(s) are updated correctly.
Alternative considered:
Directly updating relationships with bulk sqlbatch update in entity_relationship between user and role to achieve the above.
However, this does not capture change description correctly. 
See #2460 
#
#
</p>
#
#

Support swapping default roles

---

ingestion/src/metadata/ingestion/ometa/ometa_api.py

Fix https://github.com/open-metadata/OpenMetadata/issues/2902
Getting empty payload even when no issue from OM API is raised. This might be because of specific configurations on the infra side. Let's be verbose on these scenarios
#
#
</p>
#
#

Fix #2902  - Check for empty payload

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/FeedRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedResource.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/feeds/FeedResourceTest.java

Fix #2867: Add support for GET /feed/{id}/posts

---

ingestion/src/metadata/config/workflow.py
ingestion/src/metadata/ingestion/api/processor.py
ingestion/src/metadata/ingestion/processor/query_parser.py
ingestion/src/metadata/orm_profiler/api/models.py
ingestion/src/metadata/orm_profiler/api/workflow.py
ingestion/src/metadata/orm_profiler/metrics/composed/duplicate_count.py
ingestion/src/metadata/orm_profiler/metrics/core.py
ingestion/src/metadata/orm_profiler/metrics/registry.py
ingestion/src/metadata/orm_profiler/metrics/static/avg.py
ingestion/src/metadata/orm_profiler/metrics/static/distinct.py
ingestion/src/metadata/orm_profiler/metrics/static/histogram.py
ingestion/src/metadata/orm_profiler/metrics/static/stddev.py
ingestion/src/metadata/orm_profiler/orm/functions/README.md
ingestion/src/metadata/orm_profiler/orm/functions/concat.py
ingestion/src/metadata/orm_profiler/orm/registry.py
ingestion/src/metadata/orm_profiler/processor/orm_profiler.py
ingestion/src/metadata/orm_profiler/profiles/core.py
ingestion/src/metadata/orm_profiler/sink/metadata_rest.py
ingestion/src/metadata/orm_profiler/validations/core.py
ingestion/tests/integration/orm_profiler/test_orm_profiler.py
ingestion/tests/unit/profiler/test_metrics.py
ingestion/tests/unit/profiler/test_workflow.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/2894 and partially https://github.com/open-metadata/OpenMetadata/issues/2878
There are two main changes in this PR:
- Instead of relying on all the profiling and validation logic in the Workflow, we have prepared a Processor to handle that stuff, trying to follow a more strict `workflow` logic. We have also updated the Status to properly log the results.
- We have implement new metrics:
- AVG - which also handles AVG_LENGTH for strings and text
- DISTINCT_COUNT
- DUPLICATE_COUNT
- HISTOGRAM -> This is interesting because it helped us notice that we were missing a more complex type of Metric `QueryMetric`.  We have also developed intermediate functions (CONCAT) that can be used when computing other metrics. 
#
#
<p …

Fix #2894 - Profiler Processor & Metrics

---

openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesPage.component.tsx

I worked on the roles page because it is showing blank UI when switching to the users tab.
#
#
#
#

Fix : Roles page is showing blank UI when switching to the users tab.

---

ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/src/metadata/utils/helpers.py

Fix #2901: fixed error message
```
[2022-02-22 14:36:55,902] ERROR    {metadata.ingestion.ometa.ometa_api:419} - GET DatabaseService for name/local_mysql.Error 404 - creating databaseService instance for local_mysql
```
#
#
#

Fix #2901: fixed error message

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DashboardRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DatabaseRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/GlossaryTermRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TeamRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/UserRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java

I worked on this to simplify the codebase
#
#
</p>
#
#

Refactor EntityReference list population with id list for a given entity type

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/FeedRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/UserRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedUtil.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/DefaultAuthorizer.java
catalog-rest-service/src/main/resources/json/schema/entity/feed/thread.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/feeds/FeedResourceTest.java

Fix #2865: Thread should have its own message and posts should only be the replies

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/RoleResource.java
catalog-rest-service/src/main/resources/json/schema/entity/teams/role.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/RoleResourceTest.java
ingestion-core/src/metadata/_version.py

Support returning teams for GET /roles

---

openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/Webhooks.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/pages/Webhooks/WebhooksPageTest.java

I worked on the adding selenium tests for Webhooks page
#
#
#
@darth-coder00 @shahsank3t

Adding Webhooks selenium tests

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/UserRepository.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/RoleResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/UserResourceTest.java

Assign default roles from Teams to User

---

openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/Common.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/DashboardDetails.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/DashboardServicePage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/DatabaseServicePage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/ExplorePage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/MessagingServicePage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/MyDataPage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/PipelineDetails.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/PipelineServicePage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/RolesPage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/TableDetails.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/TagsPage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/TeamsPage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/TopicDetails.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/UserListPage.java
openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/objectRepository/UserPage.java

Use RequiredArgsConstructor in openmetadata-ui/*.java

---

ingestion/src/metadata/ingestion/source/presto.py

Fix #2946: Presto Ingestion issues fix
The error `[2022-02-25 12:43:58,436] ERROR    {metadata.ingestion.source.sql_source:170} - Failed to generate sample data for dbgen_version - (pyhive.exc.DatabaseError) {'message': "Could not serialize column 'dv_create_time' of type 'time(3)' at position 1:3"` is a [bug](https://github.com/trinodb/trino/issues/6852) with presto and has been fixed in later version of trino.
Although while ingesting presto I noticed datatype related errors
```
/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/pyhive/sqlalchemy_presto.py:151: SAWarning: Did not recognize type 'char(16)' of column 'w_warehouse_id'
util.warn("Did not recognize type '%s' of column '%s'" % (row.Type, row.Column)) …
```

Fix #2946: Presto Ingestion issues fix

---

ingestion/examples/workflows/clickhouse_usage.json
ingestion/setup.py
ingestion/src/metadata/ingestion/source/clickhouse.py
ingestion/src/metadata/ingestion/source/clickhouse_usage.py
ingestion/src/metadata/utils/sql_queries.py

Fix #2937: added clickhouse usage connector
#
#
#

Fix #2937: added clickhouse usage connector

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java

Fix #2996: ChangeEventHandler throws NPE at times

---

ingestion/src/metadata/ingestion/source/metabase.py

I worked on the adding lineage in metabase.
#
#
#

Metabase lineage

---

catalog-rest-service/pom.xml
catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/MessageParser.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/ChangeEventParser.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/feeds/FeedResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/feeds/MessageParserTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/ChangeEventParserTest.java

See #2834 
In this patch, I have implemented the following changes:
- Added support for column level entity links
- Merged add and delete events into one update event
- Show inline diff of the changes done (with html tags for UI to render, since there is no markdown support for font colors)
- Add change type to the thread's message to know whether its a minor or a major version change
- Added unit tests
#
#
The API response of Feed API will now be like this with html tags that can rendered nicely in the UI:
```
{
"id": "5c0e6146-bfbd-446d-a335-a3e9d21fb852",
"href": "http://localhost:8585/api/v1/feed/5c0e6146-bfbd-446d-a335-a3e9d21fb852",
"threadTs": 1645943657593,
"about": "<#E/table/local_mysql.sample_db.lineorder/columns>",
"createdBy": "anonymous",
"updatedAt": 1645943657593, …
```

Fix #2834: Merge the change events 'delete' and 'add' as 'update' for Activity Feed

---

catalog-rest-service/src/main/resources/json/schema/entity/services/dashboardService.json
ingestion-core/src/metadata/_version.py
ingestion/examples/workflows/powerbi.json
ingestion/setup.py
ingestion/src/metadata/ingestion/source/powerbi.py

Power BI connector

---

ingestion/src/metadata/ingestion/sink/elasticsearch.py

ES index: ignore any errors during the es index

---

Makefile

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/3040
We were missing checks on tests and examples directories. This PR updates the recipes to include everything but `generated` in the formatting rules.
Thanks
#
#
</p>
#
#

Fix #3040 - py_format recipe includes more paths

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/TeamResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/DefaultAuthorizer.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/SecurityUtil.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/JsonPatchUtils.java
catalog-rest-service/src/main/resources/json/schema/entity/policies/accessControl/rule.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/permissions/PermisssionsResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/TeamResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/JsonUtilsTest.java

See #2950
This supports creation of a role and adding UpdateTeam permission to the role.
Any user that has this role can update team composition of users
#
#
</p>
#
#

Add UpdateTeam permission support

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/FeedRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedResource.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/feeds/FeedResourceTest.java

Fix #2866: Add support for PATCH to feed API to be able to resolve a thread

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/elasticsearch/ElasticSearchIndexDefinition.java
catalog-rest-service/src/main/resources/elasticsearch/glossary_index_mapping.json
ingestion/src/metadata/ingestion/models/table_metadata.py
ingestion/src/metadata/ingestion/sink/elasticsearch.py
ingestion/src/metadata/ingestion/sink/elasticsearch_constants.py

Fix #3051: Glossary-term suggest api has fqdn same as name

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java

I worked on this to simplify the code changes on how default role is allocated to users.
- Avoid change description updates for each user when their role is changed
- Simplify the codebase
#
#
</p>
#
#

Simplify default role allocation for users

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/dashboard/DashboardServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/database/DatabaseServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/messaging/MessagingServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/pipeline/PipelineServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/Authorizer.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/DefaultAuthorizer.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/NoopAuthorizer.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/SecurityUtil.java

Fix #3067: Service Creation should only be done by Bots or admins and Update only by the owners

---

ingestion/setup.py

Excluding db2 from all plugins, as it causes `_arch` issues on some os platforms
#
#
</p>
#
#
@harshach @akash-jain-10 @pmbrull

Excluding db2 from all plugins

---

ingestion/src/metadata/ingestion/source/sql_alchemy_helper.py
ingestion/src/metadata/profiler/common/database_common.py

Added connect_args and options for the creation of engine
#
#
</p>
#
#

Sql_alchemy_helper Engine fix

---

ingestion/examples/workflows/redshift.json
ingestion/src/metadata/ingestion/source/redshift.py

I worked on the fixing ingestion in redshift having "." operator in table name.
fix #3098 
#
#
#

Redshift-table-name-fail-fix-in-query

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/ChangeEventParser.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/ChangeEventParserTest.java

Fix #3080: Activity Feed: Blank feed on my-data page for updating user's role or team

---

ingestion/src/metadata/ingestion/source/salesforce.py

I worked on fixing column issue in salesforce. 
fix #3137
#
#

column-issue-fixed

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/RulesModal/AddRuleModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/dropdown/AnchorDropDownList.tsx
openmetadata-ui/src/main/resources/ui/src/interface/types.d.ts
openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/index.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/index.tsx

Closes #3140 
I worked on issue #3140 
#
#
#
#

Fix #3140 UI Allow users to update teams based on updateTeams permission.

---

catalog-rest-service/src/main/resources/json/schema/tests/column/columnValuesToBeNotInSet.json
ingestion-core/src/metadata/_version.py
ingestion/examples/sample_data/datasets/tableTests.json
ingestion/src/metadata/orm_profiler/profiles/core.py
ingestion/src/metadata/orm_profiler/validations/column/column_values_not_in_set.py
ingestion/tests/unit/profiler/test_session_validations.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/3112
We have:
- Added some safety when getting column profile data
- Constrained a bit more a test type value
- Added sample tests
- Changed the name of columnValuesToBeNotInSet from `values` to `forbiddenValues`, otherwise pydantic was having a hard time with the parsing. This should fix https://github.com/open-metadata/OpenMetadata/issues/3143
Thanks
#
#
</p>
#
#

Fix #3112 - col profile safety & sample data

---

openmetadata-ui/src/main/resources/ui/src/axiosAPIs/userAPI.ts
openmetadata-ui/src/main/resources/ui/src/components/Modals/ConfirmationModal/ConfirmationModal.tsx
openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesPage.component.tsx

Closes #2874 
I worked on issue #2874 
#
#
#
#

Fix #2874Support ability to select a role as default from the UI

---

catalog-rest-service/src/main/resources/json/schema/tests/column/columnValuesToMatchRegex.json
ingestion-core/src/metadata/_version.py
ingestion/src/metadata/orm_profiler/metrics/static/ilike_count.py
ingestion/src/metadata/orm_profiler/metrics/static/like_count.py
ingestion/src/metadata/orm_profiler/profiles/core.py
ingestion/src/metadata/orm_profiler/validations/column/column_values_to_match_regex.py
ingestion/src/metadata/orm_profiler/validations/core.py
ingestion/tests/unit/profiler/test_metrics.py
ingestion/tests/unit/profiler/test_session_validations.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/3105
- Fixed the implementation of LIKE and ILIKE metrics
- Fixed table queries to handle Hive issues for column count
- Added proper debugging to ease tracing of issues
- Implemented ColumnValuesToMatchRegex & fixed the JSON Schema title
#
#
</p>
#
#

Fix #3105 - ColumnValuesToMatchRegex & other fixes

---

ingestion/src/metadata/ingestion/processor/query_parser.py

User was facing 
[2022-03-04 16:40:24,291] INFO     {metadata.ingestion.source.sql_source_common:33} - Table Scanned:
[2022-03-04 16:40:24,291] ERROR    {metadata.ingestion.processor.query_parser:74} - strptime() argument 1 must be str, not datetime.datetime
Strptime expecting str got datetime fix
#
#
</p>
#
#

Fix: Query Parser

---

ingestion/src/metadata/ingestion/ometa/superset_rest.py
ingestion/src/metadata/ingestion/source/superset.py

Fix #3066: Superset Auth Fixed
#
#
#

Fix #3066: Superset Auth Fixed

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/security/DefaultAuthorizer.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/NoopAuthorizer.java

I worked on this to fix an issue where Entity team is not found while running the app
ForceRegister team as work around for now
#
#
</p>
#
#

Fix entity not found in Authorizer init

---

ingestion/setup.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/3181
- Fix ES version, as it was just picking 7.13.1. This speeds up the process
- Bump down redash version. 0.1.9 uses click > 8, while we are still at 7. That change might impact other dependencies in the dependency tree because it completely broke the CI pipeline. @codingwithabhi, please review that version 0.1.8 works for your latest patch as well
Thanks
#
#
</p>
#
#

Fix #3181  - Align ingestion requirements

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/FeedRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/feeds/FeedUtil.java
catalog-rest-service/src/main/resources/json/schema/api/feed/createPost.json
catalog-rest-service/src/main/resources/json/schema/entity/feed/thread.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/feeds/FeedResourceTest.java

Fix #3124: Activity Feed: Add support for deleting a post

---

openmetadata-ui/src/main/resources/ui/src/utils/AuthProvider.util.ts

fix: Azure SSO Scopes

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditor.tsx
openmetadata-ui/src/main/resources/ui/src/styles/x-master.css
openmetadata-ui/src/main/resources/ui/yarn.lock

Fixes #3163 
I worked on issue #3163 
#
#
#
#

Fix #3163 Description not capturing Bold/Italic. 

---

catalog-rest-service/src/main/resources/json/schema/tests/column/columnValuesLengthsToBeBetween.json
catalog-rest-service/src/main/resources/json/schema/tests/table/tableColumnCountToEqual.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/databases/TableResourceTest.java
ingestion-core/src/metadata/_version.py
ingestion/src/metadata/orm_profiler/validations/column/column_values_length_to_be_between.py
ingestion/src/metadata/orm_profiler/validations/table/table_column_count_to_equal.py
ingestion/tests/unit/profiler/test_validation_parsing.py
ingestion/tests/unit/profiler/test_validations.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/3217
When parsing JSONs into pydantic classes we need the `config` dict to be unique, otherwise pydantic messes up and does not pick the proper class. In this PR I am updating some names of properties to offer the unicity to the parser, but we will need to maybe rethink a bit the defs.
We will still need to fix the `columnValuesToBeUnique` vs. `columnValuesToBeNotNull`. As config is empty in these cases, we cannot guarantee that the proper class gets parsed. cc @harshach I'll open a new issue for them.
cc @Sachin-chaurasiya @ShaileshParmar11, please review the updated JSONs in case we need to make some naming changes in the UI.
Thanks,
#
#
<p align="center">For frontend related change, please link screenshots of your …

Fix #3217 - Test case props should be unique

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/ColumnTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.tsx

I fixed issue-3216 Data Quality - Min and Max value config error
Closes #3216 
#
#
https://user-images.githubusercontent.com/71748675/157029905-a865c325-2bec-49bc-85b5-dbd54d8a7ffe.mov
Preview (Screenshots) :
#
#

Fix: issue-3216 Data Quality - Min and Max value config error

---

catalog-rest-service/src/main/resources/json/schema/tests/column/columnValuesToBeNotNull.json
catalog-rest-service/src/main/resources/json/schema/tests/column/columnValuesToBeUnique.json
ingestion-core/src/metadata/_version.py
ingestion/tests/unit/profiler/test_validation_parsing.py

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/3221
We are adding some default properties to columnValuesToBeUnique and columnValuesToBeNotNull JSONs so that they can be properly parsed by pydantic
#
#
</p>
#
#

Fix #3221 - columnValuesToBeUnique vs. columnValuesToBeNotNull JSONs

---

bootstrap/sql/mysql/v004__create_db_connection_info.sql
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/CollectionDAO.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java
catalog-rest-service/src/main/resources/json/data/role/DataConsumer.json
catalog-rest-service/src/main/resources/json/schema/entity/teams/role.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/RoleResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/UserResourceTest.java
ingestion-core/src/metadata/_version.py
openmetadata-ui/src/main/resources/ui/src/generated/entity/teams/role.ts
openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesPage.component.tsx

Issue-3234: Rename default in role_entity to defaultRole

---

catalog-rest-service/src/main/resources/json/schema/entity/data/table.json
ingestion-core/src/metadata/_version.py
ingestion/examples/sample_data/datasets/tables.json
ingestion/src/metadata/orm_profiler/metrics/composed/distinct_ratio.py
ingestion/src/metadata/orm_profiler/metrics/composed/duplicate_count.py
ingestion/src/metadata/orm_profiler/metrics/composed/unique_ratio.py
ingestion/src/metadata/orm_profiler/metrics/registry.py
ingestion/src/metadata/orm_profiler/metrics/static/column_count.py
ingestion/src/metadata/orm_profiler/metrics/static/count.py
ingestion/src/metadata/orm_profiler/metrics/static/count_in_set.py
ingestion/src/metadata/orm_profiler/metrics/static/distinct_count.py
ingestion/src/metadata/orm_profiler/metrics/static/histogram.py
ingestion/src/metadata/orm_profiler/metrics/static/ilike_count.py
ingestion/src/metadata/orm_profiler/metrics/static/like_count.py
ingestion/src/metadata/orm_profiler/metrics/static/max_length.py
ingestion/src/metadata/orm_profiler/metrics/static/mean.py
ingestion/src/metadata/orm_profiler/metrics/static/min_length.py
ingestion/src/metadata/orm_profiler/metrics/static/null_count.py
ingestion/src/metadata/orm_profiler/metrics/static/row_count.py
ingestion/src/metadata/orm_profiler/metrics/static/stddev.py
ingestion/src/metadata/orm_profiler/metrics/static/unique_count.py
ingestion/src/metadata/orm_profiler/profiles/core.py
ingestion/src/metadata/orm_profiler/profiles/default.py
ingestion/tests/integration/ometa/test_ometa_table_api.py
ingestion/tests/unit/profiler/test_metrics.py
ingestion/tests/unit/profiler/test_profiler.py
openmetadata-ui/pom.xml

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/3248 and fixes https://github.com/open-metadata/OpenMetadata/issues/3251.
We have:
- Removed `missingPercentage` and `missingCount` from the columnProfile. It just makes sense in tests.
- Added `distinctProportion` to columnProfile
- Refactored and properly differentiated unique and distinct metrics
- Updated metrics test with more data
- Updated profiler QueryMetric runner
- Added missing `@property` to a bunch of metrics.
Thanks
#
#
</p>
#
#

Fix #3248 & #3251 - Update metrics and column profile

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/ActivityFeedCard.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/UserDetailsModal/UserDetailsModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx

I worked on the UI feedback , see #3115 
#
#
#
#

UI : Addressing 0.9.0 Feedback Part 2

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/AddDataQualityTest.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/ColumnTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQualityTab/DataQualityTab.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQualityTest/DataQualityTest.tsx
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfiler.component.tsx
openmetadata-ui/src/main/resources/ui/src/generated/tests/column/columnValuesToBeNotNull.ts
openmetadata-ui/src/main/resources/ui/src/generated/tests/column/columnValuesToBeUnique.ts
openmetadata-ui/src/main/resources/ui/src/interface/dataQuality.interface.ts
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/tour-page/TourPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx

Closes #3223 Data Quality - Add Test Button
Closes #3228 Data Quality - Test on complex types
Closes #3260 Data Quality - columnValuesToBeUnique & columnValuesToBeNotNull JSON UI
Closes #3243 Data Profiler - Add Test against column should have said column selected by default
#
#
Closes #3223 Data Quality - Add Test Button
Closes #3228 Data Quality - Test on complex types
Closes #3260 Data Quality - columnValuesToBeUnique & columnValuesToBeNotNull JSON UI
Closes #3243 Data Profiler - Add Test against column should have said column selected by default
https://user-images.githubusercontent.com/71748675/157252862-5f33fffc-d121-4824-86b3-e38c5b2fde0e.mov
#
#

Fix: Data quality bug fixes

---

openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.tsx

Closes #3312 
I worked filter out the owned object with entities in user profile and alignment issue fixed.
#
#
#
#

fixed issue-3312: filter out the owned object with entities

---

openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfiler.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/fonts.css
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx

Closes #3333
1. Work on fixing timestamp issue were its not allow to add test from profiler when `timestamp is without time zone`.
2. Added support to filter column test options for `DATE` datatype
#
#
#
#
@Sachin-chaurasiya @darth-coder00 @shahsank3t

Fixed issue: 3333 Data Quality - Check tests being supported in Date but not Timestamp

---

ingestion/src/metadata/cli/docker.py

Logs currently before this fix were printing twice.
Changed those to once.
Fix #3377
#
#
</p>
#
#
@harshach @akash-jain-10

Fix 3377: Logs to be printed only once

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/constants/DatasetDetails.constants.ts
openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx

Closes #3406 
Changed toast message for adding and editing test, also added toast notification for deleting test successfully. to keep consistent ui as we are showing toast notification for edit and add
Closes #3452 
Config value is not getting display in edit mode for `columnCoun`
#
#
#3406
https://user-images.githubusercontent.com/71748675/158559188-541ccea3-7b8e-4e91-ac23-966836d01df4.mov
#3452 
https://user-images.githubusercontent.com/71748675/158558397-b04b5798-33ce-4bd1-8543-7b27443217ab.mov
#
#
@harshach @vivekratnavel @Sachin-chaurasiya @shahsank3t @darth-coder00

Fix issue-3406 wrong toast on UI for editing tests, issue-3452 config value is not getting display in edit mode

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/AddDataQualityTest.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/ColumnTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQualityTab/DataQualityTab.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQualityTest/DataQualityTest.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQualityTest/Table/DataQualityTable.tsx
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfiler.component.tsx

Closes #3431 Incorrect UI exception for adding tests to deleted entities
#
#
https://user-images.githubusercontent.com/71748675/158586679-f8ecf82f-c6e7-434e-a9ce-649c7a54cd9d.mov
#
#
@shahsank3t @Sachin-chaurasiya @darth-coder00 @harshach @vivekratnavel

Fix issue-3431 Incorrect UI exception for adding tests to deleted entities

---

openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
openmetadata-ui/src/main/resources/ui/src/enums/entity.enum.ts
openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.tsx

I have filter out the other entity except data assets.
Closes #3473 
#
#
#
#
@harshach @vivekratnavel @darth-coder00 @Sachin-chaurasiya

Fix issue-3473: we need to show only assets in owned and following tab.

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/GlossaryReferenceModal/GlossaryReferenceModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/GlossaryReferenceModal/GlossaryReferenceModal.tsx

Closes #3263 
I worked on the fixing issue of saving empty references in glossary terms
#
#
</p>
#
#
@vivekratnavel @Sachin-chaurasiya @harshach

Fixed #3263: Able to save an empty reference in glossary term

---

ingestion/src/metadata/ingestion/source/mysql.py

Fix #3487: fixed MySQL multiple database ingestion issue
#
#
#

Fix #3487: fixed MySQL multiple database ingestion issue

---

openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.tsx

Closes #3554 Href links don't work in description dropdown
#
#
https://user-images.githubusercontent.com/71748675/159419130-dea986c7-345f-43f7-83f5-e91b5032478f.mov
#
#

Fix issue-3554: Href links don't work in description dropdown

---

.github/workflows/py-tests.yml

Tests are failing because of timeout being too near to the threshold
#
#
</p>
#
#
@harshach @akash-jain-10 @pmbrull

Modifying Timeout for PyTests

---

openmetadata-ui/src/main/resources/ui/package.json

Added text summary for unit test coverage, that will report coverage like shown below:
```
=============================== Coverage summary ===============================
Statements   : 39.91% ( 7230/18115 )
Branches     : 18.14% ( 2734/15068 )
Functions    : 21.24% ( 794/3738 )
Lines        : 37.56% ( 5871/15632 )
================================================================================
```

Add text-summary reporting for UI unit test coverage

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DatabaseRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DatabaseServiceRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/EntityRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/GlossaryTermRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/MlModelRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/RoleRepository.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java

See #3497 for details of the bug. This bus is due to code not handling finding owner for an asset or team for a user due to incorrect method call in the backend to retrieve the data from the database.
#
#
#

Fixes #3497 API fails to return assets and users belonging to team when the team is deleted

---

openmetadata-ui/src/main/resources/ui/src/pages/login/index.tsx

Closes #2833 UI: Sandbox page overflows from the bottom
#
#
https://user-images.githubusercontent.com/71748675/159757042-1cfc19fb-8d44-438b-bbb6-71829c755848.mov
#
#
@shahsank3t, @darth-coder00, @Sachin-chaurasiya @harshach @vivekratnavel

Fix issue-2833: UI: Sandbox page overflows from the bottom

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TeamRepository.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/TeamResourceTest.java

Fix #3612 Team Patch API is not updating isJoinable field

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplicationConfig.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/config/ConfigResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/sandbox/SandboxConfiguration.java

See #3626 
Now, we can add the following config to openmetadata.yaml to enable sandbox mode
```
sandboxModeEnabled: true
```
And get the value of the config with `/api/v1/config/sandbox` with the following response
```
{
"sandboxModeEnabled": true
}
```
#
#
#

Fix #3626 Add a config API for sandbox mode

---

conf/openmetadata-security.yaml
conf/openmetadata.yaml

Added ENV variable support for the `sandboxModeEnabled` flag
#
#

Add ENV variable support for sandbox mode enabled config

---

catalog-rest-service/src/main/resources/json/schema/api/data/createMlModel.json
catalog-rest-service/src/main/resources/json/schema/entity/data/mlmodel.json
ingestion-core/src/metadata/_version.py

Fix #3726
With the addition of EntityName and fullyQualifiedEntityName, we can clean up the mlmodel.json definitions. Without those changes, the tests were failing.
#
#
</p>
#
#

Fix #3726 - Remove mlmodel custom defs

---

catalog-rest-service/src/main/resources/json/schema/entity/services/connections/database/trinoConnection.json
docs/integrations/connectors/trino.md
ingestion/src/metadata/ingestion/source/trino.py
ingestion/src/metadata/utils/engines.py
ingestion/src/metadata/utils/source_connections.py
ingestion/tests/unit/source_connection/test_trino_connection.py
ingestion/tests/unit/test_source_url.py

Refactor trino connection to use  Json Schema definition
Allow proxies for the trino ingestion connection via the optional `proxies` field in TrinoConfig
Trino python client allows to setup proxies via `proxies` key in `http_session` field.
#
#
#
#

Refactor Trino Connector and allow proxy setup in trino connection config

---

catalog-rest-service/src/main/resources/json/schema/metadataIngestion/databaseServiceQueryUsagePipeline.json

Added result limit in DatabaseServiceQueryUsagePipeline
#
#
#

Added result limit in DatabaseServiceQueryUsagePipeline

---

openmetadata-ui/src/main/resources/ui/src/components/EntityList/EntityList.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/explore.constants.ts

Fixes #3993 
I worked on issue #3993 
#
#
https://user-images.githubusercontent.com/59080942/162582297-a2139920-1788-4786-9ace-e85e1f5b62e7.mov
#
#

Fix #3993 Selecting a service type filter should only list the databases that belong to the service type

---

ingestion/src/metadata/utils/engines.py

Fix #4032 
create_engine method requires options to be passed as dictionary. The options were assigning as a ConnectionOptions objects so that is needed to be converted to dictionary.
Also previously an empty dictionary was being passed if the options were empty. We can pass. an empty ConnectionOptions object now and it will be converted to dictionary
#
#
#
@pmbrull please check the implementation

Fixes to connection options in create engine

---

ingestion/src/metadata/ingestion/models/encoders.py
ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/tests/integration/ometa/test_ometa_service_api.py
openmetadata-airflow-apis/src/openmetadata/operations/deploy.py

Fix #4171 
The main issue here was that we were not handling properly secretStr when creating services. We've prepared a custom encoder to show them correctly when converting to JSON
#
#
</p>
#
#

Fix #4171 - Prepare custom encoder for SecretStr

---

ingestion/src/metadata/ingestion/source/clickhouse_usage.py
ingestion/src/metadata/ingestion/source/mssql_usage.py
ingestion/src/metadata/ingestion/source/redshift_usage.py
ingestion/src/metadata/ingestion/source/snowflake_usage.py

```
Traceback (most recent call last):
File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/bin/metadata", line 8, in <module>
sys.exit(metadata())
File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/Users/mayursingal/Desktop/ulixius1/OpenMetadata/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke …
```

Usage Engine Connection Fix

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/CollectionDAO.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/UserResourceTest.java

Fix #4201: Query with 'before' params is failing for Users API

---

openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/index.tsx

Closes #4208 
I worked on the teams page to allow owners to remove users from team
#
#
https://user-images.githubusercontent.com/86726556/164063373-27ae8f99-ddb2-49d5-aef8-7ee5c52c1bea.mov
</p>
#
#
@harshach @open-metadata/ui

Fix #4208: Owner of a team should be able to delete a user

---

ingestion/src/metadata/ingestion/source/snowflake.py

Snowflake throws private key attribute not found error when sent an empty dictionary
#
#
</p>
#
#

Fixed Snowflake 

---

ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py
ingestion/src/metadata/ingestion/sink/metadata_rest.py

Lineage was not getting created when schema name was was appearing twice. Added a condition to handle the use case
#
#
#

Fixed lineage issue for double schema name

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/airflow/AirflowRESTClient.java
catalog-rest-service/src/main/resources/json/schema/entity/services/ingestionPipelines/ingestionPipeline.json
openmetadata-airflow-apis/src/openmetadata/api/apis_metadata.py
openmetadata-airflow-apis/src/openmetadata/api/rest_api.py
openmetadata-airflow-apis/src/openmetadata/operations/status.py

Fix #4258 
- Return 404 if DAG is not in the DagBag
- Return empty if the DAG has not been run yet
- Discard searching for specific runId, as it is not used from UI
Added `deployed` field to IngestionPipeline which gets informed as true/false from `pipelineStatus` query param
#
#
</p>
#
#

Fix #4258 - Check dag bag and discard run id search

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/security/DefaultAuthorizer.java

Fix #4336: in HA setup, multiple instances of OpenMetadata servers try to create admin users and one of them will fail

---

openmetadata-ui/src/main/resources/ui/src/components/common/react-select-component/ReactSelectMultiInput.tsx

Now we can remove the filter pattern if we want.
Closes #4276 
#
#
#
https://user-images.githubusercontent.com/71748675/164446681-2884d351-3b98-4b52-b69b-ad2da6efe993.mov
#

Fix issue-4276: UI: Filter Schema once added unable to remove

---

ingestion/src/metadata/orm_profiler/metrics/static/histogram.py
ingestion/src/metadata/orm_profiler/orm/functions/length.py
ingestion/src/metadata/orm_profiler/orm/registry.py
ingestion/src/metadata/orm_profiler/profiler/default.py
ingestion/tests/unit/profiler/test_profiler.py
openmetadata-airflow-apis/setup.py

Fix #4332
Aside from a couple of fixes, this PR also disabled the Histogram from the default profiler. We are currently not showing that metric in the profiler view and its giving us some issues in different dialects. Opened https://github.com/open-metadata/OpenMetadata/issues/4368 to improve how we compute it
#
#
</p>
#
#

Fix #4332 - Athena LEN & hist concat cast + disable

---

openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TopicDetails/TopicDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/UserPage/UserPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
openmetadata-ui/src/main/resources/ui/src/utils/ToastUtils.ts

I work on removing success notifications for conversation created and deleted and reducing the success toast timing, also provided the option to pass close toast timing
Closes #4302 
#
#
</p>
#
#

Remove success toast notification!

---

openmetadata-ui/src/main/resources/ui/src/components/AddGlossary/AddGlossary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddGlossary/AddGlossary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddGlossaryTerm/AddGlossaryTerm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddGlossaryTerm/AddGlossaryTerm.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx

I worked on the glossary and glossary term page feedback.
#
#
#
#
@open-metadata/ui u

Fix: Glossary and Glossary term page issues.

---

openmetadata-ui/src/main/resources/ui/src/components/common/FormBuilder/FormBuilder.tsx

I worked on the removing disable state for save button without test-connection
#
#
</p>
#
#

Fix Schema Form Save button

---

openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetails.tsx
openmetadata-ui/src/main/resources/ui/src/components/TeamsAndUsers/TeamsAndUsers.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/UserDetails/UserDetails.tsx
openmetadata-ui/src/main/resources/ui/src/interface/teamsAndUsers.interface.ts

Moved  create action to left panel for "Teams and User Page", allowed the admin to join any team even if it is closed.
#4241 
#
#
#
#

Move add action of teams and user page to left panel

---

openmetadata-ui/src/main/resources/ui/src/components/ManageTab/ManageTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidget.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/OwnerWidget/OwnerWidget.tsx

I worked on removing dummy text from manage tab
#
#
#
#

UI: Remove dummy text from manage tab

---

openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Users/Users.interface.ts
openmetadata-ui/src/main/resources/ui/src/pages/UserPage/UserPage.component.tsx

Fixes #4414 
I worked on issue #4414 
#
#
#
#

Fix #4414 User Profile Roles are missing Admin option in dropdown

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplication.java

Fix #4429: Authorizer module should start after ES publisher is started

---

openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx

I worked on explore entity cards to display meta information like `service` , `database` an `databaseSchema`
#
#
#
#

UI :Add meta information in explore entity cards

---

openmetadata-ui/src/main/resources/ui/webpack.config.dev.js

I have added a hot reload module for UI, it will reload the browser automatically when there are changes in the codebase for the frontend. it is helpful for checking changes related to the frontend in the browser without refreshing the browser manually.
#
#
</p>
#
#

Hot reload module for UI 

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/ChangeEventParser.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/feeds/FeedResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/ChangeEventParserTest.java
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/FeedCardHeader/FeedCardHeader.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/ColumnTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddGlossary/AddGlossary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddGlossaryTerm/AddGlossaryTerm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddService/Steps/SelectServiceType.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddWebhook/AddWebhook.tsx
openmetadata-ui/src/main/resources/ui/src/components/CreateUser/CreateUser.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataQualityTest/Table/DataQualityTable.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityDeleteModal/EntityDeleteModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ConnectionConfigForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.style.css
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx
openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/AddGlossaryTermPage/AddGlossaryTermPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/services/index.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/AddUsersModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/AddUsersModal.tsx
openmetadata-ui/src/main/resources/ui/src/styles/tailwind.css

This PR fixes issues reported in #4241

UI: Fix miscellaneous UI issues

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/ColumnTestForm.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/ColumnTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.tsx

I worked on the Add test form in Data Quality tab to remove execution frequency from it
#
#
Previous UI:
Current UI:
</p>
#
#
@pmbrull @harshach @open-metadata/ui

Fix #4453: Remove the Frequency of Test Run field when we add a test

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/elasticsearch/ElasticSearchEventPublisher.java

Fix #4493: ElasticSearch publisher goes into pause mode if a document missing exception thrown

---

openmetadata-ui/src/main/resources/ui/src/pages/TeamsAndUsersPage/TeamsAndUsersPage.component.tsx

Closes #4499 Fixed issue UI: do not throw error when team list is empty []
#
#
https://user-images.githubusercontent.com/71748675/165487580-e9a70cf2-179f-42b4-bfef-6164fe6a0e20.mov
#
#

fix issue-4499:- UI: do not throw error when team list is empty []

---

openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx

Closes #4516 UI: Remove popover for ingestion status if there is no details available
#
#
https://user-images.githubusercontent.com/71748675/165513344-929aec01-0baf-4145-96af-a9ee2943cf74.mov
#
#

fixed issue-4516 UI: Remove popover for ingestion status if there is no details available

---

.github/workflows/maven-build.yml
bootstrap/sql/com.mysql.cj.jdbc.Driver/v001__create_db_connection_info.sql
bootstrap/sql/org.postgresql.Driver/v001__create_db_connection_info.sql
catalog-rest-service/src/main/java/org/openmetadata/catalog/Entity.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/CatalogApplicationTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/EntityResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/policies/PolicyResourceTest.java

Making MySQL and Postgres bootstrap files more consistent. Following are the changes:
1. Consistent index naming as done for Postgres
2. Change `UNIQUE KEY (columnName)` to equivalent `UNIQUE (columnName)` as done for Postgres
3. Fixed some indentation issues
Similarly, Postgres bootstrap files are made consistent with MySQL with indentation, space, removing new lines, etc.
Finally, container reuse is turned on to reduce the test time spent in restarting the containers.
#
#

Make bootstrap sql files for mysql and postgres consistent with each other

---

catalog-rest-service/src/main/resources/json/schema/api/services/ingestionPipelines/createIngestionPipeline.json
catalog-rest-service/src/main/resources/json/schema/entity/services/ingestionPipelines/ingestionPipeline.json
openmetadata-airflow-apis/src/openmetadata/workflows/ingestion/common.py

Pydantic did not properly import the enum default from other file's definitions
#
#
</p>
#
#

Remove default logger from ingestionpipeline

---

ingestion/src/metadata/cli/ingest.py
ingestion/src/metadata/cmd.py
ingestion/src/metadata/ingestion/api/parser.py
ingestion/src/metadata/ingestion/api/workflow.py
ingestion/tests/unit/test_workflow_parse.py

Fix #4540 and fix #4553
This PR helps us bring correct error messaging for invalid JSON configs:
```
❯ metadata ingest -c ~/sources/mssql_bad.json
[2022-04-29 13:06:37] ERROR    {Ingestion:parser:123} - Error parsing the Workflow Configuration for Mssql ingestion
1 validation error for MssqlConnection
random
extra fields not permitted (type=value_error.extra)
```
When a validation fails, we'll fetch the source class and redo the parsing scoping only to the source config. This way we only throw the messaging for that specific source in a more manageable manner
#
#
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for …

Fix #4540 - Parse connection JSON gracefully

---

bootstrap/sql/org.postgresql.Driver/v001__create_db_connection_info.sql

For the postgres migration script `CREATE INDEX` and `CREATE FUNCTION` clauses are missing `IF NOT EXISTS` checks which can cause problems.
#
#
#
@open-metadata/backend

Add IF NOT EXISTS checks to postgres migration

---

catalog-rest-service/src/main/resources/json/schema/entity/services/connections/database/redshiftConnection.json
ingestion/tests/unit/test_source_url.py

Modifying Redshift schema - adding database as a required field
Before:
Database - Optional field
Didn't work if we passed it as empty/blank/none
After:
Added it as required, user will face an error if they pass in an invalid value
fix #4545 
#
#
</p>
#
#

Modify redshift schema - adding database as a required field

---

openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/Steps/ConfigureIngestion.tsx

Closes #4581 
I worked on the Add/Edit ingestion page to remove unnecessary fields for Dashboard and messaging services
#
#
https://user-images.githubusercontent.com/86726556/166501013-76187a37-2723-419b-b5b4-825773e62494.mov
</p>
#
#
@open-metadata/ui @harshach

Fix #4581: [Looker] | Ingestion UI | Remove Unnecessary config on service connection

---

openmetadata-ui/src/main/resources/ui/src/components/AddService/AddService.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ConnectionConfigForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ServiceConfig.tsx
openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx

Closes #4511 
I worked on the service connection form to hide test connection for SampleData service
#
#
https://user-images.githubusercontent.com/86726556/166493781-bf3cd086-8b45-48af-9b4e-a6a68e27cd51.mov
</p>
#
#
@open-metadata/ui @harshach

Fix #4511: Hide the test connection button for Sample Data.

---

openmetadata-ui/src/main/resources/ui/src/components/EntityList/EntityList.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
openmetadata-ui/src/main/resources/ui/src/interface/types.d.ts
openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/tour-page/TourPage.component.tsx

Closes #4575 UI: Add total count of user owned or following data entities in profile page and home page
#
#
Home Page:-
User Page:-
#
#

Fix issue-4575: UI: Add total count of user owned or following data entities in profile page and home page

---

ingestion/src/metadata/ingestion/source/glue.py

We were using manual iterations and token retrieval to paginate data instead of the supported `paginate` methods.
I was not able to replicate the issue where not all dbs were ingested (getting the same data before and now), but yet again, we do not have much data in our Glue and I'm missing permissions.
This patch might get rid of the issue, we'll need to test it further.
#
#
</p>
#
#

Fix #4732 - Glue clean and paginate

---

openmetadata-airflow-apis/setup.py

I worked on the setup.py from the openmetadata airflow api  because  currently we need to donwload the tar release and unpack it to the plugins dir of airflow installation. This process can be made easier by specyfing and entrypoint aiflow.plugin which airflow in runtime picks the plugin and installs it.
#
- [] Bug fix
#
#

Configure entrypoint for airflow plugin

---

openmetadata-airflow-apis/setup.py

Reverts open-metadata/OpenMetadata#4733
Having some conflicts with ingestion image. Check thread here https://openmetadata.slack.com/archives/C02B6955S4S/p1651824724328819?thread_ts=1651716288.401759&cid=C02B6955S4S
Thanks

Revert "Configure entrypoint for airflow plugin"

---

catalog-rest-service/src/main/resources/json/schema/entity/services/connections/connectionBasicType.json
conf/openmetadata.yaml
openmetadata-ui/src/main/resources/ui/src/components/ServiceConfig/ConnectionConfigForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/FormBuilder/FormBuilder.tsx
openmetadata-ui/src/main/resources/ui/src/constants/services.const.ts
openmetadata-ui/src/main/resources/ui/src/utils/JSONSchemaFormUtils.ts

Closes #4595
See #4746 
#
#
https://user-images.githubusercontent.com/1051198/167241599-b1822b37-7143-4378-9b11-a171899ac13c.mov
#

Fix #4746. UI: Connection Arguments and Connection Options should support inner dicts

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/LocationRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/locations/LocationResource.java
catalog-rest-service/src/main/resources/json/schema/api/data/createLocation.json
catalog-rest-service/src/main/resources/json/schema/entity/data/location.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/locations/LocationResourceTest.java
ingestion/examples/sample_data/locations/locations.json
ingestion/src/metadata/ingestion/sink/metadata_rest.py
ingestion/src/metadata/ingestion/source/gcs.py
ingestion/src/metadata/ingestion/source/glue.py
ingestion/src/metadata/ingestion/source/s3.py
ingestion/src/metadata/ingestion/source/sample_data.py

We were using `name` to store the location path. That easily overflowed the 128 characters.
This PR fixes #4768 and adds the property `path` to location.
#
#
</p>
#
#

Fix #4768 - Add Location path

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/PipelineRepository.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/pipelines/PipelineResourceTest.java
ingestion/tests/integration/lineage/airflow/test_airflow_lineage.py
ingestion/tests/integration/ometa/test_ometa_pipeline_api.py

Fix #4610
Running a PUT updating a Pipeline Entity with a specific list of tasks, returns the Pipeline Entity with that list only. However, running a GET again returns the list with the old + new tasks.
Updated the tests to cover this scenario
#
#
</p>
#
#

[WIP] Fix #4610 - Pipeline Tasks removal

---

openmetadata-ui/src/main/resources/ui/src/axiosAPIs/userAPI.ts
openmetadata-ui/src/main/resources/ui/src/components/BotsDetail/BotsDetail.component.tsx
openmetadata-ui/src/main/resources/ui/src/generated/entity/teams/authN/jwtAuth.ts
openmetadata-ui/src/main/resources/ui/src/generated/entity/teams/user.ts
openmetadata-ui/src/main/resources/ui/src/pages/BotsListpage/BotsListpage.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/BotsPage/BotsPage.component.test.tsx

Closes #4827 
I worked on the Bots details page to show the expiry date of the token and unit tests.
#
#
#
#

Fix #4827 UI : Show Expiry date for JWT token on bots details page.

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/UserResource.java

Fix #4870: Return empty response if the bot token is not available

---

openmetadata-ui/src/main/resources/ui/src/components/GlossaryTerms/GlossaryTermsV1.component.tsx

Closes #4855 
I worked on issue #4855 
#
#
#
#

Fix #4855  Glossary Term has redundant button for `Add Reviewer`

---

openmetadata-ui/src/main/resources/ui/src/components/containers/PageLayout.tsx
openmetadata-ui/src/main/resources/ui/src/styles/x-master.css

Fixes #4745 
I worked on issue #4745 
#
#
#
#

Fix #4745 UI: For scrolling the content in the middle column, the cursor needs to be in the middle column .

---

ingestion/src/metadata/ingestion/sink/elasticsearch.py

Fix #4919 : Fix elastic search teams indexing
```
AttributeError: 'MetadataESConnection' object has no attribute 'includePolicy'
```
This issue was fixed in #4884 
#
#
#

Fix #4919: Fix elastic search teams indexing

---

ingestion/src/metadata/ingestion/source/superset.py

fix #4586 
I was not able to reproduce the error but if the attributes of charts are not set, it won't stop the ingestion.
It will skip the corrupt charts and move on ingesting other charts
#
#
</p>
#
#

Add error handling for charts in superset

---

ingestion/src/metadata/ingestion/source/clickhouse.py

I worked on Adding multiple database support in Clickhouse.
Befor : Clickhouse picks up default database when not specified in the config file.
Now: When database is not specified in the config, all available databases  ingest.
Fix #4931 
#
#

Fix #4931: Add multiple database support in Clickhouse

---

openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.tsx
openmetadata-ui/src/main/resources/ui/src/constants/feed.constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/StringsUtils.ts

Fixes #4718 
Fixes #4991 
I worked on fixing these two issues.
#
#
https://user-images.githubusercontent.com/59080942/168733480-3a44f2eb-3d96-41e2-bb3d-a195a7b60253.mov
#
#

Fix #4718 UI: Link in the @mention of user refreshes the whole page

---

openmetadata-ui/src/main/resources/ui/cypress/integration/Pages/myData.spec.js
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/ColumnTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddGlossary/AddGlossary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddGlossaryTerm/AddGlossaryTerm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/Steps/ConfigureIngestion.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddService/Steps/ConfigureService.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddService/Steps/ConnectionDetails.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddService/Steps/SelectServiceType.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddWebhook/AddWebhook.tsx
openmetadata-ui/src/main/resources/ui/src/components/BotsDetail/BotsDetail.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/CreateUser/CreateUser.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/NodeSuggestions.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/GlossaryReferences/GlossaryReferences.tsx
openmetadata-ui/src/main/resources/ui/src/components/GlossaryTerms/GlossaryTermsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityDeleteModal/EntityDeleteModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/Form.tsx
openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetails.tsx
openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTConfigFormBuilder.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTGCSConfig.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTHttpConfig.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTLocalConfig.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTS3Config.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/FilterPattern/FilterPattern.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/SearchInput/SearchInput.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/searchbar/Searchbar.tsx
openmetadata-ui/src/main/resources/ui/src/components/dropdown/DropDownList.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/Form.tsx
openmetadata-ui/src/main/resources/ui/src/styles/tailwind.css

Closes #4781 
I worked on fixing UI for all Input fields
#
#
<p align="">
Before
After
</p>
#
#

Fix #4781: forms text fields looks like it has space in the beginning

---

openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetails.tsx
openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx

Closes #4951 Unwanted entries for the My Data section on the User Profile page and assets tab on the team's page
#
#
https://user-images.githubusercontent.com/71748675/169297005-ba3a082d-b20b-473d-9f68-0d706da3dc06.mov
https://user-images.githubusercontent.com/71748675/169297371-48a27b56-f86e-49b2-ab68-4c8c017de8a9.mov
#
#

Fix issue-4951: Unwanted entries for My Data section on User Profile page 

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/yarn.lock

Closes #4443 
I worked on fixing swagger requests in secure mode
#
#
</p>
#
#

Fix #4443: Swagger APIs must work in secure mode

---

.github/workflows/selenium-noIngestion-tests.yml
openmetadata-ui/src/main/resources/ui/json2ts.sh

Fixes json2ts concurrency memory consumption & dependency error
#
#
</p>
#
#

Fixes concurrent memory consumption

---

.github/workflows/cypress-integration-tests.yml

Cypress workflow will require 'safe to test' label to be added to the PRs

Cypress: workflow should run only with a 'safe to test' label

---

openmetadata-ui/src/main/resources/ui/src/constants/constants.ts

I worked on issue #5110
#
#
https://user-images.githubusercontent.com/59080942/169960681-a7731a3b-beab-4526-83b5-facd736520de.mov
#
#

Fix #5110 UI : Hide bots link from setting dropdown if user is not an admin

---

catalog-rest-service/pom.xml
catalog-rest-service/src/main/java/org/openmetadata/catalog/airflow/AirflowRESTClient.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/ingestionpipelines/IngestionPipelineResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/JsonUtils.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/PipelineServiceClient.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/airflow/AirflowRESTClientIntegrationTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/airflow/HttpServerExtension.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/airflow/JsonHandler.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/airflow/MockResponse.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/ingestionpipelines/IngestionPipelineResourceUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/JsonUtilsTest.java
openmetadata-airflow-apis/README.md
openmetadata-airflow-apis/src/openmetadata/api/apis_metadata.py
openmetadata-airflow-apis/src/openmetadata/api/config.py
openmetadata-airflow-apis/src/openmetadata/api/rest_api.py
openmetadata-airflow-apis/src/openmetadata/operations/last_dag_logs.py
pom.xml

Closes #2725 
Added a new endpoint in the Airflow REST plugin (`/rest_api/api?api=last_dag_logs&dag_id={task_id}`) for get all logs from the last run in the following format:
```json
{
"instance_task_1": "log attempt 1\n*** Reading local file: /path/2.log\nlog attempt 2",
"instance_task_1": "log attempt 1\n*** Reading local file: /path/2.log\nlog attempt 2"
}
```
Added a similar endpoint in OpenMetadata server (`/api/v1/services/ingestionPipelines/logs/{task_id}/last`) which makes a request to the Airflow REST plugin and returns its response.
#
#
</p>
#
#

Fix #2725: Add IngestionPipeline Task logs

---

openmetadata-ui/src/main/resources/ui/src/components/DatasetVersion/DatasetVersion.component.tsx

I worked on fixing table constraint is missing in dataset version schema issue
#
#
#
#

Fix : table constraint is missing in datasetVersion schema

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/WebhookRepository.java

Webhook post fails due to empty secretKey

---

ingestion/sonar-project.properties
ingestion/src/metadata/ingestion/source/database/athena.py
ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/sqlalchemy_source.py
ingestion/src/metadata/ingestion/source/sqa_types.py
ingestion/src/metadata/orm_profiler/orm/registry.py
ingestion/src/metadata/utils/column_type_parser.py
ingestion/tests/unit/profiler/test_profiler.py

Fix #5108
The issue was that the profiler was failing for `map` type in Athena. Even though pyathena handles it as a string, the profiler actually needs to run some logic that failed.
By providing wrapper classes on top of SQA types, we can override the pyathena dialect to map source types to our custom definitions. This way, we can properly handle the richer type system that OM has.
Also, athena tables are external by definition, so we updated that as well.
#
#
</p>
#
#

Fix #5108 - Add Map and Struct support for Athena & Block them for profiler

---

openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/UserCard.tsx

I worked on issue #5207 
#
#
#
#

Fix #5207 UI - Team Assets display table full address

---

openmetadata-ui/src/main/resources/ui/src/axiosAPIs/tableAPI.ts
openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx

I worked on issue #5248 
#
#
Here we have 15 tables in `ecommerce_db `
Same count, we have while deleting the `ecommerce_db`
#
#

Fix #5248 UI : Confirmation modal is showing wrong tables count on database page

---

ingestion/src/metadata/ingestion/source/amundsen.py

Amundsen Connector Fix for 0.10.1
#
#
#

Amundsen Connector Fix 

---

conf/openmetadata.yaml

Fix #5272: Add a env variable to configure log level for OpenMetadata server

---

catalog-rest-service/src/main/resources/json/schema/api/data/createChart.json
catalog-rest-service/src/main/resources/json/schema/api/data/createDashboard.json
catalog-rest-service/src/main/resources/json/schema/entity/data/chart.json
catalog-rest-service/src/main/resources/json/schema/entity/data/dashboard.json
ingestion/src/airflow_provider_openmetadata/lineage/utils.py
ingestion/src/metadata/ingestion/source/dashboard/looker.py
ingestion/src/metadata/ingestion/source/dashboard/metabase.py
ingestion/src/metadata/ingestion/source/dashboard/powerbi.py
ingestion/src/metadata/ingestion/source/dashboard/redash.py
ingestion/src/metadata/ingestion/source/dashboard/superset.py
ingestion/src/metadata/ingestion/source/dashboard/tableau.py
ingestion/src/metadata/utils/helpers.py
ingestion/tests/integration/lineage/airflow/test_airflow_lineage.py

Fix #4696 - Only store URL suffixes when extracting metadata
#
#
</p>
#
#

Fix #4696 - Only store URL suffixes when extracting metadata

---

ingestion/setup.py
ingestion/src/metadata/cmd.py

see #5305 
Removes the report command which we don't need it any more.
#
#

Fix #5305: Add simple webhook server to metadata command to test metadata events

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/FeedCardHeader/FeedCardHeader.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/FeedCardHeader/FeedCardHeader.tsx

Fixes #5240 
I worked on issue #5240 
#
#
#
#

Fix #5240 Display database name and table name in activity feed.

---

openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx

Fixes #5384 
I worked on issue #5384 
#
#
#
#

Fix #5384 Use `displayName` instead of  `name` for pipeline listing page

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/databases/TableResourceTest.java

Fix #5498: Column comparator should ignore case

---

Makefile
ingestion/src/metadata/orm_profiler/orm/converter.py
ingestion/src/metadata/orm_profiler/profiler/core.py
ingestion/tests/integration/orm_profiler/test_converter.py
ingestion/tests/integration/orm_profiler/test_orm_profiler.py

This PR fixes #4723 issue where table with case sensitive column (i.e. non uppercase column) throw an error. This PR will force quoting when database service is snowflake and column name is not uppercase.
We also turn `orm_profiler` integration test back on.
#
#
#

[ISSUE-4723] Fix Snowflake Case Sensitive Error with Profiler

---

openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryCard.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableQueries/QueryCard.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableQueries/TableQueries.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableQueries/TableQueries.tsx

I worked on #5542 
#
#
https://user-images.githubusercontent.com/59080942/174724095-137516db-19b7-42cc-b85e-16924d07bdf3.mov
#
#

Fix #5542 UI : Table Query Card Is Not Expandable

---

ingestion/src/airflow_provider_openmetadata/lineage/config/providers.py

The airflow method `conf.get` on airflow only returns strings.
The scope parameter needs to be a list, by switching to `conf.getjson` it will try to parse to a list.
#
#
#

Fix airflow lineage config auth scopes

---

openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx

This PR fixes #5546 where decimal field type show column tests as not supported.
#
#
#
#

[ISSUE-5546] Added decimal as supported dataType

---

openmetadata-ui/src/main/resources/ui/cypress/integration/Pages/EntityDetails.spec.js
openmetadata-ui/src/main/resources/ui/cypress/integration/Pages/TeamsAndUsers.spec.js
openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/UserDetails/UserDetails.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/UserDetails/UserDetails.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidget.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetV1.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DeleteWidget/DeleteWidgetV1.tsx
openmetadata-ui/src/main/resources/ui/src/interface/teamsAndUsers.interface.ts
openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TeamsAndUsersPage/TeamsAndUsersPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/x-master.css
openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx

I worked on the on the issue #5474 UI: Users, Teams and all the entities should support both soft-delete and hard-delete #5600
Closes #5474 
#
#
added soft-delete support for all the entities
users page delete modal
#
#

Feat: UI: Users, Teams and all the entity should support both soft-delete and hard-delete 

---

conf/openmetadata.yaml

Fix #5235: AIRFLOW_AUTH_PROVIDER value to be custom-oidc instead of customOidc

---

ingestion/src/metadata/orm_profiler/metrics/static/column_names.py
ingestion/src/metadata/orm_profiler/metrics/static/mean.py
ingestion/src/metadata/orm_profiler/metrics/static/stddev.py
ingestion/src/metadata/orm_profiler/orm/functions/length.py
ingestion/src/metadata/orm_profiler/orm/functions/modulo.py
ingestion/src/metadata/orm_profiler/orm/functions/random_num.py

This PR fixes #4935 implementing:
- logic to handle click modulo function
- logic to generate random sample
- logic to return `None` if mean or std function return `NaN`
#
#
#

Fixes #4935 -- Profiler Error with ClickHouse empty tables

---

openmetadata-ui/src/main/resources/ui/src/components/web-scoket/web-scoket.provider.tsx

Fix polling fallback when there's error for websocket & fore to use websocket only
#
#
#
#

fix(ui): do not fallback to polling and use websocket as transport method

---

bootstrap/sql/com.mysql.cj.jdbc.Driver/v002__create_db_connection_info.sql
bootstrap/sql/org.postgresql.Driver/v002__create_db_connection_info.sql
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/FeedRepository.java

- Fixed migration of database from 0.10.3 to 0.11 for activity feed and reactions for both Mysql and Postgres
#

Fix migration script for migrations to 0.11

---

openmetadata-ui/src/main/resources/ui/src/components/dropdown/AnchorDropDownList.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TeamsAndUsersPage/TeamsAndUsersPage.component.tsx

I worked on the Fixed: Team & Users page is stuck at loading on trying to join the team and UI: Version is displayed in 2 lines
Closes #5812 
Closes #5813 
#
#
https://user-images.githubusercontent.com/71748675/176858467-e81b84a5-a0b7-4362-92ac-04a9c431a552.mov
#
#

Fixed: Team & Users page is stuck at loading on trying to join the team

---

docs/integrations/airflow/airflow-lineage.md

Added a note explaining how airflow users can set the OpenMetadata lineage callbacks by default for all DAGs, Tasks or specifics operators. 
#
- [] Bug fix
#
#

Add to docs how to setup lineage callbacks by default on airflow

---

openmetadata-ui/src/main/resources/ui/src/components/common/description/Description.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/description/Description.tsx
openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx

Fixes #5843 
I worked on issue #5843 
#
#
#
#

Fix#5843  UI : Do not show the request description icon in entities that has no support for tasks yet

---

openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Users/Users.util.tsx
openmetadata-ui/src/main/resources/ui/src/pages/UserPage/UserPage.component.tsx

> Update the default filter to "My Data" instead "All Activity" for the User profile page
Closes: [#5836](https://github.com/open-metadata/OpenMetadata/issues/5836)
#
#
#
#

fix(ui): #5836 User profile should show user related activity only

---

openmetadata-ui/src/main/resources/ui/src/axiosAPIs/ingestionPipelineAPI.ts
openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.mock.ts
openmetadata-ui/src/main/resources/ui/src/components/Ingestion/Ingestion.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Ingestion/ingestion.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/IngestionStepper/IngestionStepper.css
openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TasksUtils.ts

I worked on the UI button to pause/unpause ingestion pipeline executions
Fixes #5652
#
#
https://user-images.githubusercontent.com/71748675/177514163-d60d565e-84fa-4941-985a-bb19c4a1deb1.mov
#
#

Feat: UI button to pause/unpause ingestion pipeline executions

---

openmetadata-ui/src/main/resources/ui/src/styles/x-master.css

For larger resolutions > 2000px the layout centers itself instead of occupying the full screen.
#
#
https://user-images.githubusercontent.com/1051198/177706639-cecae38f-1b05-4602-a648-1e0971b18298.mov
#

UI: Fix browser zoom breaks UI layout

---

openmetadata-ui/src/main/resources/ui/src/components/ManageTab/ManageTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/OwnerWidget/OwnerWidget.tsx
openmetadata-ui/src/main/resources/ui/src/components/dropdown/DropDownList.tsx
openmetadata-ui/src/main/resources/ui/src/components/dropdown/types.ts
openmetadata-ui/src/main/resources/ui/src/utils/ManageUtils.ts

- Fetch total count for Users & Teams
- Serach should work correctly 
- update count on searching 
Closed: #5892 
#
#
https://user-images.githubusercontent.com/12962843/177803350-c815a5ee-d79b-4e79-b12f-0f9f0ece997c.mov
#
#

fix(ui): owner search issue and show total count on load

---

ingestion/src/metadata/utils/source_connections.py

Fix #5877: Renamed Database to DatabaseSchema for Oracle Connection
#
#
#

Fix #5877: Renamed Database to DatabaseSchema for Oracle Connection

---

openmetadata-ui/src/main/resources/ui/src/authentication/auth-provider/AuthProvider.tsx
openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/OidcAuthenticator.tsx
openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/AuthProvider.util.ts

- I worked on refreshing auth token before its expiration. 
- Affected SSOs are Google, AWS Cognito, Custom OIDC
- @vivekratnavel We need to support one more redirect URI from SSOs: `/silent-callback` 
#
#
> Dev testing performed for
1. Should start to try silentSignIn before the token is about to expire ( Before 50 seconds )
2. Should re-try on failure for 3 times after that redirect to login screen
3. Initialise timer on App load & After successful login
4. Re-try attempt consider for consecutive retires, On successful login we will reset the retry count
#
#

feat(ui): refresh token support for OIDC client login

---

ingestion/src/metadata/orm_profiler/orm/functions/median.py
ingestion/src/metadata/orm_profiler/validations/column/column_values_to_match_regex.py
ingestion/tests/unit/profiler/test_session_validations.py

Fixes #5964 where trino median function is not compiled correctly. It also updates the wording for `columnValuesToMatchRegex ` to make it explicit as to what is being tested.
#
#
#

Fixes #5964 -- Trino Median function and columnValuesToMatchRegex wording

---

bootstrap/sql/com.mysql.cj.jdbc.Driver/v003__create_db_connection_info.sql
bootstrap/sql/org.postgresql.Driver/v003__create_db_connection_info.sql

In 0.11 we added FQN to users and teams, while the migrations missed that step.
Also, 0.10 did not add FQN on the services, making the `list` API miss the pagination. Here we are adding the missing information.
#
#
</p>
#
#

Update missing FQN

---

catalog-rest-service/src/main/resources/json/schema/entity/tags/tagCategory.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/tags/TagResourceTest.java

Fix #5092: Allow tag names to be 64 chars in length

---

catalog-rest-service/src/main/resources/json/schema/tests/table/tableCustomSQLQuery.json
catalog-rest-service/src/main/resources/json/schema/tests/tableTest.json
ingestion/src/metadata/orm_profiler/processor/orm_profiler.py
ingestion/src/metadata/orm_profiler/validations/core.py
ingestion/src/metadata/orm_profiler/validations/table/table_custom_sql_query.py
ingestion/tests/unit/profiler/test_session_validations.py
ingestion/tests/unit/profiler/test_validations.py
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/Forms/TableTestForm.tsx

This PR fixes #3463 by implementing the base logic to execute custom SQL tests. The test has been defined as a tableTest as it is technically executed against the whole table. This limits the number of SQL tests to 1. I am suggesting to fix in a second PR (open to suggestion though).
@open-metadata/ui I used a `label` field for the query imput, let me know if you think there is a better element to use.
We also took the opportunity to re-work part of the test dispatch in anticipation of the test case API re-work. 
#
#
#
#
@open-metadata/ui 

Fixes #3463 -- Implement Custom SQL Data Quality Tests

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/CollectionDAO.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/EntityRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/GlossaryRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/GlossaryTermRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TagCategoryRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TagRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java
catalog-rest-service/src/main/resources/json/schema/type/tagLabel.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/EnumBackwardCompatibilityTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/util/TestUtils.java
ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/database_service.py
openmetadata-core/src/main/java/org/openmetadata/core/entity/repository/EntityRepository.java
openmetadata-core/src/main/java/org/openmetadata/core/jdbi3/CollectionDAO.java
openmetadata-core/src/main/resources/json/schema/type/tagLabel.json
openmetadata-ui/src/main/resources/ui/src/components/GlossaryDetails/GlossaryDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/GlossaryTerms/GlossaryTermsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/SchemaTab/SchemaTab.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/tags-container/tags-container.tsx
openmetadata-ui/src/main/resources/ui/src/components/tags-viewer/tags-viewer.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/TagSuggestion.tsx

I worked on fixing make generate gives different results depending on OS
Fix #5712 
#
#

FIX 5712: make generate gives different results depending on OS

---

ingestion/examples/workflows/metabase.yaml

In Yaml file dbServiceName field move from serviceConnection to sourceConfig
#
#

dbServiceName field move from serviceConnection to sourceConfig

---

openmetadata-ui/src/main/resources/ui/src/components/common/TreeView/treeView.css

- Worked on fixing text-overflow for glossary page navigation 
- Closed: #5988 
#
#
#
#

fix(ui): add ellipses for text overflow

---

ingestion/src/metadata/utils/gcs_utils.py
ingestion/src/metadata/utils/s3_utils.py

Fix #6091: Fix Datalake arrays must be of the same length
#
#
#

Fix #6091: Fix Datalake arrays must be of the same length

---

openmetadata-ui/src/main/resources/ui/src/components/TeamsSelectable/TeamsSelectable.tsx

I worked on the Team listing is not scrollable when creating the user
Closes #6099 
#
#
https://user-images.githubusercontent.com/71748675/179513155-babd39b1-e1e6-403c-b548-056fdad41604.mov
#
#

Fixed issue Team listing is not scrollable when creating the user

---

openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/TaskDetailPage/TaskDetailPage.tsx

Closes #6175 
I worked on changing logic to show "Close with comment" for  task creators, assignees, owners and admins
#
#
#
#

Fix #6175 UI : show "Close with comment" for  task creator, assignees, owners and admins

---

.github/workflows/py-tests-3_9.yml
Makefile

Fix for failing CI due to a missing parameter when calling sed from the Github action.

Fix#5924: Fix coverage.xml generation

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/FeedRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/RestUtil.java

- Instead of throwing an exception for hard deleted users, now showing deletedUser in case of deleted user.
#
#
#
#

Backend: Soft deleting a user is causing the page to not load

---

openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx

Fixes #6202 
I worked on issue #6202 
#
#
Entity have same tags in multiple columns
Unique tags on explore page entity card
#
#

Fix #6202 UI : Explore page card should show unique tags

---

.github/workflows/py-tests-3_9.yml

We stop receiving the SonarCloud summary in the PR after updating the GH workflow for py3.9.
The 'pull_request_target' workflow trigger must pass some extra arguments to the Sonar Cloud GH action.
#
@pmbrull 

Fix missing SonarCloud decorator in PR when triggering GH workflow for py3.9

---

openmetadata-ui/src/main/resources/ui/src/constants/entity.constants.ts

I worked on fixing soft delete should not be sent hard delete true on teams and users' page
#
#
#
#

Fix softDelete should not sent hardDelete true

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/AddIngestion.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.constant.ts
openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.jsx

I worked on the Service ingestion workflows should be configurable as scheduled or on-demand
Closes #6071 
#
#
https://user-images.githubusercontent.com/71748675/179922593-18657652-7aa0-44f5-8488-1b98a509490e.mov
#
#

fixed issue 6071: Service ingestion workflows should be configurable as scheduled or on-demand

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java

Fix #6255 Backend: Ignore dashboard usage summary in activity feed

---

catalog-rest-service/src/test/java/org/openmetadata/catalog/airflow/AirflowRESTClientIntegrationTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/bots/BotResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/databases/DatabaseSchemaResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/feeds/MessageParserTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/metadata/TypeResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/mlmodels/MlModelResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/policies/PolicyResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/security/JWTTokenGeneratorTest.java
openmetadata-core/src/test/java/org/openmetadata/core/util/TypeUtilTest.java

Fix sonar issues
Remove public modifiers from test classes and methods where it's possible
#
#
#
@sureshms
@open-metadata/backend

ISSUE-3790: Remove unnecessary public modifiers in tests

---

ingestion/src/metadata/orm_profiler/orm/converter.py
ingestion/src/metadata/orm_profiler/processor/orm_profiler.py
ingestion/src/metadata/orm_profiler/profiler/core.py
ingestion/src/metadata/orm_profiler/sink/metadata_rest.py
ingestion/tests/unit/profiler/test_converter.py

Fixes #6078 where DB column named `metadata` conflict with SQA reserved attribute.
#
#
#

Fixes #6078 - DB column named `metadata` conflict with SQA reserved attribute

---

ingestion/src/metadata/ingestion/bulksink/metadata_usage.py
ingestion/src/metadata/ingestion/ometa/mixins/table_mixin.py
ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/src/metadata/ingestion/source/database/usage_source.py
ingestion/src/metadata/utils/lru_cache.py
ingestion/src/metadata/utils/sql_lineage.py
ingestion/tests/unit/metadata/utils/test_lru_cache.py

As explained on #6241, we've identified that the database usage ingestion does a very large amount of repeated requests to elastisearch and the backend tables for every query/table processed. This PR is a first effort to improve usage ingestion performance by implementing caches/checks in three stages of the process:
* `metadata_usage` & `table_mixin`: For each table, avoid ingesting the same query more than once as it will add no new information and most of the repetaed queries are created by previous stages in the process. 
* `sql_usage` cache the result of `search_table_entities` that does one query to ES and potentially many to backend and was one of the main sources of the slowdown. I wasn't able to find a nice place to put the cache due to the way the code is structured so I ended …

[TASK-6241] Cache ES ingestion when ingesting usage

---

ingestion/src/metadata/utils/connections.py
ingestion/src/metadata/utils/sql_queries.py
ingestion/tests/unit/test_ometa_utils.py

https://github.com/open-metadata/OpenMetadata/issues/6140
We wanted to add a header to all openmetadata queries in order to identify & filter them. We've achieved that by using [SQLAlchemy's event listeners](https://docs.sqlalchemy.org/en/14/core/event.html) to intercept and alter all statements from the engine in `CommonDbSourceService`. Seem to work on the inspector when inspecting connections derived from the same engine too. Example query extracted from the Redshift's system tables:
We've also filtered all queries with the OpenMetadata & dbt headers as per the issue.
I only have access for a working setup of Redshift so we as we've modified several queries for other systems if we have some battery of integration tests it would be safer to run them.
#
#
N/A
#
#

[TASK-6140] Add OMeta header to SQLAlchemy-based queries

---

openmetadata-airflow-apis/src/openmetadata/operations/last_dag_logs.py

#6286
We were getting a "doesn't exist" error when trying to ingest logs from DAGs triggered manually. [This PR addresses that](https://github.com/open-metadata/OpenMetadata/pull/6296).
#
#
N/A
#
#

[TASK-6282] Extract logs of triggered DAGs

---

ingestion/src/metadata/ingestion/source/database/datalake.py
ingestion/src/metadata/utils/s3_utils.py

#6295 
As described in the task, we want to avoid loading the entire files to extract/infer their schemas. This PR addresses this for the S3 ingestion:
* CSV/TSV: Leverages the `StreamingBody` returned by boto3 to read and parse only the first n (defaulting to 100) rows in the file.
* JSONL: Leverages the `StreamingBody` returned by boto3 to read & parse into dicts the first n rows (defaulting to 100) and then loading them into a dataframe. **Files with a single JSON object are not supported for now as it's not possible to do a partial read without extra tooling**
* Parquet: Leverages the tooling in Arrow to only read the schema in the parquet footer and extract the schema from there
Equivalent changes on the GCS will be done on a separate PR. We've done the minimum amount of changes …

[TASK-6295] Reduce memory footprint for S3 ingestion

---

.github/workflows/py-tests-3_10.yml
.github/workflows/py-tests-3_7.yml
.github/workflows/py-tests-3_8.yml
.github/workflows/py-tests-3_9.yml
docker/local-metadata/.ci_env
docker/run_local_docker.sh
openmetadata-dist/pom.xml

Added `no-ui` option for start server from `run_local_docker.sh` script without the web interface. This can be used when starting the server for running the py-test integration tests so the CI time will be reduced.
An [example](https://github.com/open-metadata/OpenMetadata/runs/7520340330?check_suite_focus=true) of this approach running in CI.

Reduce the CI times for py-tests

---

openmetadata-dist/pom.xml

Add missing build definition to profile `only-backend` in `openmetadata-ui`.

Update POM profile build configuration when using the only-backend profile

---

openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditor.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.less
openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.tsx
openmetadata-ui/src/main/resources/ui/src/components/tags/tags.tsx
openmetadata-ui/src/main/resources/ui/src/styles/tailwind.css

I worked on the Tier Description Dropdown which did not show any tier description on hover.
#
#
#
#

tier description dropdown

---

openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTConfigForm.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTFormConstants.ts
openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTS3Config.tsx

I worked on the feature: allow configuration of dbt s3 from the UI without AWS credentials
Closes #6291 
#
#
https://user-images.githubusercontent.com/71748675/181076129-032798a4-6baf-40c5-8f26-de452f5ecff1.mov
#
#

feature: allow configuration of dbt s3 from the UI without AWS credentials

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/events/ChangeEventHandler.java

Task Conversation had thread type as "Task" , because of which task notification were getting created, This fixes that issue
#
#
#

[Backend][Notifications] Fix taskConversation sent as taskNotification

---

ingestion/src/metadata/ingestion/ometa/mixins/tag_mixin.py
ingestion/src/metadata/ingestion/sink/metadata_rest.py
ingestion/src/metadata/ingestion/source/database/bigquery.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/tests/integration/ometa/test_ometa_tags_mixin.py

Fix #6248: Use PUT API instead of POST for tag & tagCategory
#
#
#

Fix #6248: Use PUT API instead of POST for tag & tagCategory

---

openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.less

Fixes #6397 
I worked on overriding markdown parser default stylings.
#
#
#
#

Fix #6397 UI : Override markdown parser default stylings 

---

openmetadata-dist/pom.xml

Add missing dependency to rpm profile in `openmetadata-dist` project pom.
#
@pmbrull

Fix: Add missing dependency to rpm profile in openmetadata-dist pom

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/DescriptionTabs.test.tsx
openmetadata-ui/src/main/resources/ui/src/styles/index.js
openmetadata-ui/src/main/resources/ui/src/styles/slick-carousel.scss
openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
openmetadata-ui/src/main/resources/ui/webpack.config.prod.js
openmetadata-ui/src/main/resources/ui/yarn.lock

Revert react-slick package as it's breaking login page
#
#
</p>
#
#

revert(ui): react-slick added back as it's breaking login page

---

openmetadata-ui/src/main/resources/ui/src/components/EntityList/EntityList.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/recently-viewed/RecentlyViewed.tsx
openmetadata-ui/src/main/resources/ui/src/interface/types.d.ts
openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TopicDetails/TopicDetailsPage.component.tsx

Closes #4391 
I worked on issue #4391 
#
#
#
#

Fix #4391 UI : Use user API to get owns and following data on home page.

---

docker/metadata/openmetadata-start.sh

Replaced `wget` with `nc` in openmetadata entrypoint as `wget` fails in case PostgreSQL is used even when the DB server is available.
#
#
</p>
#
#

Replaced wget with nc in entrypoint to support PostgreSQL

---

ingestion/src/metadata/utils/timeout.py
ingestion/tests/unit/profiler/test_runner.py

#5522 
Fixing the profiler timeout not working. When listing the objects we passed as a predicate [isfunction](https://docs.python.org/3/library/inspect.html#inspect.isfunction), which evaluates as true is an object is a function or a lambda. When setting the [QueryRunner](https://github.com/open-metadata/OpenMetadata/blob/aae4410c93a03263c5a6ee755630a7982d4457c5/ingestion/src/metadata/orm_profiler/interfaces/sqa_profiler_interface.py#L137-L145) we are not passing the class itself but rather an instance of the class (we're calling the constructor) so all methods inside the instance will be member(bound) methods. Member methods in python are not considered as functions but rather as [bound methods](https://www.geeksforgeeks.org/bound-methods-python/#:~:text=A%20bound%20method%20is%20the,are …

[ISSUE-5522] Fix profiler timeout

---

catalog-rest-service/pom.xml
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/PolicyRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/lineage/LineageResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/policies/PolicyResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/NoopAuthorizer.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/policyevaluator/OperationContext.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/security/policyevaluator/PolicyEvaluator.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/EntityUtil.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/util/JsonUtils.java
catalog-rest-service/src/main/resources/json/data/ResourceDescriptors.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/accessControl/resourceDescriptor.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/accessControl/rule.json
catalog-rest-service/src/main/resources/json/schema/entity/policies/policy.json
catalog-rest-service/src/main/resources/json/schema/type/basic.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/policies/PolicyResourceTest.java
common/pom.xml
ingestion-core/src/metadata/_version.py
openmetadata-core/pom.xml
openmetadata-ui/pom.xml
pom.xml

Currently, Policy validation is handcoded because of `anyOf` field in the Policy.json. Making change to use JsonSchema based constraint validation. Also making a few changes in POM.xml to avoid defining the same version numbers, adding SpEL as a dependency, and other changes...
#
#

Use JSON schema constraints to validate policies and other misc cleanup

---

ingestion/src/metadata/great_expectations/action.py
ingestion/tests/unit/great_expectations/test_ometa_validation_action.py

Fixes #6453 by changing ometa_service_name to database_service_name. This is a backward compatible change. Using `ometa_service_name` will throw a deprecation warning.
#
#
#

Fixes 6453 -- Changed ometa_service_name to database_service_name

---

ingestion/src/metadata/orm_profiler/interfaces/sqa_profiler_interface.py
ingestion/src/metadata/utils/connections.py

Fixes #6476 by changing how scoped_session factory is created. `max_overflow=-1` is set to allow infinite connection creation (though the pool has a set limit of 5). This should allow room for slight lag between connections release and connection creation (between python and the db).
When testing against redshift and mysql opened connections remained stable.
#
#
#

Fixes #6476 -- Multiple db connections opened

---

openmetadata-ui/src/main/resources/ui/src/components/TeamsSelectable/TeamsSelectable.tsx
openmetadata-ui/src/main/resources/ui/src/pages/signup/index.tsx

…API call.
I worked on the signup page error issue.
#
#
</p>
#
#

fix(ui): Eliminating signup page error

---

openmetadata-ui/src/main/resources/ui/src/authentication/auth-provider/AuthProvider.tsx
openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/MsalAuthenticator.test.tsx
openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/MsalAuthenticator.tsx

fix(ui): notify auth provider for login failed event

---

.github/workflows/security-scan.yml

Security scan GH workflow fails with the following error:
We are doing `mvn -DskipTests clean install` before running the security scan which does not put the package in the local repository.

Do 'mvn clean install' when running security-scan GH workflow

---

openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/BlurLayout.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/BlurLayout.tsx

I worked on issue #6497
#
#
https://user-images.githubusercontent.com/59080942/182307696-9dd7a9b5-9e31-4578-890c-a724319e1aa0.mov
#
#

Fix #6497 UI : Replace arrow with `Read more` text

---

openmetadata-ui/src/main/resources/ui/src/components/TeamsSelectable/TeamsSelectable.tsx

I worked on the TeamsSelectable component to increase the size parameter for search/query api call
#
#
</p>
#
#

Fix(UI): Increase size param for teams search by query api

---

openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/MsalAuthenticator.tsx
openmetadata-ui/src/main/resources/ui/src/pages/login/index.tsx
openmetadata-ui/src/main/resources/ui/src/pages/signup/index.tsx

I worked on the infinite loop issue for azure sso.
Also fixed redirection based on isAuthenticated instead of userDetails
**Issue**
If user try login after a while app goes to infinite loading.
**Fix**
For azure auth we only leveraged on `ssoSilent`.  Where as per [doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#using-an-account-object) we need to have fallback to `loginPopup` as well
@harshach Unable to replicate exact case yet, Trying to have reproducible steps to get exact details but this is potential fix that needed to Azure auth.
#
#
#
#

fix(ui): for use signin we should try fallback popup login

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DashboardServiceRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/DatabaseServiceRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/MessagingServiceRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/MlModelServiceRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/PipelineServiceRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/ServiceRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/ServiceEntityResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/dashboard/DashboardServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/database/DatabaseServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/messaging/MessagingServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/mlmodel/MlModelServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/pipeline/PipelineServiceResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/AWSSecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/LocalSecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/SecretsManager.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/jdbi3/DashboardServiceRepositoryUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/jdbi3/DatabaseServiceRepositoryUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/jdbi3/MessagingServiceRepositoryUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/jdbi3/MlModelServiceRepositoryUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/jdbi3/PipelineServiceRepositoryUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/jdbi3/ServiceRepositoryTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/DashboardServiceResourceUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/DatabaseServiceResourceUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/MessagingServiceResourceUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/MlModelServiceResourceUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/PipelineServiceResourceUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/ServiceResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/AWSSecretsManagerTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/LocalSecretsManagerTest.java

Fixes: https://github.com/open-metadata/OpenMetadata/issues/6487
Change how service repositories stores and update services and interact with the secrets manager.

Fix#5917: Stop saving connection service configuration parameters when secret manager is configured

---

ingestion/src/metadata/ingestion/lineage/sql_lineage.py
ingestion/tests/unit/test_sql_lineage.py

`get_lineage_by_query` function uses a global dict to handle the columns, which is not great.
I worked on improving this logic.
Fix: #5789 
#
#

Clean col-level lineage internal logic

---

pom.xml

Fix for vulnerability found in org.postgresql:postgresql@42.3.6 by Snyk.
```
Issues with no direct upgrade or patch:
✗ SQL Injection [High Severity][https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-2970521] in org.postgresql:postgresql@42.3.6
introduced by org.open-metadata:catalog-rest-service@0.12.0-SNAPSHOT > org.postgresql:postgresql@42.3.6
This issue was fixed in versions: 42.2.26, 42.4.1
```
#

Fix: Snyk vulnerability found in org.postgresql:postgresql@42.3.6

---

openmetadata-docs/content/main-concepts/high-level-design.md

Signed-off-by: Ramesh Mani <ramesh.mani@gmail.com>
High Level Design documentation  starting paragraph has a typo
#
#
</p>
#
#

6623:High Level Design documentation  starting paragraph has a typo

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplication.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplicationConfig.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/ingestionpipelines/IngestionPipelineResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/AWSSecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/LocalSecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/SecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/SecretsManagerFactory.java
catalog-rest-service/src/main/resources/json/schema/entity/services/connections/metadata/openMetadataConnection.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/AWSSecretsManagerTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/LocalSecretsManagerTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/SecretsManagerFactoryTest.java
catalog-rest-service/src/test/resources/openmetadata-secure-test.yaml
conf/openmetadata.yaml
ingestion/airflow.cfg
ingestion/examples/airflow/airflow.cfg
ingestion/src/metadata/ingestion/ometa/ometa_api.py
ingestion/src/metadata/utils/secrets_manager.py
ingestion/tests/unit/metadata/utils/test_secrets_manager.py
openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/credentials_builder.py
openmetadata-core/src/main/resources/json/schema/entity/services/connections/metadata/openMetadataConnection.json

Fixes: #6517 
Added `clusterName` property to the application config YAML to differentiate OpenMetadata Server instance.
Started using the `clusterName` in the new name convention for storing secrets:
- `/{clusterName}/service/{serviceType}/{connectionType}/{serviceName}`
- `/{clusterName}/auth-provider/{authProvider}`
Backend: @open-metadata/backend 

Fix#6517: Add clusterName property to the application config yaml

---

openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/profiler.py

When creating a Profiler DAG, it did not consider `loggerLevel` from the ingestion pipeline.

Fix: Profiler DAG takes loggerLevel from ingestion pipeline into account

---

openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ProfilerSettingsModal.tsx

I worked on the profiler setting modal slider showing undefined when there is no value
Closes #6690 
#
#
#
#

fixed issue 6690 profiler setting modal slider showing undefined when there is no value

---

openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.jsx
openmetadata-ui/src/main/resources/ui/src/components/common/CronEditor/CronEditor.test.tsx

Fixes: #6360
Changed the empty string we were sending for `none` time schedule by `null`.

Fix#6360: Airflow 2.3.3 None schedule validation

---

openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/react-select-component/reactSelectCustomStyle.ts

I worked on the issue with user page confirm button while editing teams falling out of the container.
#
#
Before : 
Now : 
</p>
#
#

Fix(UI): Fixed issue with confirm button falling out of container.

---

openmetadata-ui/src/main/resources/ui/src/pages/CreateUserPage/CreateUserPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPage/CustomPropertiesPageV1.tsx
openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/AddRolePage/AddRolePage.tsx
openmetadata-ui/src/main/resources/ui/src/router/GlobalSettingRouter.tsx
openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/RouterUtils.ts

I worked on the non-admin user global setting left panel should be visible properly 
Fixes #6710
#
#
#
#

Fixed issue: for non-admin user global setting left panel should visible properly  #6710

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/IngestionPipelineRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/services/ingestionpipelines/IngestionPipelineResource.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/AWSSecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/LocalSecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/SecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/SecretsManagerMigrationService.java
catalog-rest-service/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
catalog-rest-service/src/main/resources/json/schema/metadataIngestion/workflow.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/jdbi3/IngestionPipelineRepositoryTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/ingestionpipelines/IngestionPipelineResourceTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/ingestionpipelines/IngestionPipelineResourceUnitTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/services/ingestionpipelines/IngestionPipelineResourceUnitTestParams.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/AWSSecretsManagerTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/LocalSecretsManagerTest.java
ingestion/src/metadata/ingestion/api/workflow.py
ingestion/src/metadata/utils/secrets_manager.py
ingestion/tests/unit/metadata/utils/test_secrets_manager.py
openmetadata-core/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
openmetadata-core/src/main/resources/json/schema/metadataIngestion/workflow.json

Fixes: #6643
Added a new method in the secrets' manager interface for saving the DBT source config objects of the Services pipelines. 
In addition, we also migrate DBT source config objects of pipelines when a secret manager is activated.

Fix#6643: Secure in secrets manager the dbtConfigSource object

---

ingestion/src/metadata/orm_profiler/api/workflow.py
ingestion/src/metadata/orm_profiler/interfaces/interface_protocol.py
ingestion/src/metadata/orm_profiler/interfaces/sqa_profiler_interface.py
ingestion/src/metadata/orm_profiler/processor/orm_profiler.py
ingestion/src/metadata/orm_profiler/profiler/core.py
ingestion/src/metadata/orm_profiler/profiler/default.py
ingestion/src/metadata/orm_profiler/validations/models.py
ingestion/src/metadata/utils/processor_config_helper.py
ingestion/tests/unit/profiler/conftest.py
ingestion/tests/unit/profiler/test_metrics.py
ingestion/tests/unit/profiler/test_profiler.py
ingestion/tests/unit/profiler/test_sample.py
ingestion/tests/unit/profiler/test_session_validations.py
ingestion/tests/unit/profiler/test_sqa_profiler_interface.py
ingestion/tests/unit/profiler/test_workflow.py

This PR fixes #5661. This is a preparatory refactor to be able to implement #5831. 
In this PR we split the assocaition between the profiler and the processor (i.e. data quality runner) object in the workflow. This is needed as data quality tests and profiler will be executed in seperate workflow. 
N.B.
We temporarely removed the support for sample and partitioned tables. These will be re-implemented in #5831 as they are dependend on the workflow implementation.
#
#
#

Fixes #5661 by removing association between profiler and data quality

---

openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/router/AuthenticatedAppRouter.tsx
openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx

I worked on the Removed restriction for settings path
#
#
#
#

Allow settings path for all the domains

---

catalog-rest-service/src/main/resources/json/schema/entity/data/table.json

Fixes #5830 by implementing `timestampz` to distinguish timestamp with timezone.
#
#
#
#

Fixes #5830 Added timestamp with timezone data type

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/WebhookRepository.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/events/WebhookResource.java
catalog-rest-service/src/main/resources/json/schema/api/events/createWebhook.json
catalog-rest-service/src/main/resources/json/schema/entity/events/webhook.json

All types must be defined in entities and used by createRequest types and not the other way around. cc @mohitdeuex 
#
#

Make WebhookType part of webhook.json and not the create request

---

openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx

I worked on the fixing the styling of edit icon, switch and filter for user page
#
#
<p>
Before : 
After : 
Before : 
After : 
</p>
#
#

Fix(UI): Fixed styling of edit icon, switch and filter for user page

---

openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx

I worked on the entityTable component to eliminate the error occurred when no dataTypeDisplay value present.
#
#
</p>
#
#

Fix #6780 : fixed the error occurring  when dataTypeDisplay value is not present

---

ingestion/src/metadata/ingestion/sink/metadata_rest.py

Fix #6858 - DBT table not found by FQN
#
#
</p>
#
#

Fix #6858 - DBT table not found by FQN

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TableRepository.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/jdbi3/TableRepositoryUnitTest.java

Fixes: #6868
Fix table repository bug, which was causing NullPointerException.

Fix#6868: Fix table repository bug

---

openmetadata-ui/src/main/resources/ui/src/components/common/title-breadcrumb/title-breadcrumb.component.tsx

Fixes #6932 
I worked on issue #6932 
#
#
#
#

Fix #6932 UI | Full Table name is not displayed on the Table Home Page

---

openmetadata-airflow-apis/openmetadata_managed_apis/api/error_handlers.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/delete.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/deploy.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/disable.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/enable.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/health.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/ip.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/kill.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/last_dag_logs.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/status.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/test_connection.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/routes/trigger.py
openmetadata-airflow-apis/openmetadata_managed_apis/api/utils.py
openmetadata-airflow-apis/openmetadata_managed_apis/operations/deploy.py
openmetadata-airflow-apis/openmetadata_managed_apis/operations/kill_all.py
openmetadata-airflow-apis/openmetadata_managed_apis/operations/test_connection.py
openmetadata-airflow-apis/openmetadata_managed_apis/utils/logger.py
openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/common.py
openmetadata-airflow-apis/openmetadata_managed_apis/workflows/workflow_builder.py
openmetadata-airflow-apis/openmetadata_managed_apis/workflows/workflow_factory.py

Part of: #6027 and #5835
We are trying to improve and align logging by following these rules:
- Use `logger.debug(traceback.format_exc())` after catching an exception
- Log the exception/error as part of the logger message. Tried to follow the convention `{message}: {err/exc}`
- Use `warning` instead of `warn` and log it when the application encounters a problem that interrupts normal operation flow, but it has a fallback or can fix the problem itself or can continue
- Log an error if the `except` is at the end of the method or if we are rolling back

Fix#6027: Improve logging in OpenMetadata Airflow APIs

---

ingestion/src/metadata/interfaces/sqa_interface.py
ingestion/src/metadata/test_suite/api/workflow.py
ingestion/src/metadata/test_suite/runner/core.py

Fixes #5313  If non-OM test definitions are found we will skip them from workflow execution. 
#
#
#

Fixes #5313 by adding logic to skip non OM on testSuite workflow

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/AnnouncementModal/AddAnnouncementModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/AnnouncementModal/AddAnnouncementModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/AnnouncementModal/EditAnnouncementModal.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/AnnouncementModal/EditAnnouncementModal.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TimeUtils.ts

I worked on the changing labels for add and edit announcement modals.
#
#
Before:
Now:
</p>
#
#

Fix(UI): Updated labels for add and edit announcement modals

---

openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.tsx

I worked on the browser notification bug.
#
#
clicking on browser notification of chrome will now open the concerned link in new tab.
https://user-images.githubusercontent.com/51777795/187506788-9658149e-a5f8-4ce9-b7fa-4c39b589dd66.mov
</p>
#
#

Fix(UI): Clicking on browser notification for chrome will now open new window

---

ingestion/src/metadata/orm_profiler/profiler/core.py

Added logic to allow profile data to be ingested when sample data fetch fails

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx
openmetadata-ui/src/main/resources/ui/src/interface/dataQuality.interface.ts

Fixed below bug #7090
- Selecting some column-level tests breaks the UI
-  Error building the UI:
#
#
#
#

Profiler & Data Quality UI feedback & improvement Part1

---

ingestion/src/metadata/orm_profiler/metrics/static/unique_count.py
ingestion/src/metadata/orm_profiler/profiler/core.py

Some data type do not support unique count due to the impossibility to group by this field type (i.e. arrays, structs, etc.)
#
#
</p>
#
#

Remove unique computation for unsupported fields

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/AddDataQualityTestV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/SelectTestSuite.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/rightPanelData.ts
openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/ProfilerDashboard.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx

Worked on below task:
- Metrics value formatting issue Fixes https://github.com/open-metadata/OpenMetadata/issues/7082
- clicking on cancel or the table name in breadcrum when creating testcase/testsuite should bring user back to profiler view
- update the right panel text
- #7090
#
#
</p>
#
#

Profiler & Data Quality UI feedback & improvement #7090 part 3

---

openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/PoliciesDetailPage/PoliciesDetailPage.tsx

Convert Policies -> Organization collapse panel card into full card
https://github.com/open-metadata/OpenMetadata/issues/7071#issuecomment-1235765378
#
#
#
#

Revamp Policies CollapseTable in Card style

---

ingestion/src/metadata/utils/connections.py

Fixes: #7112 
Pass the `SchemaRegistryClient` to the `AvroConsumer` to avoid using `CachedSchemaRegistryClient`.

Fix#7112: Issue ingesting Kafka when the basic auth is enabled in the Schea Registry

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/jdbi3/TeamRepository.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/teams/TeamResourceTest.java

Fix #7187 Backend: Patching teams API for team type is not working properly

---

openmetadata-ui/src/main/resources/ui/src/authentication/auth-provider/AuthProvider.tsx

I worked on the hide toast error message on unauthorised access
#
#
https://user-images.githubusercontent.com/12962843/188557809-f69729f4-ca9a-4741-b218-17b9fe53d377.mov
#
#

fix(ui): hide error if API throws un-authorized

---

openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/EntitySummaryDetails/EntitySummaryDetails.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/TeamTypeSelect/TeamTypeSelect.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/TeamTypeSelect/TeamTypeSelect.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/TeamTypeSelect/TeamTypeSelect.utils.ts

I worked on removing the group type option for teams with child teams while editing team type.
Fixed a bug with team count for child teams not in sync with search results
#
#
</p>
#
#

UI: Removed group type option for teams with child teams.

---

openmetadata-ui/src/main/resources/ui/cypress/integration/Pages/EntityDetails.spec.js
openmetadata-ui/src/main/resources/ui/src/axiosAPIs/feedsAPI.ts

Fixes #7276
I worked on issue #7276
#
#
https://user-images.githubusercontent.com/59080942/188713013-d56936c4-67a9-4670-ae28-fb10874549ab.mov
(Screenshots) :
#
#

Fix #7276 UI: Entity Page Activity Feed tab is empty   

---

openmetadata-airflow-apis/openmetadata_managed_apis/views/templates/rest_api/index.html

Fix #6897
There were a bunch of old HTML features in there we could not support in terms of auth. Cleaning everything out to avoid confusion
#
#
</p>
#
#

Fix #6897 - Update rest plugin docs

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/dqtests/TestSuiteResource.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/resources/dqtests/TestSuiteResourceTest.java

Fix #7000: Delete with recursive=true is not working for testSuite API

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/NoopSecretsManager.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/SecretsManagerConfiguration.java
catalog-rest-service/src/main/java/org/openmetadata/catalog/secrets/SecretsManagerFactory.java
catalog-rest-service/src/main/resources/json/schema/entity/services/connections/metadata/secretsManagerProvider.json
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/AWSSSMSecretsManagerTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/AWSSecretsManagerTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/ExternalSecretsManagerTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/NoopSecretsManagerTest.java
catalog-rest-service/src/test/java/org/openmetadata/catalog/secrets/SecretsManagerFactoryTest.java
catalog-rest-service/src/test/resources/openmetadata-secure-test.yaml
conf/openmetadata.yaml
ingestion/src/metadata/utils/secrets/aws_based_secrets_manager.py
ingestion/src/metadata/utils/secrets/external_secrets_manager.py
ingestion/src/metadata/utils/secrets/noop_secrets_manager.py
ingestion/src/metadata/utils/secrets/secrets_manager_factory.py
ingestion/tests/integration/ometa/test_ometa_secrets_manager.py
ingestion/tests/unit/metadata/utils/secrets/test_noop_secrets_manager.py
ingestion/tests/unit/metadata/utils/secrets/test_secrets_manager_factory.py
openmetadata-core/src/main/resources/json/schema/entity/services/connections/metadata/secretsManagerProvider.json

- Simplified implementation in Python SDK
- Renamed `local` secrets manager to `noop`

Fix: Improvements on secret manager implementation

---

openmetadata-ui/src/main/resources/ui/src/utils/PermissionsUtils.ts

I worked on Adding the` ConditionalAllow` check for Create Operation Permission
#
#
#
#

UI : Add `ConditionalAllow` check for Create Operation Permission

---

openmetadata-ui/src/main/resources/ui/src/axiosAPIs/permissionAPI.ts
openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/MlModelDetail/MlModelDetail.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/PermissionProvider/PermissionProvider.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/PermissionProvider/PermissionProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/PipelineDetails/PipelineDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DashboardDetailsPage/DashboardDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/MlModelPage/MlModelPage.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/MlModelPage/MlModelPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PipelineDetails/PipelineDetailsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TopicDetails/TopicDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TopicDetails/TopicDetailsPage.test.tsx

I worked on adding Permission Check on Entity Page.
#
#
#
#

UI : Add Permission Check on Entity Page

---

openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.style.less
openmetadata-ui/src/main/resources/ui/src/components/GlossaryDetails/GlossaryDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/GlossaryTerms/GlossaryTermsV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/Card/Card.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ActivityFeedSettingsPage/ActivityFeedSettingsPage.tsx
openmetadata-ui/src/main/resources/ui/src/styles/app.less
openmetadata-ui/src/main/resources/ui/src/styles/components/glossary.less
openmetadata-ui/src/main/resources/ui/src/styles/x-master.css

- Fix glosssary right panel styling issue
- Fix glossary breadcrumb padding issue
- Change Activity field reset button name
- Fix glossary description card padding issue
- Fix body overflow issue
- Added body color
#
#
#
#

UI :- Fix glossary and UI bugs

---

openmetadata-ui/src/main/resources/ui/cypress/integration/Pages/Roles.spec.js
openmetadata-ui/src/main/resources/ui/src/components/AddGlossary/AddGlossary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/PropertyValue.tsx
openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.ts

I worked on fixing the glossary trailing name space issue. 
#
#
#
#

Fix Glossary trailing name space issue

---

docker/metadata/docker-compose-postgres.yml

Postgres container misses port mapping required to connect to the database
#
#
#

Add port mapping for postgres container

---

catalog-rest-service/src/main/java/org/openmetadata/catalog/security/jwt/JWTTokenGenerator.java

Initialize JWTTokenGenerator instance in a static block instead of volatile variable based, synchronized initialization that is marked as a bug in Sonar cloud.
#
#

Fix Sonar Cloud issue - Static initialization of JWTTokenGenerator

---

ingestion/setup.py
ingestion/src/metadata/orm_profiler/profiler/core.py

Fixes #7399 -- Use `__future__ annotation` to use class object type hint instead of `Self`
#
#
#

Fixes #7399 Removed typing_extension dependency

---

openmetadata-ui/src/main/resources/ui/src/authentication/auth-provider/AuthProvider.tsx
openmetadata-ui/src/main/resources/ui/src/utils/AuthProvider.util.ts

I worked on the fixing silent sign-in not working
- Issue:
- Timeout we are setting was too close to expiry that it's not able to re-issue new token
- Fix
- Update 2 minute buffer to perform silent sign-in
#
#
#
#

fix(ui): silent sign-in

---

ingestion/src/metadata/ingestion/source/database/database_service.py

I worked on the Fixing DBT root config error handling.
When `"dbtConfigSource":{}` that time it was giving tuple index of range error, and `get_dbt_details()` also execute that block even `"dbtConfigSource":{}` so that is handled . 
Fix: #7341
#
#

Fix: DBT root config error handled

---

openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/Steps/ConfigureIngestion.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ProfilerSettingsModal.tsx

- Issue : #7392
- allowed to use decimal point in Profile sample progress bar
- allowed to use decimal point in Add Profile ingestion sample
#
#
#
#

Fix UI Issue: Allow decimal point in profile sample

---

docker/local-metadata/docker-compose-postgres.yml
docker/local-metadata/docker-compose.yml

fix: docker-compose ingestion service volumes path typo error

---

openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx

I worked on the issue with expansion of rows in entity tables.
#
#
**Before :** 
https://user-images.githubusercontent.com/51777795/191012415-03f8bee0-7063-4d1c-bb51-57d169f29ef1.mov
**After :**
https://user-images.githubusercontent.com/51777795/191012501-5ec9c666-5ac0-402e-a4e1-796e6a44e01d.mov
</p>
#
#

Fix(UI) #7491: Fixed expansion issue for rows in entity tables

---

openmetadata-service/src/main/java/org/openmetadata/service/security/DefaultAuthorizer.java
openmetadata-spec/src/main/resources/json/schema/entity/bot.json

Fixes: #7424
We were not creating Bot entities when the default authorizer was initialized. Only the bot users were created.

Fix#7424: Create Bots on default authorizer init

---

openmetadata-ui/src/main/resources/ui/src/pages/explore/ExplorePage.component.tsx

Fixes #7466 
I worked on issue #7466 
#
#
https://user-images.githubusercontent.com/59080942/191233694-8f464d8b-1590-4c01-8f75-5f03c44b6456.mov
#
#

Fix #7466 UI throws fetch entity count error when there is no data in ElasticSearch

---

openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx

- https://github.com/open-metadata/OpenMetadata/issues/7496
- https://github.com/open-metadata/OpenMetadata/issues/7334#issuecomment-1241309097
- fix empty data issue while changing owner in Profiler and DataQuality
#
#
https://user-images.githubusercontent.com/66266464/191016032-eeddc276-7a7c-4aa6-b825-f69d1e836d8a.mov
#
#

Fix UI :  Empty data issue while changing owner in Profiler and DataQuality

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Bots.spec.js
openmetadata-ui/src/main/resources/ui/src/components/BotListV1/BotListV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/constants.ts

Fixes #7575 
I worked on issue #7575 
#
#
https://user-images.githubusercontent.com/59080942/191232062-b4097a09-0ea6-40dc-9bab-5d15c20e4ac1.mov
#
#

Fix #7575 UI : Fetch bots with limit=100 and filter it on the UI side.

---

ingestion/ingestion_dependency.sh

Fixes: #7493 
We can not restart `ingestion` container due to the following error:
```
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.9/site-packages/lockfile/pidlockfile.py", line 77, in acquire
write_pid_to_pidfile(self.path)
File "/home/airflow/.local/lib/python3.9/site-packages/lockfile/pidlockfile.py", line 161, in write_pid_to_pidfile
pidfile_fd = os.open(pidfile_path, open_flags, open_mode)
FileExistsError: [Errno 17] File exists: '/opt/airflow/airflow-webserver-monitor.pid'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/airflow/.local/bin/airflow", line 8, in <module>
sys.exit(main())
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/__main__.py", line 38, in main …
```

Fix#7493: Airflow container can not be restarted

---

ingestion/setup.py

Fix #7395: Bump sqllineage version to 1.3.6
tested these changes with hive version 2.1.0, 2.3.2 & 3.2.1
#
#
#

#7395: Bump sqllineage version to 1.3.6

---

openmetadata-ui/src/main/resources/ui/src/components/AddGlossary/AddGlossary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddGlossaryTerm/AddGlossaryTerm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddTags/add-tags.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TagsUtils.ts

I worked on the Allow users to add to tags during the creation process
Closes #7550
#
#
#
#

Fixed issue: Allow users to add to tags during the creation process - P0 - 0.12.1 #7550

---

docker/local-metadata/mysql-script.sql

updating database airflow_db with proper character set and collate
see #7641 
#
#
</p>
#
#

updating database airflow_db with proper character set and collate

---

openmetadata-ui/src/main/resources/ui/src/axiosAPIs/testAPI.ts
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx

- Issue: Closes #7309
-  Added platform filter of OM for Custom test definition
#
#
#
#

Fix UI :- Added platform filter for Custom test definition

---

ingestion/src/metadata/ingestion/source/database/snowflake_query_parser.py

I worked on the Fixing Validate query log duration with Snowflake account_usage
Fix: #6896
#
#

Fix: Remove min duration limit

---

.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql.yml

Split cypress integrations tests to mysql and psql CI.
Looks like the operation of CI gets cancelled when running with multi dimension matrix strategy. Fallback to splitting cypress in its own separate ci for postgres.
#
#
#

fix: Split cypress integrations tests to mysql and psql CI

---

ingestion/src/metadata/utils/source_connections.py

Fixes ADC Bigquery Project ID issue where project id doesn't get  overriden if we use ADC
#
#
</p>
#
#

Fix Bigquery ADC project id overriding

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java

Fix #7675: Authorizer should allow users to update their own profile

---

ingestion/src/metadata/test_suite/validations/column/column_value_max_to_be_between.py
ingestion/src/metadata/test_suite/validations/column/column_value_mean_to_be_between.py
ingestion/src/metadata/test_suite/validations/column/column_value_median_to_be_between.py
ingestion/src/metadata/test_suite/validations/column/column_value_min_to_be_between.py
ingestion/src/metadata/test_suite/validations/column/column_value_stddev_to_be_between.py
ingestion/src/metadata/test_suite/validations/column/column_values_in_set.py
ingestion/src/metadata/test_suite/validations/column/column_values_length_to_be_between.py
ingestion/src/metadata/test_suite/validations/column/column_values_missing_count_to_be_equal.py
ingestion/src/metadata/test_suite/validations/column/column_values_not_in_set.py
ingestion/src/metadata/test_suite/validations/column/column_values_sum_to_be_between.py
ingestion/src/metadata/test_suite/validations/column/column_values_to_be_between.py
ingestion/src/metadata/test_suite/validations/column/column_values_to_be_not_null.py
ingestion/src/metadata/test_suite/validations/column/column_values_to_be_unique.py
ingestion/src/metadata/test_suite/validations/column/column_values_to_match_regex.py
ingestion/src/metadata/test_suite/validations/column/column_values_to_not_match_regex.py
ingestion/src/metadata/utils/entity_link.py
ingestion/tests/unit/metadata/utils/test_entity_link.py
ingestion/tests/unit/test_suite/test_validations.py
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java

Issue #7623 
- Backend -> entityLink will be encoded (i.e. `first name` will become `first+name`)
- ingestion -> we will be expecting an encoded entityLink from the `testCase` (`+` to encode spaces). We will be decoding the column name to perform the check and run the tests
#
#
#

Fixes #7623 -- Added logic to encode and decode entityLink

---

openmetadata-ui/src/main/resources/ui/src/components/BotListV1/BotListV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/jsons/en.ts
openmetadata-ui/src/main/resources/ui/src/pages/CreateUserPage/CreateUserPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/CreateUserPage/CreateUserPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/router/AuthenticatedAppRouter.tsx

Fixes #7646 
I worked on issue #7646 
#
#
#
#

Fix #7646 UI: Non-admin user should not be allowed to add a bot

---

openmetadata-docs/content/openmetadata/connectors/pipeline/airflow/cli.md

The documentation for Airflow include reference to Airbite ingestion.
I worked on the documentation fix because it refer to the wrong package
#
#
#
- @harshach (I see you are the one that work on that file in the past, if you're not the right one feel free to ignore it)

Fix a few typo in the doc (airflow instead of airbite)

---

openmetadata-ui/src/main/resources/ui/src/authentication/auth-provider/basic-auth.provider.tsx
openmetadata-ui/src/main/resources/ui/src/authentication/authenticators/basic-auth.authenticator.tsx
openmetadata-ui/src/main/resources/ui/src/axiosAPIs/auth-API.ts
openmetadata-ui/src/main/resources/ui/src/jsons/en.ts
openmetadata-ui/src/main/resources/ui/src/pages/forgot-password/forgot-password.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/forgot-password/forgot-password.styles.less
openmetadata-ui/src/main/resources/ui/src/pages/login/index.tsx
openmetadata-ui/src/main/resources/ui/src/pages/login/login.style.less
openmetadata-ui/src/main/resources/ui/src/pages/reset-password/reset-password.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/reset-password/reset-password.style.less
openmetadata-ui/src/main/resources/ui/src/pages/reset-password/reset-password.utils.ts
openmetadata-ui/src/main/resources/ui/src/pages/signup/account-activation-confirmation.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/signup/basic-signup.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/signup/basic-signup.style.less
openmetadata-ui/src/main/resources/ui/src/router/AppRouter.tsx
openmetadata-ui/src/main/resources/ui/src/utils/AuthProvider.util.ts
openmetadata-ui/src/main/resources/ui/src/utils/LocalStorageUtils.ts
openmetadata-ui/src/main/resources/ui/src/utils/UserDataUtils.ts

I worked on the:
1. Added licence file to each newly files
2. Fix error/success messages
3. Tested with username sign-in only
4. Once the email confirm user should get toast and redirect to the Sign in page
5. Integrate self signup feature so that admin can control over who can sign-in or not
#
#
</p>
#
#

fix(ui): allow username or email login

---

openmetadata-ui/src/main/resources/ui/src/components/AddGlossaryTerm/AddGlossaryTerm.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx

I worked on the issue where Trailing space in display name and FQN of glossary term is not handled correctly
https://github.com/open-metadata/OpenMetadata/issues/7074#issuecomment-1245849177
Closes #7704
#
#
https://user-images.githubusercontent.com/71748675/192083464-8a9367b8-8448-45fe-abdc-59adba7b03da.mov
#
#

Fixed issue : Trailing space in display name and FQN of glossary term is not handled correctly

---

openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.utils.tsx
openmetadata-ui/src/main/resources/ui/src/interface/teamsAndUsers.interface.ts
openmetadata-ui/src/main/resources/ui/src/pages/teams/TeamsPage.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TeamUtils.ts

I worked on adding a switch to show soft deleted teams on team details page.
#
#
https://user-images.githubusercontent.com/51777795/191962885-aad3446d-c9bf-49de-99e4-a48d2ed27e98.mov
</p>
#
#

UI: Added a switch to show soft deleted teams on team details page

---

ingestion/src/metadata/ingestion/source/database/database_service.py

I worked on the fixing Error initializing ingest: ‘RedshiftSource’ object has no attribute ‘dbt_manifest’.
#
#

Fix: RedshiftSource’ object has no attribute ‘dbt_manifest’

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Teams.spec.js
openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/AddTeamForm.tsx

I worked on the adding cypress tests for checking the option for permanent delete is available for soft deleted teams
#
#
</p>
#
#

UI: Added cypress tests for soft deleted team checks.

---

openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/ProfilerDashboard.tsx
openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/DataQualityTab.tsx
openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/profilerDashboard.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/TestCasesTab/TestCasesTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/ProfilerDashboardPage/ProfilerDashboardPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteDetailsPage/TestSuiteDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/app.less

I worked on the [Add ability to view and delete "soft-deleted" tests#7728](https://github.com/open-metadata/OpenMetadata/issues/7728)
Closes #7728
#
#
https://user-images.githubusercontent.com/71748675/192517117-503f8b23-4068-4ff4-bdb5-cb290232bd7a.mov
#
#

(Feature) UI: Add ability to view and delete "soft-deleted" tests#7728

---

openmetadata-ui/src/main/resources/ui/src/components/BotDetails/AuthMechanismForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.test.tsx

Fixes #7753
I worked on issue #7753 
#
#
#
#

Fix #7753 Empty bot view when the bot user auth mechanism is not set

---

ingestion/src/metadata/ingestion/source/database/dbt_source.py

- Added support for test ingestion without `dbt docs generate` run
- removed millisecond from timestamp
- changed test result failure to 0
#
#
</p>
#
#

Fix minor issues with dbt test results ingestion

---

ingestion/src/metadata/utils/source_connections.py

I worked on the fixing 'GCSCredentialsPath' object has no attribute 'projectId' error
Fix: #7727
#
#

Fix: 'GCSCredentialsPath' object has no attribute 'projectId'

---

openmetadata-ui/src/main/resources/ui/src/authentication/auth-provider/AuthProvider.tsx

I worked on the redirection issue where user was thrown to 404 page after refreshing auth token is failed.
#
#
**Before :** 
https://user-images.githubusercontent.com/51777795/192958832-bd90e260-c6b7-4a12-b8c0-69cae000678b.mov
**After :** 
https://user-images.githubusercontent.com/51777795/192959160-bad67dae-8db9-4d97-b283-d5b4549c58e5.mov
</p>
#
#

UI: Fixed redirection issue after refreshing auth token failed

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/myData.spec.js
openmetadata-ui/src/main/resources/ui/src/components/app-bar/Appbar.tsx
openmetadata-ui/src/main/resources/ui/src/components/app-bar/Suggestions.tsx

I worked on fixing the issue with suggestion overlay staying after redirection to the search result page. This behaviour was seen when user clicks on the result immediately after typing in search box where search result is present already, or clicks on previous suggestions before the suggestion results for newly typed text are populated (due to delay in API response)
#
#
**Before :**
https://user-images.githubusercontent.com/51777795/193206233-366d2ad0-ec0e-46f3-af66-8f9881493e9f.mov
**After :**
https://user-images.githubusercontent.com/51777795/193206290-2c31916c-f9fb-4f6e-8aa3-0443e70c656d.mov
</p>
#
#

UI: Fixed issue with suggestion overlay staying after redirection to the result

---

ingestion/src/metadata/test_suite/api/workflow.py
openmetadata-airflow-apis/openmetadata_managed_apis/workflows/ingestion/common.py

- In airflow workflow first try to get the testSuite entity to check if we can reach the OM server, otherwise raise same errors than other service
- In testSuite workflow exit the whole workflow if we cannot find any testSuite in the config file and throw an error message
#
#
#

Added checks to see if DAG can reach OM

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/EntityDetails.spec.js
openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityThreadPanel/ActivityThreadPanelBody.tsx

I worked on fixing the entity announcement cypress test
#
#
#
#

Fix: Entity Announcement Cypress test

---

openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java
openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/elastic-search-index.page.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EventPublisherUtils.ts

I worked on the fixing below issues
1. Index request shows actual number instead truncated
2. Recreate index message update
3. Ideal --> Idel
#
#
#
#

fix(ui): show actual count for index requests

---

openmetadata-ui/src/main/resources/ui/src/pages/GlossaryPage/GlossaryPageV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/app.less

- Issue : Closes #7878
- Fix glossary default item after clicking from list to navigation
- Increase font weight of tags list as per glossary
#
#
Issue : 
https://user-images.githubusercontent.com/66266464/193534805-7510d20e-53a4-4a67-a1c2-3f5aa1f25500.mov
Resolved : 
https://user-images.githubusercontent.com/66266464/193534839-4361e749-66c2-4205-965c-176edd786dc6.mov
#
#

Fix UI :-  Glossary default item after clicking from list to navigation

---

openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx

Fixes #7881
I worked on issue #7881 
#
#
https://user-images.githubusercontent.com/59080942/193564293-95c00393-fd89-4b50-a29f-141188bded39.mov
#
#

Fix #7881 Tag page throws 404 for tierTag when upgrading from 0.11.5 to 0.12.1

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/elasticSearch/BuildSearchIndexResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java

Related issue: #7863 
I fixed the use of boolean wrapper class return values in order to prevent NPE's. Conditional clauses checking these return values now  use a NPE safe alternative.
#
#
</p>
#
#

Fix 'Use the primitive boolean expression' - warning

---

ingestion/src/metadata/utils/source_connections.py
ingestion/tests/unit/test_source_connection.py

I worked on the fixing connector for hive has double dash.
Fix: #7715 
#
#

Fix: connector for hive has double dash

---

ingestion/src/metadata/ingestion/source/database/sql_column_handler.py
ingestion/src/metadata/utils/helpers.py
ingestion/tests/unit/test_helpers.py

Contraint column names are returned by SQA with double quotes when the table DDL include this character. This causes an error to be raised `Invalid column name found in table constraint` as the column name is not found in the table entity columns https://github.com/open-metadata/OpenMetadata/blob/cd43f1fdcf4103f205864a721e8747f38502051d/openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseUtil.java#L62.
#
#
</p>
#
#

Redshift constrain error

---

openmetadata-docs/content/deployment/upgrade/docker.md
openmetadata-docs/content/quick-start/local-deployment.md

There were two references in the docs to `0.12.0` and `0.11.3`, I replaced them with `{version}` which I saw used elsewhere in one of the same files.
#
#
#

fix two hardcoded references to old version number

---

ingestion/src/metadata/cmd.py

Fixes #7503 -- Removed click.Tuple() and used nargs instead

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java

Fix #7908 Backend: Glossary term deletion executes partial deletion

---

ingestion/src/metadata/ingestion/ometa/superset_rest.py

A user reported that the connector for Superset (version 2.0.0) was failing to a missing slash in the queries done to the API. 
From the [documentation](https://superset.apache.org/docs/api/), it seems we need to add a slash at the end to the requests to `/chart` and `/dashboard`. 
In our dev instance, both queries work.

Fix Superset REST client requests

---

openmetadata-ui/src/main/resources/ui/src/constants/elasticsearch.constant.ts

I worked on the removing unwanted "bot" entity from re-indexing API
#
#
#
#

fix(ui): bot is not part of re-index entity

---

.github/workflows/py-tests.yml

Sonar coverage tests must run only for Python 3.9 tests.

Fix: Sonar coverage test run only for Python 3.9

---

openmetadata-ui/src/main/resources/ui/src/components/BotDetails/AuthMechanism.tsx

I worked on making AuthMechanism Fields to readOnly from NonEditable.
#
#
#
#

UI : Make AuthMechanism Fields to readOnly from NonEditable

---

ingestion/src/metadata/utils/source_connections.py
ingestion/tests/unit/test_source_connection.py

I worked on the fixing connection failed because of having '@' character in uname and pass
Fix: #7182
#
#

FIX: connection failed because of having '@' character in uname and pass

---

pom.xml

This reverts commit 7dd9804d783eefa9e7d6665ecde87d818f1ad547.
#
#
</p>
#
#

Revert "Bump jackson-databind from 2.13.4 to 2.13.4.1 (#8242)"

---

openmetadata-ui/src/main/resources/ui/src/components/dropdown/DropDownList.tsx

- Issue : Closes  #8290
- Remove icon visible in Dropdown other than owner
#
#
#
#

fix(ui) :  Remove icon visible in Dropdown other than owner

---

ingestion/src/metadata/cmd.py

Issue-8315: Parameter 'input' on the metadata restore CLI not working

---

openmetadata-docs/content/developers/contribute/build-code-and-run-tests/prerequisites.md

Maven fails to build the code if the Java version is higher than 11. 

Doc: Update Java prerequisites for build code

---

ingestion/src/metadata/ingestion/lineage/sql_lineage.py
ingestion/tests/unit/test_query_parser.py

Fix `merge into` queries which could start with a comment like:
```sql
/* comment */ 
merge into table_1 using (select a, b from table_2) 
when matched update set t.a = 'value' 
when not matched then insert (table_1.a, table_2.b) values ('value1', 'value2')
```

Fix lineage to support 'merge into' queries starting with comments

---

openmetadata-ui/src/main/resources/ui/src/pages/teams/AddUsersModalV1.tsx

Remove `INITIAL_FROM` import from `AddUserModalV1` to fix UI tests.
#
#
#

Remove INITIAL_FROM constant to fix UI tests

---

openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamHierarchy.tsx
openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/Teams.tsx
openmetadata-ui/src/main/resources/ui/src/interface/teamsAndUsers.interface.ts
openmetadata-ui/src/main/resources/ui/src/pages/teams/TeamsPage.tsx

Issue: #8261 
Includes:
- changes from boolean to number for loader state to account for multiple functions loading data asynchronously
- the teams page will now only load once isdataloading is < 0 otherwise the loader is displayed
Changes made to stop incorrect placeholder appearing when there is a delay in API
#
#
</p>
https://user-images.githubusercontent.com/110955804/197248518-2a9acb38-28ec-459b-ae5a-a511720bacde.mov
#
#

FIX(UI): #8261: Handle Loading States In a Better Way

---

ingestion/src/metadata/cmd.py

Fixed incorrect const import in `cmd.py`
There is no library named `const` which was imported here and this import is causing cli ingestions to fail with below error.
#
#
#

Fixed incorrect const import in cmd.py

---

openmetadata-ui/src/main/resources/ui/src/constants/feed.constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.tsx

- Issue: Closes #8293
- fix the Team redirect URL while mentions
#
#
#
#

Fix UI :- fix the Team redirect url in mentions

---

openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx

- Issue:- #8375
- Added Row count separator in a table entity
#
#
#
#

Fix UI :- Added Row count separator in table entity

---

openmetadata-ui/src/main/resources/ui/src/router/AppRouter.tsx
openmetadata-ui/src/main/resources/ui/src/utils/WebAnalyticsUtils.ts

Closes #8396 
I worked on issue #8396 
#
#
https://user-images.githubusercontent.com/59080942/198370521-4fef9c43-8941-4e99-9532-29b140f38b80.mov
#
#

Fix #8396 Multiple webanalytics events send per single page load

---

ingestion/Dockerfile
ingestion/Dockerfile.ci

Changed the GID used in the ingestion docker images that are causing an error during the following Snyk scan:
```
Step 8/20 : COPY --chown=airflow:airflow ingestion/ingestion_dependency.sh /opt/airflow
unable to convert uid/gid chown string to host mapping: can't find gid for group airflow: no such group: airflow
make[1]: *** [Makefile:231: snyk-ingestion-report] Error 1
make[1]: Leaving directory '/home/runner/work/OpenMetadata/OpenMetadata'
make: *** [Makefile:269: snyk-report] Error 2
```

Update GID used in ingestion docker images

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/src/pages/explore/ExplorePage.component.tsx
openmetadata-ui/src/main/resources/ui/yarn.lock

Fix the issue with `ExplorePage` pagination when filters are applied by adding `useDeepCompareEffect` package to handle effects with objects as dependencies.
#
#
[openmetadata_broken_pagination.webm](https://user-images.githubusercontent.com/88427079/199027272-0a59a59b-db74-47a9-95fb-4e6808e23f04.webm)
#
#

Fix #8450 Explore page pagination not working

---

openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx
openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/RouterUtils.ts

Fixed the below issue:
- Fixed tags page cypress
- tags filter was not selected while redirecting from tags page (tags usage click) to explore page
- fixed database search was broken issue from database page
#8448
#
#
https://user-images.githubusercontent.com/71748675/199013322-3e5ef32f-bd63-42fb-86b5-9dd7727e5e0e.mov
https://user-images.githubusercontent.com/71748675/199013961-82c43758-64cc-48b6-a15e-92e36bf39fa5.mov
#
#

UI: Fixed filter issue on redirection from tags page to explore page

---

openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/CustomControls.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/Lineage.constants.ts

I worked on the below changes:
- Added zoomOnScroll, zoomOnPinch & zoomOnDoubleClick
- Updated code related to zoom
- fixed zoom panel glitch issue, and zoom panel was not getting updated latest zoom value issue
- Added transition effect for zoom
Closes #6942 
#
#
https://user-images.githubusercontent.com/71748675/199211409-d7de9182-3e75-4d16-b724-b7c7b61fc92e.mov
#
#

Fix UI | Enable 2-finger scroll zoom-in/zoom-out on the Lineage tab#6942

---

openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/EntityPopOverCard.tsx
openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.tsx
openmetadata-ui/src/main/resources/ui/src/components/tags-viewer/tags-viewer.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/tags-viewer/tags-viewer.tsx
openmetadata-ui/src/main/resources/ui/src/styles/spacing.less

Closes #7802 
I worked on adding differentiation between tags and the glossary by
- Showing `#` only for tags
- Showing glossary terms first always
#
#
#
#

Fix #7802 Differentiate Tags & Glossary Terms

---

openmetadata-ui/src/main/resources/ui/src/utils/PermissionsUtils.ts

I worked on the removing ConditionalAllow check for Create Operation as we have fixed this issue https://github.com/open-metadata/OpenMetadata/issues/7004
#
#
#
#

Revert #7292 : Add ConditionalAllow check for Create Operation Permission

---

openmetadata-ui/src/main/resources/ui/src/components/BotListV1/BotListV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/UserList/UserListV1.tsx
openmetadata-ui/src/main/resources/ui/src/constants/HelperTextUtil.ts
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json

Closes #8467
I worked on issue #8467 
#
#
#
#

Fix UI(#8467) : Only allow admins to create and update bot and user entities

---

openmetadata-ui/src/main/resources/ui/src/constants/error-message.ts

**Updating the password error string to match the regex**
The error string now mentions that numbers are required in password
Closes: #7994 
#
#
<p align="center"> 
New error string
<br>
</p>
#
#

#7994 Updating password error message to mention numbers.

---

openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx

I worked on fixing an issue where incorrect data was being sent to the PATCH API call for tables resulting in an error while removing tags for columns.
#
#
https://user-images.githubusercontent.com/51777795/200287233-4dcaabb3-9a15-4368-b774-beb0a287bc6e.mov
</p>
#
#

Fix(UI) #8552: Fixed issue with tag removal for columns

---

openmetadata-ui/src/main/resources/ui/src/components/Modals/AnnouncementModal/AddAnnouncementModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/AnnouncementModal/EditAnnouncementModal.tsx
openmetadata-ui/src/main/resources/ui/src/utils/AnnouncementsUtils.ts

I worked on the fixing wrong field names showing in the validation messages for add and edit announcement modal.
#
#
</p>
#
#

Fix(UI) #8563: Fixed field name in announcement modal.

---

openmetadata-ui/src/main/resources/ui/package.json
openmetadata-ui/src/main/resources/ui/src/@types/web-analytics.d.ts
openmetadata-ui/src/main/resources/ui/src/utils/WebAnalyticsUtils.ts
openmetadata-ui/src/main/resources/ui/yarn.lock

Closes #8540 
I worked on issue #8540, which includes.
- Default we will set the expiry of 30 minutes
- If the user is inactive for 30 minutes then the session will expire and a new session will be created.
- If the user is active and interacting with pages then we will reset the expiration by extending the expiry to the next 30 minutes from the current timestamp.
Example :
Let's say the expiry is at "5:45:23 PM", and the user spent some time and then Interact with other pages in 2 minutes so the expiry time will be extended to "5:47:23 PM".
In case of inactivity expiry will remain at "5:45:23 PM".
cc: @harshach @TeddyCr 
#
#
</p>
#
#

Fix #8540 Session ID does not reset for web analytic

---

ingestion/src/metadata/ingestion/source/database/dbt_source.py

Fix #8455: fix dbt test errors when run not passed
#
#
#

Fix #8455: fix dbt test errors when run not passed

---

openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx

Fixed Data is getting round-off at the time of formatting in en-US
Closes #8575 
Closes #8574 
#
#
#
#

UI: Fixed Data is getting round off at the time of formatting in en-US

---

ingestion/src/metadata/utils/source_connections.py
ingestion/tests/unit/test_source_connection.py

I worked on the Fixing Hive connection don't use correct user in the connection from WebUI.
Fix: #8332 
#
#

Fix: Hive connection issue

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/ColumnSummary/ColumnSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/ColumnSummary/ColumnSummary.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/EntitySummaryPanel.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/EntitySummaryPanel.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/EntitySummaryPanel.style.less
openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardV2.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardV2.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCardBody.tsx
openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.tsx
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/styles/app.less
openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx

I worked on adding panel to show entity summary on explore page.
#
#
</p>
#
#

Feat(UI): Added EntitySummaryPanel in Explore page

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.style.less
openmetadata-ui/src/main/resources/ui/src/components/Modals/ModalWithMarkdownEditor/ModalWithMarkdownEditor.tsx
openmetadata-ui/src/main/resources/ui/src/components/SchemaTab/SchemaTab.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx
openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx

(UI) #8513: UI improvements - part 1

---

openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DailyActiveUsersChart.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightDetail.less
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightSummary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightSummary.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DescriptionInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/OwnerInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/PageViewsByEntitiesChart.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TierInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TopViewEntities.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TotalEntityInsight.tsx
openmetadata-ui/src/main/resources/ui/src/constants/DataInsight.constants.ts
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/spacing.less
openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.tsx

Fixes #8639
I worked on issue #8639, which includes,
- Showing overview of entities and web charts
- On click of overview scroll down to a particular chart
- Showing most active user with hover over the card
#
#
https://user-images.githubusercontent.com/59080942/201112686-a395f71f-2158-4d9d-b415-ecfe9875cf73.mov
#
#

Feat #8639 UI : Show charts latest value in data insight overview card and rename datasets to data assets

---

ingestion/src/metadata/orm_profiler/orm/functions/sum.py

Fixes #8430
I'm experiencing this overflow often in my MSSQL logs, often when an ID value or other large int value is summed.  This increases the overflow threshold for `sum()` from 2 billion (2^31) to 9 quintillion (2^63).
Most database variants are affected by this (see the issue for specifics) so I made this the generic function and then created a variant-specific version that doesn't cast, for Snowflake and Vertica.  That may not be necessary if the CAST from int to bigint would be ignored but I couldn't find out and don't have a way to test.
#
#
#
@TeddyCr

cast to bigint to avoid overflow when summing

---

openmetadata-ui/src/main/resources/ui/src/components/EntityInfoDrawer/EdgeInfoDrawer.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/schema-editor/SchemaEditor.tsx

Fixed Lineage SQL query only visible on click
Closes #8628
#
#
https://user-images.githubusercontent.com/71748675/201589001-44c4068e-be1a-49e3-ab62-44ede0dffd6a.mov
#
#

Fixed Lineage SQL query only visible on click #8628

---

openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx

Fixed UI | Table Detail pane on the Lineage tab doesn't show the column count
Closes #6947 
#
#
#
#

UI: Fixed UI | Table Detail pane on the Lineage tab doesn't show the column count

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/src/components/Ingestion/IngestionRecentRun/IngestionRecentRuns.component.tsx

I worked on the updating default status to "--" instead queued
#
#
#
#

fix(ui): update default status to empty instead queued

---

openmetadata-service/src/main/java/org/openmetadata/service/security/DefaultAuthorizer.java

Setting up for the first time auth mechanism for bots could fail in case that `openmetadata` is the auth provider but there is no configuration.

On init the auth provider 'openmetadata' must generate a JWT token if not present on config

---

ingestion/src/metadata/test_suite/validations/table/table_custom_sql_query.py
openmetadata-docs/content/connectors/ingestion/workflows/data-quality/tests.md

The initial implementation of the custom SQL  test was written to support both:
1. no rows return by a query
2. COUNT(*) AS count returning 0
number 2)  is actually proving complex to test as count will depend on whether the `count` alias is set in the query. This particular COUNT(*) test seem to also create confusion from users (from support channel).
To simplify the test we decided to remove 2) and only check if a query retruns rows.
#
#
</p>
#
#

Remove count logic in custom sql test

---

ingestion/src/metadata/ingestion/lineage/sql_lineage.py

'get_table_entities_from_query' was not searching for table entities using uppercase table names.

FIx: 'get_table_entities_from_query' try with uppercase table name

---

.github/workflows/py-cli-e2e-tests.yml

Minor fix on text sent into slack when E2E fails which was not taking into account the variable `$E2E_TEST`.

Fix: minor fix on text sent into slack when E2E fails

---

bootstrap/sql/com.mysql.cj.jdbc.Driver/v006__create_db_connection_info.sql
bootstrap/sql/org.postgresql.Driver/v006__create_db_connection_info.sql

Entity timeseries table missing index on entityFQN causing slower queries

---

ingestion/src/metadata/orm_profiler/orm/functions/median.py
ingestion/src/metadata/orm_profiler/orm/functions/modulo.py

Fixes #8408  pyodbc compiles to c++. When passing `%%` to escape the `%` as per python logic this threw an error when the driver is pyodbc.
#
#
</p>
#
#

Fixes #8408 - added logic for modulo function for pyodbc driver

---

ingestion/src/metadata/ingestion/source/database/datalake.py
ingestion/src/metadata/utils/gcs_utils.py
ingestion/src/metadata/utils/s3_utils.py

Fix #8868: Support  `json.gz` files for datalake
#
#
#

Fix #8868: Support  `json.gz` files for datalake

---

.github/workflows/airflow-apis-tests-3_9.yml
.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql.yml
.github/workflows/java-checkstyle.yml
.github/workflows/maven-build.yml
.github/workflows/py-checkstyle.yml
.github/workflows/py-tests.yml
.github/workflows/yarn-coverage.yml

Downgrade version of wait-on-check-action to 1.0.0 which current version is failing on clean up with the following error:
Version [1.0.0](https://github.com/lewagon/wait-on-check-action/commit/0179dfc359f90a703c41240506f998ee1603f9ea) does not include this part of the code that seems to be the cause of the error:
```yaml
- name: Cache Ruby Gems
uses: actions/cache@v2
with:
path: ${{ github.action_path }}
key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
restore-keys: ${{ runner.os }}-gems-
```
ngestion: @open-metadata/ingestion

Fix: Downgrade version of wait-on-check-action to 1.0.0

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java

Bug when deploying an Ingestion Pipeline which was causing deploy them encrypted.

Fix: Bug when deploying ingestion pipeline

---

openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DailyActiveUsersChart.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DescriptionInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/EmptyGraphPlaceholder.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/KPIChart.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/OwnerInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/PageViewsByEntitiesChart.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TierInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TotalEntityInsight.tsx

I worked on adding an empty data placeholder for the data insight graph
#
#
#
#

UI : Add Empty data placeholder for data insight graph

---

openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/KPILatestResults.tsx

Fixes #8924 
I worked on issue #8924 
#
#
#
#

Fix #8924  KPI completness width should be `currentValue/targetValue`

---

openmetadata-ui/src/main/resources/ui/src/axiosAPIs/searchAPI.ts
openmetadata-ui/src/main/resources/ui/src/components/app-bar/Appbar.tsx
openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/SearchUtils.ts

- Closes #6811
- fix the search bar issue of having quotes in the search text
- fix the search text having `/` in it
#
#
Before : 
After :
#
#

UI : fix the search bar issue having quote in the search text

---

openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java

Fix #8579: Add unit test to cover the cases where columnProfile is null or not being sent by client

---

openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardTitle.component.tsx

Fixes #9093 
I worked on issue #9093 
#
#
https://user-images.githubusercontent.com/59080942/204971175-7d711864-18f2-43e6-af66-a1384650bec5.mov
#
#

Fix 9093 : Search Card Link to smoothly route instead of loading the whole page

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java

Fix #8083: Adding a child term to a parent term in glossary produces error

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java

Fix #8323: GenerateToken can overwrite any relations that user may have

---

openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedList.tsx
openmetadata-ui/src/main/resources/ui/src/utils/TimeUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/TimeUtils.ts

I worked on the fixing relative time related issue on the feeds page
#9089 
#
#
#
#

fix(ui): wrong relative time being rendered

---

openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.less
openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCardBody.tsx
openmetadata-ui/src/main/resources/ui/src/styles/app.less
openmetadata-ui/src/main/resources/ui/src/styles/temp.css

I worked on #9017 
#
#
Before: 
After:
</p>
#
#

Fix(UI)#9017: Fixed description not rendering on explore page in Safari browser

---

openmetadata-ui/src/main/resources/ui/src/pages/LogsViewer/LogsViewer.component.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/LogsViewer/LogsViewer.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/LogsViewer/LogsViewer.interfaces.ts

I worked on fixing the issue mentioned here https://github.com/open-metadata/OpenMetadata/issues/8996#issuecomment-1334138065
#
#
#
#

Fix : Logs screen for data insight pipeline is hanging

---

openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/DatabaseSchemaDetailsUtils.ts

I worked on fixing the issue with soft deleted tables showing on the schema details page.
I also added pagination support for the tables list.
closes #7173 
#
#
https://user-images.githubusercontent.com/51777795/205881365-6c43b862-80a2-494e-a978-d220851faf98.mov
</p>
#
#

Fix(UI)#7173: Fixed issue where soft deleted tables were showing on schema details page

---

openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DescriptionInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/KPIChart.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/OwnerInsight.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightLeftPanel.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.tsx

I worked on removing Y-axis for percentage charts on data insight page
#
#
#
#

UI : Remove Y-axis for percentage charts on data insight page

---

conf/openmetadata.yaml

Fix for #9167 Added a default value for SLACK_CHAT_SLACK_URL which is : [https://slack.open-metadata.org/](https://slack.open-metadata.org/)
Files changed : 
- [conf/openmetadata.yaml](https://github.com/open-metadata/OpenMetadata/blob/main/conf/openmetadata.yaml)
#
#
#

Fixes #9167 - Default value for SLACK_CHAT_SLACK_URL

---

openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DescriptionInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/PageViewsByEntitiesChart.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TierInsight.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TopViewEntities.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TotalEntityInsight.tsx
openmetadata-ui/src/main/resources/ui/src/constants/DataInsight.constants.ts
openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/styles/app.less
openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.tsx

I worked on the data insight feedback
#8996
- make most view data assets clickable 
- Converted all bar graphs to line chart
- Added chart filter functionality on click of legend
- fixed styling
#
#
- make most view data assets clickable 
- Convert all bar graphs to line chart
- Added filter for chart, onClick of legend
- fixed styling 
https://user-images.githubusercontent.com/71748675/207845815-1646e2e6-42e2-4f69-89ba-732fbcf92505.mov
- Convert all bar graph to line chart
#
#

UI: Data insight feedback part 1

---

openmetadata-ui/src/main/resources/ui/src/constants/DataInsight.constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsight.interface.ts
openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.tsx

issue: https://github.com/open-metadata/OpenMetadata/issues/8996#issuecomment-1327618489
Added checkbox dropdown for data insight filters
#
#
#
#

UI: Converted data insight dropdown to checkbox dropdown

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/DashboardSummary/DashboardSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/MlModelSummary/MlModelSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/PipelineSummary/PipelineSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TopicSummary/TopicSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardTitle.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardV2.tsx
openmetadata-ui/src/main/resources/ui/src/styles/components/size.less

I worked on the following:
#
#
https://user-images.githubusercontent.com/51777795/208408449-1c016d6f-d8a8-4dcb-9c8e-597d6d3d7780.mov
</p>
#
#

Improvements(UI): Summary Panel improvements

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/ProfilerDashboard/component/TestSummary.tsx

- Fixed data preserved issue while creating test case
- fixed formatting for y axis tick on test case graph and space issue
#
#
https://user-images.githubusercontent.com/71748675/208465006-0c163248-a623-42cd-9839-5ab0b9c78118.mov
#
#

UI: Fixed test case value preserve issue and test case graph improvement

---

openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TierInsight.tsx
openmetadata-ui/src/main/resources/ui/src/constants/DataInsight.constants.ts
openmetadata-ui/src/main/resources/ui/src/interface/data-insight.interface.ts
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/utils/DataInsightUtils.tsx

UI: Updated Tier label in data insight chart
#9184
#
#
#
#

UI: Updated Tier label in data insight chart

---

openmetadata-ui/src/main/resources/ui/src/components/EntityTable/EntityTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SummaryList/SummaryList.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SummaryList/SummaryList.interface.ts
openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx

I worked on:
- Adding more information such as Primary key, Not null, etc. for columns
- Font weight for types fixed
#
#
</p>
#
#

UI: Added more information for table columns in summary panel.

---

openmetadata-ui/src/main/resources/ui/src/components/EntityList/EntityList.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/MyData/MyData.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/tour-page/TourPage.component.tsx

I worked on:
- Added skeleton loader for 'My Data' and 'Following' Section on the home page
https://user-images.githubusercontent.com/51777795/209053084-9b1252c7-88d0-45f9-9a08-9ceba10ca036.mov
- Fixed counts mismatch for the view all button in the 'My Data' Section
#
#
</p>
#
#

Improvements(UI): My data and Following section improvements

---

openmetadata-ui/src/main/resources/ui/src/pages/ProfilerDashboardPage/ProfilerDashboardPage.tsx

fix redirection issue from entity details page to profiler page
#
#
https://user-images.githubusercontent.com/71748675/209129183-8aa88012-6fb3-42e0-843f-13c0cd262fdb.mov
#
#

fix redirection issue from entity details page to profiler page

---

docker/local-metadata/docker-compose-postgres.yml
docker/local-metadata/docker-compose.yml
docker/metadata/docker-compose-postgres.yml
docker/metadata/docker-compose.yml

Volume had permission errors
```
["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
```
Adding RW permissions on the path works locally but fails on CI. Removing the volumes for now
#
#
</p>
#
#

Removing ES volumes

---

docker/local-metadata/docker-compose-postgres.yml
docker/local-metadata/docker-compose.yml
docker/metadata/docker-compose-postgres.yml
docker/metadata/docker-compose.yml
docker/run_local_docker.sh
ingestion/setup.py
ingestion/src/metadata/cli/docker.py

Fixes #9448
Running docker from CLI failed because of the missing parameter `--project-directory .` to use the created directory `docker-volume`. Instead, it was using the directory of the `docker-compose` file. 
We have updated the library to communicate Python and Docker into a version that supports that parameter. In addition, we have also updated our script to start docker when testing. 

Fix#9448: Add ES volumes

---

ingestion/src/metadata/ingestion/lineage/parser.py
ingestion/src/metadata/ingestion/lineage/sql_lineage.py
ingestion/tests/unit/test_query_parser.py
ingestion/tests/unit/test_sql_lineage.py

This PR will improve SQL column lineage parsing with:
* CTEs support
* Support inline comments
* Expand `*` in sources
We are testing OM and we found a lot of our DBT models did not have column level lineage. After some research we found in the most simple cases was because the parser was not correctly supporting those features. An issue was opened in https://github.com/open-metadata/OpenMetadata/issues/9536 
#
#
N/A
#
#

Improve SQL column lineage parsing

---

openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
openmetadata-ui/src/main/resources/ui/webpack.config.prod.js

I worked on removing react-tippy and rc-tree from webpack config.
#
#
#
#

chore (ui) : remove react-tippy and rc-tree from webpack config

---

openmetadata-ui/src/main/resources/ui/src/components/DashboardDetails/DashboardDetails.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/entityPageInfo/EntityPageInfo.test.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/Glossary.mock.ts
openmetadata-ui/src/main/resources/ui/src/mocks/Tags.mock.ts
openmetadata-ui/src/main/resources/ui/src/utils/SvgUtils.tsx

- Deprecated SvgUtils.tsx file
- Fixed skip unit test 
#
#
</p>
#
#

Fixed: Enabled skipped unit test and deprecated svgUtils.tsx

---

openmetadata-ui/src/main/resources/ui/src/components/GlossaryDetails/GlossaryDetails.component.tsx

UI: Add owner for glossary is not showing option on initial open
Closes #9602 
#
#
https://user-images.githubusercontent.com/71748675/211994334-cc523e94-ad77-4e1d-8ee7-1c1c3c4e0fdd.mov
#
#

Fixed UI: Add owner for glossary is not showing option on initial open  #9602

---

ingestion/src/metadata/ingestion/ometa/client.py
ingestion/src/metadata/ingestion/ometa/ometa_api.py
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/metadata/openMetadataConnection.json

- Allows for extra headers to be provided to the ometa API client
- Adds `extraHeaders` to the `workflowConfig.openMetadataServerConfig` schema
- Supports copying existing header values using string modulo format with the header dictionary
Example usage:
```yaml
openMetadataServerConfig:
hostPort: ${OMD_API_HOST}
authProvider: google
extraHeaders:
Proxy-Authorization: "%(Authorization)s"
Some-Env-Header: ${MY_ENV_VAR}
Static-Header: my-value
```
The primary use case is for Google Cloud's Identity Aware Proxy (IAP) which allows secure access to private services but removes the Authorization header in the process. The `Proxy-Authorization` header gets forwarded along to the service as the `Authorization` header for the service behind IAP. In this case, the token is valid for Google SSO as …

Extra headers for metadata API

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardV2.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/searched-data/SearchedData.tsx

- Issue :  https://github.com/open-metadata/OpenMetadata/issues/9535#issue-1512549001
- Fix the non-selected card color while search in Explore page
#
#
#
#

UI : Fix the non-selected card color while search in Explore page

---

openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/AddIngestion.component.tsx
openmetadata-ui/src/main/resources/ui/src/constants/Ingestions.constant.ts

- Issue : Empty string was passed when classification was empty
- Added default value for DBT Classification field
#
#
#
#

UI : Added default value for DBT Classification field

---

openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightProgressBar.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightProgressBar.tsx
openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/TierInsight.tsx

- Issue : https://github.com/open-metadata/OpenMetadata/issues/9535#issue-1512549001
- Fix the count in Data Insights page on Tier
#
#
#
#

UI : Fix the count in Data Insights page on Tier

---

openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchUtils.test.tsx
openmetadata-ui/src/main/resources/ui/src/utils/AdvancedSearchUtils.tsx
openmetadata-ui/src/main/resources/ui/src/utils/mocks/AdvancedSearchUtils.mock.ts

I worked on the issue where highlighted characters' cases were not proper in options for 'Search Dropdowns'.
Takes care of one issue in #9535 
#
#
Before:
After:
</p>
#
#

fix(ui): search dropdown options case changing issue

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx

I worked on disabling profiler API calls for deleted tables for summary panel details to eliminate errors thrown.
closes #9768 
#
#
Before:
https://user-images.githubusercontent.com/51777795/212962017-814ba6e8-9e8c-401d-af0e-c86e0cfcd696.mov
After:
https://user-images.githubusercontent.com/51777795/212962045-e54872b4-8f0c-4901-94f8-d604b6e3bd36.mov
</p>
#
#

fix(ui): disabled profiler calls for deleted tables for summary panel details

---

openmetadata-ui/src/main/resources/ui/cypress/common/common.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Teams.spec.js
openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/EntitySummaryDetails/EntitySummaryDetails.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/OwnerWidget/OwnerWidgetWrapper.component.tsx

Fixes #9775 
I worked on issue #9775 
#
#
#
#

fix(#9775): UI - Teams owner can only be another user not another team

---

ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/database_service.py
ingestion/src/metadata/ingestion/source/database/datalake/metadata.py
ingestion/src/metadata/ingestion/source/database/deltalake/metadata.py
ingestion/src/metadata/ingestion/source/database/domodatabase/metadata.py
ingestion/src/metadata/ingestion/source/database/dynamodb/metadata.py
ingestion/src/metadata/ingestion/source/database/glue/metadata.py
ingestion/src/metadata/ingestion/source/database/lineage_source.py
ingestion/src/metadata/ingestion/source/database/salesforce/metadata.py

Fix #8884
Fix #9460 
Moved the View Lineage from the metadata ingestion to the lineage workflow. Reasons:
1. We centralize lineage processing in a single place. Makes it easier to debug. The lineage was a `post_processing` at the service level anyway as it required ALL the metadata to be available.
2. There was a bug where we picked up the view definition (twice) and using the latest inspector instead of the one for each database. This simplifies the logic as we just get the tables from the API.
Further work: It would be interesting to add a query parameter for `tableType` when listing tables in the API to only fetch views in these scenarios.
#8884 also listed moving dbt lineage to the lineage workflow. The reason not to is to maintain all the catalog and manifest information when …

Fix #8884 & #9460 - View lineage happens in the lineage workflow

---

.github/workflows/py-checkstyle.yml
ingestion/setup.py
ingestion/src/metadata/ingestion/api/workflow.py
ingestion/src/metadata/ingestion/lineage/models.py
ingestion/src/metadata/ingestion/lineage/parser.py
ingestion/src/metadata/ingestion/lineage/sql_lineage.py
ingestion/src/metadata/ingestion/ometa/client.py
ingestion/src/metadata/ingestion/processor/query_parser.py
ingestion/src/metadata/ingestion/source/database/common_db_source.py
ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
ingestion/src/metadata/ingestion/source/database/lineage_source.py
ingestion/src/metadata/ingestion/source/database/postgres/lineage.py
ingestion/tests/unit/test_sql_lineage.py

I have updated the `sqllineage` used until now with `openmetadata-sqllineage`, which adds an option to extract lineage by using `sqlfluff` as the parser and considers the dialect of the query. Since it is a recent change, we will use the `sqlfluff` parser option as a fallback for the usual lineage extraction. 
In addition, the `LineageParser` now supports the dialect parameter to use `sqllineage` with `sqlfluff`.

Fix: Replace `sqllineage` with `openmetadata-sqllineage`

---

openmetadata-ui/src/main/resources/ui/src/pages/KPIPage/AddKPIPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/KPIPage/EditKPIPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/KPIPage/KPIPage.interface.ts

I worked on the 
issues of Data insight page mentioned in #9819 
#
#
</p>
#
#

fix: start date should be less than end date on KPI page

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TopicSummary/TopicSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TopicSummary/TopicSummary.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/mocks/TopicSummary.mock.ts

I worked on fixing the issue with the topic entity summary panel not showing schema fields
#
#
https://user-images.githubusercontent.com/51777795/214218132-51a6b792-8483-4dc0-9841-0541691c7648.mov
</p>
#
#

fix(ui): topic entity summary panel not showing schema fields

---

openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/common/EntitySummaryDetails/EntitySummaryDetails.tsx
openmetadata-ui/src/main/resources/ui/src/interface/types.d.ts
openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/datasetDetailsPage.mock.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityUtils.tsx

closes #9846 
#
#
https://user-images.githubusercontent.com/51777795/214301582-673332a8-1c88-43c9-99c2-cfb92f41d372.mov
https://user-images.githubusercontent.com/51777795/214301713-5c212de9-9141-40a4-8f3d-22d5e5d81b45.mov
https://user-images.githubusercontent.com/51777795/214301734-79e10408-314c-4c71-8738-07670ee8f5a8.mov
Fixed localization key mismatch: 
</p>
#
#

fix(ui)#9846: row count not populating on table details page

---

openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card-v2/TableDataCardV2.less

- Issue: Change active styling
- Change entity active card styling and hover on cards too
- added initial shadow on cards too
#
#
https://user-images.githubusercontent.com/66266464/214542535-8b3ef230-f9a4-40ba-82d0-6de368a843a3.mov
#
#

UI : Change entity active card styling and hover on cards too

---

.github/workflows/py-cli-e2e-tests.yml
ingestion/tests/cli_e2e/test_cli_db_base.py
ingestion/tests/cli_e2e/test_cli_dbt_base.py

E2E was running tests using a subprocess, and the subprocess was not being considered to measure the coverage.

Fix: Consider coverage on subprocess in E2E CLI tests

---

ingestion/src/metadata/ingestion/source/database/redshift/queries.py

I worked on the #8867 issue because we have the same issue in our deployment
#
#
#

Deduplicate stl_querytext rows, fixes #8867

---

openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SummaryList/SummaryList.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/SummaryList/SummaryListItems/SummaryListItems.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/TableSummary/TableSummary.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx
openmetadata-ui/src/main/resources/ui/src/utils/EntitySummaryPanelUtils.tsx

#
#
**Constraint Icons:**
**Before:**
**After:**
**Summary panel hiding:**
https://user-images.githubusercontent.com/51777795/214601123-d65931c5-cb8c-463b-946a-387f2a792c6d.mov
</p>
#
#

ui: entity summary panel improvements

---

.github/workflows/py-ingestion-publish.yml

This was generated properly in the testing CI but not on the publish. Users kept getting `ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2` as we were not using the right installation recipe
#
#
</p>
#
#

Fix antlr version when publishing the ingestion package

---

openmetadata-ui/src/main/resources/ui/cypress/common/advancedSearchQuickFilters.js
openmetadata-ui/src/main/resources/ui/cypress/constants/advancedSearchQuickFilters.constants.js
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/AdvancedSearchQuickFilters.spec.js
openmetadata-ui/src/main/resources/ui/src/components/Explore/ExploreQuickFilters.tsx
openmetadata-ui/src/main/resources/ui/src/constants/AdvancedSearch.constants.ts
openmetadata-ui/src/main/resources/ui/src/rest/miscAPI.ts

I worked on:
#
#
https://user-images.githubusercontent.com/51777795/215095114-a195bba3-a041-4047-859e-814c378869d7.mov
https://user-images.githubusercontent.com/51777795/215095162-611ba49a-88b4-4001-982a-96dc184264ff.mov
</p>
#
#

fix(ui): ui fixes for search dropdown suggestions API for owner and tag quick filters

---

openmetadata-ui/src/main/resources/ui/src/components/DatasetDetails/DatasetDetails.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/SampleDataTable/SampleDataTable.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfiler.interface.ts
openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/TableProfilerV1.tsx
openmetadata-ui/src/main/resources/ui/src/components/TableQueries/TableQueries.tsx
openmetadata-ui/src/main/resources/ui/src/pages/DatasetDetailsPage/DatasetDetailsPage.component.tsx

I worked on fixing API errors shown for deleted tables on table details page
#
#
**Before:**
https://user-images.githubusercontent.com/51777795/215103547-7deb4b82-d9df-44e4-ba7c-7ebaff8b1397.mov
**After:**
https://user-images.githubusercontent.com/51777795/215103847-18223553-c8de-49d5-a858-e6004d647d86.mov
</p>
#
#

fix(ui): API errors shown for deleted tables on table details page

---

openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BasicAuthenticator.java

When basic auth is enabled and the user is created through the API without a password, the stored auth mechanism is null. This can cause a null pointer exception when changing the user password for the first time.

Bug: Change password of a user without auth mechanism set

---

openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/EntityLineage.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/LineageNodeLabel.tsx
openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/entityLineage.style.less
openmetadata-ui/src/main/resources/ui/src/constants/Lineage.constants.ts
openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx

- Added expand/collapse button for a single node
- Increase default value for zoom out
#
#
https://user-images.githubusercontent.com/71748675/215260008-297356bd-a626-4b03-8381-d0f09bf8e4a6.mov
#
#

UI: Added expand/collapse button for single nodes and increase default value for zoom out  in lineage

---

openmetadata-ui/src/main/resources/ui/src/pages/Glossary/GlossaryLeftPanel/GlossaryLeftPanel.component.tsx
openmetadata-ui/src/main/resources/ui/src/styles/components/button.less

- Fix the add button styling for non admin button
#
#
#
#

UI : Fix the add button styling for non admin button

---

ingestion/src/metadata/utils/ssl_registry.py

When configuring SSL for ingesting, an error on missing 'certificatePath' from SSLConfig object was raised.

Fix: error getting 'certificatePath' from SSLConfig object

---

.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql.yml
.github/workflows/maven-build.yml
.github/workflows/yarn-coverage.yml

I worked on the issue #9638 regarding CI optimisation.
I have tested and found that maven build can help to save 10-15 minutes of time whereas yarn is just approx a minute.
#
#

Adding caching for maven and yarn

---

ingestion/tests/unit/topology/metadata/test_amundsen.py
openmetadata-docs/content/connectors/database/dynamodb/airflow.md
openmetadata-docs/content/connectors/database/dynamodb/cli.md
openmetadata-docs/content/connectors/database/dynamodb/index.md
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/dynamoDBConnection.json

DynamoDB being a NoSQL database it currently does not support the implementation of the profiler, neither can it support dbt ingestion.
This PR cleans up both of this element. We opened an [issue](https://github.com/open-metadata/OpenMetadata/issues/10013) to add profiler support to NoSQL db.
#
#
</p>
#
#

Remove profiler support for dynamodb

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java

With the current logic, when updating test suites, if a test suite is updated via the API without explicitly passing the existing test cases linked to that test suite then all the relationship between the test suite and the test case are deleted.
From a user point of view it seems more confortable to reason in terms of testCase -> testSuite relationship where test cases are added and remove from the perspective of the test case (vs a bi-directional relationship) - i.e. test cases are deleted from test suite through a test case deletion request (vs a test suite update). 
#
#
</p>

fix(testSuite): removed relationship update with testCase on testSuite update

---

ingestion/src/metadata/orm_profiler/orm/functions/datetime.py
openmetadata-docs/content/connectors/ingestion/workflows/profiler/index.md

Bigquery timestamp fields do not support INTERVAL with MONTH and YEAR unit. We decided to raise an exception pointing to the documentation on setting partition for the user (vs doing some approximation).
#
#
</p>
#

Fixes issue #10082 -- Unsupported field types for bigquery

---

.github/workflows/py-tests-skip.yml
.github/workflows/py-tests.yml

pytest CI must be forced in case of changes in `openmetadata-service` or `openmetadata-spec`.

Fix: pytest CI should not skipped with changes on om-spec or om-service

---

openmetadata-ui/src/main/resources/ui/src/components/Glossary/ImportResult/ImportResult.tsx

Fixed scroll issue in the glossary bulk upload preview
#
#
- Success preview
https://user-images.githubusercontent.com/71748675/216602445-5957595f-e31f-4871-bf78-5aafaa2183ff.mov
-Failed preview
https://user-images.githubusercontent.com/71748675/216602647-a87d343b-8702-4317-99b0-f24b8ffa0307.mov
#
#

fixed: scroll issue in glossary preview

---

openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx

fixed  fetch table api in ascending order in schema details page 
#
#
#
#

ui: fetch table api in ascending order in schema details page

---

openmetadata-ui/src/main/resources/ui/src/components/AddTags/AddTags.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddTags/add-tags.component.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/Tags.mock.ts

- fixed: tag api being called on every click in create a glossary and create glossary term page
- Added Unit test for the changes
#
#
https://user-images.githubusercontent.com/71748675/217243938-ebef3a7f-6ca4-4539-969b-71c859d02ffa.mov
#
#

fixed: tag api being called on every click in create glossary and create glossary term page

---

openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx

fix: Table list view within service shows `name` instead of `displayName` #10136

---

openmetadata-ui/src/main/resources/ui/src/components/TableProfiler/Component/ColumnProfileTable.tsx

fix: table scroll in column profile table #10166
#
#
https://user-images.githubusercontent.com/71748675/217870116-5efdf29c-2024-425f-bad4-410a3271280b.mov
#
#

fix: table scroll in column profile table

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java

We were not checking if the user was a bot when updating or creating a bot user.
fixes #10177

Fix#10177: Check if user is bot before update or create a bot user

---

openmetadata-ui/src/main/resources/ui/cypress.config.ts
openmetadata-ui/src/main/resources/ui/cypress/e2e/Flow/SearchFlow.spec.js

As advance search is always running 1st in cypress and it takes a good amount of time and occupies 1 full machine, so renaming the spec to change the order of the test
#
#
</p>
#
#

cypress: rename advanceSearch spec to SearchFlow

---

conf/openmetadata.yaml
openmetadata-docs/content/deployment/security/ldap/index.md
openmetadata-service/src/main/java/org/openmetadata/service/security/auth/LdapAuthenticator.java
openmetadata-service/src/main/java/org/openmetadata/service/util/LdapUtil.java
openmetadata-spec/src/main/resources/json/schema/configuration/ldapConfiguration.json
openmetadata-spec/src/main/resources/json/schema/configuration/ldapTrustStoreConfig/truststoreConfig.json

Fixes #10211
#
#
#
@mohityadav766

Fixed#10211: Enable LDAP configuration to be configured via environment variable

---

openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
openmetadata-ui/src/main/resources/ui/src/pages/explore/ExplorePage.component.tsx

I worked on making changes in explore page not to persist the facet filters on tab change.
#
#
https://user-images.githubusercontent.com/59080942/220620845-9f819e2e-52d7-4f19-8e2a-8b8f06f73040.mov
#
#

chore(ui): do not persist the facet filters on tab change

---

openmetadata-ui/src/main/resources/ui/src/components/nav-bar/NavBar.tsx
openmetadata-ui/src/main/resources/ui/src/utils/BrowserNotificationUtils.test.ts
openmetadata-ui/src/main/resources/ui/src/utils/BrowserNotificationUtils.ts

I worked on adding a check for whether a notification is present in the window because some browser does not support the notification API.
#
#
I have tested on a simulator and the alert shown is only for testing purposes.
https://user-images.githubusercontent.com/59080942/220907380-c42d4e08-ef1d-417d-8dfb-cd20136f17d3.mov
#
#

chore(ui): add check for notification is present or not in the browser

---

ingestion/src/metadata/orm_profiler/api/workflow.py

... even when `serviceConnection` was omitted from workflow YAML.
The profiler workflow tested the `serviceConnection` before attempting to retrieve `serviceConnection` details from OMD server. This meant that you could not store `serviceConnection` credentials for profiling on OMD server; you had to put them inline in the workflow YAML.
The profiler workflow's `_retrieve_service_connection_if_needed` function was missing a negation: It would only try to retrieve `serviceConnection` details from OMD server _if they were already defined in the workflow_. This was opposite the behavior described in the docstring, and meant that even if the first issue above were fixed, you still couldn't retrieve profiling `serviceConnection` details from OMD server.
**NOTE:** I have patched my …

[fixed] profiler would not fetch serviceConnection from OpenMetadata

---

ingestion/operators/docker/Dockerfile
ingestion/operators/docker/Dockerfile-dev
ingestion/operators/docker/main.py
ingestion/operators/docker/test_connection.py
openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/airflow/AirflowRESTClient.java
openmetadata-service/src/main/java/org/openmetadata/service/clients/pipeline/noop/NoopClient.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
openmetadata-service/src/test/java/org/openmetadata/service/pipelineService/MockPipelineServiceClient.java
openmetadata-spec/src/main/java/org/openmetadata/sdk/PipelineServiceClient.java

- Using Response instead of HttpResponse as return type for the Pipeline Service Client methods. It just makes it easier to adapt everywhere.
- Prepared the first version of the test connection entrypoint to the openmetadata/ingestion-base image
#
#
</p>
#
#

Simplify Pipeline Service Client Response and prep test connection for ingestion base

---

openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
openmetadata-ui/src/main/resources/ui/src/pages/AddAlertPage/AddAlertPage.tsx

- Issue : -  Empty object is sent if added fields are empty in filters and destination
- Make generated fields required in filters and destination
#
#
Issue : 
Resolved : 
#
#

Fix(UI) : Make generated fields required in filters and destination

---

ingestion/src/metadata/utils/s3_utils.py

Added endpointURL and region_name in s3_utils.py because this was missing in S3FileSystem
and crashed the ingress (because it called the wrong S3 - storage).
This fixes https://github.com/open-metadata/OpenMetadata/issues/10279
#
#

fix: Use endpointURL and region in s3_fs

---

openmetadata-docs/content/connectors/pipeline/airflow/index.md

Fixed a service name typo that was using `Airbyte` instead of the correct name `Airflow`
#
#
#
not sure who reviews documentation, couldn't find anything specific on the contributing doc

fix service name typo in docs

---

ingestion/src/metadata/ingestion/ometa/client.py
ingestion/tests/integration/ometa/test_ometa_api.py
ingestion/tests/integration/workflow/mysql_test.yaml
ingestion/tests/integration/workflow/test_workflow.py

When the logs are set to `DEBUG` in any ingestion workflow, we print the `Authorization` headers sent to the OM server. This PR masks those values to avoid displaying sensitive information. 

Fix: Stop displaying authorization values in debug logs

---

openmetadata-service/src/main/java/org/openmetadata/service/alerts/gchat/GChatWebhookPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/alerts/generic/GenericWebhookPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/alerts/msteams/MSTeamsWebhookPublisher.java
openmetadata-service/src/main/java/org/openmetadata/service/alerts/slack/SlackWebhookEventPublisher.java

webhook retry code has a bug where if else part should start to look 400+ error instead it was 300
#
#
</p>
#
#

Fix error code if else in webhooks

---

ingestion/src/metadata/ingestion/source/database/column_helpers.py
ingestion/src/metadata/ingestion/source/database/hive/metadata.py
ingestion/src/metadata/profiler/orm/functions/length.py
ingestion/src/metadata/profiler/orm/functions/median.py
ingestion/src/metadata/profiler/orm/functions/random_num.py
ingestion/src/metadata/profiler/orm/registry.py
ingestion/tests/unit/source/test_column_helpers.py

- Colnames were loaded as `table.col`. Fixed to be just `col`.
- We did not retrieve table comments. Ammended that.
- We were missing SQL compilation for Impala which was breaking some metrics.
We still need to figure out some SQL errors on the profiler. I am wondering if my setup is just not correct. Will dig further.
#
#
</p>
#
#

Pyimpala fix colnames, comments and dialect sql compilation

---

ingestion/src/metadata/ingestion/lineage/parser.py
ingestion/src/metadata/utils/timeout.py
ingestion/tests/unit/test_sql_lineage.py

Fix flaky test where testing timeout was not working as expected. Removed unnecessary debug print inside the timeout decorator.

Bug: fix flaky timeout test

---

openmetadata-ui/src/main/resources/ui/src/pages/UserListPage/UserListPageV1.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/UserListPage/UserListPageV1.tsx

I worked on changing the search variable for users and changed it to `userSearchTerm`, because the name was conflicting with the global search.
Closes [#10390](https://github.com/open-metadata/OpenMetadata/issues/10390)
#
#
https://user-images.githubusercontent.com/59080942/224322272-a105c6ff-37a5-47ac-9923-542de9484082.mov
https://user-images.githubusercontent.com/59080942/224326059-86b16385-69fd-4b69-9616-b428751f3846.mov
#
#

chore(ui): change user page search variable name to `user`

---

openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/ParameterForm.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/ParameterForm.tsx
openmetadata-ui/src/main/resources/ui/src/mocks/TestSuite.mock.ts

Make column name a selection box only for tableRowInsertedCountToBeBetween test
#
#
#
#

fix: Make column name a selection box only for tableRowInsertedCountToBeBetween test

---

openmetadata-service/src/main/java/org/openmetadata/service/security/auth/LdapAuthenticator.java

Fix #10580 User cannot sign in when using an LDAP server that deny anonymous binds during SSL-enabled LDAP authentication
#
#
</p>
#
#

Fix #10580: add bindDN and bindPassword to args of LDAPConnection()

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ContainerRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/objectstores/ContainerResourceTest.java

Containers can have `dataModel` as a property. The columns in the data model can have tags, which werent' properly handled by the PATCH operations as the updater was missing all the logic.
As we'll have columns in tables, datamodels and the incoming Data Model Entity for dashboards, we have externalized the columns updater logic so that it can be reused everywhere.
#
#
</p>
#
#

Handle object store tags & Create abstract EntityUpdaterWithColumn

---

ingestion/setup.py
ingestion/tests/unit/topology/database/test_datalake.py

Remove `avro-python3` deprecated dependency

Fix: remove avro-python3 deprecated dependency

---

docker/development/docker-compose.yml
docker/docker-compose-ingestion/docker-compose-ingestion.yml
docker/docker-compose-quickstart/docker-compose.yml

We are not passing the right env variable to the ingestion docker image in the docker-compose.

Fix: pass correct env var to the ingestion docker image

---

ingestion/src/metadata/__version__.py
ingestion/src/metadata/ingestion/ometa/mixins/server_mixin.py
ingestion/src/metadata/ingestion/source/database/oracle/metadata.py
ingestion/src/metadata/ingestion/source/database/oracle/queries.py
ingestion/tests/unit/test_version.py

Fix oracle bulk view definitions and comments & improve metadata version
Oracle was giving us the names in upper case, which did not match the dict keys
#
#
</p>
#
#

Fix oracle bulk view definitions and comments & improve metadata version

---

ingestion/src/metadata/examples/workflows/databricks.yaml
ingestion/src/metadata/ingestion/connections/test_connections.py
ingestion/src/metadata/ingestion/source/database/databricks/connection.py
openmetadata-docs/content/connectors/database/databricks/airflow.md
openmetadata-docs/content/connectors/database/databricks/cli.md
openmetadata-docs/content/connectors/database/databricks/index.md
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/databricksConnection.json

Add timeout parameter in databricks, so we can pass seconds to wait cluster ready
Fix #9639 
#
#
</p>
#
#

Fix databricks timeout issue

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AlertActionRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AlertRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ChartRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DashboardRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataInsightChartRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseSchemaRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryTermRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/KpiRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LocationRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MetricsRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/MlModelRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PolicyRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ReportRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/RoleRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ServiceEntityRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/StorageServiceRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestDefinitionRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TypeRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/WebAnalyticEventRepository.java

Setting the fields `owner`, `tags`, `href` before writing entity JSON to the backend database and restoring them after the write can be moved to `EntityRepository.store()` method instead of doing it in every class the implements the `storeEntity` method.
#
#

Move common functionality to EntityRepository store method

---

ingestion/src/metadata/ingestion/ometa/mixins/user_mixin.py
ingestion/src/metadata/ingestion/sink/elasticsearch_mapping/user_search_index_mapping.py
ingestion/tests/integration/ometa/test_ometa_user_api.py
openmetadata-service/src/main/resources/elasticsearch/en/user_index_mapping.json

The old index and search query properly returned `None` if an email with an unknown domain was sent, e.g., searching by `user@random.com`. However, there were errors if we searched an unexisting email from an existent domain, e.g., `not-a-real-user@known-domain.com`.
This PR adds the email as a keyword and updates the search query to properly flag these cases and avoid false positives in the hits.
#
#
</p>
#
#

Fix search by email index keyword

---

openmetadata-ui/src/main/resources/ui/cypress/constants/constants.js
openmetadata-ui/src/main/resources/ui/cypress/constants/redirections.constants.js
openmetadata-ui/src/main/resources/ui/src/components/MyAssetStats/MyAssetStats.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/MyAssetStats/MyAssetStats.test.tsx
openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx

Fixes #10718
I worked on Bringing back the count for services, teams, and users, and removing the count for glossaries on the landing page.
#
#

fix #10718: Bring back the count for services, teams, and users, and remove the count for glossaries on the landing page.

---

openmetadata-docs/content/overview/releases/index.md

Due to a typo in the year on the [releases page](https://docs.open-metadata.org/overview/releases) it looks like the latest release is more than 1 year ago...
#
#

Fix year of latest release in releases documentation page

---

.github/workflows/maven-build.yml
.github/workflows/py-tests.yml

GitHub actions are not being triggered when the following files are updated:
- Makefile
- pom.xml
- yarn.lock
This PR can only be tested manually and comments in the code are not required.

Fix: Update when GH actions are triggered

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js

fix(test): skip glossary cypress tests

---

.github/workflows/airflow-apis-tests-3_9.yml
.github/workflows/cypress-integration-tests-mysql.yml
.github/workflows/cypress-integration-tests-postgresql.yml
.github/workflows/java-checkstyle.yml
.github/workflows/maven-build.yml
.github/workflows/py-checkstyle.yml
.github/workflows/py-tests.yml
.github/workflows/yarn-coverage.yml

Ref - as per issue mentioned [here](https://github.com/lewagon/wait-on-check-action/issues/59), we will update out `wait-interval` to be 90 seconds between the Github API Requests for this github action step.
Here is the documentation for `wait-interval` - https://github.com/lewagon/wait-on-check-action#wait-interval-optional-default-10
#
#

fix(CI): rate limit issue with lewagon/wait-on-check-action

---

ingestion/src/metadata/ingestion/source/database/snowflake/connection.py

Fix Snowflake Test Connection when no database passed
#
#

Fix Snowflake Test Connection when no database passed

---

ingestion/setup.py

Updated `openmetadata-sqllineage` dependency after releasing version `1.0.3`. It does not need to be fixed to a specific version of `openmetadata-sqllineage`.
#

Update: openmetadata-sqllineage dependency

---

ingestion/src/metadata/data_insight/api/workflow.py
ingestion/src/metadata/data_insight/processor/entity_report_data_processor.py
ingestion/src/metadata/data_insight/processor/web_analytic_report_data_processor.py
ingestion/src/metadata/data_insight/sink/metadata_rest.py
ingestion/src/metadata/ingestion/sink/elasticsearch.py
ingestion/src/metadata/utils/workflow_output_handler.py

Fixes #10911 
- Improve logging output for data insight workflow
**Success**
```logs
[2023-04-04 10:55:09] INFO     {metadata.DataInsight:workflow:298} - Starting data processor execution
[2023-04-04 10:55:09] INFO     {metadata.DataInsight:workflow:216} - Processing data for report type ReportDataType.EntityReportData
[2023-04-04 10:55:14] INFO     {metadata.DataInsight:workflow_reporter:29} - Source: Processed 412 records, filtered 0 records, found 0 errors
[2023-04-04 10:55:14] INFO     {metadata.DataInsight:workflow_reporter:36} - Sink: Processed 0 records, found 0 errors
[2023-04-04 10:55:19] INFO     {metadata.DataInsight:workflow_reporter:29} - Source: Processed 1112 records, filtered 0 records, found 0 errors
[2023-04-04 10:55:19] INFO …
```

Fixes #10911 - Improve Data Insight Logging

---

openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/PolicyEvaluator.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/permissions/PermissionsResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/PolicyEvaluatorTest.java

Fixes #10924 
Trim the redundant permissions in the permission list
#
#
- [x ] My PR title is `Fixes 10924 : Trim the redundant permissions in the permission list`
- [x ] I have commented on my code, particularly in hard-to-understand areas. 
Improvement
- [x ] I have added tests around the new logic.

Fixes #10924 - Trim the redundant permissions in the permission list

---

ingestion/src/metadata/data_quality/validations/table/sqlalchemy/tableCustomSQLQuery.py

add rollback logic to custom sql query to exit out of transaction
#
#

fix: add rollback logic to custom sql query to exit out of transaction

---

ingestion/src/metadata/data_quality/validations/table/base/tableRowInsertedCountToBeBetween.py
ingestion/src/metadata/ingestion/connections/test_connections.py

Fixes #10975
I worked on this issue as it was breaking the workflow as part of an edge case.
#
#

Issue 10975 - fix workflow break at none

---

ingestion/src/metadata/ingestion/source/database/datalake/metadata.py
ingestion/src/metadata/ingestion/source/database/datalake/utils.py
ingestion/tests/unit/topology/database/test_datalake.py

Fix #10273: Parse nested json for dataleke
as of now we parse only top level the json keys
```
{
"level1": {
"level2":{
"level3": 1
}
}
}
```
for example if my data looks like above we only will consider the `level1` as of current implementation 
this pr will improve the parsing logic and will append the children in case of nested records
#
#

Fix #10273: Parse nested json for datalake

---

ingestion/src/metadata/ingestion/source/database/hive/connection.py
ingestion/src/metadata/ingestion/source/database/postgres/connection.py
ingestion/src/metadata/ingestion/source/database/redshift/connection.py
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/hiveConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/postgresConnection.json
openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/redshiftConnection.json
openmetadata-spec/src/main/resources/json/schema/security/ssl/validateSSLClientConfig.json

Added enums and fields for:
- Redshift SSL
- Postgres SSL
- Hive Auth
#
#

Added enum for ssl and auth in redshift, postgres and hive

---

ingestion/tests/cli_e2e/test_cli_mysql.py

I worked on Fixing E2E test for MySql.
It was getting failed because of few tables got deleted.
#
#

Fix E2E for Mysql

---

ingestion/src/metadata/ingestion/source/database/redshift/queries.py

Improve Redshift Query for Usage:
The scans subquery contain the information about the table schema and database information but I've noticed that redshift might not always have that data even though the query is available within the queries sub-query/results 
hence making the scans info as optional as schema and database name can be handled by the es  
#
#

Improve Redshift Query for Usage

---

ingestion/setup.py

Bump `openmetadata-sqllineage` version to 1.0.4.

Fix: bump 'openmetadata-sqllineage' version to 1.0.4

---

ingestion/tests/cli_e2e/common/test_cli_db.py

Fixed profiler partition test by removing count of table process to focus only on the following variable of the tests:
- No failures have been reported on the sink and source side (i.e. partitioning is working as expected)
- Metrics are computed as expected
#
#

fix: remove count of results processed

---

bootstrap/sql/com.mysql.cj.jdbc.Driver/v009__create_db_connection_info.sql
bootstrap/sql/org.postgresql.Driver/v009__create_db_connection_info.sql

In migration vote is an invalid field it needs to be "votes", but can be removed since can be updated later
#
#

Remove "vote" from migration

---

ingestion/tests/cli_e2e/common/test_cli_db.py
ingestion/tests/cli_e2e/test_cli_bigquery.py
ingestion/tests/cli_e2e/test_cli_vertica.py

In https://github.com/open-metadata/OpenMetadata/pull/11169/files we added a filter for the profiler to be executed only against the tables in the `get_include_schema` which can have less tables than in the entire database. This PR adds the possibility to specify the number of table profile we expect.

fix: logic for number of profiled tables

---

ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
ingestion/src/metadata/ingestion/source/dashboard/tableau/models.py

The `dataType` field when querying the Tableau API to extract the Data Models is optional.

Fix: Tableau DataModel optional dataType

---

ingestion/src/metadata/ingestion/source/database/vertica/metadata.py
ingestion/src/metadata/ingestion/source/database/vertica/queries.py

To fetch the vertica comments we have applied a join between `v_catalog.columns` and  `v_catalog.comments` table based on the condition `com.object_name LIKE CONCAT(CONCAT(col.table_name, '_%.'), col.column_name)`
since there is a wildcard it will fetch the comment for a table with similar names for example `table_a.col` and `table_a_new.col` will be considered the columns of the same table, hence this logic is flawed, I've changed it to compare with the object/table id and column name
#
#

Fix Vertica column fetch query

---

ingestion/Dockerfile
ingestion/Dockerfile.ci

Updating the `python-daemon` dep until we do a proper upgrade of the Airflow version https://github.com/apache/airflow/pull/29916
#
#

Bump python-daemon

---

openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/AddIngestion.component.tsx

Fixed issue related to ingestion workflow was not getting triggered
#
#

fix: ingestion was not getting trigger for 1 day scheduler

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/TableResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java

The TableResource only allowed filtering tables by `database`. Adding the logic for filter the list by `databaseSchema` as well.
We can work around this by filtering with `database=<databaseSchemaFQN>` but might be a bit misleading
#
#

Filter tables by databaseSchema

---

ingestion/tests/cli_e2e/base/test_cli_db.py
ingestion/tests/cli_e2e/test_cli_snowflake.py

Increase delay for E2E tests for system tables to register DDL operation
#
#

fix: increase sleep delay for system tables

---

ingestion/src/metadata/ingestion/lineage/parser.py

Fix `ValueError: too many values to unpack` for col lineage
part of fix for #7427 
#
#

Fix `ValueError: too many values to unpack` for col lineage

---

openmetadata-ui/src/main/resources/ui/src/components/AddService/Steps/ConfigureService.tsx
openmetadata-ui/src/main/resources/ui/src/components/CustomEntityDetail/AddCustomProperty/AddCustomProperty.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsForm.tsx
openmetadata-ui/src/main/resources/ui/src/utils/formUtils.tsx

I worked on adding support for internal form item props in form utils.
#
#

chore(ui): add internal form item props support in form utils

---

ingestion/tests/cli_e2e/base/test_cli_db.py
ingestion/tests/cli_e2e/test_cli_snowflake.py

Since the bigquery and snowflake tests are quite unstable due to this. If after this change we keep receiving alerts, let's remove the system metrics tests from here
#
#

Increase wait time for system metrics e2e test

---

ingestion/Dockerfile.ci

Remove `aarch64` from dockerfile  as `aarch64` is not supported by `ibm-db-sa`
#
#

Remove `aarch64` from dockerfile

---

ingestion/examples/sample_data/tests/testSuites.json
ingestion/src/metadata/data_quality/api/workflow.py
ingestion/src/metadata/data_quality/validations/base_test_handler.py
ingestion/src/metadata/ingestion/source/database/sample_data.py
ingestion/tests/integration/ometa/test_ometa_test_suite.py
ingestion/tests/integration/test_suite/test_workflow.py
ingestion/tests/unit/test_suite/test_validations_databases.py
ingestion/tests/unit/test_suite/test_validations_datalake.py
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestSuiteResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java
openmetadata-spec/src/main/resources/json/schema/api/tests/createTestSuite.json
openmetadata-spec/src/main/resources/json/schema/metadataIngestion/testSuitePipeline.json
openmetadata-spec/src/main/resources/json/schema/tests/basic.json
openmetadata-spec/src/main/resources/json/schema/tests/testSuite.json

Fixes #11863
**ingestion**
- added logic to set test case failure status type to `New` on test case failure
**Backend**
- added `executableEntityReference` to test suite object as a link between an entity and an executable test suite (expects the FQN from which we get and link an entity reference). This is only required for executable test suites
- added `patch` endpoint for test case result with path parameter `fqn` corresponding to a test case `fqn` and `timestamp` corresponding to a test case result execution. This will be used to update the "failure status" of the test case result object
#
#

Fixe Issue #11863 - Add Status logic for test case results

---

openmetadata-ui/src/main/resources/ui/src/components/PermissionProvider/PermissionProvider.tsx
openmetadata-ui/src/main/resources/ui/src/components/authentication/auth-provider/AuthProvider.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/authentication/auth-provider/AuthProvider.tsx
openmetadata-ui/src/main/resources/ui/src/utils/LocalStorageUtils.ts

I worked on logic to remove refresh token on logout
#
#

chore(ui): remove refresh token on logout

---

openmetadata-docs/content/v1.0.0/connectors/ingestion/workflows/dbt/ingest-dbt-ui.md

The following note provides more clarification for the users that are trying to ingest data from locally hosted dbt to Openmetadata Local file system.
Added a note For local file system DBT integration
I worked on, this because the statement lacks clarity for the end users.
#

Added Note for Local File System Ingestion (ingest-dbt-ui.md)

---

ingestion/src/metadata/profiler/api/workflow.py
ingestion/src/metadata/profiler/interface/profiler_protocol.py
ingestion/src/metadata/profiler/interface/sqlalchemy/sqa_profiler_interface.py
ingestion/src/metadata/profiler/processor/core.py

Implement logic to release connection from QueuePool on the profiler side.
#
#

fix: release connection from engine pool

---

openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ServiceEntityResource.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/services/metadata/MetadataServiceResource.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/services/MetadataServiceResourceTest.java

The previous code missed adding auto-generated UUID.
#
- [x ] Bug fix
#

Fix #12014: Register OpenMetadata as a service when the server starts.

---

openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestCaseRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TestSuiteRepository.java
openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestCaseResourceTest.java
openmetadata-service/src/test/java/org/openmetadata/service/resources/dqtests/TestSuiteResourceTest.java

Fixes #12069 
- Consolidated `getTestSummary` logic in `EntityUtils`
- Updated tests to catch testSummary returning no value when testCases are passed
- added extension filter to collection query
- added `testSuiteId` field to `testCases/executionSummary` endpoint
#
#

Fixes #12069 - Test Case Summary for testSuite endpoint return 0

---

openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Roles.spec.js
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/EditTestCaseModal.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddDataQualityTest/components/TestCaseForm.tsx
openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/Steps/ConfigureIngestion.tsx
openmetadata-ui/src/main/resources/ui/src/components/CreateUser/CreateUser.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/CreateUser/CreateUser.test.tsx
openmetadata-ui/src/main/resources/ui/src/components/Modals/EntityNameModal/EntityNameModal.component.tsx
openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTConfigFormBuilder.tsx
openmetadata-ui/src/main/resources/ui/src/pages/AddAlertPage/AddAlertPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/AddDataInsightReportAlert/AddDataInsightReportAlert.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/AddPolicyPage/AddPolicyPage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/PoliciesPage/RuleForm/RuleForm.tsx
openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/AddRolePage/AddRolePage.tsx
openmetadata-ui/src/main/resources/ui/src/pages/TestSuitePage/AddTestSuiteForm.tsx
openmetadata-ui/src/main/resources/ui/src/pages/teams/AddTeamForm.tsx

Part of #11358 
I worked on adding support for parenthesis in the entity name
#
#

chore(ui): allow parenthesis in entity name
