open-metadata/OpenMetadata

- openmetadata-docs/content/v1.6.x/deployment/security/oidc/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/security/oidc/index.md
I worked on Note Addition in OIDC.
#
#
> Docs: Note Addition in OIDC

- openmetadata-docs/content/v1.6.x/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/postgres/index.md
I worked on PostgresSQL Doc Updation.
#
#
> Docs: PostgresSQL Doc Updation

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
Addresses this error in openmetadata ops
```
Failed to reindex due to 
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class org.openmetadata.schema.system.EventPublisherJob (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; org.openmetadata.schema.system.EventPublisherJob is in unnamed module of loader 'app')
at org.openmetadata.service.util.OpenMetadataOperations.executeSearchReindexApp(OpenMetadataOperations.java:786)
at org.openmetadata.service.util.OpenMetadataOperations.reIndex(OpenMetadataOperations.java:730)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at …
```
> MINOR: fix: convert json values for app configs

- openmetadata-docs/content/v1.6.x/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/postgres/index.md
I worked on PostgresSQL Doc formating FIX.
#
#
> Docs: PostgresSQL Doc Formating Fix

- openmetadata-docs/content/partials/v1.7/connectors/dashboard/dashboard-lineage.md
I worked on 1.7 Lineage Heading Fix
#
#
> Docs: 1.7 Lineage Heading Fix

- openmetadata-docs/content/v1.6.x/how-to-guides/data-quality-observability/quality/tests-yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/tests-yaml.md
I worked on Note Addition in Custom SQL Test.
#
#
> Docs: Note Addition in Custom SQL Test

- ingestion/src/metadata/examples/workflows/nifi.yaml
- ingestion/src/metadata/ingestion/ometa/client.py
- ingestion/src/metadata/ingestion/source/pipeline/nifi/client.py
- ingestion/src/metadata/ingestion/source/pipeline/nifi/connection.py
> Fixes ISSUE-13953: Converted Nifi Client from requests module to OM REST client

- openmetadata-ui/src/main/resources/ui/src/components/Database/DatabaseSchema/DatabaseSchemaTable/DatabaseSchemaTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/APICollectionPage/APICollectionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/SchemaTablesTab.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceMainTabContent.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/Database/Database.util.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/Database/Database.util.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseSchemaDetailsUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseSchemaDetailsUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseServiceUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseServiceUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtilClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
- I worked on hidding  the import/export manage items and bulk edit button in case of entity is delete
Issue : 
Resolved : 
#
#
> MINOR: hide the import/export and bulk edit button in case of entity is delete

- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
so it can be used with children classes
#
#
> MINOR: chore: make AppResource/convertPipelineStatus protected

- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Pipeline/Airflow.md
I worked on removing the Horizontal Rule from Service Connection page
#
#
> Docs: Fixing Service Connection Page for Airflow Connector

- openmetadata-ui/src/main/resources/ui/src/components/DataAssetSummaryPanel/DataAssetSummaryPanel.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.ts
1. Fixes  the below issue of empty block getting displayed for Data Assets Summary Panel
Issue
Fix
[
](url)
2. Formatting issue in description cards
Issue
fix
#
#
> Fix: Assets Tab empty Summary panel and text formatting Bug 

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
> added missing search cleanup

- openmetadata-ui/src/main/resources/ui/src/components/ServiceInsights/PlatformInsightsWidget/PlatformInsightsWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ServiceInsights/ServiceInsightsTab.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/Ingestion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/ServiceConfig/FiltersConfigForm.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/ServiceConnection.constants.ts
- openmetadata-ui/src/main/resources/ui/src/enums/ServiceConnection.enum.ts
- openmetadata-ui/src/main/resources/ui/src/utils/ServiceInsightsTabUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/date-time/DateTimeUtils.ts
-  Added data formatting to the platform insights charts to insert the data for missing days for a better view in case of no past data
#
#
> Minor: Refactor Service Insights and Ingestion Components

- openmetadata-ui/src/main/resources/ui/src/components/Database/DatabaseSchema/DatabaseSchemaTable/DatabaseSchemaTable.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Database/DatabaseSchema/DatabaseSchemaTable/DatabaseSchemaTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Database.constants.ts
- openmetadata-ui/src/main/resources/ui/src/utils/APICollection/APICollectionClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/APIEndpoints/APIEndpointClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/ContainerDetailsClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DashboardDataModelClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DashboardDetailsClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/Database/DatabaseClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseSchemaClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/Domain/DomainClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/GenericWidget/GenericWidgetUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/MetricEntityUtils/MetricDetailsClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/MlModel/MlModelClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/PipelineClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/SearchIndexDetailsClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/StoredProcedureClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TableClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TopicClassBase.ts
> chore(ui): update entity page layout

- openmetadata-ui/src/main/resources/ui/src/components/SearchSettings/SearchPreview/SearchPreview.test.tsx
Fixed the failing unit test for Search Preview component
#
#
> test(ui): fix search preview test case

- conf/openmetadata.yaml
- openmetadata-service/src/main/java/org/openmetadata/service/security/AuthenticationException.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/SecurityUtil.java
- openmetadata-spec/src/main/resources/json/schema/configuration/authorizerConfiguration.json
- openmetadata-ui/src/main/resources/ui/src/generated/configuration/authorizerConfiguration.ts
Added allowed domains in case more than one domain needs to be allowed
#
#
> Add Multiple Allowed Domains on enforcePrincipalDomain

- ingestion/tests/integration/ometa/test_ometa_bot_rbac.py
> MINOR: Fix failing pytest

- .github/workflows/maven-build.yml
- openmetadata-ui/src/main/resources/ui/jest.config.js
- openmetadata-ui/src/main/resources/ui/package.json
- include the junit for UI in the test report in github actions
- this will solve the false positive for "publish test report" and reduce feedback loop for getting failing tests
for example, in this case one cannot explore the logs directly in the UI as they are too large. but the published test 
report provides no context on the failing tests.
[link to original job](https://github.com/open-metadata/OpenMetadata/actions/runs/13815787485/job/38648487744)
#
#
> MINOR: ci: create a junit test report for CI

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SuggestionRepository.java
Add the right change summary when accepting suggestions
#
#
> MINOR - Suggested patches should have ChangeSource Suggested

- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchSourceBuilderFactory.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchSourceBuilderFactory.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchSourceBuilderFactory.java
- openmetadata-service/src/main/resources/json/data/searchSettings/searchSettings.json
> Search issues: Revert to using queryStringBuilder

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/processors/DataInsightsEntityEnricherProcessor.java
> MINOR: Fix ChangeSummary NullPointerException

- openmetadata-docs/content/partials/v1.6/connectors/yaml/common/gcp-config-def.md
- openmetadata-docs/content/partials/v1.6/connectors/yaml/common/gcp-config.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/common/gcp-config-def.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/common/gcp-config.md
- openmetadata-docs/content/v1.6.x/connectors/database/bigquery/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/bigtable/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/gcs-datalake/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/ml-model/vertexai/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/storage/gcs/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/bigquery/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/bigtable/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/gcs-datalake/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ml-model/vertexai/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/gcs/yaml.md
I worked on GCP Partial Creation and Addition.
#
#
> Docs: GCP Partial Creation and Addition

- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
I worked on Release Hyper Link Correction.
#
#
> Docs: Release Hyper Link Correction

- bootstrap/sql/migrations/native/1.7.0/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.7.0/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.7.0/postgres/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.7.0/postgres/schemaChanges.sql
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/triggers/PeriodicBatchEntityTrigger.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/flowable/builders/FieldExtensionBuilder.java
1. Moved schema migrations to correct file.
2. Added a `required` flag to the field extension build to allow null values.
#
#
> MINOR fix: workflow definition 1.7 migrations

- ingestion/src/metadata/ingestion/source/database/db2/service_spec.py
- ingestion/src/metadata/ingestion/source/database/druid/service_spec.py
- ingestion/src/metadata/ingestion/source/database/greenplum/service_spec.py
- ingestion/src/metadata/ingestion/source/database/hive/service_spec.py
- ingestion/src/metadata/ingestion/source/database/impala/service_spec.py
- ingestion/src/metadata/ingestion/source/database/mariadb/service_spec.py
- ingestion/src/metadata/ingestion/source/database/pinotdb/service_spec.py
- ingestion/src/metadata/ingestion/source/database/singlestore/service_spec.py
- ingestion/src/metadata/ingestion/source/database/sqlite/service_spec.py
- ingestion/src/metadata/ingestion/source/database/teradata/service_spec.py
CHERRY PICKING [https://github.com/open-metadata/OpenMetadata/pull/19293](THIS) FOR PATCH RELEASE 
Added lineage_source_class and profiler_class inside service_spec of different connectors
- Added lineage source class 
- We were facing an error :-
```
File "/opt/airflow/venv-1.6.1/lib64/python3.9/site-packages/metadata/utils/importer.py", line 130, in import_from_module
module_name, obj_name = key.rsplit(MODULE_SEPARATOR, 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
```
- This occured because during the lneage execution the code was expecting a lineage_source_class from service_spec and it got None.
#
#
> resolved <NoneType object has no attribute rsplit> issue

- ingestion/src/metadata/profiler/orm/converter/base.py
- ingestion/tests/cli_e2e/test_cli_oracle.py
…orkflow agents (#20309)"
This reverts commit 20ab64d1f1e782d6f21ae91f33198a21a8d70fba.
#
#
> Revert #17660: Oracle Lowercase Invalid Identifier Fix

- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
Fix: Tableau CustomSQL datasource SQL not shown
#
#
> Fix: Tableau CustomSQL datasource SQL not shown

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityInfoDrawer/EntityInfoDrawer.component.tsx
- I worked on fixing the display not render in lineage drawer
Issue:
Resoved : 
#
#
> MINOR: fix the display not render in lineage drawer

- openmetadata-docs/content/partials/v1.6/connectors/yaml/common/aws-config-def.md
- openmetadata-docs/content/partials/v1.6/connectors/yaml/common/aws-config.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/common/aws-config-def.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/common/aws-config.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/quicksight/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/athena/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/dynamodb/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/glue/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/s3-datalake/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md
- openmetadata-docs/content/v1.6.x/connectors/messaging/kinesis/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/ml-model/sagemaker/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/glue-pipeline/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/storage/s3/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/quicksight/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/athena/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/dynamodb/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/glue/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/s3-datalake/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/messaging/kinesis/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ml-model/sagemaker/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/glue-pipeline/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/s3/yaml.md
I worked on Aws Partial Addition in Connectors.
#
#
> Docs: Aws Partial Addition in Connectors

- openmetadata-docs/content/partials/v1.6/connectors/yaml/common/azure-config-def.md
- openmetadata-docs/content/partials/v1.6/connectors/yaml/common/azure-config.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/common/azure-config-def.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/common/azure-config.md
- openmetadata-docs/content/v1.6.x/connectors/database/adls-datalake/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/datafactory/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/storage/adls/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/adls-datalake/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/datafactory/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/adls/yaml.md
I worked on Azure Partial Creation and Addition.
#
#
> Docs: Azure Partial Creation and Addition

- ingestion/src/metadata/profiler/orm/converter/converter_registry.py
- ingestion/src/metadata/profiler/orm/converter/mariadb/converter.py
- ingestion/src/metadata/profiler/orm/registry.py
- ingestion/src/metadata/profiler/orm/types/custom_time.py
> MINOR: Fix mariadb profiling with Time datatype

- openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionResource.java
Fixes - https://github.com/open-metadata/OpenMetadata/issues/13682
#
#
> Adds missing permissions on alerts

- bootstrap/sql/migrations/native/1.6.7/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.6.7/postgres/schemaChanges.sql
Found using [this scanning script](https://gist.github.com/sushi30/dfca65378d58192b1525d54f4c037984).
#
#
> MINOR: chore: added missing timestamp indexes for time series tables

- openmetadata-service/src/main/java/org/openmetadata/service/config/AzureConfiguration.java
- openmetadata-service/src/main/java/org/openmetadata/service/config/S3Configuration.java
> Add private key configs to ObjectStorage

- openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationProcess.java
added javadoc for org.openmetadata.service.migration.api.Migration
#
#
> MINOR: docs: migration process

- .gitignore
- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/ingestion/source/database/sql_column_handler.py
- ingestion/src/metadata/utils/credentials.py
- openmetadata-spec/src/main/resources/json/schema/security/credentials/gcpCredentials.json
- openmetadata-spec/src/main/resources/json/schema/security/credentials/gcpExternalAccount.json
- openmetadata-ui/src/main/resources/ui/src/generated/security/credentials/gcpCredentials.ts
This pull request includes several changes to improve the handling of Google Cloud Platform (GCP) credentials and enhance the BigQuery metadata ingestion process. The most important changes include adding support for GCP Application Default Credentials (ADC), updating the project ID retrieval logic, and improving the handling of nested columns in BigQuery.
Enhancements to GCP credentials handling:
* [`ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py`](diffhunk://#diff-307b9dbe870ac6a21e89eecf8bda90fc03493bf448ded0203bd30bb6a761efbdR55-R57): Added support for `GcpExternalAccount` and updated the `set_project_id` method to handle project IDs from service connections or ADC. [[1]](diffhunk://#diff-307b9dbe870ac6a21e89eecf8bda90fc03493bf448ded0203bd30bb6a761efbdR55-R57) …
> Fixes #18346: feat(BigQuery) Enhance project ID discovery and ADC support

- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/ingestion/source/database/sql_column_handler.py
This pull request includes several updates to the `ingestion` module, specifically targeting the handling of BigQuery metadata and column processing. The most important changes involve removing a custom column type processing method for BigQuery and updating the logic for processing column children in the `sql_column_handler`.
* Removed the `_process_col_type` method from `metadata.py`, which previously forced the parsed string to be `None` for BigQuery to ensure standard column type handling.
* Updated the `process_column` method in `sql_column_handler.py` to remove the conditional logic that set `arrayDataType` to `UNKNOWN` if `arr_data_type` was not present.
* Added logic to prioritize source-provided children for column processing in the `process_column` method, ensuring that any …
> MINOR: Enhance SQL column processing for BigQuery ingestion

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardNew/ActivityFeedcardNew.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/EntityPopOverCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/popover-card.less
Added entity links for Entity Created/Deleted cards on Activity Feed Card
https://github.com/user-attachments/assets/a724ba4b-5efc-406d-8c9e-dde44433c5f1
Fix
https://github.com/user-attachments/assets/859bc9a0-287e-49f9-9435-1dec81c1eed1
#
#
> Minor: Links for entity card on Activity Feed

- openmetadata-ui/src/main/resources/ui/src/components/common/AirflowMessageBanner/airflow-message-banner.less
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JSONSchemaTemplate/ObjectFieldTemplate.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts
Updated field to take up additional fields.
#
#
> Update field changes

- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v170/MigrationUtil.java
Fix Migration for postgres 
#
#
> Fix Migration for postgres for Lineage

- ingestion/src/metadata/ingestion/source/database/dbt/dbt_config.py
Fix - DBT Better Logs and Improved Error Handling
#
#
> Fix - DBT Better Logs and Improved Error Handling

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/opensearch/OpenSearchDataInsightsClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/CostAnalysisWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/DataAssetsWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataQuality/DataQualityWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/WebAnalyticsWorkflow.java
Fixes issue with deleting AWS OpenSearch Data Streams.
Adds some minor INFO logs
#
#
> MINOR: Fix DI Data Stream delete on OpenSearch

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Container.spec.ts
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/ContainerDetailUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/ContainerDetailsClassBase.ts
Updated to have a count of Schema and Children tabs for container.
#
#
> Updated the count in tabs for containers

- openmetadata-ui/src/main/resources/ui/src/components/SearchSettings/EntitySeachSettings/EntitySearchSettings.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/StatusAction/status-action.less
- openmetadata-ui/src/main/resources/ui/src/pages/SearchSettingsPage/SearchSettingsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/SearchSettingsPage/search-settings.less
- Fixed restore defaults action
- Fixed Add button behaviour for Term Boost and Field Value Boost
https://github.com/user-attachments/assets/f8890728-a39c-4582-871b-91a46bff8617
https://github.com/user-attachments/assets/99cd1574-8c6f-4e74-a97a-05558c5df3f8
#
#
> fix(ui): restore defaults and add term boosts for search ranking settings

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/search/opensearch/OpenSearchDataInsightsClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/costAnalysis/CostAnalysisWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataAssets/DataAssetsWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/dataQuality/DataQualityWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/workflows/webAnalytics/WebAnalyticsWorkflow.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
Fix delete data stream on AWS OpenSearch
Minor INFO logs added
#
#
> Fix DI Data Stream delete on OpenSearch

- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightHeader/DataInsightHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/GlossaryUtils.tsx
- I worked on fixing glossary table column width 
Issue : 
https://github.com/user-attachments/assets/3fcd7be6-c042-4eec-8de9-2f4e9b95505a
Resovled : 
https://github.com/user-attachments/assets/3b2170fe-41b6-497f-a394-3f04679b105a
#
#
> fix the glossary table column width

- .github/workflows/playwright-postgresql-e2e-skip.yml
- .github/workflows/playwright-postgresql-e2e.yml
> ci(pw): increase number of machine to fasten the results

- bin/openmetadata-server-start.sh
> Fix openmetadata-server-start.sh can't start in daemon

- ingestion/src/metadata/ingestion/lineage/models.py
- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
- ingestion/src/metadata/ingestion/source/database/lineage_source.py
- ingestion/src/metadata/ingestion/source/database/snowflake/lineage.py
> MINOR: Lineage Improvements

- openmetadata-docs/content/v1.6.x/connectors/database/mysql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/index.md
> Docs: mysql docs update

- ingestion/src/metadata/data_quality/validations/table/base/tableCustomSQLQuery.py
- ingestion/src/metadata/utils/helpers.py
- ingestion/tests/integration/datalake/test_datalake_profiler_e2e.py
- ingestion/tests/integration/datalake/test_ingestion.py
- openmetadata-service/src/main/resources/json/data/tests/tableCustomSQLQuery.json
This pull request includes changes to enhance the data quality validation process by adding a new operator parameter, refactoring code to use a new helper function, and updating test files to improve maintainability.
Enhancements to data quality validation:
* [`ingestion/src/metadata/data_quality/validations/table/base/tableCustomSQLQuery.py`](diffhunk://#diff-29f5b2d20440c54350b015ca873c9b6e36c46980b85ec642d39e4dc15476b092R55-R58): Added the `operator` parameter to the `run_validation` method and used the new `evaluate_threshold` function to compare results against the threshold. [[1]](diffhunk://#diff-29f5b2d20440c54350b015ca873c9b6e36c46980b85ec642d39e4dc15476b092R55-R58) [[2]](diffhunk://#diff-29f5b2d20440c54350b015ca873c9b6e36c46980b85ec642d39e4dc15476b092R72) …
> Fixes 19119: Enhance TableCustomSQLQueryValidator to support threshold operation

- ingestion/src/metadata/ingestion/ometa/mixins/table_mixin.py
- ingestion/tests/integration/ometa/test_ometa_table_api.py
> Fix #20236: Handle Sample Data with non-utf8 characters

- openmetadata-ui/src/main/resources/ui/src/components/common/Table/table.less
- I worked on removing extra padding
#
#
> MINOR: fix table padding

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/ChangeLogs.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> chore(ui): update what's new data content for 1.6.7

- openmetadata-docs/content/v1.6.x/connectors/database/mysql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/index.md
> MINOR: Add mysql missing permissions docs

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/data-asset-header.less
- openmetadata-ui/src/main/resources/ui/src/utils/DataAssetsHeader.utils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/DataAssetsHeader.utils.tsx
- I worked on fixing spacing around dataAssetHeader with items count
Issue : 
Resolved : 
#
#
> FIX:  spacing around dataAssetHeader with items count

- ingestion/src/metadata/ingestion/models/custom_pydantic.py
> MINOR: Fix python checkstyle

- openmetadata-docs/content/partials/v1.6/connectors/troubleshooting.md
- openmetadata-docs/content/partials/v1.7/connectors/troubleshooting.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/connectors/api/rest/index.md
- openmetadata-docs/content/v1.6.x/connectors/api/rest/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/domo-dashboard/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/domo-dashboard/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/lightdash/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/lightdash/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/looker/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/looker/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/metabase/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/metabase/troubleshooting.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/api/rest/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/api/rest/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/domo-dashboard/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/domo-dashboard/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/lightdash/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/lightdash/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/looker/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/looker/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/metabase/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/metabase/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on 5 Connectors API and Dashboard Troubleshooting Updation.
#
#
> Docs: 5 Connectors API and Dashboard Troubleshooting Updation

- openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/LeftSidebar.component.tsx
- I worked on  removing home redirect link from the navbar logo, since we now have a dedicated home button in left sidebar
#
#
> MINOR: remove home redirect link from the navbar logo

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SuggestionRepository.java
> FIX - Single suggestion should be marked as Suggested too

- openmetadata-service/src/main/java/org/openmetadata/service/security/AuthenticationException.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java
Fix token message
Update message
#
#
> Fix token invalid message

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
In case the search source filter does not have teh query it can run into issues
#
#
> Add null check for buildSearchSourceFilter

- openmetadata-ui/src/main/resources/ui/src/components/MyData/LeftSidebar/LeftSidebar.component.tsx
Reverts open-metadata/OpenMetadata#20513
> Revert "MINOR: remove home redirect link from the navbar logo"

- openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts
Updated the return value and type in getExtraInfo method to make it consistent for collate.
#
#
> MINOR: update getExtraInfo return type

- openmetadata-docs/content/v1.6.x/quick-start/getting-started/day-1/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/quick-start/getting-started/day-1/index.md
Fixing Day1 Docs Requirement Section
#
#
> Docs: Fixing Day1 Docs Requirement Section

- .github/workflows/playwright-integration-tests-mysql.yml
- .github/workflows/playwright-integration-tests-postgres.yml
- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
- ingestion/setup.py
- ingestion/src/metadata/ingestion/models/custom_pydantic.py
This pull request includes several changes to the GitHub workflows and the `ingestion/setup.py` file to improve the handling of Playwright dependencies. The most important changes include updating the workflows to use a specific set of Playwright dependencies and defining these dependencies in the `setup.py` file.
Updates to GitHub workflows:
* [`.github/workflows/playwright-integration-tests-mysql.yml`](diffhunk://#diff-93fde4fd4b40f08b36ca37b27e589fe4aed889ccce9a20d29ebeffbc2338a2e8L87-R87): Changed `ingestion_dependency` from "all" to "playwright" to limit dependencies to only those required for Playwright tests.
* [`.github/workflows/playwright-integration-tests-postgres.yml`](diffhunk://#diff-60d5e3111de4e84051a7f3b8b48e5031e79a42054ab991ae2df15d57455c5f9aL87-R87): Changed …
> MINOR: Update Playwright integration test workflows to use 'playwright' deps

- openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts
This pull request includes a modification to the `getAuthContext` function in the `openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts` file to improve the handling of authentication requests.
Improvements to authentication request handling:
* [`openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts`](diffhunk://#diff-083eec9d4ac00cdb5b7dd06c76abd61667b6f6abdd7cedc2c16a927180127d67L51-R53): Increased the request timeout from 60 seconds to 90 seconds and added the `Connection: 'keep-alive'` header to maintain persistent connections.
#
#
> fix(test): apiContext socket hangup issue in AUTs

- ingestion/tests/integration/conftest.py
- ingestion/tests/integration/mysql/conftest.py
- ingestion/tests/integration/mysql/test_classifier.py
Following https://github.com/open-metadata/OpenMetadata/pull/19711, I suggest testing for dangling connections in our integration tests. OpenMetadata agents should leave the databases without any dangling connections as this takes up resources from the database systems.
This change adds an assertions for dangling connections on MySQL. Currently the ingestion framework does leave some connections.
#
#
> MINOR: test: assert dangling db connections

- ingestion/src/metadata/ingestion/source/database/postgres/lineage.py
- ingestion/src/metadata/utils/db_utils.py
> MINOR: Fix public schema lieage for postgres

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/TriggerInterface.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/triggers/EventBasedEntityTrigger.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/triggers/NoOpTrigger.java
- Adds a listener to update the Workflow Instance in case an Exception happens on a given Step
- Update logic for the External Pipeline in the Day One Workflow (Collate AI Documentation Agent)
- Now it deploys a pipeline with the updated configuration and then deploys a pipeline with the current configuration. No updating the application itself.
#
#
> MINOR: Fix collate ai documentation agent

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedListV1New.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableTags/TableTags.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsViewer/TagsViewer.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TourUtils.tsx
**Fixed Tour page**
Before
After
**Worked on tags data inside table, initially there should be 3 tags visible instead of 5, decreasing row height.**
Before
After
#
#
> fix(ui): tour page and tags data inside table

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkEditEntity.spec.ts
- skip BulkEdit Entity Database playwright test
- Issue is on the Database level, in middle of the action somehow Entity Table Column data appears in the DataGrid. On Local environment it doesn't appear on multiple tries. Currently disabling the test and will further investigate on it and enable the test. 
#
#
> PLAYWRIGHT: skip BulkEdit Entity Database playwright test

- openmetadata-docs/content/v1.6.x/deployment/ingestion/external/mwaa.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/ingestion/external/mwaa.md
I worked on Note Updation in Mwaa.
#
#
> Docs: Note Updation in Mwaa

- openmetadata-docs/content/v1.6.x/how-to-guides/data-quality-observability/quality/test.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/test.md
I worked on Collate Mention in Table Data to Be Fresh.
#
#
> Docs: Collate Mention in Table Data to Be Fresh

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/qliksense/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/qliksense/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/quicksight/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/quicksight/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/redash/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/redash/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/sigma/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/sigma/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/superset/index.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/superset/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/dashboard/tableau/troubleshooting.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/qliksense/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/qliksense/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/quicksight/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/quicksight/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/redash/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/redash/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/sigma/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/sigma/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/superset/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/superset/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/tableau/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/dashboard/tableau/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on  Connectors Troubleshooting addition for Dashboard.
#
#
> Docs: Connectors Troubleshooting addition for Dashboard

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/connectors/search/elasticsearch/index.md
- openmetadata-docs/content/v1.6.x/connectors/search/elasticsearch/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/storage/adls/index.md
- openmetadata-docs/content/v1.6.x/connectors/storage/adls/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/storage/gcs/index.md
- openmetadata-docs/content/v1.6.x/connectors/storage/gcs/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/storage/s3/index.md
- openmetadata-docs/content/v1.6.x/connectors/storage/s3/troubleshooting.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/search/elasticsearch/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/search/elasticsearch/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/search/opensearch/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/search/opensearch/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/adls/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/adls/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/gcs/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/gcs/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/s3/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/storage/s3/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on Troubleshoot Section Addition.
#
#
> Docs: Troubleshoot Section Addition

- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/storage/StorageServiceResource.java
Adds PATCH endpoint to update storage service by FQN
This pull request introduces a new endpoint to the `StorageServiceResource` class to allow updating a storage service by its fully qualified name (FQN) using a JSON Patch. This addition is aimed at enhancing the flexibility of the storage service update operations.
* [`openmetadata-service/src/main/java/org/openmetadata/service/resources/services/storage/StorageServiceResource.java`](diffhunk://#diff-8601b988c4425a59cc516ab2a4a23370b21dd01d440333675ebd1e11667c5bf0R396-R426): Added a new `PATCH` endpoint to update a storage service by FQN using JSON Patch. This includes the operation ID `patchStorageServiceByFQN`, a summary, description, external documentation link to the JSON Patch RFC, and consumes `application/json-patch+json`.
#
#
> MINOR: Add PATCH endpoint to update storage service by FQN

- ingestion/setup.py
Enhances Playwright plugin to add dbt
#
#
> MINOR: Add dbt plugin to Playwright dependencies

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProvider.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProviderContext.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/IncidentManagerPageHeader/IncidentManagerPageHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/IncidentManagerPageHeader/IncidentManagerPageHeader.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseStatus/TestCaseIncidentManagerStatus.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseStatus/TestCaseIncidentManagerStatus.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCaseStatusModal/TestCaseStatusModal.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/TestCaseStatusModal/TestCaseStatusModal.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Entity/Task/TaskTab/TaskTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/Task/TaskTab/TaskTabNew.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/IncidentManager/IncidentManager.component.tsx
Remove: user list api from activityFeedProvider without impacting current behaviour
https://github.com/user-attachments/assets/af011fdf-87bc-4979-97c4-4521da817e01
#
#
> Remove: user list api from activityFeedProvider without impacting current behaviour

- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
- I worked on fixing glossary column shifting on some assertion
#
#
> MINOR: fix glossary column shifting on some assertion

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/activity-feed-tab.less
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/assets-tabs.less
- openmetadata-ui/src/main/resources/ui/src/components/common/FeedsFilterPopover/FeedsFilterPopover.component.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
Updated the task filter icon in Task tab of Activity Feed and Assets and Following Tab  of User Profile Page
Original
Updated
#
#
> Minor : Update task filter icon 

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/openlineage/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/openlineage/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/spline/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/spline/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/stitch/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/stitch/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/wherescape/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/wherescape/troubleshooting.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/openlineage/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/openlineage/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/spline/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/spline/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/stitch/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/stitch/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/wherescape/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/wherescape/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on Troubleshoot Section Addition in Pipeline Completed.
#
#
> Docs: Troubleshoot Section Addition in Pipeline Completed

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/airbyte/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/airbyte/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/airflow/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/dagster/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/dagster/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/databricks-pipeline/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/databricks-pipeline/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/datafactory/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/datafactory/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/dbtcloud/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/dbtcloud/troubleshooting.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/airbyte/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/airbyte/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/airflow/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dagster/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dagster/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/databricks-pipeline/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/databricks-pipeline/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/datafactory/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/datafactory/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dbtcloud/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/dbtcloud/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on Troubleshoot Section Addition in Pipeline till DBT Cloud.
#
#
> Docs: Troubleshoot Section Addition in Pipeline till DBT Cloud

- openmetadata-ui/src/main/resources/ui/playwright/constant/service.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ServiceBaseClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/serviceIngestion.ts
- Added retry mechanism with exponential backoff for API requests
- Implemented consecutive error tracking (max 3 errors) to prevent infinite loops
- Added proper error handling for network requests
- Fixed import formatting issues
- Added `makeRequest` helper with 3 retry attempts and exponential backoff
- Added error counter to track consecutive failures
- Improved error handling in polling mechanism
- Fixed linter errors in import statements
- More reliable test execution
- Better handling of network issues
- Clearer error messages for debugging
> Refactor ServiceBaseClass: Implement exponential backoff for API requests and enhance error handling in pipeline status retrieval

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityExportModalProvider/EntityExportModalProvider.component.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Export.constants.ts
- added new export type PDF.
- Fix the fileName in case user change for PNG and other.
#
#
> Minor: added new export type and fileName fix on download

- openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx
https://github.com/user-attachments/assets/73e054ac-6873-495e-96f9-a64b50496a9b
#
#
> minor(ui) - Update Test connection modal to cancel the message when modal closes

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Bot/BotListV1/BotListV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable/IngestionListTable.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionListTable/IngestionStatusCount/IngestionStatusCount.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/IngestionPipelineList/IngestionPipelineList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/teams.less
- openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableList/DomainSelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableTree/DomainSelectableTree.interface.ts
- openmetadata-ui/src/main/resources/ui/src/constants/constants.ts
https://github.com/user-attachments/assets/e69a831d-8083-4277-9b95-bce57405e8d1
https://github.com/user-attachments/assets/b3af13a8-3d9e-4d95-ab2c-14c68d1a3165
https://github.com/user-attachments/assets/77b79f13-86de-42ea-9f09-3c99de297df5
https://github.com/user-attachments/assets/ac140c21-41ba-477e-b037-f33490153d7b
> Fixed : Members page and Minor UI bugs

- openmetadata-docs/content/v1.6.x/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/bigquery/yaml.md
Fixes https://github.com/open-metadata/OpenMetadata/issues/20502
I added an additional row to the permissions list for BigQuery. Incremental metadata collection doesn't work without this additional permissions.
I verified this by creating a custom role in GCP that only has the listed permissions. When I add the missing permission, metadata ingestion worked.
#
#
> Fixes 20502: Improve BigQuery docs with missing permissions

- ingestion/src/metadata/examples/workflows/rest.yaml
- ingestion/src/metadata/ingestion/source/api/rest/connection.py
- ingestion/src/metadata/ingestion/source/api/rest/metadata.py
- ingestion/src/metadata/ingestion/source/api/rest/models.py
- ingestion/src/metadata/utils/filters.py
- ingestion/tests/unit/topology/api/test_rest.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/api/restConnection.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/api/restConnection.ts
Fix #20546 
Fix #20348 
I worked on REST connector enhancements, filters support.
#
#
> issue-20546: REST connector enhancements

- ingestion/src/metadata/ingestion/lineage/parser.py
- ingestion/src/metadata/ingestion/ometa/mixins/lineage_mixin.py
- ingestion/src/metadata/ingestion/source/database/lineage_source.py
- ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
> MINOR: Improve threading for lineage

- openmetadata-ui/src/main/resources/ui/src/components/common/NoOwner/NoOwnerFound.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/OwnerLabel/OwnerLabel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/OwnerLabel/owner-label.less
> Minor: Fixed No owner text color

- openmetadata-service/src/main/java/org/openmetadata/service/config/S3Configuration.java
> Added prefix and SSE in S3

- openmetadata-ui/src/main/resources/ui/src/pages/DataQuality/DataQualityClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/pages/DataQuality/DataQualityPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataQuality/DataQualityPage.tsx
it is supporting the PR of the export DQ dashboard as pdf
#
#
> Feat: supporting PR for export dashboard

- openmetadata-ui/src/main/resources/ui/src/components/ServiceInsights/PlatformInsightsWidget/PlatformInsightsWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts
- I worked on added option for extended menu item in platform insight service
#
#
> MINOR: added option for extended menu item in platform insight service

- .github/workflows/py-checkstyle.yml
> MINOR: Fix Py-CheckStyle Workflow

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
I worked on Connectors Menu Error Fix
#
#
> Docs: Connectors Menu Error Fix

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
Fixes [20683](https://github.com/open-metadata/OpenMetadata/issues/20683)
#
#
> [Fix-20683] Indexing Issues due  incrementalChangeDescription

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> Update what's new content for 1.6.8

- openmetadata-service/src/main/java/org/openmetadata/service/resources/EntityResource.java
> chore: Add Logs for import export

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityExportModalProvider/EntityExportModalProvider.interface.ts
feat(ui): add PDF layout configuration and dimensions interfaces
- Introduced PDFLayoutConfig and PDFDimensions interfaces to support PDF export functionality.
- Updated ExportData type to include exportConfig for PDF layout settings.
#
#
> feat(ui): add PDF layout configuration and dimensions interfaces

- openmetadata-service/src/main/java/org/openmetadata/service/config/AzureConfiguration.java
> Default credentials, prefix path in Azure

- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v140/MigrationUtil.java
> [Minor] - Add Check for Null destinations

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/data-asset-header.less
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ko-kr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
> Minor: fixed copy tooltip || source url button

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppSchedule/AppSchedule.component.tsx
- openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
> Minor: Removed Divider from table

- ingestion/setup.py
> chore: more linient pinning for python neo4j

- openmetadata-docs/content/partials/v1.6/releases/1.6.7.md
- openmetadata-docs/content/partials/v1.6/releases/latest.md
- openmetadata-docs/content/partials/v1.7/releases/1.6.7.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/releases/releases/index.md
I worked on 1.6.8 Release Updation.
#
#
> Docs: 1.6.8 Release Updation

- openmetadata-service/src/main/java/org/openmetadata/service/security/AuthenticationCodeFlowHandler.java
Updated code to handle null refresh token
#
#
> [Fix-19741] Azure SSO callback getRefreshToken null 

- conf/openmetadata.yaml
- docker/development/docker-compose-gcp.yml
- docker/development/docker-compose-postgres.yml
- docker/development/docker-compose.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- openmetadata-service/src/main/java/org/openmetadata/service/security/AuthenticationCodeFlowHandler.java
- openmetadata-spec/src/main/resources/json/schema/security/client/oidcClientConfig.json
- openmetadata-ui/src/main/resources/ui/src/generated/security/client/oidcClientConfig.ts
OIDC: Allow max_age to be optional 
#
#
> [Fix-20125] OIDC: Allow max_age to be optional

- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/athena/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/clickhouse/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mssql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/oracle/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/redshift/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/snowflake/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/unity-catalog/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/ingestion/workflows/reverse-metadata.md
- Add connector / operation / entity level documentation
- Added Custom SQL examples.
- Added documentation for Custom SQL.
#
#
> MINOR: documentation improvements for Reverse Metadata

- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/athena/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/clickhouse/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mssql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mysql/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/oracle/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/redshift/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/snowflake/index.md
> MINOR: Reverse Metadata Custom SQL documentation

- openmetadata-ui/src/main/resources/ui/src/components/SearchSettings/GlobalSettingsItem/global-settings-item.less
- openmetadata-ui/src/main/resources/ui/src/utils/CSV/CSVUtilsClassBase.tsx
- I worked on fixing the tag selector overflow issue from cell.
- Issue was the open CSS written for the setting page, where effecting here. When a person visit setting and then the bulk edit page. Since the CSS get loaded from the setting page. which was seen in the Bulk Edit one. 
Issue : 
https://github.com/user-attachments/assets/d602dd87-e45f-43eb-8006-c4b3be292834
Resolved : 
https://github.com/user-attachments/assets/84469fe4-9410-4a95-8955-4c7c06c7ae73
#
#
> MINOR: fix the tag selector overflow issue from cell

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UserProfilePersona/UserProfilePersona.component.tsx
This PR fixes following issue for default persona update in User Profile Page
The Default persona was not getting updated properly in some cases due to not having display name . There was a check added for displaying the default persona in the chip based on whether or not we have the display name . 
Issue:-
https://github.com/user-attachments/assets/d6c5970e-84ac-4698-a420-79a652a16e97
Fix:-
Have added proper checks for fullyQualified name and name before displaying the default persona
https://github.com/user-attachments/assets/016ef483-84fb-447d-b7e7-741d77ab3a45
#
#
> Fix: minor issue in default persona update

- .github/workflows/airflow-apis-tests.yml
- .github/workflows/py-cli-e2e-tests.yml
- .github/workflows/python-packages-publish.yml
> MINOR: Fix Python Workflows

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java
Fixes Unnecessary password encryption in case of empty password
#
#
> Fix Empty Password Settings

- openmetadata-docs/content/v1.6.x/deployment/azure-auth.md
- openmetadata-docs/content/v1.6.x/deployment/iam-auth.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/azure-auth.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/iam-auth.md
I worked on Hyper Link Insertion
#
#
> Docs: Hyper Link Insertion

- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-insights/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-insights/service-insights.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on Service Insights Doc Updation.
#
#
> Docs: Service Insights Doc Updation

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.test.tsx
Fix DataAssetsHeader component logic and add tests for data quality lineage conditions
This pull request includes changes to the `DataAssetsHeader` component in the `openmetadata-ui` project to improve the handling of data quality alerts and enhance test coverage. The most important changes include setting default values for props, modifying conditional logic, and adding new test cases.
Changes to `DataAssetsHeader` component:
* [`openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx`](diffhunk://#diff-b7f1b6e45ff783869f0d101112cf693b22b496a68f706a22c2c3c45166f19034L199-R199): Set `isDqAlertSupported` to `false` by default to ensure a default value is always provided.
* [`openmetadata-ui/src/main/resources/ui/src/components/DataAsse …
> Fix DataAssetsHeader component logic and add tests for data quality lineage conditions

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardV2/FeedCardBody/OwnerFeed/OwnersFeed.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/activity-feed-tab.less
Issue : 
- For the Owner feed which is a Team we were making API call for the user to search the team profile. Which was wrong
Fix: 
- Have added a check fro the Team and show the appropriate component to render team icon and name.
Issue : 
Fix : 
#
#
> MINOR: fix the team profile call being made in activity feed

- openmetadata-ui/src/main/resources/ui/src/pages/APICollectionPage/APICollectionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtilClassBase.ts
- supported entityName in arguments of extraManageItems in entityClass
#
#
> MINOR: supported entityName in arguments of extraManageItems in entityClass

- .github/workflows/docker-openmetadata-ingestion.yml
Fixes #20703
build the ingestion image with fewer dependencies. this should be part of our usual release process
#
#
> RELEASE - Add openmetadata/ingestion-slim

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/SuggestionsResourceTest.java
> FIX #19919 - Traverse children columns when accepting suggestions

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TeamRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/domains/DataProductResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/domains/DomainResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/TeamResource.java
- Apis allowed bypassing any user to update teams in a user, becuase there were authoirization checks missing
- Add EDIT_ALL to bulkAsset edition as well
#
#
> Missing Permission on Adding Users to team

- openmetadata-service/src/main/java/org/openmetadata/csv/EntityCsv.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/AbstractNativeApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/ApplicationHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/NativeApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/autoPilot/AutoPilotApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/createAndRunIngestionPipeline/CreateIngestionPipelineImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/QueryRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TypeRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v170/MigrationUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/EntityResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/dqtests/TestCaseResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/connections/TestConnectionDefinitionResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/metadata/MetadataServiceResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/UserResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/types/TypeResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/NoopAuthorizer.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/auth/BasicAuthenticator.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/AppMarketPlaceUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/UserUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/apps/AppsResourceTest.java
> [Fix-20765] Issue in update() method

- openmetadata-service/src/main/java/org/openmetadata/service/resources/policies/PolicyResource.java
This will allow users with EDIT permissions to validate conditions
#
#
> Add Policy validation to users

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/EntitySummaryPanel.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataAssetSummaryPanel/DataAssetSummaryPanel.tsx
Fixes [#1426](https://github.com/open-metadata/openmetadata-collate/issues/1426)
- I worked on supporting domain information in EntityInfoPanel
#
#
> #1426: supported domain information in EntityInfoPanel

- openmetadata-spec/src/main/resources/json/schema/type/basic.json
> [Minor] : Fix #19845 Number type custom properties being treated as integer

- openmetadata-ui/src/main/resources/ui/playwright/utils/lineage.ts
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityExportModalProvider/EntityExportModalProvider.component.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Export.constants.ts
- I worked on adding beta tag for png and pdf export
#
#
> MINOR: added beta tag for png and pdf export

- openmetadata-ui/src/main/resources/ui/src/components/APIEndpoint/APIEndpointSchema/APIEndpointSchema.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Pipeline/Execution/Execution.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Pipeline/PipelineTaskTab/PipelineTaskTab.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Topic/TopicSchema/TopicSchema.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/ListView/ListView.component.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/components/radio.less
- openmetadata-ui/src/main/resources/ui/webpack.config.dev.js
Before:
After:
https://github.com/user-attachments/assets/437d8aba-48ac-4d1f-82be-5375a5f3a84e
#
> Minor:Restyled button group

- openmetadata-docs/content/v1.6.x/deployment/security/azure/kubernetes.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/deployment/security/azure/kubernetes.md
I worked on oidcConfiguration.enabled Addition.
#
#
> Docs: oidcConfiguration.enabled Addition

- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v170/MigrationUtil.java
> MINOR: Fix PII Column Bar Chart

- openmetadata-docs/content/v1.6.x/connectors/pipeline/glue-pipeline/index.md
- openmetadata-docs/content/v1.6.x/connectors/pipeline/glue-pipeline/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/glue-pipeline/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/pipeline/glue-pipeline/yaml.md
I worked on Glue Pipeline Feature Updation.
#
#
> Docs: Glue Pipeline Feature Updation

- openmetadata-ui/src/main/resources/ui/playwright/utils/importUtils.ts
- openmetadata-ui/src/main/resources/ui/src/components/Modals/ModalWithCustomProperty/ModalWithCustomPropertyEditor.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/CustomPropertyTable/CustomPropertyTable.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/CSV/CSVUtilsClassBase.tsx
- I worked on parsing error in case of special character in tag for BulkEdit/Import case.
- Custom Property in Extension was not working
Issue : 
https://github.com/user-attachments/assets/6b07e46f-c68e-4d36-83b0-5fad27edda8e
https://github.com/user-attachments/assets/f3d010cd-654d-4754-982d-b45c964a472a
Fix : 
https://github.com/user-attachments/assets/25952f84-d1de-471f-bef7-4acd31fe5f06
https://github.com/user-attachments/assets/f9a73bb9-f69c-4df8-942e-bacfcdd545b6
#
#
> FIX: parsing error in case of special character in tag for BulkEdit/Import case

- openmetadata-service/src/main/java/org/openmetadata/service/resources/teams/TeamResource.java
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamDetailsV1.tsx
Use Subset of Permissions for add delete Users in teams 
#
#
> Use Subset of Permissions for add delete Users in teams 

- openmetadata-ui/src/main/resources/ui/src/components/Container/ContainerDataModel/ContainerDataModel.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/EditTestCaseModal.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/CustomProperty/CustomPropertyTable.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamHierarchy.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamImportResult/TeamImportResult.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/UserImportResult/UserImportResult.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Topic/TopicSchema/TopicSchema.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Table/Table.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataQuality/DataQualityProvider.test.tsx
- I worked on reverted table fixed header changes
https://github.com/user-attachments/assets/b9e7d9f3-b812-480f-ae0e-5f16ce19f902
#
#
> reverted table fixed header changes

- ingestion/src/metadata/ingestion/source/messaging/kinesis/metadata.py
This PR fixes a bug in the Kinesis messaging source where the `Topic` class was incorrectly imported from `metadata.generated.schema.type.schema` instead of the correct entity
definition path `metadata.generated.schema.entity.data.topic`.
**Problem:**
The `yield_topic_sample_data` method used the `type.schema.Topic` definition when calling `fqn.build` and `metadata.get_by_name`. These functions expect the main entity
class.
**Fix:**
Changed the import statement to use `metadata.generated.schema.entity.data.topic.Topic`.
#
#
> fix(ingestion): Correct Topic import in Kinesis source

- ingestion/tests/integration/ometa/test_ometa_patch.py
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
If we have an entity with inherited owners and PATCH any other property, the owners get applied directly to the entity as a side effect
#
#
> FIX CL-#1427 - PATCH applies inherited owners

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/ServiceConnectionDetails/ServiceConnectionDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/interface/service.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
Updated edit form to fetch ingestion runner
#
#
> Minor updates for edit config page

- openmetadata-ui/src/main/resources/ui/playwright/support/entity/TableClass.ts
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableDescription/TableDescription.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLink.ts
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
- I worked on fixing the suggestion not visible for nested columns
https://github.com/user-attachments/assets/f4edeca4-1919-45bb-b391-4c9f789648f7
https://github.com/user-attachments/assets/d60302b0-61d0-4027-9b49-d0db5feb4a01
#
#
> fix the suggestion not visible for nested columns

- ingestion/src/metadata/ingestion/source/messaging/kinesis/metadata.py
> MINOR - Fix py checkstyle

- openmetadata-spec/src/main/resources/json/schema/metadataIngestion/reverseIngestionPipeline.json
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/reverseIngestionPipeline.ts
> MINOR - Add ingestion runner for reverse metadata

- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ko-kr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/utils/Export/ExportUtils.ts
- I worked beautify png image export error in case of size limit
#
#
> MINOR: beautify png image export error in case of size limit

- ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
Fix #20470  : Dashboard OverrideMetadata
#
#
> Fix : Dashboard OverrideMetadata

- openmetadata-docs/content/partials/v1.6/connectors/database/partitioned-tables.md
- openmetadata-docs/content/partials/v1.7/connectors/database/partitioned-tables.md
- openmetadata-docs/content/v1.6.x/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/bigquery/yaml.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/bigquery/yaml.md
I worked on BigQuery Partial Doc Updation.
#
#
> Docs: BigQuery Partial Doc Updation

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/TaskFeedCard/TaskFeedCard.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/TaskFeedCard/TaskFeedCardNew.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/RemainingOwner/OwnerReveal.tsx
- I worked on fixing the task owner alignment issue due to padding, with the count avatar.
- Also have reduce the font size of count to `-4px `. Upto 40% of the container
Issue :  
Fixed : 
#
#
> MINOR: fix the task owner alignment issue

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermModal/GlossaryTermModal.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryV1.component.tsx
> fix glossary duplicates

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on Connectors Order Connection in Menu.
#
#
> Docs: Connectors Order Connection in Menu

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/createAndRunIngestionPipeline/CreateIngestionPipelineImpl.java
Fixes the ReRun on AutoPilot by setting the OpenMetadataConnection properly
#
#
> MINOR: Fix ReRun by actually setting the OpenMetadataConnection properly

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
> MINOR - Fix NPE for empty topics in lineage

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- Order deletion so that in transaction the rows and not deadlocked 
#
#
> Order deletion by tagFQN

- ingestion/src/metadata/ingestion/models/custom_pydantic.py
> MINOR: Fix pydantic warnings in ingestion

- openmetadata-docs/content/partials/v1.6/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.7/connectors/database/connectors-list.md
I worked on Connectors List Updation.
#
#
> Docs: Connectors List Updation

- ingestion/src/metadata/ingestion/source/database/bigquery/metadata.py
- ingestion/src/metadata/ingestion/source/database/clickhouse/metadata.py
- ingestion/src/metadata/ingestion/source/database/common_db_source.py
- ingestion/src/metadata/ingestion/source/database/hive/metadata.py
- ingestion/src/metadata/ingestion/source/database/oracle/metadata.py
- ingestion/src/metadata/ingestion/source/database/oracle/utils.py
- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
- ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
- ingestion/src/metadata/ingestion/source/database/snowflake/utils.py
- ingestion/src/metadata/ingestion/source/database/unitycatalog/metadata.py
- ingestion/src/metadata/utils/sqlalchemy_utils.py
- ingestion/tests/integration/postgres/test_lineage.py
> MINOR: Always Include DDL for Views

- ingestion/src/metadata/ingestion/lineage/parser.py
> MINOR: Fix 'lr_sqlparser' referenced before assignment

- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/QueryBuilderWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Form/JSONSchema/JsonSchemaWidgets/QueryBuilderWidget/query-builder-widget.less
- openmetadata-ui/src/main/resources/ui/src/utils/QueryBuilderUtils.tsx
Before:
https://github.com/user-attachments/assets/cb9ed268-621b-41d5-882d-f06968760358
After:
https://github.com/user-attachments/assets/fd66b507-da01-4571-b11b-a391795327c8
#
#
> Made Fields immutable for Applications

- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
I worked on updating the playwright workflow for PRs to omit the tests marked with tag `nighlyOnly`. 
#
#
> Update the playwright workflow for the PRs to omit the nightly only tests

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
```
RROR [2025-04-15 10:22:30,170] [dw-588 - PUT /api/v1/suggestions/accept-all?userId=f1c17d49-0459-45ad-bbb3-6d701e3be990&entityFQN=snowflake.CUSTOMERS.JAFFLE_SHOP.STG_PAYMENTS&suggestionType=SuggestDescription] o.o.s.r.f.SuggestionsResource - Got exception: [NullPointerException] / message [Cannot invoke "String.equals(Object)" because the return value of "org.openmetadata.schema.entity.data.Table.getSchemaDefinition()" is null] / related resource location: [org.openmetadata.service.resources.feeds.SuggestionsResource.acceptAllSuggestions](SuggestionsResource.java:301)
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.openmetadata.schema.entity.data.Table.getSchemaDefinition()" is null
at …
```
> MINOR - Fix NPE for tables without schema definition

- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/BigQuery.md
I have made the BigQuery project ID documentation clearer for scenarios involving multiple projects.
#
#
> Minor(doc): Bigquery Documentation

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/FeaturesCarousel.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/FeaturesCarousel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
- openmetadata-ui/src/main/resources/ui/src/constants/Login.constants.ts
- openmetadata-ui/src/main/resources/ui/src/constants/LoginClassBase.ts
> chore(ui): fix what's new features with collate flag

- bootstrap/sql/migrations/native/1.5.7/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.5.7/postgres/postDataMigrationSQLScript.sql
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v157/MigrationUtil.java
> MINOR: fix duplicate param key insertion

- openmetadata-ui/src/main/resources/ui/src/pages/EditConnectionFormPage/EditConnectionFormPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/EditConnectionFormPage/EditConnectionFormPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts
> Updates for edit service related to runner

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
Fixes flaky test 'Create and Assign Task with Suggestions'
#
#
> Minor : fix activity feed playwright failure

- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
> Remove Deletion from loadDefaultApps

- openmetadata-ui/src/main/resources/ui/src/utils/TagsUtils.tsx
- I worked on ... because ...
Issue : 
https://github.com/user-attachments/assets/e0356af4-cb86-4e64-bcb8-e08a688ce8ad
Fixed : 
https://github.com/user-attachments/assets/0477c6ae-49ec-4715-93a8-e6c6e497c954
#
#
> MINOR: fix the glossary tag breaking in bulk edit and import

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> Fix whats new messaging

- ingestion/setup.py
> MINOR: bigquery lib fix for sample data

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/classification/Auto Classification/auto-pii-tagging.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/classification/Auto Classification/external-workflow.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/classification/Auto Classification/index.md
- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/classification/Auto Classification/workflow.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-governance/classification/Auto Classification/auto-pii-tagging.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-governance/classification/Auto Classification/external-workflow.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-governance/classification/Auto Classification/index.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/how-to-guides/data-governance/classification/Auto Classification/workflow.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/menu.md
I worked on Auto Change to Auto Classification.
#
#
> Docs: Auto Change to Auto Classification

- openmetadata-service/src/main/java/org/openmetadata/service/config/AzureConfiguration.java
> Variable name changed for prefix path

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/QueryRepository.java
Remove QUery Cost Record on query removal
#
#
> Cleanup Query Record

- bootstrap/sql/migrations/native/1.7.0/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.7.0/postgres/schemaChanges.sql
> Add cleanup apps_extension_time_series

- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/pyproject.toml
- openmetadata-airflow-apis/pyproject.toml
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-shaded-deps/elasticsearch-dep/pom.xml
- openmetadata-shaded-deps/opensearch-dep/pom.xml
- openmetadata-shaded-deps/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
- scripts/update_version.py
> feat: Bump Versions to 1.7.0-SNAPSHOT on Main Branch

- openmetadata-ui/src/main/resources/ui/playwright/constant/customizeDetail.ts
- openmetadata-ui/src/main/resources/ui/src/components/Customization/CustomizeTabWidget/CustomizeTabWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericProvider/GenericProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Table.constants.ts
- openmetadata-ui/src/main/resources/ui/src/pages/CustomizablePage/CustomizeStore.ts
- openmetadata-ui/src/main/resources/ui/src/utils/CustomizableLandingPageUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/CustomizePage/CustomizePageUtils.ts
- openmetadata-ui/src/main/resources/ui/src/utils/GenericWidget/GenericWidgetUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableClassBase.ts
Issue: Upon removing any widget it blanks the left side bar, refer image:
Fix: 
https://github.com/user-attachments/assets/69613aab-a9d5-4167-a601-3ca975a8551b
#
#
> fix(ui): persona for remove widget

- openmetadata-ui/src/main/resources/ui/src/components/Domain/SubDomainsTable/SubDomainsTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/SelectableList/SelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.interface.ts
- openmetadata-ui/src/main/resources/ui/src/context/WebSocketProvider/WebSocketProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedureTab.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/CSV/CSVUtilsClassBase.tsx
- fix the team selected, is not shown in modal.
- fix the repeated user seen in list for the selected owner.
- fix the owner modal not closing on cancel button, from user list.
- fix the domain not selected, and being repeated in the list.
- fix the domain and storeProcedure table spacing
- Have fix some sonar issue
Issue :  
https://github.com/user-attachments/assets/c9a7096a-5f66-4e0f-8c28-3ebf5ec6e059
https://github.com/user-attachments/assets/0ca616d5-a4c8-4916-becc-4d3a3ffc28c6
Fixed : 
https://github.com/user-attachments/assets/4b77373e-18f8-45ab-a8a1-bf3f7fc40913
https://github.com/user-attachments/assets/a9dfb850-081f-4f7d-bc5a-dbbbba587b84
#
#
> fix the owner listing and domain selector in bulk action

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/StoredProcedureRepository.java
> MINOR: NPE handling for SP lineage

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/ChartWidgets/DataStatisticWidget/DataStatisticWidget.component.tsx
> fix: UI styling in overview tab of Data quality

- openmetadata-docs/content/v1.6.x/connectors/database/mongodb/troubleshooting.md
- openmetadata-docs/content/v1.7.x-SNAPSHOT/connectors/database/mongodb/troubleshooting.md
I worked on Mongodb integration Addition.
#
#
> Docs: Mongodb integration Addition

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/AddDataQualityTestV1.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/ParameterForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/ResizablePanels/resizable-panels.less
- openmetadata-ui/src/main/resources/ui/src/pages/TestSuiteIngestionPage/TestSuiteIngestionPage.tsx
> Revert the test case form css

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppImpl.java
> MINOR: Handle run internal app when app is running

- openmetadata-spec/src/main/resources/json/schema/email/smtpSettings.json
- openmetadata-ui/src/main/resources/ui/src/generated/email/smtpSettings.ts
> Fix Smtp Configuration

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/IncidentManagerPageHeader/IncidentManagerPageHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/IncidentManagerPageHeader/IncidentManagerPageHeader.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/NoOwner/NoOwnerFound.tsx
- I worked on fixing the reviewer placeholder container multiple no
Issue : 
Resoled: 
#
#
> MINOR: fix the reviewer placeholder container multiple no

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/tags/TagLabelUtil.java
Fix Failures due to unpopulated terms and tags 
#
#
> Fix Glossary Terms failure

- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/v1.7.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.7.x/sdk/python/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/sdk/python/index.md
I worked on 1.7 version Updation in docs
#
#
> Docs: 1.7 Updation

- .github/workflows/monitor-slack-link.yml
- scripts/slack-link-monitor.py
This pull request includes significant updates to the Slack link monitoring workflow and the associated Python script. The changes enhance the workflow's reliability, improve logging, and ensure better error handling.
* [`.github/workflows/monitor-slack-link.yml`](diffhunk://#diff-42927b63832fca64fd279a1edfc41806554ac09508eefc99ac00681100670867R15-R62): Added comments for clarity, least privilege permissions, and a fail-fast strategy for matrix jobs. Updated steps to include caching for Python dependencies and improved logging for the monitoring script.
* [`scripts/slack-link-monitor.py`](diffhunk://#diff-ae7c67bfcbcff69b5ea526bb7ca0fe6936dd72c9bc6fc63d44cdf1c1a8d28fc1R14-R84): Added logging configuration and helper functions for environment variables. Improved error handling and logging …
> MINOR: Enhance Slack Link Monitoring Workflow and Script

- .github/workflows/sync-docs-v1.yml
Updating the Docs Workflow
#
#
> Docs: Updating the Docs Workflow

- ingestion/src/metadata/ingestion/source/api/rest/metadata.py
> MINOR: REST minor fixes

- openmetadata-docs/content/partials/v1.7/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.7/connectors/ml-model/connectors-list.md
- openmetadata-docs/content/partials/v1.7/connectors/pipeline/connectors-list.md
- openmetadata-docs/content/partials/v1.7/connectors/search/connectors-list.md
- openmetadata-docs/content/partials/v1.8/connectors/database/connectors-list.md
- openmetadata-docs/content/partials/v1.8/connectors/ml-model/connectors-list.md
- openmetadata-docs/content/partials/v1.8/connectors/pipeline/connectors-list.md
- openmetadata-docs/content/partials/v1.8/connectors/search/connectors-list.md
I worked on BETA Version Correction of Connectors.
#
#
> Docs: BETA Version Correction

- openmetadata-docs/content/v1.6.x/how-to-guides/admin-guide/data-insights.md
- openmetadata-docs/content/v1.7.x/how-to-guides/admin-guide/data-insights.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/how-to-guides/admin-guide/data-insights.md
I worked on Image Name correction in data Insights.
#
#
> Docs: Image Name correction in data Insights

- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
- I worked on fixing disabling service insight pdf export when the tab is not insight tab
#
#
> MINOR: service insight pdf export fix

- openmetadata-docs/content/partials/v1.6/releases/1.6.9.md
- openmetadata-docs/content/partials/v1.7/releases/1.6.10.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/partials/v1.8/releases/1.6.10.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x/collate-menu.md
- openmetadata-docs/content/v1.7.x/menu.md
- openmetadata-docs/content/v1.7.x/releases/releases/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/releases/releases/index.md
I worked on Release 1.6.10 Updation in docs.
#
#
> Docs: Release 1.6.10 Updation

- openmetadata-docs/content/partials/v1.7/deployment/upgrade/upgrade-prerequisites.md
> DOCS - AWS OpenSearch settings 1.7 FIX

- openmetadata-docs/content/v1.7.x/applications/reverse-metadata.md
Add a placeholder page for the application docs. This page can be removed once https://github.com/open-metadata/openmetadata-collate/pull/1433 is deployed.
#
#
> docs: reverse metadata documentation fix

- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
I worked on 1.7 Release Section Updation.
#
#
> Docs: 1.7 Release Section Updation

- openmetadata-ui/src/main/resources/ui/src/utils/i18next/i18nextUtil.ts
- I worked on fixing the ui coverage test, failing due to same pair pre-exist
#
#
> fix the ui coverage test

- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
> Docs: Updating the release notes

- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/pyproject.toml
- openmetadata-airflow-apis/pyproject.toml
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-service/pom.xml
- openmetadata-shaded-deps/elasticsearch-dep/pom.xml
- openmetadata-shaded-deps/opensearch-dep/pom.xml
- openmetadata-shaded-deps/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
> feat: Bump Versions to 1.8.0-SNAPSHOT on Main Branch

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.7.x/collate-menu.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/collate-menu.md
I worked on Collate Menu Order Rearrangement.
#
#
> Docs: Collate Menu Order Rearrangement

- openmetadata-docs/content/v1.6.x/collate-menu.md
- openmetadata-docs/content/v1.7.x/collate-menu.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/collate-menu.md
I worked on Release Removal from Collate Menu.
#
#
> Docs: Release Removal from Collate Menu

- ingestion/tests/cli_e2e/test_cli_powerbi.py
> MINOR: pbi e2e fix

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomEdge.component.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomEdge.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomNodeV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/EntityLineage.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/LineageSearchSelect/LineageSearchSelect.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/NodeChildren/NodeChildren.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Lineage/Lineage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/Skeleton/CommonSkeletons/ControlElements/ControlElements.component.tsx
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.interface.tsx
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
> Lineage optimise

- openmetadata-ui/src/main/resources/ui/src/components/common/DomainLabel/domain-label.less
- openmetadata-ui/src/main/resources/ui/src/components/common/OwnerAvtar/OwnerAvatar.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/OwnerItem/OwnerItem.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/OwnerLabel/OwnerLabel.component.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
Worked on owner and domain component. 
- Fixed owner name being cut on overflow
- Removed popovercard for team
- Applied consistent styling between owner and domain
Before
After:
#
#
> Fix: Owner with long name is being cut || Removed API call for teams 

- openmetadata-docs/content/v1.6.x/deployment/backup-restore-metadata.md
- openmetadata-docs/content/v1.6.x/deployment/upgrade/index.md
- openmetadata-docs/content/v1.7.x/deployment/backup-restore-metadata.md
- openmetadata-docs/content/v1.7.x/deployment/upgrade/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/backup-restore-metadata.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/upgrade/index.md
> Docs: Updating the Backup docs

- openmetadata-docs/content/v1.6.x/deployment/security/azure/docker.md
- openmetadata-docs/content/v1.7.x/deployment/security/azure/docker.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/security/azure/docker.md
I worked on OIDC Variable Addition.
#
#
> Doc: OIDC Variable Addition

- openmetadata-docs/content/v1.7.x/deployment/security/custom-oidc/kubernetes.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/security/custom-oidc/kubernetes.md
I worked on Removing ODIC Troubleshooting Section.
#
#
> Docs: Removing OIDC Troubleshooting Section

- openmetadata-ui/src/main/resources/ui/src/components/Auth/AuthProviders/AuthProvider.tsx
- I worked on showing error message on case self signup login error
#
#
> MINOR: show error message on case self signup login error

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/WorkflowHandler.java
> MINOR: Remove JobUnlock on startUp

- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainExpertsWidget/DomainExpertWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.component.tsx
Fixed Add experts font color and removed double padding from right box of data product page
Before :
After:
#
#
> minor(ui): domain page layout changes

- openmetadata-service/src/main/java/org/openmetadata/service/formatter/field/TestCaseResultFormatter.java
> Fixes #20567: Added display name and description in Testcase Alert emails

- openmetadata-docs/content/v1.7.x/deployment/security/okta/docker.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/security/okta/docker.md
fix the issue of omd docs on okta sso.
`previous screenshot:`
`After issue fix:`
#
#
> Fix docs okta sso docker issue.

- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
Fixed flaky ServiceEntity test
- Delete Service
#
#
> chore: fix flaky serviceEntity test

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/AssetsSelectionModal/asset-selection-model.style.less
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityHeaderTitle/EntityHeaderTitle.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/OwnerLabel/OwnerLabel.component.tsx
> Fix(ui): header truncate issue || owner Disalignment

- openmetadata-docs/content/v1.7.x/applications/index.md
- openmetadata-docs/content/v1.7.x/collate-menu.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/applications/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/collate-menu.md
update application menu structure and slug formatting in 1.7.x and v1.8.x-SNAPSHOT (#21003)
#
#
> MINOR: update application menu structure and slug formatting 

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> add whats new for 1.6.11

- openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/GlossaryVersionPage.spec.ts
Fixed flaky 'Glossary Term' test in Glossary Version page due to viewport scrolling issues.
The test was failing because the glossary reviewer diff element was positioned outside the viewport sometimes, causing element interaction failures. This happened because:
- The page wasn't properly scrolling to show the diff element
- Elements outside the viewport cannot be interacted with in Playwright tests sometimes.
- Added `scrollIntoViewIfNeeded()` to ensure the glossary reviewer diff element is visible in the viewport
- This ensures the element is properly scrolled into view before any interaction attempts
https://github.com/user-attachments/assets/ea0b5c58-6f42-480d-8448-7ddebe096ec6
#
#
> Fix : flaky glossary version page test failure

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppRunsHistory/AppRunsHistory.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/AppRunsHistory/AppRunsHistory.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/date-time/DateTimeUtils.ts
Fixes [#20527](https://github.com/open-metadata/OpenMetadata/issues/20527)
Original Formatting
Updated Formating
#
#
> Update formatting for duration in application configuration

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/AppRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
Add Api endpoint to reduce api endpoint size
#
#
> Added Api endpoint to list applications reference to reduce payload

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/insights/DataInsightsApp.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
- openmetadata-spec/src/main/resources/json/schema/entity/applications/configuration/internal/dataInsightsAppConfig.json
- openmetadata-spec/src/main/resources/json/schema/system/eventPublisherJob.json
- openmetadata-ui/src/main/resources/ui/src/generated/system/eventPublisherJob.ts
> Fixes #20920: validation for Search Index app and data insights app configuration

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/CollectionDAO.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
Fixes [<issue-number>](https://github.com/open-metadata/OpenMetadata/issues/20509)
#
#
> [Fix-20509] Database Service Hierarchy Cleanup

- openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertsRuleEvaluator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/SubscriptionUtil.java
- openmetadata-service/src/main/resources/json/data/EventSubResourceDescriptor.json
- Mention on task not working fixed
#
#
> Fixes #19774: Mention on task fixes

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/CustomEdge.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Lineage/Lineage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.interface.tsx
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ja-jp.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ko-kr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- openmetadata-ui/src/main/resources/ui/src/pages/PlatformLineage/PlatformLineage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
Enhance data quality lineage tracking by introducing dqHighlightedEdges state and updating related logic in CustomEdge component. Implement recursive function to retrieve all downstream edges from a node in the lineage graph.
https://github.com/user-attachments/assets/c5ba94da-525a-4586-ac04-08f4c7c67dba
- Change page title based on plaform selection
- Remove filters for platform lineage
https://github.com/user-attachments/assets/fe110294-f68b-46e5-97e7-4ead62ac5565
#
#
> enhancement: improve DQ failure lineage tracing

- openmetadata-ui/src/main/resources/ui/src/pages/EntityImport/BulkEntityImportPage/bulk-entity-import-page.less
- openmetadata-ui/src/main/resources/ui/src/utils/CSV/CSVUtilsClassBase.tsx
- I worked on fixing the select cell for tags and glossary in bulk action
Issue : 
Fix : 
https://github.com/user-attachments/assets/12af9f6b-1548-4fd1-88be-9ee0659278f4
#
#
> MINOR: fix the select cell for tags and glossary in bulk action

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/Ingestion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/Ingestion/ingestion.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
I worked on the OSS changes necessary for fetching the Collate AI Agents status
Required for: https://github.com/open-metadata/openmetadata-collate/pull/1517
#
#
> Minor(UI): OSS changes to pass the workflow start timestamp to collate AI agents widget

- ingestion/src/metadata/ingestion/source/database/postgres/metadata.py
- ingestion/src/metadata/ingestion/source/database/postgres/queries.py
- ingestion/src/metadata/ingestion/source/database/postgres/utils.py
Fix #20024: Fix get schema names logic for postgres
#
#
> Fix #20024: Fix get schema names logic for postgres

- openmetadata-docs/content/v1.6.x/deployment/secrets-manager/supported-implementations/azure-key-vault/index.md
- openmetadata-docs/content/v1.7.x/deployment/secrets-manager/supported-implementations/azure-key-vault/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/secrets-manager/supported-implementations/azure-key-vault/index.md
Fixes A typo in AD directory Role name for airflow pod
According to  https://learn.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli#azure-built-in-roles-for-key-vault-data-plane-operations
#
#
> Fixes #21023 : correct role name in azure key vault documentation

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationsProvider/ApplicationsProvider.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Applications/ApplicationsProvider/ApplicationsProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/applicationAPI.ts
> replace: application list api with `/installed` api endpoint

- openmetadata-docs/content/v1.6.x/connectors/pipeline/airflow/troubleshooting.md
- openmetadata-docs/content/v1.6.x/how-to-guides/admin-guide/roles-policies/authorization.md
- openmetadata-docs/content/v1.7.x/connectors/pipeline/airflow/troubleshooting.md
- openmetadata-docs/content/v1.7.x/how-to-guides/admin-guide/roles-policies/authorization.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/pipeline/airflow/troubleshooting.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/how-to-guides/admin-guide/roles-policies/authorization.md
I worked on Link Checker Error Fix.
#
#
> Doc: Link Checker Error Fix

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
> MINOR: pbi dashboard sourceurl fix

- ingestion/src/metadata/ingestion/models/patch_request.py
- ingestion/tests/unit/metadata/ingestion/models/test_table_constraints.py
Fix #20902: Fix duplicate constraints error
#
#
> Fix #20902: Fix duplicate constraints error

- openmetadata-docs/content/v1.6.x/connectors/ingestion/lineage/spark-lineage.md
- openmetadata-docs/content/v1.7.x/connectors/ingestion/lineage/spark-lineage.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/ingestion/lineage/spark-lineage.md
I worked on Index Addition in Spark Lineage.
#
#
> Doc: Index Addition in Spark Lineage

- bootstrap/sql/migrations/native/1.7.1/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.7.1/postgres/schemaChanges.sql
Add operator parameter to test_definition Custom SQL queries in MySQL and Postgres
Fixes #20913
#
#
> Fixes #20913 - Migrations - add operator parameter to test_definition

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Metric.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/metric.ts
I worked on fixing flaky matrics test cases.  
1. Made sure that api are loaded before searching for data, 
2. All the entries should be on a single page of a table (no pagination ). 
3. Made sure that after deleting matrics, the message should always match the test.
#
#
> Fix(Ui): fixed flaky metrics tests

- openmetadata-docs/content/partials/v1.7/connectors/yaml/auto-classification.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/data-profiler.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/query-usage.md
- openmetadata-docs/content/partials/v1.7/deployment/faqs.md
- openmetadata-docs/content/partials/v1.7/deployment/redeploy.md
- openmetadata-docs/content/partials/v1.7/deployment/upgrade/post-upgrade-steps.md
- openmetadata-docs/content/partials/v1.8/connectors/search/configure-ingestion.md
- openmetadata-docs/content/partials/v1.8/connectors/storage/configure-ingestion.md
- openmetadata-docs/content/partials/v1.8/connectors/yaml/auto-classification.md
- openmetadata-docs/content/partials/v1.8/connectors/yaml/data-profiler.md
- openmetadata-docs/content/partials/v1.8/connectors/yaml/query-usage.md
- openmetadata-docs/content/partials/v1.8/deployment/faqs.md
- openmetadata-docs/content/partials/v1.8/deployment/redeploy.md
- openmetadata-docs/content/partials/v1.8/deployment/upgrade/post-upgrade-steps.md
Updating the v1.5 references in docs
#
#
> Docs: Updating the v1.5 references in docs

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
> MINOR: Fix unsupported Pipeline entity for lineage

- openmetadata-docs/content/v1.6.x/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.7.x/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/pipeline/airflow/index.md
I worked on 404 Link Correction.
#
#
> Doc: 404 Link Correction

- openmetadata-docs/content/v1.6.x/menu.md
- openmetadata-docs/content/v1.6.x/releases/releases/index.md
- openmetadata-docs/content/v1.6.x/roadmap/index.md
- openmetadata-docs/content/v1.7.x/menu.md
- openmetadata-docs/content/v1.7.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x/roadmap/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/roadmap/index.md
Removing roadmap page from the docs
#
#
> Docs: Removing roadmap page from the docs

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/IncidentManagerPageHeader/IncidentManagerPageHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/NoOwner/NoOwnerFound.tsx
before
after:
Fixes #[21082](https://github.com/open-metadata/OpenMetadata/issues/21082)
#
#
> Fixed (ui): owner label for incident manager

- conf/openmetadata.yaml
- conf/operations.yaml
- openmetadata-spec/src/main/resources/json/schema/configuration/openMetadataBaseUrlConfiguration.json
Fixes invalid url issue
https://github.com/open-metadata/OpenMetadata/issues/21016
#
#
> Add operations.yaml

- .github/workflows/mysql-nightly-e2e.yml
- .github/workflows/postgresql-nightly-e2e.yml
> feat(ci): run playwright over particular branch

- openmetadata-ui/src/main/resources/ui/playwright/utils/importUtils.ts
> PLAYWRIGHT: fix bulk import database flaky test

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/custom-node.less
- openmetadata-ui/src/main/resources/ui/src/components/Explore/EntitySummaryPanel/CommonEntitySummaryInfo/CommonEntitySummaryInfo.tsx
- fix the lineage column icon not visible in case of column contains child nodes.
- added the owner label in the entity summary panel, previously it was only value in case of owner.
Issue : 
Fix: 
#
#
> MINOR: fix lineage column icon and entity summary panel owner label not visible

- bootstrap/sql/migrations/native/1.8.0/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.8.0/postgres/schemaChanges.sql
- openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/AutoPilotApplication.json
added runtime.enabled: true to autopilot marketplace definition
#
#
> MINOR fix: autopilot marketplace runtime

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.test.tsx
Worked on Certifications  which are now made always visible irrespective of its value is present or not
#
Before:
After:
#
> Minor(ui):Made certification always visible

- .snyk
> Ignore _openmetadata_testutils from snyk

- openmetadata-docs/content/v1.6.x/deployment/bare-metal/index.md
- openmetadata-docs/content/v1.6.x/deployment/docker/index.md
- openmetadata-docs/content/v1.7.x/deployment/bare-metal/index.md
- openmetadata-docs/content/v1.7.x/deployment/docker/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/bare-metal/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/docker/index.md
I worked on Cluster Allias Configuration update.
#
#
> Doc: Cluster Allias Configuration update

- openmetadata-service/src/main/java/org/openmetadata/service/resources/databases/DatabaseResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/entity/data/database.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/data/database.ts
Continuing pr changes in https://github.com/open-metadata/OpenMetadata/pull/21017
#
#
> Support followers for Database

- openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomainForm/AddDomainForm.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/AddGlossaryTermForm/AddGlossaryTermForm.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/AsyncSelectList.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/TreeAsyncSelectList.tsx
- openmetadata-ui/src/main/resources/ui/src/interface/FormUtils.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/TagSuggestion.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/formUtils.tsx
Worked on the Tree Dropdown structure for the Glossary Terms inside below forms:
- Add Domain -> Glossary Terms
- Add Term -> Related Terms
https://github.com/user-attachments/assets/0479cad6-ba77-4d50-84d7-aa946ab3feba
#
#
> fix(ui): tree dropdown for glossary terms inside form

- ingestion/src/metadata/ingestion/source/database/oracle/queries.py
Fixes https://github.com/open-metadata/openmetadata-collate/issues/1552
#
#
> Fix #1552: Improve Fetch Oracle View Definition Query

- openmetadata-docs/content/v1.6.x/how-to-guides/data-quality-observability/quality/custom-tests.md
- openmetadata-docs/content/v1.7.x/how-to-guides/data-quality-observability/quality/custom-tests.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/how-to-guides/data-quality-observability/quality/custom-tests.md
I worked on Custom Test Case Correction.
#
#
> Doc: Custom Test Case Correction

- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
I worked on Collate Video Updation.
#
#
> Doc: Collate Video Updated

- openmetadata-ui/src/main/resources/ui/src/utils/HistoryUtils.ts
This pull request updates the `getBasePath` utility function in `HistoryUtils.ts` to include a conditional check for `window.BASE_PATH` against a template string `${basePath}`. This ensures the function returns an empty string if the condition is met.
Key change:
* [`openmetadata-ui/src/main/resources/ui/src/utils/HistoryUtils.ts`](diffhunk://#diff-ea821fde0c1c1cff461a6a50ac11ba88fb8d278f42d455a56be975a2a91f2854L17-R19): Modified the `getBasePath` function to include a conditional check for `window.BASE_PATH` against `${basePath}`, improving the logic for determining the base path.
#
#
> fix(ui): ignore basePath static value for dev mode

- openmetadata-service/src/main/java/org/openmetadata/service/resources/apps/AppResource.java
Since this is the flow when we install the apps via POST as well. Otherwise, we can end up installing an app that's not enabled, leading to further errors.
This impacts for example Collate AI, raising errors on the UI when we try to get the billing info eventhough the app is disabled
#
#
> FIX - Try to install app before initializing the entity

- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/BarMenu/BarMenu.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/EntityDescription/EntityAttachmentProvider/EntityAttachmentProvider.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/EntityDescription/EntityAttachmentProvider/EntityAttachmentProvider.tsx
issue: 
https://github.com/user-attachments/assets/29229859-9d40-48b6-aaf5-3d775dad523b
Fix:
https://github.com/user-attachments/assets/66b1418b-b0eb-4f88-86dd-c58de629249a
#
#
> Fix: Resolve multiple image insertion issues and ensure proper inline error messaging

- ingestion/src/metadata/ingestion/api/topology_runner.py
- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
> MINOR: Handle udf definition fetch exceptions

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkImport.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/InlineEdit/inline-edit.less
UI Fixes : 
-  Fix the Announcement card placement
- Fix the InLine component button size
Playwright Fix: 
- Bulk Import  - Table
- Entity.spec - Announcement
Issue : 
Resolved : 
#
#
> FIX: flaky test and ui issues

- openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
Added a dependency of defaultLayout to fetchDocument useEffect so as to update the layout when defaultLayout changes.
#
#
> Add dependency in fetchDocument useEffect

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/powerbi/models.py
- openmetadata-spec/src/main/resources/json/schema/entity/data/dashboardDataModel.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/data/dashboardDataModel.ts
> issue-19890: PBI dataflow support

- ingestion/src/metadata/ingestion/source/storage/s3/metadata.py
> issue-20074: s3 objects get paginated response

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCard/FeedCardBody/FeedCardBody.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/Shared/task-badge.less
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/EntityPageInfos/AnnouncementCard/AnnouncementCard.less
- openmetadata-ui/src/main/resources/ui/src/components/common/EntityPageInfos/AnnouncementCard/AnnouncementCard.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/MyDataPage/my-data.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
- I worked on fixing the Announcement card placement and colors.
- Fix the icon and text color in Recent Announcement
- Fix the overflowing of text from announcement card in Modal
Issue :   
Fix: 
#
#
> MINOR: fix the announcement card placement and minor styling

- openmetadata-docs/content/v1.6.x/connectors/dashboard/powerbi/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.7.x/connectors/dashboard/powerbi/index.md
- openmetadata-docs/content/v1.7.x/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/dashboard/powerbi/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/databricks/index.md
> docs: pbi, databricks docs fix

- openmetadata-docs/content/v1.6.x/connectors/messaging/kafka/troubleshooting.md
- openmetadata-docs/content/v1.7.x/connectors/messaging/kafka/troubleshooting.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/messaging/kafka/troubleshooting.md
I worked on schemaRegistryTopicSuffixName updation in Kafka troubleshooting.
#
#
> Doc: schemaRegistryTopicSuffixName updation

- openmetadata-docs/content/v1.6.x/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.7.x/connectors/pipeline/airflow/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/pipeline/airflow/index.md
I worked on GCS & MWAA Link Addition.
#
#
> Doc: GCS & MWAA Link Addition

- openmetadata-docs/content/v1.6.x/sdk/index.md
- openmetadata-docs/content/v1.7.x/sdk/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/sdk/index.md
Docs are currently hard-coded. They need to be automatically generated from swagger codegen.
Partially delivers https://github.com/open-metadata/OpenMetadata/issues/20559
#
#
> MINOR: docs: added openapi docs link

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/changeEvent/generic/GenericPublisher.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionMapper.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/CompiledRule.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/ExpressionValidator.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/SubscriptionUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/URLValidator.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/policies/PolicyResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/ExpressionValidatorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/PolicyEvaluatorTest.java
- pom.xml
> Fix snyk's reported vulnerabilities

- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
> fix(test): tags & glossary term failure

- openmetadata-ui/src/main/resources/ui/src/context/AirflowStatusProvider/AirflowStatusProvider.test.tsx
- openmetadata-ui/src/main/resources/ui/src/context/AirflowStatusProvider/AirflowStatusProvider.tsx
> fix(ui): authenticate pipeline status api call

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TypeRepository.java
Fixes an edge case in `postUpdateCustomPropertyConfig` where the enum cleanup background job was not triggered when all enum keys were removed.
#
#
> Minor : Fix enum cleanup not triggering when all enum keys are removed

- ingestion/tests/unit/topology/dashboard/test_superset.py
> MINOR: Disable Flaky superset tests

- ingestion/src/metadata/ingestion/ometa/mixins/es_mixin.py
- ingestion/src/metadata/ingestion/source/pipeline/airbyte/constants.py
- ingestion/src/metadata/ingestion/source/pipeline/airbyte/metadata.py
- ingestion/src/metadata/ingestion/source/pipeline/airbyte/utils.py
- ingestion/src/metadata/ingestion/source/pipeline/openlineage/models.py
- ingestion/src/metadata/ingestion/source/pipeline/pipeline_service.py
- ingestion/src/metadata/utils/fqn.py
- ingestion/tests/unit/topology/pipeline/test_airbyte.py
- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
Fixes #17433
This PR adds support of lineage extraction of airbyte pipelines for different database services. Currently, MySQL, Postgres, Mssql and MongoDB are supported.
#
#
> Fix airbyte pipeline lineage extraction

- ingestion/src/metadata/ingestion/source/database/athena/metadata.py
> MINOR: Add athena schema comment support

- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/ModelTab/ModelTab.component.tsx
I have worked on adding edit display name functionality for dashboard data models
https://github.com/user-attachments/assets/f0f8c294-8fa9-4a09-898d-71b29f1744ec
#
> Added(ui): edit display name for dashboard Data model

- openmetadata-ui/src/main/resources/ui/playwright.config.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/NotificationAlerts.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/ObservabilityAlerts.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/alert.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/observabilityAlert.ts
> Fix: Observablity alert flaky test

- ingestion/src/metadata/readers/dataframe/json.py
Fixes https://github.com/open-metadata/openmetadata-collate/issues/1550
#
#
> Fix #1550: Metadata ingestion errors from Azure Data Lake

- openmetadata-docs/content/v1.6.x/how-to-guides/data-discovery/bulk-upload.md
- openmetadata-docs/content/v1.7.x/applications/autopilot.md
- openmetadata-docs/content/v1.7.x/applications/reverse-metadata.md
- openmetadata-docs/content/v1.7.x/how-to-guides/data-discovery/bulk-upload.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/applications/autopilot.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/applications/reverse-metadata.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/how-to-guides/data-discovery/bulk-upload.md
I worked on YT Video Updation.
#
#
> Doc: YT Video Updation

- ingestion/src/metadata/data_quality/source/test_suite.py
- ingestion/src/metadata/workflow/profiler.py
Temporary fix to unblock ingestion until #21259 is handled.
#
#
> FIX - Ingestion workaround for Services with null secrets

- ingestion/src/metadata/utils/datalake/datalake_utils.py
Fixes https://github.com/open-metadata/openmetadata-collate/issues/1532
#
#
> Fix #1532: Fix Error ingesting using Datalake adls connector

- openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AdminProtectedRoute.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DataInsightPage/DataInsightPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/GlobalSettingPage/GlobalSettingPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServicesPage/ServicesPage.tsx
Worked on styles for permission placeholder for the pages.
#
#
> fix(ui): styles for permission placeholder 

- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/TaskFeedCard/TaskFeedCard.component.tsx
> Fix(ui) : Assignee alignment issue on task feed card for deleted user/team

- bootstrap/sql/migrations/native/1.7.1/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.7.1/postgres/schemaChanges.sql
- bootstrap/sql/migrations/native/1.8.0/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.8.0/postgres/schemaChanges.sql
> fix: move autopilot runtime migrations to 1.7.1

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkImport.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/importUtils.ts
> PLAYWRIGHT: fix the flaky test failure around bulk import

- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/GithubStarCard/github-star-card.style.less
- I worked on fixing the data asset header spacing in Metric entity
- fix the spacing between floating cards.
Issue : 
Fixed : 
#
#
> MINOR: fix the data asset header spacing in Metric entity

- openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/GlossaryVersionPage.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/ErrorWithPlaceholder/PermissionErrorPlaceholder.tsx
Worked on flaky test for Glossary Version Page.
#
#
> fix(test): flaky glossary version test

- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
> Fix : Flaky follower test 

- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/teams.less
- I worked on fixing the description box of team page
Issue : 
Fix : 
#
#
> MINOR: fix the description box of team page

- ingestion/src/metadata/ingestion/source/database/vertica/queries.py
Fix #20746: DB columns in Vertica
#
#
> Fix #20746: DB columns in Vertica

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/GlossaryRepository.java
> MINOR: Import glossary term tag bug fix

- openmetadata-ui/src/main/resources/ui/src/constants/Appearance.constants.ts
- openmetadata-ui/src/main/resources/ui/src/pages/AppearanceConfigSettingsPage/AppearanceConfigSettingsPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/AppearanceConfigSettingsPage/AppearanceConfigSettingsPage.tsx
- I worked on fixing the theme color for success and warning.
- Also removed the beta tag from the custom theme
Issue : 
Fixed : 
#
#
> MINOR: fix the success theme color and remove the beta tag custom theme

- ingestion/src/metadata/ingestion/source/database/snowflake/queries.py
- ingestion/src/metadata/ingestion/source/database/snowflake/utils.py
> MINOR: Snowflake View Definition Fallback

- openmetadata-ui/src/main/resources/ui/src/components/APIEndpoint/APIEndpointVersion/APIEndpointVersion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Container/ContainerVersion/ContainerVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DashboardVersion/DashboardVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModelVersion/DataModelVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/StoredProcedureVersion/StoredProcedureVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableVersion/TableVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Metric/MetricVersion/MetricVersion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModel/MlModelVersion/MlModelVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Pipeline/PipelineVersion/PipelineVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SearchIndexVersion/SearchIndexVersion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Topic/TopicVersion/TopicVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/APICollectionPage/APICollectionVersionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaVersionPage/DatabaseSchemaVersionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseVersionPage/DatabaseVersionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceVersionPage/ServiceVersionMainTabContent.tsx
- I worked on fixing tags appearance in version page
Issue : 
Fixed : 
#
#
> MINOR: fix the tags rendering in entity version pages

- openmetadata-ui/src/main/resources/ui/src/constants/Services.constant.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DatabaseServiceUtils.test.tsx
> Minor: Hide incremental metadata extraction config in the UI

- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/mcp/HttpServletSseServerTransportProvider.java
- openmetadata-service/src/main/java/org/openmetadata/service/mcp/McpServer.java
- openmetadata-service/src/main/java/org/openmetadata/service/mcp/tools/GlossaryTermTool.java
- openmetadata-service/src/main/java/org/openmetadata/service/mcp/tools/McpTool.java
- openmetadata-service/src/main/java/org/openmetadata/service/mcp/tools/PatchEntityTool.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/JwtFilter.java
> Add Authorization RBAC to patch tool

- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/ExpressionValidator.java
Add missing evaluator class 
#
#
> Add Missing Package to rule evaluator

- openmetadata-ui/src/main/resources/ui/src/components/APIEndpoint/APIEndpointVersion/APIEndpointVersion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Container/ContainerVersion/ContainerVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DashboardVersion/DashboardVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModelVersion/DataModelVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/CommonWidgets/CommonWidgets.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsContainer/DataProductsContainer.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/StoredProcedureVersion/StoredProcedureVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableVersion/TableVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityRightPanel/EntityRightPanel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Metric/MetricVersion/MetricVersion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModel/MlModelVersion/MlModelVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Pipeline/PipelineVersion/PipelineVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/SearchIndexVersion/SearchIndexVersion.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Topic/TopicVersion/TopicVersion.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/APICollectionPage/APICollectionVersionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaVersionPage/DatabaseSchemaVersionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseVersionPage/DatabaseVersionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/GenericWidget/GenericWidgetUtils.tsx
- I worked on fixing the data product being rendered in tables
Issue : 
Fixed : 
#
#
> MINOR: fix the data product being rendered in tables

- ingestion/src/metadata/data_quality/validations/column/sqlalchemy/columnValuesToBeUnique.py
> MINOR: clean up import

- ingestion/src/metadata/data_quality/validations/column/sqlalchemy/columnValuesToMatchRegex.py
> MINOR: Fix like test

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/LineageSearchSelect/LineageSearchSelect.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityLineage/LineageSearchSelect/LineageSearchSelect.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Lineage.constants.ts
Add virtual list in lineage select to avoid lagging in case of large lineages
#
#
> add virtual list for lineage select

- openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericProvider/GenericProvider.tsx
This pull request refines the logic for handling the left panel's expand/collapse behavior in the `GenericProvider` component. The changes improve layout management by introducing checks for edge cases, ensuring the layout is updated only when necessary, and handling fallback scenarios more robustly.
* Added a check to return early if `leftPanelWidget` is not defined, preventing unnecessary operations.
* Ensured the layout is only updated when the left panel's width differs from the target width, avoiding redundant updates.
* Refactored the logic to store and restore the `expandedLayout` more cleanly, ensuring fallback to the current layout if no stored layout is available.
* Enhanced readability and maintainability by restructuring the `setLayout` logic and adding comments for clarity. …
> fix the entity collapsable right panel

- openmetadata-service/src/main/java/org/openmetadata/service/secrets/SecretsManager.java
We are eating all the traces in the server, so we don't have a way to check the encryption issues that users see in the UI
#
#
> MINOR - Secrets Manager server logging

- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/pyproject.toml
- openmetadata-airflow-apis/pyproject.toml
> MINOR [1.6.8]Bump ingestion version

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/EntityRightCollapsablePanel.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericProvider/GenericProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/IconButtons/EditIconButton.tsx
- I worked on fixing the right panel visible on the bottom of page even after expanded is closed.
- Added playwright test for the fix.
Issue : 
https://github.com/user-attachments/assets/3b91bbe7-f07f-489c-981a-fed923af6441
Fixed : 
https://github.com/user-attachments/assets/3c4839cb-8e1f-41f5-b662-b8c2dc9c5d5a
#
#
> MINOR: fix the right panel visible after expanded is closed

- bootstrap/sql/migrations/native/1.7.1/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.7.1/postgres/schemaChanges.sql
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/WorkflowHandler.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/createAndRunIngestionPipeline/CreateIngestionPipelineImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/createAndRunIngestionPipeline/RunIngestionPipelineImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/flowable/builders/ParallelGatewayBuilder.java
- openmetadata-spec/src/main/resources/json/schema/configuration/workflowSettings.json
> MINOR: Improve Workflow Logs and Reduce Concurrency

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Pipeline/PipelineDetails/PipelineDetails.component.tsx
Issue:-
Activity Feeds count not showing up for pipeline details page, due to missing counts api call in PipelineDetails component.
Fix:-
#
#
> fix(ui):  Feeds count not showing up in PipelineDetails page.

- .github/workflows/mysql-nightly-e2e.yml
> fix(ci): typo for mysql workflow slack message title

- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchSourceBuilderFactory.java
OSS missing guards for Log , log1p and sort
#
#
> OSS add guards for sqrt, log1p etc

- openmetadata-docs/content/v1.7.x/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.7.x/connectors/database/bigquery/yaml.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/bigquery/yaml.md
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/BigQuery.md
> Docs: Adding Cost Per TiB in docs

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
I worked on adding what's new content for 1.7.1 release.
https://github.com/user-attachments/assets/16844226-5368-447d-b289-5dac5d4c8555
#
#
> Minor: Add what's new for 1.7.1 release

- bootstrap/sql/migrations/native/1.7.1/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.7.1/postgres/schemaChanges.sql
- openmetadata-service/src/test/java/org/openmetadata/service/resources/system/SystemResourceTest.java
> MINOR: Fix app marketplace migrations

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchSourceBuilderFactory.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchSourceBuilderFactory.java
> Revert: Filter for function score and add floor to totalVotes

- bootstrap/sql/migrations/native/1.7.1/postgres/schemaChanges.sql
Fix Query for postgres tablei
#
#
> Failing Postgres sql

- bootstrap/sql/migrations/native/1.7.1/postgres/schemaChanges.sql
> Escape ? to causing issues in jdbi binding

- openmetadata-docs/content/partials/v1.6/connectors/yaml/common/aws-config.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/common/aws-config.md
- openmetadata-docs/content/partials/v1.8/connectors/yaml/common/aws-config.md
- openmetadata-docs/content/v1.7.x/connectors/ingestion/workflows/dbt/ingest-dbt-yaml.md
I worked on DBT indentation Fix.
#
#
> Doc: DBT indentation FIX

- openmetadata-ui/src/main/resources/ui/src/components/DataProducts/DataProductsContainer/DataProductsContainer.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreV1.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/SearchClassBase.ts
- Revert the data assets order for search and adjust styles for the number of data assets in explore page
Before
After
https://github.com/user-attachments/assets/ec7fb09e-46cc-4ff4-b8a6-5a938e8aba1c
- Fix the title for Add Data Products
Before
After
#
#
> chore(ui): revert search order and minor styles changes for Explore page

- openmetadata-docs/content/v1.6.x/deployment/upgrade/docker.md
- openmetadata-docs/content/v1.6.x/deployment/upgrade/kubernetes.md
- openmetadata-docs/content/v1.7.x/deployment/upgrade/docker.md
- openmetadata-docs/content/v1.7.x/deployment/upgrade/kubernetes.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/upgrade/docker.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/upgrade/kubernetes.md
I worked on 404 Error Fix.
#
#
> Doc: 404 Error Fix

- ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/looker/models.py
Add: Looker column level lineage
#
#
> Add: Looker column level lineage

- openmetadata-service/pom.xml
- openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
- Removes APache Connector with old school HttpUrlConnectorProvider()
#
#
> Removed apache connector

- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/AddWidgetModal/AddWidgetModal.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/AddWidgetModal/AddWidgetModal.tsx
Fixes: #21479 
Issue:
-  Having an Announcement is causing issues since it doesn't have any control to move or delete
Fix:
#
#
> fix(ui): #21479 filter announcment widget from customisation

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
> Fix: looker CLL errors

- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/ModelTab/ModelTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaTable/SchemaTable.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/DisplayName/DisplayName.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/DisplayName/DisplayName.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/DisplayName/DisplayName.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/fonts.less
Fixes #21459
Worked on Dashboard Data Model name column should not be links and clickable. 
Removed `link` prop from `DisplayName` component inside `ModelTab`, making the `link` optional inside `DisplayName` component.
Issue:
https://github.com/user-attachments/assets/16ae1a94-7c0f-4569-a18f-19b6c3dc9cd3
Fix:
https://github.com/user-attachments/assets/a065799d-03bd-4df8-977b-c9a7622e7588
Name and displayName color fix:
Earlier name and displayName both had same regular color making it difficult to identify them if link is not present.
Added `text-grey-600` class to name if displayName is present changing color of the name to grey.
#
#
> fix(ui): dashboard data model name column should not be link

- openmetadata-docs/content/v1.6.x/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/postgres/troubleshooting.md
- openmetadata-docs/content/v1.6.x/connectors/database/postgres/yaml.md
- openmetadata-docs/content/v1.7.x/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.7.x/connectors/database/postgres/troubleshooting.md
- openmetadata-docs/content/v1.7.x/connectors/database/postgres/yaml.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/postgres/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/postgres/troubleshooting.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/postgres/yaml.md
- Included instructions for configuring IAM authentication in PostgreSQL, detailing necessary database settings, user permissions, and AWS role requirements.
- Added troubleshooting information for the "PAM authentication failed for user" error, outlining steps to resolve IAM permission issues.
#
#
> Doc: Add IAM authentication details for PostgreSQL connector

- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
To let initialize Collate App after https://github.com/open-metadata/OpenMetadata/pull/21543/files since we need to pass the limits there when registering the MCP
#
#
> FIX - OpenMetadataApplication update limits to protected

- openmetadata-docs/content/v1.6.x/how-to-guides/data-governance/domain-&-data-products/index.md
- openmetadata-docs/content/v1.7.x/how-to-guides/data-governance/domain-&-data-products/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/how-to-guides/data-governance/domain-&-data-products/index.md
I worked on YT Video Link Fix.
#
#
> Doc: YT Video Link Fix

- openmetadata-ui/src/main/resources/ui/src/components/ExploreV1/ExploreSearchCard/explore-search-card.less
Issue:-
https://github.com/user-attachments/assets/35ab9a84-5fb0-4b21-af16-7b5361a658c7
Fix
https://github.com/user-attachments/assets/2d7e8c76-e323-4651-b4e0-e85b0ea2046d
#
#
> Fix(ui):  Background color for text highlight in tables of explore cards

- openmetadata-docs/content/v1.6.x/connectors/database/postgres/troubleshooting.md
- openmetadata-docs/content/v1.7.x/connectors/database/postgres/troubleshooting.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/postgres/troubleshooting.md
I worked on Postgres Troubleshooting Updation.
#
#
> Doc: Postgres Troubleshooting Updation

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/IngestionPipelineRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/SystemRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
Fix #21226: External ingestion not visible on UI without Airflow
#
#
> Fix #21226: External ingestion not visible on UI without Airflow

- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/BlockEditor.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/BlockEditor.constants.ts
Fixes [#21566](https://github.com/open-metadata/OpenMetadata/issues/21566)
issue:
https://github.com/user-attachments/assets/f42f9125-0072-4b0b-81e2-717b08e58b66
Solution:
https://github.com/user-attachments/assets/50df56a3-ffc7-4612-809d-17a47734252c
#
#
> Fix: #21566 Copy-Paste from Excel triggers file upload instead of pasting content

- openmetadata-ui/src/main/resources/ui/src/components/APIEndpoint/APIEndpointDetails/APIEndpointDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DashboardDetails/DashboardDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/DataModelDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Metric/MetricDetails/MetricDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MlModel/MlModelDetail/MlModelDetail.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Pipeline/PipelineDetails/PipelineDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Topic/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/APICollectionPage/APICollectionPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ContainerPage/ContainerPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseDetailsPage/DatabaseDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/SearchIndexDetailsPage/SearchIndexDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/StoredProcedure/StoredProcedurePage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.tsx
Flaky Playwright test:
- Remove the 2000ms from the alert notification and use the default timer of the alert function.
- Entity.spec around the restore was failing due to alert being timeout and not visible.
#
#
> PLAYWRIGHT: fix the flaky  playwright test

- ingestion/src/metadata/ingestion/lineage/models.py
I worked on adding lineage dialect for Exasol, Trino and Vertica database.
#
#
> Add lineage dialect for Exasol, Trino and Vertica

- openmetadata-docs/content/v1.6.x/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/databricks/yaml.md
- openmetadata-docs/content/v1.6.x/connectors/database/unity-catalog/index.md
- openmetadata-docs/content/v1.6.x/connectors/database/unity-catalog/yaml.md
- openmetadata-docs/content/v1.7.x/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.7.x/connectors/database/databricks/yaml.md
- openmetadata-docs/content/v1.7.x/connectors/database/unity-catalog/index.md
- openmetadata-docs/content/v1.7.x/connectors/database/unity-catalog/yaml.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/databricks/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/databricks/yaml.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/unity-catalog/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/database/unity-catalog/yaml.md
I worked on Databricks and Unity Catalog Requirement Updation.
#
#
> Doc: Databricks and Unity Catalog Requirement Updation

- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TableProfiler/ProfilerSettingsModal/ProfilerSettingsModal.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/SchemaEditor.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/SchemaEditor.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/SchemaEditor/SchemaEditor.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Topic/TopicDetails/TopicDetails.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/QueryViewer/QueryViewer.component.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/components/code-mirror.less
- openmetadata-ui/src/main/resources/ui/src/utils/DashboardDataModelUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/SearchIndexUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
https://github.com/user-attachments/assets/d1427ee7-8797-49ff-a7c6-ab56d000439e
#
#
> Fix: Issue related to SQL query viewer

- openmetadata-docs/content/v1.6.x/how-to-guides/admin-guide/alerts.md
- openmetadata-docs/content/v1.7.x/how-to-guides/admin-guide/alerts.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/how-to-guides/admin-guide/alerts.md
I worked on  YT Video Link Removal.
#
#
> Doc: YT Video Link Removal

- ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py
Fix: Looker cll parsing issue
#
#
> Fix: Looker cll parsing issue

- ingestion/src/metadata/ingestion/source/dashboard/tableau/client.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/connection.py
- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/dashboard/tableauConnection.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/dashboard/tableauConnection.ts
Chore: Tableau Improvements
Fixes #21552 
#
#
> Chore: Tableau Improvements

- ingestion/src/metadata/ingestion/api/topology_runner.py
Fixes #21551
I worked on removing check of `sourceHash` present on existing entity while performing PATCH request. Ideally, PATCH request should be perform when entity is present regardless of `sourceHash` presence in entity.
#
#
> Fixes #21551: Remove existing entity source hash presence check

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ActivityFeed.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardNew/ActivityFeedcardNew.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedCardNew/CommentCard.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedDrawer/ActivityFeedDrawer.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedList/ActivityFeedListV1New.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedProvider/ActivityFeedProviderContext.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedTab/ActivityFeedTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/TaskFeedCard/TaskFeedCardNew.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseIncidentTab/TestCaseIncidentTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/IncidentManager/TestCaseIncidentTab/TestCaseIncidentTab.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/Task/TaskTab/TaskTabNew.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/Task/TaskTabIncidentManagerHeader/TasktabIncidentManagerHeaderNew.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Feeds.constants.ts
- openmetadata-ui/src/main/resources/ui/src/rest/feedsAPI.ts
Fixes #21276
- Add functionality to load comments of the post via lazy loading
- Fix flickering while switching tasks.
- Fix re-rending issue, if the user clicks on an active task/feed/conversation
- Added playwright test
https://github.com/user-attachments/assets/4f4b71fa-bf7e-4c5f-9076-5e2c0c06adf2
#
#
> Fix: #21276 Only 3 Comments Shown by Default in Incident View

- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityExportModalProvider/EntityExportModalProvider.interface.ts
This pull request removes an unused property from the `PDFLayoutConfig` interface in the `EntityExportModalProvider.interface.ts` file.
* **Code cleanup**:
* Removed the `imagesPerPage` property from the `PDFLayoutConfig` interface, as it is no longer used. (`[openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityExportModalProvider/EntityExportModalProvider.interface.tsL33]
#
#
> MINOR: remove the type not wanted in pdfLayout config

- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummary/TestSummaryGraph.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummaryCustomTooltip/TestSummaryCustomTooltip.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/Profiler/TestSummaryCustomTooltip/TestSummaryCustomTooltip.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/date-time/DateTimeUtils.test.ts
Fixes #21649
Issue:
The previous calculation was based on milliseconds, but we were getting values in seconds.
Solution:
#
#
> Fix: #21649 Freshnes test is not displaying right time value (seconds vs miliseconds)

- openmetadata-ui/src/main/resources/ui/src/styles/modal.less
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
This pull request includes updates to the modal and button styling in the UI, focusing on simplifying the design and improving accessibility. The most important changes involve removing unnecessary shadow effects and updating focus styles for buttons.
* Removed the box-shadow effect from primary buttons in modal footers to simplify the design. (`openmetadata-ui/src/main/resources/ui/src/styles/modal.less`, [openmetadata-ui/src/main/resources/ui/src/styles/modal.lessL38-L41](diffhunk://#diff-5b449b174336549446ec147d4645a4db42b646e6a8200239723721dabf11a52cL38-L41))
* Updated the `@button-box-shadow-focus` variable to use a more accessible color (`rgba(209, 233, 255, 1)`) for focus outlines, replacing the previous multi-shadow definition. …
> MINOR: fix the primary button focus color

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
This PR updates the 'Whats new section' for 1.7.2 release
https://github.com/user-attachments/assets/c3636f7b-1eb3-4fd5-bc4e-5c991e639917
#
#
> chore(ui): Whats new for 1.7.2

- ingestion/src/metadata/cli/classify.py
- ingestion/src/metadata/cli/dataquality.py
> MINOR: Fix bigquery import issue

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/TableIndex.java
- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
- openmetadata-ui/src/main/resources/ui/src/generated/entity/data/table.ts
Update Field table queries  to queries
#
#
> Fix - Queries not tableQueries

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/TableClass.ts
- openmetadata-ui/src/main/resources/ui/src/rest/testAPI.ts
This pull request updates API endpoint paths related to test case results across multiple files to ensure consistency and alignment with the updated API structure. The changes primarily involve replacing `/testCaseResult` with `/testCaseResults` in the affected code.
* [`openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts`](diffhunk://#diff-6e338f862dd7ea40c7948ab15c2c59acf863065097cf2f2d12cf96b9f3c1eaf7L305-R305): Updated the endpoint in `page.waitForResponse` to use `/testCaseResults/*?*` instead of `/testCaseResult?*`.
* [`openmetadata-ui/src/main/resources/ui/playwright/support/entity/TableClass.ts`](diffhunk://#diff-57a7ae250ed3f4c1a452f58a1207fec3079eedf1f70d9b130121df30d9ec7b60L348-R348): Modified the endpoint in `apiContext.put` to use …
> Refactor Data Quality API endpoints in Playwright tests and support classes to use consistent URL structure for test case results

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
This PR updates whats new for 1.7.2 release
https://github.com/user-attachments/assets/71969ea1-f54a-43e8-9253-59b56428ba5a
#
#
> chore(ui) : update whats new for 1.7.2 

- openmetadata-ui/src/main/resources/ui/playwright/utils/advancedSearch.ts
> Fix (ui): Flaky Advance Search test case

- openmetadata-docs/content/partials/v1.7/releases/1.7.1.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/partials/v1.8/releases/1.7.1.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/v1.7.x/menu.md
- openmetadata-docs/content/v1.7.x/releases/releases/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/releases/releases/index.md
I worked on 1.7.2 Release Updation.
#
#
> Doc: 1.7.2 Release Updation

- openmetadata-service/src/main/resources/json/data/app/McpApplication.json
- openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/McpApplication.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Applications/McpApplication.md
- openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/McpApplication.json
> Mcp Doc fixes

- ingestion/src/metadata/data_quality/source/test_suite.py
Fixes #21274
**What**
- get profiler config when executing bundle test suite to propagate table sample config
#
#
> ISSUE #21274: added profiler config when executing bundle suite

- openmetadata-docs/content/v1.6.x/connectors/api/index.md
- openmetadata-docs/content/v1.7.x/connectors/api/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/connectors/api/index.md
I worked on API Service Page Content Updation.
#
#
> Doc: API Service Page Content Updation

- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/hashtag/hashtagSuggestion.ts
Fixes: While rendering the KnowledgeCenter card with DataAsset hashList, it renders an element which covers the leftSideBar
I have removed rendering of the same on creation instead, keep it interactive to avoid blocking of sidebar 
Issue
https://github.com/user-attachments/assets/9006295c-9ad7-4225-b153-19911aec6e4a
Fix
https://github.com/user-attachments/assets/ff163380-1004-4124-99c3-2ac5c275a45c
#
#
> fix(ui): hashlist in view blocks leftsidebar

- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
This PR removes the recently added `deleted` parameter from the internal `searchByField` API here -  https://github.com/open-metadata/OpenMetadata/pull/21151
The `deleted` flag is already handled via `queryFilter` in the `queryBuilder` object. Passing it separately is redundant and can interfere with internal field-level filtering.
#
#
> Fix #21653 - Remove recently added delete param field in searchByField api

- ingestion/src/metadata/ingestion/source/dashboard/superset/queries.py
Fix #21099: fix Superset ingestion bad query
#
#
> Fix #21099: fix Superset ingestion bad query

- openmetadata-service/src/main/java/org/openmetadata/service/resources/search/SearchResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/ElasticSearchClient.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OpenSearchClient.java
Revert pr #21723, this is api is used only by the ingestion team and  these changes did not cause issue in the Automator filters
#
#
> Revert pr #21723

- bootstrap/sql/migrations/native/1.7.3/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.7.3/postgres/schemaChanges.sql
Fix Tests broken by #21747
#
#
> Fix Tests broken by #21747

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> Minor: Added What new content for 1.7.3

- openmetadata-service/src/main/java/org/openmetadata/service/mcp/tools/CreateTestCaseTool.java
- openmetadata-service/src/main/java/org/openmetadata/service/mcp/tools/DefaultToolContext.java
- openmetadata-service/src/main/java/org/openmetadata/service/mcp/tools/TestDefinitionsTool.java
- openmetadata-service/src/main/resources/json/data/mcp/tools.json
Add Create Test Casea tool
#
#
> Add Data Quality Test Casae

- openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/hashtag/hashtagSuggestion.ts
This pull request introduces improvements to the `hashtagSuggestion` functionality in the `BlockEditor` component. The changes ensure better handling of editor modes and enhance the user experience by modifying the behavior of the suggestion list.
Enhancements to editor behavior:
* [`openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/hashtag/hashtagSuggestion.ts`](diffhunk://#diff-10c81f79112b71cb337ac1d0a9027aee4afa246c0ff61837d9beeac047aa0df9R63-R67): Added a check to prevent the suggestion list from rendering when the editor is in preview mode (`isEditable === false`).
User experience improvements:
* [`openmetadata-ui/src/main/resources/ui/src/components/BlockEditor/Extensions/hashtag/hashtagSuggestion.ts`](diffhunk://#diff-10c81f79112b71cb337ac1d0a9027aee4afa24 …
> fix(ui): hashlist render for block editor

- bootstrap/sql/migrations/native/1.7.4/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.7.4/postgres/schemaChanges.sql
- openmetadata-service/src/main/java/org/openmetadata/service/events/subscription/AlertsRuleEvaluator.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/events/subscription/EventSubscriptionResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/ExpressionValidator.java
- openmetadata-service/src/main/resources/json/data/EntityObservabilityFilterDescriptor.json
- openmetadata-service/src/main/resources/json/data/EventSubResourceDescriptor.json
- openmetadata-service/src/main/resources/json/data/FilterFunctionsDescriptor.json
- openmetadata-service/src/main/resources/json/data/eventsubscription/ActivityFeedEvents.json
- openmetadata-spec/src/main/resources/json/schema/events/subscriptionResourceDescriptor.json
- openmetadata-ui/src/main/resources/ui/src/generated/events/subscriptionResourceDescriptor.ts
- This disabled feeds that are generated by bots 
#
#
> Disabled bot creating activity feeds

- .github/workflows/typescript-type-generation.yml
I worked on adding a blank workflow for type generation 
#
#
> Add empty TypeScript Type Generation workflow for pull requests

- openmetadata-docs/content/v1.7.x/deployment/bare-metal/index.md
- openmetadata-docs/content/v1.7.x/developers/contribute/build-code-and-run-tests/prerequisites.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/bare-metal/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/prerequisites.md
I worked on Java Version Updation to 21.
#
#
> Doc: Java Version Updation to 21

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/TeamsDragAndDrop.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Metric.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataInsightReportApplication.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/EntityVersionPages.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/VersionPages/ServiceEntityVersionPage.spec.ts
This pull request improves the Playwright test suite for the OpenMetadata UI by enhancing user authentication handling, replacing outdated methods, and optimizing test execution flows. The changes primarily focus on introducing a reusable `UserClass`, utilizing `performAdminLogin` for admin authentication, and improving test reliability by waiting for network and UI states.
* Replaced `storageState` usage for admin login with a new `UserClass` implementation across multiple test files. This allows dynamic login handling and ensures better encapsulation of user-related operations.
* Introduced `performAdminLogin` utility to streamline admin login and role setup, replacing `createNewPage` in test setup and cleanup procedures.
* Updated the "Teams drag and drop" test to …
> PLAYWRIGHT: fix delete async alert on other playwright test causing failure

- ingestion/tests/integration/alationsink/test_alationsink.py
- ingestion/tests/integration/sources/mlmodels/mlflow/conftest.py
> MINOR: Fix pytests

- ingestion/src/metadata/profiler/interface/sqlalchemy/bigquery/profiler_interface.py
Fixes #21447
**What**
- preserve BQ casing for struct fields
**Why**
- previous approached return the lowercase version of the field throwing an error when matching against actual table column when ingesting profiler data
#
#
> ISSUE #21447: preserve BQ struct field casing

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ColumnRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/columns/ColumnResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/teams/UserResourceTest.java
> Fix TableResourceTest failures for column updates

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/glossary/GlossaryTermResourceTest.java
> fix #21394 Custom properties bug update with existing wrong values

- openmetadata-ui/src/main/resources/ui/src/components/DataAssetSummaryPanel/DataAssetSummaryPanel.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataAssetSummaryPanel/DataAssetSummaryPanel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityInfoDrawer/EntityInfoDrawer.component.tsx
- openmetadata-ui/src/main/resources/ui/src/context/LineageProvider/LineageProvider.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
Fixes lineage expand collapse - There was a case where we received same entities with different doc id. Added a cleanup for removing duplicates.
Minor - Show owner info on lineage summary panel.
#
#
> fix(ui): lineage expand collapse

- openmetadata-service/pom.xml
> commons-beanutils vulnerability reported in security scan

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Policies.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Roles.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/roles.ts
- This PR fixes AUT failures for Policies.spec and Roles.spec caused due to pagination.
- The element we need to locate is not present on the page, so we need to check next pages for it.
- Created a util function `getLocatorWithPagination` to find the element and used it inside tests.
#
#
> fix(test): AUT failures for Policies.spec and Roles.spec

- openmetadata-ui/src/main/resources/ui/src/pages/LoginPage/LoginCarousel.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/LoginPage/login.style.less
This pull request introduces a small enhancement to the login carousel component by adding a new CSS class for styling. The change improves the maintainability and customization of the carousel's appearance.
Styling updates:
* [`openmetadata-ui/src/main/resources/ui/src/pages/LoginPage/LoginCarousel.tsx`](diffhunk://#diff-068cb65ba6d6d59f61a17483472079fd6e330be85c04490b1c410567c60e9edaR30): Added the `className="login-carousel"` property to the carousel component to facilitate targeted styling.
* [`openmetadata-ui/src/main/resources/ui/src/pages/LoginPage/login.style.less`](diffhunk://#diff-17fdc98661a9401c4f5f1925e92c2012a1a63392fd8602ae062fbf5dd94c770aR193): Defined the `.login-carousel` class and nested styling rules to adjust the height of carousel slides. 
Issue :  
Fixed : 
#
#
> MINOR: fix the layout of suggestion slider in description box

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> Release: Add what's new content for 1.7.5

- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/Users.component.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/Users.component.tsx
This PR removes the additional api call happening in user profile page's My Data and Following tab
The additional call was happening because of fetching assets in parent component( Users compoenent ) and passing the assets count to Asset tab via prop. This  call in parent component is not required in case of User Profile page, since we do not require the count to be shown in Tab header. Its required only in cases where we are showing assets count in Tab Headers .
Issue
https://github.com/user-attachments/assets/647baad1-3f9e-475b-b925-e20bd6d127ad
Fix
https://github.com/user-attachments/assets/f2bb2ebf-dc38-45c6-b012-45c037db815c
#
#
> Fix(ui): Additional query call in user profile page

- openmetadata-ui/src/main/resources/ui/src/pages/LoginPage/LoginCarousel.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/LoginPage/login.style.less
Issue with image being cropped for small screen sizes
https://github.com/user-attachments/assets/5020e022-bbf9-407d-8abd-1a909c445c98
https://github.com/user-attachments/assets/b679a795-4bf9-41ac-8d9b-297ee8110db9
#
#
> fix(ui): carousel image being cropped for small width

- openmetadata-service/src/main/java/org/openmetadata/service/resources/scim/ScimResource.java
> Swagger response code corrected for scim

- openmetadata-docs/content/partials/v1.7/releases/1.7.4.md
- openmetadata-docs/content/partials/v1.7/releases/latest.md
- openmetadata-docs/content/partials/v1.8/releases/1.7.4.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/v1.7.x/deployment/docker/index.md
- openmetadata-docs/content/v1.7.x/menu.md
- openmetadata-docs/content/v1.7.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.7.x/releases/releases/index.md
- openmetadata-docs/content/v1.7.x/sdk/python/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/sdk/python/index.md
I worked on 1.7.5 Release Updation.
#
#
> Doc: 1.7.5 Release Updation

- openmetadata-docs/content/v1.7.x/developers/contribute/build-code-and-run-tests/prerequisites.md
- openmetadata-docs/content/v1.8.x-SNAPSHOT/developers/contribute/build-code-and-run-tests/prerequisites.md
I worked on Java JDK Version Updation to 21.
#
#
> Doc: Java JDK Version Updation to 21

- openmetadata-docs/content/v1.8.x-SNAPSHOT/sdk/go/index.md
Just fix Go SDK Doc readme to say "How to Use APIs Using the Go Client" from "How to Use APIs Using the Java Client"
#
#
> Doc: fix client to Go

- ingestion/setup.py
> MINOR: Fix pytests jaraco package

- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
The totalAssetCount was only updated when `assetCount === undefined` . This means that if the parent component provides an assetCount prop, the AssetsTabs component will use that value and won't update it based on the actual search results.
This is the root cause of the flakiness! The issue is:
The parent component provides an assetCount prop
Assets are added, but the parent doesn't immediately update the assetCount
The AssetsTabs component continues to use the old assetCount value
The totalAssetCount remains at the old value
The search/filter controls don't render  and the delete btn is not visible on refresh because totalAssetCount === 0 
The fix I applied should resolve this by ensuring the UI is properly synchronized after adding assets. 
Issue:-
On refresh the delete option was not …
> Fix : Domain AUT failure

- openmetadata-service/src/main/resources/elasticsearch/en/query_cost_record_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/query_cost_record_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/query_cost_record_index_mapping.json
Revert : [query_cost_record_search_index Search reindexing issue](https://github.com/open-metadata/OpenMetadata/pull/21906) as it affcets the aggregation used in /api/v1/queryCostRecord/service/{serviceFQN} api
#
#
> Revert : query_cost_record_search_index Search reindexing issue

- openmetadata-service/src/main/java/org/openmetadata/service/search/elasticsearch/dataInsightAggregators/QueryCostRecordsAggregator.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/dataInsightAggregator/QueryCostRecordsAggregator.java
- openmetadata-service/src/main/resources/elasticsearch/en/query_cost_record_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/jp/query_cost_record_index_mapping.json
- openmetadata-service/src/main/resources/elasticsearch/zh/query_cost_record_index_mapping.json
> Fix query cost aggregation

- CLAUDE.md
Added Claude MD to start working with directory
#
#
> Add Claude.md

- openmetadata-docs/content/partials/v1.7/connectors/yaml/api/source-config-def.md
- openmetadata-docs/content/partials/v1.7/connectors/yaml/api/source-config.md
- openmetadata-docs/content/partials/v1.8/connectors/yaml/api/source-config-def.md
- openmetadata-docs/content/partials/v1.8/connectors/yaml/api/source-config.md
- openmetadata-docs/content/v1.7.x/connectors/api/rest/yaml.md
I worked on Rest YAML File Updation.
#
#
> Doc: Rest YAML File Updation

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Policies.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Roles.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/roles.ts
Worked on flaky tests for Policies.spec and Roles.spec
The Next button needs to click to find the exact role/policy we needed, due to large list. 
The tests failed due to unavailability of the Next button.
<br />
Changed the iteration logic to find the needed policy/role using Next button, instead of while loop, used for loop.
#
#
> fix(test): flaky Policies.spec and Roles.spec

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TableRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
> Remove Default: null from columns and let json to pojo handle

- ingestion/src/metadata/ingestion/source/dashboard/tableau/metadata.py
Tableau Lineage Is not generated if the lineage is made from tables within multiple schemas the root cause is that from UpstreamTable model we rely on values `table_name` and `schema` fields returned by the graphql query 
in such case the `schema` field will only contain name of a single schema (limitation from tableau) but it also provided a fullName field from which we can extract the actual schema.
#
#
> Minor: Fix Tableau Lineage in Multi Schema Model

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/AdvanceSearchFilter/CustomPropertyAdvanceSeach.spec.ts
This PR fixes CustomPropertyAdvanceSeach.spec.ts > CustomProperty Dashboard Filter test
The test was failing while it was trying to access the entity-header-display-name after applying the advance search and getting redirected to the explore page.
Fix
Added loader detach check before accessing the entity-header-display-name
#
#
> Fix(test): Custom property advance search AUT failure

- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/partials/v1.9/releases/latest.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/releases/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/releases/releases/latest.md
I worked on 1.8 Release Updation.
#
#
> Doc: 1.8 Release Updation

- ingestion/src/metadata/ingestion/source/api/rest/metadata.py
> MINOR: REST display object column type

- ingestion/src/metadata/pii/algorithms/classifiers.py
- ingestion/src/metadata/pii/algorithms/presidio_patches.py
- ingestion/src/metadata/sampler/processor.py
- ingestion/src/metadata/sampler/sqlalchemy/databricks/sampler.py
- ingestion/src/metadata/sampler/sqlalchemy/sampler.py
- ingestion/src/metadata/sampler/sqlalchemy/unitycatalog/sampler.py
Fixes #21955
doing some improved session handling to close it properly. we can see how the mem profile keeps more steady (vs. the screenshots on the issue where there's a slight base memory steady growth)
Also fixing a small exception catch on the presidio after last PII changes
#
#
> FIX #21955 - Handle sampler SQA sessions

- openmetadata-ui/src/main/resources/ui/src/utils/ApplicationSchemas/SearchIndexingApplication.json
Search index app settings shows it as query cost result but it should be query cost record.
this also solves error produced in backend
```
ERROR [2025-06-25 01:20:19,243] [AppScheduler_Worker-1] o.o.s.a.b.s.SearchIndexApp - Failed to recreate index for entityType 'queryCostResult'.
java.lang.NullPointerException: Cannot invoke "org.openmetadata.service.search.models.IndexMapping.getIndexName(String)" because "indexMapping" is null
```
#
#
> Minor: Fix typo on query cost record index

- ingestion/setup.py
- ingestion/src/metadata/data_quality/validations/models.py
- ingestion/src/metadata/data_quality/validations/runtime_param_setter/base_diff_params_setter.py
- ingestion/src/metadata/data_quality/validations/runtime_param_setter/table_diff_params_setter.py
- ingestion/src/metadata/data_quality/validations/table/sqlalchemy/tableDiff.py
- ingestion/src/metadata/ingestion/source/database/trino/connection.py
Backports Fix done in https://github.com/open-metadata/OpenMetadata/pull/21983/files
> Backport Trino Fix

- openmetadata-service/src/main/java/org/openmetadata/service/governance/workflows/elements/nodes/automatedTask/runApp/RunAppImpl.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ChangeSummarizer.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v132/MigrationUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchRepository.java
Fixes Playwright failures in main.
After changes in JsonUtils class in [PR #21882](https://github.com/open-metadata/OpenMetadata/pull/21882), some classes were still catching the old exception and were not updated to handle the new JsonParsingException.
#
#
> Fix Playwright failures: handle JsonParsingException after JsonUtils refactor

- openmetadata-docs/content/v1.7.x/how-to-guides/data-governance/classification/Auto Classification/index.md
- openmetadata-docs/content/v1.8.x/how-to-guides/data-governance/classification/Auto Classification/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/how-to-guides/data-governance/classification/Auto Classification/index.md
I worked on Auto Classification Images Fix.
#
#
> Doc: Auto Classification Images Fix

- .github/workflows/typescript-type-generation.yml
> Chore: Fix the failing type generation workflow for PRs from forked repository

- openmetadata-spec/src/main/resources/json/schema/entity/data/table.json
> feat: add write dml

- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/SearchIndexApp.java
> Fix: recreate fails if we can't find one index for a given entity

- openmetadata-docs/content/v1.8.x/collate-menu.md
- openmetadata-docs/content/v1.8.x/menu.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/menu.md
I worked on MCP Menu Updation.
#
#
> Doc: MCP Menu Updation

- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/dashboard/looker/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/dashboard/powerbi/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/dashboard/tableau/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/database/bigquery/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/database/mssql/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/database/mysql/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/database/postgres/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/database/redshift/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/messaging/kafka/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/pipeline/dagster/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/search/elasticsearch/yaml.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/storage/s3/yaml.md
This pull request updates the OpenMetadata documentation to improve clarity and consistency by adding descriptions and marking required fields in YAML configuration examples across various connectors. The changes primarily focus on enhancing documentation for authentication, connection settings, and optional configurations.
* [`openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/dashboard/looker/yaml.md`](diffhunk://#diff-ea85cf3b0082750647ee71ec9e608b14602dc6980421de278a46619c1bbc8133L136-R142): Added descriptions for `clientId`, `clientSecret`, and `hostPort`, marking them as required for Looker API integration.
* [`openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/database/bigquery/index.md`](diffhunk://#diff-566fa0bc3ae099e6416280e3e59244c62261e45b918b61ec6fc20b31c160cc8eL157-R173) …
> Fix Documentation: Consistency around connector yamls

- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
> Update Servlet Holders for SAML

- openmetadata-service/src/main/java/org/openmetadata/service/search/opensearch/OSLineageGraphBuilder.java
[Fixes #21876](https://github.com/open-metadata/OpenMetadata/issues/21876)
#
#
> Issue in Os Lineage Repository

- pom.xml
In the latest run of  publishing mvn package getting error , update the legacy ossrh endpoints to the new central publisher
`Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project openmetadata-java-client: Failed to deploy artifacts: Could not transfer artifact org.open-metadata:common:jar:javadoc:1.8.0-20250702.035737-170 from/to ossrh (https://s01.oss.sonatype.org/content/repositories/snapshots): status code: 403, reason phrase: Forbidden `
#
#
> update the snapshots url for ossrh migration

- .github/workflows/playwright-mysql-e2e-skip.yml
- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e-skip.yml
- .github/workflows/playwright-postgresql-e2e.yml
This pull request updates GitHub Actions workflows to enhance test execution conditions and include additional file paths for triggering workflows. The most important changes involve refining the `if` conditions for job execution and expanding the file path triggers for Playwright E2E workflows.
* [`.github/workflows/playwright-mysql-e2e-skip.yml`](diffhunk://#diff-4d9f638a223646d6c1bcce06ec1b6c5195e493158e41230ad360c599077f015bL31-R31): Added `openmetadata-ui/src/main/resources/ui/playwright/**` to the list of file paths that trigger this workflow.
* [`.github/workflows/playwright-mysql-e2e.yml`](diffhunk://#diff-37a13e66deb903f6ecd558b6a8a4d8d90e827623ba3305f6afcc5afdd7a2b38aR32): Added `openmetadata-ui/src/main/resources/ui/playwright/**` to the list of file paths that trigger this …
> chore(ci): improve e2e runners with conditions

- README.md
- ingestion/README.md
- openmetadata-ui/src/main/resources/ui/package.json
- scripts/check_prerequisites.sh
- Updated the Ingestion Framework section in README.md to reflect an increase in supported connectors from 75+ to 84+.
- Revised Python version requirement in ingestion/README.md from 3.8+ to 3.9+.
- Updated Node.js version requirement in package.json from 10.0.0 to 18.19.0.
- Changed Java required version in check_prerequisites.sh from 11, 16, 17 to 21.
#
#
> Update README and Ingestion Framework Documentation

- common/pom.xml
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-service/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
Fixes issue in publishing staging repository in https://central.sonatype.com/
add name tag in pom.xml of all modules
#
#
> add name tag in pom.xml of all modules

- openmetadata-docs/content/partials/v1.8/releases/1.8.0.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/partials/v1.9/releases/1.8.0.md
- openmetadata-docs/content/partials/v1.9/releases/latest.md
- openmetadata-docs/content/v1.8.x/deployment/docker/index.md
- openmetadata-docs/content/v1.8.x/menu.md
- openmetadata-docs/content/v1.8.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.8.x/releases/releases/index.md
- openmetadata-docs/content/v1.8.x/sdk/python/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/sdk/python/index.md
I worked on 1.8.1 Release Updation.
#
#
> Doc: 1.8.1 Release Updation

- openmetadata-ui/src/main/resources/ui/playwright/utils/bot.ts
- Added checks for the visibility of the revoke button and the authentication mechanism before performing actions.
- Improved flow to ensure appropriate button clicks based on the current UI state.
#
#
> fix(playwright): enhance bot page token reset logic to handle button visibility

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
> fix glossary playwright failure

- openmetadata-docs/content/v1.7.x/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.8.x/connectors/database/bigquery/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/database/bigquery/index.md
I worked on Note Updation in Big Query.
#
#
> Doc: Note Updation in Big Query

- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/BlockEditorUtils.ts
Fixes #22029
Issue:-
https://github.com/user-attachments/assets/a85aee35-07c6-4bbb-b7f0-aeceae118b57
Mentions were being rendered twice in the BlockEditor due to double processing of HTML content. The formatContent function was calling _convertMarkdownFormatToHtmlString on already-processed HTML content, causing mentions to be duplicated.
Root Cause
The formatContent function was always processing content through _convertMarkdownFormatToHtmlString, even when the input was already HTML. This caused:
HTML mentions to be processed twice
Server-formatted mentions to be re-processed
Duplicate mention structures in the output
Solution
Added a check to only convert markdown to HTML if the content is not already HTML:
https://github.com/user-attachments/assets/ea6ab69b-c384-45d1-a5f7-b157485f3342 …
> fix(ui): Mentions formatting in block editor

- openmetadata-ui/src/main/resources/ui/playwright/e2e/auth.setup.ts
- fix the playwright auth-setup breaking
#
#
> PLAYWRIGHT: fix the playwright auth-setup breaking

- openmetadata-docs/content/v1.7.x/connectors/ingestion/workflows/dbt/auto-ingest-dbt-core.md
- openmetadata-docs/content/v1.8.x/connectors/ingestion/workflows/dbt/auto-ingest-dbt-core.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/ingestion/workflows/dbt/auto-ingest-dbt-core.md
I worked on X symbol Removal in Artifacts Discovery.
#
#
> Doc: X symbol Removal

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/CustomThemeConfig.spec.ts
> flaky(UI): custom config Playwright

- openmetadata-docs/content/v1.7.x/connectors/ingestion/workflows/lineage/lineage-workflow-query-logs.md
- openmetadata-docs/content/v1.8.x/connectors/ingestion/workflows/lineage/lineage-workflow-query-logs.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/ingestion/workflows/lineage/lineage-workflow-query-logs.md
I worked on Lineage Workflow Configuration Updation.
#
#
> Doc: Lineage Workflow Configuration Updation

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Domains.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/domain.ts
- openmetadata-ui/src/main/resources/ui/src/components/AppRouter/DomainRouter.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomain/AddDomain.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomain/AddDomain.test.tsx
This issue was introduced when migrating toast notifications across all pages.
#
#
> fix(ui): show toast error on duplicate domain

- ingestion/src/metadata/ingestion/source/database/snowflake/connection.py
- ingestion/src/metadata/ingestion/source/database/snowflake/service_spec.py
- ingestion/tests/unit/test_source_connection.py
Refactoring Snowflake connection to use the new Connection Class
#
#
> MINOR: Update Snowflake Connection

- bin/openmetadata-server-start.sh
> Add more debug logs; improve JVM params to be JVM 21

- ingestion/tests/integration/ometa/test_ometa_service_api.py
> MINOR: Fix pytest 3.10

- openmetadata-mcp/src/main/java/org/openmetadata/mcp/HttpServletSseServerTransportProvider.java
- openmetadata-mcp/src/main/java/org/openmetadata/mcp/MCPStreamableHttpServlet.java
- openmetadata-mcp/src/test/java/org/openmetadata/mcp/McpIntegrationTest.java
- Added semaphore acquire on sessions
- Updated Executor to use virtual threads
#
#
> Added Virtual Threads and Semaphore to control

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/client.py
I worked on adding api logs to track data extraction in powerbi 
#
#
> MINOR: add logs for all powerbi api calls

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/dashboard/powerBIConnection.json
- openmetadata-ui/src/main/resources/ui/src/generated/api/automations/createWorkflow.ts
- openmetadata-ui/src/main/resources/ui/src/generated/api/services/createDashboardService.ts
- openmetadata-ui/src/main/resources/ui/src/generated/api/services/ingestionPipelines/createIngestionPipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/automations/testServiceConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/automations/workflow.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/dashboard/powerBIConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/serviceConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/dashboardService.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/ingestionPipelines/ingestionPipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/testSuitePipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/workflow.ts
I worked on adding option to display source db table name instead of renamed powerbi table name in dataset tables
#
#
> MINOR: pbi display table name from source

- ingestion/src/metadata/sampler/sqlalchemy/databricks/sampler.py
- ingestion/src/metadata/sampler/sqlalchemy/sampler.py
- ingestion/src/metadata/sampler/sqlalchemy/unitycatalog/sampler.py
- ingestion/tests/unit/sampler/sqlalchemy/test_unitycatalog_sampler.py
The unity catalog and databricks connector fails with OOM when a table has an array field which may contain huge data, with this pr we are only getting max 10 items from array instead of fetching all the items form it
#
#
> MINOR: Improve Array Sampler for UC & DBX

- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ServiceBaseClass.ts
Fix failing playwright tests for:
- AutoClassification.spec.ts
- ServiceIngestion.spec.ts
#
#
> Test: Fix the failing playwright for service ingestion

- ingestion/src/metadata/ingestion/source/database/snowflake/connection.py
> MINOR: parametrize get private key for snowflake

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
Update whats new with latest cherry picked PR change.
#
#
> chore(ui): minor update in whats new 1.8.2

- openmetadata-docs/content/v1.7.x/connectors/pipeline/dbtcloud/index.md
- openmetadata-docs/content/v1.7.x/deployment/secrets-manager/how-to-add-a-new-implementation/index.md
- openmetadata-docs/content/v1.8.x/connectors/pipeline/dbtcloud/index.md
- openmetadata-docs/content/v1.8.x/deployment/secrets-manager/how-to-add-a-new-implementation/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/pipeline/dbtcloud/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/secrets-manager/how-to-add-a-new-implementation/index.md
Fixes typos and broken links in the docs
#
- [ x] Documentation
#
> Docs update

- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/importUtils.ts
- openmetadata-ui/src/main/resources/ui/src/components/Certification/Certification.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/AsyncSelectList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/AsyncSelectList/TreeAsyncSelectList.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/DomainSelectableList/DomainSelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/FocusTrap/FocusTrapWithContainer.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/FocusTrap/FocusTrapWithContainer.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/InlineEdit/InlineEdit.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/SelectableList/SelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/TierCard.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/TierCard.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/TierCard.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/tier-card.style.less
- openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/UserTeamSelectableList.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/UserTeamSelectableList/user-team-selectable-list.less
- openmetadata-ui/src/main/resources/ui/src/hooks/useRovingFocus.test.tsx
- openmetadata-ui/src/main/resources/ui/src/hooks/useRovingFocus.ts
- openmetadata-ui/src/main/resources/ui/src/pages/TasksPage/shared/TagSuggestion.tsx
- openmetadata-ui/src/main/resources/ui/src/styles/variables.less
- openmetadata-ui/src/main/resources/ui/src/utils/CSV/CSVUtilsClassBase.tsx
- openmetadata-ui/src/main/resources/ui/yarn.lock
🔧 Problem
Several selection components in the application lacked full keyboard accessibility, making it difficult for users to:
- Navigate options using arrow keys
- Select items using <kbd>Enter</kbd> or <kbd>Space</kbd>
✅ Enhancements
This PR adds roving focus and keyboard support for the following components:
- ✅ Certification selection component
- ✅ Domain selection component
- ✅ Tier selection component
- ✅ User/team selection component
- ✅ Tag selection component
- ✅ Glossary and related terms component
🔑 Key Features
- Enables arrow key navigation through list/virtual list items.
- Ensures pressing <kbd>Enter</kbd> or <kbd>Space</kbd> triggers selection without triggering parent collapsible behaviors.
- Introduces a shared utility (useRovingFocus) to manage keyboard focus behavior …
> Table bulk edit keyboard support

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/Table.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Database/DatabaseSchema/DatabaseSchemaTable/DatabaseSchemaTable.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TableDetailsPageV1/TableDetailsPageV1.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/Database/Database.util.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/TableUtils.tsx
Tab labels like `database -> schema -> table -> schema` were causing confusion replaced first schema with Database Schema and last schema with columns. 
Also changed heading of a column from `Schema names` to `Name`
https://github.com/user-attachments/assets/9b2c70dd-3503-46d8-a1d0-e80028d368e3
#
#
> chore(ui): rename confusing labels

- openmetadata-service/src/main/java/org/openmetadata/service/OpenMetadataApplication.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/ElasticSearchBulkSink.java
- openmetadata-service/src/main/java/org/openmetadata/service/apps/bundles/searchIndex/OpenSearchBulkSink.java
Fixes index name having issues
#
#
> Fix ElasticSearchSink and OpeSearchSink

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts
> fix(test): test case list pagination functionality

- openmetadata-docs/content/partials/v1.8/releases/1.8.1.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/partials/v1.9/releases/1.8.1.md
- openmetadata-docs/content/partials/v1.9/releases/latest.md
- openmetadata-docs/content/v1.8.x/deployment/docker/index.md
- openmetadata-docs/content/v1.8.x/menu.md
- openmetadata-docs/content/v1.8.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.8.x/releases/releases/index.md
- openmetadata-docs/content/v1.8.x/sdk/python/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/sdk/python/index.md
I worked on 1.8.2 Release Update.
#
#
> Docs: 1.8.2 Release Update

- .github/workflows/java-checkstyle.yml
- .github/workflows/py-checkstyle.yml
> Revert #22175 (Update GitHub workflows to ignore changes in docs)

- openmetadata-docs/content/v1.7.x/connectors/pipeline/airflow/configuring-lineage.md
- openmetadata-docs/content/v1.8.x/connectors/pipeline/airflow/configuring-lineage.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/pipeline/airflow/configuring-lineage.md
I worked on Configure Lineage Note Updation.
#
#
> Docs: Configure Lineage Note Updation

- openmetadata-docs/content/partials/v1.8/releases/1.8.2.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/partials/v1.9/releases/1.8.2.md
- openmetadata-docs/content/partials/v1.9/releases/latest.md
- openmetadata-docs/content/v1.8.x/deployment/docker/index.md
- openmetadata-docs/content/v1.8.x/menu.md
- openmetadata-docs/content/v1.8.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.8.x/releases/releases/index.md
- openmetadata-docs/content/v1.8.x/sdk/python/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/sdk/python/index.md
I worked on Release 1.8.3 Updation.
#
#
> Docs: Release 1.8.3 Updation

- openmetadata-ui/src/main/resources/ui/playwright/constant/customProperty.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/customProperty.ts
- openmetadata-ui/src/main/resources/ui/src/constants/CustomProperty.constants.ts
- openmetadata-ui/src/main/resources/ui/src/utils/CustomProperty.utils.test.ts
Fixes #21883 
https://github.com/user-attachments/assets/8a93ea4c-2c47-4ffd-a9d1-a3ec88bf871e
#
#
> Feat(ui): Add "Metric" as an Option for Entity Reference Type Dropdown 

- .github/workflows/claude.yml
> fix: claude workflow token

- openmetadata-ui/src/main/resources/ui/playwright/utils/observabilityAlert.ts
I worked on fixing the flakiness in ObservabilityAlerts.spec.ts
#
#
> Minor: Fix the flakiness in ObservabilityAlerts.spec.ts

- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomiseLandingPageHeader/CustomiseLandingPageHeader.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomiseLandingPageHeader/CustomiseLandingPageHeader.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomiseLandingPageHeader/CustomiseSearchBar.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomiseLandingPageHeader/CustomiseSearchBar.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomiseLandingPageHeader/customise-search-bar.less
- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomizeMyData/CustomizeMyData.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/MyTaskWidget/MyTaskWidget.tsx
> Fix customize search functionality

- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/DataAssetsWidget/DataAssetWidget.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/DataAssetsWidget/DataAssetsWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/DataAssetsWidget/DataAssetsWidget.constants.ts
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/DataAssetsWidget/data-assets-widget.less
> Redesign Data Assets widget

- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DirectoryIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/DriveServiceIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/FileIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SpreadsheetIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/WorksheetIndex.java
> Minor Fix: Add upstreamLineage in Directory, Worksheet, File, Spreadsheet DriveService  Search Indexers

- openmetadata-docs/content/v1.7.x/quick-start/index.md
- openmetadata-docs/content/v1.8.x/quick-start/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/quick-start/index.md
I worked on Quick Start Fix.
#
#
> Docs: Quick Start Fix

- openmetadata-ui/src/main/resources/ui/.eslintrc.yaml
I worked on fixing the eslint error thrown related to jest
#
#
> Minor: Fix eslint error

- bin/openmetadata-server-start.sh
> Fix JVM params

- openmetadata-docs/content/partials/v1.8/releases/1.8.3.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/partials/v1.9/releases/1.8.3.md
- openmetadata-docs/content/partials/v1.9/releases/latest.md
- openmetadata-docs/content/v1.8.x/deployment/docker/index.md
- openmetadata-docs/content/v1.8.x/menu.md
- openmetadata-docs/content/v1.8.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.8.x/releases/releases/index.md
- openmetadata-docs/content/v1.8.x/sdk/python/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/sdk/python/index.md
I worked on 1.8.4 Release Updation.
#
#
> Docs: 1.8.4 Release Updation

- openmetadata-ui/src/main/resources/ui/src/components/Classifications/ClassificationDetails/ClassificationDetails.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/TagsPage/TagsPage.tsx
- Facing console error around Owner and Domain where undefined when page was render initially.
- Solve issue : Since on the initial render we  were not blocking the renderer so it was moving forward to child component without data and we were getting this console issue. Have block the initial render with the already loader present in the page.  
Issue : 
#
#
> fix the console error of domain and owner in classification page

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/SchemaDefinition.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/FrequentlyJoined.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataInsight.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Domains.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ApiCollectionClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/DatabaseClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/MetricClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/testCases.ts
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/KPIWidget/KPIWidget.component.tsx
> Fix failing E2E tests

- openmetadata-service/src/test/java/org/openmetadata/service/util/EntityRelationshipCleanupTest.java
> Fix Flaky Test

- openmetadata-ui/src/main/resources/ui/src/components/MyData/FeedWidget/FeedWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/FollowingWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/MyTaskWidget/MyTaskWidget.tsx
> fix typescript errors for landing page

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DatabaseRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/DatabaseSchemaResourceTest.java
> Fix Database bulkFetcher for service

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Domains.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainPage.component.tsx
> Fix(UI) : Persist Domain custom property

- openmetadata-ui/src/main/resources/ui/src/components/MyData/FeedWidget/FeedWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/MyDataWidget/MyDataWidget.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/RightSidebar/FollowingWidget.tsx
Fix the view-more-count localisation for the widgets.
#
#
> fix(ui): count localisation for widgets

- ingestion/src/metadata/great_expectations/action.py
- ingestion/src/metadata/ingestion/ometa/mixins/tests_mixin.py
> MINOR: pass GX description on test case creation

- openmetadata-ui/src/main/resources/ui/src/components/MyData/GithubStarCard/github-star-card.style.less
> MINOR: fix the github card border color

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/UserDetails.spec.ts
This PR fixes 'Create team with domain and verify visibility of inherited domain in user profile after team removal' test
https://github.com/user-attachments/assets/2c3253c8-f4b2-44e3-801e-c797dc5393f0
#
#
> fix(test): User Details Test

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/QueryEntity.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableQueries/TableQueries.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Database/TableQueries/TableQueries.tsx
Fixes #22480
- I worked on fixing the table query pagination showing incorrect pageSize
Issue : 
https://github.com/user-attachments/assets/053f4a7b-f8b3-4f31-92a2-ecb1f5c95d77
Fixed : 
https://github.com/user-attachments/assets/0956aaef-60b6-4df8-b64e-140da73282ce
#
#
> #22480: fix the table query pagination showing incorrect pageSize

- openmetadata-service/src/main/resources/json/data/eventsubscription/ActivityFeedEvents.json
This fixes the feed updates from the bot.
#
#
> [MINOR][Fix] - Activity Feed Alerts

- openmetadata-ui/src/main/resources/ui/src/utils/sanitize.utils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/sanitize.utils.ts
The Problem
When you type a message in OpenMetadata's activity feed (like a comment) and mention someone using @Accounting, the system should save it as a special link format like <#E::team::Accounting|@Accounting>.
But instead, it was being saved as &lt;#E::team::Accounting|@Accounting&gt; - which is the HTML-encoded version where < becomes &lt; and > becomes &gt;.
p.s this issue appears to be resolved on latest main / sandbox-beta. Might be because of the upgraded react version.
Why This Happened
The system has a security feature called "sanitization" that converts special characters like < and > into safe HTML entities to prevent malicious code. However, this was also affecting the legitimate entity links that OpenMetadata uses internally.
Solution
Smart Sanitization …
> fix(ui):  mentions formatting and AUT failure fix

- openmetadata-ui/src/main/resources/ui/playwright/e2e/nightly/ServiceIngestion.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ServiceBaseClass.ts
> fix(test): ServiceIngestion AUTs

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/AssetsSelectionModal/AssetSelectionModal.interface.ts
- openmetadata-ui/src/main/resources/ui/src/pages/PlatformLineage/PlatformLineage.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/chartsAPI.ts
- openmetadata-ui/src/main/resources/ui/src/utils/Assets/AssetsUtils.ts
Issues covered in PR:
- 404 error for searching any entity which has `/` in it
- On select charts from lineage search receives `Unexpected error`
- Removed deleted entity from LIneage search
https://github.com/user-attachments/assets/cd4457da-f454-48e7-ab13-424b1478009b
Fix:
https://github.com/user-attachments/assets/4b360ffe-82d6-436e-ac98-dc031898c794
#
#
> Fix(UI): LIneage Search issue

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> chore(ui): added whats new details

- openmetadata-docs/content/v1.7.x/deployment/production-ready-requirements.md
- openmetadata-docs/content/v1.8.x/deployment/production-ready-requirements.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/production-ready-requirements.md
I worked on Minimum Requirement Correction for OpenMetadata.
#
#
> Docs: Minimum Requirement Correction for OpenMetadata

- openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.test.tsx
> fix sonar failure for mentions formatting

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataAssetSummaryPanel/DataAssetSummaryPanel.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityInfoDrawer/EntityInfoDrawer.component.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/EntityLineageUtils.tsx
Problem:
https://github.com/user-attachments/assets/f35d78d0-cd88-4cbe-8bd1-4ae3a39fa10b
Fix:
https://github.com/user-attachments/assets/46c5dc6e-db54-46b7-9ac0-1204c23fa39b
#
#
> Fix(ui): Lineage Crash

- openmetadata-service/src/main/resources/json/data/settings/searchSettings.json
- openmetadata-ui/src/main/resources/ui/playwright/utils/searchSettingUtils.ts
Fixes explore count mismatch issue
While testing in test-argo we identified
when we are searching for  term `collection` , it gives count 1 for pipeline entity , but no pipeline getting listed .
On further check identified that this [specific pipeline](https://test-argo.getcollate.io/pipeline/sample_airflow.dim_address_etl) has one glossary Term in its column with name `collection.I.have.dot` , which is causing the count to be 1 (count is coming from dataAsset and the results coming from pipeline_search_index)
The solution we are going for is to not include tags in searchField of searchSettings.json, this is because we have a separate  tagFilter, using which we can use to  search for entities with specific tags
#
#
> Fix explore count mismatch - 2

- ingestion/tests/integration/mysql/conftest.py
> MINOR: Fix mysql pytest version

- conf/openmetadata.yaml
- ingestion/setup.py
- ingestion/src/metadata/utils/secrets/kubernetes_secrets_manager.py
- ingestion/src/metadata/utils/secrets/secrets_manager_factory.py
- ingestion/tests/unit/metadata/utils/secrets/test_kubernetes_secrets_manager.py
- ingestion/tests/unit/metadata/utils/secrets/test_secrets_manager_factory.py
- openmetadata-service/pom.xml
- openmetadata-service/src/main/java/org/openmetadata/service/exception/SecretsManagerException.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/KubernetesSecretsManager.java
- openmetadata-service/src/main/java/org/openmetadata/service/secrets/SecretsManagerFactory.java
- openmetadata-service/src/test/java/org/openmetadata/service/secrets/KubernetesSecretsManagerTest.java
- openmetadata-spec/src/main/resources/json/schema/security/credentials/kubernetesCredentials.json
- openmetadata-spec/src/main/resources/json/schema/security/secrets/secretsManagerProvider.json
- openmetadata-ui/src/main/resources/ui/src/generated/api/automations/createWorkflow.ts
- openmetadata-ui/src/main/resources/ui/src/generated/api/services/createMetadataService.ts
- openmetadata-ui/src/main/resources/ui/src/generated/api/services/ingestionPipelines/createIngestionPipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/applications/app.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/automations/testServiceConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/automations/workflow.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/metadata/openMetadataConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/serviceConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/ingestionPipelines/ingestionPipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/metadataService.ts
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/application.ts
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/testSuitePipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/workflow.ts
- openmetadata-ui/src/main/resources/ui/src/generated/security/secrets/secretsManagerConfiguration.ts
- openmetadata-ui/src/main/resources/ui/src/generated/security/secrets/secretsManagerProvider.ts
> Fix #22511: k8s secret support for Secrets Manager

- openmetadata-docs/content/v1.7.x/connectors/ingestion/workflows/dbt/ingest-dbt-owner.md
- openmetadata-docs/content/v1.8.x/connectors/ingestion/workflows/dbt/ingest-dbt-owner.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/connectors/ingestion/workflows/dbt/ingest-dbt-owner.md
I worked on  indentation Correction in Ingest DBT Owner.
#
#
> Docs: Indentation Correction in Ingest DBT Owner

- openmetadata-docs/content/partials/v1.9/deployment/upgrade/upgrade-prerequisites.md
> doc: add test case breaking change

- openmetadata-docs/content/v1.7.x/applications/reverse-metadata.md
- openmetadata-docs/content/v1.8.x/applications/reverse-metadata.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/applications/reverse-metadata.md
I worked on Reverse Metadata Application First letter capital correction.
#
#
> Docs: Reverse Metadata Application Doc Capital Letter Correction

- openmetadata-ui/src/main/resources/ui/playwright.config.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkImport.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/customProperty.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/metric.ts
- Mertic fix
- Bulk Import Range selector and custom property
- Moved the clipboard permission to specific spec and remove from global
#
#
> PLAYWRIGHT: fix flaky metric and bulk import issue around range selector

- openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
> Minor: Initialise WorkflowHandler in the tests and reorder initialization

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/ExploreTree.spec.ts
Worked on ExploreTree.spec for failing tests
#
#
> fix(test): ExploreTree.spec

- openmetadata-docs/content/v1.8.x/applications/reverse-metadata.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/applications/reverse-metadata.md
I worked on Reverse Metadata, Trino Addition in Supported Table.
#
#
> Docs: Reverse Metadata, Trino Addition in Supported Table

- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
> [Fix - 22431] Add Drop Index to ops

- ingestion/src/metadata/ingestion/source/database/athena/metadata.py
- ingestion/src/metadata/ingestion/source/database/athena/utils.py
- ingestion/src/metadata/ingestion/source/database/glue/metadata.py
- ingestion/tests/unit/topology/database/test_athena_utils.py
- ingestion/tests/unit/topology/database/test_glue.py
…athena
Fix #14830: Ignore non current columns for iceberg tables for glue & athena
#
#
> Fix #14830: Ignore non current columns for iceberg tables for glue & athena

- ingestion/src/metadata/profiler/interface/sqlalchemy/profiler_interface.py
- ingestion/src/metadata/sampler/sqlalchemy/sampler.py
- ingestion/src/metadata/sampler/sqlalchemy/snowflake/sampler.py
Fixes #22144 
This pull request introduces improvements to memory management and simplifies session handling in the SQLAlchemy-based profiler and sampler modules. The changes enhance efficiency, reduce complexity, and ensure proper cleanup of resources. Below is a summary of the most important updates:
- **Garbage Collection in Profiler**: Added explicit garbage collection (`gc.collect()`) in the `compute_metrics_in_thread` method to help manage memory usage during multi-threaded operations.
- **Refactored Session Management in Sampler**: Replaced the manual session tracking (`_active_sessions`) and context manager with a thread-safe session factory (`session_factory`) for cleaner and more efficient session handling.
- **Updated Query Execution**: Modified multiple methods to use …
> Fixes #22144: Enhance memory management and proper cleanup of resources in profiler

- bootstrap/sql/migrations/native/1.8.8/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.8.8/postgres/schemaChanges.sql
Get updated searchSettings on server restart , which were changed in this pr - https://github.com/open-metadata/OpenMetadata/pull/22203 introduced in 1.8.7
#
#
> Add missing migrations for changes related to searchSettings introduced in version 1.8.7

- openmetadata-docs/content/v1.7.x/deployment/docker/index.md
- openmetadata-docs/content/v1.8.x/deployment/docker/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/docker/index.md
I worked on Opensearch Version Updation.
#
#
> Docs: Opensearch Version Updation

- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/SearchIndex.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
1. Skipping Index for multiple column references for foreign key.
2. If any error occurs during this , skip the current doc and proceed.
3. Tests
#
#
> Fix: Skipping Multiple column references by a single column in Foreign Key during Index Creation

- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/EmailMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/FeedMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/GChatMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/MSTeamsMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/formatter/decorators/SlackMessageDecorator.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/EntityUtil.java
- openmetadata-service/src/test/java/org/openmetadata/service/formatter/decorators/EmailMessageDecoratorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/formatter/decorators/SlackMessageDecoratorTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/util/EntityUtilTest.java
- Adds safe encoding to Alert Link for different decorators 
- 
#
#
> Fix alert link issue

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/whatsNewData.ts
> chore(ui): add what's new 1.8.8

- openmetadata-ui/src/main/resources/ui/src/components/DataQuality/AddDataQualityTest/components/AddTestSuitePipeline.tsx
https://github.com/user-attachments/assets/002f2836-92a2-4f19-a843-e0c803b42558
#
#
> Minor(ui) : Changed Edit Ingestion Label  

- ingestion/src/airflow_provider_openmetadata/lineage/backend.py
Fixes #22474, small change
I worked on this issue because it breaks using OM as an airflow lineage backend
#
#
After the changes in https://github.com/open-metadata/OpenMetadata/pull/22474 we've started to experience the following error:
after the fix:
> fixes 22474 (PR): Remove redundant set of braces in `additional_client_config_arguments`

- ingestion/src/metadata/ingestion/source/pipeline/fivetran/metadata.py
Fixes typo in code docs
#
- [ x] Documentation
#
> Fixed typo referring to airbyte in Fivetran file

- ingestion/src/metadata/ingestion/source/database/datalake/metadata.py
Earlier we were logging `Processing table: ABC` even if it was filtered this pr fixes that
#
#
> MINOR: Improve datalake processing table log

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts
- I worked on fixing the lineage cycle playwright failing on 1.8.9
#
#
> PLAYWRIGHT: fix the lineage cycle playwright failing on 1.8.9

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataContractRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/data/DataContractResourceTest.java
- handling OM connection on trigger
- simplifying message on contract status to only show exception messages, not OK/KO redundant results
#
#
> MINOR - Handle OM connection on DC trigger

- openmetadata-spec/src/main/resources/elasticsearch/en/classification_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/jp/classification_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/zh/classification_index_mapping.json
Fixes below error, as sorting is not done on text field
```
"failures": [
{
"shard": 0,
"index": "classification_search_index",
"node": "VHuP14GzTGGIKcW6vX9V1w",
"reason": {
"type": "exception",
"reason": "Elasticsearch exception [type=illegal_argument_exception, reason=Fielddata is disabled on [updatedAt] in [classification_search_index]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [updatedAt] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]"
}
}
]
},
```
#
#
> fix sorting on updatedAt field in classification_search_index

- ingestion/src/metadata/ingestion/source/database/unitycatalog/connection.py
- ingestion/src/metadata/ingestion/source/database/unitycatalog/queries.py
- ingestion/src/metadata/ingestion/source/database/unitycatalog/query_parser.py
- ingestion/src/metadata/ingestion/source/database/unitycatalog/usage.py
Unity Catalog currently uses query history api which requires admin privileges to access, this pr changes it to get query history from `system.query.history` table where admin access is not required
#
#
> MINOR: Improve Unity Catalog Usage

- openmetadata-docs/content/partials/v1.8/releases/1.8.8.md
- openmetadata-docs/content/partials/v1.8/releases/latest.md
- openmetadata-docs/content/partials/v1.9/releases/1.8.8.md
- openmetadata-docs/content/partials/v1.9/releases/latest.md
- openmetadata-docs/content/v1.8.x/deployment/docker/index.md
- openmetadata-docs/content/v1.8.x/menu.md
- openmetadata-docs/content/v1.8.x/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.8.x/releases/releases/index.md
- openmetadata-docs/content/v1.8.x/sdk/python/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/docker/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/menu.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/quick-start/local-docker-deployment.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/releases/releases/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/sdk/python/index.md
I worked on 1.8.9 Release Updation.
#
#
> Docs: 1.8.9 Release Updation

- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/DataModelDetails.interface.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DataModel/DataModels/DataModelsTable.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/ServiceDetailsPage/ServiceDetailsPage.tsx
Fixes #22548 
https://github.com/user-attachments/assets/b7938d01-38db-4510-8f64-be49b25117b2
#
#
> Fix(UI): Incorrect Data model count

- ingestion/src/metadata/ingestion/source/database/databricks/connection.py
- ingestion/src/metadata/ingestion/source/database/unitycatalog/connection.py
- ingestion/src/metadata/ingestion/source/database/unitycatalog/metadata.py
- ingestion/src/metadata/profiler/interface/sqlalchemy/databricks/profiler_interface.py
- ingestion/tests/unit/topology/database/test_databricks.py
This pr fixes the following two issues
- Databricks connector does not support `DESCRIBE HISTORY` [command](https://github.com/open-metadata/OpenMetadata/blob/e99078bb7ade8f3acf943385ea276c2c07fa1163/ingestion/src/metadata/profiler/metrics/system/databricks/system.py#L27) for views hence the profiler workflow would always fail if databricks catalog contains any views - this pr fixes that by skipping metric computation on views
- Databricks test connection would execute `Describe Extended table` query for all the tables available within a random schema during test connection, this happens because we called the inspector.get_table_names method for test connection which would list all tables and views and run the describe command for each of them, this fixed that and implements a better test …
> MINOR: Improve Databricks Profiler & Test Connection

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/PipelineRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
> Minor : missing old pipeline in pipeline widget

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/LoginConfiguration.spec.ts
Fix: Login Configuration Test Failing Due to InputNumber Field Interaction Issues
Issue Description
The LoginConfiguration.spec.ts test was failing with the following error:
Root Cause Analysis
API Timing Issue: The test was checking UI values immediately after clicking save, but the backend API call (PUT /api/v1/system/settings) was still in progress.
InputNumber Component Interaction Issue: The test was using only page.fill() to populate Ant Design's InputNumber components. While this updates the DOM value, it doesn't trigger the necessary React events (blur and onChange) that update the component's internal state. As a result, when the form submits, it sends the old values instead of the newly filled values.
Solution
1. Added API Response Wait
2. Fixed InputNumber Field Interaction
Key …
> fix (test) : Login test failure

- openmetadata-ui/src/main/resources/ui/playwright/utils/permission.ts
The Permissions.spec was failing for below reason,
Added fix by waiting for specific loader
#
#
> fix(test): permissions test fix 

- conf/openmetadata.yaml
- openmetadata-spec/src/main/resources/json/schema/configuration/elasticSearchConfiguration.json
- openmetadata-ui/src/main/resources/ui/src/generated/configuration/elasticSearchConfiguration.ts
- openmetadata-ui/src/main/resources/ui/src/generated/settings/settings.ts
json schema and yaml updated to support embedding model input. Changes needed due to features implemented in [this PR](https://github.com/open-metadata/openmetadata-collate/pull/1922)
#
#
> Enable bedrock embedding service

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/DataQuality/AddTestCaseNewFlow.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts
I worked on fixing data quality-related tests and marking some as `fixme`
TODO:
@ShaileshParmar11 to remove the sample data dependency from the tests.
#
#
> Chore(UI): Fix data quality AUTs

- openmetadata-ui/src/main/resources/ui/src/components/DataAssetRules/DataAssetRules.component.tsx
- openmetadata-ui/src/main/resources/ui/src/locale/languages/de-de.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/es-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/fr-fr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/gl-es.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/he-he.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ko-kr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/mr-in.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/nl-nl.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pr-pr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-pt.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/ru-ru.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/th-th.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/tr-tr.json
- openmetadata-ui/src/main/resources/ui/src/locale/languages/zh-cn.json
- Improve data asset rules page description and translation (via LLM)
- Disable adding and editing rules buttons
#
#
> MINOR - Disable Custom Data Asset Rules

- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/WhatsNewAlert/WhatsNewAlert.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Modals/WhatsNewModal/WhatsNewAlert/WhatsNewAlert.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/GithubStarCard/GithubStarCard.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/GithubStarCard/GithubStarCard.test.tsx
Issue:
https://github.com/user-attachments/assets/6fe91fea-92ea-4adc-9ee8-40b04f2560dd
Solution:
https://github.com/user-attachments/assets/6481239e-c893-47b0-b9e1-510c14c0270f
https://github.com/user-attachments/assets/2bf925ce-4e7c-4306-ae95-9cd5801daf8b
#
#
> Fix(ui) : Release dialog flash 

- openmetadata-ui/src/main/resources/ui/src/components/DataAssetRules/DataAssetRules.component.tsx
COVERAGE: fix the coverage issue due to dataAssetRules changes
#
#
> COVERAGE: fix the coverage issue due to dataAssetRules changes

- openmetadata-ui/src/main/resources/ui/playwright/constant/common.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/AdvancedSearch.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Entity.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/EntityDataConsumer.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/EntityDataSteward.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/EntityDataClass.ts
> Fix(ui): Flaky Tier Count

- openmetadata-ui/src/main/resources/ui/src/components/DataAssetRules/DataAssetRules.component.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/CustomizablePage/CustomizablePage.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/CustomizePage/CustomizePageUtils.ts
> Fix empty chart UI in persona

- common/pom.xml
- openmetadata-mcp/pom.xml
- common-lang3
- comomn-compress 
#
#
> Fix Security Vulnerabilities

- common/pom.xml
- openmetadata-service/pom.xml
- pom.xml
> [MINOR] Fix Vulnerabilities 

- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/CuratedAssetsWidget.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/curated-assets-widget.less
> Fix curated assets description

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataContractRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/rules/RuleEngine.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/data/DataContractResourceTest.java
Found cases where we had mismatches in the link between test suites and contracts when we did not find test suites properly by name. Updating the logic to go by ID and properly validating existing contract information.
Also, test suite summary had info about tests that were removed. Filtering that on the contract validation to ensure we only keep tabs on tests currently available in the suite
#
#
> FIX - Contract mismatch with existing test suites

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataContractRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/data/DataContractResourceTest.java
handling wrong test suite <> contract relationship creating if we PUT DQ expectations to an existing contract
#
#
> FIX - Restore existing DC during PUT

- conf/openmetadata.yaml
- openmetadata-spec/src/main/resources/json/schema/configuration/elasticSearchConfiguration.json
- openmetadata-ui/src/main/resources/ui/src/generated/configuration/elasticSearchConfiguration.ts
- openmetadata-ui/src/main/resources/ui/src/generated/settings/settings.ts
json schema and yaml updated to support embedding model input. Changes needed due to features implemented in [this pr](https://github.com/open-metadata/openmetadata-collate/pull/1922).
#
#
> Minor: add configs for embedding provider

- openmetadata-ui/src/main/resources/ui/src/components/MyData/CustomizableComponents/CustomiseGlossaryTermDetailPage/CustomiseGlossaryTermDetailPage.tsx
- openmetadata-ui/src/main/resources/ui/src/components/MyData/Widgets/CuratedAssetsWidget/CuratedAssetsWidget.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/NavBar/NavBar.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/CustomizableDomainPage/CustomizableDomainPage.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/CustomizeDetailsPage/CustomizeDetailsPage.tsx
1. Remove home text from landing page navbar
2. Disable save when there are no unsaved changes on governance customization pages
https://github.com/user-attachments/assets/d045a9a1-4e23-4c97-9380-82213edbaaba
3. Disable save when there are no unsaved changes on data assets customization pages
https://github.com/user-attachments/assets/1362f9ec-4f4b-4fd8-a6ee-17d7a2e39cd6
#
#
> Remove home text from landing page and disable save for customize pages

- openmetadata-ui/src/main/resources/ui/src/locale/languages/pt-br.json
> Fixes #22847: Update PT-BR locale owner-plural-with-colon attribute

- .github/workflows/mysql-nightly-e2e.yml
- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
- .github/workflows/postgresql-nightly-e2e.yml
- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/yarn.lock
> Upgrade playwright version to 1.54.2 (latest) to support indexedDb storageState

- openmetadata-docs/content/v1.7.x/deployment/secrets-manager/index.md
- openmetadata-docs/content/v1.8.x/deployment/secrets-manager/index.md
- openmetadata-docs/content/v1.9.x-SNAPSHOT/deployment/secrets-manager/index.md
> DOCS - Fix secrets typo

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
- ingestion/src/metadata/ingestion/source/dashboard/powerbi/models.py
- ingestion/tests/unit/test_powerbi_table_measures.py
> issue-22425: PowerBI parse expression along with measure

- openmetadata-docs/content/v1.9.x-SNAPSHOT/applications/data-retention.md
The retention period app cleans Activity Threads as well, but it was not mentioned in the docs. 
I have updated the `data-retention.md` file to include `activityThreadsRetentionPeriod`.
#
#
> MINOR: Update `data-retention.md` file to include `activityThreadsRetentionPeriod`

- .github/workflows/sync-docs-v1.yml
> Update the sync-doc workflow

- openmetadata-docs/content/v1.10.x-SNAPSHOT/collate-menu.md
- openmetadata-docs/content/v1.10.x-SNAPSHOT/how-to-guides/data-quality-observability/profiler/spark-engine/external-configuration.md
- openmetadata-docs/content/v1.10.x-SNAPSHOT/how-to-guides/data-quality-observability/profiler/spark-engine/ui-configuration.md
- openmetadata-docs/content/v1.9.x/collate-menu.md
- openmetadata-docs/content/v1.9.x/how-to-guides/data-quality-observability/profiler/spark-engine/external-configuration.md
- openmetadata-docs/content/v1.9.x/how-to-guides/data-quality-observability/profiler/spark-engine/ui-configuration.md
> Fix the docs collate content failure

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/UserRepository.java
> Removed lastLoginTime from change Description

- ingestion/src/metadata/ingestion/source/pipeline/airflow/connection.py
---
Fix #22164: Fix airflow compatibility issue with version 2.2.5
Problem
When testing connection with Airflow 2.2.5, the connection test fails with the following error:
Pipeline details access error: (psycopg2.errors.UndefinedColumn) column serialized_dag.data_compressed does not exist
This occurs because the data_compressed column was introduced in Airflow 2.3.0 and doesn't exist in earlier versions like 2.2.5.
Root Cause
The test_pipeline_details_access function in connection.py was querying SerializedDagModel with .first(), which attempts to fetch all columns from the table. Since
data_compressed doesn't exist in Airflow 2.2.5's schema, this caused a SQL error.
Solution
Modified the query to explicitly select only the dag_id column instead of fetching all columns:
result = …
> Fix #22164: Fix airflow compatibility issue with version 2.2.5

- openmetadata-docs/content/v1.9.x/how-to-guides/admin-guide/alerts.md
While setting up alerts and selecting destinations, we get the option to choose `advanced configurations` such as `Headers`, `Query Params`, and `HTTP Method`. These settings were not mentioned in the documentation, so I have updated the `alerts.md` file to include these details.
#
#
> MINOR: Update `alerts.md` to include `Advanced Configurations`

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/PersonaFlow.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/persona.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Users/UserProfilePersona/UserProfilePersona.component.tsx
- openmetadata-ui/src/main/resources/ui/src/hooks/useApplicationStore.ts
1. Fixed the issue of default persona is not visible in Default Persona section in User Profile
2. Fixed the playwright test as earlier version of test was checking if the default persona is visible on the dropdown popover when we click on user, not inside user profile page.
https://github.com/user-attachments/assets/d44b0d32-ad67-4b7f-8f8a-da2b034f3e7c
https://github.com/user-attachments/assets/09a61675-a7c1-40c2-8e26-4d5b01956c6b
#
#
> fix(ui): default persona in user profile

- ingestion/src/metadata/ingestion/source/dashboard/powerbi/metadata.py
- precede source table name before pbi table name(visible on UI) while creating lineage with db service
#
#
> MINOR: precede source table name before pbi table name

- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/RuleEvaluator.java
- openmetadata-service/src/test/java/org/openmetadata/service/security/policyevaluator/RuleEvaluatorTest.java
Fixes 
Setup
https://github.com/user-attachments/assets/4afb7be4-d66e-493e-8081-95009df3decc
Working:
https://github.com/user-attachments/assets/c906bbfc-0d18-43ea-8ff6-0d2ebfdbfc2d
Screenshots of incident manager and test suites
#
#
> Fix Bug: Match All Tags giving a NPE when the resource doesn't have tags

- openmetadata-docs/content/v1.10.x-SNAPSHOT/collate-ai/index.md
- openmetadata-docs/content/v1.9.x/collate-ai/index.md
I worked on Natural Language Search Feature Updation.
#
#
> Docs: Natural Language Search Feature Updation

- conf/openmetadata.yaml
> Fix - Do not able RDF by default

- openmetadata-ui/src/main/resources/ui/src/utils/LogsClassBase.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/LogsClassBase.ts
fixed redirection issue from logs view page
https://github.com/user-attachments/assets/18f556e3-70de-4f24-a20f-df48fee57dc1
#
#
> fix: issue with redirection from logs view page to data quality page.

- openmetadata-service/src/main/java/org/openmetadata/service/resources/system/ConfigResource.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/system/ConfigResourceTest.java
> Remove configuration for APIs for auth or authorizer

- openmetadata-ui/src/main/resources/ui/src/pages/Persona/PersonaListPage/PersonaPage.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/Persona/PersonaListPage/PersonaPage.tsx
https://github.com/user-attachments/assets/ab5e966c-ca3b-4dca-8dc7-7770952c7de2
#
#
> Fix pagination for Persona listing

- .github/workflows/yarn-coverage.yml
This pull request introduces a minor update to the GitHub Actions workflow configuration by enabling manual triggering of the SonarCloud + Jest Coverage workflow.
* Added the `workflow_dispatch` event to `.github/workflows/yarn-coverage.yml` to allow the workflow to be run manually from the GitHub UI.
#
#
> Minor: Add workflow_dispatch option in yarn-coverage.yml workflow

- conf/openmetadata.yaml
Starting load test: 300000 requests with 10000 concurrent connections
Target URL: http://localhost:8585/
------------------------------------------------------------
Load Test Results:
------------------------------------------------------------
Total requests: 300000
Concurrent requests: 10000
Total time: 83.36 seconds
Throughput Metrics:
------------------------------
Overall RPS (Requests Per Second): 3598.84
Successful RPS: 3598.84
Failed RPS: 0.00
Request Status Summary:
Successful requests: 300000 (100.00%)
Failed requests: 0 (0.00%)
Error requests: 0 (0.00%)
Response Time Statistics:
Average: 2.170 seconds
Median: 1.986 seconds
Min: 0.474 seconds
Max: 7.728 seconds
Standard deviation: 1.039 seconds
Throughput Over Time (1-second windows):
---------------------------------------- …
> Improve Performance

- ingestion/examples/sample_data/dashboards/dashboardDataModels.json
- ingestion/examples/sample_data/mysql/tables.json
- ingestion/src/metadata/ingestion/models/custom_basemodel_validation.py
- ingestion/src/metadata/ingestion/models/custom_pydantic.py
- ingestion/src/metadata/utils/fqn.py
- ingestion/tests/unit/models/test_custom_basemodel_validation.py
- ingestion/tests/unit/models/test_custom_pydantic.py
- ingestion/tests/unit/test_fqn.py
- ingestion/tests/unit/utils/test_fqn_special_chars.py
Fixes https://github.com/open-metadata/OpenMetadata/issues/21677
This pull request introduces a robust, configuration-driven system for handling special character transformations in entity names, such as table and column names, across the ingestion and FQN (Fully Qualified Name) building pipeline. The new approach replaces the previous hardcoded logic with a scalable, model-aware mechanism. Additionally, it enhances test coverage for FQN building with special characters and updates sample data accordingly.
The most important changes are:
* Refactored the name transformation logic in `custom_basemodel_validation.py` to use a hybrid, configuration-driven system. This includes the introduction of `TransformDirection`, a lazy-initialized `TRANSFORMABLE_ENTITIES` mapping, and recursive …
> Fixes #21677: Refactor and enhance the entity name transformation logic

- ingestion/tests/cli_e2e/dashboard/tableau/redshift.yaml
- ingestion/tests/cli_e2e/dashboard/tableau/tableau.yaml
- ingestion/tests/cli_e2e/test_cli_tableau.py
> Improve: Tableau e2e Tests

- .github/workflows/mysql-nightly-e2e.yml
- .github/workflows/playwright-mysql-e2e.yml
- .github/workflows/playwright-postgresql-e2e.yml
- .github/workflows/postgresql-nightly-e2e.yml
- openmetadata-ui/src/main/resources/ui/package.json
- openmetadata-ui/src/main/resources/ui/playwright.okta.config.ts
- openmetadata-ui/src/main/resources/ui/playwright/login-flows/tests/okta-login.spec.ts
- openmetadata-ui/src/main/resources/ui/src/pages/LoginPage/SignInPage.tsx
> [WIP] Login flow e2e tests

- common/pom.xml
- docker/docker-compose-ingestion/docker-compose-ingestion.yml
- docker/docker-compose-openmetadata/docker-compose-openmetadata.yml
- docker/docker-compose-quickstart/Dockerfile
- docker/docker-compose-quickstart/docker-compose-postgres.yml
- docker/docker-compose-quickstart/docker-compose.yml
- ingestion/Dockerfile
- ingestion/operators/docker/Dockerfile
- ingestion/pyproject.toml
- openmetadata-airflow-apis/pyproject.toml
- openmetadata-clients/openmetadata-java-client/pom.xml
- openmetadata-clients/pom.xml
- openmetadata-dist/pom.xml
- openmetadata-mcp/pom.xml
- openmetadata-service/pom.xml
- openmetadata-shaded-deps/elasticsearch-dep/pom.xml
- openmetadata-shaded-deps/opensearch-dep/pom.xml
- openmetadata-shaded-deps/pom.xml
- openmetadata-spec/pom.xml
- openmetadata-ui/pom.xml
- pom.xml
> chore(release): Prepare Branch for `1.10.0-SNAPSHOT`

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/LargeGlossaryPerformance.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTermTab/GlossaryTermTab.test.tsx
This pr includes
-  Fixed child term loss on load of next 50 terms in Infinite scroll
- Improving playwright cover 
- Fixed unit test
#
#
> Fix(ui): prevent child term state loss on infinite scroll

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/domain.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
> chore(ui): playwright fixes 

- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
> Fixes: Snowflake Tags Ingestion

- ingestion/src/metadata/ingestion/lineage/sql_lineage.py
- ingestion/src/metadata/ingestion/source/database/unitycatalog/lineage.py
> MINOR: Improve UC lineage exception handling

- openmetadata-ui/src/main/resources/ui/src/rest/miscAPI.ts
- I worked on fixing the markdown data not visible in right panels of Applications and Services
- Failure reason was the bundler being changed from Webpack to Vite
- Reason previously we copy every thing from public folder all the internal files to dist folder, but with the vite change we were just copy the public folder and pasting it directly. which includes the inner folders as well. Due to which we weren't able to acces the route properly.
Fix :  
#
#
> fix the markdown data not visible in right panels

- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Applications/McpApplication.md
Fixes duplicate documentation about mcp endpoints. 
further details on https://openmetadata.slack.com/archives/C02B6955S4S/p1756197401088549 
#
#
> Fixes duplicated documentation about the mcp endpoints

- openmetadata-service/src/main/java/org/openmetadata/service/Entity.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/APICollectionRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/APIEndpointRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataContractRepository.java
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apis/APICollectionResource.java
- openmetadata-service/src/main/java/org/openmetadata/service/resources/apis/APIEndpointMapper.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchIndexFactory.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/SearchUtil.java
- openmetadata-service/src/main/java/org/openmetadata/service/search/indexes/APICollectionIndex.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/ServiceHierarchyCleanup.java
- openmetadata-service/src/test/java/org/openmetadata/service/apps/bundles/dataRetention/DataRetentionAppTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/apis/APICollectionResourceTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/data/DataContractResourceTest.java
- Limit which entities are allowed to have Data Contracts, specially around expectations that can be set (semantic, schema and DQ)
- Also there was a typo on an entity name API_COLLECTION
#
#
> MINOR - Add BE validations on entity types for Data Contracts

- openmetadata-service/src/main/java/org/openmetadata/service/migration/api/MigrationWorkflow.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/context/MigrationOps.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/context/MigrationWorkflowContext.java
- openmetadata-service/src/main/java/org/openmetadata/service/util/OpenMetadataOperations.java
- openmetadata-service/src/test/java/org/openmetadata/service/OpenMetadataApplicationTest.java
- During Ops: Compute all the context as we were already doing, to keep it properly stored in the db.
- During tests: we will only compute initial and last migration context
#
#
> MINOR - Simplify migration context computing during tests

- openmetadata-service/src/main/java/org/openmetadata/service/socket/OpenMetadataAssetServlet.java
This pull request introduces improved frontend routing support for specific paths in the `OpenMetadataAssetServlet`. Now, requests to certain whitelisted frontend routes will serve the main index file instead of returning a 404 error, ensuring smoother navigation for single-page application routes.
**Frontend routing improvements:**
* Added a static list `WHITELISTED_PATHS` (currently `/docs` and `/signin`) to specify frontend routes that should serve the index file instead of a 404 error.
* Updated the `doGet` method to check for requests to whitelisted paths; if a request matches and would otherwise result in a 404, the servlet now responds with the index file and a 200 status.
* Implemented a helper method `isWhitelistedPath` to determine if a request URI matches any whitelisted path. …
> chore(BE): update response code for docs & signin page

- openmetadata-service/src/main/java/org/openmetadata/service/security/policyevaluator/CreateResourceContext.java
> Fix Resource Context - Invalid Entity Type being passed

- openmetadata-ui/src/main/resources/ui/playwright.config.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkImport.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Users.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/glossary.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/importUtils.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/user.ts
I worked on fixing flaky playwright test
- Users.spec
- Bulk Import.spec
- Glossary.spec (Also skipped test around "Term should stay approved when changes made by reviewer") need to fix it from BE as it's constantly failing in AUT's around the workflow.
#
#
> Chore(ui): fix flaky playwright test

- openmetadata-ui/src/main/resources/ui/playwright.config.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/DataQuality/AddTestCaseNewFlow.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/Tour.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/domain.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/GlossaryTerms/tabs/AssetsTabs.component.tsx
> playwright: fixed flakiness in AddTestCaseNewFlow, Tour & Domains

- ingestion/src/metadata/ingestion/source/database/bigquery/lineage.py
> MINOR: Add support for clone queries in bigquery

- openmetadata-service/src/main/resources/dataInsights/config.json
> MINOR: Fix data insight index for multidomain

- openmetadata-ui/src/main/resources/ui/src/constants/Services.constant.ts
- I worked on removing the `Spark` connector support from UI
#
#
> MINOR: remove the spark connector support from UI

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataProductRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/domains/DataProductResourceTest.java
We had an immutability issue when sorting lists, plus we had to properly handle different types on the bulk GET
#
#
> FIX - Data Product bulk addition with different types

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/LineageRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/jdbi3/LineageRepositoryTest.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/lineage/LineageResourceTest.java
Many times lineage ingestion fails because we have stricter validation about column level lineage. i.e. if the column passed in the add lineage request does not exist then we raise and error and does not allow lineage to get created.
but the issue is when the column is deleted from the source and if the column lineage was already created, right now there is no way to clean that lineage up hence we lead into error while adding new col lineage to such case.
hence this pr loosens up the validation logic and does the job of cleaning such lineage instead of marking it as failed. 
#
#
> MINOR: Fix column lineage validation

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SearchSettings.spec.ts
> chore(ui): fix search settings playwright

- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
- ingestion/tests/unit/topology/database/test_snowflake.py
- openmetadata-spec/src/main/resources/json/schema/entity/services/connections/database/snowflakeConnection.json
- openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Snowflake.md
- openmetadata-ui/src/main/resources/ui/src/generated/api/automations/createWorkflow.ts
- openmetadata-ui/src/main/resources/ui/src/generated/api/services/createDatabaseService.ts
- openmetadata-ui/src/main/resources/ui/src/generated/api/services/ingestionPipelines/createIngestionPipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/automations/testServiceConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/automations/workflow.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/database/snowflakeConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/connections/serviceConnection.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/databaseService.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/services/ingestionPipelines/ingestionPipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/testSuitePipeline.ts
- openmetadata-ui/src/main/resources/ui/src/generated/metadataIngestion/workflow.ts
Fixes #22452 
#
#
New feature
or decision-making process is reflected in the issue.
> Fixes #22452: [Snowflake] Add custom host support for `View in Snowflake` source url

- openmetadata-ui/src/main/resources/ui/src/components/DataContract/AddDataContract/AddDataContract.test.tsx
> MINOR: fix the unit test for the DataContract

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/EntityRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/databases/TableResourceTest.java
During the restoration of soft deleted entities, inherited fields are also taken into consideration.
Fixes the issue where a soft deleted entity has data product and an inherited domain from parent.
https://github.com/user-attachments/assets/6498d5ac-550d-40c5-bab3-ef7ebd2067e2
#
#
> Restore deleted entities will take inherited fields into consideration

- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Domain/DomainTabs/DocumentationTab/DocumentationTab.test.tsx
Fixes 
Fixes #23232
Fixed an issue where an incorrect type was being passed to the description editor for the data product, which was causing the creation of an incorrect entityLink for the upload API.
https://github.com/user-attachments/assets/642fd0a2-d41f-4081-9de9-1136e67f14c7
#
#
> Fix #23232 Users with Data Product edit permission unable to upload images due to missing Domain resource permission

- openmetadata-spec/src/main/resources/elasticsearch/en/data_products_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/en/security_service_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/en/test_case_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/en/test_case_resolution_status_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/en/test_case_result_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/en/test_suite_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/jp/data_products_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/jp/security_service_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/jp/test_case_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/jp/test_case_resolution_status_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/jp/test_case_result_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/jp/test_suite_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/data_products_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/security_service_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/test_case_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/test_case_resolution_status_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/test_case_result_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/test_suite_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/zh/data_products_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/zh/security_service_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/zh/test_case_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/zh/test_case_resolution_status_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/zh/test_case_result_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/zh/test_suite_index_mapping.json
> Add missing tier mapping

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataContracts.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataAssets/DataAssetsHeader/DataAssetsHeader.test.tsx
- openmetadata-ui/src/main/resources/ui/src/mocks/DataContract.mock.ts
- I worked on fix contract status button not visible if Persona is set having contract tab with the entity
- Added Unit and Playwright Test to back it.
Issue : 
Resolved : 
#
#
> fix contract status button not visible in persona having contract tab

- openmetadata-ui/src/main/resources/ui/src/setupTests.js
- openmetadata-ui/src/main/resources/ui/src/utils/ServiceUtilClassBase.ts
- openmetadata-ui/src/main/resources/ui/src/utils/date-time/DateTimeUtils.ts
- openmetadata-ui/src/main/resources/ui/src/vite-env.d.ts
This pull request updates the logic for detecting the development environment in the `EnvironmentUtils.ts` utility file to better support Vite's environment variables. The change improves compatibility and reliability when determining the current environment mode.
Environment detection improvements:
* Updated the `development` variable to first check `import.meta.env.MODE` (used by Vite) for the development mode, and fallback to `process.env.NODE_ENV` if necessary. (`openmetadata-ui/src/main/resources/ui/src/utils/EnvironmentUtils.ts`)
#
#
> fix(ui): pick right mode env production / dev

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataQualityAndProfiler.spec.ts
This pull request refines the way test case descriptions are filled in the Playwright E2E tests for the Data Quality and Profiler pages. The changes ensure that the description fields are targeted more precisely within their respective forms, which improves test reliability and reduces the risk of interacting with the wrong input elements.
**Improvements to test reliability and selector precision:**
* In the table test case, the description field is now filled by first scoping the locator to the `test-case-form-v1` form using `getByTestId`, rather than using a global locator.
* In the column test case, the description field is similarly filled by scoping to the `test-case-form-v1` form, enhancing selector specificity.
* When editing a test case, the description field is now filled by …
> playwright: fixed failing test case for description box selection.

- openmetadata-spec/src/main/resources/elasticsearch/ru/api_collection_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/api_endpoint_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/chart_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/classification_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/container_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/dashboard_data_model_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/dashboard_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/data_products_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/database_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/database_schema_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/directory_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/file_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/glossary_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/glossary_term_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/metric_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/mlmodel_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/pipeline_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/query_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/search_entity_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/spreadsheet_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/stored_procedure_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/table_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/tag_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/topic_index_mapping.json
- openmetadata-spec/src/main/resources/elasticsearch/ru/worksheet_index_mapping.json
Added entityStatus and reviewers in Russian Index Mappings
#
#
> Added entityStatus and reviewers property in ru index mappings

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DataContractRepository.java
- openmetadata-service/src/test/java/org/openmetadata/service/resources/data/DataContractResourceTest.java
- support chart
- Add missing schema validation for dashboard data model and APIs
#
#
> MINOR - Handle chart for Data Contract and add schema validations

- openmetadata-service/src/test/java/org/openmetadata/service/resources/data/DataContractResourceTest.java
- openmetadata-spec/src/main/resources/json/schema/entity/data/dataContract.json
- openmetadata-ui/src/main/resources/ui/src/generated/api/data/createDataContract.ts
- openmetadata-ui/src/main/resources/ui/src/generated/entity/data/dataContract.ts
Add more consumer granularity to the Data Contract schema.
#
#
> MINOR - Update contract security schema

- ingestion/src/metadata/ingestion/lineage/models.py
Lineage dialect postgres added to greenplum
#
#
> Lineage dialect postgres added to greenplum

- openmetadata-service/src/test/java/org/openmetadata/service/resources/feeds/FeedResourceTest.java
> Fix test flakiness in FeedResourceTest

- conf/openmetadata.yaml
> Increase Max Server threads

- openmetadata-ui/src/main/resources/ui/playwright.config.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/IncidentManager.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/incidentManager.ts
> playwright: fixed incident manager flaky test

- openmetadata-ui/src/main/resources/ui/src/components/Explore/ExplorePage.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/EntityPopOverCard.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/PopOverCard/EntityPopOverCard.tsx
- openmetadata-ui/src/main/resources/ui/src/rest/contractAPI.ts
- openmetadata-ui/src/main/resources/ui/src/rest/queryAPI.ts
- openmetadata-ui/src/main/resources/ui/src/utils/EntityUtilClassBase.ts
Integrated API calls for fetching notifications and bots instead of showing "No data found" on hover in the activity feed. Fixed the redirection issue when clicking on a bot name in the activity feed.
Fixes #23225 
https://github.com/user-attachments/assets/e1fa2b1f-84d1-42b8-8c43-23fa2dee0401
https://github.com/user-attachments/assets/2b2561cb-0a55-4ca1-8cff-5786d80cc0e5
#
> Fix: integrate API for notifications and bots update bot details redirection

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/ExploreSortOrderFilter.spec.ts
Fixes ExploreSortOrder.spec
#
#
> fix(test): AUT for ExploreSortOrder 

- ingestion/src/metadata/ingestion/source/database/stored_procedures_mixin.py
> Handle `None` value of  `procedure_name` in stored proc lineage processing

- openmetadata-ui-core-components/src/main/resources/ui/vite.config.ts
> chore(ui): update terser to esbuild

- openmetadata-ui/src/main/resources/ui/playwright/utils/customProperty.ts
- openmetadata-ui/src/main/resources/ui/src/constants/PageHeaders.constant.ts
- openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.test.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsUtils.test.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/GlobalSettingsUtils.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/SwMessenger.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/SwTokenStorage.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/SwTokenStorageUtils.test.ts
Fixes #22947 
https://github.com/user-attachments/assets/353911b8-cbfe-42ef-b662-dafa71701157
#
#
> fix(ui): update breadcrumbs in custom property page

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/IngestionBot.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/auth.setup.ts
This pull request refactors the Playwright E2E test setup for the Ingestion Bot flow to streamline authentication and resource management. The main improvements involve replacing manual login logic with a shared utility, ensuring proper cleanup of browser resources, and improving test reliability.
**Test authentication and resource management improvements:**
* Replaced manual admin login using `AdminClass` with the shared `performAdminLogin` utility in `IngestionBot.spec.ts`, simplifying authentication and reducing code duplication. [[1]](diffhunk://#diff-eecfdd8564db84ba71a982ab1b4eccf8479ec8e8ab5bc27ee442aeadbf54d745L16-R17) [[2]](diffhunk://#diff-eecfdd8564db84ba71a982ab1b4eccf8479ec8e8ab5bc27ee442aeadbf54d745L34-R42)
* Ensured proper cleanup by calling `afterAction()` after tests and …
> chore(test): fix ingestion bot tests

- bootstrap/sql/migrations/native/1.9.9/mysql/postDataMigrationSQLScript.sql
> Minor my sql migration

- openmetadata-ui/src/main/resources/ui/playwright/utils/bot.ts
> fix data contract failing flaky test

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Tags.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/tag/ClassificationClass.ts
- openmetadata-ui/src/main/resources/ui/src/pages/TagPage/TagPage.tsx
- fix the tags playwright test
- Also fix the tag page breaking of owner and domain failure, due to data accessing before it is defined.
#
#
> chore(ui): fix the tags playwright test

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SearchIndexApplication.spec.ts
> chore(ui): fix playwright for search index app

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Lineage.spec.ts
- fix lineage cycle playwright test
#
#
> chore(ui): fix lineage cycle playwright test

- openmetadata-service/src/main/java/org/openmetadata/service/resources/services/ingestionpipelines/IngestionPipelineResource.java
> MINOR: Enable Log streaming for ingestion pipelines

- bootstrap/sql/migrations/native/1.9.11/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.9.11/postgres/schemaChanges.sql
- openmetadata-service/src/main/java/org/openmetadata/service/migration/mysql/v1911/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/postgres/v1911/Migration.java
- openmetadata-service/src/main/java/org/openmetadata/service/migration/utils/v1911/MigrationUtil.java
- openmetadata-service/src/main/resources/json/data/settings/searchSettings.json
add entityType.keyword aggregation in searchSettings.json
#
#
> add entityType.keyword aggregation in searchSettings.json

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/IngestionBot.spec.ts
- fix ingestion bot playwright timeout issue but removing unwanted steps.
#
#
> chore(ui): fix ingestion bot playwright timeout issue

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SearchSettings.spec.ts
> fix(test): search preview

- ingestion/src/metadata/ingestion/source/database/databricks/client.py
- ingestion/src/metadata/ingestion/source/database/databricks/queries.py
- ingestion/src/metadata/ingestion/source/pipeline/databrickspipeline/metadata.py
> Fixes: Databricks Pipeline Lineage Flow

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkEditEntity.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/BulkImport.spec.ts
- Use the in file data creation, rather than getting from pre-requesties
#
#
> PLAYWRIGHT: improve playwright test of bulk import/edit

- openmetadata-ui/src/main/resources/ui/playwright/utils/common.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/entity.ts
- openmetadata-ui/src/main/resources/ui/src/components/Certification/Certification.component.tsx
- Supported infinite scroll on Certification List
Issue : 
https://github.com/user-attachments/assets/5a4efe0b-6e87-43b0-a889-af13c81862a0
Fix : 
https://github.com/user-attachments/assets/df89a6d6-78b7-4336-b58c-6fa21230aace
#
#
> supported scroll in certification popover list

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/ApiServiceRest.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/MlFlowIngestionClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ServiceBaseClass.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/serviceIngestion.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Services/ServiceConfig/ConnectionConfigForm.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/FormBuilder/FormBuilder.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/TestConnection/TestConnection.tsx
- openmetadata-ui/src/main/resources/ui/src/pages/AddServicePage/AddServicePage.component.tsx
This reverts commit b1a1cd89a743b321b2726e5c85f66408c8687dc8
#
#
> Revert "Fix(ui): Force Test Connection (#21734)"

- INCIDENT_RESPONSE.md
- THREAT_MODEL.md
- bootstrap/sql/migrations/native/1.10.0/mysql/schemaChanges.sql
- bootstrap/sql/migrations/native/1.10.0/postgres/schemaChanges.sql
- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/ListFilter.java
> Add threat model and incident response

- openmetadata-ui/src/main/resources/ui/src/components/DataContract/ContractExecutionChart/ContractExecutionChart.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataContract/ContractExecutionChart/ContractExecutionChart.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/DataContract/ContractExecutionChart/ContractExecutionChart.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataContract/ContractExecutionChart/ContractExecutionChartTooltip.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataContract/ContractExecutionChart/ContractExecutionChartTooltip.test.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataContract/ContractExecutionChart/contract-execution-chart.less
- openmetadata-ui/src/main/resources/ui/src/utils/DataContract/DataContractUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DataContract/DataContractUtils.ts
- modify contract execution chart to occupy full space and the charts bar's should be starting from left and side and not center.
Previous :
Current. : 
#
#
>  Modify ContractExecutionChart to occupy full space and chart bar's start from left

- openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomainForm/AddDomainForm.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/MUIFormItemLabel/MUIFormItemLabel.tsx
- openmetadata-ui/src/main/resources/ui/src/utils/formUtils.tsx
> Change helper text background and foreground colors for Domain type

- openmetadata-ui/src/main/resources/ui/src/components/DataContract/ContractExecutionChart/ContractExecutionChart.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/DataContract/ContractExecutionChart/ContractExecutionChart.test.tsx
- openmetadata-ui/src/main/resources/ui/src/constants/Color.constants.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DataContract/DataContractUtils.test.ts
- openmetadata-ui/src/main/resources/ui/src/utils/DataContract/DataContractUtils.ts
- I worked on supporting running status in contract execution chart
#
#
> supporting running status in contract execution chart

- openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomain/add-domain.less
`block-editor-wrapper` has 1px border-width and 8px border-radius, so `bar-menu-wrapper` needs to be 7px border-radius, so that the inner curve of `block-editor-wrapper` and outer curve of `bar-menu-wrapper` are properly touched
Full field view
With both 8px border radius ❌ (_bg is red only for demo purpose_)
With 8px and 7px border radius ✅ (_bg is red only for demo purpose_)
#
#
> Update editor border radius

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Teams.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/team.ts
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamsHeaderSection/TeamsInfo.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/Settings/Team/TeamDetails/TeamsHeaderSection/TeamsInfo.test.tsx
- I worked on supporting owner operation with editOwner and editALL for teams
#
#
> support owner operation with editOwner and editALL for teams

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Glossary.spec.ts
- openmetadata-ui/src/main/resources/ui/src/components/Glossary/AddGlossary/AddGlossary.component.tsx
- I worked on Fixing creation of Glossary when domain is selected.
- Fix the popover being scrolled for ower, reviewer and domains
Issue : 
https://github.com/user-attachments/assets/0eeafe7d-730f-4952-a712-d75c68eefc83
Fix : 
https://github.com/user-attachments/assets/6bd31ce6-9380-461b-9cba-d7578c27bca1
Uploading Screen Recording 2025-10-01 at 12.21.00 PM.mov…
#
#
> Fix creation of Glossary when domain is selected

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/DataContracts.spec.ts
- I worked on fixing data contract flaky test are data asset button check
#
#
> chore(ui): fix data contract flaky test are data asset button check

- openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomainForm/AddDomainForm.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/IconPicker/IconPicker.interface.ts
- openmetadata-ui/src/main/resources/ui/src/components/common/IconPicker/MUIIconPicker.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/atoms/navigation/useSearch.tsx
Setting searchbox width in icon picker through props
|Before | After |
|-|-|
|<img width="437" height="560" alt="Screenshot 2025-10-01 at 2 39 11 PM" src="https://github.com/user-attachments/assets/1f470834-8a64-4baf-b19f-681c7f6148a9" />|<img width="437" height="560" alt="Screenshot 2025-10-01 at 2 38 29 PM" src="https://github.com/user-attachments/assets/0457170b-8728-45a7-a3cf-e67a416d0f7f" />|
#
#
> Set searchbox width through props

- openmetadata-ui/src/main/resources/ui/src/components/Domain/AddDomainForm/AddDomainForm.component.tsx
- openmetadata-ui/src/main/resources/ui/src/components/common/MUISelect/MUISelect.tsx
> Add placeholder for domain field

- openmetadata-ui/src/main/resources/ui/src/components/AppRouter/AppRouter.tsx
> Chore(UI): fix collate build

- openmetadata-sdk/src/main/java/org/openmetadata/sdk/fluent/Tables.java
> MINOR: Fix HIERARCHYID failing test

- ingestion/src/metadata/ingestion/source/database/snowflake/metadata.py
- ingestion/src/metadata/ingestion/source/database/sql_column_handler.py
Handle snowflake `NoSuchTableError` exception when columns permissions are missing and add common exception handling for such cases.
#
#
> Add better handling of columns not found or permission issue exceptions

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Features/CustomizeDetailPage.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/SearchIndexApplication.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/persona.ts
- openmetadata-ui/src/main/resources/ui/src/pages/Persona/PersonaListPage/PersonaPage.tsx
> playwright: update loader and pagination size for CustomizeDetailPage spec

- ingestion/src/metadata/workflow/base.py
- ingestion/src/metadata/workflow/workflow_resource_metrics.py
> Fixes #22406: Add workflow resource utilisation metrics for better troubleshooting

- bootstrap/sql/migrations/native/1.10.0/mysql/postDataMigrationSQLScript.sql
- bootstrap/sql/migrations/native/1.10.0/postgres/postDataMigrationSQLScript.sql
Before Migration 
Postgre:
mysql:
After Migration:
Postgre:
mysql:
#
#
> App Screenshots Migration

- openmetadata-sdk/pom.xml
> Vulnerability fix for org.json

- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/CustomizeWidgets.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Flow/PersonaFlow.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/e2e/Pages/Users.spec.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/customizeLandingPage.ts
- openmetadata-ui/src/main/resources/ui/playwright/utils/persona.ts
1. KPI Widget
2. NavigationBlocker.spec.ts
3. Users.spec.ts
4. PersonaFlow.spec.ts
5. CuratedAssets.spec.ts
#
#
> Playwright: Fix failing AUT tests

- openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/DomainRepository.java
> Minor:refactor fetching assetsCount for individual fields

- openmetadata-ui-core-components/src/main/resources/ui/tsconfig.json
> Chore(UI): Revert module resolution

- .github/workflows/py-nox-ci.yml
- ingestion/setup.py
~Bump `datamodel-code-generator` to latest version to resolve errors introduces with `pydantic` 2.12.0.~
Pin down `pydantic` to 2.11.* or lower due to breaking changes in 2.12.0.
```
make generate
Makefile:142: warning: overriding commands for target `build-ingestion-base-local'
Makefile:137: warning: ignoring old commands for target `build-ingestion-base-local'
Running Datamodel Code Generator
Make sure to first run the install_dev recipe
rm -rf ingestion/src/metadata/generated
mkdir -p ingestion/src/metadata/generated
python scripts/datamodel_generation.py
Traceback (most recent call last):
File "/Users/mohittilala/projects/OpenMetadata/scripts/datamodel_generation.py", line 43, in <module>
main(args)
File "/Users/mohittilala/projects/OpenMetadata/env/lib/python3.9/site-packages/datamode …
```
> Pin `pydantic` to <2.12.0
